### ISSUE TITLE
Add Usage documentation

### ISSUE THREAD

**Issue by thedrow** [valyala/fasthttp#10]
Other than https://github.com/TechEmpower/FrameworkBenchmarks/pull/1765/files I don't see usage examples of this library.
A full tutorial will allow others to adopt this library more easily.

**Comment by valyala** [comment]
Basic usage documentation must appear soon.

Thanks for the idea, @thedrow .

**Comment by valyala** [comment]
There are [some examples](https://godoc.org/github.com/valyala/fasthttp#pkg-examples) available in [the documentation](https://godoc.org/github.com/valyala/fasthttp).

**Comment by valyala** [comment]
Added [switching from net/http to fasthttp](https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp) section into README.

**Comment by abacaj** [comment]
Getting better with the docs / examples, maybe time to have a small dedicated site to fasthttp for better display of docs / examples 😀

**Comment by valyala** [comment]
Yeah, this site will be created with [github pages](https://pages.github.com/).

**Comment by abacaj** [comment]
@valyala if you need styling help for a theme or something similar, I can lend a hand - I was a front end dev for about a year.

**Comment by valyala** [comment]
Cool! @abacaj , could you create initial site version using [github pages](https://pages.github.com/) under your account? Then I could review and publish it.
Currently I have no idea what contents this site should contain other than README.md :)

**Comment by valyala** [comment]
[Examples](https://github.com/valyala/fasthttp/tree/master/examples) folder has been added.

**Comment by valyala** [comment]
Added [helloworldserver example](https://github.com/valyala/fasthttp/tree/master/examples/helloworldserver).

Closing the bug, since it looks like documentation minimum has been reached.

**Comment by thedrow** [comment]
Thanks.
