### ISSUE TITLE
zero-copy response writes possible?

### ISSUE THREAD

**Issue by karlseguin** [valyala/fasthttp#1002]
Hi,
It seems like we have a choice between setting a response body that cannot be mutated after the handler (e.g., via `SetBodyRaw`) or a body that can be muted  after the handler (e.g., via `SetBody) but with the cost of fasthttp copying the body.

Further, unless I'm mis-reading the code (which is very possible), it seems like there's possibly even more copying going on internally (into a bufio.Writer).

I'm wondering if there's a way to streamline this (or if this has been explored before and deemed unnecessary)?

For example, we build the body into our own pooled buffer, and it would be nice to go from this directly into conn.Write with a way for us to know when this is done so that we can release the pool. Something like:

```
func handler(ctx *fasthttp.RequestCtx) {
  resp := checkout(...) // implements io.Writer and io.Closer
   ...
   ctx.SetWriter(resp) 
}
```

Since our buffer implements `io.Closer`, it would be possible for `fasthttp` to signal that the buffer can be released back into the pool.

**Comment by erikdubbelboer** [comment]
The closest you can get is using `SetBodyStream` which should be easy if your buffer is also an `io.Reader`. `SetBodyStream` will also call `Close` if your buffer implements `io.Closer`. This will also bypass the `bufio.Writer` as `io.Copy` (used to copy from your buffer to the socket) will check if the output is an `io.ReaderFrom` which `bufio.Writer` is and call that instead which should make the `net.TCPConn` read directly from your buffer.
