### ISSUE TITLE
I can't  shutdown my http server 

### ISSUE THREAD

**Issue by roverliang** [valyala/fasthttp#1003]
**fasthttp version:** v1.23.0

Below is my test code,  when I send a http request,  `server.GetOpenConnectionsCount` value is not 1 , why ? 

I cannot close my service because its number of connections is not zero

```go
package main

import (
	"fmt"
	"github.com/valyala/fasthttp"
	"os"
	"os/signal"
	"syscall"
	"time"
)

func RequestHandler(ctx *fasthttp.RequestCtx) {
	_, _ = fmt.Fprintf(ctx, "hello %s", "world")
	return
}

var stopCh = make(chan os.Signal)

func main() {
	server := &fasthttp.Server{
		Handler: RequestHandler,
	}
	signal.Notify(stopCh, syscall.SIGTERM, syscall.SIGINT)
	go func() {
		for {
			time.Sleep(1 * time.Second)
			fmt.Println(server.GetOpenConnectionsCount())
		}
	}()

	go func() {
		_ = server.ListenAndServe("0.0.0.0:8082")
	}()

	select {
	case <-stopCh:
		_ = server.Shutdown()
	}
}
```

**Comment by roverliang** [comment]
This may not be a bug, but it needs explicit explanation. When keepalive is not closed by default. `ctx.SetConnectionClose()` should be called manually at the end of each request

**Comment by erikdubbelboer** [comment]
This is documented in `Shutdown`: https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Server.Shutdown
```
Shutdown does not close keepalive connections so its recommended to set ReadTimeout to something else than 0. 
```

**Comment by milosgajdos** [comment]
I've observed a behaviour where I'm setting the `ReadTimeout` as per the docs and then calling `server.Shutdown`. The thing I'm noticing is, the server read deadline does not seem to be firing which makes me think something else might be amiss here.

```Go
...
...
	server := &fasthttp.Server{
		Handler:      RequestHandler,
		IdleTimeout:  60 * time.Second,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
	}
	
	app := &App{
		server: server,
	}
	
	// start the app server here
	
	timeoutCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	return app.Close(timeoutCtx)

```

App close method:
```Go
// Close gracefully shuts down the server.
func (a *App) Close(ctx context.Context) error {
	errChan := make(chan error, 1)
	go func() {
		select {
		case <-ctx.Done():
		case errChan <- a.server.Shutdown():
		}
	}()

	select {
	case <-ctx.Done():
		return fmt.Errorf("server shut down: %v", ctx.Err())
	case err := <-errChan:
		return err
	}
}
```

Now when I `Close` the app which in turn triggers the `server.Shutdown` I'd expect the server to exit before the context deadline exceeds (ReadTimeout < Context Deadling), but that's not the case which makes me wonder what am I missing or rather what's actually going on here -- I'm suspecting `IdleTimeout` is kicking in and overriding `ReadTimeout` for whatever reason?

```
2021/06/18 10:40:28 error: server shut down: context deadline exceeded
```

**Comment by erikdubbelboer** [comment]
You are correct, I have added `IdleTimeout` to the documentation for `Shutdown`. It will wait on both.

**Comment by milosgajdos** [comment]
IMO, the real question here is. Should it wait on both?
