### ISSUE TITLE
Got 404 not found when requesting Gitlab API

### ISSUE THREAD

**Issue by IshiKura-a** [valyala/fasthttp#1004]
Hello, I'm currently use fasthttp to the information of branch by gitlab api. Here's a strange problem:

When I tried to get the information for branches such as `release/3.47.0`, I got `{"error":"404 Not Found"}`. However, when I try the same url and token by `net/http` or directly use `curl`, I got the correct information. Next, I tried branch `master`, all of the above 3 methods return the correct answer.

The url used is `https://{server}/api/v4/projects/{projectId}/repository/branches/release%2F3.47.0` (`release/3.47.0` needs to be transformed into `release%2F3.47.0` here).

The `curl` command is:
```bash
curl -H "PRIVATE-TOKEN: xxx" https://{server}/api/v4/projects/{projectId}/repository/branches/release%2F3.47.0
```

The code using `net/http` is:
```go
func get1(requestUrl string, token string) []byte {
	client := &http.Client{}
	reqest, err := http.NewRequest("GET", requestUrl, nil)

	reqest.Header.Add("PRIVATE-TOKEN", token)
	if err != nil {
		panic(err)
	}

	response, _ := client.Do(reqest)
	body, err := ioutil.ReadAll(response.Body)
	defer response.Body.Close()

	return body
}
```

The code using fasthttp is
```go
func get2(requestUrl string, token string) []byte {
	request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()

	defer func() {
		fasthttp.ReleaseResponse(response)
		fasthttp.ReleaseRequest(request)
	}()

	request.Header.SetMethod(`GET`)
	request.Header.Set(`PRIVATE-TOKEN`, token)
	request.SetRequestURI(requestUrl)

	if err := fasthttp.Do(request, response); err != nil {
		return nil
	}

	data := response.Body()
	return data
}
```

**Comment by erikdubbelboer** [comment]
fasthttp does some path normalizing by default, to turn it off you can define your own client with this option disabled:
```go
// Somewhere that can be reused (don't do this for every request or you won't be able to use keep-alive connections.
c := &fasthttp.Client{
	DisablePathNormalizing: true,
}

// Then just use that client:
if err := c.Do(request, response); err != nil {
```

Another issue you have:
```go
data := response.Body()
return data
```
This is not possible. After you `fasthttp.ReleaseResponse(response)` the `[]byte` of the body might be reused for other requests or responses.
Either make a `copy` of the bytes or turn them into a string for example.

**Comment by IshiKura-a** [comment]
This works! Thanks a lot
