### ISSUE TITLE
Error when serving connection "host"<->"client": EOF

### ISSUE THREAD

**Issue by l1ving** [valyala/fasthttp#1006]
I'm not sure how to debug this exactly, the majority of logged errors in the last 24 hours have been just "EOF".
```
liv@fs-over-http:~$ cat foh-2021-04-11.log | grep "EOF" | wc -l
42720
liv@fs-over-http:~$ cat foh-2021-04-11.log | wc -l
43951
```

Server configuration: https://github.com/l1ving/fs-over-http/blob/5865251d5297ea7d2a5fca6d81b5e66bdd076004/main.go#L60

Production server: https://i.l1v.in (running with TLS on https)

I have also grepped my server logs for my own IP range.. I haven't gotten this error myself even once and have no idea how to reproduce it.

**Comment by erikdubbelboer** [comment]
Seems like you have some bad clients connecting to your server that close the connection before the server expects it. These could for example be bots check your server. Did you have anyone complain about your website not working?

**Comment by l1ving** [comment]
No complaints that I know of, no.

I suppose the issue would be on the bots end? I'll filter it from my logs if it's a non-issue

**Comment by erikdubbelboer** [comment]
Is there a proxy in front of fasthttp?

**Comment by l1ving** [comment]
Nope

**Comment by erikdubbelboer** [comment]
Then it can really only be from bad behaving clients, especially if nobody complains. There is no known issue in fasthttp which would otherwise cause this.

**Comment by l1ving** [comment]
Good to know, thank you. Since opening the issue I haven't had any actual users report issues, I assume it's just from website scanning bots then.
