### ISSUE TITLE
longer request/response header values will cause error 'error when reading response headers: small read buffer'

### ISSUE THREAD

**Issue by fooofei** [valyala/fasthttp#1007]
Error:
``` 
error when reading response headers: small read buffer. Increase ReadBufferSize. Buffer size=8192, ...
```
How:
```
 1 set fasthttp's `Client`  `ReadBufferSize`  to `8*1024`  
 2 then request to a Demo Server, the Server response a header with value length longer than 8192
 3 then the client will meet the error
```
Why:

  fasthttp's `Server` and `Client` struct have `ReadBufferSize` field.

  fasthttp will create a `bufio.Reader` with the size of   `ReadBufferSize` to read the underlying  TCP connection.

  in `github.com/valyala/fasthttp/header.go`: 1321
```go
func (h *ResponseHeader) tryRead(r *bufio.Reader, n int) error
```
called `mustPeekBuffered` will retrive `bufio.Reader`'s memory cached buffer.

If a http response header value longer than `bufio.Reader`'s cache size, then here got an error 
```
need more data: cannot find trailing lf
```
`EXPECT` fasthttp continue read more data from TCP connection, but fasthttp stop parse, return an error to caller.

the same issue with 
```go
func (h *RequestHeader) tryRead(r *bufio.Reader, n int) error 
```

Involved version: 

fasthttp <= v1.23.0

**Comment by erikdubbelboer** [comment]
This is correct and documented behavior. See [Client.ReadBufferSize](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Client.ReadBufferSize) which says:
```
// Per-connection buffer size for responses' reading.
// This also limits the maximum header size.
```
