### ISSUE TITLE
Add option to set value of RemoteAddr/RemoteIP by middleware

### ISSUE THREAD

**Issue by lafriks** [valyala/fasthttp#1008]
Maybe pointer to  `net.Addr` could be added to `RequestCtx` set that it could be set by middleware that if set would be used by `RequestCtx.RemoteAddr()` instead of one from `c`.

This would allow implementing more robust and generic middlewares for handling `X-Real-IP` and/or `X-Forwarded-For` etc

**Comment by erikdubbelboer** [comment]
A pull request is welcome. I'm not sure if a pointer to a `net.Addr` or a method to set it would be better.

**Comment by lafriks** [comment]
I can create a PR if idea is acceptable. I meant adding private variable to struct `RequestCtx` and adding method something like `SetRemoteAddr` that would set it.

**Comment by lafriks** [comment]
@erikdubbelboer PR submitted
