### ISSUE TITLE
Adding MIME types for Static Files (Downloading APK on Android issue)

### ISSUE THREAD

**Issue by moneszarrugh** [valyala/fasthttp#1011]
[Issue on gofiber](https://github.com/gofiber/fiber/issues/1295) which internally uses fasthttp.

------------

My feature request is regarding serving static files.

https://docs.gofiber.io/#static-files

There is an issue when I'm serving `.apk` files and downloading them from Chrome mobile browser on Android. They download as `.apk.zip` and not just `.apk`.

Apparently, the issue is related to MIME types. Refer to https://serverfault.com/questions/501562/configure-iis-7-0-to-download-apk/501564

If you allow setting custom MIME type it would be very useful. Thanks

**Comment by erikdubbelboer** [comment]
Fasthttp uses `https://golang.org/pkg/mime/#TypeByExtension` which uses your local system's mime.types file(s). If you fix those files the issue will be fixed.
