### ISSUE TITLE
fasthttp -> net/http adapter

### ISSUE THREAD

**Issue by Kukunin** [valyala/fasthttp#1012]
Hello there, and thank you for the awesome package. 

I have a web application, that uses iris-v12. And it has literally two hot endpoints that are executed 99% of the time. And those endpoints are slim, so the underlying HTTP layer matters. The load can be easily 50k rps. I did benchmarks, and fasthttp is 1.5x faster for my usage, which is great.

Now, the question. I don't want to migrate the whole application, since I don't need high performance there. I need to migrate only these two endpoints. 

I found https://github.com/valyala/fasthttp/blob/master/fasthttpadaptor/adaptor.go but it seems it's the opposite of what I need. 
I believe that the adapter wouldn't fit, since `iris` still will handle the hot endpoints, and then requests will go to `fasthttp`. This chain, I believe won't be faster than just `iris`.

My plan is to have fasthttp listening to all requests, do the basic routing, and if it's not those two endpoints, forward the request to the iris framework, so it can handle it. This way I'll have hot parts use fasthttp while the rest of the slow API will remain unchanged. Has somebody done a similar approach? 

I hope that you can validate my plan and advice any directions/examples of how to implement such adapter. 

Thank you

**Comment by erikdubbelboer** [comment]
This is exactly what the adapter you linked to does:
```go
app := iris.New()

app.Get("/", func(ctx iris.Context) {
	ctx.Writef("Hello from iris")
})

adaptor := fasthttpadaptor.NewFastHTTPHandler(app)
slashFast := []byte("/fast")

err := fasthttp.ListenAndServe(":8080", func(ctx *fasthttp.RequestCtx) {
	if bytes.Equal(ctx.Path(), slashFast) {
		ctx.WriteString("hello from fasthttp")
	} else {
		adaptor(ctx)
	}
})
if err != nil {
	panic(err)
}
```

**Comment by Kukunin** [comment]
Thank you, that's exactly what I was looking for
