### ISSUE TITLE
return the serial data of Josn

### ISSUE THREAD

**Issue by Mars0817** [valyala/fasthttp#1013]
When concurrent, return the serial data of Josn？

Eg:
{"id":"www","status":{"code":200,"msg":"ok"}}id":"123","name":"wwww"}

**Comment by erikdubbelboer** [comment]
Can you explain?

**Comment by Mars0817** [comment]
When concurrent requests occur, the two returned results overlap.

The return result of log output is JSON
Eg:
{"id":"www","status":{"code":200,"msg":"ok"}}id":"123","name":"wwww"}

This is the result of two requests

**Comment by erikdubbelboer** [comment]
You are probably reusing byte slices returned by fasthttp where you shouldn't. For example using the result of [`ctx.PostBody()`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestCtx.PostBody) while the response handler has already returned. Or if you're doing request using the bytes returned by [`response.Body()`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Response.Body) after calling `fasthttp.ReleaseResponse` on it.

**Comment by Mars0817** [comment]
Every request will be process

resp := fasthttp.AcquireResponse()
defer fasthttp.ReleaseResponse(resp)

The normal request returns the correct result
When concurrent requests occur, the two returned results overlap.

**Comment by erikdubbelboer** [comment]
I'm going to have to see your relevant code to see what you are doing wrong.

**Comment by Mars0817** [comment]
type Request struct {
	header  Header
	timeout int
	logMode uint8
}

func (rq Request) request(method string, url string, reqBody interface{}) (respBody []byte, statusCode int, err error) {
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	for k, v := range rq.header {
		req.Header.Set(k, v)
	}
	req.Header.SetMethod(method)
	req.SetRequestURI(url)

	var requestBodyByte []byte
	switch reflect.ValueOf(reqBody).Kind() {
	case reflect.String:
		requestBodyByte = []byte(reflect.ValueOf(reqBody).String())
	case reflect.Slice:
		requestBodyByte = reflect.ValueOf(reqBody).Bytes()
	default:
		requestBodyByte, err = json.Marshal(reqBody)
		if err != nil {
			return respBody, statusCode, fmt.Errorf("json.Marshal error: %v", err)
		}
	}

	rl := reqLog{
		Method:   method,
		Url:      url,
		Header:   rq.header,
		ReqBody:  reqBody,
		ResBody:  "",
		Duration: "nil",
		Err:      "nil",
	}

	req.SetBody(requestBodyByte)

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp) 

	err = fasthttp.DoTimeout(req, resp, time.Second*time.Duration(rq.timeout))
	if err != nil {
		if rq.logMode&2 == 2 {
			rl.Err = err.Error()
			_ = json.Unmarshal(resp.Body(), &rl.ResBody)
			log.Info(rl)
		}

		return respBody, statusCode, err
	}
	respBody = resp.Body()
	statusCode = resp.StatusCode()


	return respBody, statusCode, nil
}

**Comment by erikdubbelboer** [comment]
You can not return `respBody`. Those bytes will be reused once your function returns because of the `defer fasthttp.ReleaseResponse(resp) `. You either need to make a copy or better release the response after you are done with the body.

**Comment by Mars0817** [comment]
The results are copied

respBody = resp.Body()

**Comment by erikdubbelboer** [comment]
That is not a copy. That will just return a slice that points to the same backing array. Please read up on how slices work in Go.

**Comment by Mars0817** [comment]
All right, thanks!
