### ISSUE TITLE
Fasthttp - Custom filehandler

### ISSUE THREAD

**Issue by pschakravarthi** [valyala/fasthttp#1017]
Hi,

How to serve files using customer file handler that allows to preprocess file content.

Example : 
if the request is coming as http://examples.com/static/abcd the application should serve the binary file /var/www/fasthttp/binary/kbabcd.bin

**Comment by erikdubbelboer** [comment]
You can use [`fasthttp.ServeFile`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#ServeFile)
