### ISSUE TITLE
Does fasthttp have requests Contexts ?

### ISSUE THREAD

**Issue by xiangnanscu** [valyala/fasthttp#1018]
Hello, I'm new to fasthttp and I come across this man says (https://github.com/labstack/echo/issues/1617#issuecomment-692699827):

`if you run a long-running query through an HTTP endpoint, and the client closes the connection, you don't get any kind of signal, so the query will keep running on the background`

Is that true?

**Comment by erikdubbelboer** [comment]
That is true, this has nothing to do with fasthttp. It is the way sockets work. You need to perform an operation on the socket to get an update on the state of the socket. If your query is running and you aren't trying to write to the socket or read from it your program won't know if the connection was closed.
