### ISSUE TITLE
TLS performance vs. nginx for WebSocket server

### ISSUE THREAD

**Issue by Tozuko** [valyala/fasthttp#1020]
I'm trying to run a very low-latency WebSocket server for a fast-paced real-time browser game and currently am using fasthttp and the fasthttp port of gorilla/websockets (https://github.com/fasthttp/websocket). (I may later try to replace this with https://github.com/nhooyr/websocket or https://github.com/gobwas/ws.)

In an attempt to minimize latency as much as possible, I'd like to see if I can remove any reverse proxies from the equation, like nginx. However, I know nginx performs fast TLS termination, so I'm trying to figure out if average user latency will likely be better with or without nginx.

(I know the best option is just to benchmark, but I wanted to ask a few questions first before diving in.)

Someone asked about SSL performance in this fasthttp issue in 2018: https://github.com/valyala/fasthttp/issues/438

There are two comments saying nginx should be much faster for TLS termination:

>I can already tell you that nginx is going to be a lot fast, somewhere around 3x to 10x faster. This has nothing to do with fasthttp and is completely because of the Golang crypto stack being written in Go. This means it doesn't have the decades of performance optimizations that other stacks like OpenSSL have.

>Almost everything will run faster if you terminate TLS on load-balancer/nginx cache.

However, this 2016 article claims they saw lower latency even with net/http's `http.ListenAndServeTLS` compared to nginx: https://blog.gopheracademy.com/advent-2016/tls-termination-bench/

Cloudflare, known for their production Go experience, wrote this in 2016 as well: https://blog.cloudflare.com/exposing-go-on-the-internet/

>Back when crypto/tls was slow and net/http young, the general wisdom was to always put Go servers behind a reverse proxy like NGINX. That's not necessary anymore!
>
>At Cloudflare we recently experimented with exposing pure Go services to the hostile wide area network. With the Go 1.8 release, net/http and crypto/tls proved to be stable, performant and flexible.

Any general suggestions or advice here? Thanks.

**Comment by dgrr** [comment]
It might be ok to use NGINX, is something you need to test. The Golang SSL is not as fast as you can expect. And for WebSocket, I would use https://github.com/fasthttp/fastws.

**Comment by erikdubbelboer** [comment]
My advise would also be to benchmark this yourself. In my experience Go TLS is still slower than nginx, but the overhead of having nginx in between might be make it worse again. There is no way to tell without actually benchmarking your specific situation.
