### ISSUE TITLE
Invalid request header setting 

### ISSUE THREAD

**Issue by axing42** [valyala/fasthttp#1025]
```go
func home(ctx *fasthttp.RequestCtx) {

	ctx.Request.Header.Set("Content-Type", "text/html; charset=utf-8")
	ctx.WriteString("<h1>hello</h1>")
}
func main() {
	var m = func(ctx *fasthttp.RequestCtx) {
		switch string(ctx.Path()) {
		case "/":
			home(ctx)
		}
	}
	println("http server listen:127.0.0.1:1234/")
	fasthttp.ListenAndServe(":1234", m)
}
```
![6IGPS~XQ0CKEGK7AMQ4$KL](https://user-images.githubusercontent.com/56167651/118233618-b8167000-b4c4-11eb-8bb1-7cc1509d6c50.png)

Cannot be set to text/html

**Comment by axing42** [comment]
Using the HTTP library is normal😒

**Comment by dgrr** [comment]
https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestCtx.SetContentType

**Comment by axing42** [comment]
> https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestCtx.SetContentType

thank 🤣🤣

**Comment by erikdubbelboer** [comment]
You're setting the content-type of `ctx.Request` which is the incoming request. What you want is:
```go
ctx.Response.Header.Set("Content-Type", "text/html; charset=utf-8")
```

**Comment by erikdubbelboer** [comment]
Or indeed even better `ctx.SetContentType("Content-Type", "text/html; charset=utf-8")`
