### ISSUE TITLE
Suggestion: FSCompressedFileSuffix

### ISSUE THREAD

**Issue by kataras** [valyala/fasthttp#103]
I have to know if you are willing to change [fasthttp.FSCompressedFileSuffix (fs.go:256)](https://github.com/valyala/fasthttp/blob/master/fs.go#L256) to a Var in order to change it.

Or make a function which change it and add the -fasthttp.gz at the end, I want to change it to ` iris-fasthttp.gz` .

Also I think that the [FSHandlerCacheDuration](https://github.com/valyala/fasthttp/blob/master/fs.go#L260) it's too small, maybe better to make it 3-5 minutes ?

Thanks!!

**Comment by valyala** [comment]
`FSHandlerCacheDuration` is actually an expiration duration for inactive file handlers. This means that file handlers for frequently read files won't be closed. IMHO, 10 seconds is enough for the default value. Will update documentation do be less misleading.

Additionally, file handlers' expiration duration may be adjusted via [FS.CacheDuration](https://godoc.org/github.com/valyala/fasthttp#FS).

As for `FSCompressedFileSuffix`, I'll add the corresponding `FS.CompressedFileSuffix` tunable.

**Comment by valyala** [comment]
Done.

**Comment by kataras** [comment]
> Additionally, file handlers' expiration duration may be adjusted via FS.CacheDuration.

Yes I already set it to 5 minutes,  as you said is propably a bad value I will change it to 20 seconds then.

Thanks for adding the `CompressedFileSuffix` !

I have another question for `Server`  instance, If ` &fasthttp.Server{Name: "iris"}`   [*1](https://github.com/kataras/iris/blob/master/config/server.go#L15)[*2](https://github.com/kataras/iris/blob/master/server/server.go#L26) and do something like this: 
` fmt.Println(requestCtx.Response.String())` on a request handler it outputs:
```
HTTP/1.1 200 OK
**Server: fasthttp**
Date: Mon, 23 May 2016 13:17:20 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 17

```


 [Here is a runnable example](https://github.com/iris-contrib/examples/blob/master/log_response_custom_middleware/main.go).
But when I open it from the browser,  the header is setted correctly to ` iris` , when you have time could you explain me what's happening (is a bug? is something I did wrong?)  The only solution I found to this is by setting the response's header on every request.

**Comment by valyala** [comment]
This looks like a bug. Will investigate it

**Comment by valyala** [comment]
Fixed

**Comment by kataras** [comment]
Thanks you :)
