### ISSUE TITLE
URI.RequestURI() behavior is not same as url.ReqeustURI()

### ISSUE THREAD

**Issue by morefreeze** [valyala/fasthttp#1030]
```go
// RequestURI returns RequestURI - i.e. URI without Scheme and Host.
func (u *URI) RequestURI() []byte {
```

I have no idea RequestURI will return url encoded path or not. I pass a uri like "/foo/%2Fbar" (with literally percent and 2 hex, in this case %2F is `/` ), I hope fasthttp pass it as proxy(with DisablePathNormalizing = true) to server who can receive as the same ("/foo/%2Fbar") instead "/foo/bar" or "/foo//bar"

```go
p := "/foo/%2Fbar"
u := fasthttp.URI{}
u.SetPath(p)
// u.DisablePathNormalizing = true
fmt.Printf("%v %v %v\n", string(u.RequestURI())) // /foo/bar, /foo/%2Fbar if last line uncomment

uu := url.URL{Path: p}
fmt.Printf("%v\n", uu.RequestURI()) // /home/%252Fbar
```

I agree with `normalizePath` remove duplicate slashes, /./ parts and so on, but I don't think `decodeArgAppendNoPlus` should go first, because you don't know which / comes from %2F.

**Comment by erikdubbelboer** [comment]
I'm confused at what you want exactly.

With this code:
```go
package main

import (
  "fmt"

  "github.com/valyala/fasthttp"
)

func main() {
  fasthttp.ListenAndServe(":8080", func(ctx *fasthttp.RequestCtx) {
    fmt.Printf("%q\n", ctx.RequestURI())
  })
}
```
And running:
```sh
curl -v 'localhost:8080/foo/%2Fbar'
```
It prints:
```
"/foo/%2Fbar"
```
which seems exactly what you want?

**Comment by morefreeze** [comment]
> I'm confused at what you want exactly.
> 
> With this code:
> 
> ```go
> package main
> 
> import (
>   "fmt"
> 
>   "github.com/valyala/fasthttp"
> )
> 
> func main() {
>   fasthttp.ListenAndServe(":8080", func(ctx *fasthttp.RequestCtx) {
>     fmt.Printf("%q\n", ctx.RequestURI())
>   })
> }
> ```
> 
> And running:
> 
> ```shell
> curl -v 'localhost:8080/foo/%2Fbar'
> ```
> 
> It prints:
> 
> ```
> "/foo/%2Fbar"
> ```
> 
> which seems exactly what you want?

I appreciate your example, but I lose in reading source code. Could you give me some hint about where is setting request path. I can't figure out how ctx.Reqeust set /foo/%2Fbar. BTW, I found there are read header and body in Server.serveConn, however I found nowhere to setPath
