### ISSUE TITLE
Consider using copy-less []byte/string conversion

### ISSUE THREAD

**Issue by tliron** [valyala/fasthttp#1031]
Many of the optimizations in fasthttp are based on using byte arrays instead of strings. That is wise!

However, there is an assumption that translating these into strings (or back) requires a copy and should thus be discouraged.

With some caveats, this is not true. There are in fact reliable ways to avoid copying. Please see the code I use, [here](https://github.com/tliron/kutil/blob/main/util/string.go). I urge you to consider these or similar functions to handle conversion, and perhaps to benchmark the memory use and total throughput accordingly.

(The major caveat is the use of "unsafe". Some projects decide, as a matter of principle, to not use it. However, for the same reason fasthttp doesn't try to copy Go's http library, I believe that "unsafe" would be acceptable here.)

For completion, here are some references to code and discussion on this topic:

* https://go101.org/article/unsafe.html
* https://github.com/golang/go/issues/25484
* https://github.com/golang/go/issues/19367
* https://golang.org/src/strings/builder.go#L45

**Comment by dgrr** [comment]
fasthttp already avoids string copies. Checkout [this](https://github.com/valyala/fasthttp/search?q=b2s) and [this](https://github.com/valyala/fasthttp/search?q=s2b).

**Comment by tliron** [comment]
Ah, thanks, I missed that because it's private. Why are these not public APIs and part of the documentation?

**Comment by dgrr** [comment]
Usually, is better if the user doesn't have access to those functions. To avoid library malfunctions I'd say.

**Comment by tliron** [comment]
Hm, I think that in this case because this library is so focused on performance and non-copy that you would want to allow users to have the same benefits. In my case, because these are private I had to essentially use a duplicate of them.

Please consider making them public and documented! They are an important contribution of this project.

**Comment by erikdubbelboer** [comment]
I would rather not export these functions. They are very easy to misuse (still using the string why mutating the byte slice etc). And misuses aren't always easily noticeable. Since the functions are really small I rather have people copy them into their code and hopefully seeing what they do so they understand what they do and what can go wrong.

**Comment by tliron** [comment]
Alright. Well, final suggestion: write about this in the "Tricks with []byte buffers" section in the README.

I just think this is a very important optimization technique and it's too bad that many fasthttp users aren't even aware of it.

**Comment by erikdubbelboer** [comment]
I agree, it would be good to mention this there. A pull request for this is always welcome, I'm not very good at writing documentation 🙈

**Comment by tliron** [comment]
Thank you for your agreement, I will try to send a doc PR soon!
