### ISSUE TITLE
1.25.0: fasthttpadaptor duplicate content-type with go stdlib embed

### ISSUE THREAD

**Issue by james-d-elliott** [valyala/fasthttp#1033]
So in 1.25.0 we noticed the `content-type` header with things using the fasthttpadaptor not only had two headers, but the first one was always text/plain when used in conjunction with go stdlib embed.

This is specifically (for an unknown reason) caused by this change:

https://github.com/valyala/fasthttp/commit/b2f111bd987535e673df3172e34ec06fed46ae0f#diff-e6ec50a76313ea3e95c7fa583dd3909aae602d31e74d55631becdab50949a519R95

I have put together an example application that will showcase the issue which I've attached [here](https://github.com/valyala/fasthttp/files/6527456/example.zip).

Edit: Also as a note, part of the above commit was reverted theoretically unintentionally here:

https://github.com/valyala/fasthttp/commit/04cde74c419c81185c47e28683da50c8a152d01d#diff-e6ec50a76313ea3e95c7fa583dd3909aae602d31e74d55631becdab50949a519L71

https://github.com/valyala/fasthttp/commit/04cde74c419c81185c47e28683da50c8a152d01d#diff-f9e55e6c9441df72de54af693adaa40e418460e97707b7b86b20c78b6947ca47R40

**Comment by erikdubbelboer** [comment]
I have made a fix here https://github.com/valyala/fasthttp/pull/1036
@james-d-elliott you can try this if you want.
@kirillDanshin @savsgio can you guys please check what you think of this fix, since it potentially breaks for users who misuse the library at the moment.

**Comment by james-d-elliott** [comment]
I'm more than willing to test @erikdubbelboer. I'm assuming the way it breaks the functionality is in the way @juan-chan intended to use it. Reading the intent behind the change it only affects headers that cannot be separated by commas as per [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

`Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.`

**Comment by erikdubbelboer** [comment]
@james-d-elliott did you test it? Indeed it shouldn't break that functionality.

**Comment by james-d-elliott** [comment]
I tested just this morning, had a long weekend. Looks to work as I'd expect.

**Comment by erikdubbelboer** [comment]
I have merged the fix and tagged a new release.
