### ISSUE TITLE
ResponseHeader DelClientCookie does not care about cookie flags sameSite / secure

### ISSUE THREAD

**Issue by peczenyj** [valyala/fasthttp#1035]
Hello

Today I have a code like this

```
// RemoveID method.
func (*XXX) RemoveID(ctx *fasthttp.RequestCtx) {
	ctx.Response.Header.DelClientCookie(myCookieName)
}
```

however, since I am using the _sameSite_ mode as _fasthttp.CookieSameSiteStrictMode_ everywhere (and this implies enable the _secure_ flag), I may trigger some warnings in some browsers

what I expect: some easy way to set the sameSite mode when I am removing cookies 

suggestion: use funcional options

```
// Use DelCookie if you want just removing the cookie from response header.
func (h *ResponseHeader) DelClientCookie(key string, opts ...ClientCookieOpts) {
	h.DelCookie(key)

	c := AcquireCookie()
	c.SetKey(key)
	c.SetExpire(CookieExpireDelete)
	h.SetCookie(c)
        for _, o := range opts { // NEW
               o(c)
         }
	ReleaseCookie(c)
}

// ClientCookieOpts funcional option 
type ClientCookieOpts func(*fasthttp.Cookie)

// WithSameSite returns a functional option to be able to set the cookie sameSite flag if needed
func WithSameSite func(mode fasthttp.CookieSameSite) ClientCookieOpts {
        return func(c *fasthttp.Cookie){
                    c.SetSameSite(mode)
        }
}
// WithSecure returns a functional option to be able to set the cookie secure flag if needed
func WithSecure func(secure bool) ClientCookieOpts {
        return func(c *fasthttp.Cookie){
                    c.SetSecure(secure)
        }
}
```

usage

```
// RemoveID method.
func (*XXX) RemoveID(ctx *fasthttp.RequestCtx) {
        // no need to set Secure since it is done on SetSameSite = none
	ctx.Response.Header.DelClientCookie(myCookieName, fasthttp.WithSameSite(fasthttp.CookieSameSiteNoneMode))
}
```

**Comment by peczenyj** [comment]
another option is set some defaults in the ResponseHeader to be used like this

**Comment by erikdubbelboer** [comment]
This is similar as https://github.com/valyala/fasthttp/issues/951 where we decided that we don't want to add a function for every possible cookie option combination. The way you propose with the options functions is better but it's a whole different way of handling options from how the rest of fasthttp does it. I think I still prefer that we only have the simple function and if people want to set different options they just have to inline the code. It's not like [`DelClientCookie`](https://github.com/valyala/fasthttp/blob/5bb5cfc9ca3db7caf1917ca0c8431e70cafa87cb/header.go#L1059-L1063) is a lot of code.

**Comment by peczenyj** [comment]
Well… this means we should close this issue?
