### ISSUE TITLE
HostClient.DisableHeaderNamesNormalizing does not apply to requests.

### ISSUE THREAD

**Issue by dgrr** [valyala/fasthttp#1037]
As the title says: HostClient.DisableHeaderNamesNormalizing does not apply to the requests. 
If someone wants to disable the headers normalization then you need to call [this function](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestHeader.DisableNormalizing) on every request.

See [this](https://github.com/valyala/fasthttp/blob/master/client.go#L1425)

**Comment by erikdubbelboer** [comment]
Which makes sense as normalizing happens when you are adding the headers to the request, not when the client sends the request.

It's probably good to make this more clear in the documentation.

**Comment by stokito** [comment]
Maybe I'm wrong but looks like the `Header.SetCanonical()` just sets a header "as is" without converting to a canonical form

**Comment by erikdubbelboer** [comment]
Correct, the documentation states: `assuming that key is in canonical form.`.
