### ISSUE TITLE
TCP Timeout With Search Engine

### ISSUE THREAD

**Issue by ryouko-dev** [valyala/fasthttp#1038]
I self host an instance of Searx which is using Morty, a server-side proxy - more information available at their repository https://github.com/asciimoo/morty. The code that makes Morty run is the ``morty.go`` file, with less significant configuration being available in ``config/config.go``. 

Morty has two jobs depending on how it is configured within Searx. It can act as:

1.) A search result proxy. This proxies all search results that are typically under the "general" tab of a search engine.

or

2.) A search result and image proxy. This proxies all search results under the "general" tab of a search engine, and all images under the "image" tab.

Morty seems to have issues with the image proxy though. When trying to debug the program, it seems to send ``GET`` requests to an engine for every individual image that gets displayed. That looks something like the following:

```
2021/05/15 00:45:40 GET https://tse3.mm.bing.net/th?id=OIP.dlZObkDNs_DapL5-RdYReAHaFG&pid=Api
2021/05/15 00:45:40 GET https://tse3.mm.bing.net/th?id=OIP.GmUd-r2vAQeB1pk62XXvzwHaC2&pid=Api
2021/05/15 00:45:41 GET https://live.staticflickr.com/2340/2625236627_2e83523858_t.jpg
2021/05/15 00:45:42 error: dialing to the given TCP address timed out
2021/05/15 00:45:43 error: dialing to the given TCP address timed out
2021/05/15 00:45:44 error: dialing to the given TCP address timed out
```

but goes on for potentially hundreds of requests depending on how large an image page is for the Searx instance, and whether or not the owner of the Searx instance enabled infinite scrolling. By looking at the repository's previous issues, this appears to be related to issues #591 and #299 which are regarding the above error. If I read and understood those issues correctly, it means that the server being sent the ``GET`` request simply can't handle the load or accept connections quickly enough. 

I'm wondering if there would be a way to potentially resolve this issue by grouping image requests or something similar. Through my understanding, this would mean sending less requests to each search engine and should result in less timeouts, but I don't know how realistic that is in the real world. Any help here would be appreciated.

**Comment by erikdubbelboer** [comment]
Responded here https://github.com/asciimoo/morty/issues/106
