### ISSUE TITLE
Select outgoing IP

### ISSUE THREAD

**Issue by LucaTheHacker** [valyala/fasthttp#1039]
Hi, I have a server with multiple IPs and I'd like to select which one to use to do the request.

I've tried to check the documentation but seems impossible to specify it, am I missing something?

**Comment by erikdubbelboer** [comment]
You have to set your [`Client.Dial`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Client.Dial) to the `Dial` func of a `TCPDialer` with [`TCPDialer.LocalAddr`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#TCPDialer.LocalAddr) set to the local IP address that you want to use.
