### ISSUE TITLE
MaxConnsPerIP with X-Forwarded-For Ip adress

### ISSUE THREAD

**Issue by raifpy** [valyala/fasthttp#1040]
![image](https://user-images.githubusercontent.com/50047969/120169078-3c2c5f80-c208-11eb-97f2-02164b8df6a8.png)

Hi. Firstly thanks for this huge, great library.
I using MaxConnsPerIP value for create router, but it's look MaxConnsPerIP checking only RemoteAddr
![image](https://user-images.githubusercontent.com/50047969/120169673-dd1b1a80-c208-11eb-8c3a-86035cdde345.png)
![image](https://user-images.githubusercontent.com/50047969/120169762-f328db00-c208-11eb-88fb-f2a2b092e0ee.png)

if you are not use any redirector* It's ok.
But i using CloudFlare, so my request's RemoteAddr is CloudFlare's IP.

I'm worried about my router working incorrectly.
Can you add option for CF Ip's.
Thanks..

**Comment by raifpy** [comment]
![image](https://user-images.githubusercontent.com/50047969/120173235-80216380-c20c-11eb-98e8-095ea8387436.png)

**Comment by lafriks** [comment]
I don't think that's possible to implement as this happens before headers are even received

**Comment by raifpy** [comment]
> I don't think that's possible to implement as this happens before headers are even received

It came to my mind later, but I didn't close the problem saying maybe there will be a solution 😄
Thank you anyway
