### ISSUE TITLE
missing to send v to wp.stopCh 

### ISSUE THREAD

**Issue by xly0713** [valyala/fasthttp#1041]
https://github.com/valyala/fasthttp/blob/6233fbc08ea58da4f846ae3c4fd4bfd6feabb55b/workerpool.go#L76

1. wp.Stop only close wp.stopCh.
2. a goroutine in wp.Start function read wp.stopCh for interrupt clean work.  Is there wrong?

**Comment by erikdubbelboer** [comment]
The goroutine started from `wp.Start` will stop once the channel is closed as reading from closed channel returns the zero value for the channel type: https://play.golang.org/p/-ijgA1_2d4N
