### ISSUE TITLE
Only listen on IPv6, doesn't have fasthttp.Listen

### ISSUE THREAD

**Issue by kokizzu** [valyala/fasthttp#105]
It only listen on IPv6 when using `ListenAndServe`, 
and fasthttp doesn't have `Listen` function.

Reference: https://groups.google.com/forum/#!msg/golang-nuts/F5HE7Eqb6iM/q_um2VqT5vAJ

**Comment by valyala** [comment]
Now `fasthttp` listens only IPv4 by default.

Just pass custom listener to [Serve](https://godoc.org/github.com/valyala/fasthttp#Serve) for listening on non-ipv4 medium.

**Comment by kataras** [comment]
@valyala Can you explain the reasons for this change because I didn't understood 100%, the defaulted "tcp" worked well so far,
I'm using custom `net.Listen("tcp",..` ,  you 're recommending that we should change this to v4?

**Comment by valyala** [comment]
@kataras ,

- `net.Listen("tcp", addr)` listens either on both IPv4 and IPv6 or only on IPv6 interface if `addr` doesn't contain hostname. For example,

```go
// May listen either on IPv6 or on both IPv4 and IPv6 interfaces.
net.Listen("tcp", ":80")
```

This may be unexpected or misleading - see [the discussion](https://groups.google.com/forum/#!msg/golang-nuts/F5HE7Eqb6iM/q_um2VqT5vAJ) for more details.

So now `fasthttp` server listens only IPv4 interfaces by default. This complements already existing decisions regarding [reuseport](https://godoc.org/github.com/valyala/fasthttp/reuseport) listener and [default dialer](https://godoc.org/github.com/valyala/fasthttp#Dial) used by `fasthttp` clients, which use IPv4 by default.

**Comment by kataras** [comment]
Hm ok so it's general Go's network interface 'bug' or operating system's choice  (if I understood correctly). Thanks you @valyala you're very helpful person and I hope we will see soon the http2 support, if I can help somewhere I will!

**Comment by valyala** [comment]
> Hm ok so it's general Go's network interface 'bug' or operating system's choice (if I understood correctly). 

I think this is general IPv6 "bug" related to its' over-engineering, which leads to very slow adoption :)

> I hope we will see soon the http2 support, if I can help somewhere I will!

Currently http2 isn't on my radar. But I'll glad to see and help third-party http2 libraries for `fasthttp`.

> Something happened after last changes and Coverage widget (on readme) shows error, you should fix it because other maybe scare of it

Will try fixing it.
It may be related to https://github.com/vieux/gocover.io/issues/3 .

**Comment by kataras** [comment]
@valyala I just released that maybe we have bug, look

```go
//....s.Server is the &fasthttp Server
var err error
s.listener, err = net.Listen("tcp4", s.Config.ListeningAddr) // tried with "tcp" also
go s.Server.Serve(s.listener)
```

before we could close/terminate the server by closing the net.listener like
```go
//...
s.listener.Close() // this now doesn't close the server, the s.listener is not nil but .Close doesnt works
```

Now this code does nothing, it doesn't closes the server, if you want more informations let me know, 

OS: Windows 7 x64 - latest fasthttp (upgraded before 20 minutes)

**Comment by kataras** [comment]
@valyala I just released that maybe we have bug, look

```go
//....s.Server is the &fasthttp Server
var err error
s.listener, err = net.Listen("tcp4", "127.0.0.1:8080") // tried with "tcp" also
go s.Server.Serve(s.listener)
```

before we could close/terminate the server by closing the net.listener like
```go
//...
s.listener.Close() // this now doesn't close the server, the s.listener is not nil but .Close doesnt works
```

Now this code does nothing, it doesn't closes the server, if you want more informations let me know, 

OS: Windows 7 x64 - latest fasthttp (upgraded before 20 minutes)
