### ISSUE TITLE
Error when sending more than 100 requests to a host via PipelineClient .

### ISSUE THREAD

**Issue by stfuanu** [valyala/fasthttp#1051]
Hello :) , 

I want to send 50,000+ resquests to a host , in a ratelimited manner , So thought of using PipelineClient , cuz then i would be able to send more requests in Less Connections/Load to the server .

so while executing that , whenever i send more than 100-150 requests or so , randomly this EOF error comes .
`2021/06/20 21:14:47 error in PipelineClient("157.245.125.234"): EOF
EOF`

Therefore , I wanted to know :--
- What is this Error ,
- and How can i avoid it ,
- or Does it even matter because i am getting all of the responses back anyways , with hardly any time wasted . so just mute the error ?
Edit : It does cause major delay sometimes .

Less than 100 -200:

```console
root@snap:~/skrr# go run pipe.go 200
Sending  200 requests...

Time Taken : 995.608µs
Total Response Read := 200

root@snap:~/skrr# go run pipe.go 100
Sending  100 requests...

Time Taken : 602.138µs
Total Response Read := 100

```

More than 100-200:

```console

root@snap:~/skrr# go run pipe.go 500
Sending  500 requests...
2021/06/20 21:28:21 error in PipelineClient("157.245.125.234"): EOF
EOF
Error Occured at Req No. : 251

Time Taken : 1.994905ms
Total Response Read := 500

root@snap:~/skrr# go run pipe.go 250
Sending  250 requests...
2021/06/20 21:29:22 error in PipelineClient("157.245.125.234"): EOF
EOF
Error Occured at Req No. : 125

Time Taken : 1.338302ms
Total Response Read := 250

```

Code : pipe.go 

```golang
package main

import (
	"github.com/valyala/fasthttp" //nolint:goimports
	// "net/url"
	"reflect"
	"sync"
	"time"
	"os"
	"strconv"
	// "log"
	// "console"
	"fmt"
	"unsafe" //nolint:goimports
)

// var client *fasthttp.PipelineClient //nolint:gochecknoglobals

var batch int

func CreatePipelineClient(url string) *fasthttp.PipelineClient {
	return &fasthttp.PipelineClient { //nolint:gofmt
		Addr: url,
		MaxConns:            10000,
		MaxPendingRequests:  10000,
		MaxBatchDelay:       0,
		Dial:                nil,
		DialDualStack:       false,
		IsTLS:               false,
		TLSConfig:           nil,
		MaxIdleConnDuration: 50 * time.Second,
		ReadBufferSize:      4096,
		WriteBufferSize:     4096,
		ReadTimeout:         10 * time.Minute,
		WriteTimeout:        10 * time.Minute,
		Logger:              nil,
	}
}



func Request(uri string , c *int , cli *fasthttp.PipelineClient) {
	// fmt.Println(*c)
	// client := CreatePipelineClient("157.245.125.234")

	// if *c == batch {
		// cli = CreatePipelineClient("157.245.125.234")
		// fmt.Println("newclient at : ", batch)
		// batch = batch + 100
	// }
	
	

	destUrl := []byte(uri)

	req := fasthttp.AcquireRequest()
	res := fasthttp.AcquireResponse()

	req.SetRequestURIBytes(destUrl)


	if err := cli.Do(req, res); err != nil {
		println(err.Error())
		fmt.Printf("Error Occured at Req No. : %d \n", *c)
	}
	// time.Sleep(700 * time.Millisecond)

	fasthttp.ReleaseRequest(req)
	if res.StatusCode() == 200 {
		*c++
		// fmt.Println(*c)
		// fmt.Println(res.StatusCode() , BytesToString(destUrl)) // Print Response
		fasthttp.ReleaseResponse(res)
	}

}

func BytesToString(b []byte) string {
	bh := (*reflect.SliceHeader)(unsafe.Pointer(&b))
	sh := reflect.StringHeader{Data: bh.Data, Len: bh.Len}
	return *(*string)(unsafe.Pointer(&sh)) //nolint:wsl
}

// var syncMap sync.Map
// u, _ := url.Parse(ur)
// if _, ok := HTTPClients[u.Host]; !ok {
	// syncMap.Store(u.Host, CreatePipelineClient(u.Host))
	// HTTPClients[u.Host] = CreatePipelineClient(u.Host)
// }
// client := HTTPClients[u.Host]



// func pushnewclient(ur string) 

func main() {

	reqs := os.Args[1]
	// print
	re, _ := strconv.Atoi(reqs)
	// print(re)
	// os.Exit(0)
	wgfuzz := new(sync.WaitGroup)



	c := 0
	// count := &c

	start := time.Now()
	// limit := 100
	// lim := &limit
	fmt.Println("Sending " ,re , "requests...")
	client := CreatePipelineClient("157.245.125.234")
	
	for i := 0; i < re; i++ {

		wgfuzz.Add(1)
		// 

		go func() {	
			// Progress.TotalConn++
			// fmt.Println("connection No. : " , concount)
			Request("http://157.245.125.234" , &c , client)
			wgfuzz.Done()
		}()
	}

	elapsed := time.Since(start)

	wgfuzz.Wait()
	fmt.Printf("\nTime Taken : %s \nTotal Response Read := %d \n", elapsed , c )

}

```

Or maybe I made mistake in how pipelined request are suppossed to be sent .
Help plz :/

**Comment by erikdubbelboer** [comment]
Does the server you are sending the requests to support HTTP pipelining? Pipelining doesn't reduce the connections or load on the server, it will just send many requests at once. Normal servers always expect 1 request, then send the reply and then expect the next request. With pipelining you send many requests at once and then expect the replies for all of them.

Isn't the server just rate limiting you for sending too many requests?

**Comment by stfuanu** [comment]
It's a simple self-hosted nginx server on a vps .
idk , if it was for "too many req error " then status code would be 429 ?? , all responses were 200 OK .
also this EOF error comes at random  .

Basically , I am kinda lost and want to figure out how i could send N(let's say 100) pipelined request on a 10 concurrent connections .
or after sending 100 batched requests , Would i need to make new clients again for making new connection and sending 100 again , or `MaxConns` & `MaxPendingRequests` can somehow be tweaked to do this ??

**Comment by erikdubbelboer** [comment]
Seems like nginx has a certain limit to it's pipelining. It's not for nothing that browsers all have pipelining disabled. There are many servers with no or broken support.

If you found settings that work for your server I would continue using those.
