### ISSUE TITLE
High latency spikes with simple example

### ISSUE THREAD

**Issue by xiaowenxia** [valyala/fasthttp#1055]
I sampled 5 minutes latency with an simple fasthttp example in 100QPS, and found high latency spikes (up to 9ms latency but less than 1ms most of the time) in the result:
<img width="2595" alt="latency" src="https://user-images.githubusercontent.com/16155447/123599330-0e96fe00-d828-11eb-9f9b-57294bc0712a.png">

Is the latency spikes normal or I missing something?

Test environment:
* `ecs.t5-c1m1.xlarge`: 4 CPU , 4G RAM
* `CentOS 7`, Kernel 3.10.0

the fasthttp test example is:
```go
package main

import (
    "fmt"
    "github.com/valyala/fasthttp"
)

func httpHandle(ctx *fasthttp.RequestCtx) {
    fmt.Fprintf(ctx, "hello world")
}

func main() {
    if err := fasthttp.ListenAndServe("0.0.0.0:7070", httpHandle); err != nil {
        fmt.Println("start fasthttp fail:", err.Error())
    }
}
```

And I used [vegeta](https://github.com/tsenart/vegeta) to sample the latency report, latency sampling commands like this:
```shell
# sampling
$ echo "GET http://localhost:7070/fasthttp/hello" | ./vegeta attack -duration=5m -rate 100 | tee results.fasthttp.bin | ./vegeta report

# generate report
$ cat results.fasthttp.bin | ./vegeta plot > plot.fasthttp.html
```

**Comment by erikdubbelboer** [comment]
Try changing the handler to this:
```
func httpHandle(ctx *fasthttp.RequestCtx) {
    ctx.WriteString("hello world")
}
```
I'm not sure from the top of my head if `fmt.Fprintf` causes allocations which potentially cause garbage collector spikes.

But more likely the latency spikes are on the vegeta side. Can you try a different tool and see if you notice the same?

**Comment by xiaowenxia** [comment]
Thanks.
I got the same result after changing to `ctx.WriteString("hello world")`. But I found that there is no high latency spikes when i test on my mac and another computer, maybe there are some wrong configuration on the `ECS`.

**Comment by erikdubbelboer** [comment]
With virtualization you can always have small hiccups like that. Last time I tried Amazon their networking wasn't great either. If you need networking performance I would always go with Google Cloud.
