### ISSUE TITLE
Extra CRLF after body breaks the server 

### ISSUE THREAD

**Issue by artur-ma** [valyala/fasthttp#1057]
accroding to this doc https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

        generic-message = start-line
                          *(message-header CRLF)
                          CRLF
                          [ message-body ]
        start-line      = Request-Line | Status-Line
        
        
  "In the interest of robustness, servers SHOULD ignore any empty line(s) received where a Request-Line is expected. In other words, if the server is reading the protocol stream at the beginning of a message and receives a CRLF first, it should ignore the CRLF."
  
  
  but if we send extra CRLF to the server where should be the Request-Line, the server expects it to be included in `Content-Length` value, otherwise, if Content-Lenght does not match the actual content size, the server will never write the response to the socket

**Comment by artur-ma** [comment]
Reproduce with Nodejs

```
    socket.cork()
    socket.write(`POST /testPost HTTP/1.1\r\nconnection: keep-alive\r\nhost: localhost:8989\r\n'content-length: 2\r\n\r\n`, 'ascii')
    socket.write(body)
    socket.write('\r\n', 'ascii')
    socket.uncork()
```

p.s body lenght is "2" (`{}`), client never gets a response, once I change it to "4" (including `\r` and `\n`) it works

**Comment by erikdubbelboer** [comment]
Have you tried with the latest version? I kinda contains a fix for this.

**Comment by artur-ma** [comment]
It works, thanks!
