### ISSUE TITLE
Crashing when serving hijacked connections from a SSH listener

### ISSUE THREAD

**Issue by bloeys** [valyala/fasthttp#1059]
Hello,

First of all, thanks for this amazing library!

We have a bit of a niche use case where our program SSH's (using Go's `crypto/ssh`) into a remote host and then does two things:

1. Port forwards remote->local to a Fasthttp server using a SSH listener, where the request handler hijacks the connection.
2. Sends requests local->remote on a specific port on the remote machine through a SSH conn created using `sshClient.Dial`.
3. Run a second fasthttp server in the same program that accepts connections from a normal local listener (not through SSH).

It seems that if the connection is being served using a SSH listener and ends up being hijacked fasthttp panics. I have mostly traced it down to the `net.Conn` implementation used by `crypto/ssh`, as they do NOT implement Set Read/Write Deadline functions required by the Conn interface.

They implement empty functions (to satisfy the interface) that simply return an error: 
https://github.com/golang/crypto/blob/5ff15b29337e062d850872081bcd9f4d784f4c25/ssh/tcpip.go#L464

It seems these end up being called in `server.go` (as far as I saw so far), produce an error and crash. The lines that are crashing seem to be here: https://github.com/valyala/fasthttp/blob/d0df1e1dde9159848f2153989461e0a3e81f2b40/server.go#L2335

It would be great if this can be handled somehow, or if you have another recommendation in this case. As a dirty workaround, we are currently vendoring the dependencies and commenting out those lines in `server.go`, which stops crashes but am not sure if it has negative effects, especially on the normal server.

Any help is appreciated 🙏🏻

**Comment by erikdubbelboer** [comment]
I would suggest you wrap the `net.Conn` with your own struct that just returns nil for these methods and forwards the other ones to the `crypto/ssh` Conn. Would that work for you?

I'm not sure what fasthttp should do if these fail, we could log an error I guess?

**Comment by bloeys** [comment]
Yes I was also thinking implementing the interface and do nothing could work, although a bit annoying to implement in every project that has this.

For Fasthttp perhaps we can check for the error message returned by the SSH conn (`ssh: tcpChan: deadline not supported`) and if so ignore the error. If its a different error then the current behavior of crashing might be good idea as an error here might mean something really wrong happened.

What do you think about this?

**Comment by erikdubbelboer** [comment]
I feel like checking for `deadline not supported` is too arbitrary. Other code can use a different error message for the same intent.

I'm thinking that even if fasthttp would log errors, you would still have to implement your Conn wrap to get rid of those errors.

Did you already implement the interface? Maybe you could make a package for it so other can easily reuse it?
