### ISSUE TITLE
Strange timeout issue with fasthttp

### ISSUE THREAD

**Issue by iyuvalk** [valyala/fasthttp#1060]
Hi, I'm using fasthttp to send POST requests to a SAAS REST service and I get a timeout error long before the timeout I have set for the DoTimeout command.

The code I'm using looks like this:
```
timeStarted := time.Now()
err = upstreamClient.DoTimeout(req, resp, time.Duration(upstreamTimeoutMilliseconds) * time.Millisecond)
timeTaken := time.Since(timeStarted)
if err == nil || errors.Is(err, syscall.EPIPE) {
	statusCode := resp.StatusCode()
	status := resp.String()
	fasthttp.ReleaseResponse(resp)

         //Handle the status code and such...
} else {
	log.Printf(" ERROR: cannot send logs batch (after %v): %v", timeTaken, err)
}
```

In the log I see lots of lines like this:
```
 ERROR: cannot send logs batch (after 3.32μs): timeout
 ERROR: cannot send logs batch (after 65.379067ms): timeout
 ERROR: cannot send logs batch (after 6.008866ms): timeout
 ERROR: cannot send logs batch (after 36.436383ms): timeout
```

The value of the variable 'upstreamTimeoutMilliseconds' is set to 120000. How is it possible that the "DoTimeout" function returns with a timeout error BEFORE that amount of time with a timeout error?

Interestingly enough, I have a code that wraps this call and if it failed, for example with a timeout, it retries the same call up to 5 times before giving up. From the logs it seems that this timeout issue happens ALL THE TIME AT FIRST REQUEST and succeeds in the second attempt.

**Comment by erikdubbelboer** [comment]
Could it be that the DNS lookup times out or that the server is closed for connections? I need more information or reproducible code to see what is happening.

**Comment by iyuvalk** [comment]
Well. First of all - thanks a lot for your reply (:
If it was so easy to reproduce the problem I'm guessing that I could probably figure this out by myself. In the time since I opened this issue I found out that there's a device (a firewall) that probably sends fake TCP.RESET packets to my server on behalf of our SAAS service. Perhaps this could be the cause of this problem. We're going to try and fix this today and I'll update you here. Thanks again.

**Comment by iyuvalk** [comment]
Just updating that this TCP.RESET is not caused by the firewall. Testing a BGP configuration that to my understanding could be related. Keeping this case open here just in case it would turn out that it's not the BGP either.

**Comment by moredure** [comment]
@iyuvalk, so what the reason?

**Comment by iyuvalk** [comment]
Still investigating the issue with the ISP to understand if it is related
to the library that I used or to some BGP settings. Will update you here in
few days.

**Comment by moredure** [comment]
@iyuvalk Thanks, will be waiting!

**Comment by iyuvalk** [comment]
Well. I know it took me a while but I wanted to be 100% percent sure of it first. You are off the hook! Since that my code, which uses fasthttp was in fact called by another, C code (from fluentbit) it was difficult for me to tell which part of the puzzle is causing the issue but eventually I ran my own code with different configurations of the hosting fluentbit C code and eventually managed to get it to work as expected. Just want to say that I appreciate your patience and willing to help! Thanks (:

**Comment by moredure** [comment]
@iyuvalk go 1.16.6+ and golang 1.17.1 had some issues with timers maybe it's your case, also I made some pull request to golang to allow to bypass interruptor goroutine (in case you are not going to cancel request by hand) so it might be interesting for you.
