### ISSUE TITLE
`RequestCtx.IsTLS()` doesn't recognize`perIPConn` when TLS is used

### ISSUE THREAD

**Issue by tysg** [valyala/fasthttp#1062]
Steps To Reproduce: See https://github.com/gofiber/fiber/issues/1456

Description: 

When `Server.MaxConnsPerIP` is set to a non-zero value, the server wraps every incoming connection to a `perIPConn` in `acquirePerIPConn`. `perIPConn` has the struct definition: 

```go
type perIPConn struct {
	net.Conn

	ip               uint32
	perIPConnCounter *perIPConnCounter
}
```
When a `tls.Conn` comes in, `acquirePerIPConn` assigns the `tls.Conn` to the field `Conn` in the return value, which restricts the `tls.Conn` to `net.Conn`.

https://github.com/valyala/fasthttp/blob/9466cd7657c9b3e3ec7e2601114ffaaa739aeed4/peripconn.go#L48-L59

Therefore, the `IsTLS()` check on `perIPConn` will fail, as it doesn't implement the `connTLSer` any more. 

https://github.com/valyala/fasthttp/blob/9466cd7657c9b3e3ec7e2601114ffaaa739aeed4/server.go#L709-L720

Furthermore, adding the following failing test in `server_test.go` confirmed the discovery:
```go

func TestRequestCtxIsTLS(t *testing.T) {
	t.Parallel()

	var ctx RequestCtx

        // ... omitted

	ctx.c = &struct {
		net.Conn
		fooBar bool
	}{Conn: &tls.Conn{}}
	if !ctx.IsTLS() {
		t.Fatal("IsTLS must return true") // fails
	}
}
```

**Comment by tysg** [comment]
I would love to work on this if the maintainers can point me the correct direction :)

**Comment by erikdubbelboer** [comment]
@tysg the simplest way is probably for `RequestCtx.IsTLS` to check for `perIPConn` like this example: https://play.golang.org/p/p6zHsqpKhyC
If you can make a pull request for this including the test from above that would be great! 🙏

**Comment by tysg** [comment]
@erikdubbelboer Thanks for the code snippet! I submitted the PR under #1064
