### ISSUE TITLE
[Features Request] support HTTPS via proxy for HostClient?

### ISSUE THREAD

**Issue by skiloop** [valyala/fasthttp#1066]
Does HostClient support HTTPS via proxy?

I go over the codes of HostClient, and find at HostClient.doNonNilReqResp
```go
        if c.IsTLS != bytes.Equal(req.uri.Scheme(), strHTTPS) {
		return false, ErrHostClientRedirectToDifferentScheme
	}
```
IsTLS means the connection between client and direct host is an encrypted connection, in proxy case the direct host is the proxy. As fast as I know for HTTPS via a non-HTTPS proxy, the connection between the client and proxy is not a TLS connection, and clients send encrypted data via the plain connection and the proxy do not know what the meaning of the data after the handshakes between clients and the web server have been done.

So how about some implements to support https via proxy for HostClient?

**Comment by erikdubbelboer** [comment]
Have you tried if it works? I think it should.

The code you link there is to detect misuse of `HostClient` a `HostClient` has a pool of connections to a server:port. Which means it can only be used for http or https connections, not both as you can't send a http request to a https port and vica versa. So if you need to support switching between http and https connections you need to use `Client` instead.

**Comment by ccychan** [comment]
> Have you tried if it works? I think it should.
> 
> The code you link there is to detect misuse of `HostClient` a `HostClient` has a pool of connections to a server:port. Which means it can only be used for http or https connections, not both as you can't send a http request to a https port and vica versa. So if you need to support switching between http and https connections you need to use `Client` instead.
---------------------------------------------------------------------------------------------------------------------
Hi, I am new to fasthttp. I am trying to create a proxy service to listen to incoming http traffic, and proxy traffic to https endpoint (through TLS transport). Is there an example on how to use Client to achieve this? Thanks.
