### ISSUE TITLE
Question about HTTP DELETE method

### ISSUE THREAD

**Issue by tracer0tong** [valyala/fasthttp#107]
Hi, I'm just curious why you doesn't support DELETE method? This is a one of useful methods for classic RESTful interfaces. Do you have some reasons for that?
And yet another question. Do you have a method to get information about all request headers (I want to get information from X-Real-IP for my task), possibly I'm just didn't find it.

**Comment by valyala** [comment]
> Hi, I'm just curious why you doesn't support DELETE method?

Actually `fasthttp` should support arbitrary methods including DELETE. Method name may be obtained via [RequestCtx.Request.Header.Method](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Method). See the test added in [this commit](https://github.com/valyala/fasthttp/commit/ccf67b7c98691668b7658ddfd91751f6f4e48e6f) for details.

> Do you have a method to get information about all request headers (I want to get information from X-Real-IP for my task), possibly I'm just didn't find it.

See [RequestCtx.Request.Header.Peek](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Peek) and [RequestCtx.Request.Header.VisitAll](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.VisitAll).

**Comment by tracer0tong** [comment]
I've made short pull request and added a IsDelete(). That was a first question. About second one, thank you, that's what I need!

**Comment by valyala** [comment]
Merged pull request
