### ISSUE TITLE
fasthttp.Client may raise many routinues to clean connections when i use fasthttp.Client as proxy client

### ISSUE THREAD

**Issue by chhquan** [valyala/fasthttp#1073]
When I use fasthttp.Client as a proxy client, I found that it will raise a routinue to clean the HostClients and each HostClient will raise a routinue to clean its connection, unfortunately, a proxy may has many upstream server, and many routinues will be created. Does it need to reduce those routines? It is possiable to use  a connection pool to manage all connections ?

**Comment by erikdubbelboer** [comment]
It's not needed to reduce those goroutines. Goroutines by themselves are very light, and these are mostly sleeping so they don't take up any CPU and only a little bit of memory. The goroutines are also [stopped when there are no connections anymore](https://github.com/valyala/fasthttp/blob/5a6e6e102bf70ec6d2a7bad033abb9d9f008f03c/client.go#L554-L561).

Right now the goroutines sleep for 10 seconds. What I think we should do is change that to something like `Client.MaxIdleConnDuration` so if you set a low idle duration you don't have the goroutine hanging around for too long.

**Comment by erikdubbelboer** [comment]
See: https://github.com/valyala/fasthttp/pull/1076

**Comment by chhquan** [comment]
@erikdubbelboer When I use a client proxy, it may have thousands of routine because there may be hundreds of upstream servers and each server has serval hosts. I think it is possiable to deduce the number of goroutines by using a cleaner routinue. the HostClient may register itself to the cleaner when the first connection created. And the cleaner will clear a HostClient when it has no connections. And the same as Client.

**Comment by erikdubbelboer** [comment]
That would make sense as well. A pull request for that would be welcome as I don't currently have time to make a change like that.

**Comment by chhquan** [comment]
@erikdubbelboer It is ok, thanks!
