### ISSUE TITLE
Client doesn't change Dial for host if it's changed in Client. API is misleading

### ISSUE THREAD

**Issue by edwvee** [valyala/fasthttp#1075]
E.g. I do requests with set of proxies. I set ```client.Dial``` at first, do request, get dial timeout. Then I change proxy setting client.Dial with function using different proxy and I get timeout error with the same proxy as in previous example. Looks like Dial is stuck to the host.
```go
func (c *Client) Do(req *Request, resp *Response) error {
	uri := req.URI()
	if uri == nil {
		return ErrorInvalidURI
	}

	host := uri.Host()

	isTLS := false
	scheme := uri.Scheme()
	if bytes.Equal(scheme, strHTTPS) {
		isTLS = true
	} else if !bytes.Equal(scheme, strHTTP) {
		return fmt.Errorf("unsupported protocol %q. http and https are supported", scheme)
	}

	startCleaner := false

	c.mLock.Lock()
	m := c.m
	if isTLS {
		m = c.ms
	}
	if m == nil {
		m = make(map[string]*HostClient)
		if isTLS {
			c.ms = m
		} else {
			c.m = m
		}
	}
	hc := m[string(host)]
	if hc == nil {
		hc = &HostClient{
			Addr:                          addMissingPort(string(host), isTLS),
			Name:                          c.Name,
			NoDefaultUserAgentHeader:      c.NoDefaultUserAgentHeader,
			Dial:                          c.Dial,
```

There is even no precaution in the commentary above Client's field Dial.
If it's one Client - one Dial, then API should be changed. But for now it's dualistic behaviour: the old Dial stays for known to Client hosts and the new one is being used for new hosts.

**Comment by erikdubbelboer** [comment]
I'm afraid it's not supported to change the `Client` fields while the `Client` is already in use.

See: https://github.com/valyala/fasthttp/pull/1076
