### ISSUE TITLE
Limiting bandwidth with ServeFile

### ISSUE THREAD

**Issue by onthegit** [valyala/fasthttp#1083]
Hello,
is there a way to limit bandwidth speed with servefile with something like: https://github.com/juju/ratelimit 

or other  way io.Reader?
This is for large files.

**Comment by erikdubbelboer** [comment]
I'm afraid that [`fasthttp.ServeFile`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#ServeFile) and [`fasthttp.FS`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#FS) don't have any support for this.

What you could do is open the file yourself ([`os.Open`](https://pkg.go.dev/os#Open)), wrap it using [`ratelimit.Reader`](https://pkg.go.dev/github.com/juju/ratelimit?utm_source=godoc#Reader) and then pass it to [`RequestCtx.SetBodyStream`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestCtx.SetBodyStream)
