### ISSUE TITLE
[Question] Which method is the best practice for product env?

### ISSUE THREAD

**Issue by diCagri** [valyala/fasthttp#1089]
Hi,

I am new at fasthttp, i have few questions about how we can run fasthttp at product environment. And i will start with my basic questions (i come from python and i m junior dev so if you be more specific i will be grateful).

1 - I am using this simple switch-case for my microservice
```
func RequestHandler(ctx *fasthttp.RequestCtx) {
	switch string(ctx.Path()) {

	case "/split-text":
		splitService(ctx)

	default:
		ctx.Error("Unsupported path", fasthttp.StatusNotFound)
	}
}

func main() {
	fasthttp.ListenAndServe(":8080", RequestHandler)
}
```

Does it use all cores when run with "go run main.go" command? Do I need to write a special argument?

2 - 

I am using first method for all my services when i looked for i saw different methods and i dont get it why they are using these ways. so, which is the best way and best practice? 

- first is server code from section 1.1 https://github.com/tsingson/fasthttp-guide
in this way he is adding  multiple "s.Serve" to a group and returns group.Run(). What are the advantages of this method? Is there any difference with the 1st method? Also if i want to give parameters like "MaxConnsPerIP" what should i do? 

````
type webServer struct {
	Config WebConfig
	addr   string
	Log    *zap.Logger
	ln     net.Listener
	router *router.Router
	debug  bool
}


func (ws *webServer) Run() (err error) {
	ws.muxRouter()
	// reuse port
	ws.ln, err = listen(ws.addr, ws.Log)
	if err != nil {
		return err
	}
	var lg = zaplogger.InitZapLogger(ws.Log)
	s := &fasthttp.Server{
		Handler:            ws.router.Handler,
		Name:               ws.Config.Name,
		ReadBufferSize:     ws.Config.ReadBufferSize,
		MaxConnsPerIP:      ws.Config.MaxConnsPerIP,
		MaxRequestsPerConn: ws.Config.MaxRequestsPerConn,
		MaxRequestBodySize: ws.Config.MaxRequestBodySize, //  100 << 20, // 100MB // 1024 * 4, // MaxRequestBodySize:
		Concurrency:        ws.Config.Concurrency,
		Logger:             lg,
	}

	// run fasthttp serv
	var g run.Group
	g.Add(func() error {
		return s.Serve(ws.ln)
	}, func(e error) {
		_ = ws.ln.Close()

	})
	return g.Run()
}
````

- second is second code block from here https://husobee.github.io/golang/fasthttp/2016/06/23/golang-fasthttp.html
this article is 5 years old so i dont trust it but i just want to ask is this a good way?

````
func (s *Server) Serve(ln net.Listener) error {
	var lastOverflowErrorTime time.Time
	var lastPerIPErrorTime time.Time
	var c net.Conn
	var err error

	maxWorkersCount := s.getConcurrency()
	s.concurrencyCh = make(chan struct{}, maxWorkersCount)
	wp := &workerPool{
		WorkerFunc:      s.serveConn,
		MaxWorkersCount: maxWorkersCount,
		LogAllErrors:    s.LogAllErrors,
		Logger:          s.logger(),
	}
	wp.Start()

	for {
		if c, err = acceptConn(s, ln, &lastPerIPErrorTime); err != nil {
			wp.Stop()
			if err == io.EOF {
				return nil
			}
			return err
		}
		if !wp.Serve(c) {
			s.writeFastError(c, StatusServiceUnavailable,
				"The connection cannot be served because Server.Concurrency limit exceeded")
			c.Close()
			if time.Since(lastOverflowErrorTime) > time.Minute {
				s.logger().Printf("The incoming connection cannot be served, because %d concurrent connections are served. "+
					"Try increasing Server.Concurrency", maxWorkersCount)
				lastOverflowErrorTime = time.Now()
			}

			// The current server reached concurrency limit,
			// so give other concurrently running servers a chance
			// accepting incoming connections on the same address.
			//
			// There is a hope other servers didn't reach their
			// concurrency limits yet :)
			time.Sleep(100 * time.Millisecond)
		}
		c = nil
	}
}
````

for these method which is the more effective way? or you guys have different fasted method :) And can you guys answer my questions and explain this methods to me :)
Thank you so much !

**Comment by erikdubbelboer** [comment]
1. Yes it will use all cores as it will start separate goroutines to handle incoming requests.
2. That `run.Group` with only one thing running doesn't make much sense, you don't need that.
I don't understand the last part of the question, this is code from fasthttp it self, you don't have to implement this to use fasthttp.

**Comment by tsingson** [comment]
> * https://github.com/tsingson/fasthttp-guide

about 2, yes, run.Group for single task is not need.

in my product mode, there some other task code in run.Group. 

@diCagri 

i wrap fasthttp in a webServer struct:
1.  add another task code to run background
2. wrap a demon to keep webServer running with reuseport 

good luck...
