### ISSUE TITLE
Partial read

### ISSUE THREAD

**Issue by melardev** [valyala/fasthttp#1100]
Hi, is there a way to read N bytes from a fasthttp response and the ability to drop the response before reading the whole response?
I see fasthttp kind of equivalent to `iotil.ReadAll`, is there a way to provide a custom read implementation? ReadAll is known to be unsafe how can I do that?

I am aware this concern was raised years ago (#411, #99), and an alternative is provided, however, some years have passed, is there

**Comment by erikdubbelboer** [comment]
I'm afraid not. fasthttp is optimized for speed for a specific workload. It will always read the full response body.

**Comment by PeterlitsZo** [comment]
First of all, thanks for your great work~

But I need the partial reading function for testing... Now I have no idea how to test it (Because the `BodyStreamWriter` is an infinite loop...). I find that the test in fasthttp is only testing for full response...

**Comment by erikdubbelboer** [comment]
Which test in fasthttp do you mean?
