### ISSUE TITLE
Closing idle connections (and improving shutdown)

### ISSUE THREAD

**Issue by fserb** [valyala/fasthttp#1103]
I've been trying to get proper shutdown on fasthttp, and given the number of bugs with people confused about this, maybe something better could be done? 

The current situation (please correct me if I'm wrong) seems to be that: Unless keepalive connections are completely disabled or `readTimeout` is set to something, there's no way to gracefully shutdown fasthttp. Also, setting those two things right before calling `Shutdown()` seems to be ignored. Finally, I am not sure what `CloseOnShutdown` was supposed to do, but whatever it is, it doesn't seem to be doing it. :)

This makes `Shutdown()` very unfriendly to use.

My code is something like:
```go
serverCtx, serverStopCtx := context.WithCancel(context.Background())

quitCtx, quitCancel := signal.NotifyContext(serverCtx,
    syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)

go func() {
    <-quitCtx.Done()
    quitCancel()

    shutdownCtx, cancel := context.WithTimeout(serverCtx, 60*time.Second)
    defer cancel()

    go func() {
      server.Shutdown()
      serverStopCtx()
    }()

    <-shutdownCtx.Done()
    if shutdownCtx.Err() == context.DeadlineExceeded {
      log.Printf("graceful shutdown timed out... forcing exit.")
    }
    serverStopCtx()
}()

if err = server.ListenAndServe(":8080"); err != nil {
  log.Panic(err)
}

<-serverCtx.Done()

// shutdown code, defer, etc, etc...
```

This is a bit more convoluted than the usual examples, because it includes a hard timeout on Shutdown.

If I start this code and `ctrl+c` before any requests, if works perfectly. Same if I `curl` and then `ctrl+c`. But if I open a request on a browser, then keepalive kicks in and then this will only shutdown on the hard timeout (60s) OR if I set a `ReadTimeout` for fasthttp (in which case it will wait for the read timeout to pass and then quit).

I'm thinking about some options on how to address this:

1. Would it be possible to implement something similar to: [closeIdleConns](https://github.com/golang/go/blob/release-branch.go1.15/src/net/http/server.go#L2743) from net/http? Would that solve the issue? Or would "pending" requests still hang until their timeout kicks in?

2. Would it be possible for `Shutdown()` to "update" all connections to not be keepalive anymore? I.e., to finish as soon as the current request is gone?

**Comment by erikdubbelboer** [comment]
```
CloseOnShutdown when true adds a `Connection: close` header when when the server is shutting down.
```
This just tells new clients to not reuse the connection while the server is shutting down.

Implementing something like `closeIdleConns` should be doable. We'll need to add a `[]net.Conn` to `Server` and then have [`serveConn`](https://github.com/valyala/fasthttp/blob/44d0333ba35a6873598e2e9eb55323505aaf79f3/server.go#L2008) add and remove connections based on if they are idle or not.

If you can try making a pull request that would be great, otherwise I'll try to make time for this soon.

**Comment by edwvee** [comment]
In my case ```ReadTimeout``` even doesn't work:
```go
server = &fasthttp.Server{
		Handler:               r.handle,
		CloseOnShutdown:       true,
		NoDefaultServerHeader: true,
		NoDefaultContentType:  true,
		NoDefaultDate:         true,
		ReadTimeout:           10 * time.Second,
		IdleTimeout:           300 * time.Second,
	}
/*
start server, then requests are going
*/
timer := time.NewTimer(20*time.Second)
	shutdownErr := make(chan error)
	go func() {
		shutdownErr <- r.server.Shutdown()
	}()
	select {
	case <-timer.C:
		err = ErrDidntShutdownInTime
	case err = <-shutdownErr:
	}
``` 
So ```err``` is ```ErrDidntShutdownInTime```.
The strange thing is that I wrote a test in go with multiple clients sending to server and using keep-alive. And test passes, but in real life I always get that error.

**Comment by erikdubbelboer** [comment]
For that to work you'll also have to set `IdleTimeout` to a value lower than 20 seconds. And your handlers also need to take less than 20 seconds. Shutdown will wait for all of those.

**Comment by edwvee** [comment]
1. Is that because there is no feature to close idle connections?
2. IdleTimeout of 20 seconds means that keep alive time is 20 seconds?

**Comment by erikdubbelboer** [comment]
Both correct. That's why I said a pull request for a function to close all idle connections would be useful 😄

**Comment by edwvee** [comment]
Thank you. In Shutdown I stuck here: https://github.com/valyala/fasthttp/blob/711e421685d419ab41ef7cfe4886d069ffb2db9c/server.go#L1820

**Comment by erikdubbelboer** [comment]
Correct. I would close idle connections before it. When we're in this loop it should only be waiting for active connections which is will close once the current request is done. If an idle connection just send a request it will be handled like this as well. Maybe you can make a pull request with what you have so far?

**Comment by RyouZhang** [comment]
> 

Maybe you need to waitting the conn trigger idle timeout, then close it.
