### ISSUE TITLE
Server return normally but client timeout 

### ISSUE THREAD

**Issue by horizonzy** [valyala/fasthttp#1104]
Hi, team.
Recently I found a problem.
My client print error log as below:
```
t=2021-09-16T15:00:47+0800 lvl=eror msg="[fetchAllData] http request error, cause: timeout" caller=table.go:128
```

It looks like a http request timeout, my client timeout is `10s`. 
client code:
```
var client = &fasthttp.Client{
	Name: "CLIENT",
	MaxConnsPerHost: 16,
	MaxIdleConnDuration: time.Second * 50,
	ReadBufferSize:      10 * 1024 * 1024,
	WriteBufferSize:     1 * 1024,
}
```
use way:
```
	var err error = nil
	url := cfg.API.MdbStoreHost + "/table/data/all"
	remoteResp := fasthttp.AcquireResponse()
	req := fasthttp.AcquireRequest()
	req.Header.SetContentType("application/json")
	req.Header.SetMethod("POST")
	defer func() {
		fasthttp.ReleaseRequest(req)
		fasthttp.ReleaseResponse(remoteResp)
	}()

	req.SetRequestURI(url)
	err = client.DoTimeout(req, remoteResp, time.Second*10)
	if err != nil {
		log.Root.Error("[fetchAllData] http request error, cause: " + err.Error())
	}
```

Worth to talk about that response body is large about 70M. I'm not sure is it problem.

Client error time is `2021-09-16T15:00:47+0800` and timeout is `10s`, so the request send time is about `2021-09-16T15:00:37+0800`.

So I trace the metrics data around that point in time at server side filter by this client ip.  

![image](https://user-images.githubusercontent.com/22524871/133585910-45ae0d76-038d-475b-a7d0-c0c8f7b92edb.png)

The first request response time is `15:00:39.156` and spend `1391ms`, it can infer send time is `15:00:37.765`. It matched the client request.

And we can also infer it by second request.

The second request response time is `15:00:48.693` and spend `927ms`, it can infer send time is `15:00:47.766`.  It matched client error log time. (my client will request again when request timeout)

At the server metrics data, the first request just spend `1391`, but fast http client request timeout. 

Is my way of use fasthttp wrong?

**Comment by horizonzy** [comment]
Hi. @erikdubbelboer, could you do me a favor.

**Comment by erikdubbelboer** [comment]
The way you use fasthttp looks correct. I think you have to do more testing with your server. For example, is spend_time including the network time? What if you do `time.Second*1000` and measure how long it takes?

**Comment by horizonzy** [comment]
> The way you use fasthttp looks correct. I think you have to do more testing with your server. For example, is spend_time including the network time? What if you do `time.Second*1000` and measure how long it takes?

Thanks for your reply. I noticed that DoTimeout() won't terminate if the response didn't return in timeout. Setting readTimeout at client will be better?
like this:
```
var ReadAllDataFromMdbStoreClient = &fasthttp.Client{
	Name: "CLIENT",
	MaxConnsPerHost: 16,
	MaxIdleConnDuration: time.Second * 50,
	ReadBufferSize:      10 * 1024 * 1024,
	WriteBufferSize:     1 * 1024,
	ReadTimeout: time.Second * 10,
}
```
If I config ReadTimeout, when request did't return in `10s`, the connection will be close by client?

**Comment by erikdubbelboer** [comment]
Yes, it's better to just use `client.Do` as it doesn't start any extra gorountines as well. But then you have to set `ReadTimeout` and `WriteTimeout`.

**Comment by horizonzy** [comment]
Thanks erikdubbelboer. I will modify the setting. 👍

**Comment by horizonzy** [comment]
Here a another error happen.


I modify the way. config readTimeout and writeTimeout both `10s`. 
```
var client = &fasthttp.Client{
	Name: "CLIENT",
	MaxConnsPerHost: 16,
	MaxIdleConnDuration: time.Second * 50,
	ReadBufferSize:      10 * 1024 * 1024,
	WriteBufferSize:     1 * 1024,
	ReadTimeout: time.Second * 10,
	WriteTimeout: time.Second * 10,
}

.....

	tx1 := time.Now().Unix()
	err = ReadAllDataFromMdbStoreClient.Do(req, remoteResp)
	if err != nil {
	tx2 := time.Now().Unix()
	fmt.Printf("it spend %d\n",tx2-tx1)
	fmt.Println(err.Error()) 
        }
```

I make server sleep 11s. 
But at client side, `client.Do(req, remoteResp)` spend 50s and return error. 

error info:
```
it spend 50
the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection
```

It seems the connection already be close? I checked my server keep-alive timeout, below is the info. 
```
 mac@apples-MacBook-Pro ~  curl -I -H "Connection: keep-alive" -X POST http://localhost:8080/raft/leader
HTTP/1.1 200
vary: accept-encoding
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 17 Sep 2021 11:01:42 GMT
Keep-Alive: timeout=60
Connection: keep-alive
```
client `MaxIdleConnDuration: 50s`.


I'm confused about this phenomenon.
1.the request spend 50s to wait. 
2.why did the error happen.

@erikdubbelboer sry for disturbance again.

**Comment by erikdubbelboer** [comment]
Can you provide me with a small standalone example program to test this with? Maybe I can also have access to the server?

I'm unable to reproduce this by myself.
I wrote this simple program to test what you are doing: https://gist.github.com/erikdubbelboer/b18aff34c1627dd57b10be13716f27a6
As you can see it just always times out after 10 seconds as expected:
```
% go run test.go
timeout
10.003879846s
timeout
10.005112542s
timeout
10.001776064s
timeout
10.005362893s
timeout
10.00077944s
timeout
10.005161722s
timeout
10.003921237s
timeout
10.0053424s
^Csignal: interrupt
```

**Comment by horizonzy** [comment]
@erikdubbelboer Hi, I found the problem. I create a new project with fasthttp 1.28.0. It works well.

The problem only occur in my particular project whcih use lower version, I will upgrade the version in this project.
