### ISSUE TITLE
Strange parts in the response body

### ISSUE THREAD

**Issue by gitoslavexxx** [valyala/fasthttp#1109]
I have the following code to send my query request with auto retrying on the bad dial connection
```Go
func queryRequest() []byte {
	req := fasthttp.AcquireRequest()
	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseRequest(req)
	defer fasthttp.ReleaseResponse(resp)

	req.SetConnectionClose()
	req.SetRequestURI(queryUrl)
	req.Header.SetMethod(fasthttp.MethodPost)
	req.Header.SetUserAgent(ua)
	req.SetBody(queryPostBytes)

	for {
		dialFunc := DefaultSocksDial
		httpClient := &fasthttp.Client{
			ReadTimeout:              10*time.Second,
			WriteTimeout:             10*time.Second,
			MaxConnDuration:          -1,
			MaxIdleConnDuration:      -1,
			MaxConnsPerHost:          2048,
			Dial: dialFunc,
		}
		err := httpClient.Do(req, resp)
		if err != nil {
			dialFunc = dialers.NextSocksDial()
			continue
		}

		break
	}
	
	return resp.Body()
}
```
it's works fine with a small amount of goroutines executing this func, but when the app increasing amount up to ~2000 the `resp.Body()` method starts to return some extra parts of data from the other responses. For example if one response contains `bodyfromresp1` then the other might return `bodyfromresp2mresp1` where `mresp1` is a part from the first response

**Comment by erikdubbelboer** [comment]
The return value of `resp.Body()` is invalid after `fasthttp.ReleaseResponse(resp)` (the memory will be reused for other responses). So you either have to make a copy of it or move your `fasthttp.ReleaseResponse(resp)` to after you are done using the body.

**Comment by YachenLee123** [comment]
> The return value of `resp.Body()` is invalid after `fasthttp.ReleaseResponse(resp)` (the memory will be reused for other responses). So you either have to make a copy of it or move your `fasthttp.ReleaseResponse(resp)` to after you are done using the body.

if return string(resp.Body()) , then  work is ok ? because  []byte is slice .
