### ISSUE TITLE
How close all requests on server by new request?

### ISSUE THREAD

**Issue by whimax** [valyala/fasthttp#1110]
Hi! How i can close all requests on server by new input request?
I try  this code for example, but this ia bad way:

```

package main

import (
	"flag"
	"fmt"
	"log"
	"time"

	"github.com/valyala/fasthttp"
)


var (
	addr   = flag.String("addr", ":8080", "TCP address to listen to")
	ctxArr []*fasthttp.RequestCtx
)

func main() {

	flag.Parse()

	h := requestHandler
	if err := fasthttp.ListenAndServe(*addr, h); err != nil {
		log.Fatalf("Error in ListenAndServe: %s", err)
	}
}
func requestHandler(ctx *fasthttp.RequestCtx) {
	ctxArr = append(ctxArr, ctx)

	if len(ctxArr) > 1 {
		for i := 0; i < len(ctxArr)-1; i++ {
			ctxArr[i].Conn().Close()
		}
		ctxArr = ctxArr[len(ctxArr)-1:]
	} else {
		fmt.Fprintf(ctx, "Your id %d\n\n", ctx.ConnID())
		time.Sleep(20 * time.Second)
		fmt.Fprintf(ctx, "after sleep msg!\n\n")
		return
	}
	fmt.Fprintf(ctx, "request breaked\n\n")
}

```

**Comment by erikdubbelboer** [comment]
I'm curious, what is the reason you want to do this?

What you are doing now doesn't make sense. You can not keep a reference to `ctx` after your handler has returned.
Also the response is only returned to the client once your handler returns. So the data you write before the `time.Sleep` only reaches the client after.

What you are trying to do can only be done using [`Hijack`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx.Hijack).

**Comment by whimax** [comment]
> 
> I'm curious, what is the reason you want to do this?
> 
a user on the frontend creates a request to the backend. The first request is long and the user creates a second one, which the backend quickly processes and sends a response, and the frontend displays it... everything is fine, but after a while the backend sends a response to the first request and the frontend displays an already unnecessary response...

**Comment by erikdubbelboer** [comment]
That sounds like a frontend issue and not something you should try to fix on the backend. If the frontend sends a second request it should ignore the responses from the requests before that. This is something that is easy to fix on the frontend. If you want to fix this on the backend you also need to know which requests come from the same client. It just doesn't make sense to do this on the backend.
