### ISSUE TITLE
FastHttp is slow with proxies.

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1112]
_### **First of all i really appreciate your hard work ! 
you made an great library
my issue is when im running the script without proxies im getting 20-29k post requests / per second 
but when i use Proxies i only get 400-800 requests
my proxies is good and stable but im sure that i made the proxy function wrong.
so what is the fastest way to add proxies to fasthttp function without low speed?**_

**Comment by tylitianrui** [comment]
more  detail, please

**Comment by erikdubbelboer** [comment]
Can you post some code you are currently using? That way we can see exactly what you want and maybe what is going wrong.

**Comment by DeathRowTools** [comment]
package main

import (
	"bytes"
	"fmt"
	"github.com/valyala/fasthttp"

	"io/ioutil"
	"math/rand"

	"strings"
	"time"
)

var counter int = 0
var badcounter int = 0
var content, _ = ioutil.ReadFile("dt.txt")
var lines = strings.Split(string(content), "\n")

var content2, _ = ioutil.ReadFile("proxy.txt")
var lines2 = strings.Split(string(content2), "\n")

func starting(target string) {
	for true {
		check(target)
	}
}

func check(target string) {
	sessionid := strings.Split(lines[rand.Intn(1000-10+1)+10], ":")[0]
	proxytouse := lines2[rand.Intn(3900-10+1)+10]
	proxytouse = strings.TrimSuffix(proxytouse, "\r")

	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)
	req.SetRequestURI("https://i.instagram.com/api/v1/accounts/set_username/")
	req.Header.SetMethod("POST")
	req.Header.Set("User-Agent", "Instagram 124.0.0.17.473 Android (28/9; 280dpi; 720x1382; samsung; SM-A105FN; a10; exynos7885; en_US; 192992565)")
	req.Header.Add("Accept-Language", "en-US,en;q=0.5")
	req.Header.Add("Cookie", "sessionid="+sessionid+";")
	req.Header.SetContentType("application/x-www-form-urlencoded")
	req.Header.Add("Connection", "close")
	req.SetBody([]byte("username=" + target))
	req.PostArgs()

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)

	err := fasthttp.Do(req, resp)
	if err != nil {
		badcounter++
		fmt.Println(err)
	}
	contentEncoding := resp.Header.Peek("Content-Encoding")
	var body []byte
	if bytes.EqualFold(contentEncoding, []byte("gzip")) {
		body, _ = resp.BodyGunzip()
	} else {
		body = resp.Body()
	}

	if strings.Contains(string(body), "This username isn't available.") == true || strings.Contains(string(body), "wait") == true {
		
		counter++
	} else {

		badcounter++
	}

	req.ConnectionClose()
	req.SetConnectionClose()
	resp.ConnectionClose()
	resp.SetConnectionClose()

}

func getrs() {
	for true {
		var oldint int = counter
		time.Sleep(1 * time.Second)
		var rs int = counter - oldint
		fmt.Printf("Good >> [%d] | R/S >> [%d] | Error: >> [%d].\n", counter, rs, badcounter)
	}
}

func main() {
	var target string
	fmt.Print("Enter your Target: ")
	fmt.Scanf("%s", &target)
	for i := 1; i < 200; i++ {
		go starting(target)
	}
	getrs()

}

**Comment by DeathRowTools** [comment]
Here is the code for the script Please Read the note.
https://pastebin.com/dSJD7XqN
===========
and here is the script with proxies.
Also Please read the note.
https://pastebin.com/Jq7SLVmE

**Comment by DeathRowTools** [comment]
@tylitianrui 
@erikdubbelboer 
if there is any thing i can do please help me with this its an life changing script for me :)

**Comment by erikdubbelboer** [comment]
One like 83 you are constantly creating a new `fasthttp.Client` which makes it impossible for it to reuse the connection which means it constantly has to authenticate with the proxy again. You need to change your code to reuse the `fasthttp.Client`.

How fast is your proxy? Cause if your proxy limits you to only 400-800 requests per second than of course no change is ever going to make it faster.

**Comment by DeathRowTools** [comment]
my proxies are super faster with no limits it can handle 100k request per second with no problem.
but how can i reuse the connection? but each connection must have a new proxy 
i dont want to use the same proxy like and just reuse it because this will kill the proxy
i want it to reuse the connection but with new proxies is that possible
again thank you for helping me to succeed with my goal.

**Comment by DeathRowTools** [comment]
i got 5000 proxies in my list
in c# my script gets 6k request per second
in node.js it gets 11k request per second 
thats why im trying to learn fasthttp so i can make 20k or even 3-5k is goos because it uses a low cpu load 
so i can run multi windows and i will get total of 20-30 k
any way what is the best method to use 5000 proxies as fast as possible?

**Comment by DeathRowTools** [comment]
W

**Comment by erikdubbelboer** [comment]
Maybe try something like this: https://play.golang.org/p/LEj2xFqsXLQ
I also fixed some other issues like using atomic counters when incrementing/reading them from different goroutines.

**Comment by DeathRowTools** [comment]
Thank you very much eric!!! I will try this right now

**Comment by DeathRowTools** [comment]
hi Erik good morning.
so i tried your script but it still gives me only 1300 request per second (its much better) than before
but still i need it to be around 3000-5000 is this possible?

**Comment by DeathRowTools** [comment]
and also im getting this error a lot 
the server closed connection before returning the first response byte. Make sure
the server returns 'Connection: close' response header before closing the conne
ction
what does this mean and how to solve it

**Comment by erikdubbelboer** [comment]
That means your proxy is closing the connection when it's unexpected.

I'm curious, can you share your nodejs code, I want to see why that would be so much faster.
