### ISSUE TITLE
Why fasthttp.URI does not handle port?

### ISSUE THREAD

**Issue by peczenyj** [valyala/fasthttp#1113]
Hello

I have some endpoints that maybe receive an url as parameter. To validate I usually do:

```go
                url := []byte{... }
                u := fasthttp.AcquireURI()
                defer fasthttp.ReleaseURI(u)

                if err := u.Parse(nil, url); err != nil {
                        return err
                }
                ... // other checks
```

However, this kind of url is considered valid, while the golang core package `net/url` return an error `invalid port ":=\\" after host`
```
https://.çèéà@&~!&:=\\/\"'`~<>|+-*()[]{}%$;,¥&&$22|||<>< 4ly8lzjmoNx233AXELDtyaFQiiUH-fd8c-CnXUJVYnGIs4Uwr-bptom5GCnWtsGMQxeM2ZhoKE973eKgs2Sjh6RePnyaLpCi6SiNSLevcMoraARrp88L-SgtKqd-XHAtSI8hiPRiXPQmDIA4BGhSgoc0nfn1PoYuGKKmDcZ04tANRc3iz4aF4-A1UrO8bLHTH7MEJvzx.someqa.fr/A/?&QS_BEGIN<&8{b'Ob=p*f> QS_END
```

I realize the fasthttp.URI ignores the port. This is by design? Should I use  `net/url`  to validate instead the URI Parse method ?

**Comment by erikdubbelboer** [comment]
This is fixed in https://github.com/valyala/fasthttp/commit/542a203b42a3cb722244e1ef74fda0804a926383

**Comment by peczenyj** [comment]
thanks a lot. do you know when it will be available?

**Comment by erikdubbelboer** [comment]
I always wait a couple of days before I tag a new release so people using master can try it before. It will probably be next week Monday.
