### ISSUE TITLE
Adaptor for fasthttp.Request and fasthttp.Response

### ISSUE THREAD

**Issue by benedictjohannes** [valyala/fasthttp#1114]
I've looked into `fasthttp/fasthttpadaptor/request.go` and the `ConvertRequest` function converts _to_ standard `net/http.Request`.

A lot of code is written to produce `net/http.Request`, or accepts an interface that satisfy `net/http.Do` function, making it not trivial to use `fasthttp.Client` without a converter.

Would you consider adding the reverse? This would likely require
- converting _from_ standard `net/http.Request` _to_ `fasthttp.Request`
- converting _from_ standard `net/http.Response` _to_ `fasthttp.Response`
- a type that implements 
```
Do(*net/http.Request) (*http.Response, error)
```

**Comment by erikdubbelboer** [comment]
A pull request to add functions for those conversions would be welcome. But I'm curious for your use case. Why aren't you just using `net/http` for everything? fasthttp is really only for some special cases where performance really matters. It feels to me that if you already have code using `net/http` then you probably don't have one of those cases and using fasthttp would only complicate your code unnecessarily.
