### ISSUE TITLE
Lots of errors with reverse proxy and apache bench

### ISSUE THREAD

**Issue by terhechte** [valyala/fasthttp#112]
Hey,

I'm trying out a really simple reverse proxy. My initial implementation was much more complex, so I've broken it down to something rather simple:

``` go
var proxyClient = &fasthttp.HostClient{
    Addr: "127.0.0.1:8077",
    ReadTimeout: 30 * time.Second,
    WriteTimeout: 30 * time.Second,
    ReadBufferSize: 64 * 1024,
    WriteBufferSize: 64 * 1024,
}

func reverseProxyHandler(ctx *fasthttp.RequestCtx) {
    req := &ctx.Request
    resp := &ctx.Response
    // uncommenting the following line doesn't change anything
    //req.Header.Add("Connection", "close")
    if err := proxyClient.Do(req, resp); err != nil {
        ctx.Logger().Printf("error when proxying the request: %s", err)
    }
}
```

My setup is that I have a separate web server (during testing I'm using Cherokee, but I've also tried Python's SimpleHTTPServer, however in production I won't be able to influence the server that is being proxied). And the fasthttp server should just read the data, perform some modifications, and return it. My current, production, solution is written in OpenResty/Lua, however I wanted to have something more type safe and extendable, so I decided to try fasthttp.

When I run it with apache bench, though, the code above generates a lot of errors. The errors are:
"no free connections available to host" and "the server closed connection before returning the first response byte".

The same apache bench, run against the OpenResty server, on the other hands, works flawlessly. I.e. the following run "ab -n 1000 -c 1000 URL" returns the following results:

```
Server Software:        OpenResty
Concurrency Level:      1000
Time taken for tests:   7.409 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      93558 bytes
HTML transferred:       0 bytes
Requests per second:    134.96 [#/sec] (mean)
Time per request:       7409.358 [ms] (mean)
Time per request:       7.409 [ms] (mean, across all concurrent requests)
Transfer rate:          12.33 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       20   84  33.0     87     132
Processing:   163 3060 1741.4   3461    7259
Waiting:        0 2199 2366.9   3461    7259
Total:        292 3144 1724.6   3590    7284

Percentage of the requests served within a certain time (ms)
  50%   3590
  66%   3710
  75%   3727
  80%   3739
  90%   5674
  95%   7277
  98%   7281
  99%   7282
 100%   7284 (longest request)


Server Software:        fasthttp
Concurrency Level:      1000
Time taken for tests:   6.486 seconds
Complete requests:      1000
Failed requests:        466
   (Connect: 0, Receive: 0, Length: 466, Exceptions: 0)
Total transferred:      1633490 bytes
HTML transferred:       1462308 bytes
Requests per second:    154.18 [#/sec] (mean)
Time per request:       6485.739 [ms] (mean)
Time per request:       6.486 [ms] (mean, across all concurrent requests)
Transfer rate:          245.96 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       34  199  84.3    206     327
Processing:   261 1737 2074.1    622    6147
Waiting:      261 1737 2074.1    622    6147
Total:        295 1935 2127.4    922    6406

Percentage of the requests served within a certain time (ms)
  50%    922
  66%   2144
  75%   2267
  80%   3060
  90%   6190
  95%   6304
  98%   6370
  99%   6376
 100%   6406 (longest request)

```

With less concurrency settings everything works mostly fine though. What am I doing wrong?

Regards & Thanks,
Benedikt

**Comment by valyala** [comment]
As I know, `ab` doesn't use keepalive connections by default, so `ctx.Request.ConnectionClose()` returns true. This instructs `HostClient` closing connection after each request to upstream server. This may result in TCP connections' exhaustion under high load, since all the connections to the upstream server will be in `TIME_WAIT` or `CLOSE_WAIT` mode.

Try adding `ctx.Request.ResetConnectionClose()` before `proxyClient.Do`:

```go
func reverseProxyHandler(ctx *fasthttp.RequestCtx) {
    ctx.Request.ResetConnectionClose()
    if err := proxyClient.Do(&ctx.Request, &ctx.Response); err != nil {
        ctx.Logger().Printf("error when proxying the request: %s", err)
    }
}
```

**Comment by valyala** [comment]
@terhechte , did my suggestion help resolving your issue?

**Comment by terhechte** [comment]
Hey, thanks. I totally forgot about this issue. Yes, that helped.

**Comment by zhuqiuyang** [comment]
ask a question . i know i can control MaxIdleConnDuration between fasthttp server and upstream server with next line.
```go
var proxyClient = &fasthttp.HostClient{
    MaxIdleConnDuration: time.Duration,
}
```
But if i want control MaxIdleConnDuration between fasthttp server and user browser(client), how can i realize it. Did fasthttp have this method ?
thx.
@terhechte @valyala
