### ISSUE TITLE
fasthttp.Response does not handle Content-Type: text/event-stream properly

### ISSUE THREAD

**Issue by ShivanshVij** [valyala/fasthttp#1129]
If there's a webserver that FastHTTP is attempting to read from using the following:

```go
err = ctx.Response.Header.Read(bufferedNetConn)
if err != nil {
	ctx.SetConnectionClose()
	ctx.SetStatusCode(http.StatusBadGateway)
	_ = netConn.Close()
	return
}
```

Then then code will hang indefinitely if the webserver is attempting to stream data using the `text/event-stream` content-type. 

A potential solution is to go into the `fasthttp.readBody` function, check if the `resp.Header` for the `text/event-stream` content-type and if it's there, then we simply stream it using the BodyStreamWriter function. 

Alternatively, we could also just make the `resp.bodyBuffer` and `fashttp.readBody` functions exported, and users could check the headers and decide whether to stream or not themselves.

**Comment by erikdubbelboer** [comment]
https://github.com/valyala/fasthttp/issues/998#issuecomment-801248654

**Comment by ShivanshVij** [comment]
We're trying to use FastHTTP as a reverse proxy, so it's acting as both the client and the server.

It basically needs to be able to forward the text-stream, and if we default to always using the bodystreamwriter then performance takes a major hit.
