### ISSUE TITLE
Extract modules for buffers to separate library

### ISSUE THREAD

**Issue by stgleb** [valyala/fasthttp#113]
Hello, i'm going to use part of fast http for processing byte buffers. How about to extract all []byte/string related modules to separate library and allow people to use this small subset instead of including all fasthttp package to their project?

**Comment by valyala** [comment]
@stgleb , I'm going to create a separate package for working with byte buffer pools, which will be based on [bytebuffer.go](https://github.com/valyala/fasthttp/blob/master/bytebuffer.go). But I think this doesn't match your expectations.

So I'd recommend extracting relevant parts from `fasthttp` code and creating a separate package on your own. Then this package may be mentioned in `fasthttp` readme.

**Comment by erikdubbelboer** [comment]
I'm guessing this turned into https://github.com/valyala/bytebufferpool
