### ISSUE TITLE
client: URI is always parsed

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1141]
To perform an HTTP requests each time the `SetRequestURIBytes()` must be called. But internally the method just saves an URL and it is then parsed inside of `parseURI()`:
```go
func (req *Request) parseURI() error {
	if req.parsedURI {
		return nil
	}
	req.parsedURI = true
	return req.uri.parse(req.Header.Host(), req.Header.RequestURI(), req.isTLS)
}
```
My application has a bunch of fixed URLs like `http://example.com/api/` and I can call the ` req.uri.parse()` only once on initialization. And then I would like to just set this `fasthttp.URI` objects before sending the request with a new method `SetRequestURI(preparsedUri)`.

Is any reason why this wasn't implemented? Will you implement this or accept a PR with such functionality?

**Comment by erikdubbelboer** [comment]
To be honest I'm not sure why it was implemented like that. Yes I would accept a PR to support such functionality.

**Comment by stokito** [comment]
Thank you for merging, this should be useful if we have a base URI that can be copied and some part can be changed.
But I found even a better way for my case when API endpoint is static:
0. Create a separate request pool for each API endpoint
1. Create a request manually and set URI and headers
2. Execute the request
3. Put the request back to pool but without calling the Reset()
4. Next time when the request will be taken from the pool it will already have a parsed URI and headers. You just need to override a body

```go
var requestPool sync.Pool

func main() {
        reqBody := []byte("{\"id\": 1}")
        // AcquireRequest
	reqV := requestPool.Get()
	var req *fasthttp.Request
	if reqV != nil {
		req = reqV.(*fasthttp.Request)
	} else {
		req = &fasthttp.Request{}
		req.SetRequestURIBytes("http://example.com/api/v1/")
		req.Header.SetMethod(fasthttp.MethodPost)
		req.Header.SetContentType("application/json")
	}
	resp := fasthttp.AcquireResponse()
	req.SetBodyRaw(reqBody)
	err := fasthttp.Do(req, resp)
	// Same as fasthttp.ReleaseRequest but without reset
	requestPool.Put(req)
	fasthttp.ReleaseResponse(resp)
}
