### ISSUE TITLE
client: How to increase DNS TTL?

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1142]
The fasthttp caches DNS calls for 3 seconds. I have a heavy loaded system that calls a lot of APIs but all of them are very static.
How can I increase the internal cache TTL?
I found the `fasthttp.TCPDialer` that has the `DNSCacheDuration` but how can I configure my client to use the custom `TCPDialer`?

**Comment by erikdubbelboer** [comment]
You can use [`Client.Dial`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Client.Dial) to set to a custom `fasthttp.TCPDialer{ ... }.Dial` to overwrite the defaults.

**Comment by stokito** [comment]
Thank you @erikdubbelboer ! Here is an example how I did it:
```go
	client := &fasthttp.Client{
		Dial: (&fasthttp.TCPDialer{
			Concurrency:      4096,
			DNSCacheDuration: time.Hour,
		}).Dial,
	}
```
