### ISSUE TITLE
 Response body blocking

### ISSUE THREAD

**Issue by cachalots** [valyala/fasthttp#1146]
In version v1.31.0, it will not block, but it will block in the master branch.
I think this is related to HTTP/1.1 header "Connection: keep-alive".
``` go
package main

import "github.com/valyala/fasthttp"

func main() {
	fasthttp.ListenAndServe(":8080", func(ctx *fasthttp.RequestCtx) {
		c := fasthttp.HostClient{Addr: "neverssl.com"}
		var (
			req  = fasthttp.AcquireRequest()
			resp = fasthttp.AcquireResponse()
		)

		req.SetHost("neverssl.com")
		if err := c.Do(req, resp); err != nil {
			panic(err)
		}

		resp.Header.CopyTo(&ctx.Response.Header)

		// on the master branch only set header "Connection: close" will not block
		//ctx.Response.SetConnectionClose()

		ctx.Response.SetBody(resp.Body())
	})
}
```
```go.mod
module test-fasthttp

go 1.16

require github.com/valyala/fasthttp v1.31.1-0.20211104122440-931d0a452319
//require github.com/valyala/fasthttp v1.31.0
```
```curl
curl -i -vvv 127.0.0.1:8080 
```

**Comment by cachalots** [comment]
The problem should be that the first line (```HTTP/1.1 200 OK```) of the header is missing after the master version copy response header. ```HTTP/1.1 200 OK``` still exists after copy header in version 1.31.0.

I use curl version 7.64.1, after the request, the response will be blocked. If use version 7.79.1, you will get an error after the request  ```curl: (1) Received HTTP/0.9 when not allowed.```

**Comment by cachalots** [comment]
In the master version,  after copy the response header,  if I call ```ctx.Response.Header.IsHTTP11()```  , return true, I 
call ```ctx.Response.SetStatusCode(200)```, but there is no header(```HTTP/1.1 200 OK```) in the response header.

**Comment by erikdubbelboer** [comment]
This is currently being fixed in https://github.com/valyala/fasthttp/pull/1135 which should be merged very soon.
