### ISSUE TITLE
How to add a dynamic proxy to the request sent by the client?

### ISSUE THREAD

**Issue by thep0y** [valyala/fasthttp#1147]
I am using fasthttp to write a crawler program, and I need to use a proxy pool to set a different proxy for each request.
According to the http proxy in https://github.com/valyala/fasthttp/blob/master/fasthttpproxy/http.go, I use the shuffle algorithm to disrupt the proxy pool at each request and select the first proxy to pass in:
```go
pool := []string{"1", "2", "3", ...}
shuffle(pool)
client.Dial = fasthttpproxy.FasthttpHTTPDialer(pool[0])
```
Because the external variable `proxy` is used in the closure function `DialFunc` returned by `fasthttpproxy.FasthttpHTTPDialer`, no matter how many times `client.Dial = fasthttpproxy.FasthttpHTTPDialer(pool[0])` is executed, the final worked proxy is the `proxy` passed in for the first time, makes the proxy pool completely useless.
I haven't found a solution after thinking for a long time. Can someone help me?

**Comment by erikdubbelboer** [comment]
You should do something like this:
```go
dialers := []fasthttp.DialFunc{
  fasthttpproxy.FasthttpHTTPDialer("1"),
  fasthttpproxy.FasthttpHTTPDialer("2"),
  fasthttpproxy.FasthttpHTTPDialer("3"),
}

client.Dial = func(addr string) (net.Conn, error) {
  return dialers[rand.Intn(len(dialers))](addr)
}

**Comment by thep0y** [comment]
I have tried it, below is my code and running result:
```go
func main() {
	rand.Seed(time.Now().UnixNano())

	client := &fasthttp.Client{}

	dialers := []fasthttp.DialFunc{
		fasthttpproxy.FasthttpHTTPDialer("115.209.51.15:45104"),
		fasthttpproxy.FasthttpHTTPDialer("117.87.185.156:45111"),
		fasthttpproxy.FasthttpHTTPDialer("123.73.147.48:46603"),
		fasthttpproxy.FasthttpHTTPDialer("123.73.147.231:46603"),
		fasthttpproxy.FasthttpHTTPDialer("36.25.23.184:45148"),
	}

	client.Dial = func(addr string) (net.Conn, error) {
		return dialers[rand.Intn(len(dialers))](addr)
	}

	for i := 0; i < len(dialers); i++ {
		body := make([]byte, 0)
		_, body, err := client.Get(body, "https://httpbin.org/get")
		if err != nil {
			panic(err)
		}

		resp := make(map[string]interface{})
		json.Unmarshal(body, &resp)
		fmt.Println(resp["origin"])
	}
}
```
worked ips:
```
115.209.51.15
115.209.51.15
115.209.51.15
115.209.51.15
115.209.51.15
```

**Comment by erikdubbelboer** [comment]
That's because it's using a keepalive connection. If you want it to use a different proxy for each request you have to add a `Connection: close` header.
