### ISSUE TITLE
client: MaxIdleConnDuration can't be more than 10 seconds

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1149]
I have few questions about the mCleaner function:
https://github.com/valyala/fasthttp/blob/931d0a4523197a0d06def6ef32b1849f0663f5db/client.go#L544
Why the `MaxIdleConnDuration` can't be set to more than 10 seconds? `if sleep > 10S { sleep = 10S }`
```go
if sleep > 10*time.Second {
		sleep = 10 * time.Second
	}
```
Many idle connections are fine for my service and I would like to try a bigger timeout.

Also as far I understood here is a race because a new connection may be added before client removing `delete(m, k)` i.e. this  
```go
			v.connsLock.Lock()
			shouldRemove := v.connsCount == 0
			v.connsLock.Unlock()
			if shouldRemove {
				delete(m, k)
			}
```
Must be changed to:
```go
			v.connsLock.Lock()
			shouldRemove := v.connsCount == 0
			if shouldRemove {
				delete(m, k)
			}
			v.connsLock.Unlock()
```

@erikdubbelboer  you wrote this lines, could you please check it?
Thank you all

**Comment by stokito** [comment]
Just checked some existing PRs and looke like here the problem with conn lock is already solved: https://github.com/valyala/fasthttp/pull/1098/files#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfR548

**Comment by erikdubbelboer** [comment]
The 10 second max timeout in mCleaner has nothing to do with `MaxIdleConnDuration`. It's only used to clean up HostClients that don't have any open connections anymore, it doesn't close open connections.

The other issue has been fixed in: https://github.com/valyala/fasthttp/commit/f7c354c760cf6974f0a954eb2e024dceb842f002
