### ISSUE TITLE
fasthttp get404, but http get 200

### ISSUE THREAD

**Issue by bodhisatan** [valyala/fasthttp#1152]
![middle_img_v2_1491e0b4-7a37-4df2-a6e9-c718e7f95ceg](https://user-images.githubusercontent.com/35862184/140904457-75543bd7-44c6-4399-be72-5ab27d6cb566.png)

**Comment by erikdubbelboer** [comment]
You have to create a `fasthttp.Client` and set [`Client.DisablePathNormalizing`](https://pkg.go.dev/github.com/valyala/fasthttp#Client.DisablePathNormalizing) to `true`. And then use the `Get` method on that client.
