### ISSUE TITLE
how to let the client change proxy

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1153]
I have asked before about (how to make fasthttp faster) and all thanks to you now its really good
however i have an Q
how can i shuffle proxies to clients without getting spamblocked?
because client is reusing same proxy and with time the proxy gets blocked
is there a method like every 30 seconds let the proxy update in the clients?
Thanks in Advance {sorry for my bad ENG}

**Comment by erikdubbelboer** [comment]
You might want to look at this for example: https://github.com/valyala/fasthttp/issues/1147
