### ISSUE TITLE
Occasionally a required host header is missing from a request？

### ISSUE THREAD

**Issue by cpathlu** [valyala/fasthttp#1156]
**Error message**
    missing required Host header in request

**What happened?**
    Call the same interface concurrently, occasionally, 99.9% of requests are successful

**Fasthttp version**
v0.0.0-20160617101304-d42167fd04f6, v1.9.0 , v1.31.0

**Handler implementation**
```
Send request API: https://host:port/get/user/info

func (r *Router) Handler(ctx *fasthttp.RequestCtx) {
	if r.PanicHandler != nil {
		defer r.recv(ctx)
	}

	path := string(ctx.Path())
	method := string(ctx.Method())
   
        fmt.Println(&ctx.Request)
        // output: missing required Host header in request

        fmt.Println(string(ctx.Path()), string(ctx.Method())
        // output: / GET 

	if root := r.trees[method]; root != nil {
		if f, tsr := root.getValue(path, ctx); f != nil {
			......
                      return
		} else if method != "CONNECT" && path != "/" {
                        ......
                } 
	}

          ......

	// Handle 404
	if r.NotFound != nil {
		r.NotFound(ctx)
	} else {
		ctx.Error(fasthttp.StatusMessage(fasthttp.StatusNotFound),
			fasthttp.StatusNotFound)
	}
}
```

**Comment by erikdubbelboer** [comment]
How are you sending the requests?

Can you try the following handler and see if it still happens?
```go
func (r *Router) Handler(ctx *fasthttp.RequestCtx) {
        fmt.Println(&ctx.Request)
}
```

**Comment by cpathlu** [comment]
This thing may not reproduce, I will try your method

Here is a rough idea of how I call, and the call link

```
import (
	"crypto/tls"
	"fmt"
	"testing"
	"time"

	"github.com/astaxie/beego/httplib"
)

func Test_GetUserInfos(t *testing.T) {
	var i int
	for {
		i++
		time.Sleep(time.Millisecond * 10)
		go func(i int) {
			_, err := getUserInfos(i)
			if err != nil {
				panic(err)
			}
		}(i)
	}
}

func getUserInfos(i int) (interface{}, error) {
	url := fmt.Sprintf("https://host:port/get/user/info?id=%v", i)
	var data interface{}
	err := httplib.Get(url).
		SetTLSClientConfig(&tls.Config{InsecureSkipVerify: true}).
		SetTimeout(100*time.Second, 30*time.Second).ToJSON(&data)
	if err != nil {
		panic(err)
	}
	return data, err
}
```

Service invocation chain & Service deployment & Framework usage:

serviceA 	        -->   nginx proxy                     --> serviceB
k8s-pod		-->  nginx proxy		       --> k8s-pod
beego1.12.1	-->  openresty 1.15.8.2          --> fasthttp v0.0.0-20160617101304-d42167fd04f6, v1.9.0 , v1.31.0

**Comment by cpathlu** [comment]
I'm trying to output
fmt.Println("In:Handler", &ctx.Request, "path", string(ctx.Path()), "method:", string(ctx.Method()), "RequestURI:", string(ctx.Request.Header.RequestURI()))

Output:
In:Handler missing required Host header in request path / method: GET RequestURI: /get/user/info

ctx.Path() output is /
ctx.Request.Header.RequestURI() output is correct

**Comment by erikdubbelboer** [comment]
Ok, this is a bit confusing with fasthttp I guess. `fmt.Println(&ctx.Request)` invokes methods on `fasthttp.Request` that don't work for requests received in a server context. It's only for requests build for sending with a Client.
I think that is messing up the Request. I know it shouldn't, but the fasthttp API is complicated and things like that can't just easily be fixed.

What happens if you remove the `fmt.Println(&ctx.Request)`. Will `fmt.Println(string(ctx.Path()), string(ctx.Method())` still print the wrong path once in a while?

**Comment by cpathlu** [comment]
> Ok, this is a bit confusing with fasthttp I guess. `fmt.Println(&ctx.Request)` invokes methods on `fasthttp.Request` that don't work for requests received in a server context. It's only for requests build for sending with a Client. I think that is messing up the Request. I know it shouldn't, but the fasthttp API is complicated and things like that can't just easily be fixed.
> 
> What happens if you remove the `fmt.Println(&ctx.Request)`. Will `fmt.Println(string(ctx.Path()), string(ctx.Method())` still print the wrong path once in a while?

Yes, this problem is really complicated and not easy to troubleshoot

We have so many environments where this service is deployed that it seems to be more likely to trigger this issue in a standalone environment

ctx.Path() output is wrong "/" and ctx.Method() output is fine if fmt.Println(&ctx.Request) is removed

I'm now trying to use ctx.Request.URI().PathOriginal() and get 'path' by resolving ctx.Request.Header.RequestURI() internally through the service.

If you have a better way to share it with me, thank you very much 🙏

**Comment by erikdubbelboer** [comment]
Can you try `fmt.Printf("%#v", ctx.Request)`?

**Comment by cpathlu** [comment]
> fmt.Printf("%#v", ctx.Request)

No problem, I can try

**Comment by cpathlu** [comment]
> Can you try `fmt.Printf("%#v", ctx.Request)`?
Output：

fasthttp.Request{noCopy:fasthttp.noCopy{}, Header:fasthttp.RequestHeader{noCopy:fasthttp.noCopy{}, disableNormalizing:false, noHTTP11:true, connectionClose:true, cookiesCollected:false, rawHeadersParsed:true, contentLength:0, contentLengthBytes:[]uint8{0x30}, method:[]uint8{0x47, 0x45, 0x54}, requestURI:[]uint8{0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x3f, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x34, 0x39, 0x66, 0x32, 0x33, 0x64, 0x62, 0x66, 0x2d, 0x34, 0x61, 0x38, 0x32, 0x2d, 0x34, 0x63, 0x63, 0x36, 0x2d, 0x39, 0x37, 0x32, 0x38, 0x2d, 0x37, 0x31, 0x31, 0x36, 0x61, 0x31, 0x64, 0x61, 0x39, 0x35, 0x65, 0x31, 0x26, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x32, 0x32, 0x38, 0x61, 0x33, 0x37, 0x62, 0x36, 0x2d, 0x32, 0x37, 0x33, 0x39, 0x2d, 0x34, 0x64, 0x37, 0x39, 0x2d, 0x39, 0x37, 0x30, 0x31, 0x2d, 0x64, 0x36, 0x32, 0x35, 0x30, 0x62, 0x38, 0x32, 0x34, 0x64, 0x64, 0x37}, host:[]uint8{0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x64, 0x65, 0x76, 0x70, 0x6d, 0x63, 0x2e, 0x74, 0x2e, 0x6c, 0x61, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6e}, contentType:[]uint8(nil), userAgent:[]uint8{0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72}, h:[]fasthttp.argsKV{fasthttp.argsKV{key:[]uint8{0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x70}, value:[]uint8{0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39}, noValue:false}, fasthttp.argsKV{key:[]uint8{0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72}, value:[]uint8{0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39}, noValue:false}, fasthttp.argsKV{key:[]uint8{0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67}, value:[]uint8{0x67, 0x7a, 0x69, 0x70}, noValue:false}}, bufKV:fasthttp.argsKV{key:[]uint8{0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72}, value:[]uint8(nil), noValue:false}, cookies:[]fasthttp.argsKV(nil), rawHeaders:[]uint8{0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x64, 0x65, 0x76, 0x70, 0x6d, 0x63, 0x2e, 0x74, 0x2e, 0x6c, 0x61, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6e, 0xd, 0xa, 0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x70, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0xd, 0xa, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20, 0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0xd, 0xa, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x20, 0x67, 0x7a, 0x69, 0x70, 0xd, 0xa, 0xd, 0xa}, rawHeadersCopy:[]uint8{0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x64, 0x65, 0x76, 0x70, 0x6d, 0x63, 0x2e, 0x74, 0x2e, 0x6c, 0x61, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6e, 0xd, 0xa, 0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x50, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0xd, 0xa, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20, 0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0xd, 0xa, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x20, 0x67, 0x7a, 0x69, 0x70, 0xd, 0xa, 0xd, 0xa}}, uri:fasthttp.URI{noCopy:fasthttp.noCopy{}, pathOriginal:[]uint8{0x2f}, scheme:[]uint8{0x68, 0x74, 0x74, 0x70}, path:[]uint8{0x2f}, queryString:[]uint8{}, hash:[]uint8(nil), host:[]uint8{}, queryArgs:fasthttp.Args{noCopy:fasthttp.noCopy{}, args:[]fasthttp.argsKV{}, buf:[]uint8(nil)}, parsedQueryArgs:false, DisablePathNormalizing:false, fullURI:[]uint8{0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x2f}, requestURI:[]uint8{0x2f}, username:[]uint8(nil), password:[]uint8(nil)}, postArgs:fasthttp.Args{noCopy:fasthttp.noCopy{}, args:[]fasthttp.argsKV(nil), buf:[]uint8(nil)}, bodyStream:io.Reader(nil), w:fasthttp.requestBodyWriter{r:(*fasthttp.Request)(nil)}, body:(*bytebufferpool.ByteBuffer)(nil), multipartForm:(*multipart.Form)(nil), multipartFormBoundary:"", parsedURI:true, parsedPostArgs:false, keepBodyBuffer:true, isTLS:true, schemaUpdate:false}

**Comment by cpathlu** [comment]
> Can you try `fmt.Printf("%#v", ctx.Request)`?

output:
fasthttp.Request{noCopy:fasthttp.noCopy{}, Header:fasthttp.RequestHeader{noCopy:fasthttp.noCopy{}, disableNormalizing:false, noHTTP11:true, connectionClose:true, cookiesCollected:false, rawHeadersParsed:true, contentLength:0, contentLengthBytes:[]uint8{0x30}, method:[]uint8{0x47, 0x45, 0x54}, requestURI:[]uint8{0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x3f, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x34, 0x39, 0x66, 0x32, 0x33, 0x64, 0x62, 0x66, 0x2d, 0x34, 0x61, 0x38, 0x32, 0x2d, 0x34, 0x63, 0x63, 0x36, 0x2d, 0x39, 0x37, 0x32, 0x38, 0x2d, 0x37, 0x31, 0x31, 0x36, 0x61, 0x31, 0x64, 0x61, 0x39, 0x35, 0x65, 0x31, 0x26, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x32, 0x32, 0x38, 0x61, 0x33, 0x37, 0x62, 0x36, 0x2d, 0x32, 0x37, 0x33, 0x39, 0x2d, 0x34, 0x64, 0x37, 0x39, 0x2d, 0x39, 0x37, 0x30, 0x31, 0x2d, 0x64, 0x36, 0x32, 0x35, 0x30, 0x62, 0x38, 0x32, 0x34, 0x64, 0x64, 0x37}, host:[]uint8{0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x64, 0x65, 0x76, 0x70, 0x6d, 0x63, 0x2e, 0x74, 0x2e, 0x6c, 0x61, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6e}, contentType:[]uint8(nil), userAgent:[]uint8{0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72}, h:[]fasthttp.argsKV{fasthttp.argsKV{key:[]uint8{0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x70}, value:[]uint8{0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39}, noValue:false}, fasthttp.argsKV{key:[]uint8{0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72}, value:[]uint8{0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39}, noValue:false}, fasthttp.argsKV{key:[]uint8{0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67}, value:[]uint8{0x67, 0x7a, 0x69, 0x70}, noValue:false}}, bufKV:fasthttp.argsKV{key:[]uint8{0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72}, value:[]uint8(nil), noValue:false}, cookies:[]fasthttp.argsKV(nil), rawHeaders:[]uint8{0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x64, 0x65, 0x76, 0x70, 0x6d, 0x63, 0x2e, 0x74, 0x2e, 0x6c, 0x61, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6e, 0xd, 0xa, 0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x70, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0xd, 0xa, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20, 0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0xd, 0xa, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x20, 0x67, 0x7a, 0x69, 0x70, 0xd, 0xa, 0xd, 0xa}, rawHeadersCopy:[]uint8{0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x64, 0x65, 0x76, 0x70, 0x6d, 0x63, 0x2e, 0x74, 0x2e, 0x6c, 0x61, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x63, 0x6e, 0xd, 0xa, 0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x50, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0xd, 0xa, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20, 0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0xd, 0xa, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x20, 0x67, 0x7a, 0x69, 0x70, 0xd, 0xa, 0xd, 0xa}}, uri:fasthttp.URI{noCopy:fasthttp.noCopy{}, pathOriginal:[]uint8{0x2f}, scheme:[]uint8{0x68, 0x74, 0x74, 0x70}, path:[]uint8{0x2f}, queryString:[]uint8{}, hash:[]uint8(nil), host:[]uint8{}, queryArgs:fasthttp.Args{noCopy:fasthttp.noCopy{}, args:[]fasthttp.argsKV{}, buf:[]uint8(nil)}, parsedQueryArgs:false, DisablePathNormalizing:false, fullURI:[]uint8{0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x2f}, requestURI:[]uint8{0x2f}, username:[]uint8(nil), password:[]uint8(nil)}, postArgs:fasthttp.Args{noCopy:fasthttp.noCopy{}, args:[]fasthttp.argsKV(nil), buf:[]uint8(nil)}, bodyStream:io.Reader(nil), w:fasthttp.requestBodyWriter{r:(*fasthttp.Request)(nil)}, body:(*bytebufferpool.ByteBuffer)(nil), multipartForm:(*multipart.Form)(nil), multipartFormBoundary:"", parsedURI:true, parsedPostArgs:false, keepBodyBuffer:true, isTLS:true, schemaUpdate:false}

**Comment by cpathlu** [comment]
> Can you try `fmt.Printf("%#v", ctx.Request)`?

I've replaced host with "0x74,0x65,0x73,0x74,0x2E,0x63,0x6F,0x6D", Other information has not changed

Output:

fasthttp.Request{noCopy:fasthttp.noCopy{}, Header:fasthttp.RequestHeader{noCopy:fasthttp.noCopy{}, disableNormalizing:false, noHTTP11:true, connectionClose:true, cookiesCollected:false, rawHeadersParsed:true, contentLength:0, contentLengthBytes:[]uint8{0x30}, method:[]uint8{0x47, 0x45, 0x54}, requestURI:[]uint8{0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x67, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x3f, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x34, 0x39, 0x66, 0x32, 0x33, 0x64, 0x62, 0x66, 0x2d, 0x34, 0x61, 0x38, 0x32, 0x2d, 0x34, 0x63, 0x63, 0x36, 0x2d, 0x39, 0x37, 0x32, 0x38, 0x2d, 0x37, 0x31, 0x31, 0x36, 0x61, 0x31, 0x64, 0x61, 0x39, 0x35, 0x65, 0x31, 0x26, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x3d, 0x32, 0x32, 0x38, 0x61, 0x33, 0x37, 0x62, 0x36, 0x2d, 0x32, 0x37, 0x33, 0x39, 0x2d, 0x34, 0x64, 0x37, 0x39, 0x2d, 0x39, 0x37, 0x30, 0x31, 0x2d, 0x64, 0x36, 0x32, 0x35, 0x30, 0x62, 0x38, 0x32, 0x34, 0x64, 0x64, 0x37}, host:[]uint8{0x74,0x65,0x73,0x74,0x2E,0x63,0x6F,0x6D}, contentType:[]uint8(nil), userAgent:[]uint8{0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72}, h:[]fasthttp.argsKV{fasthttp.argsKV{key:[]uint8{0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x70}, value:[]uint8{0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39}, noValue:false}, fasthttp.argsKV{key:[]uint8{0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72}, value:[]uint8{0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39}, noValue:false}, fasthttp.argsKV{key:[]uint8{0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67}, value:[]uint8{0x67, 0x7a, 0x69, 0x70}, noValue:false}}, bufKV:fasthttp.argsKV{key:[]uint8{0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72}, value:[]uint8(nil), noValue:false}, cookies:[]fasthttp.argsKV(nil), rawHeaders:[]uint8{0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x74,0x65,0x73,0x74,0x2E,0x63,0x6F,0x6D, 0xd, 0xa, 0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x70, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0xd, 0xa, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20, 0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0xd, 0xa, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x20, 0x67, 0x7a, 0x69, 0x70, 0xd, 0xa, 0xd, 0xa}, rawHeadersCopy:[]uint8{0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x74,0x65,0x73,0x74,0x2E,0x63,0x6F,0x6D, 0xd, 0xa, 0x58, 0x2d, 0x52, 0x65, 0x61, 0x6c, 0x2d, 0x49, 0x50, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x58, 0x2d, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x46, 0x6f, 0x72, 0x3a, 0x20, 0x31, 0x30, 0x2e, 0x34, 0x39, 0x2e, 0x31, 0x36, 0x34, 0x2e, 0x34, 0x39, 0xd, 0xa, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0xd, 0xa, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x3a, 0x20, 0x62, 0x65, 0x65, 0x67, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0xd, 0xa, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x2d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x20, 0x67, 0x7a, 0x69, 0x70, 0xd, 0xa, 0xd, 0xa}}, uri:fasthttp.URI{noCopy:fasthttp.noCopy{}, pathOriginal:[]uint8{0x2f}, scheme:[]uint8{0x68, 0x74, 0x74, 0x70}, path:[]uint8{0x2f}, queryString:[]uint8{}, hash:[]uint8(nil), host:[]uint8{}, queryArgs:fasthttp.Args{noCopy:fasthttp.noCopy{}, args:[]fasthttp.argsKV{}, buf:[]uint8(nil)}, parsedQueryArgs:false, DisablePathNormalizing:false, fullURI:[]uint8{0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x2f}, requestURI:[]uint8{0x2f}, username:[]uint8(nil), password:[]uint8(nil)}, postArgs:fasthttp.Args{noCopy:fasthttp.noCopy{}, args:[]fasthttp.argsKV(nil), buf:[]uint8(nil)}, bodyStream:io.Reader(nil), w:fasthttp.requestBodyWriter{r:(*fasthttp.Request)(nil)}, body:(*bytebufferpool.ByteBuffer)(nil), multipartForm:(*multipart.Form)(nil), multipartFormBoundary:"", parsedURI:true, parsedPostArgs:false, keepBodyBuffer:true, isTLS:true, schemaUpdate:false}

**Comment by erikdubbelboer** [comment]
What version of fasthttp are you using? I see `rawHeadersParsed` which was removed 2 years ago: https://github.com/valyala/fasthttp/commit/bcaa594b413c26d748b2201d2c59476617ca789a

Can you try upgrading to the latest version and print the same again when it goes wrong?

**Comment by cpathlu** [comment]
> What version of fasthttp are you using? I see `rawHeadersParsed` which was removed 2 years ago: [bcaa594](https://github.com/valyala/fasthttp/commit/bcaa594b413c26d748b2201d2c59476617ca789a)
> 
> Can you try upgrading to the latest version and print the same again when it goes wrong?

The current version is  v1.9.0

You can try the upgrade. I have tried v1.31.0 before

**Comment by erikdubbelboer** [comment]
Please try `v1.33.0` and show the same output again when it goes wrong so I can see the internal state and what might go wrong.
