### ISSUE TITLE
FasthttpHTTPDialer return 502 for proxy?

### ISSUE THREAD

**Issue by koteesy** [valyala/fasthttp#1158]
Hello!

i'm trying to learn fasthttp library, and doing some tests, and not all working exactly what i expected =D

For example, i create a host client:

```
var hostClient = fasthttp.HostClient{
	Addr:                          "httpbin.org",
	Name:                          "Http bin",
	MaxConns:                      100000,
	MaxConnWaitTimeout:            100000,
	Dial: fasthttpproxy.FasthttpHTTPDialer("my proxy"),
}
```

Try to do some request:

```
func makeFastHttpRequest () (*fasthttp.Response, []byte, error) {
	req := fasthttp.AcquireRequest()
	resp := fasthttp.AcquireResponse()
	
	defer func() {
		fasthttp.ReleaseResponse(resp)
		fasthttp.ReleaseRequest(req)
	}()

        uri := "https://httpbin.org/get"

	req.SetRequestURI(uri)

	req.Header.SetMethod("GET")

	req.Header.Add("Connection", "close")
	req.Header.Add("Sorry", "We testing GO client, please don't ban us!")

	err := hostClient.DoTimeout(req, resp, time.Duration(time.Second * 10))

	if err != nil {
		return nil, nil, err
	}

	return resp, resp.Body(), nil
}
```

And get error: fast error could not connect to proxy: (here my proxy url) status code: 502

But if i change client to:
```
var hostClient = fasthttp.Client{
	//Name:                          "Http bin",
	MaxConnWaitTimeout:            100000,
	MaxConnsPerHost: 10000,
	Dial: fasthttpproxy.FasthttpHTTPDialer("my proxy"),
}
```

```makeFastHttpRequest``` start working, and i can get result.

But if i try to request http url instead of https, i get the same error with 502 code, like that: ```uri := "http://httpbin.org/get"```

When default http client working well with http/https urls with my proxy ( like that )
```
func getClient() *http.Client {
	proxyUrl, err := url.Parse("http://myproxy")

	if err != nil {
		log.Fatal("Proxy error", err.Error())
	}

	return &http.Client{
		Timeout: time.Second * 60,
		Transport: &http.Transport{
			MaxIdleConnsPerHost: 1000,
			MaxIdleConns: 1000,
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
			Proxy: http.ProxyURL(proxyUrl),
	}}
}
````

Thanks!

**Comment by erikdubbelboer** [comment]
```go
func makeFastHttpRequest () (*fasthttp.Response, []byte, error) {
	req := fasthttp.AcquireRequest()
	resp := fasthttp.AcquireResponse()
	
	defer func() {
		fasthttp.ReleaseResponse(resp)
		fasthttp.ReleaseRequest(req)
	}()

	...

	return resp, resp.Body(), nil
}
```
You can't release a request and return it, that will cause all kinds of issues.

But not the issue where your proxy is returning 502. You'll have to look at your proxy to find out why, I'm sure it will return some status message.

If I were you I would just use `net/http`. If your use case requires proxies, fasthttp is overkill and completely not needed.

**Comment by koteesy** [comment]
> But not the issue where your proxy is returning 502. You'll have to look at your proxy to find out why, I'm sure it will return some status message.

But if the standard http.client works fine with a proxy like http/https - isn't the fact that fast http doesn't work with it, it's not a fasthttp problem?

 > If I were you I would just use net/http. If your use case requires proxies, fasthttp is overkill and completely not needed.

Yea,i read description on the package, and also i do some tests with a lot of requests, and i think fasthttp is for us, because on default http.client we has a big cpu usage

Also, can you please say - can we pass proxies to HostClient?

**Comment by erikdubbelboer** [comment]
Could be a fasthttp issue, could be the proxy doing things wrong or could be anything else.

Have you tried for example removing these?
```
req.Header.Add("Connection", "close")
req.Header.Add("Sorry", "We testing GO client, please don't ban us!")
```

HostClient should work with a proxy, but keep in mind that HostClient is really for a single domain and protocol. You can't use the same HostClient to make requests to http and https or to different domains.

I would need to see your full code and get access to your proxy to really debug this issue.

Can you try running your code with `-race` to see if you have any other concurrency bugs?

**Comment by koteesy** [comment]
> Could be a fasthttp issue, could be the proxy doing things wrong or could be anything else.
> 
> Have you tried for example removing these?
> 
> ```
> req.Header.Add("Connection", "close")
> req.Header.Add("Sorry", "We testing GO client, please don't ban us!")
> ```
> 
> HostClient should work with a proxy, but keep in mind that HostClient is really for a single domain and protocol. You can't use the same HostClient to make requests to http and https or to different domains.
> 
> I would need to see your full code and get access to your proxy to really debug this issue.
> 
> Can you try running your code with `-race` to see if you have any other concurrency bugs?

I don't think here's a concurrency problem, full code you can see [here](https://pastebin.com/HJdLRJVy)

Removing headers do nothing, still get 502

I try to change my proxy server to proxies [from this free proxies](http://free-proxy.cz/ru/proxylist/country/RU/https/uptime/all) and still see same result..

Requesting ```https``` urls working well with fasthttp, but ```http``` urls not working

Requesting ```http/https``` urls working well with default http.client

**Comment by koteesy** [comment]
@erikdubbelboer


> > Could be a fasthttp issue, could be the proxy doing things wrong or could be anything else.
> > Have you tried for example removing these?
> > ```
> > req.Header.Add("Connection", "close")
> > req.Header.Add("Sorry", "We testing GO client, please don't ban us!")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > HostClient should work with a proxy, but keep in mind that HostClient is really for a single domain and protocol. You can't use the same HostClient to make requests to http and https or to different domains.
> > I would need to see your full code and get access to your proxy to really debug this issue.
> > Can you try running your code with `-race` to see if you have any other concurrency bugs?
> 
> I don't think here's a concurrency problem, full code you can see [here](https://pastebin.com/HJdLRJVy)
> 
> Removing headers do nothing, still get 502
> 
> I try to change my proxy server to proxies [from this free proxies](http://free-proxy.cz/ru/proxylist/country/RU/https/uptime/all) and still see same result..
> 
> Requesting `https` urls working well with fasthttp, but `http` urls not working
> 
> Requesting `http/https` urls working well with default http.client

**Comment by erikdubbelboer** [comment]
I'm sorry but I don't have time to help you debug that much code. Can you make a small standalone example that I can run that shows how it's going wrong? Just a `func main()` with the code in it please.

**Comment by koteesy** [comment]
> I'm sorry but I don't have time to help you debug that much code. Can you make a small standalone example that I can run that shows how it's going wrong? Just a `func main()` with the code in it please.

I just can't give you our proxy because they appear only for our server, I'll try to buy some proxy and let you know

**Comment by erikdubbelboer** [comment]
Maybe you can use one of those free proxies?

**Comment by koteesy** [comment]
> Maybe you can use one of those free proxies?

If I take one of them and throw off the sample code - at the time when you check, it may no longer be available. But I will definitely come up with something, while I was testing it all, I realized that the problem may be related to redirects, some proxies give 301/302 - and I can normally read this answer in fasthttpclient, and some give an error instead of 301 /302.

**Comment by jw6602** [comment]
> @erikdubbelboer
> 
> > Could be a fasthttp issue, could be the proxy doing things wrong or could be anything else.
> > Have you tried for example removing these?
> > ```
> > req.Header.Add("Connection", "close")
> > req.Header.Add("Sorry", "We testing GO client, please don't ban us!")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > HostClient should work with a proxy, but keep in mind that HostClient is really for a single domain and protocol. You can't use the same HostClient to make requests to http and https or to different domains.
> > I would need to see your full code and get access to your proxy to really debug this issue.
> > Can you try running your code with `-race` to see if you have any other concurrency bugs?
> 
> I don't think here's a concurrency problem, full code you can see [here](https://pastebin.com/HJdLRJVy)
> 
> Removing headers do nothing, still get 502
> 
> I try to change my proxy server to proxies [from this free proxies](http://free-proxy.cz/ru/proxylist/country/RU/https/uptime/all) and still see same result..
> 
> Requesting `https` urls working well with fasthttp, but `http` urls not working
> 
> Requesting `http/https` urls working well with default http.client

fasthttp client doesn't support http/https proxies over http sites. This is b/c we the connect proxy are used for the https sites  only.
