### ISSUE TITLE
Cors support

### ISSUE THREAD

**Issue by jadbox** [valyala/fasthttp#116]
I wonder if anyone has been able to get Cors working with fasthttp or if there's a module for it (although I couldn't find one).

**Comment by hexadecy** [comment]
There is one middleware for Echo v2:
[Echo Cors](https://github.com/labstack/echo/blob/master/middleware/cors.go)

And another one for Iris:
[Iris Cors](https://github.com/kataras/iris/blob/master/middleware/cors/cors.go)

They are pretty similar to https://github.com/rs/cors

**Comment by kataras** [comment]
@hexadecy  Just to know: Iris' cors is rs/cors for fasthttp [as noted in the first line](https://github.com/kataras/iris/blob/master/middleware/cors/cors.go#L1)

**Comment by kataras** [comment]
@hexadecy  Good to know: Iris' cors is rs/cors for fasthttp [as noted in the first line](https://github.com/kataras/iris/blob/master/middleware/cors/cors.go#L1)

**Comment by valyala** [comment]
Added `question` label to the issue, so it could be located via the link in the last FAQ entry on [README.md](https://github.com/valyala/fasthttp/blob/master/README.md).

**Comment by valyala** [comment]
Closing the issue, since there are no plans for adding Cors support directly into `fasthttp`.

**Comment by felipemfp** [comment]
If anyone is looking for a well tested and pure fasthttp middleware, there's [lab259/cors](https://github.com/lab259/cors) (which is a fork of [rs/cors](https://github.com/rs/cors) targetting fasthttp).

**Comment by tsingson** [comment]
> If anyone is looking for a well tested and pure fasthttp middleware, there's [lab259/cors](https://github.com/lab259/cors) (which is a fork of [rs/cors](https://github.com/rs/cors) targetting fasthttp).

cool,  I like it.
