### ISSUE TITLE
client: AcquireRequestAndResponse()

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1160]
To perform a request with http client we need to acquireboth request and response:
```
req := fasthttp.AcquireRequest()
res := fasthttp.AcquireResponse()
```
Internally they'll make two `sync.Pool.Get()` calls and may make these two structs.
What if I declare a single struct that contains both Request and Response so they'll be initialized at once and store them in the same `sync.Pool`:

```
type ReqResp struct {
	fasthttp.Request
	fasthttp.Response
}

reqResp := fasthttp.AcquireRequestAndResponse()
req := &reqResp.Request
res := &reqResp.Response
```

Will it have a performance benefit? Or this doesn't worth to do?

**Comment by erikdubbelboer** [comment]
I don't think it's worth to do this. `sync.Pool.Get` takes nanoseconds, you won't be able to measure the impact.
