### ISSUE TITLE
Client returns an error about ErrConnectionClosed

### ISSUE THREAD

**Issue by r0ckysec** [valyala/fasthttp#1168]
```
2021/12/02 19:19:51 fasthttp.go:138:  the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection
```
My client configuration
```
client: &fasthttp.Client{
	TLSConfig: &tls.Config{
		InsecureSkipVerify: true,
		MinVersion:         tls.VersionTLS10,
	},
	MaxConnsPerHost: 2000,
	MaxIdleConnDuration: 10 * time.Second,
	MaxConnDuration: 15 * time.Second,
	ReadTimeout:  5 * time.Second,
	WriteTimeout: 10 * time.Second,
	MaxConnWaitTimeout:        5 * time.Second,
	MaxIdemponentCallAttempts: 5,
},
```
![image](https://user-images.githubusercontent.com/44518337/144421773-80d711aa-bc11-4471-b778-bf3416f11f69.png)
And i set SetConnectionClose sets 'Connection: close' request header.
But it still doesn't work
How can i fix it？？

**Comment by erikdubbelboer** [comment]
This means the connection was closed before a response was received. Either your server doesn't like the request and closes the connection for some reason. Or maybe `ReadTimeout:  5 * time.Second,` is too low and the server takes longer to respond.

**Comment by r0ckysec** [comment]
In high concurrency, I caught the request message:
```
GET /xxx.login HTTP/1.1
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0
Host: xxx.xxx.com
Connection: close



HTTP/1.1 200 OK
Date: Fri, 03 Dec 2021 07:33:20 GMT
Content-Length: 0


```
In this case, disconnect it so that it does not report an error?

**Comment by erikdubbelboer** [comment]
Sounds like it's an issue on the server side. Nothing fasthttp can do about that I'm afraid.

**Comment by r0ckysec** [comment]
It's okay, thanks for the help, the concurrent performance is very good
