### ISSUE TITLE
goroutine resource leak for tcpAddrsClean()

### ISSUE THREAD

**Issue by greenb6939** [valyala/fasthttp#1170]
```
func (d *TCPDialer) tcpAddrsClean() {
	expireDuration := 2 * d.DNSCacheDuration
	for {
		time.Sleep(time.Second)
		t := time.Now()
		d.tcpAddrsMap.Range(func(k, v interface{}) bool {
			if e, ok := v.(*tcpAddrEntry); ok && t.Sub(e.resolveTime) > expireDuration {
				d.tcpAddrsMap.Delete(k)
			}
			return true
		})

	}
}
```

Hi Team,
I'm tracking down an issue I have when using the fasthttp.TCPDialer{} in my fasthttp.Client{}. It appears that every new connection is resulting in a call to the `(d *TCPDialer) dial()` method which fires off a goroutine for DNS cache cleanup via `go d.tcpAddrsClean()`.

I was wondering if it was intentional to have the `tcpAddrsCleanup()` loop forever or if there was supposed to be a conditional check on the DNS cache map for breaking out of the loop and allowing the goroutine to exit?

I'd be happy to provide logs if they'd help!

**Comment by erikdubbelboer** [comment]
Can I see your code where you create and use your client? Are you sure you aren't constantly recreating it?

**Comment by greenb6939** [comment]
Thanks for your quick response, Erik. I added tracing all over the place and it looks like I am indeed using the same client with each request.

Here's a simple program that sets up and uses the fasthttp.Client like my production code does. Pay no attention to the 'proxy' struct and 'start' method, I stripped out the fasthttp.Server since it's not relevant here.

```
package main

import (
	"fmt"
	"github.com/valyala/fasthttp"
	"net"
	"runtime"
	"time"
)

type proxy struct {
	addr string
	port uint16

	client *fasthttp.Client
}

func (p *proxy) start() {
	p.client = &fasthttp.Client{
		Name:                     "FUBAR",
		NoDefaultUserAgentHeader: true,
		Dial: func(addr string) (net.Conn, error) {
			dialer := &fasthttp.TCPDialer{}
			if p.addr != "" && p.addr != "127.0.0.1" {
				dialer.LocalAddr = &net.TCPAddr{
					IP: net.ParseIP(p.addr),
				}
			}
			return dialer.Dial(addr)
		},
		MaxIdleConnDuration: 40 * time.Second,               //max idle time before closing connection (default is 10s)
		MaxConnWaitTimeout:  time.Duration(2 * time.Second), //max duration to wait for a free connection
	}
	fmt.Printf("(p *proxy) start() client=%p\n", p.client)
}

func httpReq(c *fasthttp.Client) {
	fmt.Printf("httpReq() client=%p\n", c)

	req, res := fasthttp.AcquireRequest(), fasthttp.AcquireResponse()
	defer func() {
		fasthttp.ReleaseRequest(req)
		fasthttp.ReleaseResponse(res)
	}()

	req.SetRequestURI("www.google.com")

	err := c.DoTimeout(req, res, time.Duration(2)*time.Second)

	if err == nil {
		resBody := make([]byte, len(res.Body()))
		copy(resBody, res.Body())
	}
}

func main() {
	proxy := &proxy{addr: "127.0.0.1", port: uint16(666)}
	proxy.start()

	for {
		fmt.Println("----------------------")
		fmt.Printf("goroutine count before req: %d\n", runtime.NumGoroutine())

		httpReq(proxy.client)

		time.Sleep(1 * time.Second)

		fmt.Printf("goroutine count after req: %d\n", runtime.NumGoroutine())

		time.Sleep(59 * time.Second)
	}
}
```

Here is my output after running several minutes. The ***DEBUG*** logs are traces I put into the client.go and tcpdialer.go files:

> (p *proxy) start() client=0xc000148000
> ----------------------
> goroutine count before req: 1
> httpReq() client=0xc000148000
> ***DEBUG*** fasthttp (c *Client) DoTimeout() client=0xc000148000
> ***DEBUG*** fasthttp clientDoTimeout(c=0xc000148000)
> ***DEBUG*** fasthttp (d *TCPDialer) dial() creating tcpAddrsClean() goroutine
> goroutine count after req: 3
> ----------------------
> goroutine count before req: 2
> httpReq() client=0xc000148000
> ***DEBUG*** fasthttp (c *Client) DoTimeout() client=0xc000148000
> ***DEBUG*** fasthttp clientDoTimeout(c=0xc000148000)
> ***DEBUG*** fasthttp (d *TCPDialer) dial() creating tcpAddrsClean() goroutine
> goroutine count after req: 5
> ----------------------
> goroutine count before req: 3
> httpReq() client=0xc000148000
> ***DEBUG*** fasthttp (c *Client) DoTimeout() client=0xc000148000
> ***DEBUG*** fasthttp clientDoTimeout(c=0xc000148000)
> ***DEBUG*** fasthttp (d *TCPDialer) dial() creating tcpAddrsClean() goroutine
> goroutine count after req: 6
> ----------------------
> goroutine count before req: 4
> httpReq() client=0xc000148000
> ***DEBUG*** fasthttp (c *Client) DoTimeout() client=0xc000148000
> ***DEBUG*** fasthttp clientDoTimeout(c=0xc000148000)
> ***DEBUG*** fasthttp (d *TCPDialer) dial() creating tcpAddrsClean() goroutine
> goroutine count after req: 7

**Comment by erikdubbelboer** [comment]
Ah I see `fasthttp.TCPDialer` also created a cleanup Goroutine that is never terminated. I think we should probably document this better. I'll start working on that. You can fix your case using:

```go
type proxy struct {
	addr string
	port uint16

	dialer *fasthttp.TCPDialer
	client *fasthttp.Client
}

func (p *proxy) start() {
	p.dialer = &fasthttp.TCPDialer{}

	if p.addr != "" && p.addr != "127.0.0.1" {
		p.dialer.LocalAddr = &net.TCPAddr{
			IP: net.ParseIP(p.addr),
		}
	}

	p.client = &fasthttp.Client{
		Name:                     "FUBAR",
		NoDefaultUserAgentHeader: true,
		Dial:                     p.dialer.Dial,
		MaxIdleConnDuration:      40 * time.Second,               //max idle time before closing connection (default is 10s)
		MaxConnWaitTimeout:       time.Duration(2 * time.Second), //max duration to wait for a free connection
	}
}
```

**Comment by greenb6939** [comment]
I confirmed that the *fasthttp.TCPDialer change resolved my issue. Thanks again @erikdubbelboer !
