### ISSUE TITLE
fasthttp and Nagle's algorithm

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1171]
im trying to make my fasthttp request latency down to 1ms or 5ms 
i saw on google that if i turned Nagle's algorithm off i will get better latency 
so my Q is how can i disable that with fasthttp?
in c# i turn it off this way:
ServicePointManager.UseNagleAlgorithm = false;

**Comment by erikdubbelboer** [comment]
Are you talking about a client or a server?

**Comment by DeathRowTools** [comment]
client

**Comment by erikdubbelboer** [comment]
Go already turns of Nagle's algorithm by default as you can see [here](https://github.com/golang/go/blob/a01a6d6efea52802f455849cd52ef7f8d049033a/src/net/tcpsock.go#L222) and in the [`TCPConn.SetNoDelay`](https://pkg.go.dev/net#TCPConn.SetNoDelay) documentation.
