### ISSUE TITLE
SetStreamBody example, please

### ISSUE THREAD

**Issue by jobber2955** [valyala/fasthttp#1172]
Sorry for this Noobie question, but i can't find a full example for SetStreamBody.

- Sitituation: I need to download a large file(5~ 20GB) from server.
- Except: Just like python requests req.get("http://xxx.com", stream=True) and then iter_content() it.So i don't run out of my memory for caching the response body.
- What i tried: Look into the [Official example](https://pkg.go.dev/github.com/valyala/fasthttp#example-RequestCtx.SetBodyStreamWriter) here but i don't quite understand the example, and Github Issue and Google, 
- I know fasthttp may not be suitable for me, but in my sitituation, i need to do lots of api request(each video require about 5~20 to get all the params i need) before i download the file, and these requests are small, so i figure fasthttp may be good for me. And i'm not very interesting in introducing too many package that has similar function(for example using fasthttp for doing the api requests and net/http for downloading the file). Also i think this is a good chance for me to understand fasthttp and study memory management as well.

Here's my existing code:
```
req := &fasthttp.Request{}
res := &fasthttp.Response{}
client := &fasthttp.Client{}
req.SetRequestURI(url)
req.Header.SetMethod(fasthttp.MethodGet)
req.Header.Set("Sec-Fetch-Mode", "navigate")
setCommonHeader(req)
for key, value := range d.cookie {
	req.Header.SetCookie(key, value)
}

if err := client.DoTimeout(req, res, 10 * time.Second); err != nil {
	d.logger.Error(err)
	return false
}
// Let's say body is 5GB, and definitely will run out of my memory.
body := res.Body()
```

I noticed that `SetBodyStream` is only avaiable when i using `*RequestCtx`, but in my case, i use a `&fasthttp.Request{}` and a `&fasthttp.Response{}` for doing the request. 
Is there any kindly full example for doing the request? If so i would be very grateful.

And also a little question here: What's the difference between `Directly create a *fasthttp.Request or Reponse or Client` and `Using the fasthttp.AcquireRequest etc`? Is my way of creating req, res, client not recommend?

**Comment by jobber2955** [comment]
I think maybe i need to create a ctx and set the ctx's body to "streaming mode", and pass a StreamReader to the ctx, then i can use the reader to reader out the response body?
But i don't understand how to implement the do request part.

Also i think if i can get this streaming function figured, I want be able to implement a progress indicator as well.
In python requests, iter_content is like a while loop, which i can implement a counter for downloaded bytes.
But in golang or fasthttp, i found the official example are using a io.reader. My thought is that maybe I need to implement the loop myself.
Something like 
```
ticker := time.NewTicker(time.second)
for {
    // Create a buffer
    // Copy Reader's content to buffer
    // Flush the Reader
    // Write the buffer's content to file and then clear the buffer
    // Check if Reader EOF, if EOF, then break the loop(How? By checking if Reader's length are 0? But if my connection are bad, will it be checked before it recieve the response? Or there is a flag like EOF that i can use to check?)
}
```

**Comment by erikdubbelboer** [comment]
I'm afraid body steaming is only supported for `fasthttp.Server` and not for `fasthttp.Client`. I would suggest you just use `net/http`. Unless you're doing thousands of requests per second you really don't need fasthttp.
