### ISSUE TITLE
How to optimize fasthttp appendBodyFixedSize memory overflow？

### ISSUE THREAD

**Issue by r0ckysec** [valyala/fasthttp#1177]
The program crashed during the operation, I used pprof to check the results as follows：
![image](https://user-images.githubusercontent.com/44518337/146571814-282ffa0a-fc8d-40ce-b9be-5e989b932632.png)

Flat | Flat% | Sum% | Cum | Cum% | Name | Inlined?
-- | -- | -- | -- | -- | -- | --
5871.80MB | 92.60% | 92.60% | 5871.80MB | 92.60% | github.com/valyala/fasthttp.appendBodyFixedSize

Custom function
```
func (req *HttpRequest) Request(method string, Url string, data string) (*fasthttp.Response, error) {
        request := fasthttp.AcquireRequest()
        defer fasthttp.ReleaseRequest(request)
        ... ... ...
        resp := fasthttp.AcquireResponse()
	request.SetConnectionClose()
	var err error
	if err = req.client.DoTimeout(request, resp, req.timeout); err != nil {
		log.Log.Println(err.Error())
		return nil, err
	}
	return resp, err
}
```
Function call
```
        ... ...
        resp, err := req.Get(url)
	if resp != nil {
		defer fasthttp.ReleaseResponse(resp)
	}
	if err != nil {
		log.Log.Println(err)
		return
	}
        ... ...
```

Where do I need to optimize?

**Comment by erikdubbelboer** [comment]
How big are your response bodies? I'm afraid fasthttp doesn't support response streaming, it will always read the whole body into memory. What are you doing with the response? If you would use `net/http` you could stream the body into a file for example, with fasthttp this is impossible.

**Comment by zeeshan-mohd** [comment]
Hi @erikdubbelboer I have used [fasthttp.SetBodySizePoolLimit](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#SetBodySizePoolLimit) but somehow my systems memory consumption is still not going down.It is a high QPS service, wondering what exactly is wrong on my end.It shoots up even if I make single request ( on test environment ) with > 100 Mb and the memory never comes down.Any thoughts on this ?

**Comment by zeeshan-mohd** [comment]
Hi @erikdubbelboer . I am getting the same issue ( instance not crashing , but reporting v. high memory ) in my service which has a high QPS and is receiving payload > 100 Mb.Although I have used **SetBodySizePoolLimit** and set 32kb ( req ) and 512kb ( res ) as limit , still i am seeing buffer not getting cleared and memory gradually rising.

**Comment by erikdubbelboer** [comment]
Have you tried using pprof to see where the allocations/leaks are?

**Comment by zeeshan-mohd** [comment]
> Have you tried using pprof to see where the allocations/leaks are?

Hey @erikdubbelboer yes , I see that the allocation is always done from **[appendBodyFixedSize](https://github.com/valyala/fasthttp/blob/2909827c57b79a4e4aa3fa7bd56affcba6fb6b8e/http.go#L2331)** method . The heap profile shows approx 98% memory allocated here.However , I assume [this](https://github.com/valyala/bytebufferpool/blob/master/pool.go#L53) allocation to be picked up by the garbage collector  when we have served the current request as I have disabled the **ReduceMemoryUsage** option and have used **SetBodySizePoolLimit** with 512Kb limit.Even if I make a single request with > 100 Mb resp payload I see memory spiking to > 200 Mb ( of the container ) and not settling down.There are no parallel/concurrent requests on the container , its isolated.

**Comment by erikdubbelboer** [comment]
Are you using Server or Client?

Keep in mind that Go doesn't release allocated memory back to your OS unless the OS asks for it. So unless there is memory pressure on the OS, Go will keep the memory and will keep reporting the usage.

**Comment by zeeshan-mohd** [comment]
> Are you using Server or Client?
> 
> Keep in mind that Go doesn't release allocated memory back to your OS unless the OS asks for it. So unless there is memory pressure on the OS, Go will keep the memory and will keep reporting the usage.

I am using it as a proxy , so using both server and client .
Also , I explicitly ran debug.FreeOSMemory() , but still no improvements I can see.The memory remains same.This would mean that bytes allocated during [appendBodyFixedSize](https://github.com/valyala/fasthttp/blob/2909827c57b79a4e4aa3fa7bd56affcba6fb6b8e/http.go#L2331) are not dereferenced and are not marked to be garbage collected ( ideally it should have been since I've SetBodySizePoolLimit ) .
Is there any other pool that might be the bytes ?

**Comment by erikdubbelboer** [comment]
`debug.FreeOSMemory()` doesn't free any memory. It just tells the OS that the memory isn't used anymore and can be reclaimed if needed. So this isn't going to change the memory usage if nothing else in your system is trying to claim that memory.

**Comment by zeeshan-mohd** [comment]
> `debug.FreeOSMemory()` doesn't free any memory. It just tells the OS that the memory isn't used anymore and can be reclaimed if needed. So this isn't going to change the memory usage if nothing else in your system is trying to claim that memory.

Thanks @erikdubbelboer this does look to be correct theory.I used madvdontneed=1 and the problem seems to be resolved.
Appreciate your time and effort.
