### ISSUE TITLE
Proxy Request

### ISSUE THREAD

**Issue by RoseMAgreement** [valyala/fasthttp#1179]
is there any example for setting up proxy for fasthttp client?

**Comment by erikdubbelboer** [comment]
I'm guessing you mean a reverse proxy, in that case https://github.com/yeqown/fasthttp-reverse-proxy is a good example.

**Comment by RoseMAgreement** [comment]
> I'm guessing you mean a reverse proxy, in that case https://github.com/yeqown/fasthttp-reverse-proxy is a good example.

Hello, its not that, using fasthttp to send http request but with proxy, is there an example for that? ive been researching didnt find any.

**Comment by erikdubbelboer** [comment]
There are examples how to create a client with different types of proxies here: https://pkg.go.dev/github.com/valyala/fasthttp@v1.31.0/fasthttpproxy

**Comment by RoseMAgreement** [comment]
thanks.
