### ISSUE TITLE
server: Get remote IP as a string

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1182]
I had to get a remote IP addr without the port and it took some time for me to write the solution:
```go
func getIp(reqCtx *fasthttp.RequestCtx) string {
	addr := reqCtx.RemoteAddr()
	ipAddr, ok := addr.(*net.TCPAddr)
	if !ok {
		return ""
	}
	return ipAddr.IP.String()
}
```

I think this must be a popular task that many users may want. How do you think, will it make any sense to add such method into the fasthttp library? Or most users just want to do `reqCtx.RemoteAddr().String()`

**Comment by erikdubbelboer** [comment]
Alternatively you can do this:
```go
func getIp(reqCtx *fasthttp.RequestCtx) string {
	ipport := reqCtx.RemoteAddr().String()
	if ip, err := net.SplitHostPort(ipport); err != nil {
		return ""
	} else {
		return ip
	}
}
```

I don't think it's needed to add method to fasthttp. We already expose way to many methods, I don't just want to add things to that that only take a couple of lines of code.

**Comment by stokito** [comment]
your sample looks like does more memory allocation. That's one of the reason why to add such a function :) Three lines to make a life easier for users. Anyway, I'm not insists, just a proposal
