### ISSUE TITLE
Shutdown() function freezes execution if at least one request was performed (v1.31.0)

### ISSUE THREAD

**Issue by waclawthedev** [valyala/fasthttp#1190]
How to reproduce:

**1. Execute the next code:** 
```
func main() {
	server := fasthttp.Server{Handler: func(ctx *fasthttp.RequestCtx) {
		ctx.WriteString("OK")
		return
	}}
	go server.ListenAndServe("0.0.0.0:8000")
	println("Press ENTER to shutdown")
	bufio.NewReader(os.Stdin).ReadString('\n')
	println("Shutdown ...")
	startTime := time.Now()
	server.Shutdown()
	fmt.Printf("%v", time.Since(startTime))
}
```

**2. Try to press ENTER after performing requests on 127.0.0.1:8000. The output something like that:**

```
Press ENTER to shutdown

Shutdown ...
36.1746735s
```

_**If you will try to press ENTER just after server started (without requests on 127.0.0.1:8000) - everything is ok:**_
```
Press ENTER to shutdown

Shutdown ...
101.211041ms
```

**Comment by erikdubbelboer** [comment]
This has been fixed by https://github.com/valyala/fasthttp/pull/1155 in the just released `v1.32.0`
