### ISSUE TITLE
How to process the following error?

### ISSUE THREAD

**Issue by zhangtong007** [valyala/fasthttp#1195]
When the *fasthttp.Client.Dotimeout method is executed, the following error is thrown:
**error when reading response headers: EOF. Buffer size=33, contents: "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x00\x81@\x00\x04\x00\x10\x00\x00"**

Check whether the error occurs as follows:
github.com/valyala/fasthttp@v1.9.0/header.go:1351
![image](https://user-images.githubusercontent.com/91560756/149607591-752fa64e-9cca-4d1a-9988-a2cc1d48f5bb.png)

go.mod:
require(
github.com/valyala/fasthttp v1.19.0
)
replace(
github.com/valyala/fasthttp => github.com/valyala/fasthttp v1.9.0
)

**Comment by erikdubbelboer** [comment]
It looks like the response you are getting doesn't make sense. But why are you using fasthttp v1.9.0? It's almost [2 years old](https://github.com/valyala/fasthttp/releases/tag/v1.9.0). There have been so many bugfixes. Please upgrade to v1.32.0 first and see if it still happens.

**Comment by zhangtong007** [comment]
> It looks like the response you are getting doesn't make sense. But why are you using fasthttp v1.9.0? It's almost [2 years old](https://github.com/valyala/fasthttp/releases/tag/v1.9.0). There have been so many bugfixes. Please upgrade to v1.32.0 first and see if it still happens.

After I upgraded to 1.32.0, I still had this problem.
![image](https://user-images.githubusercontent.com/91560756/149611550-ae42c83e-d186-437f-af0c-4e14a8272673.png)

**Comment by erikdubbelboer** [comment]
Are you sure it is updated? Is the ʼreplaceʼ line gone from your go.mod?

Anyways, I think it's a weird ​response you are getting. It's full of 0s while http is text based. Are you maybe sending a http request on a https port?

**Comment by zhangtong007** [comment]
> It looks like the response you are getting doesn't make sense. But why are you using fasthttp v1.9.0? It's almost [2 years old](https://github.com/valyala/fasthttp/releases/tag/v1.9.0). There have been so many bugfixes. Please upgrade to v1.32.0 first and see if it still happens.
I tried to test the read result by adding the following log:
**github.com/valyala/fasthttp@v1.9.0/header.go:1306**
![image](https://user-images.githubusercontent.com/91560756/149614196-c961b5bf-71d9-4633-bcf0-b48a55e3472a.png)

running result as the following:
Information when **an exception** occurs:
![image](https://user-images.githubusercontent.com/91560756/149614226-0d4235d1-a19c-42ee-87ca-58fffb3faa26.png)
Information during **normal** execution：
![image](https://user-images.githubusercontent.com/91560756/149614262-0e1e6600-b6a9-4bca-8e10-24bbebc3e929.png)

In normal execution, an H can be extracted from the I/O stream.

**Comment by zhangtong007** [comment]
> Are you sure it is updated? Is the ʼreplaceʼ line gone from your go.mod?
> 
> Anyways, I think it's a weird ​response you are getting. It's full of 0s while http is text based. Are you maybe sending a http request on a https port?

The server is HTTPS, and the scheme is HTTPS based on logs.

**Comment by erikdubbelboer** [comment]
That response you are getting isn't normal http. Have you tried making the request with curl or normal net/http to see if that works?

**Comment by zhangtong007** [comment]
> That response you are getting isn't normal http. Have you tried making the request with curl or normal net/http to see if that works?

Thanks for the reply.I sent it through the go language net/http, so I don't know exactly what caused the problem at this point. Can fasthttp and net/http be used simultaneously within a service?

**Comment by erikdubbelboer** [comment]
They can be used together just fine. If the request works with net/http then maybe you were using fasthttp wrong. But if you don't need the performance from fasthttp I would definitely suggest you keep using net/http as it's much easier to use.

**Comment by zhangtong007** [comment]
> They can be used together just fine. If the request works with net/http then maybe you were using fasthttp wrong. But if you don't need the performance from fasthttp I would definitely suggest you keep using net/http as it's much easier to use.
Thanks for the issue.
