### ISSUE TITLE
is there  any way to make fasthttp send post request with low ms?

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1200]
speed is very important for  my script and yes fasthttp is fast and it sends a lot of requests but the receive time is a bit slow
is there any way to make it a lil bit faster? im re using the connection and i know that nagle algorithm is turned off by deafult in fast http
any other suggetsions?
Edit, i saw on stackoverflow that turning off ssl verification  makes request much faster how can i do that in fasthttp?

**Comment by erikdubbelboer** [comment]
Are you talking about the client or server side?

If you're reusing connections then ssl verification won't make any difference as that is only done once.

Assuming you're talking about the client side:
You can never be faster than how fast the server you are requesting from responds. Have you measured how fast they respond? What is the latency to the server? How fast are you getting the responses and why do you think it could be faster? How many requests are you doing per second?

**Comment by DeathRowTools** [comment]
Client side,
Ok but how can I disable ssl verification any way?
And im getting 4 ms response time
Sending 10k request per sec
In c# i get 1.5 ms response time but i cant run high request

**Comment by erikdubbelboer** [comment]
You can set [`Client.TLSConfig`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Client.TLSConfig) to a config with [`InsecureSkipVerify: true`](https://pkg.go.dev/crypto/tls#Config.InsecureSkipVerify).

So the 1.5ms in C# is while doing a lot less requests? In that case the server might be overloaded and can't process 10k requests per second fast enough to respond in 1.5ms. Or is the 1.5ms in C# without reading the response body maybe?

**Comment by DeathRowTools** [comment]
Its 1.5 with reading response body !
And personally i know people runing 20k r/s witv 0.9 ms of ms

**Comment by DeathRowTools** [comment]
> 

how can i make that in code? 
![image](https://user-images.githubusercontent.com/91473167/150645402-f866d529-3ea6-4d12-8cbc-b41b4a45edab.png)

**Comment by erikdubbelboer** [comment]
```go
client.TLSConfig = &tls.Config{
	InsecureSkipVerify: true,
	ClientSessionCache: tls.NewLRUClientSessionCache(0),
}
```

**Comment by DeathRowTools** [comment]
thank you so much you are my hero for real <3 much appreciated for all your hard work
