### ISSUE TITLE
Panics at on context close, v1.33.0

### ISSUE THREAD

**Issue by Gaudeamus** [valyala/fasthttp#1205]
Hello, unfortunately there are no more details except this message I could find.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x200 pc=0x901667]

goroutine 19473 [running]:
github.com/valyala/fasthttp.(*RequestCtx).Done(0x8c4639)
        /go/src/dsp/vendor/github.com/valyala/fasthttp/server.go:2691 +0x7
context.propagateCancel.func1()
        /usr/local/go/src/context/context.go:280 +0x50
created by context.propagateCancel
        /usr/local/go/src/context/context.go:278 +0x1d0
```

**Comment by Gaudeamus** [comment]
I believe it's due to latest `func (ctx *RequestCtx) reset()` where `ctx.s = nil` is now set

**Comment by moredure** [comment]
https://github.com/valyala/fasthttp/commit/436977654aa1d51bf45507353e5ff34a4f54ca1a

**Comment by moredure** [comment]
https://github.com/valyala/fasthttp/pull/1201

**Comment by moredure** [comment]
Are you calling Done() function inside request handler or in some goroutine/task scheulder (ants, etc) where requestctx may be already released?

**Comment by Gaudeamus** [comment]
on the init of handler it goes like:
```
	handlerData.requestCtx = fasthttpCtx
	handlerData.ctx, handlerCtx.cancel = context.WithTimeout(fasthttpCtx, time.Millisecond*500)
```
on the defer of the handler there is release context like this:
```
	handlerData.requestCtx = nil //ensure not use context anymore
	if handlerData.cancel != nil {
		handlerData.cancel()
	}
	if handlerData.ctx != nil {
		select {
		case <-handlerData.ctx.Done():
		default:
			logs.Warning("context is not released")
		}
	}
	handlerData.cancel = nil
	handlerData.ctx = nil
```

**Comment by moredure** [comment]
as I understand it logging "context is not released", then panics after 500ms

**Comment by moredure** [comment]
I'll make pull request to golang to fix it)

**Comment by moredure** [comment]
https://github.com/golang/go/pull/50989/files

**Comment by moredure** [comment]
But in some cases parent.Err() will panic anyway, since server may close s.done channel, and in parallel child cancel then sometimes it might call parent.Err() when s already nil

**Comment by moredure** [comment]
so nil check for s inside fasthttp will be a good option for such cases) but it's also a concurrency issue...

**Comment by moredure** [comment]
I guess it's better to replace done channel inside s to context.Context than no additional goroutine should be created on withTimeout

**Comment by moredure** [comment]
https://github.com/valyala/fasthttp/pull/1206

**Comment by moredure** [comment]
@Gaudeamus you can try this pull request

**Comment by moredure** [comment]
Another fix for it is to utilise atomic for requestCtx.s field

**Comment by moredure** [comment]
@erikdubbelboer please review, probably you have a better idea how to avoid race condition with RequestCtx.

**Comment by moredure** [comment]
The problem here is that context package expects contexts to not be reused...

**Comment by Gaudeamus** [comment]
just for your info - no warning is triggered, as you assumed
> as I understand it logging "context is not released", then panics after 500ms
I'm currently downgrating to 1.32, will wait for next release to try. Thanx

**Comment by moredure** [comment]
Yes, true, no context is not released printed, because the context itself canceled, but context internal  goroutine which relies on (*requestCtx).Done() chan struct will be created afterwards panicing with nil exception on *Server field...

**Comment by gzuidhof** [comment]
I can confirm I'm running into the same issue, when reverting back to `v1.32.0` it's all good again.

**Comment by moredure** [comment]
We certainly need to assign a bug flag to this ticket.

**Comment by moredure** [comment]
@gzuidhof you can check https://github.com/valyala/fasthttp/pull/1206 this ticket it should reduce the number of goroutines created, but probably will increase lock contention since sharing server context across all requestCtx handlers

**Comment by erikdubbelboer** [comment]
Sorry I haven't had the time to look into this yet, I will hopefully this weekend.

**Comment by itzikiusa** [comment]
Hi, any news about it?

**Comment by erikdubbelboer** [comment]
How about this as a fix?: https://github.com/valyala/fasthttp/pull/1234

**Comment by moredure** [comment]
Should totally works as long as context pool server specific!
