### ISSUE TITLE
How to solve the following timeout problem?

### ISSUE THREAD

**Issue by zhangtong007** [valyala/fasthttp#1211]
I ran into a timeout problem where the following error "timeout" was returned during the execution of the online environment. This is an occasional problem that rarely occurs.

```go
client := &fasthttp.Client{
		MaxIdleConnDuration:  *,
		MaxConnsPerHost:     *,
		ReadTimeout:         50000 * time.Second,
		ReadBufferSize:      *,
		Dial: func(addr string) (net.Conn, error) {}
}
err := client.DoTimeout(req, resp, 50000*time.Second)
		if err != nil {
			fmt.Printf("err:%s\n", err.Error())
			return
		}
```
![image](https://user-images.githubusercontent.com/91560756/152944443-33f516e7-109c-45d1-86ec-dfc74444b257.png)

**Comment by erikdubbelboer** [comment]
I'm confused, what exactly is going wrong? You're using `DoTimeout` but you don't expect a timeout?

**Comment by zhangtong007** [comment]
Yes.
I used Dotimeout with the timeout set to 50,000s, but the timeout was immediately returned when I called it.
There is a low probability that this problem occurs due to long-term stability. The problem may be caused by the timer pool.
I'm thinking about using the Do method, setting readtimeout and writetimeout to ensure

**Comment by erikdubbelboer** [comment]
Yes I would definitely recommend using `Do` with the timeout you already set. `DoTimeout` uses more resources and basically does the same.

`DoTimeout` and `Do` can timeout immediately if the `Dial` function times out immediately for some reason.

**Comment by zhangtong007** [comment]
Thanks for your reply
