### ISSUE TITLE
Possible bug with DoRedirects() and request headers

### ISSUE THREAD

**Issue by zachgrayio** [valyala/fasthttp#1217]
Looks like when using `DoRedirects()` to access artifactory URLs that in the end are resolving to `s3` buckets (behind the scenes in artifactory), we get an AWS error because the `Authorization` header is present in the request body and the URL contains an auth token from Artifactory as a query parameter.

This only occurs with this http client; my assumption is that `DoRedirects` is erroneously attaching headers which it should not be, to subsequent requests? :thinking: 

FWIW I resolved this by writing my own `DoRedirects()` that dropped `Authorization` headers if present and there were redirects to follow.

**Comment by erikdubbelboer** [comment]
`DoRedirects` just follows redirects and keeps sending exactly the same request with the same headers to each following url. I'm afraid that this is something that we can't change anymore without introducing a backwards incompatibility.

It's a good fix to just write your own `DoRedirects` implementation as that isn't very hard.
