### ISSUE TITLE
Question: Why is content length `int` and not `int64`

### ISSUE THREAD

**Issue by mtneug** [valyala/fasthttp#1222]
I'm wondering why content length is not explicitly an `int64`. Probably for most users, `int` is equivalent, but 32-bit system should also be able to send and receive bodies larger than 2GB. If I followed the code correctly, requests will have a content length of -2 and responses will divert to chunked transfer encoding with a content length of -1 even when the actual content length is known in both cases. In addition, this makes for awkward code like [this overflow check and error handling](https://github.com/valyala/fasthttp/blob/ad8a07a86e131fc65a3f6a0f88583badf20a6e88/fs.go#L1247-L1252).

**Comment by erikdubbelboer** [comment]
I have no idea why valyala choose `int` in the past. But I'm afraid we can't change it to `int64` without breaking backwards compatibility of the API.

But I also can't imagine a use case for using fasthttp when you're receiving bodies that are this big. Fasthttp is really designed for handling a lot of small requests per second. Up [until recently](https://pkg.go.dev/github.com/valyala/fasthttp#Server.StreamRequestBody) fasthttp would always read the whole request body into memory before calling the handler. And `fasthttp.Client` doesn't still reads the whole body into memory. It does this for the performance benefit. If you don't need that performance you really shouldn't be using fasthttp to begin with.
