### ISSUE TITLE
how to graceful restart mysql fasthttp server？

### ISSUE THREAD

**Issue by b1ackhuang** [valyala/fasthttp#1229]
how to graceful restart mysql fasthttp server？

**Comment by xdorro** [comment]
You can refer to this example: https://github.com/gofiber/recipes/blob/master/graceful-shutdown/main.go

**Comment by b1ackhuang** [comment]
it is greaceful stutdown, but what I want is graceful restart, like this:  https://gist.github.com/rivo/f96ad8710b54a49180a314ec4d68dbfb
