### ISSUE TITLE
Add support for multi-line header values

### ISSUE THREAD

**Issue by valyala** [valyala/fasthttp#123]
Currently `fasthttp` doesn't support multi-line header values. See https://github.com/kataras/iris/issues/190 for details.

Probably, multi-line header values must be supported or properly handled by `fasthttp`.

**Comment by erikdubbelboer** [comment]
I don't think we should change the `Peek` signature. What we can do is add another method called `PeekMulti(key string) [][]byte`. One issue is that it will always result in a heap allocation for the `[][]byte`. We could avoid that by making it `PeekMulti(key string, reuse [][]byte) [][]byte` where `reuse` gets reused for the return value.

**Comment by kirillDanshin** [comment]
Of course, we will not change existing API. +1 on *Multi, if we'll find anyone that still needs that feature 😀

**Comment by Fenny** [comment]
I think this issue can be closed https://github.com/valyala/fasthttp/pull/688
