### ISSUE TITLE
Configurable LIFO, FIFO client connection pooling

### ISSUE THREAD

**Issue by bssd7** [valyala/fasthttp#1236]
Hello, 

we use fasthttp in our gateway and in front of the gateway is a nginx. While monitoring one of our more load intensive applications we could see, that the load balance is distributed equal after nginx, but after our gateway the load balance was some how screwed up.
After digging into the code we found out, that the cause of this is, that fasthttp is using a LIFO strategy for the connection pooling.

It would be great if the connection pooling strategy could be made configurable so that the user can decide which pooling strategy should be used.

As you can see in the pictures below after the nginx the load balance is equal over the different connections
![Load_balance_after_nginx](https://user-images.githubusercontent.com/100851055/156718515-0d7a740f-c5b2-4907-bead-f38ac762f451.png)

But after the Gateway with fasthttp the load balance looks like this:
![Load_balance_after_gateway_with_fasthttp](https://user-images.githubusercontent.com/100851055/156719750-0ba5f54d-6ccd-46d2-a698-048a3d1c60b7.png)
.

**Comment by erikdubbelboer** [comment]
I would be open to a pull request for this. I'm afraid I don't have time to add this myself any time soon.

For someone who wants to work on this:

Here it always takes the last connection from the `conns` slice: https://github.com/valyala/fasthttp/blob/62c15a5d098f23fcf7540841ed2377d4fd428956/client.go#L1547-L1550
And here it always adds a used connection to the end of the `conns` slice: https://github.com/valyala/fasthttp/blob/62c15a5d098f23fcf7540841ed2377d4fd428956/client.go#L1778

**Comment by stokito** [comment]
So previously by default the FastHTTP had LIFO but now it's FIFO? And the FIFO should be better for most cases, right? I'm asking because not sure if I have to change the parameter

**Comment by erikdubbelboer** [comment]
The previous default was also FIFO so that didn't change. Which strategy is better depends on your specific use case. I suggest testing them.

**Comment by erikdubbelboer** [comment]
Sorry you are right, I was reading it wrong. The default strategy was changed cause FIFO works best for most situations.
