### ISSUE TITLE
Changing fasthttp.RequestCtx.Response field type to interface{}, use fasthttp.Response as the default implementation

### ISSUE THREAD

**Issue by lesismal** [valyala/fasthttp#1239]
Thanks for your great job on this project! I learn much from it!

I wrote a poller framework [nbio](https://github.com/lesismal/nbio) to reduce goroutine nums and memory usage in high concurrency scenarios, and by using poller-net-layer instead of std-net-layer, my framework has achieved the compatibility with net/http or net/http based frameworks such as gin and echo. Then we can control the goroutine pool with a limited size, for example, 1m connections, in a single process, using only 1k or 10k goroutine pool size, we can customise the size if we want. we also reduce memory cost by using the same buffer pool between different layers(tcp/tls/http/websocket). With all the details, we can not gain a higher response performance if the service just serve for normal online connections, but we can avoid more gc/stw/huge-mem-cost problems caused by the huge num of goroutines when there are huge online connections(eg: 1M connections, 100k rps, reduce 60%-90% memory cost, and the service runs fine).

I also want to achieve compatibility with fasthttp. For a poller framework, I need some different response implementation and have implemented it in my framework, but fasthttp.RequestCtx.Response is a struct type that doesn't allow me to use my response implementation.
If fasthttp can change RequestCtx.Response field type to interface{}, as net/http's http.Handler did `ServeHTTP(ResponseWriter, *Request)`, it shall not lose performance for std-net-based-fasthttp itself, but will be more helpful for me or other guys who want to customize more details.

Thanks again! Hope you guys are doing well!

**Comment by erikdubbelboer** [comment]
I'm sorry but changing `RequestCtx.Response` to an `interface{}` would break backwards compatibility for all our users, so that's not going to happen. Why exactly do you think you need this change specifically? It sounds a lot like https://github.com/valyala/fasthttp/pull/922

**Comment by lesismal** [comment]
> I'm sorry but changing `RequestCtx.Response` to an `interface{}` would break backwards compatibility for all our users, so that's not going to happen. 

Sorry to hear that but you are right and I understand it. I didn't aware of that and open this issue, sorry for wasting your time, I'll close it.

> Why exactly do you think you need this change specifically? It sounds a lot like #922

It's kind of like #922, I'm planning to use another Conn(with non-blocking read/write) implementation instead of net.Conn(blocking read/write), it's like @calbot 's way to use gnet. 
But I did more: full implementation of non-blocking and async-streaming parser for tls/http1.x/websocket, .and deeply customized buffer pool and goroutine pool and some other details.
