### ISSUE TITLE
content-length is 0

### ISSUE THREAD

**Issue by zhangfuhong** [valyala/fasthttp#1240]
1. when use the `err = fasthttp.Do(req, resp)`, it can show the correct content-length `req.Header.ContentLength()`
![Snipaste_2022-03-08_18-06-37](https://user-images.githubusercontent.com/55829833/157214950-bf053e4b-0820-4f1b-8553-eff0c1045644.png)

2. when use the `fasthttp.DoTimeout(req, resp,expire)`, `req.Header.ContentLength()` always shows the length is 0.
![image](https://user-images.githubusercontent.com/55829833/157215120-be478903-4994-4168-b254-2e249ad442d4.png)

**Comment by zhangfuhong** [comment]
github.com/valyala/fasthttp v1.14.0

**Comment by erikdubbelboer** [comment]
Please update to `v1.34.0` and let me know if it still happens. You shouldn't be using a version that is almost 2 years old!

**Comment by erikdubbelboer** [comment]
But I think the issue is that `DoTimeout` creates a new `Request` object to use for the request (so the one passed in can be reused after the function returns while the request is still running). It swaps the body to this new request. So your old request won't have a body anymore. This is expected behavior.

**Comment by erikdubbelboer** [comment]
See: https://github.com/valyala/fasthttp/blob/59f94a3f7137d0ad215bd262df7082d1e632a1f7/client.go#L1207-L1209

**Comment by zhangfuhong** [comment]
@erikdubbelboer  thanks for your help, but when i upgrade the fasthttp verison 1.34.0, it also always shows this case.
![image](https://user-images.githubusercontent.com/55829833/157354987-bf30af76-12e8-4585-809f-579ba13c3b12.png)
but when use the below code can be work well.
`client := fasthttp.Client{ReadTimeout: expire, WriteTimeout: expire}`
	`err = client .Do(req, resp)`
so the issue also exist.

**Comment by erikdubbelboer** [comment]
Like I explained above, `DoTimeout` will always remove the body from the request, this is by design and not a bug.

**Comment by zhangfuhong** [comment]
@erikdubbelboer  ok, got it, thanks
