### ISSUE TITLE
Extra goroutine after server gracefull shutdown

### ISSUE THREAD

**Issue by denvolj** [valyala/fasthttp#1241]
Seems that updateServerDate() creating goroutine that can't be exited.
This is causing some test tools (like goleak) to report about extra goroutines even after server's gracefull shutdown.

**Comment by denvolj** [comment]
Dirtyhack: you can ignore by this way
`
	goleak.VerifyNone(
		t,
		goleak.IgnoreTopFunction("time.Sleep"),
	)
`

**Comment by erikdubbelboer** [comment]
I'm open to a pull request to somehow fix this. But I don't see any other way than an extra method to stop it. And you'll have to build your re-settable version of sync.Once I guess.
