### ISSUE TITLE
dialing to the given TCP address timed out

### ISSUE THREAD

**Issue by louyuexing** [valyala/fasthttp#1242]
Using fasthttp to make concurrent requests, a large number of exceptions occur,
How can I check it, please
![image](https://user-images.githubusercontent.com/27764555/157653789-68054fdd-98b9-42d2-a971-810e52e3f959.png)

**Comment by louyuexing** [comment]
client code
<img width="652" alt="image" src="https://user-images.githubusercontent.com/27764555/157653969-556870fd-1d04-46c3-b07b-bf1eb6edb0b6.png">

**Comment by fresh** [comment]
Can you show the client configuration you are using?

**Comment by louyuexing** [comment]
> 你能显示你正在使用的客户端配置吗？

<img width="530" alt="image" src="https://user-images.githubusercontent.com/27764555/157784600-a2bb44c3-08b9-46f7-bcd7-a03362721760.png">

server:
2 cores｜4GB RAM｜80GB｜6Mbps

**Comment by louyuexing** [comment]
> Can you show the client configuration you are using?

<img width="454" alt="image" src="https://user-images.githubusercontent.com/27764555/157785275-ddfce39a-07c5-4bba-89f9-feba7fddc521.png">

**Comment by fresh** [comment]
> > Can you show the client configuration you are using?
> 
> 
> 
> <img width="454" alt="image" src="https://user-images.githubusercontent.com/27764555/157785275-ddfce39a-07c5-4bba-89f9-feba7fddc521.png">
> 
> 

Try taking out the Dial param within your FastHttp Client config, and try using 1024*1024 instead of 1024*8 and see if that works. Also what site are you trying to send concurrent requests to?

**Comment by louyuexing** [comment]
> 


> > > Can you show the client configuration you are using?
> > 
> > 
> > <img alt="image" width="454" src="https://user-images.githubusercontent.com/27764555/157785275-ddfce39a-07c5-4bba-89f9-feba7fddc521.png">
> 
> Try taking out the Dial param within your FastHttp Client config, and try using 1024_1024 instead of 1024_8 and see if that works. Also what site are you trying to send concurrent requests to?

I'm glad you can reply to my question, my English is really bad, these are all translated with Google translation software, please understand!

【1】
The interface is an open site, mainly used to push messages to users, but this interface does not support batch push, and we need to push about 100,000 messages per minute.
【2】
Test server configuration
2 cores/4GB/80GB/6M

**Comment by fresh** [comment]
What is your Request looking like? Can I see that?

**Comment by erikdubbelboer** [comment]
Seems to me like that site doesn't like you opening this many connections this quickly. Are you reusing FastHttpClient correctly so you can make use of keep-alive connections? How many requests are you sending in parallel and now? We need to see a lot more code to see what you could improve or might do wrong.

**Comment by louyuexing** [comment]
> What is your Request looking like? Can I see that?


Do you need to see the request address?

**Comment by louyuexing** [comment]
> Seems to me like that site doesn't like you opening this many connections this quickly. Are you reusing FastHttpClient correctly so you can make use of keep-alive connections? How many requests are you sending in parallel and now? We need to see a lot more code to see what you could improve or might do wrong.

You don't mind, I'll send you some code on this issue to your mailbox.
