### ISSUE TITLE
How to submit an array of parameters for a form request

### ISSUE THREAD

**Issue by duxphp** [valyala/fasthttp#1244]
The form submission data structure is as follows, how to pass operation to AcquireArgs for processing?

```
params := map[string]interface{}{
		"accessToken": "xxxx",
		"dataType":    2,
		"image":      "xxxx",
		"operation": []map[string]interface{}{
			{
				"setToken":"xxxx",
				"threshold": 80,
				"matchCount": 1,
			},
		},
	}
```

**Comment by erikdubbelboer** [comment]
This doesn't seem to make much sense as query params (as they are key=value only), unless you build your own custom encoding. I would just [make JSON out of it](https://pkg.go.dev/encoding/json#Marshal) and [set it as the body](https://pkg.go.dev/github.com/valyala/fasthttp#Request.SetBody). Or if it really has to be in the query params I would just put that JSON string [in the url](https://pkg.go.dev/net/url#QueryEscape).
