### ISSUE TITLE
How to use POST data with application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by rushkii** [valyala/fasthttp#1245]
I need to POST request using application/x-www-form-urlencoded, I don't know how to use it, is there an example?
This is my request data:
```
token=mytoken&username=myusername&password=mypassword
```

**Comment by fresh** [comment]
req := fasthttp.AcquireRequest()
...
req.SetBody([]byte("token=mytoken&username=myusername&password=mypassword"))
OR
req.SetBodyString("token=mytoken&username=myusername&password=mypassword")

**Comment by erikdubbelboer** [comment]
Or you can use [`fasthttp.WriteMultipartForm`](https://pkg.go.dev/github.com/valyala/fasthttp#WriteMultipartForm) to write a [`multipart.Form`](https://pkg.go.dev/mime/multipart#Form) to a `bytes.Buffer` and add that as body.
Remember to call [`RequestHeader.SetMultipartFormBoundary`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestHeader.SetMultipartFormBoundary) or set the `Content-Type` header correctly yourself.

**Comment by deepakbhatia** [comment]
Is there an example of using it the way described below.

I cannot find any way to get this to work 

> Or you can use [`fasthttp.WriteMultipartForm`](https://pkg.go.dev/github.com/valyala/fasthttp#WriteMultipartForm) to write a [`multipart.Form`](https://pkg.go.dev/mime/multipart#Form) to a `bytes.Buffer` and add that as body. Remember to call [`RequestHeader.SetMultipartFormBoundary`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestHeader.SetMultipartFormBoundary) or set the `Content-Type` header correctly yourself.

**Comment by erikdubbelboer** [comment]
This is one way to do it:
```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"mime/multipart"
	"net/textproto"
	"os"

	"github.com/valyala/fasthttp"
)

func main() {
	var b bytes.Buffer

	w := multipart.NewWriter(&b)

	if err := w.SetBoundary("someboundary"); err != nil {
		panic(err)
	}

	if err := w.WriteField("foo", "bar"); err != nil {
		panic(err)
	}

	h := make(textproto.MIMEHeader)
	h.Set("Content-Disposition", `form-data; name="main"; filename="main.go"`)
	h.Set("Content-Type", "text/plain")
	m, err := w.CreatePart(h)
	if err != nil {
		panic(err)
	}
	f, err := os.Open("main.go")
	if err != nil {
		panic(err)
	}
	if _, err := io.Copy(m, f); err != nil {
		panic(err)
	}
	if err := f.Close(); err != nil {
		panic(err)
	}

	req := fasthttp.AcquireRequest()

	req.SetRequestURI("http://localhost:8080")
	req.Header.SetContentType(w.FormDataContentType())
	req.SetBody(b.Bytes())

	fmt.Println(req.String())
}
```
