### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1] 

### ISSUE THREAD

**Issue by avi-stx** [valyala/fasthttp#1246]
goroutine 271 [running]:
[29](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:29)
github.com/valyala/fasthttp.releaseArg(...)
[30](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:30)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/args.go:469
[31](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:31)
github.com/valyala/fasthttp.(*Args).ParseBytes(0xc0000fbd68, {0xc0002ba420, 0x1e, 0xc00030bf40})
[32](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:32)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/args.go:103 +0x39e
[33](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:33)
github.com/valyala/fasthttp.(*URI).parseQueryArgs(...)
[34](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:34)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/uri.go:903
[35](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:35)
github.com/valyala/fasthttp.(*URI).QueryArgs(...)
[36](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:36)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/uri.go:895
[37](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:37)
github.com/valyala/fasthttp.(*RequestCtx).QueryArgs(0xc0000fbb80)
[38](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:38)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:974 +0x58
[39](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:39)
github.com/valyala/fasthttp.(*RequestCtx).FormValue(0xc0000fbb80, {0x226f260, 0xd252c0})
[40](https://github.com/lyvecloud/LyveFRP/runs/5527072205?check_suite_focus=true#step:6:40)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:1099 +0x2c

we get the error in 
func releaseArg(h []argsKV) []argsKV {
	return h[:len(h)-1]
} 

i think we should add 
if ! len(h) > 0{
     return nil 
}

**Comment by erikdubbelboer** [comment]
Can you show your code that is triggering this? My guess would be that you are re-using something after it has already been release. Try running your program with `go run -race` or `go build -race`.

**Comment by ran-seagate** [comment]
Hi, Im working with @avi-stx , this is our output when building with -race and running:

==================
[2022/03/20 - 14:17:37] 127.0.0.1:57514 | HTTP/1.1 | GET /itworks/t2.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20220320%2Fus-west-1%2Fs3%2Faws4_request&X-Amz-Date=20220320T104153Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=c268d619f247d793f0cb8d05c1897b1942dffac02a0c92edb046c0f33b094efa - 400 - 3.321084ms | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
==================
WARNING: DATA RACE
Read at 0x000106011d88 by goroutine 40:
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:65 +0x34

Previous write at 0x000106011d88 by goroutine 34:
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:65 +0x4c

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
==================
WARNING: DATA RACE
Read at 0x0001055fe9d8 by goroutine 40:
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:66 +0x70

Previous write at 0x0001055fe9d8 by goroutine 34:
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:67 +0xb8

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
==================
WARNING: DATA RACE
Read at 0x0001055fe9b0 by goroutine 40:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:101 +0x3c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Previous write at 0x0001055fe9b0 by goroutine 34:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:115 +0x60c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
==================
WARNING: DATA RACE
Read at 0x0001055fe9a8 by goroutine 40:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:102 +0x1ec
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Previous write at 0x0001055fe9a8 by goroutine 34:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:115 +0x60c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
==================
WARNING: DATA RACE
Read at 0x0001055fe9a0 by goroutine 40:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:105 +0x22c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Previous write at 0x0001055fe9a0 by goroutine 34:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:115 +0x60c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
==================
WARNING: DATA RACE
Read at 0x0001055fe9c8 by goroutine 40:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:108 +0x26c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Previous write at 0x0001055fe9c8 by goroutine 34:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:115 +0x60c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
==================
WARNING: DATA RACE
Read at 0x0001055fe9d0 by goroutine 40:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:109 +0x2a8
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Previous write at 0x0001055fe9d0 by goroutine 34:
  LyveFRP/cmd.minMaxDuration()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:115 +0x60c
  LyveFRP/cmd.metricsMiddleware()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/metrics.go:69 +0x130

Goroutine 40 (running) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38

Goroutine 34 (finished) created at:
  LyveFRP/cmd.Combined.func1()
      /Users/940394/Desktop/seagate_repos/LyveFRP/cmd/server.go:42 +0x500
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2341 +0x1710
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x50
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xb0
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/940394/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x38
==================
