### ISSUE TITLE
404 Response From FastHttp Client

### ISSUE THREAD

**Issue by fresh** [valyala/fasthttp#1247]
Hello, recently my fasthttp client was working fine but then one day it started throwing 404 errors for Twitter.com

For other HTTP clients, this request would give a status code of 200, but every single request with fasthttp to anything on Twitter.com gives a 404, what could be the problem?

**Comment by erikdubbelboer** [comment]
Seems like twitter is somehow blocking these requests. Doing a `http` request you get the proper 301 response. But any way I make the normal request seems to fail. Even if you change the user agent and send the exact same headers as a normal browser. I'm not quite sure how they do it, maybe the look at the order of the headers or some ssl differences. I'm afraid there is nothing I can do about this.

**Comment by fresh** [comment]
Thank you for looking into it. Appreciate it!
