### ISSUE TITLE
Replacing multiple slash in request URI

### ISSUE THREAD

**Issue by sgvx** [valyala/fasthttp#1252]
I need to send the GET request https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/i/rRo5b2M9Gc9AwQ but http client replacing slashes.

client:
<pre>
GET /yandex/get/https:/disk.yandex.ru/i/rRo5b2M9Gc9AwQ HTTP/1.1
</pre>

example code:

<pre>
import ("log"; "crypto/tls"; "github.com/valyala/fasthttp")
func main() {
	client := &fasthttp.Client{
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
		DisablePathNormalizing: true,
	}
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)
	req.SetRequestURI("https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/i/rRo5b2M9Gc9AwQ")
	res := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(res)
	log.Printf("RequestURI %s", req.RequestURI())
	log.Printf("Query %s", req.String())
	if err := client.DoRedirects(req, res, 10); err != nil {
		log.Fatal(err)
	}
	log.Printf("Response code %d", res.StatusCode())
}
</pre>

With curl:

<pre>
sgvx@node1 ~ > curl -s -v -o ./t1.jpg -k https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/i/BjU-osOZWYvIww
*   Trying 78.46.92.107...
* Connected to getfile.dokpub.com (78.46.92.107) port 443 (#0)
* found 129 certificates in /etc/ssl/certs/ca-certificates.crt
* found 520 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: dokpub.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=dokpub.com
*        start date: Fri, 04 Feb 2022 23:37:16 GMT
*        expire date: Thu, 05 May 2022 23:37:15 GMT
*        issuer: C=US,O=Let's Encrypt,CN=R3
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /yandex/get/https://disk.yandex.ru/i/BjU-osOZWYvIww HTTP/1.1
> Host: getfile.dokpub.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Server: nginx
< Date: Thu, 17 Mar 2022 10:27:33 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
</pre>

How to send a request without replacing the slash?

**Comment by sgvx** [comment]
> Have you tried setting https://pkg.go.dev/github.com/valyala/fasthttp#Client.DisablePathNormalizing ?

Yes, I testing with client, as above my example

<pre>
	client := &fasthttp.Client{
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
		DisablePathNormalizing: true,
	}
</pre>

but output request with replaced slash

<pre>
2022/03/17 17:36:20 RequestURI https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/i/rRo5b2M9Gc9AwQ
2022/03/17 17:36:20 Query GET /yandex/get/https:/disk.yandex.ru/i/rRo5b2M9Gc9AwQ HTTP/1.1
Host: getfile.dokpub.com

2022/03/17 17:36:24 Response code 404
</pre>

**Comment by erikdubbelboer** [comment]
Can you try the following, can you do this after `req.SetRequestURI`:
```
req.URI().DisablePathNormalizing = true
```

**Comment by sgvx** [comment]
> Can you try the following, can you do this after `req.SetRequestURI`:
> 
> ```
> req.URI().DisablePathNormalizing = true
> ```

Yes it worked. Thanks!
