### ISSUE TITLE
gosec high issue : G402 (CWE-295): TLS MinVersion too low.

### ISSUE THREAD

**Issue by Aoang** [valyala/fasthttp#1256]
I updated https://github.com/valyala/fasthttp/pull/1253/commits/4657a76f0fd104ac1bd2eda2e7f269bdd8305421#diff-6102d4f2cddb56c446459bde9bf8e8044b87ce3f98a24c2bba99debfd62461dc in https://github.com/valyala/fasthttp/pull/1253 , and got high issue with gosec : G402 (CWE-295): TLS MinVersion too low.

To fix it, there are two options.

1. set tls.Config.MinVersionis to tls.VersionTLS10 or higher
2. gosec excluding rules G402

Well, what should we do ?

**Comment by erikdubbelboer** [comment]
Let's set `tls.Config.MinVersionis` to `tls.VersionTLS10`.

**Comment by Aoang** [comment]
https://github.com/valyala/fasthttp/runs/5597612499?check_suite_focus=true

I tried. Maybe we should ignore. @erikdubbelboer

**Comment by erikdubbelboer** [comment]
I think it needs to be `tls.VersionTLS12`
