### ISSUE TITLE
way is the request geting resat before i need it ot 

### ISSUE THREAD

**Issue by avi-stx** [valyala/fasthttp#1257]
I'm seeing some that the request some time is nil 
I'm sending the request to 2 diff goroutine  
any idea ?

**Comment by erikdubbelboer** [comment]
Are you reusing requests or responses after they have been released to the pool? Or in case of `Server` are you using anything after your handler has returned? Please share your code so I can see.

**Comment by avi-stx** [comment]
now i need to find in the requet some info so im sending it to 2 -4 goroutine and waiting for the first one to find the info 
etch goroutine is looking for a diif info 
looks like when they are trying to access the request info we get and error

**Comment by erikdubbelboer** [comment]
Is this inside a server handler? When that handler returns it releases everything related to the request back to the resource pool. If you want to keep using something from the request after the handler has returned you'll need to make a copy of it first.

But to be honest it sounds like you should probably just use `net/http`. Fasthttp is really only for specific use cases which it doesn't sound like you have. `net/http` is also super fast and much easier to use.

**Comment by avi-stx** [comment]
how to do a copy?

**Comment by erikdubbelboer** [comment]
Depends on what. Usually you're using some of the `[]byte` results from the body or headers, you'll need to make slices and copy those values to it.
