### ISSUE TITLE
After 1.29 graceful shutdown is broken

### ISSUE THREAD

**Issue by rupor-github** [valyala/fasthttp#1258]
We are observing panic reports during service shutdown:

```
panic: BUG: error in SetWriteDeadline(5ms): set tcp XXX.XXX.XXX.XXX:15100: use of closed network connection
goroutine 30732118 [running]:
github.com/valyala/fasthttp.(*Server).serveConn(0xc00022c240, {0xd46f50, 0xc354f
         github.com/valyala/fasthttp@v1.33.0/server.go:2353 +0x2099
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00027c000, 0xc24ef082a0)
         github.com/valyala/fasthttp@v1.33.0/workerpool.go:223 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
         github.com/valyala/fasthttp@v1.33.0/workerpool.go:195 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
         github.com/valyala/fasthttp@v1.33.0/workerpool.go:194 +0x1b5
```
         
This seems to be introduced by https://github.com/valyala/fasthttp/pull/1081 - all versions before that seems to be fine. This cannot be intercepted using recover() because it happens in goroutine started by workpool:

```
		vch := wp.workerChanPool.Get()
		ch = vch.(*workerChan)
		go func() {
			wp.workerFunc(ch)
			wp.workerChanPool.Put(vch)
		}()
```

Reliably reproducible and quite annoying.

**Comment by erikdubbelboer** [comment]
Can you try updating to the latest version, `v1.34.0` and see if it still happens?

Seems like it's this line causing the panic: https://github.com/valyala/fasthttp/blob/f3bce3aa6e9450a6f69ae3f98b6db0958d67233c/server.go#L2365
But that's during the handling of a request, unless you are closing the connection in your handler I don't see how that would be possible. Can you share your handler and how you call Shutdown?

**Comment by erikdubbelboer** [comment]
Which version of fasthttp are you using?

Just to be sure, your handler doesn't close the connection itself?

**Comment by rupor-github** [comment]
1.33.0 - does not work as you could see from original message: `github.com/valyala/fasthttp@v1.33.0/`
1.15.1 - works

As I wrote - our handler does not close connections itself

**Comment by erikdubbelboer** [comment]
I have made a branch with a change that could potentially fix the issue. Can you try this branch? You can either `go get github.com/valyala/fasthttp@4175878b13bc` or add this to your `go.mod`:
```
replace (
    github.com/valyala/fasthttp => github.com/valyala/fasthttp v1.34.1-0.20220326112101-4175878b13bc
)
```

**Comment by rupor-github** [comment]
Confirming - looks like shutdown with `v1.34.1-0.20220329185012-6d94120e500f` behaves identically to 1.15.1 we used before.
