### ISSUE TITLE
VisitUserValues inside RequestCtx

### ISSUE THREAD

**Issue by kataras** [valyala/fasthttp#126]
Hello @valyala I wanted to ask you to export this `context's`  field of`  []userDataKV` or make a func something like `VisitUserValues` . I need this in order to improve the iris' view engine's render functions which will communicate with the context's user's values , I think this will be useful for more users at the future, thanks you!

**Comment by valyala** [comment]
Closing the issue, since the corresponding pull request has been merged to the master
