### ISSUE TITLE
Potential data race in v1.34.0

### ISSUE THREAD

**Issue by agodnic** [valyala/fasthttp#1261]
### Summary
The [Go race detector](https://go.dev/blog/race-detector) issued a warning when using fasthttp v1.34.0 in a moderately high concurrency environment (~10 concurrent clients, long-lived requests ~2000ms each).

After some testing, found out that I can consistently reproduce the issue on both versions 1.33.0 and 1.34.0.
Didn't find any issue with versions <= 1.32.0.

So far, I haven't found any references to [RequestCtx](https://godoc.org/github.com/valyala/fasthttp#RequestCtx) or to its' members after returning from [RequestHandler](https://godoc.org/github.com/valyala/fasthttp#RequestHandler).

### Details
Can't provide a minimal example to reproduce this, but I can share the output of `go run -race`

`go version go1.17.5 linux/amd64`

<details>
  <summary>Go race detector output</summary>
  
  ```
==================
WARNING: DATA RACE
Write at 0x00c0006c7698 by goroutine 85:
  github.com/valyala/fasthttp.(*Server).acquireCtx()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2644 +0xef
  github.com/valyala/fasthttp.(*Server).serveConn()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2118 +0x35c
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:2084 +0x4d
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:224 +0xeb
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:196 +0x53

Previous read at 0x00c0006c7698 by goroutine 41:
  [failed to restore the stack]

Goroutine 85 (running) created at:
  github.com/valyala/fasthttp.(*workerPool).getCh()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:195 +0x34b
  github.com/valyala/fasthttp.(*workerPool).Serve()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/workerpool.go:148 +0x7e4
  github.com/valyala/fasthttp.(*Server).Serve()
      /home/u/go/pkg/mod/github.com/valyala/fasthttp@v1.34.0/server.go:1835 +0x843
  github.com/xyz/webserver.(*Server).Start.func1()
      /home/u/src/xyz/src/webserver/webserver.go:172 +0x5a
==================
  ```
  
</details>

**Comment by erikdubbelboer** [comment]
Are you using any hijack handler? Or do you use `ctx` as a context?

The `[failed to restore the stack]` makes it impossible to see what is causing it.

**Comment by erikdubbelboer** [comment]
I just pushed a fix, I'm going to tag a new version next week.
