### ISSUE TITLE
nil pointer when fasthttp.(*Request).ReleaseBody(...)

### ISSUE THREAD

**Issue by zzzzwc** [valyala/fasthttp#1265]
```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xabd0ef]

goroutine 598556 [running]:
github.com/valyala/fasthttp.(*Request).ReleaseBody(...)
        /.../github.com/valyala/fasthttp@v1.31.0/http.go:585
...
 previous code in handler
```

may be there  need a nil check of req.body at https://github.com/valyala/fasthttp/blob/7a5afddf5b805a022f8e81281c772c11600da2f4/http.go#L585 and  https://github.com/valyala/fasthttp/blob/7a5afddf5b805a022f8e81281c772c11600da2f4/http.go#L600

**Comment by DuckRui** [comment]
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> 
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xabd0ef]
> 
> goroutine 598556 [running]:
> github.com/valyala/fasthttp.(*Request).ReleaseBody(...)
>         /.../github.com/valyala/fasthttp@v1.31.0/http.go:585
> ...
>  previous code in handler
> ```
> 
> may be there need a nil check of req.body at
> 
> https://github.com/valyala/fasthttp/blob/7a5afddf5b805a022f8e81281c772c11600da2f4/http.go#L585
> 
> and
> https://github.com/valyala/fasthttp/blob/7a5afddf5b805a022f8e81281c772c11600da2f4/http.go#L600

Hello, I'm curious how you found this problem, as I did not find which function call the ReleaseBody func. Would you like tell me about process of finding this problem? Thank you very much!
