### ISSUE TITLE
trying to get a 10gb file 

### ISSUE THREAD

**Issue by avi-stx** [valyala/fasthttp#1267]
panic: runtime error: slice bounds out of range [:10737418240] with capacity 2147483648     │
│ lyvefrp-7d7444484-cv7z5:goroutine 168 [running]:                                                                    │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.appendBodyFixedSize(0x2896378, {0x28c7758, 0x0, 0x0}, 0x28c7758 │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/http.go:2101 +0x214                                 │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.readBody(0x28962c0, 0xc00058c900, 0xc00078ee00, {0x28c7758, 0xc │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/http.go:2020 +0x5d                                  │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.(*Response).ReadBody(0xc000c10180, 0xc00058c900, 0xc000d0fdd8)  │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/http.go:1317 +0x186                                 │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.(*Response).ReadLimitBody(0xc000c10180, 0x1b5ba08, 0xc00078ee00 │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/http.go:1292 +0xd8                                  │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc0006836c0, 0xc000b3e380, 0xc00 │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/client.go:1465 +0x50c                               │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.(*HostClient).do(0x446494, 0xc00019a730, 0xc000c10180)          │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/client.go:1357 +0x79                                │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.(*HostClient).Do(0xc0006836c0, 0xc000b3e380, 0xc00019a7b8)      │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/client.go:1304 +0x91                                │
│ lyvefrp-7d7444484-cv7z5:github.com/valyala/fasthttp.clientDoDeadline.func1()                                        │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/client.go:1230 +0x79                                │
│ lyvefrp-7d7444484-cv7z5:created by github.com/valyala/fasthttp.clientDoDeadline                                     │
│ lyvefrp-7d7444484-cv7z5:    github.com/valyala/fasthttp@v1.34.0/client.go:1228 +0x418

**Comment by erikdubbelboer** [comment]
You shouldn't use fasthttp for this. Fasthttp is build in a specific way to be really fast for some really specific use cases. To be fast it always reads the whole request and response bodies into memory. If you're getting a 10GB file you're not one of these use cases fasthttp was build for and I would strongly suggest you use `net/http` instead.

**Comment by avi-stx** [comment]
ok but can fasthttp handel get 10 gb file ?

**Comment by erikdubbelboer** [comment]
Yes if you set [`Client.MaxResponseBodySize`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Client.MaxResponseBodySize) high enough and have enough memory available for it to fit in completely plus overhead.

**Comment by ekozlov-search** [comment]
You can set **StreamRequestBody** to true and then use  **Request.BodyWriteTo** . Erik, it is good solution?

**Comment by avi-stx** [comment]
no its a a server that is getting the request and its proxying it using HostClient to the dest server
