### ISSUE TITLE
how can i prepare my request?

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1268]
im sending 1 post request and i need it to be as fast as possible 
so i need to prepare my headers,postdata and my connection to server to be ready 
and once i send the request it sends as fast as possible (no need to make an new connection between client & server)
so how can i make this? 
note: im using 2 functions to do this not 1 
so i will prepare the request in function number 1
then send the request from function number 2

**Comment by erikdubbelboer** [comment]
In function 1 just get a request using `fasthttp.AcquireRequest()`, set the url, add the body etc, and then pass that request to function 2 to send using a `Client`.

**Comment by DeathRowTools** [comment]
but dont i need to send request to instagram first and set "keep-alive" header? 
because if i didnt send my request to instagram from function 1, when i send it from function 2 it will make the first connection and this takes time as far as i know

**Comment by erikdubbelboer** [comment]
`keep-alive` is the default if you don't disabled it (assuming instagram's servers also do keep-alive). Yes you can just make 1 request with that `fasthttp.Client` and it should keep the connection alive for when you really need it.
