### ISSUE TITLE
│ panic: runtime error: slice bounds out of range [:-405504] │

### ISSUE THREAD

**Issue by avi-stx** [valyala/fasthttp#1273]
[2022/04/20 - 04:46:55] 10.213.102.54:46229 | HTTP/1.1 | PUT /stage1/AELqeivv/QFaK6ACSDXmTotDv.rnd - 200 - 8.685251271s |
│ panic: runtime error: slice bounds out of range [:-405504] │
│ goroutine 330 [running]: │
│ github.com/valyala/fasthttp.(*requestStream).Read(0xc000778de0, {0xc00153a000, 0xc001524380, 0x7f7f8ef88fe0}) │
│ github.com/valyala/fasthttp@v1.34.0/streaming.go:73 +0x34d │
│ bufio.(*Writer).ReadFrom(0xc001539a00, {0x1b00d80, 0xc000778de0}) │
│ bufio/bufio.go:745 +0x22c │
│ io.copyBuffer({0x1aff4e0, 0xc001539a00}, {0x1b00d80, 0xc000778de0}, {0xc001556000, 0x1000, 0x1000}) │
│ io/io.go:409 +0x14b │
│ io.CopyBuffer({0x1aff4e0, 0xc001539a00}, {0x1b00d80, 0xc000778de0}, {0xc001556000, 0xc0014a8240, 0xc00153a000}) │
│ io/io.go:396 +0x3c │
│ github.com/valyala/fasthttp.copyZeroAlloc({0x1aff4e0, 0xc001539a00}, {0x1b00d80, 0xc000778de0}) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1981 +0x7e │
│ github.com/valyala/fasthttp.writeBodyFixedSize(0xc00077d180, {0x1b00d80, 0xc000778de0}, 0x400000) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1970 +0x72 │
│ github.com/valyala/fasthttp.(*Request).writeBodyStream(0xc00077d180, 0x2) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1788 +0xad │
│ github.com/valyala/fasthttp.(*Request).Write(0xc00077d180, 0x1b5baa8) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1453 +0xd66 │
│ github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc000703040, 0xc00077d180, 0xc0014b2300)

**Comment by avi-stx** [comment]
getting this error on high load

**Comment by erikdubbelboer** [comment]
Can you share some code, I see you're using `HostClient` in combination with streaming which is not really supported. So I'm wondering how you're doing this.

**Comment by avi-stx** [comment]
im getting the request and im proxying it using HostClient

**Comment by erikdubbelboer** [comment]
I have never tested that before in combination with streaming, can I see your code on how you are doing this?

I'm guessing you're using [`RequestCtx.SetBodyStream`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestCtx.SetBodyStream) in which case fasthttp is still going to load the full 10GB file into memory (for your other issue). I really suggest not using fasthttp for this!

**Comment by avi-stx** [comment]
here is the init server 

```
func InitServer() *fasthttp.Server {
	GlobalRoutesMap = NewRoutesMap()
	GlobalRoutesHosts = NewRoutesHostMap()
	Health = true
	if cert, err := tls.LoadX509KeyPair(certFile, keyFile); err != nil && !TestMode {
		fmt.Printf("cannot load TLS certificate from certFile=%q, keyFile=%q: %s\n", certFile, keyFile, err)
		return nil
	} else {
		rootCAs, _ := x509.SystemCertPool()
		if rootCAs == nil {
			// In some systems (like Windows) system cert pool is
			// not supported or no certificates are present on the
			// system - so we create a new cert pool.
			rootCAs = x509.NewCertPool()
		}

		TlsConfig = &tls.Config{
			RootCAs:      rootCAs,
			Certificates: []tls.Certificate{cert},
			CipherSuites: []uint16{
				tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
				tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
				tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			},
			MinVersion:               tls.VersionTLS12,
			PreferServerCipherSuites: true,
			NextProtos:               []string{H2, Http11},
			CurvePreferences:         []tls.CurveID{tls.X25519, tls.CurveP256},
		}
	}

	return &fasthttp.Server{
		Name:                         APPLICATION_NAME,
		MaxRequestBodySize:           SizeOf5TB,
		DisablePreParseMultipartForm: true,
		StreamRequestBody:            true,
		Concurrency:                  Concurrency,
		IdleTimeout:                  time.Minute * 10,
		Handler:                      Combined(ProxyHandler),
	}
}
```


here in the proxying 

```
func ProxyHandler(ctx *fasthttp.RequestCtx) {
	if tenantHostUrl, err := getTenantHostName(ctx); err != nil {
		if err.Error() == ErrAKNotFoundInTheCm {
			ctx.Error(Forbidden, http.StatusForbidden)
			return
		}
		ctx.Error(AccessDenied, http.StatusBadRequest)
		return
	} else {
		ctx.Request.Header.Add(XForwardedHost, string(ctx.Host()))
		ctx.Request.Header.Add(XRealIP, ctx.RemoteAddr().String())
		if SConfig.SecureBackend {
			ctx.URI().SetScheme(Https)
			if err := (&fasthttp.HostClient{Addr: tenantHostUrl, IsTLS: true, MaxConns: Concurrency, TLSConfig: TlsConfig}).DoTimeout(&ctx.Request, &ctx.Response, time.Second*60); err != nil {
				ctx.Logger().Printf("error when proxying the request: %s", err)
				// for post pre sing URL request
				if ctx.IsPost() {
					if err := GlobalRoutesHosts.Get(tenantHostUrl, true, Concurrency).DoRedirects(&ctx.Request, &ctx.Response, 16); err != nil {
						ctx.Error("Connection refused", http.StatusInternalServerError)
					}
				} else {
					ctx.Error("Connection refused", http.StatusInternalServerError)
				}
			}
			ctx.Done()
		}
      }
}
```

**Comment by erikdubbelboer** [comment]
You didn't post the full stacktrace above. Is the panic caused by the `DoTimeout` or the `DoRedirects`. I'm guessing it's the `DoRedirects`. That one is invalid, you can't reuse `ctx.Request` for another request when it's already used by `DoTimeout`. Since you're streaming the body `DoTimeout` will already completely read the whole body. Then `DoRedirects` will try to read it again which will panic as the whole state of the reader is completely wrong. It's not build to be re-used.

**Comment by avi-stx** [comment]
No the ```DoRedirects``` will try just if ```DoTimeout``` failed and its works good in the case ```DoTimeout``` failed

**Comment by avi-stx** [comment]
and as u can see the error happened  in ```DoTimeout```it will never come to ```DoRedirects``` because its not a ``` POST``` is a  ```PUT``` as u can see in the panic ```
2022/04/20 - 04:46:55] 10.213.102.54:46229 | HTTP/1.1 | PUT /stage1/AELqeivv/QFaK6ACSDXmTotDv.rnd - 200 - 8.685251271s |```
and if u look in code i send u tha t ```DoRedirects``` is only if ```DoTimeout``` is failing for a ```POST```

```
if err := (&fasthttp.HostClient{Addr: tenantHostUrl, IsTLS: true, MaxConns: Concurrency, TLSConfig: TlsConfig}).DoTimeout(&ctx.Request, &ctx.Response, time.Second*60); err != nil {
				ctx.Logger().Printf("error when proxying the request: %s", err)
				// for post pre sing URL request
				**if ctx.IsPost() {**
					if err := GlobalRoutesHosts.Get(tenantHostUrl, true, Concurrency).DoRedirects(&ctx.Request, &ctx.Response, 16); err != nil {
						ctx.Error("Connection refused", http.StatusInternalServerError)
					}
				} else {
					ctx.Error("Connection refused", http.StatusInternalServerError)
				}
			}
			 #ctx.Done()

**Comment by avi-stx** [comment]
full trace 
[2022/04/25 - 09:48:45] 10.213.102.54:23907 | HTTP/1.1 | PUT /stage1-t1-bucket-2-1mb/b6hu268d/edJionnwNu7myoBB.rnd - 200 - 1.050057918s │
│ panic: runtime error: slice bounds out of range [:-3350528] │
│ goroutine 59550 [running]: │
│ github.com/valyala/fasthttp.(*requestStream).Read(0xc000a39dd0, {0xc0011cb000, 0xc00097e700, 0x0}) │
│ github.com/valyala/fasthttp@v1.34.0/streaming.go:73 +0x34d │
│ bufio.(*Writer).ReadFrom(0xc0010a5d40, {0x1b01280, 0xc000a39dd0}) │
│ bufio/bufio.go:745 +0x22c │
│ io.copyBuffer({0x1aff9e0, 0xc0010a5d40}, {0x1b01280, 0xc000a39dd0}, {0xc000f47000, 0x1000, 0x1000}) │
│ io/io.go:409 +0x14b │
│ io.CopyBuffer({0x1aff9e0, 0xc0010a5d40}, {0x1b01280, 0xc000a39dd0}, {0xc000f47000, 0xc0011cc948, 0xc0011cb000}) │
│ io/io.go:396 +0x3c │
│ github.com/valyala/fasthttp.copyZeroAlloc({0x1aff9e0, 0xc0010a5d40}, {0x1b01280, 0xc000a39dd0}) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1981 +0x7e │
│ github.com/valyala/fasthttp.writeBodyFixedSize(0xc00012d180, {0x1b01280, 0xc000a39dd0}, 0x800000) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1970 +0x72 │
│ github.com/valyala/fasthttp.(*Request).writeBodyStream(0xc00012d180, 0x2) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1788 +0xad │
│ github.com/valyala/fasthttp.(*Request).Write(0xc00012d180, 0x1b5bfc8) │
│ github.com/valyala/fasthttp@v1.34.0/http.go:1453 +0xd66 │
│ github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc000624340, 0xc00012d180, 0xc000954480) │
│ github.com/valyala/fasthttp@v1.34.0/client.go:1431 +0x3aa │
│ github.com/valyala/fasthttp.(*HostClient).do(0xc091b96faa1851dc, 0x3a0c4f51260, 0xc000954480) │
│ github.com/valyala/fasthttp@v1.34.0/client.go:1357 +0x79 │
│ github.com/valyala/fasthttp.(*HostClient).Do(0xc000624340, 0xc00012d180, 0xc0010c6fb8) │
│ github.com/valyala/fasthttp@v1.34.0/client.go:1304 +0x91 │
│ github.com/valyala/fasthttp.clientDoDeadline.func1() │
│ github.com/valyala/fasthttp@v1.34.0/client.go:1230 +0x79 │
│ created by github.com/valyala/fasthttp.clientDoDeadline │
│ github.com/valyala/fasthttp@v1.34.0/client.go:1228 +0x418 │

**Comment by erikdubbelboer** [comment]
The problem is `DoTimeout`. `DoTimeout` does not really stop the request after the timeout, it continues in the background but the function returns (stupid design I know). It does this by [making a copy of the `Request` and doing the operation on that](https://github.com/valyala/fasthttp/blob/9a0b4d088c35f5200f9f4694be339a28f7a9c6f6/client.go#L1218-L1249) so when the function returns the caller gets ownership of the `Request` again. But the problem with the body streaming is that it [keeps a reference to the RequestHeader](https://github.com/valyala/fasthttp/blob/9a0b4d088c35f5200f9f4694be339a28f7a9c6f6/streaming.go#L13). And this reference is to the original request instead of the copy. So when `DoTimeout` times out, your handler returns and the request is put back into the pool and reused for another incoming request, this makes the streaming use a header of another request and it goes wrong.

What I would recommend is to not use DoTimeout but instead [`HostClient.ReadTimeout`](https://pkg.go.dev/github.com/valyala/fasthttp#HostClient.ReadTimeout) and `WriteTimeout` and a normal `.Do()`. That is also much faster.

I have also commited a fix: https://github.com/valyala/fasthttp/commit/f90a674ce84bb6d9b02f349d67a4faa9daad754e I'm going to tag a new release this Wednesday. Please let me know if you still get this error after that.

Something not relevant but what you should also really do is re-use the HostClients so you can use keep-alive connections instead of building a new connection each time. Unless your connections are never to the same hosts of course.
