### ISSUE TITLE
Inflating deflated SAML request via AppendInflateBytes problem

### ISSUE THREAD

**Issue by mickeykcyolo** [valyala/fasthttp#1274]
Hey,

When trying to decompress(inflate) deflated saml request via AppendInflateBytes function it returns the next error:
"zlib: invalid header".

When I checked it I saw that underline it is using zlib reader to read the deflated request.
Attached here is a working example(simulation of b64 decoding and inflating a saml request) using a flate reader and a non working example using AppendInflateBytes:

go.mod:

github.com/valyala/fasthttp v1.14.0
github.com/klauspost/compress v1.13.6

test code:

`package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"github.com/klauspost/compress/flate"
	"github.com/stretchr/testify/assert"
	"github.com/valyala/fasthttp"
	"io/ioutil"
	"testing"
)

func Test_Flate(t *testing.T) {

	t.Run("fasthttp.AppendInflateBytes fails", func(t *testing.T) {
		content := "I Love fasthttp!"
		arr := make([]byte, 0)
		bb := bytes.NewBuffer(arr)
		deflateWriter, err := flate.NewWriter(bb, flate.DefaultCompression)
		assert.NoError(t, err)

		_, err = deflateWriter.Write([]byte(content))
		assert.NoError(t, err)

		err = deflateWriter.Flush()
		assert.NoError(t, err)

		_ = deflateWriter.Close()

		b64Content := base64.StdEncoding.EncodeToString(bb.Bytes())

		decodedRequest, err := base64.StdEncoding.DecodeString(b64Content)
		assert.NoError(t, err)

		var dst []byte
		res, err := fasthttp.AppendInflateBytes(dst, decodedRequest)
		fmt.Println(res, err)
		assert.Error(t, err)
	})

	t.Run("flate reader works", func(t *testing.T) {
		content := "I Love fasthttp!"
		arr := make([]byte, 0)
		bb := bytes.NewBuffer(arr)
		deflateWriter, err := flate.NewWriter(bb, flate.DefaultCompression)
		assert.NoError(t, err)

		_, err = deflateWriter.Write([]byte(content))
		assert.NoError(t, err)

		err = deflateWriter.Flush()
		assert.NoError(t, err)

		_ = deflateWriter.Close()

		b64Content := base64.StdEncoding.EncodeToString(bb.Bytes())

		decodedRequest, err := base64.StdEncoding.DecodeString(b64Content)
		assert.NoError(t, err)

		res, err := ioutil.ReadAll(flate.NewReader(bytes.NewReader(decodedRequest)))
		fmt.Println(res, err)
		assert.EqualValues(t, content, res)
	})

}`
	
	
What do you think?

Thanks,
Mickey

**Comment by erikdubbelboer** [comment]
It uses zlib because ʼdeflateʼ compression in the http spec is define as zlib with deflate. So this intended.
