### ISSUE TITLE
cannot find http request method in

### ISSUE THREAD

**Issue by avi-stx** [valyala/fasthttp#1277]
- error when proxying the request: write tcp4 192.168.158.255:60004->10.101.223.230:9001: write: connection reset by peer
2022/04/25 00:02:44 error when serving connection "192.168.158.255:8443"<->"10.213.102.60:24191": error when reading request headers: cannot find http request method in "\x8arO\xa2\xbc>K\xc2S\xad`\xe7\x10\x17vtXe?%\xa4~\x9d\xa17;\xf0\xc8C\x9as\x9bt(h\x1d~=\x05I2\u008a\xaa-\x8b'\xce\xe7q\x81H҈TM?\xe6\nl\xfc\xf6\x1c\xce\xe7쾶\x8aKVqV\x9f\x03\xf7\xfb`>\x9c\xf1\x8f\xa1cO\xfe\xf7g\xed\xc1\x16\xbdK'\x05\xbb\xdbZ\xb0Ʀ\x01\xe1\x8d\xc0\xc4!\x1f\xb7\xbe\xce\xd1\u007f\x85Ֆ\x10\xc8l\xbb\x00\xb5+Ǒu\xcbO\xbf\x8c\x8f\xa2ȃv!1Σ\u007f>\xcbg\x82ݽ2@\xf7\x0f\xe7W\xff\xa2\x8f\xd5\xe0\x1b\t\xf1\xe7\xfa\xae\xb7N͞ʕ\xe2\xc8vf\x8b\xea\x88>\xff7\x16\xa6g\x8c;\x8c\b/\xf0v\xd1\xef\xf9G\xae\xe1\x99!g\x8c\xd4\"\xbbq\x1d RiP\x92}\a)Ac\xae1\xe1\xf5\xaa\xf8\xdf9e\xe6\x9ab\xa1:_\xec\x98>\xbbG\x0eӧ$x\xfaw\x9fATXK\xdd?\xdesd\x1d\xb8,

**Comment by erikdubbelboer** [comment]
Exactly like the message says and like you can see in the attached body. You aren't sending any Http request. Maybe you're sending a https request to a http endpoint.
