### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by zzzzwc** [valyala/fasthttp#1278]
could you please tell me when will the next version (1.3.6) be released, we need this fix https://github.com/valyala/fasthttp/pull/1266/commits/b615924eb902e2e9698e135cfcffe72fbdacaee4

**Comment by erikdubbelboer** [comment]
I'll tag a new release this Wednesday.

**Comment by zzzzwc** [comment]
ok,thank you

**Comment by erikdubbelboer** [comment]
https://github.com/valyala/fasthttp/releases/tag/v1.36.0
