### ISSUE TITLE
possible to replace the current net with https://github.com/cloudwego/netpoll

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1279]
the bottleneck of fasthttp can be improved with bytedance netpoll
https://github.com/cloudwego/netpoll

can someone replace current with it?

**Comment by erikdubbelboer** [comment]
I don't think it's possible to do this without completely breaking the API compatibility. See also: https://github.com/valyala/fasthttp/issues/1239
If any wants to fork fasthttp and do this they are welcome and we can link to it.

But before starting work on it I would like to see some more information about this apparent bottleneck of fasthttp 😄

**Comment by hiqsociety** [comment]
ddosing fasthttp is a true bottleneck when many things are running.
if we do prefork, cant share memory. dont u think it's worth the implementation?

**Comment by hiqsociety** [comment]
after looking at https://github.com/valyala/fasthttp/issues/1239, i thought the same too but of course not DPDK but rather ebpf.

definitely netpoll is the way to go. the bottle neck is at the syscall.

**Comment by erikdubbelboer** [comment]
It's worth a try but I'm afraid I don't have time to work on this.
