### ISSUE TITLE
possible to tie ip address to the preforked process when using so-reuseport?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1280]
i'm trying to route the ip by sharding with % numcpu to the right cpu process.

1. can this be done? or what's a workaround alternative without a proxy /loadbalancer in front of it?
2. in a separate issue, is anyone working on the http2? dario is kind of busy now. i've been waiting for a long time for http2 though. hope to see it in fasthttp soon. 

thx in advance.

**Comment by erikdubbelboer** [comment]
1. I'm not sure I understand. You want to have the client IP determine which process receives the request? In that case it's not possible as the kernel is doing this not fasthttp so we have no control over it. If you mean something else please explain.

2. I don't think so.

**Comment by hiqsociety** [comment]
1. i cant find the settings to influence the kernel to do ip to cpu affinity / process / port setting. how can i work around?

**Comment by hiqsociety** [comment]
thx!
