### ISSUE TITLE
is there a handler for pre-processing remote ip addresses before going through any http stuff?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1282]
is there a handler for pre-processing remote ip addresses before going through any http stuff?

trying to write a rate limiter so was wondering if i can pre-process the net remote ip first before i do anything with the http

the http handler's overhead is too high for a rate limiter i'm thinking of doing as firewall etc.

how do i get the ip at network connection prior to any processing / http handler?

**Comment by erikdubbelboer** [comment]
In that case I would create your own listener to accept connections and do this pre-processing based on the IP before using [`Server.ServeConn`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Server.ServeConn).

If you need it per request you can maybe combine that with [`Server.ConnState`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Server.ConnState) to disconnect the connection when it becomes active and you don't want it to.
