### ISSUE TITLE
MOVE method support

### ISSUE THREAD

**Issue by KristinaEtc** [valyala/fasthttp#1283]
Thanks for the nice package!

I was wondering if you have any plans to implement [MOVE method](https://greenbytes.de/tech/webdav/rfc4918.html#METHOD_MOVE)?

**Comment by erikdubbelboer** [comment]
Where specifically do you need support for it that isn't supported right now? Yeah there is no constant defined for it but that doesn't prevent it from working.

**Comment by KristinaEtc** [comment]
I've checked docs, that's indeed easy to do this `r.Handle()` method. Thanks again
