### ISSUE TITLE
i ran in prefork mode but how do i know which logical processor the prefork process is tied to?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1284]
i ran in prefork mode but how do i know which logical processor the prefork process is tied to?

would like to spawn prefork mode listening to /tmp/http[cpu number].socket <- uds socket based on the cpu num it's tied to. automatically instead of setting cpu affinity etc. which is kind of troublesome for that small performance gain.

unless there's already a master program that can do this? is there? automatically spawn and tie the processes to individual so reuseport etc as mentioned in the performance suggestion of using fasthttp

**Comment by erikdubbelboer** [comment]
It doesn't tie it to any processor, this is something you'll have to do yourself if you want this. In which case I would suggest not using prefork but instead start the processes yourself and use github.com/valyala/fasthttp/reuseport so they can all listen on the same port.

**Comment by hiqsociety** [comment]
would love to see some managed solution for fasthttp this way then. thx anyway!
the syscall is really slowing things down. maybe can really consider using netpoll coz it's faster than gnet in future.
thx anyway!
