### ISSUE TITLE
set custom content-length header

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1286]
im trying to set content-length value different than body length value
example:
req.SetBodyString("username=12345")
i want it to send content length in this way
req.SetBodyString("username=1234")
but the body data stays the same

i tried doing this:
req.Header.Add("content-length", len(body) - 1)
didnt work :)
im trying to do this due to bug i found in a website and im trying to report it
the bug simply works when post data (body) != content-length

**Comment by erikdubbelboer** [comment]
I'm afraid this is not possible. Fasthttp will always check to make sure the content-length and body size are the same. If it's just to report it I would just write a request as a string to a `net.Conn`. We do this in some tests so you can use that as an example how: https://github.com/valyala/fasthttp/blob/7cc6f4c513f9e0d3686142e0a1a5aa2f76b3194a/server_test.go#L637

**Comment by DeathRowTools** [comment]
i must send a lil high requests
and im total noobie when it comes to sockets requests 
tcp, conn.write etc
thats why i wanted to test it on fasthttp :(

**Comment by DeathRowTools** [comment]
do you think theres an method to edit on fasthttp from my side, so it stops checking the content-length and body size are the same

**Comment by erikdubbelboer** [comment]
Yes then I would start here: https://github.com/valyala/fasthttp/blob/7cc6f4c513f9e0d3686142e0a1a5aa2f76b3194a/http.go#L1492

**Comment by DeathRowTools** [comment]
i tested this:
 req.Header.SetContentLength(len(body) - 1) in {http.go} 
and its working perfect
but i faced something weird
fasthttp.Do(req, resp)
"without proxy"
the above code working fine 
but when i try it with proxies:

client := &fasthttp.Client{
			Dial:           FasthttpHTTPDialer222("ip:port"),
			ReadBufferSize: 8192,
		}
client.do(req,resp) 
"it sends the request but the content-length dosent change"

**Comment by erikdubbelboer** [comment]
No, changing the dialer doesn't change anything about the request in fasthttp. But the proxy might change the header.
