### ISSUE TITLE
Confusion about UserData Not Implemented with MAP

### ISSUE THREAD

**Issue by shinegrin** [valyala/fasthttp#1287]
Generally, K-V pair implemented with MAP is more effictive than ARRAY(SLICE).
Is there any other consideration with implementing RequestCtx.userData with slice?
Cloud anyone explain it, please? Thanks a lot!

**Comment by erikdubbelboer** [comment]
It's implemented as slice to have less allocations. With a slice you can control exactly what happens to it and reuse it. With a map not so much. A map also uses more memory and more CPU if you have less than roughly 10 items.
