### ISSUE TITLE
how do you do prefork "listenandserve" with letsencrypt example?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1288]
with reference to this:
https://github.com/valyala/fasthttp/blob/master/examples/letsencrypt/letsencryptserver.go

cant seem to find a way to do so. possible to expand on the example coz prefork doesnt allow .Serve method

**Comment by erikdubbelboer** [comment]
I wouldn't recommend doing that. Each process would have it's own letsencrypt state and would have to request it's own certificates.

But if you really want to you'll have to write your own version of prefork. The code comes down to [passing the listening socket as extra files to the new process](https://github.com/valyala/fasthttp/blob/7cc6f4c513f9e0d3686142e0a1a5aa2f76b3194a/prefork/prefork.go#L139-L154) and then [listening on that passed file descriptor](https://github.com/valyala/fasthttp/blob/7cc6f4c513f9e0d3686142e0a1a5aa2f76b3194a/prefork/prefork.go#L119).
