### ISSUE TITLE
how do i increase limit to incoming pipelineclient connection?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1291]
error in PipelineClient("/tmp/web.socket"): write unix @->/tmp/web.socket: write: broken pipe

after a few more reloads, sometimes it stuck... like one of the mentioned issues...
https://github.com/valyala/fasthttp/issues/1051

connecting server

        ProxyClient = &fasthttp.PipelineClient{
                Addr: "/tmp/web.socket",
                Dial: func(addr string) (net.Conn, error) {
                        return net.Dial("unix", addr)Ad34UaDxWPRp
                        //return memconn.Dial("memu", "localhost")
                },

                MaxConns: 204800,https://github.com/valyala/fasthttp/issues/1051
                MaxIdleConnDuration: 30 * time.Second,
                ReadTimeout: 30 * time.Second,
                WriteTimeout: 30 * time.Second,
       }

backend server

        ln, err := net.Listen("unix", "/tmp/web.socket")
        //ln, err := net.Listen("tcp", ":80")
        if err != nil {
                log.Fatalf("error in net.Listen: %v", err)
        }

        if err := fasthttp.Serve(ln, requestHandler); err != nil {
                log.Fatalf("error in Serve: %v", err)
        }

**Comment by erikdubbelboer** [comment]
Are you seeing any errors on the backend server?

**Comment by hiqsociety** [comment]
nothing wrong with backend. i will check again and revert.

**Comment by hiqsociety** [comment]
https (reverse proxy) to http (backend)
producing the EOL for pipelineclient and error for hostclient

shld be mentioned somewhere. resolved.
