### ISSUE TITLE
saw this serverName       atomic.Value, any proper way to change the default fasthttp to custom server name?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1292]
saw this serverName       atomic.Value, any proper way to change the default fasthttp to custom server name?

ctx.Reponse.Set.Header("Server","custom") <- is this the proper way or within 
Server{
    serverName: "custom",
}

? What's the proper way?

**Comment by erikdubbelboer** [comment]
If it's for all requests then the proper way is to set [`Server.Name`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Server.Name).
