### ISSUE TITLE
http response status code 404 when using go version >= 1.17 

### ISSUE THREAD

**Issue by lianato3** [valyala/fasthttp#1296]
I have the following code sample:

```
package main

import (
	"fmt"
	"net/http"

	"github.com/valyala/fasthttp"
)

func main() {
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	req.SetRequestURI("https://ads-api.twitter.com/10/conversion_event")
	req.Header.SetMethod(http.MethodPost)

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)

	client := &fasthttp.Client{}

	_ = client.Do(req, resp)

	fmt.Println(resp.StatusCode())
}
```

fasthttp version is `v1.36.0`

when I ran the code with go `1.15`/ `1.16` I'm getting `401` status code as expected.

But when I ran it with go `1.17`/`1.18` I'm am getting `404`, I'm not sure where is the issue here, whether its in golang or fasthttp? will appreciate your help please

**Comment by erikdubbelboer** [comment]
They seem to have some kind of "spam" detection. Even if you add this:
```go
req.Header.SetUserAgent("curl/7.79.1")
req.Header.Set("Accept", "*/*")
req.Header.SetContentType("application/x-www-form-urlencoded")
```
Which makes fasthttp send:
```
POST /10/conversion_event HTTP/1.1
Host: ads-api.twitter.com
User-Agent: curl/7.79.1
Accept: */*
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
```
You will get a 404. Even though curl sends the same request (just the order of the headers is different) and gets a 401 with this:
```
curl -v -X POST --http1.1 -d '' 'https://ads-api.twitter.com/10/conversion_event'
> POST /10/conversion_event HTTP/1.1
> Host: ads-api.twitter.com
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
```
Nothing you can do about this.

**Comment by lianato3** [comment]
The issue is that I'm not really expecting to get `401` instead of `404`, but I upgraded our prod environment to use go `1.18` and all those requests to twitter started to return `404`, where we expect `200`.

**Comment by erikdubbelboer** [comment]
That could be the same "spam" detection on twitters end. The only thing I can imagine changing between those Go versions is is maybe some TCP timing or settings. Have you tried downgrading again to see if it works again? Was the Go version really the only thing you changed?

**Comment by lianato3** [comment]
Yes, the only thing that changed is go version :)
I'm running the go piece of code all day with different versions and it keep same response status `404` only with `1.18`/ `1.17`

**Comment by erikdubbelboer** [comment]
I'm afraid all I can say is that fasthttp does nothing different based on the Go version.

**Comment by lianato3** [comment]
when using net/http it returns `401` :
```resp2, _ := http.PostForm("https://ads-api.twitter.com/10/conversion_event", url.Values{})

	fmt.Println(resp2.StatusCode)```

**Comment by erikdubbelboer** [comment]
The main difference is the order of headers and some different values of headers. But they are all valid requests which again shows me that it's some twitter spam filter.

**Comment by lianato3** [comment]
After debugging it more, the `404` happens when `ClientSessionCache` is not nil in the `tls.Config`:
```
&tls.Config{
    ClientSessionCache: tls.NewLRUClientSessionCache(0),
})
```
However I don't have enough understanding of how the `ClientSessionCache` changes the request in the tls later, this **only** happens in go >= 17 versions. 

Any idea/direction of what may it be? I've also tried setting the `ClientSessionCache` with `fakeSessionCache` like cache and same `404` result.

**Comment by erikdubbelboer** [comment]
It could be that something in the session cache changed in Go >= 17, I'm not aware of any changes. It would be weird if this has any impact on the request to twitter, but I guess it could somehow trigger their spam filter which looks at things like tls properties.

I don't know how `ClientSessionCache` is used internally in the tls library but I can imagine that even setting it to a `fakeSessionCache` will still trigger the tls properties send to twitter to be different.

If this really fixes it then it's probably best to fork fasthttp for your use and remove this line: https://github.com/valyala/fasthttp/blob/b40b5a4ca3e3e56378b1bf77f5321a0b92736fd6/client.go#L1904
Of course the best solution would be for Twitter to fix this issue, but I don't see that happening easily.
