### ISSUE TITLE
fastHttpCtx.SetUserValue BUG

### ISSUE THREAD

**Issue by xj524598** [valyala/fasthttp#1297]
when fastHttpCtx.SetUserValue("instanceKey",interface{}),it woud overwrite other key, 
the  fastHttpCtx has already got a key :serverSpan, and when fastHttpCtx userData expand new item, the init key is serverSpany
finally  serverSpan is overwrite by instanceKe
see detail in down pictures
<img width="931" alt="image" src="https://user-images.githubusercontent.com/26913796/167757395-d635b13a-ea59-4a5f-90bd-0f5dcbfa4d92.png">
<img width="823" alt="image" src="https://user-images.githubusercontent.com/26913796/167757567-5cdbe3ef-1c2b-4c30-a5ea-2f896c7543d3.png">

<img width="807" alt="image" src="https://user-images.githubusercontent.com/26913796/167757674-86913070-cfe1-4051-8531-c06624805af5.png">

**Comment by erikdubbelboer** [comment]
Yes, at that point it will re-use an old value that isn't currently in use. It will overwrite the previous `key` that isn't in use anymore. Did you have an issue with this?

**Comment by xj524598** [comment]
> Yes, at that point it will re-use an old value that isn't currently in use. It will overwrite the previous `key` that isn't in use anymore. Did you have an issue with this?
but the overwrite key is  in use,you can see it in picture 2 and 3。 the key of "serverSpan" in the second of array, when add  key of "instanceKey"， it overwrite serverSpan to instanceKe.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/99610791968a1b10dd28aa7dbf426ea3bad72aed
