### ISSUE TITLE
how to pass parameter for Handler function?

### ISSUE THREAD

**Issue by vipsland** [valyala/fasthttp#1300]
server := &fasthttp.Server{
                Handler:  proxyHandler, // <- this one needs proxyHandler(something []byte)... how to get it done?
        }

**Comment by erikdubbelboer** [comment]
You can for example do it like this:
```go
	server := &fasthttp.Server{
		Handler: func(ctx *fasthttp.RequestCtx) {
			proxyHandler(ctx, something)
		},
	}
```
Does that work for you?
