### ISSUE TITLE
Is client.Do() goroutines leaks ?

### ISSUE THREAD

**Issue by kktae** [valyala/fasthttp#1302]
First of all, please understand that the sentence is awkward using a translator.

I write it by referring to the client of the sample. [here](https://github.com/valyala/fasthttp/blob/master/examples/client/client.go)

however, after running the `client.Do()` function, the number of goroutines does not end with 4 instead of 1.

In the existing `net/http` library, I used the `defer response.Body.Close()` function, is there a function to replace it?

```go
package main

import (
	"fmt"
	"runtime"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	fmt.Println("--- Start ---")

	startingGs := runtime.NumGoroutine()
	fmt.Println("[main] Number of goroutines before:", startingGs)

	test()

	endingGs := runtime.NumGoroutine()
	fmt.Println("[main] Number of goroutines after :", endingGs)

	fmt.Println("--- End ---")
}

func test() {
	/////////////////////////////////////////////////////////////////////////
	readTimeout, _ := time.ParseDuration("500ms")
	writeTimeout, _ := time.ParseDuration("500ms")
	maxIdleConnDuration, _ := time.ParseDuration("1h")
	client := &fasthttp.Client{
		ReadTimeout:                   readTimeout,
		WriteTimeout:                  writeTimeout,
		MaxIdleConnDuration:           maxIdleConnDuration,
		NoDefaultUserAgentHeader:      true, // Don't send: User-Agent: fasthttp
		DisableHeaderNamesNormalizing: true, // If you set the case on your headers correctly you can enable this
		DisablePathNormalizing:        true,
		// increase DNS cache time to an hour instead of default minute
		Dial: (&fasthttp.TCPDialer{
			Concurrency:      4096,
			DNSCacheDuration: time.Hour,
		}).Dial,
	}
	req := fasthttp.AcquireRequest()
	req.SetRequestURI("https://new.land.naver.com/")
	req.Header.SetMethod(fasthttp.MethodGet)
	resp := fasthttp.AcquireResponse()

	Gs1 := runtime.NumGoroutine()
	fmt.Println("  [test] 1 Number of goroutines :", Gs1)

	client.Do(req, resp) // leaks ? ...

	Gs2 := runtime.NumGoroutine()
	fmt.Println("  [test] 2 Number of goroutines :", Gs2)

	fasthttp.ReleaseRequest(req)
	fasthttp.ReleaseResponse(resp)
	/////////////////////////////////////////////////////////////////////////
}
```

```bash
result
--- Start ---
[main] Number of goroutines before: 1
  [test] 1 Number of goroutines : 1
  [test] 2 Number of goroutines : 4
[main] Number of goroutines after : 4
--- End ---
```

**Comment by erikdubbelboer** [comment]
Yes there are goroutines that will still be active after your request. No these are not leaks. One goroutine that will still be running is the one that [cleans up inactive idle connections](https://github.com/valyala/fasthttp/blob/66bc61ee646a8c1bdd7121afe1cd9c27ecc682a9/client.go#L1627) after their timeout expires. Another one is [cleaning up inactive HostClients](https://github.com/valyala/fasthttp/blob/66bc61ee646a8c1bdd7121afe1cd9c27ecc682a9/client.go#L535). Another one is [cleaning the `fasthttp.TCPDialer` cache](https://github.com/valyala/fasthttp/blob/d19b8727b082bc3b9aa2dc0b5a663312c0623bb7/tcpdialer.go#L282). And the last is a global one that [generates values for the `Date` header](https://github.com/valyala/fasthttp/blob/7a5afddf5b805a022f8e81281c772c11600da2f4/header.go#L2048-L2053). All except for the last global goroutine will stop once their work is done.
