### ISSUE TITLE
is it possible to not listen/ignore the request response?

### ISSUE THREAD

**Issue by xtekky** [valyala/fasthttp#1303]
This is the current script I am using:

```golang
req := fasthttp.AcquireRequest()
		resp := fasthttp.AcquireResponse() // remove this
		url := fmt.Sprintf("https://xxxxxxx.xxx/")
		req.SetRequestURI(url)
		req.Header.SetMethod("GET")
		req.Header.Add("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36")
		req.Header.Add("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8")

		fasthttp.Do(req, resp) //impossible to remove response as function requires both args

		reqs += 1

		fasthttp.ReleaseRequest(req)
		fasthttp.ReleaseResponse(resp) //try to remove this aswell
```

I can't remove the aquire response funciton and or variable,  how would it be possible to do or is it even possible ?

**Comment by erikdubbelboer** [comment]
I'm afraid this is not possible. If you really want this you will either have to make your own fork of fasthttp where you do this. Or you have to make your own `net` connection and use [`Request.WriteTo`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Request.WriteTo) to send the http request over that connection.
