### ISSUE TITLE
Add support for AIX

### ISSUE THREAD

**Issue by zhangyongding** [valyala/fasthttp#1304]

**Comment by erikdubbelboer** [comment]
I guess we'll need someone with an AIX machine to make the changes and test them. I have no idea what needs to be changed for this?

**Comment by zhangyongding** [comment]
go build error

# github.com/valyala/tcplisten
../../../../pkg/mod/github.com/valyala/[tcplisten@v1.0.0](mailto:tcplisten@v1.0.0)/socket_other.go:11:48: undefined: syscall.SOCK_NONBLOCK
../../../../pkg/mod/github.com/valyala/[tcplisten@v1.0.0](mailto:tcplisten@v1.0.0)/socket_other.go:11:70: undefined: syscall.SOCK_CLOEXEC

**Comment by zhangyongding** [comment]
Whether aix support can be added to reuseport , similar to what windows does  

https://github.com/valyala/fasthttp/tree/master/reuseport

**Comment by erikdubbelboer** [comment]
`reuseport` doesn't use `syscall.SOCK_NONBLOCK` or `syscall.SOCK_CLOEXEC` so I'm not sure what you want?

**Comment by zhangyongding** [comment]
I want it to compile and use properly

**Comment by erikdubbelboer** [comment]
And when you compile it only gives these errors?
```go
../../../../pkg/mod/github.com/valyala/[tcplisten@v1.0.0](mailto:tcplisten@v1.0.0)/socket_other.go:11:48: undefined: syscall.SOCK_NONBLOCK
../../../../pkg/mod/github.com/valyala/[tcplisten@v1.0.0](mailto:tcplisten@v1.0.0)/socket_other.go:11:70: undefined: syscall.SOCK_CLOEXEC
```
They are errors in https://github.com/valyala/tcplisten which is a dependency of `reuseport`. So I can't fix this in `reuseport`. You'll have to wait for https://github.com/valyala/tcplisten/issues/7. When that is fixed I can update the dependency of `reuseport`.
