### ISSUE TITLE
Confusion about .Body() and/or BodyUnbrotli()

### ISSUE THREAD

**Issue by Xniveres** [valyala/fasthttp#1307]
hey, i've been using fasthttp to build my own cache,

I now want to store a compressed version of the cached file in memory

now I found some weird issues in the docs and can't make sense of it:

to get the clear text version you can use ```Body()```
at least according to the example here:
<https://github.com/valyala/fasthttp/blob/master/examples/client/client.go#L54>

now, turns out there is also a function named ```BodyUnbrotli()```

with the following description:
```
// BodyUnbrotli returns un-brotlied body data.
//
// This method may be used if the response header contains
// 'Content-Encoding: br' for reading un-brotlied body.
// Use Body for reading brotlied response body.
```

and the code looks like following:

```go
func (resp *Response) BodyUnbrotli() ([]byte, error) {
    return unBrotliData(resp.Body())
}
```

now.... how do I get the actual uncompressed data, and how would I go about compressing it again?

**Comment by erikdubbelboer** [comment]
If the response has Brotli compression (`Content-Encoding: br` header present) then `resp.Body()` will return the compressed data and `resp.BodyUnbrotli()` will return the uncompressed data.

You can compress a body with Brotli using [`fasthttp.WriteBrotli`](https://pkg.go.dev/github.com/valyala/fasthttp#WriteBrotli) or [`fasthttp.AppendBrotliBytes`](https://pkg.go.dev/github.com/valyala/fasthttp#AppendBrotliBytes).
