### ISSUE TITLE
Flush response

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1309]
I have a response handler which receives a request and it can response immediately while processing continues. I think that I can finish the processing in a new gorutine but as far I understood it will make it slower and use an additional 4-8 Kb for the it's stack.
Maybe it makes sense to have some kind of `resp.Flush()` method that will immediately send a response to a client and just continue processing in the current handler?

**Comment by erikdubbelboer** [comment]
I'm afraid that's not possible. Connections are handled within a goroutine. Even if we had a `Flush()` method and you would call it to send the response. The connection would still have to wait for your processing to finish before it could handle the next request on the same connection. Therefor this doesn't make any sense. The way to do this is to start a goroutine and do the processing inside that. If you're doing thousands of requests per second and starting a separate goroutine for each of those is too much waiting with responding would be the way to go.

**Comment by stokito** [comment]
Interesting, thank you. From what I understood it still may have sense: client receives and processes response earlier so even if it can't send the next request because the conn is busy but it will process resp faster.
Just to understand a use case: I have a request logging which takes about 100ms (gzip+io) but under a thousands of RPS I'm afraid to start many goroutines just for this. 
Anyway, the change looks like difficult to implement. Maybe someone else can add something on the topic.
Thank you

**Comment by erikdubbelboer** [comment]
The client may receive and process the response faster. But then on the next request get stalled for no clear reason. This could then potentially lead to read or write timeouts on either side and would result in all kinds of unexpected behavior.

If you're not doing thousands of requests per second it's perfectly fine to just start goroutines. Go can have tens to hundreds of thousands of goroutines running with ease.

**Comment by mpldr** [comment]
I am curious about something: I want to prematurely close a connection, but make sure the response is “flushed” beforehand.

The reason being: I have 2 ways of connecting: A raw TCP socket and fasthttp. Both share a connection limit. If a connection is made exceeding the allowed number of connections, a “too many connections” reply is sent and the connection is closed afterwards. That's easy enough to do with a raw connection. Do I have to `ctx.Conn().Write()` the HTTP Response or is there a better way to “fail early”?

**Comment by theo-stv** [comment]
@erikdubbelboer 
Hi, for me nevertheless it would be useful to have the possibility of flushing. We have a sender that can sends about 1000 requests per second and more. Most important thing is too answer as many requests as fast as possible in order not to run into a timeout on sender's side. So a flush function would be very nice. I could call it and make database processing which takes a little time afterwards. And as well it is not necessary to have a free connection again before processing is completed. Only the response must come very fast. Processing can take longer in my purpose.
