### ISSUE TITLE
[feature]ReadBufferSize is for header limiter and read buffer, can set up a new parameter to header limiter？

### ISSUE THREAD

**Issue by xj524598** [valyala/fasthttp#1314]
my server may accept huge header size, so when i set up ReadBufferSize be a huge value, it my easy to oom,becaseof every request would ask for a huge bufer

**Comment by erikdubbelboer** [comment]
I'm afraid not. Fasthttp needs to be able to read the full headers into memory and won't process them piece by piece. That's why `ReadBufferSize` is also the limit of the headers.
