### ISSUE TITLE
Feature Request: retry when server reset a connection

### ISSUE THREAD

**Issue by Thearas** [valyala/fasthttp#1315]
Currently, fasthttp client will not retry when server reset a keep-alive connection.

# Expect

Retry when connection reset. Same as `net/http`: <https://cs.opensource.google/go/go/+/master:src/net/http/transport.go;l=722?q=retry&ss=go%2Fgo:src%2Fnet%2Fhttp%2F>.

Perhaps a parameter `err error` could be added to the `RetryIf` method, representing the reason for the failed request, so we can check if it is a `connection reset` error.

**Comment by erikdubbelboer** [comment]
We already do exactly this: https://github.com/valyala/fasthttp/blob/35aca7b6dfd24a5aa47750137bc4ece280e9ce91/client.go#L1324-L1333

Adding an `err error` to `RetryIf` sounds like a good idea so users can decide for themselves which errors to retry. But... it will have to be a new field as we want to be backwards compatible. A pull request is welcome.

**Comment by Thearas** [comment]
> We already do exactly this
Ah, sorry I missed it.
Will the retry request be sent on a new connection but not on another closed connection?

**Comment by Thearas** [comment]
So... Does it may encounter the same error again if retry on an idle connection?
Seems that `net/http` will always retry on a new connection, this may avoid the problem.
```go
// shouldRetryRequest reports whether we should retry sending a failed
// HTTP request on a new connection. The non-nil input error is the
// error from roundTrip.
```

**Comment by erikdubbelboer** [comment]
It could potentially encounter the error again if another idle connection was also already closed on the server side. But then it will just retry again.

**Comment by Thearas** [comment]
Hi @erikdubbelboer, I may know why I got `connection reset` error so often:

***I use the default `ConnPoolStrategy` `FIFO`***

With `FIFO`, if a request failed with `connection reset` because the connection was already closed by the server, it will choose another old connection in ConnectionPool but not a younger one to retry. However, there is a high probability that this connection is also closed, especially when there is a high concurrency.
I guess that's why [`net/http` use `LIFO`](https://cs.opensource.google/go/go/+/master:src/net/http/transport.go;l=1032;drc=47f806ce81aac555946144f112b9f8733e2ed871).

How about change the default `ConnPoolStrategy` to `LIFO`? Any suggestion?

**Comment by erikdubbelboer** [comment]
You can set [`HostClient.ConnPoolStrategy`](https://pkg.go.dev/github.com/valyala/fasthttp#HostClient.ConnPoolStrategy) to `fasthttp.LIFO`. This is not the default for backwards compatibility. `fasthttp.Client` doesn't have a `ConnPoolStrategy` field yet but it's easy to add. A pull request for that is always welcome.
