### ISSUE TITLE
how to manage the memory fasthttp

### ISSUE THREAD

**Issue by ben-swit** [valyala/fasthttp#1318]
i use fiber(fasthttp) web file server  multi region kubernetes 

if user access ASIA location then  fasthttp do reverse proxy to US server like  in middleware function 

```go
	proxy := func(host string) error {
		u, err := url.Parse(host)
		if err != nil {
			panic(err)
		}
		client := &fasthttp.HostClient{
			NoDefaultUserAgentHeader: true,
			DisablePathNormalizing:   true,
		}

		client.Addr = u.Host

		req := ctx.Request()
		res := ctx.Response()
		req.SetHost(client.Addr)
		req.Header.Del(fiber.HeaderConnection)
		defer res.Header.Del(fiber.HeaderConnection)
		return client.Do(req, res)
	}

	if proxySource[cmpID] {
		if os.Getenv("LOCATION") == "asia" {
			return ctx.Next()
		}

		return proxy(asiaHost)
	} else {
		if os.Getenv("LOCATION") == "us" {
			return ctx.Next()
		}
		return proxy(usHost)
	}
```

before i find and understand  fasthttp use bytebufferpool  but why use many memory?? 
and if i set limit use memory or other control? 

this is stress test  Get 250mb file data 
```
Showing nodes accounting for 5.25GB, 99.89% of 5.26GB total
Dropped 60 nodes (cum <= 0.03GB)
      flat  flat%   sum%        cum   cum%
    5.25GB 99.89% 99.89%     5.25GB 99.89%  github.com/valyala/fasthttp.appendBodyFixedSize
         0     0% 99.89%     5.25GB 99.91%  github.com/valyala/fasthttp.(*HostClient).Do
         0     0% 99.89%     5.25GB 99.91%  github.com/valyala/fasthttp.(*HostClient).do
         0     0% 99.89%     5.25GB 99.91%  github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp
         0     0% 99.89%     5.25GB 99.89%  github.com/valyala/fasthttp.(*Response).ReadBody
         0     0% 99.89%     5.25GB 99.89%  github.com/valyala/fasthttp.(*Response).ReadLimitBody
         0     0% 99.89%     5.25GB 99.91%  github.com/valyala/fasthttp.clientDoDeadline.func1
         0     0% 99.89%     5.25GB 99.89%  github.com/valyala/fasthttp.readBody
```

```
    9.17GB 99.94% 99.94%     9.17GB 99.94%  github.com/valyala/bytebufferpool.(*ByteBuffer).Write
         0     0% 99.94%     9.17GB 99.94%  bytes.(*Reader).WriteTo
         0     0% 99.94%     9.17GB 99.94%  github.com/gofiber/fiber/v2.(*App).handler
         0     0% 99.94%     9.17GB 99.94%  github.com/gofiber/fiber/v2.(*App).next
         0     0% 99.94%     9.17GB 99.94%  github.com/gofiber/fiber/v2.(*Ctx).Next
         0     0% 99.94%     9.17GB 99.94%  github.com/gofiber/fiber/v2.(*Ctx).SendStream
         0     0% 99.94%     9.17GB 99.94%  github.com/gofiber/fiber/v2/middleware/logger.New.func2
         0     0% 99.94%     9.17GB 99.94%  github.com/valyala/fasthttp.(*Response).Body
         0     0% 99.94%     9.17GB 99.94%  github.com/valyala/fasthttp.(*Server).serveConn
         0     0% 99.94%     9.17GB 99.94%  github.com/valyala/fasthttp.(*workerPool).getCh.func1
```

this is real multi region proxy server call  profiler

![스크린샷 2022-06-09 오후 2 06 00](https://user-images.githubusercontent.com/68882242/172768680-6b7c2bbc-7fb2-4437-9f01-cbf1bff24561.png)

**Comment by erikdubbelboer** [comment]
You're not supposed to create a new `fasthttp.HostClient` for each request. `fasthttp.HostClient` will keep connections open and will have it's own memory buffers associated with it. You need to create a single `fasthttp.HostClient` per host and keep reusing that.

**Comment by ben-swit** [comment]
@erikdubbelboer  thanks your comment ill do set and test  single client

**Comment by ben-swit** [comment]
@erikdubbelboer now 12 hour capture profile 
<img width="1604" alt="스크린샷 2022-06-15 오전 11 09 12" src="https://user-images.githubusercontent.com/68882242/173721450-d9a826c1-df56-4ae6-80f5-f52bb56803a2.png">

set single instance `HostClient` but memory still high

**Comment by erikdubbelboer** [comment]
I can't see much but it seems reasonable to me. Fasthttp will keep a lot of memory in pools/buffers to avoid stressing the garbage collector. It chooses high memory usage over high CPU usage which is always preferable in the normal use cases for fasthttp.

If you don't care about CPU usage (you really shouldn't be using fasthttp) and want low memory usage instead you can call [`fasthttp.SetBodySizePoolLimit`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#SetBodySizePoolLimit) with some really low limits (`1` for example) to prevent fasthttp from keeping memory in pools.
