### ISSUE TITLE
closing an client connection

### ISSUE THREAD

**Issue by DeathRowTools** [valyala/fasthttp#1319]
how can i close clients connections? 
client := &fasthttp.Client{
		Dial: FasthttpHTTPDialer(mainproxy),
		ReadBufferSize: 8192,
	}

after i finish from using this client i want to close it
i have noticed when i create an client, and use it, then stop using it 
it stays open for like 60 seconds or something 
im trying to close it as soon as i finish from using it :)

**Comment by erikdubbelboer** [comment]
[`client.CloseIdleConnections()`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Client.CloseIdleConnections)
