### ISSUE TITLE
Problem with chunked response and gzip

### ISSUE THREAD

**Issue by musicyin** [valyala/fasthttp#1325]
I have ask the problem at  #1322.
But the problem is not solved.
When I try to get the response with resp.Body() , It got repsonse with space
When I try to get the response with resp.BodyUnGzip() , it got error "Unexpected EOF"

The website is https://i.hzmbus.com/webhtml/login
When you requests the website about 5-6 time, it will affect the WAF , the response will issue the problem.
It is not have problem with normal net/http.

How can i get the WAF response with fasthttp client?
Which is something like that
`<html><script>
var arg1='..............................//toolong
var _0x4818= ...................//toolong
        
function setCookie(name,value){.....................//toolong
function reload(x) {.........//toolong
</script></html>`

**Comment by erikdubbelboer** [comment]
The webserver is sending a broken response. It doesn't do proper chunk encoding. net/http might work around this somehow but I'm afraid fasthttp only support correct responses. We have no plan to support broken responses.
```
% curl -v --compressed 'https://i.hzmbus.com/webhtml/login'
...

< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Encoding: gzip

...

* Failed reading the chunked-encoded stream
curl: (23) Failed reading the chunked-encoded stream
```
