### ISSUE TITLE
Bug: Using PeekBytes on a RFC 1123 Time results in incorrect time

### ISSUE THREAD

**Issue by switchupcb** [valyala/fasthttp#1339]
Reproduction
```go
response.Header.PeekBytes([]byte("Date"))
```

Input and Output
```
HTTP/1.1 200 OK
Server: cloudflare
Date: Fri, 08 Jul 2022 10:47:49 GMT
...

Peeked Date: Fri, 08 Jul 2022 10:47:48 GMT
Parsed Date: 2022-07-08 10:47:48 +0000 GMT
```

```
HTTP/1.1 200 OK
Server: cloudflare
Date: Fri, 08 Jul 2022 10:49:46 GMT
...

Peeked Date: Fri, 08 Jul 2022 10:49:45 GMT
Parsed Date: 2022-07-08 10:49:45 +0000 GMT
```

Time Format
https://wiki.freepascal.org/RFC_1123_Time_Format

**Comment by erikdubbelboer** [comment]
Can you maybe give some actual code to reproduce it? Something like this:
```go
func main() {
	var h fasthttp.ResponseHeader

	r := bytes.NewBufferString("HTTP/1.1 200 OK\r\nServer: cloudflare\r\nDate: Fri, 08 Jul 2022 10:47:49 GMT\r\n\r\n")
	br := bufio.NewReader(r)
	if err := h.Read(br); err != nil {
		panic(err)
	}

	// Prints:
	// "Fri, 08 Jul 2022 10:47:49 GMT"
	fmt.Printf("%q\n", h.PeekBytes([]byte("Date")))
}
```

Also keep in mind that HTTP header don't exactly use RFC1123. It's like RFC1123 but with hard-codes GMT as the time zone.

**Comment by switchupcb** [comment]
```go
date, err := time.Parse(time.RFC1123, response.Header.PeekBytes([]byte("Date"))
if err != nil {
    return time.Time{}, fmt.Errorf("error occurred parsing the \"Date\" HTTP Header: %v", err)
}
```

`response.Header.String()`
```
HTTP/1.1 200 OK
Server: cloudflare
Date: Fri, 08 Jul 2022 10:47:49 GMT
...
```

`response.Header.PeekBytes([]byte("Date")`
```
Peeked Date: Fri, 08 Jul 2022 10:49:45 GMT
```

`time.Parse(time.RFC1123, response.Header.PeekBytes([]byte("Date"))`
```
Parsed Date: 2022-07-08 10:49:45 +0000 GMT
```

**Comment by erikdubbelboer** [comment]
How is `response` generated? Can you give me a standalone reproducible example. I can't do anything without that.

**Comment by switchupcb** [comment]
https://github.com/switchupcb/disgo/blob/ratelimit/wrapper/requests.go

```go
request := fasthttp.AcquireRequest()
defer fasthttp.ReleaseRequest(request)
request.Header.SetMethod(method)
request.Header.SetContentTypeBytes(content)
request.Header.Set(headerAuthorizationKey, bot.Authentication.Header)
request.SetRequestURI(uri)
request.SetBodyRaw(body)
response := fasthttp.AcquireResponse()
defer fasthttp.ReleaseResponse(response)

if err := bot.Config.Client.DoTimeout(request, response, bot.Config.Timeout); err != nil {
    return fmt.Errorf("%w", err)
}
```

**Comment by erikdubbelboer** [comment]
I think I get it now. `response.Header.String()` is incorrect. It will always print the current time, not the actual time that was present in the headers: https://github.com/valyala/fasthttp/blob/35aca7b6dfd24a5aa47750137bc4ece280e9ce91/header.go#L2192-L2195
It's also impossible to set `noDefaultDate` as it can only be set by the Server. I don't know why this was build like this in the past.

`response.Header.PeekBytes([]byte("Date"))` will return the correct time, so if you only use that it will work fine.

**Comment by switchupcb** [comment]
It also occurs for `X-Ratelimit-Reset`.

**Comment by erikdubbelboer** [comment]
It shouldn't. That's a custom header that fasthttp wil completely leave alone. @switchupcb can you give some standalone code example that when executed reproduces this?

**Comment by switchupcb** [comment]
https://github.com/switchupcb/disgo/blob/v10/wrapper/request.go#L224

The reset number returned was always a number (representing the [Epoch time (seconds since 00:00:00 UTC on January 1, 1970) at which the rate limit resets](https://discord.com/developers/docs/topics/rate-limits) such as `123565.10x` where x would be a different value every time. Either that API is incorrect or the same issue was occurring since a log of `X-Ratelimit-Reset` would result in something like this within the same Token Bucket.

```
X-Ratelimit-Reset: 123565.104
...
X-Ratelimit-Reset: 123565.104
...
X-Ratelimit-Reset: 123565.107
...
X-Ratelimit-Reset: 123565.110
...
```

**Comment by erikdubbelboer** [comment]
With `response.Header.String()` only the `Date` header is handled differently and set to the current time. All other headers are added unchanged: https://github.com/valyala/fasthttp/blob/35aca7b6dfd24a5aa47750137bc4ece280e9ce91/header.go#L2226-L2228

**Comment by switchupcb** [comment]
If that is the case, it's the server (Discord) doing that I guess.
