### ISSUE TITLE
fasthttp.Response does not offer a method to access the body as a stream

### ISSUE THREAD

**Issue by ItalyPaleAle** [valyala/fasthttp#1340]
When making a request using fasthttp, for example (only relevant lines included):

```go
resp := fasthttp.AcquireResponse()
err := client.Do(req, resp)
```

There's no way to access in `resp` (of type `*fasthttp.Response`) the body as a stream.

**Comment by erikdubbelboer** [comment]
I'm afraid that this is not supported. fasthttp is all about performance and it achieves this by not supporting these kinds of things. Streaming of response bodies doesn't make sense in the use cases fasthttp is for. If you need body streaming it's better to use `net/http`.

**Comment by ItalyPaleAle** [comment]
I am confused tho. The library allows streaming on the server side but not on the client? 🤔

**Comment by erikdubbelboer** [comment]
Correct. This was contributed by someone at some point. A pull request to add support for this for Client would be welcome. But it would have a to be in a way that doesn't hurt performance at all.

**Comment by ItalyPaleAle** [comment]
Proposed PR #1342
