### ISSUE TITLE
client.Do(res, req) bug

### ISSUE THREAD

**Issue by whyynoot** [valyala/fasthttp#1341]
I have an issue with the client.Do(req, res) 

Server responding me with 400 Bad Request with message "illegal parameter" 

So, I tried to do anything with that: tried to sent just clear request only for url etc. 

But every time I try i receive 400 

The same request with or without content plus headers, works with client.Get() / Post() and also from curl, and also from net/http

So, the question is what client.Do adding to the request differently from client.Get / Post()

Not working code: 
```request := fasthttp.AcquireRequest()
request.SetRequestURI(URL)
request.Header.SetMethod(fasthttp.MethodGet)
response := fasthttp.AcquireResponse()
client := fasthttp.Client{}
err := client.Do(req, resp) --> Getting 400
```

Working code: 
```
s, text, err := client.Get(result, URL)
fmt.Println(s, string(text)) --> Getting 200
```
or the same with net/http 
```
response, _ := http.Post(URL, "application/json", bytes.NewBuffer([]byte("")))
fmt.Println(response) --> Getting 200 (text)
```

**Comment by erikdubbelboer** [comment]
The only extra thing `client.Get` does is follow redirects. But 400 is not a redirect.

Can you share a reproducible example so I can check this myself?

**Comment by whyynoot** [comment]
Can I have your email address for private sending?

**Comment by erikdubbelboer** [comment]
erik@dubbelboer.com
