### ISSUE TITLE
Memory Leak in fasthttp Client

### ISSUE THREAD

**Issue by iMro0t** [valyala/fasthttp#1347]
I have found memory leak in fasthttp Client. When it tries to read response body it's causing memory leak. 

Here are 3 graphs of heap snapshots from pprof taken with random intervals 

![profile001](https://user-images.githubusercontent.com/25949138/180613272-d070ee1a-9e51-4045-9c6e-931e50ccad56.png)
![profile002](https://user-images.githubusercontent.com/25949138/180613275-cd824099-ff8b-49b1-b953-aee10378196d.png)
![profile003](https://user-images.githubusercontent.com/25949138/180613279-b3e581d6-d39a-408b-9c1f-c7bfc0a98e5f.png)

**Comment by erikdubbelboer** [comment]
These are not memory leaks. Fasthttp is build for speed. It does this by keeping pools of allocated objects and reusing those, making it lighter on the garbage collector. What you are seeing is these pools growing. If you want low memory usage it's better to use `net/http`.
