### ISSUE TITLE
ctx.Done() isn't done when the request is done

### ISSUE THREAD

**Issue by ItalyPaleAle** [valyala/fasthttp#1350]
Not sure if this is an intended behavior or a bug.

With net/http, the context that is passed with the request (usually, `r.Context()`) is done when the request is complete, so it's common practice to use that as context for operations that are tied to the request.

With fasthttp, it doesn't seem to be the case, as I was able to repro with this code:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	srv := fasthttp.Server{
		//StreamRequestBody: true,
		Handler: requestHandler,
	}
	doneCh := make(chan struct{})
	go func() {
		cancelChan := make(chan os.Signal, 1)
		signal.Notify(cancelChan, syscall.SIGINT, syscall.SIGKILL)
		<-cancelChan
		fmt.Println("Shutting down")
		srv.Shutdown()
		time.Sleep(time.Second)
		close(doneCh)
	}()
	if err := srv.ListenAndServe("127.0.0.1:8080"); err != nil {
		log.Fatalf("Error in ListenAndServe: %v", err)
	}
	<-doneCh
}

func requestHandler(ctx *fasthttp.RequestCtx) {
	go func() {
		select {
		case <-ctx.Done():
			fmt.Println("ctx.Done", ctx.Err())
		case <-time.After(5 * time.Second):
			fmt.Println("timed out waiting for ctx.Done")
		}
	}()
	fmt.Fprintf(ctx, "Hello, world!\n\n")
	ctx.SetContentType("text/plain; charset=utf8")
}
```

Although `fasthttp.RequestCtx` does implement the `context.Context` interface, it seems to be tied to the lifecycle of the server rather than the request.

If this was the intended behavior, could I recommend at least updating the docs to make it clear?

**Comment by erikdubbelboer** [comment]
This is intended. See: https://github.com/valyala/fasthttp/issues/1219#issuecomment-1041548933
