### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by Yelijah** [valyala/fasthttp#1353]
I am a new in fasthttp. I meet EOF error when I use fasthttp. what's that mean and how to fix it? By the way, My server support keep-alived

**Comment by erikdubbelboer** [comment]
I need a lot more information or some way to reproduce what you are seeing.

**Comment by Yelijah** [comment]
> I need a lot more information or some way to reproduce what you are seeing.

 i meet this error when  use one gateway tool ([https://github.com/fagongzi/manba](https://github.com/fagongzi/manba)). but this tool seems to be deprecated whose author don't answer issue.

The dirty code seem to be in pkg/util/fasthttp_client.go:208 which use pool to store conn.

I'm soory, i know it's not suitable to submit issue in this repo. You can reject to answer me

**Comment by erikdubbelboer** [comment]
https://github.com/fagongzi/manba/blob/master/pkg/util/fasthttp_client.go is an almost full (old) copy of https://github.com/valyala/fasthttp/blob/master/client.go. I'm afraid I can't support that since it's not actually fasthttp.
