### ISSUE TITLE
[Question] Is this test correct? Is named "uncompressed" while it's calling WriteDeflate

### ISSUE THREAD

**Issue by Enrico204** [valyala/fasthttp#1354]
The test `TestResponseBodyUncompressed` apparently is using `WriteDeflate`:
https://github.com/valyala/fasthttp/blob/a5f448fc970972ab47113971d898a22fb28fef52/http_test.go#L428

Given the name, I was expecting `.Write()`. Is the test correct?

Note that the response is checked against `Content-Encoding: deflate`:
https://github.com/valyala/fasthttp/blob/a5f448fc970972ab47113971d898a22fb28fef52/http_test.go#L442

**Comment by erikdubbelboer** [comment]
This test is to test the function ʼresp.BodyUncompressed()ʼ.

**Comment by Enrico204** [comment]
OPS! Sorry, I completely missed the "body" in the function name :-(
