### ISSUE TITLE
(*pipeConn).SetDeadline() behavior mismatch with net.Conn

### ISSUE THREAD

**Issue by WKBae** [valyala/fasthttp#1357]
[net.Conn](https://pkg.go.dev/net#Conn) specifies that deadlines should apply to future *and* currently-blocked calls.

> The deadline applies to all future and pending I/O, not just the immediately following call to Read or Write.
> (...)
> SetReadDeadline sets the deadline for future Read calls and any currently-blocked Read call.
> (...)
> SetWriteDeadline sets the deadline for future Write calls and any currently-blocked Write call.

Current implementation of deadline in `fasthttputil.pipeConn` overwrites `c.readDeadlineCh` value, which does not affect blocked `readNextByteBuffer` call.

https://github.com/valyala/fasthttp/blob/af94725d117b19e761d0c6e9c1b157516c482a71/fasthttputil/pipeconns.go#L240-L249

**Comment by erikdubbelboer** [comment]
That's not true.

```go
readDeadlineCh := updateTimer(c.readDeadlineTimer, deadline) 
```
This reuses `c.readDeadlineTimer` which means the same `time.Timer` is being reused, which means the same channel is still being used for all timeouts.

And when resetting a `time.Timer` the channel stays valid and correct: https://go.dev/play/p/BKZHsqo1970
