### ISSUE TITLE
Accidental normalization of double slashes in request URL's

### ISSUE THREAD

**Issue by raviqqe** [valyala/fasthttp#1358]
`fasthttp` seems to normalize double slashes in request URL's passed to its HTTP client. This leads to inconsistent behaviour with the standard `http` package.

```go
func TestDoubleSlash(t *testing.T) {                                                                 
        s := "https://static.googleusercontent.com/media/research.google.com/en//archive/mapreduce-osdi04.pdf"
        r, err := http.Get(s)   

        assert.Nil(t, err)
        assert.Equal(t, 200, r.StatusCode)

        c, _, err := fasthttp.Get(nil, s)

        assert.Equal(t, 404, c)                                                                      
}
```

# References

- https://github.com/raviqqe/muffet/issues/240

**Comment by erikdubbelboer** [comment]
This can be disabled using: [`Client.DisablePathNormalizing = false`](https://pkg.go.dev/github.com/valyala/fasthttp#Client.DisablePathNormalizing)

**Comment by raviqqe** [comment]
Thank you for the answer! My bad I missed it.
