### ISSUE TITLE
missing Location header for http redirect

### ISSUE THREAD

**Issue by zan8in** [valyala/fasthttp#1361]
![image](https://user-images.githubusercontent.com/4088460/186195975-bbe2eac4-db0f-477a-b228-53542497365f.png)
When the header is a lowercase "location", an error info is "missing Location header for http redirect"

**Comment by erikdubbelboer** [comment]
Do you have a standalone code example to reproduce this for me?

**Comment by zan8in** [comment]
Not available due to unauthorized.
https://219.159.20.243:9443
I will delete it in half an hour

**Comment by erikdubbelboer** [comment]
Can you please share a code example. I have no idea what to do with that url. It seems like I can't even connect to that IP.

**Comment by zan8in** [comment]
![image](https://user-images.githubusercontent.com/4088460/186370013-8886d502-3f0a-4026-bdec-498f971b6216.png)
![image](https://user-images.githubusercontent.com/4088460/186370341-725305f3-aec9-4b3a-8412-0a0388e38537.png)

**Comment by zan8in** [comment]
![image](https://user-images.githubusercontent.com/4088460/186370705-704c3abf-c7de-4d45-aa83-9f9b8b5a5dcc.png)
![image](https://user-images.githubusercontent.com/4088460/186370821-5c744c6b-1128-478f-87d5-a024c2fc9b01.png)

**Comment by erikdubbelboer** [comment]
Do you have [`Client.DisableHeaderNamesNormalizing`](https://pkg.go.dev/github.com/valyala/fasthttp#Client.DisableHeaderNamesNormalizing) set to `true`? If so, try setting that to `false`.

**Comment by zan8in** [comment]
thanks
