### ISSUE TITLE
fasthttp.HostClient HTTPS

### ISSUE THREAD

**Issue by diacc234** [valyala/fasthttp#1362]
I can't get fasthttp.HostClient + fasthttp.URI to recognize I'm using HTTPS.

I'm seeing this error: _HostClient can't follow redirects to a different protocol, please use Client instead_

I've traced the error to this piece of logic in client.go
    func (c *HostClient) doNonNilReqResp(req *Request, resp *Response) (bool, error) {
    ...
    	if c.IsTLS != req.URI().isHttps() {
		return false, ErrHostClientRedirectToDifferentScheme
	}
	

if I dump the values for c.IsTLS and req.URI().Schema, I see:

      fmt.Printf("httpClient.IsTLS ? %v\n", httpClient.IsTLS)
      httpClient.IsTLS ? true

     fmt.Printf("scheme=%s", string(fastReq.URI().Scheme()))
     scheme=https
     
     so this comparison must be coming back false:

     func (u *URI) isHttps() bool {
	return bytes.Equal(u.scheme, strHTTPS)
      }

 My setup is pretty simple:

         cfg.HttpClient = &fasthttp.HostClient{
		Addr:         cfg.URL.Host,
		IsTLS:        true,
		TLSConfig:    tlsConfig,
		MaxConns:     cfg.MaxConnections,
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		RetryIf:      nil,
		Dial:         dialFunc,
	}

	m.FastUri = fasthttp.AcquireURI()
	defer fasthttp.ReleaseURI(m.FastUri)

	m.FastReq = fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(m.FastReq)

       ...
      	m.FastUri.SetPath(path)
	m.FastUri.SetScheme("https")
	m.FastReq.SetURI(m.FastUri)

Am I missing the obvious ?

**Comment by erikdubbelboer** [comment]
Do you have some standalone code to reproduce this? Like a `func main()` that creates the client like above, sets actual values and tries to make the request but gets this error instead. Now I have no idea what `...` does for example...

**Comment by diacc234** [comment]
Thank you for the quick response. 

here's the snippet - after a bit more digging, I highlighted the line that was really causing the issue.

What I was trying to do was get the **FULL** URL after setting the path, query params....is there a way I can get that or do I need to store that off into other variables as I'm setting up these objects ?

```
func main() {
	httpClient := &fasthttp.HostClient{
		Addr:  "localhost:8443",
		IsTLS: true,
	}

	fastUri := fasthttp.AcquireURI()
	defer fasthttp.ReleaseURI(fastUri)
	fastUri.SetPath("test/hello")
	fastUri.SetScheme("https")

	fastReq := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(fastReq)
	fastReq.SetURI(fastUri)

	fastResp := fasthttp.AcquireResponse()

	fmt.Printf("httpClient tls: %v\n", httpClient.IsTLS)
	fmt.Printf("uri scheme:  %v\n", string(fastUri.Scheme()))
	fmt.Printf("req uri scheme: %v\n", string(fastReq.URI().Scheme()))

	// this lines causes this error:   HostClient can't follow redirects to a different protocol, please use Client instead
	fmt.Printf("req uri: %v\n", string(fastReq.RequestURI()))

	if e := httpClient.Do(fastReq, fastResp); e != nil {
		fmt.Printf("error: %v\n", e)
	}
}```

**Comment by diacc234** [comment]
looks like I can get the full uri via Uri.FullURI()

**Comment by erikdubbelboer** [comment]
I know the whole RequestURI API is a mess, but we can't change it without breaking backwards compatibility. Good that you found a solution.
