### ISSUE TITLE
Support for INSTANA 

### ISSUE THREAD

**Issue by AdarshBP** [valyala/fasthttp#1366]
Hi , how do we setup instana in fasthttp framework, right now we added using opentracing , looks like it is not working as expected .

**Comment by erikdubbelboer** [comment]
Is this the same issue as https://github.com/valyala/fasthttp/issues/775 and https://github.com/valyala/fasthttp/issues/940?

**Comment by AdarshBP** [comment]
Yes it is the same

**Comment by li-jin-gou** [comment]
I am working on this piece of content and if it is finished I will PR it as soon as possible.❤️

**Comment by gyliu513** [comment]
@li-jin-gou any progress for this? Why did this issue got closed? Thanks
