### ISSUE TITLE
Using fasthttp with a proxy list.

### ISSUE THREAD

**Issue by comboed** [valyala/fasthttp#1369]
Hello,
So I've been using FastHTTP for quite some time and I've had an issue that I've brushed aside when using the library since I did not believe I was going to need it. When it connect to a single rotating proxy, the proxies would rotate fine and I had no issues. But when it came an actual proxy list, changing the value of client.Dial would not work and it would still reuse the same proxy/connection. I have tried using connection: close, and setting the MaxConnDuration to a second but have no luck.

Here is the test code I have bee using

```
package main

import (
	"github.com/valyala/fasthttp/fasthttpproxy"
	"github.com/valyala/fasthttp"
	"math/rand"
	"bufio"
	"fmt"
	"os"
)


var client = &fasthttp.Client{}
var proxies []string

func loadFIles() {
	var file, _ = os.Open("proxies.txt")
	defer file.Close()
	var scan *bufio.Scanner = bufio.NewScanner(file)
	for scan.Scan() {
		proxies = append(proxies, scan.Text())
	}
}

func Test() {
	for {
		client.Dial = fasthttpproxy.FasthttpHTTPDialer(proxies[rand.Intn(len(proxies))])
		
		var request *fasthttp.Request = fasthttp.AcquireRequest()
		var response *fasthttp.Response = fasthttp.AcquireResponse()

		request.Header.SetMethod("GET")
		request.SetRequestURI("API ENDPOINT")
		
		request.Header.Set("Connection", "close")

		client.Do(request, response)

		fmt.Println(string(response.Body()))
		fmt.Println(client.Dial)
	}
}

func Run() {
	loadFIles()

	for i := 0; i < 1; i++ {
		go Test()
	}
}
```

Is there another way I should be doing it?

**Comment by erikdubbelboer** [comment]
The problem is that changing `client.Dial` while the client is already in use doesn't work (it gets copied internally so you change has no effect).

What you want is:
```go
client := &fasthttp.Client{
    Dial: func(addr string) (net.Conn, error) {
        return fasthttpproxy.FasthttpHTTPDialer(proxies[rand.Intn(len(proxies))])(addr)
    },
}

**Comment by comboed** [comment]
> The problem is that changing `client.Dial` while the client is already in use doesn't work (it gets copied internally so you change has no effect).
> 
> What you want is:
> 
> ```go
> client := &fasthttp.Client{
>     Dial: func(addr string) (net.Conn, error) {
>         return fasthttpproxy.FasthttpHTTPDialer(proxies[rand.Intn(len(proxies))])(addr)
>     },
> }
> ```

But then wouldn't this slow the program completely having to constantly re-declare client every time I want to establish a new proxy?

**Comment by comboed** [comment]
> That replaces `var client = &fasthttp.Client{}`. So you still keep reusing that client in your for loop.

I have one more question. Please excuse my ignorance but as you know setting the connection to "close" allows you to rotate a proxy and establish a connection. However it throttles the program having to reopen/close the connections. What would be a suitable solution to go about this?

**Comment by erikdubbelboer** [comment]
You would have to use your own pool of HostClients instead of Client. Then you can have each HostClient use a different proxy and just randomly use one of those.

**Comment by comboed** [comment]
> You would have to use your own pool of HostClients instead of Client. Then you can have each HostClient use a different proxy and just randomly use one of those.

Would you by any chance have an example code?

**Comment by comboed** [comment]
Alright I wrote a simple function that creates a pool of host clients, my issue is that now it's giving either status code 502 or 400. Proxies are working fine so I don't know if i'm doing something wrong with how i create my host client

```
package main

import (
	"bufio"
	"crypto/tls"
	"fmt"
	"math/rand"
	"os"

	"github.com/valyala/fasthttp"
	"github.com/valyala/fasthttp/fasthttpproxy"
)


var proxies []string
var hostClients map[int]*fasthttp.HostClient

func loadFIles() {
	var file, _ = os.Open("proxies.txt")
	defer file.Close()
	var scan *bufio.Scanner = bufio.NewScanner(file)
	for scan.Scan() {
		proxies = append(proxies, scan.Text())
	}
}

func check() {
	for {
		var request *fasthttp.Request = fasthttp.AcquireRequest()
		var response *fasthttp.Response = fasthttp.AcquireResponse()

		request.Header.SetMethod("GET")
		request.SetRequestURI("API ENDPOINT")
		
		request.Header.Set("Host", "API HOST")


		err := hostClients[rand.Intn(len(hostClients))].Do(request, response)
		fmt.Println(string(response.Body()), err)
	}
}

func clientConfig(proxy string) *fasthttp.HostClient {	
	return &fasthttp.HostClient {
		TLSConfig: 						&tls.Config{InsecureSkipVerify: true},
		Dial: 							fasthttpproxy.FasthttpHTTPDialer(proxy),
		IsTLS: 							true,
	}
}

func setProxies() {
	for i := range proxies {
		hostClients[i] = clientConfig(proxies[i])
	}
}

func main() {
	loadFIles()

	hostClients = make(map[int]*fasthttp.HostClient, len(proxies))
	setProxies()

	for i := 0; i < 350; i++ {
		go check()
	}

	select {}
}
```

**Comment by erikdubbelboer** [comment]
Are `API ENDPOINT` and `API HOST` always the same? You can only use a `HostClient` to connect to a single host.

You need to set [`HostClient.Addr`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#HostClient.Addr), that address will be passed to the proxy to connect to.
