### ISSUE TITLE
Set-Cookie Header Normalization

### ISSUE THREAD

**Issue by gjchapmn** [valyala/fasthttp#1370]
Is there no way to have the set-cookie header normalization disabled? It's necessary to have the set cookie header string be able to be manipulated if you want to return multiple set cookies from a lambda behind api gateway because api gateway will drop multiple header keys https://stackoverflow.com/questions/39769222/how-can-i-send-multiple-set-cookie-headers-from-api-gateway-using-a-proxied-lamb

**Comment by erikdubbelboer** [comment]
I'm not sure I understand. What is `header normalization` doing that is preventing this? Can you give some example code to reproduce this issue?

**Comment by gjchapmn** [comment]
Hi,

It's tricky to reproduce the issue because you'll only see it on a lambda behind api-gateway. The gist of it is that I'd like to manually set the header key's like so:

Where header is a fasthttp ResponseHeader

`header.set("set-cookie", "cookie1=value1")`
`header.set("sEt-cookie", "cookie2=value2")`
`header.set("seT-cookie", "cookie3=value3")`
`header.set("test-KEY", "value3")`

because this is unfortunately the main way to have multiple set cookie headers using a lambda with api gateway 
https://stackoverflow.com/questions/66284664/multiple-set-cookie-headers-ignored-by-api-gateway-in-combination-with-lambda-in

Even if I set `disableNormalizing` to true other header keys won't be normalized but because set-cookie is considered a special header when I check my responses the first 2 headers end up dropped and it will end up as.
https://github.com/valyala/fasthttp/blob/404c8a896896943715f8fb3906a8d054fae17d3e/header.go#L1250

`Response Headers
    Set-Cookie: cookie3=value3
    test-KEY: value3
`

Set-Cookie still ends up normalized. So using fasthttp I can't seem to find a way around this header issue.

**Comment by erikdubbelboer** [comment]
[Cookies are handled differently than other headers](https://github.com/valyala/fasthttp/blob/ea6052464e7221956dedf9b9a523f8f9892c3d3b/header.go#L1282-L1288). What you are asking isn't possible. The only way this would be possible is if you fork fasthttp and expose [`setNonSpecial`](https://github.com/valyala/fasthttp/blob/ea6052464e7221956dedf9b9a523f8f9892c3d3b/header.go#L1307-L1310) in your fork so you can call that.

I don't want to change fasthttp just to accommodate this ridiculous behavior. Amazon should fix their shit instead.
