### ISSUE TITLE
Calling shutdown in advance will cause 'server' cannot exit

### ISSUE THREAD

**Issue by zc2638** [valyala/fasthttp#1371]
test code
```go
func main() {
        closeChan := make(chan struct{}, 1)
	...
	closeChan <- struct{}{}

	srv := &fasthttp.Server{}
	go func() {
		<-closeChan
		srv.Shutdown()
	}()
	srv.ListenAndServe(":8080")
}
```

fasthttp version: v1.38.0

**Comment by erikdubbelboer** [comment]
What do you mean by `cannot exist`?

When I try this code instead:
```go
func main() {
	srv := &fasthttp.Server{}
	go func() {
		if err := srv.Shutdown(); err != nil {
			println(err.Error())
		}
	}()
	time.Sleep(time.Second)
	if err := srv.ListenAndServe(":8080"); err != nil {
		println(err.Error())
	}
}
```
It works fine an just starts the server. Of course calling `Shutdown` before `ListenAndServe` doesn't do anything and calling `ListenAndServe` after that will just start the server.

**Comment by zc2638** [comment]
I want it to work like `http.Server`, after calling shutdown, the server will not start.
`Shutdown` and `ListenAndServe` will be started in different goroutines, using `context` or `channel` to ensure the exit of all services.
During the service startup phase, my other services threw an exception, and `shutdown` will be called at this time, but `ListenAndServe` still executes normally.

**Comment by erikdubbelboer** [comment]
Fasthttp servers can be reused after Shutdown has returned. If you don't want this you will have to keep this state yourself.
