### ISSUE TITLE
Is using the client faster

### ISSUE THREAD

**Issue by Mewzax** [valyala/fasthttp#1372]
Hello, I have a little question. Is using the client faster to make requests ? And if yes, what TLS config should I use ?

```go
package main

import (
	"crypto/tls"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	client := &fasthttp.Client{
		TLSConfig: &tls.Config{
			InsecureSkipVerify: true,
			ClientSessionCache: tls.NewLRUClientSessionCache(0),
		},
	}
	tries := 200

	for i := 0; i < tries; i++ {
		req := fasthttp.AcquireRequest()
		res := fasthttp.AcquireResponse()

		req.SetRequestURI("https://google.com")

		if err := client.Do(req, res); err != nil {
			panic(err)
		}
		println(res.StatusCode())

		fasthttp.ReleaseRequest(req)
		fasthttp.ReleaseResponse(res)
	}
}
```

Thank's by advance

**Comment by Mewzax** [comment]
ok i just saw fasthttp.Do was using a default Client (so perfs are equal) but what is the faster tls config ?

**Comment by erikdubbelboer** [comment]
`InsecureSkipVerify: true` makes it faster, but of course also less secure.

Setting a `ClientSessionCache` can also be faster, but keep in mind that not all servers handle this correctly. And it's always faster to just use keep-alive connections so you don't have to do the TLS handshake multiple times.
`tls.NewLRUClientSessionCache(0)` sets a default cache size of `64`. If you're going to connect to more servers than this you might want to increase it.

**Comment by akbulutdora** [comment]
> `InsecureSkipVerify: true` makes it faster, but of course also less secure.
> 
> Setting a `ClientSessionCache` can also be faster, but keep in mind that not all servers handle this correctly. And it's always faster to just use keep-alive connections so you don't have to do the TLS handshake multiple times. `tls.NewLRUClientSessionCache(0)` sets a default cache size of `64`. If you're going to connect to more servers than this you might want to increase it.

What would be the faster configurations if we want to do one get request per host? I believe disabling keep-alive is better for that. Is it possible to do it with fasthttp?

**Comment by erikdubbelboer** [comment]
I would use a single `HostClient` per request and call [`HostClient.CloseIdleConnections()`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#HostClient.CloseIdleConnections) after the request.

**Comment by akbulutdora** [comment]
> I would use a single `HostClient` per request and call [`HostClient.CloseIdleConnections()`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#HostClient.CloseIdleConnections) after the request.

I am sorry, I might have expressed myself wrong. Do you mean creating a new HostClient per GET request?

**Comment by erikdubbelboer** [comment]
Yes, a `HostClient` can only be used to connect to a single hostname. So if you're going to do only one request per hostname you'll have to create a new one for each hostname. `fasthttp.Client` would do that as well if you would use `Client`.
