### ISSUE TITLE
getting tonnes of Receive() returned set tcp 172.17.0.4:57050: use of closed network connection after long running process in test server...

### ISSUE THREAD

**Issue by vipsland** [valyala/fasthttp#1380]
getting tonnes of Receive() returned set tcp 172.17.0.4:57050: use of closed network connection after long running process in test server but production server doesnt seem to be affected. how do i debug? i dont even know where this issue is coming from.

2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection
2022/09/17 03:56:27 Receive() returned set tcp 172.17.0.4:57050: use of closed network connection

**Comment by erikdubbelboer** [comment]
ʼReceive()ʼ is not a fasthttp or stdlib function so I don't think this has anything to do with fasthttp?

**Comment by vipsland** [comment]
ok thx. i think it's customized redis section. thx
