### ISSUE TITLE
Optimized RequestHeader Peek / Exposing RequestHeader.h

### ISSUE THREAD

**Issue by karlseguin** [valyala/fasthttp#1391]
Calling `ctx.Request.Header.PeekBytes([]byte("My-Header"))`  copies the provided header, loops through for normalization and converts it to a string to compare it against known headers. I think it's a common case where the caller will know that none of those steps are necessary and could be replaced with something like:

```
func (h *RequestHeader) PeekDirect(key []byte) []byte {
	return peekArgBytes(h.h, key)
}
```

Or, alternatively and possibly more flexibly, exposing h.h.

**Comment by erikdubbelboer** [comment]
All those operations you mention are super fast and don't cause any allocations. With adding `PeekDirect` or exposing `h.h` there will be many people who don't understand this, and will try to use it for headers like `UserAgent` which will fail. So I'm not in favor of this.
