### ISSUE TITLE
How to use Context with fasthttp? Like we have r.Context() in net.http.Request.

### ISSUE THREAD

**Issue by Devendrabhat** [valyala/fasthttp#1393]
I want to get an alternative to this context function in http.Request. Can someone please guide me if I'm missing something?

```
// HTML writes a string to the response, setting the Content-Type as text/html.
func HTML(w http.ResponseWriter, r *http.Request, v string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if status, ok := r.Context().Value(statusCtxKey).(int); ok {
		w.WriteHeader(status)
	}
	w.Write([]byte(v))
}
```

**Comment by erikdubbelboer** [comment]
Firstly, if you're going to use Context then you shouldn't be using fasthttp. It just doesn't make any sense to use those together. So I would strongly suggest you switch to using net/http as it's much better.

But if you have to, then your handler will receive a [`fasthttp.RequestCtx`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx) as argument which itself acts as Context and has the [`Value`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx.Value) method you want to use already.

**Comment by Devendrabhat** [comment]
Thank you so much @erikdubbelboer for your quick response. Actually, we have our product backend written in GoLang and are using fasthttp in it. Now when we were trying to integrate an APM with it the vendor organization is supporting only net/http and is using context very extensively. Now even if I write my own handler wrapper function using fasthttp the background functions I'll need to call for integration are asking me for the context object. Following is the APM code we want to integrate. - https://github.com/appoptics/appoptics-apm-go

PS- Can you please recommend to us some APMs we can use which are supporting fasthttp as well?

**Comment by erikdubbelboer** [comment]
It's going to be really hard to integrate something like that, I don't see how to do it right now.

I'm afraid I don't know of anything like that that support fasthttp. Actual use cases for fasthttp are so performance critical that you don't want code like that to slow you down. People who have actual fasthttp use cases will write their own fast code to measure performance.
