### ISSUE TITLE
error while get -u

### ISSUE THREAD

**Issue by banmeetangv5** [valyala/fasthttp#1399]
After run go get -u github.com/valyala/fasthttp
There are many error shown as below
# github.com/klauspost/compress/flate
../go/src/github.com/klauspost/compress/flate/deflate.go:135:23: cannot convert d.window (type []byte) to type *[32768]byte
../go/src/github.com/klauspost/compress/flate/deflate.go:135:56: cannot convert d.window[windowSize:] (type []byte) to type *[32768]byte
../go/src/github.com/klauspost/compress/flate/fast_encoder.go:93:28: cannot convert e.hist (type []byte) to type *[32768]byte
../go/src/github.com/klauspost/compress/flate/fast_encoder.go:93:63: cannot convert e.hist[offset:] (type []byte) to type *[32768]byte
../go/src/github.com/klauspost/compress/flate/huffman_bit_writer.go:794:17: cannot convert w.literalFreq[:] (type []uint16) to type *[256]uint16
../go/src/github.com/klauspost/compress/flate/huffman_bit_writer.go:796:16: cannot convert w.literalFreq[256:] (type []uint16) to type *[32]uint16
What should I do for solving this problem?

**Comment by erikdubbelboer** [comment]
As you can see all the errors are in github.com/klauspost/compress, I suggest you make an issue there.
