### ISSUE TITLE
PeekKeys and PeekKeysTrailer

### ISSUE THREAD

**Issue by codefromthecrypt** [valyala/fasthttp#1400]
Similar to #179, we should have a convenience to get all existing normal and trailing header keys. Notably this is more tricky because some values are internal.

See See https://github.com/mosn/pkg/issues/66

**Comment by li-jin-gou** [comment]
This issue should be closed  cc @erikdubbelboer ❤️

**Comment by codefromthecrypt** [comment]
nice!
