### ISSUE TITLE
ResponseHeader VisitAll adds default Content-Type

### ISSUE THREAD

**Issue by codefromthecrypt** [valyala/fasthttp#1402]
It is currently difficult to tell if the user set a content-type header or not because VisitAll backfills even if it doesn't look like it.

For example, it guards on `h.ContentType()` being greater than zero, but the impl always backfills, unless I'm missing something.

```
func (h *ResponseHeader) VisitAll(f func(key, value []byte)) {
	if len(h.contentLengthBytes) > 0 {
		f(strContentLength, h.contentLengthBytes)
	}
	contentType := h.ContentType()
	if len(contentType) > 0 {
		f(strContentType, contentType)
	}

--snip---

func (h *ResponseHeader) ContentType() []byte {
	contentType := h.contentType
	if !h.noDefaultContentType && len(h.contentType) == 0 {
		contentType = defaultContentType
	}
	return contentType
}
```

**Comment by li-jin-gou** [comment]
refer to https://github.com/valyala/fasthttp/blob/master/server.go#L371

**Comment by codefromthecrypt** [comment]
ok I see what you mean. thanks!
