### ISSUE TITLE
How to trace the server.go function "writeResponse"?

### ISSUE THREAD

**Issue by hebo1982** [valyala/fasthttp#1404]
I use fasthttp for a reverseproxy.
I want to log the response time to send to the client.

But <i>Server.Hander</i> not handle this, <i>Server.ServConn(conn)</i> without Context.

```go
// server.go line 2519
func writeResponse(ctx *RequestCtx, w *bufio.Writer) error {
	if ctx.timeoutResponse != nil {
		panic("BUG: cannot write timed out response")
	}
	err := ctx.Response.Write(w)

	return err
}
```
Should this func suport handler?

**Comment by hebo1982** [comment]
<i>ConnState: func(conn net.Conn, state fasthttp.ConnState)</i>
Can get the content?

**Comment by erikdubbelboer** [comment]
I'm not sure I understand your first question?

In `ConnState` there is no valid context to pass to the function. This function can be called outside a request handler when there is no valid context. If you need to do something with stats you can use `conn` as a key in a map maybe?

**Comment by hebo1982** [comment]
@erikdubbelboer  Thanks for u reply

I want log record as nginx log_format:

```
log_format  main1  '$remote_addr - $remote_user [$time_local] "$http_host" "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    '"_uid=$cookie__uid" "fid=$cookie_fid" '
                    '$upstream_addr '
                    'ups_resp_time: $upstream_response_time '
                    'request_time: $request_time';
```

With <i>RequestHandler</i> can't get the "request_time".

```
time elapsed between the first bytes were read from the client and the log write after the last bytes were sent to the client
```

With <i>ConnState</i> handler can't get the $cookie, $status and so on that in context.

**Comment by erikdubbelboer** [comment]
You can use [`RequestCtx.Conn`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#RequestCtx.Conn) as a key to store information like the cookie and status in a map. Then in `ConnState` you can use that information as it also gets `conn` as a parameter.
