### ISSUE TITLE
%2f处理

### ISSUE THREAD

**Issue by xxxlzj520** [valyala/fasthttp#1409]
req := fasthttp.AcquireRequest()
defer fasthttp.ReleaseRequest(req)
req.SetRequestURI("http://192.168.0.89:15672/api/aliveness-test/%2f")
req.Header.SetMethod(fasthttp.MethodGet)
resp := fasthttp.AcquireResponse()
defer fasthttp.ReleaseResponse(resp)

当请求发出时，会忽略%2f。如何做到不忽略%2f，这本身就是url的一部分。

**Comment by erikdubbelboer** [comment]
你需要改 [client.DisablePathNormalizing = true](https://pkg.go.dev/github.com/valyala/fasthttp#Client.DisablePathNormalizing)
