### ISSUE TITLE
prefork mode listening to two addresses. is this possible?

### ISSUE THREAD

**Issue by ultperf** [valyala/fasthttp#1412]
need prefork mode listening to two addresses. is this possible?
if so, possible to show an example?

**Comment by li-jin-gou** [comment]
The fiber framework developed based on fasthttp supports this capability, perhaps you can refer to its code.

**Comment by hiqsociety** [comment]
fantastic though, any pure fasthttp example for this? because not using fiber at the moment

pls provide pure fasthttp example. thx
