### ISSUE TITLE
do we need to use mutex in prefork mode?

### ISSUE THREAD

**Issue by ultperf** [valyala/fasthttp#1413]
just curious, and to confirm. for prefork mode it is in single thread per process, so mutex is totally unnecessary right since memory cannot be shared.

is there any circumstances that i'm not foreseeing that mutex will be needed in prefork mode ( in regards with memory access and nothing over database etc )

**Comment by li-jin-gou** [comment]
I don't think it's necessary. What do other guys think?😳

**Comment by erikdubbelboer** [comment]
Memory can still be shared between multiple goroutines running in that single process. And goroutines can be pre-empted at any point. So you will still need mutexes to protect data accessed from multiple goroutines.
