### ISSUE TITLE
prefork mode but listen on different addresses. how to do?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1418]
any examples to show prefork mode listening from 8080 to 8090?

e.g. listening to 8080-8090

each prefork listens to a unique port.

**rationale : prefork is cool.**
if it's killed / down, it'll spawn another one through master BUT i dont want to listen to same port because my reverse proxy will route to different port of the spawned listening process.

how to get this done?

**Comment by erikdubbelboer** [comment]
That's just not now prefork works. In that case wouldn't use prefork but start the processes myself and use https://pkg.go.dev/github.com/valyala/fasthttp/reuseport?utm_source=godoc so multiple processes can listen on the same port.
