### ISSUE TITLE
copyTo is for req and resp but what about ctx? <- would like to copy ctx 

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#1421]
copyTo is for req and resp but what about ctx? <- would like to copy ctx 

is there a 
ctxTemp := ??? &fasthttp?
ctx.CopyTo(ctxTemp)?

how do i do this?

**Comment by hiqsociety** [comment]
saw this but couldnt find example. can anyone help? the line is gone anyway too.
https://github.com/valyala/fasthttp/issues/330

**Comment by li-jin-gou** [comment]
why not use ctx.Copy()?

**Comment by hiqsociety** [comment]
ctx.CopyTo undefined (type *fasthttp.RequestCtx has no field or method CopyTo)
```
	ctxTemp := &fasthttp.RequestCtx{}
	//	reqTemp := fasthttp.AcquireRequest()
	ctx.CopyTo(ctxTemp)
	```

**Comment by li-jin-gou** [comment]
> ctx.CopyTo undefined (type *fasthttp.RequestCtx has no field or method CopyTo)
> 
> ```
> 	ctxTemp := &fasthttp.RequestCtx{}
> 	ctx.CopyTo(ctxTemp)
> 	
> ```
I thought it would have this feature.😂

**Comment by li-jin-gou** [comment]
> ...
> 
> 我们可以复制到 req 和 resp。如何为 ctxTemp 结合 req 和 resp？

```
	cp := &RequestCtx{
	}
	ctx.Request.CopyTo(&cp.Request)
	ctx.Response.CopyTo(&cp.Response)
```
I note this comment

https://github.com/valyala/fasthttp/blob/f095481f0014ab50fc4c8593d6751ab3584b2457/server.go#L562

**Comment by hiqsociety** [comment]
i havent check in detail but i wonder if 

	ctx.Request.CopyTo(&cp.Request)
	ctx.Response.CopyTo(&cp.Response)

is all of ctx? anything i need to copy also? just curious

**Comment by li-jin-gou** [comment]
I think this is sufficient if you are just getting the request and response data.
