### ISSUE TITLE
i know we dont have http2 for fasthttp but can we force it to use tls 1.3?

### ISSUE THREAD

**Issue by ultperf** [valyala/fasthttp#1428]
i dunno much about this area only that fasthttp is still using http 1.1 that's all

i know we dont have http2 for fasthttp but can we force it to use tls 1.3?

coz tls 1.3 has 0 rtt.

**Comment by erikdubbelboer** [comment]
fasthttp uses the default net/tls config which uses 1.3 by default. What makes you think 1.3 isn't used?

**Comment by ultperf** [comment]
coz crypto/tls is v slow.
without tls, it's 50k req/s. with tls, 10k req/s
putting haproxy / nginx in front is better but not elegant, waste extra bandwidth and memory.

thx anyway

**Comment by erikdubbelboer** [comment]
I completely agree but I'm afraid there isn't much we can do except wait for the Go team to improve the speed.
