### ISSUE TITLE
HEAD request encounters Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by tonywang** [valyala/fasthttp#1438]
I try to request a file with `fasthttp.Client` send `HEAD` request, which is used to detect file-related header information.
At this time, the request will return `< Transfer-Encoding: chunked`

> https://github.com/valyala/fasthttp/blob/master/http.go#L1362
```

	if resp.Header.ContentLength() == -1 {
		err = resp.Header.ReadTrailer(r)
		if err != nil && err != io.EOF {
			if isConnectionReset(err) {
				return nil
			}
			return err
		}
	}
	return nil
```

it will enter this process, but the file API does not return `Trailer` information, so this will cause the request to be blocked until the read timeout.

**Comment by erikdubbelboer** [comment]
Do you have an example url or an example response?

**Comment by tonywang** [comment]
Hi @erikdubbelboer 

I got this issue, our backend system doesn't response correct header when request by HEAD.

I think this issue could be closed.

Thanks :)

**Comment by li-jin-gou** [comment]
> Hi @erikdubbelboer
> 
> I got this issue, our backend system doesn't response correct header when request by HEAD.
> 
> I think this issue could be closed.
> 
> Thanks :)

You can also close it.😳
