### ISSUE TITLE
[Bug] ERR_CONTENT_LENGTH_MISMATCH on static files

### ISSUE THREAD

**Issue by MindMayhem** [valyala/fasthttp#1445]
Hi, caught an error on all frameworks that uses fasthttp (fiber, atreugo, ...) while we serving big static files
Here's another issue (but on goFiber) - https://github.com/gofiber/fiber/issues/2244

`Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`

### How to Reproduce
- Place a large static file in the public folder and launch server.
- Try to open the file in a browser
- See console or network tab.

### Expected Behavior
- Give the browser the entire file.

This bug is reproduced on latest fasthttp version - **v1.42.0**
On version v1.41.0 , there are no problems.

**Comment by erikdubbelboer** [comment]
I can't seem to reproduce this. Can you share a file and a `func main()` that I can just run and reproduce this?

**Comment by smalloff** [comment]
> I can't seem to reproduce this. Can you share a file and a `func main()` that I can just run and reproduce this?

[gofiber_test_bug.zip](https://github.com/valyala/fasthttp/files/10102414/gofiber_test_bug.zip)

Hi! Launch server and go 127.0.0.1:8080/ckeditor.css
Look browser debug console

**Comment by erikdubbelboer** [comment]
I have just released v1.43.0 which reverts the change that caused this bug.

**Comment by smalloff** [comment]
> I have just released v1.43.0 which reverts the change that caused this bug.

Thanks It works.
