### ISSUE TITLE
stop running Handler

### ISSUE THREAD

**Issue by sten4eg** [valyala/fasthttp#1447]
How can I stop running TestHandler() with TimeoutHandler() ?
when the time is right  TimeoutHandler() it sends a msg and a status to a client but TestHandler() continues to work although I don't want it to send a requset to the database, it’s not already needed.
I use fasthttp/router.
code like this 

```
func main {
r := router.New()
r.GET("/test", TestHandler)
fasthttp.ListenAndServe(":8181", fasthttp.TimeoutHandler(r.Handler, time.Second*2, "timeout"))
}
```

```
func TestHandler(ctx *fasthttp.RequestCtx) {
  time.Sleep(time.Second * 7)
  database.GetItem(ctx)
  fmt.Println("done")
}
```

**Comment by li-jin-gou** [comment]
As far as I know this is difficult to do, because we can't kill a goroutine that is executing.
