### ISSUE TITLE
fasthttpClient can not support huge Response

### ISSUE THREAD

**Issue by xj524598** [valyala/fasthttp#1451]
when fasthttpClient receive response size is huge  ,then  mistake is show up

<img width="944" alt="image" src="https://user-images.githubusercontent.com/26913796/205668793-e396e97e-5e57-4bef-ad03-f195dc27c6ba.png">
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/26913796/205668897-042ef30c-1cf0-40f8-a42d-da468b6afada.png">

**Comment by li-jin-gou** [comment]
same to https://github.com/valyala/fasthttp/issues/1419
