### ISSUE TITLE
client.go: getClientName() may be removed

### ISSUE THREAD

**Issue by stokito** [valyala/fasthttp#1458]
When client performs a request it sets a UA if it wasn't set:
```go
userAgentOld := req.Header.UserAgent()
if len(userAgentOld) == 0 {
	req.Header.userAgent = append(req.Header.userAgent[:0], c.getClientName()...)
}
```
The getClientName() checks if !NoDefaultUserAgentHeader then returns the Client.Name field.
But it also saves it to atomic field `clientName`:
```go
func (c *pipelineConnClient) getClientName() []byte {
	v := c.clientName.Load()
	var clientName []byte
	if v == nil {
		clientName = []byte(c.Name)
		if len(clientName) == 0 && !c.NoDefaultUserAgentHeader {
			clientName = defaultUserAgent
		}
		c.clientName.Store(clientName)
	} else {
		clientName = v.([]byte)
	}
	return clientName
}
```
From what I see the clientName is basically just not needed. It never changes.
We can safely simplify to something like:
```go
userAgentOld := req.Header.UserAgent()
if len(userAgentOld) == 0 {
	userAgent := c.Name
	if userAgent == "" && !c.NoDefaultUserAgentHeader {
		userAgent = defaultUserAgent
	}
	if userAgent != "" {
		req.Header.userAgent = append(req.Header.userAgent[:], userAgent...)
	}
}
```

Is there any reason to have that atomic or I get something wrong?
@kiyonlin you was a last who changed that code, please participate
https://github.com/valyala/fasthttp/commit/02e0722fb73c6237818b8e5af55957eb919a7334

**Comment by erikdubbelboer** [comment]
Correct. The code was copied from HostClient. I think it did something in the past that isn't relevant anymore. Can you make a pull request?

**Comment by stokito** [comment]
Ideally we can make an interface for a client with Name() and NoDefaultUserAgentHeader() and make a generic function but not sure if the small change worth it
