### ISSUE TITLE
Asynchronous processing of RequestCtx in a goroutine

### ISSUE THREAD

**Issue by pkedy** [valyala/fasthttp#146]
I am experimenting with using fasthttp to implement an API gateway/reverse proxy.  At the end of a handler, I'd like to continue using the RequestCtx in a goroutine (e.g. for capturing attributes to send to an analytics server) while concurrently sending the response to the client.  The problem with this is that in the current code (serveConn in server.go), the RequestCtx can be immediately used by the next request for the connection so the context data will get overwritten.

I'm proposing a Hold() function for RequestCtx that signals serveConn to acquire a new instance instead of reusing the current ctx.  If Hold() is called by the handler, then it is also responsible for calling a Release() function to return the ctx instance to the pool.  I'm not sure if this is the most elegant or ideal way of handling this, but looking at the code, it seemed straight forward to add this logic.

**Comment by erikdubbelboer** [comment]
For this use case you can make a [copy of the Request](https://godoc.org/github.com/valyala/fasthttp#Request.CopyTo) and [Response](https://godoc.org/github.com/valyala/fasthttp#Response.CopyTo).

Implementing a `Hold` function is not easy seeing as the RequestCtx contains things like the connection and other state variables that are needed for the next request. Allowing someone to hold on to the RequestCtx would also "allow" them to call methods on it which affect the connection and would be unsafe.
