### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by petplay** [valyala/fasthttp#1465]
# github.com/valyala/fasthttp
../go/pkg/mod/github.com/valyala/fasthttp@v1.43.0/fs.go:1379:15: undefined: io.ReadAll
note: module requires Go 1.16

I am not understanding this issues, please? Anyone out there?

**Comment by li-jin-gou** [comment]
if you need to use an older version of go you'll need to use an older version of Fasthttp and refer to https://go.dev/doc/go1.16#ioutil

**Comment by erikdubbelboer** [comment]
You need at least go 1.16.x.
