### ISSUE TITLE
sending a multipart form data response

### ISSUE THREAD

**Issue by bumberboy** [valyala/fasthttp#1468]
May I know how do I send a multipart form data response that uses `multipart.Writer`?

I'm trying to send large files as a response.

**Comment by li-jin-gou** [comment]
same to https://github.com/valyala/fasthttp/issues/494

**Comment by bumberboy** [comment]
Is it really the same?I’m looking to send it in a response.Fasthttp is used as a server in this case.On 4 Jan 2023, at 6:26 PM, kinggo ***@***.***> wrote:﻿
same to #494

**Comment by li-jin-gou** [comment]
I thought it meant client, but you can set Body and content-type using response, by modifying the example, except that you need to set the response instead of the request.
Also you need to look at this  https://github.com/valyala/fasthttp/issues/1419

**Comment by bumberboy** [comment]
Ah ok. Thanks for your help!
