### ISSUE TITLE
Disable Caching for FS Handler

### ISSUE THREAD

**Issue by efectn** [valyala/fasthttp#1472]
Fasthttp FS isn't supporting disabling caching currently. Are there any way to disable it or should it be forcibly opened?

Ref: https://github.com/gofiber/fiber/issues/2201

**Comment by erikdubbelboer** [comment]
There is currently no way. I would be ok with a pull request that adds a boolean field for this. I'm afraid I don't have time to write this myself.

**Comment by sod-lol** [comment]
Can I work on this?

**Comment by erikdubbelboer** [comment]
> Can I work on this?

Yes of course!

**Comment by ReneWerner87** [comment]
@sod-lol any progress ?
