### ISSUE TITLE
How to set the request Context

### ISSUE THREAD

**Issue by xufei56789** [valyala/fasthttp#1473]
There is no http.NewRequestWithContext method similar to the http package ？

**Comment by li-jin-gou** [comment]
same to https://github.com/valyala/fasthttp/issues/1459

**Comment by xufei56789** [comment]
> 同#1459
大佬有qq或者微信指点一下吗？

**Comment by erikdubbelboer** [comment]
I assume you want to use the context to cancel the request. I'm afraid fasthttp can't support contexts for that with how the networking is done. Supporting this would require extra goroutines and channels which would slow things down. You should probably just use net/http.
