### ISSUE TITLE
Alternative for http.ServeContent?

### ISSUE THREAD

**Issue by ivanjaros** [valyala/fasthttp#1475]
Is there alternative to the http.ServeContent? All I see is fasthttp.ServeFile which takes path argument and fasthttp.ServeFileBytes that takes in entire file content in byte slice form. But no method that takes reader, not to mention lack of handling of range requests, mime detection, etag.. like http.ServeContent does.

**Comment by ivanjaros** [comment]
Looks like io.Reader can be served via ctx.Response.SetBodyStreamWriter() where range request, content type, mime detection... must be handled manually...right?

**Comment by erikdubbelboer** [comment]
I'm afraid that there is no alternative. A pull request to add one is welcome.

**Comment by ivanjaros** [comment]
> I'm afraid that there is no alternative. A pull request to add one is welcome.

ok, but is my line of thought correct, the SetBodyStreamWriter is the way to serve data from io.Reader?

**Comment by erikdubbelboer** [comment]
Yes if you don't want to do anything like Range requests that would be the best option.

**Comment by ivanjaros** [comment]
> Yes if you don't want to do anything like Range requests that would be the best option.

ok, thanks. why not range requests though?

**Comment by erikdubbelboer** [comment]
Unless your io.Reader is already the right range it won't do that for you.
