### ISSUE TITLE
Response header [Date] use a UTC time, should it use local? 

### ISSUE THREAD

**Issue by jindongyi011039** [valyala/fasthttp#149]
hello, 
fasthttp/bytesconv.go AppendHTTPDate(line:111)  used to response Date
`dst = date.In(time.UTC).AppendFormat(dst, time.RFC1123)`
is it better to use Local time
`dst = date.In(time.Local).AppendFormat(dst, time.RFC1123)`
[pic1.png] is fasthttp returned Datetime
[pic2.png] is browser's Datetime

![pic1](https://cloud.githubusercontent.com/assets/18360033/17199978/f555e552-54b3-11e6-9f40-dd1779d92d81.png)
![pic2](https://cloud.githubusercontent.com/assets/18360033/17199980/f65207c4-54b3-11e6-8b57-ef16fa96c263.png)

**Comment by medzin** [comment]
@jindongyi011039 According to HTTP/1.1 specification dates **MUST** be represented in GMT (for the purposes of HTTP, GMT is exactly equal to UTC), here's link to the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1)
