### ISSUE TITLE
Flaky test TestShutdownWithContext

### ISSUE THREAD

**Issue by alexandear** [valyala/fasthttp#1490]
The [TestShutdownWithContext](https://github.com/valyala/fasthttp/blob/master/server_test.go#L3634) sometimes fails without any reason:

[test (1.18.x, macos-latest)](https://github.com/valyala/fasthttp/actions/runs/4142944534/jobs/7164218311#logs):
```
--- FAIL: TestShutdownWithContext (2.01s)
    server_test.go:3681: unexpected open connection num: 2. Expecting 1
FAIL
FAIL	github.com/valyala/fasthttp	4.914s
```

**Comment by li-jin-gou** [comment]
I am investigating the cause.

**Comment by alexandear** [comment]
No longer reproduced.
