### ISSUE TITLE
A problem caused by fasthttpadaptor when coding with gin

### ISSUE THREAD

**Issue by duduchristian** [valyala/fasthttp#1501]
Senario:
```go
m := map[string]struct{}{}
var lock sync.Mutex
engine := gin.Default()
engine.GET("/test/:param", func(c *gin.Context){
    p := c.Param("param")
    lock.Lock()
    m[p] = struct{}{}
    lock.Unlock()
})
if err := fasthttp.ListenAndServe(":8080", fasthttpadaptor.NewFastHTTPHandler(gin.Handler())); err != nil {
    panic(err)
}
```
Call /test/param1 and /test/abc respectively for several times, you can see there are entries in m like abcam1. 
I think the problem is caused by the b2s function in request.go which makes the params obtained by gin in different calls pointing to the same byte slice:  https://github.com/valyala/fasthttp/blob/2ab79063af85601f532e85c3071c7f993b92fba5/fasthttpadaptor/request.go#L69-L72

**Comment by li-jin-gou** [comment]
refer to 
![image](https://user-images.githubusercontent.com/97824201/220513168-72bc8be3-57a5-469f-befe-9fcf928b026b.png)

in https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp
