### ISSUE TITLE
ctx.Request.SetHost() is not work.

### ISSUE THREAD

**Issue by venbill** [valyala/fasthttp#1507]
file:reverse-proxy.go
func (p *ReverseProxy) ServeHTTP(ctx *fasthttp.RequestCtx) {}
 req.SetHost(c.Addr) should be changed to   req.SetHost(string(req.Host()))

**Comment by erikdubbelboer** [comment]
There is no `reverse-proxy.go` in this repo? What do you mean?

**Comment by venbill** [comment]
sorry, it's another repository.
