### ISSUE TITLE
Add support for zstd (Zstandard) encoding

### ISSUE THREAD

**Issue by gaby** [valyala/fasthttp#1509]
Hello, currently fasthttp supports gzip and brotli as encoding when serving compressed content. It also supports them for `fasthttp.fs`. It would be very beneficial to add support for `zstd` whicb provides faster decompression rates. 

The library used by fashttp already supports zstd. Information here: https://github.com/klauspost/compress/tree/master/zstd#zstd

Tools like curl already support auto-decompression of zstd content since 2020: https://daniel.haxx.se/blog/2020/08/19/curl-7-72-0-more-compression/

**Comment by v4rn** [comment]
@erikdubbelboer new here. can i pick this?

**Comment by erikdubbelboer** [comment]
@v4rn yes please!

**Comment by gaby** [comment]
@v4rn You had any luck with this?

**Comment by v4rn** [comment]
@gaby sorry, I had some competing priorities last couple of weeks, just started looking at this. Prioritizing it this week.

**Comment by gaby** [comment]
@v4rn Any luck? thanks!

**Comment by gaby** [comment]
@v4rn Any update on this?

**Comment by Max-Cheng** [comment]
@gaby Since I'm curious about the internal implementation of fiber, I'm going to start fasthttp from this issue, wish me luck!

**Comment by gaby** [comment]
@Max-Cheng Awesome, yeah maine reason i opened this ticket is to eventually add support in Fiber.

**Comment by Max-Cheng** [comment]
@gaby zstd will be soon. I need more time to test corner cases
https://github.com/valyala/fasthttp/pull/1700

**Comment by gaby** [comment]
@Max-Cheng Awesome! Looking forward
