### ISSUE TITLE
Semicolon separate in URI args

### ISSUE THREAD

**Issue by oschwald** [valyala/fasthttp#151]
Would you be open to supporting semicolon separators in the URI query string? `net/http` does, and the [W3C recommends supporting them](https://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2). If you are open to this, I would be happy to make a PR.

**Comment by autarch** [comment]
Ping. This is blocking porting some code @oschwald and I have at work to use fasthttp.

**Comment by erikdubbelboer** [comment]
If you're still interested we are open to a PR now. Otherwise I'm closing this issue for now.
