### ISSUE TITLE
About proxy protocol v2 support when webapi behind haproxy using ssl passthrough

### ISSUE THREAD

**Issue by auxo86** [valyala/fasthttp#1519]
Hi~ I'm a beginner of fasthttp. I have written some web APIs using Fiber and placed them behind HAProxy. Because HAProxy has SSL passthrough enabled, my web APIs may need to support Proxy Protocol v2 to obtain the IP address of the HTTP request smoothly. Can I use fasthttp to set up support for this protocol?

I write a prototype here:
```
package main

import (
	"crypto/tls"
	"github.com/gofiber/fiber/v2"
	"github.com/pires/go-proxyproto"
	"net"
	"time"
)

func main() {
	app := fiber.New()
	ln, _ := net.Listen("tcp", ":8081")

	proxyListener := &proxyproto.Listener{
		Listener:          ln,
		ReadHeaderTimeout: 10 * time.Second,
	}
	defer proxyListener.Close()

	cer, _ := tls.LoadX509KeyPair("./SSL/ForTest.crt", "./SSL/ForTest.key")

	ln = tls.NewListener(proxyListener, &tls.Config{Certificates: []tls.Certificate{cer}})

	app.Get("/ok", func(c *fiber.Ctx) error {
		return c.SendString("Your IP address is: " + c.IP() + "\n")
	})

	app.Listener(ln)
}
```
It works. However, It uses net.Listen() to create custom Listener.
I have do some loading test for it, and the best result is about 22000 rps.
I don't know if the efficiency bottleneck of this simple program that displays IP address is due to my use of the Go net package.
Would it be possible to rewrite this piece of code using fasthttp?
Many thanks.

**Comment by erikdubbelboer** [comment]
Calling `net.Listen` is no problem, otherwise fasthttp will just do that for you. Your bottleneck here is probably that TLS in Go is slow. I would have haproxy do TLS termination if possible.
