### ISSUE TITLE
How to get the file size when uploading it?

### ISSUE THREAD

**Issue by SlavaBobik** [valyala/fasthttp#152]
Hi. Could you explain me, please, how to correctly get the file size from `multipart/form-data` request? 
I use `FormFile("some-key")` method for getting the file. Thanks.

**Comment by erikdubbelboer** [comment]
`RequestCtx.FormFile("filename")` returns a [`mime/multipart.FileHeader`](https://godoc.org/mime/multipart#FileHeader) which contains a `Size` field that you can use.
