### ISSUE TITLE
Don't panic for non-critical errors

### ISSUE THREAD

**Issue by mpldr** [valyala/fasthttp#1522]
Grepping the codebase, I noticed a number of panics in non-critical codepaths. This might be annoying as in #1504, or it might open users up to DoS attacks if someone finds a way to trigger something like [server.go:1947](https://github.com/valyala/fasthttp/blob/53e376f82282fd6437b5e0189e80dff0add50fe3/server.go#L1947) reliably.

This is *not* a vulnerability. It's just a design flaw, that might lead to a vulnerability when combined with bugs or rare behaviour.

Personally, I think it would be a better™ approach to log them and move on. "Connection is nil? The connection is invalid and gets dropped", "IP count is negative? Looks like a race condition. Nothing endangering data integrity".

```console
$ rg 'panic\("BUG:'
bytesconv.go
82:		panic("BUG: dst must not be nil")
129:		panic("BUG: int must be positive")
284:		panic("BUG: int must be positive")

client.go
1314:		panic("BUG: req cannot be nil")
1317:		panic("BUG: resp cannot be nil")
1997:		panic("BUG: DialFunc returned (nil, nil)")

compress.go
69:		panic("BUG: zlib.Reader doesn't implement zlib.Resetter???")

fs.go
605:		panic("BUG: negative fsFile.readersCount!")
1398:			panic("BUG: path must start with slash")

http.go
966:		panic("BUG: form boundary cannot be empty")
2200:		panic("BUG: expected zero-length buffer")

lbclient.go
87:		panic("BUG: LBClient.Clients cannot be empty")

peripconn.go
30:		panic("BUG: perIPConnCounter.Register() wasn't called")

server.go
1933:				panic("BUG: net.Listener returned non-nil conn and non-nil error")
1947:			panic("BUG: net.Listener returned (nil, nil)")
2581:		panic("BUG: cannot write timed out response")
2615:		panic("BUG: Reader must return at least one byte")
2790:	panic("BUG: unexpected Read call")
2794:	panic("BUG: unexpected Write call")
2798:	panic("BUG: unexpected Close call")
2803:		panic("BUG: cannot release timed out RequestCtx")

stackless/func.go
23:		panic("BUG: f cannot be nil")

timer.go
13:		panic("BUG: active timer trapped into initTimer()")

workerpool.go
50:		panic("BUG: workerPool already started")
75:		panic("BUG: workerPool wasn't started")
```

**Comment by erikdubbelboer** [comment]
I agree that some (maybe most) of these could be return values or should just be logged. Can you maybe have a look at which ones can be changed? There is also some like the ones in workerpool which are just programming errors if they go wrong and are only used internally.

**Comment by mpldr** [comment]
Yes, I think the safeguards make sense (though normal tests might be
better instead of shipping) I'll take a look this week :)

If I happen to replace them with tests, would that be alright with you?
-- 
Moritz Poldrack
https://moritz.sh

**Comment by erikdubbelboer** [comment]
Yes of course!
