### ISSUE TITLE
error when reading response headers: invalid header name. Buffer size=

### ISSUE THREAD

**Issue by whyynoot** [valyala/fasthttp#1531]
Hello, i have 2-3 http clients and after a day of running some of them goes to error 
```error when reading response headers: invalid header name. Buffer size=368, contents: \"169\\r\\n{\\\"timestamp\\\":1679836803,\\\"asks\\\":[{\\\"price\\\":\\\"78.9\\\",\\\"volume\\\":\\\"1519977.22\\\",\\\"amount\\\":\\\"119926202.66\\\",\\\"factor\\\":\\\"0.024\\\",\\\"type\\\":\\\"limit\\\"},{\\\"price\\\":\\\"78.92\\\",\\\"volume\\\":\\\"809078.38\\\",\\\"amount\\\":\\\"63856349.33\\\",\\\"factor\\\":\\\"0.024\\\",\\\"type\\\":\\\"factor\\\"},{\\\"price\\\":\\\"78.95\\\",\\\"volume\\\":\\\"680040.51\\\",\\\"amount\\\":\\\"53689198.26\\\",\\\"factor\\\":\\\"0.024\\\",\\\"type\\\":\\\"limit\\\"},{\\\"price\\\":\\\"79.0\\\",\\\"volume\\\":\\\"1063041.56\\\",\\\"amount\\r\\n\"```

What can this be caused? Restarting my app and everything still working fine.

**Comment by erikdubbelboer** [comment]
This usually happens when you reuse memory that you shouldn't. Is it possible you keep references to byte slices after the handler returns for example?
