### ISSUE TITLE
How to get domain name from request

### ISSUE THREAD

**Issue by suntong** [valyala/fasthttp#1541]
With `"github.com/fasthttp/router"`, and:

```go
	rtr := router.New()

	rtr.GET("/info", func(ctx *fasthttp.RequestCtx) {
		// get & return requesting server domain name here
		ctx.SetStatusCode(fasthttp.StatusOK)
	})
```

If I visit it as https://a.b.co/info, how to get such user specified requesting server domain name (`a.b.co`) from the request please? thx.

**Comment by li-jin-gou** [comment]
ctx.Host()

**Comment by suntong** [comment]
Thanks!
