### ISSUE TITLE
Timeout correlation

### ISSUE THREAD

**Issue by Tristin-C** [valyala/fasthttp#1554]
Hello, sorry to bring up such a naive question. Recently, I encountered the problem of production environment gouroutine explosion. After reviewing the previous issue, I would like to ask if it is relevant

#1435 

In this issue, it is mentioned that the goroutine is put back into the pool after the timeout. If it is not put back, is it possible to generate a large number of new workers when the Goroutine is not collected? Causing the problems I've been having?

Thank you very much for taking the time to answer my naive questions

**Comment by erikdubbelboer** [comment]
No that is not relevant. That pull request that wasn't merged would have added a goroutine. But it wasn't merged.

Are you using pipelining?

**Comment by Tristin-C** [comment]
No, I use 2.42.1 version of fiber. This problem occurs from time to time. I have no clue

**Comment by erikdubbelboer** [comment]
I would update to v2.45.0 as it contains a bunch of fixes.

Then I would use https://docs.gofiber.io/api/middleware/pprof/ to get a profile when this happens and see where are the goroutines are started from.

I'm afraid there isn't much I can do without information like that.

**Comment by Tristin-C** [comment]
@erikdubbelboer  Sorry for the lack of stickers
I have upgraded to 2.45.0 and here is what happens after the upgrade

<img width="1111" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/69131565-9015-4641-921e-2d9bf4a1b36d">
This is the goroutine when it is very tall

next

<img width="1100" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/7b0f23a2-6c5e-4398-ae72-aa64e45753fe">
This is the goroutine in its normal state


The two graphs above are goroutine observations of pprof


next

<img width="1101" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/2a6f126b-d83d-439e-a52d-9978d287e584">

This picture shows block_duration when the goroutine is high

next

<img width="566" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/c10822ea-4bea-4268-9876-5064d7625b10">

This picture shows the block_duration when the goroutine is normal

The two graphs above look at the block_duration of pprof

**Comment by erikdubbelboer** [comment]
Looks to me like you have a bunch of keep-alive connections open and waiting. If this is the case you can time them out after a while using [`Server.IdleTimeout`](https://pkg.go.dev/github.com/valyala/fasthttp?utm_source=godoc#Server.IdleTimeout).

**Comment by Tristin-C** [comment]
<img width="1144" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/9b8e6f94-6723-4ea2-b2a8-ce9899fe8c21">

@erikdubbelboer 
This is the goroutine curve.
If Server.IdleTimeout is not configured, the system automatically times out the timeout. In most cases, they spike for a short period of time and then remain too high to provide services properly.

**Comment by erikdubbelboer** [comment]
How many requests per second is the server receiving?
What does your handler do, could it be that it sometimes takes very long to respond?
Have you tried measuring your handler response times?

**Comment by Tristin-C** [comment]
@erikdubbelboer   Our service needs to deliver qps of 20,000 per second, and requires milliseconds of response. These are tested, and timeout controls are built into the logic

**Comment by erikdubbelboer** [comment]
How are you doing timeout controls? Could it be that you are using [`fasthttp.TimeoutHandler`](https://pkg.go.dev/github.com/valyala/fasthttp#TimeoutHandler)?

**Comment by Tristin-C** [comment]
@erikdubbelboer  WithTimeout is used to implement timeout control, and the use of each tripartite component is controlled

**Comment by erikdubbelboer** [comment]
One reason I can see why a lot of connections would be opened is if your handler takes too long to respond and the client needs to open a new connection instead of being able to re-use an existing one. How is the CPU usage during these spikes?
Another option is that the network is too slow and responses don't arrive at the client fast enough causing the same opening of new connections instead of re-using keep-alive connections.

**Comment by Tristin-C** [comment]
<img width="710" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/42d47cc0-7c7d-4b6e-a194-615cd1e5c4e6">
<img width="755" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/037372f3-ac99-4a40-888e-116603987fe1">
@erikdubbelboer 
The cpu peaks are shown here, with no fluctuation, as usual.
I suspect the same now, so I've added timeout controls for all three-way calls, and keep them to 20ms. I have increased the connection state monitoring metrics in hopes of confirming this conjecture.
Do you have any better suggestions?

**Comment by erikdubbelboer** [comment]
I guess slow responses could also happen if the handler is waiting for external resources, that wouldn't show as high CPU usage.

Is it an option to ask the clients if maybe something is happening on their end?

**Comment by Tristin-C** [comment]
From the client's point of view, the response time becomes longer or even exceeds the agreed response time. nginx-lb is unable to load the instance, and the instance is unable to respond properly due to the high number of Goroutines

**Comment by Tristin-C** [comment]
@erikdubbelboer  

From the client's point of view, the response time becomes longer or even exceeds the agreed response time. nginx-lb is unable to load the instance, and the instance is unable to respond properly due to the high number of Goroutines.

In the nginx-lb section, nginx_connections_active, nginx_connections_waiting, and nginx_http_requests_total are all in very low state.

The value of nginx_http_requests_total is low, but the qps of the service instance is normal.

Observing the indicators of each link of the program, it seems that nothing abnormal is found. They are executed normally, and there is no fault in the quantity.

I think I need to add more detailed monitoring indicators, such as qps and latency of each link.

**Comment by erikdubbelboer** [comment]
I looked though this issue again and I'm a bit confused with the graphs that show the number of goroutines. It shows barely any goroutines, which wouldn't make sense for 20k qps. Is it handling that many requests the whole time or only when the graph is up? If it's only handling the requests when the graph is up the CPU graph doesn't make sense?

Have you configured your nginx upstream properly to use keep-alive connections? Something like this:
```
    location = / {
        proxy_pass                      http://someupstream/;
        proxy_http_version         1.1;
        proxy_set_header           X-IP $remote_addr;
        proxy_next_upstream     error timeout invalid_header http_500;
        proxy_connect_timeout  6;
        proxy_set_header           Connection "";
    }

...

upstream someupstream {
    ip_hash;

    server upstream01:10809 weight=1 max_fails=100 fail_timeout=2s;
    server upstream02:10809 weight=1 max_fails=100 fail_timeout=2s;
    server upstream03:10809 weight=1 max_fails=100 fail_timeout=2s;

    keepalive 400;
    keepalive_requests 100000;
    keepalive_timeout 1h;
}
```

**Comment by Tristin-C** [comment]
<img width="588" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/3539e2ee-14a5-493f-a185-4aa2b8c8a1c6">

<img width="346" alt="image" src="https://github.com/valyala/fasthttp/assets/82650741/3ea87c1d-8166-4edc-b2e4-f36b9d9b6259">

@erikdubbelboer 

Sorry for not making it clear what the goroutine chart is.

Attached is a goroutine chart with numbers. The number of Goroutines is always within the security alarm range when the logic is processed normally.

The service is processing so many requests all the time that the processing logic may be different in that there are times when there is no core logic.

The keep-alive configuration for nginx is as follows:

```
    keepalive_requests 100000;
    keepalive_timeout 1h;

    location = / {
        proxy_pass                      http://someupstream/;
        proxy_http_version         1.1;
        proxy_set_header           X-IP $remote_addr;
        proxy_next_upstream     error timeout invalid_header http_500;
        proxy_connect_timeout  6;
        proxy_set_header           Connection "";
    }

...

upstream someupstream {
    ip_hash;

    server upstream01:10809 weight=1 max_fails=100 fail_timeout=2s;
    server upstream02:10809 weight=1 max_fails=100 fail_timeout=2s;
    server upstream03:10809 weight=1 max_fails=100 fail_timeout=2s;

    keepalive 400;
}
```

**Comment by Tristin-C** [comment]
@li-jin-gou 
Thank you for your advice.

The number of nginx-lb I use here is not very different from the number of instances of the upstream service.

Looking at the index of nginx connection, the number of nginx_connections_active and nginx_connections_waiting is equal.

Can I ask what your question looks like?

**Comment by erikdubbelboer** [comment]
What is the CPU usage percentage normally? Is it pretty close to 100% maybe? If so a temporary spike for some reason could cause it to run away like that.

**Comment by Tristin-C** [comment]
@erikdubbelboer 
The cpu is currently allocated 8 cpus in a single instance, and the maximum usage is 250%, which has not been reached.

The temporary spike you mentioned reminds me that there may be spikes in the monitoring of request volume. At this time the cpu will also spike, usage is far from the maximum.

Could that be the reason?

**Comment by Tristin-C** [comment]
@erikdubbelboer 
There is also a case where nginx-lb stops looking at goroutine instances when there are too many goroutine instances. In this case, Goroutine does not seem to be collected and human intervention is required to restart the instance.

**Comment by Tristin-C** [comment]
@erikdubbelboer 
In other cases, when there are too many goroutine, nginx-lb will not add more goroutine to the instance. In this case, it seems that Goroutine will not be reclaimed, and manual intervention is required to restart the instance.

**Comment by erikdubbelboer** [comment]
Goroutines aren't being reclaimed because they are for open keep-alive connections.
A spike in requests and CPU usage could certainly cause this to go up.
But maybe in that case having a lot of goroutines isn't really an issue? If they aren't doing anything.

**Comment by Tristin-C** [comment]
@erikdubbelboer 
It may not be relevant for a short time, but the initial performance is that the interface response time is too long, which exceeds the expected time. After checking, we can see the phenomenon that there are a lot of goroutine, and almost every time it is accompanied by the state.
