### ISSUE TITLE
Wrong redirect with relative path for https

### ISSUE THREAD

**Issue by linuxerwang** [valyala/fasthttp#157]
On iris 3/4, the iris.Redirect("/home") redirects to http:// instead of https:// when the webserver is using https. This behavior is different from net/http. I think it's better to be the same as net/http, and it's very convenient for developers. That is, when scheme is not specified in the path, take the scheme of the current webserver automatically.

The iris author analyzed it and figured out it's a fasthttp bug. Please see https://github.com/kataras/iris/issues/355 for reference.

Thanks.

**Comment by EtienneBruines** [comment]
When we're at this, we might also want to use the `X-Forwarded-Proto` header, which some reverse proxies use to indicate the original request was a HTTPS request. If this was set to `https`, then using that as a default makes sense.

**Comment by EtienneBruines** [comment]
Okay, adding a few lines of code, I am able to redirect to `https` correctly when behind a reverse-proxy. I will now try to reproduce your error, @linuxerwang

**Comment by kataras** [comment]
@EtienneBruines The `X-Forwarded-Proto` is 'replaced' by `Forwarded` as much as I know by the specification (https://tools.ietf.org/html/draft-ietf-appsawg-http-forwarded-10#section-4).

I'm not sure if the correct solution for the issue @linuxerwang is describing is the `X-Forwarded-Proto/Forwarded`.

Explanation: 

Different status codes can be resolve to different solution, for example there is a specific status code which makes your redirect permant by browser, other status code can redirect only to GET and so on.

The context's redirect outline is: 

```go
Redirect(urlToRedirect string, statusHeader ...int)
```

I think you have to make a research on different redirection status codes and change the statusHeader(http redirection status code) to that ( I don't have much time to test my theoritical answers right now)


Finally, check for the @EtienneBruines 's solution and tell us if that worked for you @linuxerwang.

Thanks,
kataras.

**Comment by kataras** [comment]
Ok I just fixed it manually inside Iris, we can do the same for the fasthttp I assume, code:

```go

	if ctx.IsTLS() {
		u := fasthttp.AcquireURI()
		ctx.URI().CopyTo(u)
		u.SetScheme("https")
		u.Update(urlToRedirect)

		println(string(u.FullURI()))
		ctx.SetHeader("Location", string(u.FullURI()))
		fasthttp.ReleaseURI(u)
		ctx.SetStatusCode(httpStatus)
	} else {
		ctx.RequestCtx.Redirect(urlToRedirect, httpStatus)
	}

       // do cleanup 
```

**Comment by EtienneBruines** [comment]
@kataras Thank you for your research / explanation. The major 'issue' was that the `isTLS` variable wasn't always assigned to. (Moving line 1471 to line 1486.) This alone fixed the bug @linuxerwang was describing.

**Comment by kataras** [comment]
LoL, really?  this was so unpredictable I didn't expected it from @valyala  <3

**Comment by linuxerwang** [comment]
Hi, guys

I tested with kataras's latest commit and verified that my issue has been fixed in iris. Please feel free to close this issue when the fasthttp end is fixed, too.

Thanks!

**Comment by erikdubbelboer** [comment]
I guess this issue will be fixed once https://github.com/valyala/fasthttp/pull/206 is merged.
