### ISSUE TITLE
Do I need NGINX?

### ISSUE THREAD

**Issue by denis-n** [valyala/fasthttp#158]
Hi,

I wrote a small application using fasthttp which is doing redirects and want to use DigitalOcean for hosting. Watched a video from them:

https://www.youtube.com/watch?v=Jsmeh7q9Qv4

They are using NGINX too (as a reverse proxy). 
I'm new to golang and deployment, my question is: do I need NGINX or the app will work without it?

**Comment by denis-n** [comment]
Also, how can I configure my app so it will start when Ubuntu reboots?

**Comment by jadbox** [comment]
Personally, I don't use nginx as a RP for my fasthttp services, as we don't have a use-case for it. There are reasons to still use a RP though depending on your needs: for example, a RP will allow you to upgrade your go service without connections dropping as nginx will buffer them until the new go version starts.

**Comment by tracer0tong** [comment]
If you have no TLS termination on load balancer, using nginx could be a good idea for TLS handling. Also I've used nginx exactly as @jadbox mention before for smooth upgrade process.

**Comment by tracer0tong** [comment]
For autostart I can recommend one of the standard ways: supervisord, monit, systemd.
