### ISSUE TITLE
Chromes Cookie.Priority not supported.

### ISSUE THREAD

**Issue by MartinHotmann** [valyala/fasthttp#1580]
Linking the issue I created at fiber: https://github.com/gofiber/fiber/issues/2515

Quick summary:

- Chrome supports the cookie setting `Priority`
- it is used to prioritise cookies so when the browser needs to delete - deletes the right ones
- currently only available in Chrome (but since some years)
- Options for `Priority` are: `Low`, `Medium` & `High`

Usefull links:

- https://developer.chrome.com/docs/devtools/application/cookies/
- https://bugs.chromium.org/p/chromium/issues/detail?id=232693

Thanks in advance!

**Comment by erikdubbelboer** [comment]
According to your first link the attribute is deprecated, so I'm not sure how useful it is to implement this. But if you really want it a pull request is welcome.

**Comment by ReneWerner87** [comment]
then perhaps we should not implement this
