### ISSUE TITLE
DNS Resolve Timeouts are not working

### ISSUE THREAD

**Issue by un000** [valyala/fasthttp#1581]
A problem ocurres when DNS doesn't respond properly:
```
lookup somedomain.com.com on 16.25.25.10:53: server misbehaving
```

So on the metrics with timeout of 200ms it takes 7-8 seconds
<img width="264" alt="image" src="https://github.com/valyala/fasthttp/assets/19488486/a4b80967-b776-4c85-9fdd-8f2f7997c667">

https://github.com/valyala/fasthttp/blob/ffdf59d04ca2f02556308d60d37b8e77ea04484c/tcpdialer.go?plain=1#L429-L430

resolveTCPAddrs doesn't use context from the above
https://github.com/valyala/fasthttp/blob/ffdf59d04ca2f02556308d60d37b8e77ea04484c/tcpdialer.go?plain=1#L283

I propose to pass it. What you think @erikdubbelboer ?

**Comment by erikdubbelboer** [comment]
Yes that sounds like a good idea. Can you make a pull request?

**Comment by un000** [comment]
> Yes that sounds like a good idea. Can you make a pull request?
Done
