### ISSUE TITLE
Should add 'Vary: Accept-Encoding' header when compress is used

### ISSUE THREAD

**Issue by AutumnSun1996** [valyala/fasthttp#1583]
When responses are compressed, and may be compressed by different methods, responses should has 'Vary: Accept-Encoding' header so clients can get decodable content.
I think it should be such a build-in feature in the function `CompressHandlerBrotliLevel`, maybe with a config to turn it off.

**Comment by erikdubbelboer** [comment]
I agree, I'm not sure why this isn't being done yet. Can you make a pull request?

**Comment by AutumnSun1996** [comment]
I'm glad to do that, will create one soon.
