### ISSUE TITLE
conflict code

### ISSUE THREAD

**Issue by xj524598** [valyala/fasthttp#1590]
fasthttp version: 1.45.0

all is in picture
<img width="1137" alt="企业微信截图_ddc1b9f6-509a-4945-86ed-2fff34bd4b2c" src="https://github.com/valyala/fasthttp/assets/26913796/0765e2be-7a88-4141-b43b-ae02c74939c5">

**Comment by erikdubbelboer** [comment]
What this code does is it adds a `Connection: close` header to the request when the max connection duration has been reached. After the request has been send it removes this header again to keep the request object the same as how the user's code made it.

Keep in mind that the `req.Write` line is the one that actually writes the header.
