### ISSUE TITLE
Keep-Alive in HTTP 1.0

### ISSUE THREAD

**Issue by dimchansky** [valyala/fasthttp#16]
I've created simple app to test it with Apache Benchmark (which uses HTTP/1.0):
```go
package main

import (
	"github.com/valyala/fasthttp"
)

const helloWorldString = "Hello, World!"

var (
	helloWorldBytes    = []byte(helloWorldString)
	helloWorldBytesLen = len(helloWorldBytes)
)

func plaintextHandler(ctx *fasthttp.RequestCtx) {
	ctx.SetStatusCode(fasthttp.StatusOK)
	ctx.Response.Header.SetContentType("text/plain")
	ctx.Response.Header.SetContentLength(helloWorldBytesLen)
	ctx.Response.Header.Set("Connection", "keep-alive")
	ctx.Write(helloWorldBytes)
}

func main() {
	fasthttp.ListenAndServe(":8080", plaintextHandler)
}
```

Unfortunately server closes connection, when it sees `HTTP/1.0` in `GET` request:
```
GET / HTTP/1.0
Connection: Keep-Alive
Host: 127.0.0.1:8080
User-Agent: ApacheBench/2.3
Accept: */*
```

If I change first line in request to `GET / HTTP/1.1` then everything works, server returns response:
```
HTTP/1.1 200 OK
Server: fasthttp
Date: Mon, 07 Dec 2015 11:43:30 GMT
Content-Type: text/plain
Content-Length: 13
Connection: keep-alive

Hello, World!
```
and waits for another request on the same connection.
Could you add support for Keep-Alive in HTTP 1.0?
HTTP/1.0, in its documented form, made no provision for persistent connections. But some HTTP/1.0 implementations, however, use a Keep-Alive header to request that a connection persist.

**Comment by valyala** [comment]
The server deliberately closes connections on non-HTTP/1.1 requests. I have no desire complicating the code by adding support for `Connection: keep-alive` [hack in HTTP/1.0](https://en.wikipedia.org/wiki/HTTP_persistent_connection#HTTP_1.0) requests.

Apache Benchmark (ab) is old and broken. Use something newer like [wrk](https://github.com/wg/wrk) instead.

As for the code, it may be improved in the following way:

```go
package main

import (
    "github.com/valyala/fasthttp"
)

const helloWorldString = "Hello, World!"

var helloWorldBytes = []byte(helloWorldString)

func plaintextHandler(ctx *fasthttp.RequestCtx) {
    ctx.Success("text/plain", helloWorldBytes)
}

func main() {
    fasthttp.ListenAndServe(":8080", plaintextHandler)
}
```


[ctx.Success](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Success) automatically sets StatusOK status code, sets the given `Content-Type` header and automatically calculates and sets `Content-Length` so there is no need in `ctx.SetStatusCode(fasthttp.StatusOK)`, `ctx.Response.Header.SetContentType("text/plain")` and `ctx.Response.Header.SetContentLength(helloWorldBytesLen)`.

As for `ctx.Response.Header.Set("Connection", "keep-alive")`, this header has no sense for HTTP/1.1, since HTTP/1.1-compliant client and servers [must treat all the connections as keep-alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection#HTTP_1.1) unless explicit `Connection: close` header is present.

I'm closing the bug with "won't fix" status.

**Comment by dimchansky** [comment]
Why I asked is because in other libraries (Haskell Warp, Go net/http, C# HttpListener) it was easy to make such workaround for HTTP 1.0.
I understand your position perfectly and I can't insist on anything.
Maybe I'll do it on my own.

I did quick fix of your library. Maybe you'll be interested in benchmark results on my Windows machine.

2 programs were tested with the command:
```
ab.exe -k -n 1000000 -c 51 http://127.0.0.1:8080/
```

**Standard net/http version**:
```golang
package main

import (
	"net/http"
)

const helloWorldString = "Hello, World!"

var helloWorldBytes = []byte(helloWorldString)

func plaintextHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")
	w.Write(helloWorldBytes)
}

func main() {
	http.HandleFunc("/", plaintextHandler)
	http.ListenAndServe(":8080", nil)
}
```
Benchmark result:
```
Server Software:
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /
Document Length:        13 bytes

Concurrency Level:      51
Time taken for tests:   9.662 seconds
Complete requests:      1000000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    1000000
Total transferred:      139000000 bytes
HTML transferred:       13000000 bytes
Requests per second:    103493.25 [#/sec] (mean)
Time per request:       0.493 [ms] (mean)
Time per request:       0.010 [ms] (mean, across all concurrent requests)
Transfer rate:          14048.40 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     0    0   0.8      0      13
Waiting:        0    0   0.8      0      13
Total:          0    0   0.8      0      13

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      1
  75%      1
  80%      1
  90%      1
  95%      1
  98%      3
  99%      4
 100%     13 (longest request)
```

**fasthttp version**:
```golang
package main

import (
	"github.com/valyala/fasthttp"
)

const helloWorldString = "Hello, World!"

var helloWorldBytes = []byte(helloWorldString)

func plaintextHandler(ctx *fasthttp.RequestCtx) {
	ctx.Response.Header.Set("Connection", "keep-alive")
	ctx.Success("text/plain", helloWorldBytes)	
}

func main() {
	fasthttp.ListenAndServe(":8080", plaintextHandler)
}
```

Benchmark result:
```
Server Software:        fasthttp
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /
Document Length:        13 bytes

Concurrency Level:      51
Time taken for tests:   6.162 seconds
Complete requests:      1000000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    1000000
Total transferred:      157000000 bytes
HTML transferred:       13000000 bytes
Requests per second:    162274.44 [#/sec] (mean)
Time per request:       0.314 [ms] (mean)
Time per request:       0.006 [ms] (mean, across all concurrent requests)
Transfer rate:          24879.97 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     0    0   0.4      0       4
Waiting:        0    0   0.4      0       4
Total:          0    0   0.4      0       5

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      1
  75%      1
  80%      1
  90%      1
  95%      1
  98%      1
  99%      1
 100%      5 (longest request)
```

**Comment by valyala** [comment]
Added support for 'Connection: keep-alive' header for non-http/1.1 protocols.
@dimchansky, could you verify that it works as expected?

**Comment by dimchansky** [comment]
@valyala Everything works now with Apache Benchmark that uses HTTP 1.0 with `Connection: Keep-Alive` header. Good work, thanks!
