### ISSUE TITLE
http.Transport.Dial adapter (for SOCKS5 proxy support)

### ISSUE THREAD

**Issue by shicky** [valyala/fasthttp#161]
It is more common to find SOCKS5 proxies being used instead of HTTP proxies.

SOCKS5 proxies are currently supported by `golang.org/x/net/proxy`

It would be nice to have some kind of `http.Transport.Dial` adapter for `fasthttp.DialFunc`.

For example, take a look at Socks5 Dialer adapter I implemented.

``` go
func FasthttpSocksDialer(proxyAddr string) func(addr string) (net.Conn, error) {
     return func(addr string) (net.Conn, error) {
         dialer, err := proxy.SOCKS5("tcp", proxyAddr, nil, proxy.Direct)
         if err != nil {
             log.Fatalf("error connecting to socks5 proxy")
         }   
         return dialer.Dial("tcp", addr)
     }   
 }

c := &fasthttp.Client{
    Dial: FasthttpSocksDialer("localhost:9050"),
}
```

Is there a reason why `fasthttp.DialFunc` is not compatible with `http.Transport.Dial`?

**Comment by bernardolm** [comment]
+1

**Comment by themester** [comment]
Why `fasthttp.DialFunc` should be compatible with `http.Transport.Dial`?

**Comment by erikdubbelboer** [comment]
See https://github.com/valyala/fasthttp/pull/405
