### ISSUE TITLE
slow browser initial connection compared with net/http

### ISSUE THREAD

**Issue by agalbenus** [valyala/fasthttp#1610]
Hello, I m trying to build a web server using fiber and the initial connection between browser and server (the tcp handshake) seems slow compared with net/http and other frameworks: Here is some simple code that I m using to test and compare:
```package main

import (
	"fmt"
	"html"
	"log"
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/valyala/fasthttp"
)

func main() {

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
	})

	http.HandleFunc("/hi", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hi")
	})

	go func() {
		log.Fatal(http.ListenAndServe(":8080", nil))
	}()

	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello world")
	})

	go func() {
		app.Listen(":8081")
	}()

	fasthttp.ListenAndServe(":8082", func(ctx *fasthttp.RequestCtx) {
		fmt.Fprintf(ctx, "Hello, %q", ctx.Path())
	})

}

```
Below are the results (also verified with fasthttp):

fiber:
![fiber](https://github.com/valyala/fasthttp/assets/58302554/0cb4f3ef-1f6a-4cad-8f61-a1bdbc78fb28)

fasthttp:
![fasthttp](https://github.com/valyala/fasthttp/assets/58302554/9ebd6ad4-557b-4063-a83e-f0120145961a)

net/http
![net-html](https://github.com/valyala/fasthttp/assets/58302554/9494fd20-8032-4d0b-a0a7-5297b46b398f)

**Comment by erikdubbelboer** [comment]
I can't reproduce this.
Which version of Go are you using?
Which OS are you on?
How do you start/compile the programs?

If you are on Windows and you have a virus scanner it's probably causing this.

**Comment by erikdubbelboer** [comment]
Do you have any virus scanner? My guess is that your virus scanner recognizes net/http early and allows it quickly while fasthttp takes a bit longer. Try disabling your virus scanner.
fasthttp just uses the normal Go networking library, just like net/http does. So I'm afraid there is nothing we could do about this.
