### ISSUE TITLE
Use the client high frequency request interface： tls handshake timed out 

### ISSUE THREAD

**Issue by Zyn0423** [valyala/fasthttp#1622]
My locally configured client information demo ：
func NewFastHttp() *FastHttp {

	client := &fasthttp.Client{
		Name:                     "FunTester",
		NoDefaultUserAgentHeader: true,
		TLSConfig:                &tls.Config{InsecureSkipVerify: true},
		MaxConnsPerHost:          300,      
		MaxIdleConnDuration:      300 
		MaxConnDuration:          1000 
		ReadTimeout:              1000 
		WriteTimeout:             1000 *
		MaxConnWaitTimeout:       1000 * time.Millisecond,
	}
	return &FastHttp{
		Client: client,
	}
}
Has anyone experienced this problem and how do you solve it ？

**Comment by erikdubbelboer** [comment]
I think you need to fix your example, it's invalid code. I can't see how you set your timeouts now.

Could it be that it actually just is a timeout?

**Comment by Zyn0423** [comment]
The fault is resolved. The fault location problem is a server load balancing problem
