### ISSUE TITLE
Socks proxy doesn't seem to support auth?

### ISSUE THREAD

**Issue by bennyd87708** [valyala/fasthttp#1627]
Currently have a working example program with a call to `fasthttpproxy.FasthttpHTTPDialer` for http proxies with auth using the format `user:pass@address:port`. I tried to switch this to `fasthttpproxy.FasthttpSocksDialer`, as I would like to also support socks proxies, but it seems as though this other function may only take in proxies with the format `socks5://address:port`, and that there is no support for username and password authentication with socks proxies. Is this intentional or is there any chance/plans for this feature to be supported any time soon? Thanks for the help regardless

**Comment by erikdubbelboer** [comment]
`fasthttpproxy.FasthttpSocksDialer` uses [`proxy.FromURL`](https://pkg.go.dev/golang.org/x/net/proxy?utm_source=godoc#FromURL) which also supports `socks5://user:pass@address:port` so it should just work.

**Comment by bennyd87708** [comment]
That did it - Thanks!
