### ISSUE TITLE
why release v1.49.0 is marked as latest?

### ISSUE THREAD

**Issue by peczenyj** [valyala/fasthttp#1646]
I can see

https://github.com/valyala/fasthttp/releases/tag/v1.49.0

there is a tag "latest", but it is not true, since there is v1.50.0

perhaps this tag is manually set?

**Comment by erikdubbelboer** [comment]
I have no idea. I'll tag a new release on Monday and tag it as latest.

**Comment by peczenyj** [comment]
There is a checkbox when we release to set it as “latest”.
Why? 🤷‍♂️
