### ISSUE TITLE
Cannot follow redirect when using Do() but Get() doesn't expose `Request` object for fine-grain control

### ISSUE THREAD

**Issue by shicky** [valyala/fasthttp#165]
With current implementation, it is not possible to follow redirects and manipulate `Request` object at the same time.

Access to `Request` object is absolutely necessary for setting headers etc.
- Currently `Get(dst []byte, url string)` allows you to follow redirects but it doesn't expose `Request` object.
- `Do(req *Request, resp *Response)`, exposes `Request` object but doesn't support following redirects.
- `doRequestFollowRedirects(req *Request, dst []byte, url string, c clientDoer)` is not exposed.

Proposal:

Implement alternative `DoFollowRedirect` and `doRequestFollowRedirects` that exposes `Request` and `Response` objects.

``` go
// DoFollowRedirect makes http request based on Request
func (c *Client) DoFollowRedirect(req *Request, resp *Response) error {
        return doRequestFollowRedirects(req, resp, c)
}

// doRequestFollowRedirects follows redirects and return final Response
func doRequestFollowRedirects(req *Request, resp *Response, c clientDoer) error {
        // TODO
}
```

**Comment by valyala** [comment]
Generic `DoFollowRedirects` isn't that easy as it may seem.

The following questions immediately arise when implementing this function:

- Which request headers must be preserved and which must be cleared when following redirects.
- Should timeout be passed to `DoFollowRedirects`?

So I think it would be better if redirects' following is implemented in user code either on top of `Do` or `DoTimeout` depending on user needs.
