### ISSUE TITLE
write: broken pipe

### ISSUE THREAD

**Issue by HtopH** [valyala/fasthttp#1660]
Here are two http request methods I wrapped, one using fasthttp and the other using net/http:

        func NewHttpRequest(url, requestMethod string, requestData interface{}) (responseData []byte, err error) {
	        jsons, _ := json.Marshal(requestData)
	        req := fasthttp.AcquireRequest()
        
	        req.Header.SetContentType("application/json")
	        req.Header.SetMethod(requestMethod)
	        req.SetRequestURI(url)
	        req.SetBody(jsons)
        
	        resp := fasthttp.AcquireResponse()
	        err = fasthttp.Do(req, resp)
	        fasthttp.ReleaseRequest(req)
	        defer fasthttp.ReleaseResponse(resp)
	        if err != nil {
		        logging.Debug("NewHttpRequest Do err:", err, url)
		        return nil, err
	        }
	        b := resp.Body()
	        return b, nil
        }

        func HttpRequest(url, requestMethod string, requestData interface{}) (responseData []byte, err error) {
        
	        dataJson, err := json.Marshal(requestData)
	        if err != nil {
		        logging.Debug("HttpRequest json.Marshal err:", err, url)
		        return nil, err
	        }
	        payload := strings.NewReader(string(dataJson))
	        client := &http.Client{}
	        req, err := http.NewRequest(requestMethod, url, payload)
	        if err != nil {
		        logging.Debug("HttpRequest http.NewRequest err:", err, url)
		        return nil, err
	        }
	        req.Header.Add("Content-Type", "application/json")
        
	        res, err := client.Do(req)
	        if err != nil {
		        logging.Debug("HttpRequest client.Do err:", err, url)
		        return nil, err
	        }
	        defer res.Body.Close()
        
	        body, err := ioutil.ReadAll(res.Body)
	        if err != nil {
		        logging.Debug("HttpRequest ioutil.ReadAll err:", err, url)
		        return nil, err
	        }
	        return body, nil
        }

When I use NewHttpRequest to make http requests, I occasionally get an error，I can't find the reason or the pattern of this mistake:
       ` write tcp4 127.0.0.1:48496->127.0.0.1:10205: write: broken pipe`
  

But I don't get any errors when I use HttpRequest

**Comment by erikdubbelboer** [comment]
You can't use the return value of [`resp.Body()`](https://pkg.go.dev/github.com/valyala/fasthttp#Response.Body) after releasing the response.

**Comment by erikdubbelboer** [comment]
> > You can't use the return value of [`resp.Body()`](https://pkg.go.dev/github.com/valyala/fasthttp#Response.Body) after releasing the response.
> > i can't undunstand u, he is use defer
> > defer fasthttp.ReleaseResponse(resp)
> > why u say this

Exactly, the response will be released when the function returns. So returning `resp.Body()` is not valid anymore after the return.

**Comment by wnz27** [comment]
> > > You can't use the return value of [`resp.Body()`](https://pkg.go.dev/github.com/valyala/fasthttp#Response.Body) after releasing the response.
> > > i can't undunstand u, he is use defer
> > > defer fasthttp.ReleaseResponse(resp)
> > > why u say this
> 
> Exactly, the response will be released when the function returns. So returning `resp.Body()` is not valid anymore after the return.

so u mean use resp.body in this func internal?

**Comment by wnz27** [comment]
if use like this:
func doReq(req)  (res){
  httpErr :=  fasthttpclient.Do(req, resp)
  xxxxxx
  ............
  .........
  return resp
}
Will there be a problem with  broken pipe?

**Comment by erikdubbelboer** [comment]
No that is fine. You just can't use `resp` or any of the `[]byte` return by any of the methods on `resp` after calling `fasthttp.ReleaseResponse(resp)`.

**Comment by wnz27** [comment]
i use like that :
func doReq(req) (res){
httpErr := fasthttpclient.Do(req, resp)
xxxxxx
............
.........
return resp
}

func otherFunc () {

resp := doReq()
use resp
xxxxxx
defer release res and resp
}
but have some write broken pipe error.

**Comment by wnz27** [comment]
i think may have  be some bug internal. some position resp have been close....cause the write broken pipe error

**Comment by zwh203080815** [comment]
I’ve encountered this issue as well. What’s the solution???

**Comment by wnz27** [comment]
> I’ve encountered this issue as well. What’s the solution???
func some_func(){
 defer fasthttp.ReleaseResponse(resp)
        if err != nil {
	        logging.Debug("NewHttpRequest Do err:", err, url)
	        return nil, err
        }
        b := resp.Body()
        return b, nil
}
Explain the above method：

i think the problem is ：
Although b was return， it executed "defer Fasthttp.ReleaseResponse(resp)" before returning，
so it is useless to return it.

**Comment by wnz27** [comment]
> I’ve encountered this issue as well. What’s the solution???

```
func some_func(){
    defer fasthttp.ReleaseResponse(resp)
    if err != nil {
        logging.Debug("NewHttpRequest Do err:", err, url)
        return nil, err
    }
    b := resp.Body()
    return b, nil
}
```
Explain the above method：

i think the problem is ：
Although b was return， it executed "defer Fasthttp.ReleaseResponse(resp)" before returning，
so it is useless to return it.
