### ISSUE TITLE
Fasthttp WSL 2.0 request timeout.

### ISSUE THREAD

**Issue by errrov** [valyala/fasthttp#1675]
Im using corporate VPN. Go code that I start from WSL is timed out. Without VPN it works, but I won't have access to internal web. Fasthttp code works fine in kuber pods, worked fine in WSL1 on Windows10. Currently Im using WSl2.0 Windows11
---
Terminal:
![image](https://github.com/valyala/fasthttp/assets/79909234/fd261ddb-01fa-4d5e-9162-e9b03d3c86f8)

Code:
```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/valyala/fasthttp"
)

const (
	reqTimeout = 10 * time.Second
)

func main() {
	err := GetData("https://www.google.com/")
	if err != nil {
		log.Println(err)
	}
}

func GetData(baseUrl string) error {
	request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()
	defer func() {
		fasthttp.ReleaseResponse(response)
		fasthttp.ReleaseRequest(request)
	}()
	request.SetRequestURI(baseUrl)
	request.Header.SetMethod(fasthttp.MethodGet)
	log.Println(request.URI())
	if err := fasthttp.DoTimeout(request, response, reqTimeout); err != nil {
		return err
	}
	if response.StatusCode() != fasthttp.StatusOK {
		log.Printf("%s error: [%d] %s", baseUrl, response.StatusCode(), response.Body())
		return fmt.Errorf("request error[%d]: %s", response.StatusCode(), response.Body())
	}
	return nil
}
```

---
Using stdlib everything works fine:
![image](https://github.com/valyala/fasthttp/assets/79909234/0fda5cc9-19ab-442d-bce2-d4b9379a6799)

Code:

```
package main

import (
  "io"
  "log"
  "net/http"
)

func main() {
  resp, err := http.Get("https://www.google.com")
  if err != nil {
    log.Fatalln(err)
  }
  //We Read the response body on the line below.
  body, err := io.ReadAll(resp.Body)
  if err != nil {
    log.Fatalln(err)
  }
  //Convert the body to type string
  sb := string(body)
  log.Println(sb)
}
```

**Comment by erikdubbelboer** [comment]
Could it be a firewall or antivirus that only recognizes the way net/http does things but doesn't recognize fasthttp and blocks it because of that?

My recommendation would be to use `net/http` on windows. Fasthttp is not build for windows at all, it's going to contain more windows related bugs because nobody uses it on windows and we never test it on windows.

**Comment by errrov** [comment]
The thing is, I have problem in only 1 specific case - launching code with fasthttp that goes to private server from wsl 2.0. In all other cases it works fine. No solution for this?

**Comment by erikdubbelboer** [comment]
It's not a problem with fasthttp I'm afraid. It's probably your virus scanner or firewall doing this.
