### ISSUE TITLE
Code Leaks Memory on FreeBSD, but not on Linux

### ISSUE THREAD

**Issue by johnpharmetika** [valyala/fasthttp#1679]
### Go version

go version go1.20.8 freebsd/amd64

### What operating system and processor architecture are you using (`go env`)?

```shell
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go120"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go120/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.20.8"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/root/service_utility_go/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3737356626=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

Using GoFiber (which utilizes fasthttp) and Excelize to make a service that converts json to xlsx.
Code is developed on a Linux machine but ran on FreeBSD ultimately.
When running this code on FreeBSD, memory allocated is never GCed, causing a leak. This issue is not present when compiled on Linux (with the same code)
Tested code as Linux in console, Linux as service, FreeBSD in console, FreeBSD as service. Compiled/ran in Linux the code did not leak memory, FreeBSD it always did.

Handler function
```go
type excel_json struct {
	Data [][]interface{} `json:"data"`
}

func handle_excel_v1(fiber_context *fiber.Ctx) error {
	var json_values_root excel_json
	err := json.Unmarshal(fiber_context.Body(), &json_values_root)
	if err != nil {
		err = fmt.Errorf("parse data error: %d", err)
		fmt.Println(err)
		return nil
	}

	//Buffer is set for convert_json_to_excel to write bytes to
	var excel_data bytes.Buffer

	err = convert_json_to_excel(json_values_root.Data, &excel_data)
	if err != nil {
		err = fmt.Errorf("conversion error: %d", err)
		fmt.Println(err)
		return nil
	}

	/*if json_values_root.Exists("file_path") {
		file, _ := os.Create(fmt.Sprintf("%s.%s", string(json_values_root.GetStringBytes("file_path")), "xlsx"))
		defer file.Close()

		file.Write(excel_data.Bytes())
		fiber_context.JSON(fiber.Map{
			"success":   true,
			"file_path": string(json_values_root.GetStringBytes("file_path")),
		})
	} else {*/
	fiber_context.Response().Header.Set("Content-Disposition", "attachment; filename=response.xlsx")
	fiber_context.Write(excel_data.Bytes())
	//}
	return nil
}
```

Excel conversion function
```go
package main

import (
	"bytes"
	"fmt"

	"github.com/xuri/excelize/v2"
)

func convert_json_to_excel(json_data [][]interface{}, buffer_pointer *bytes.Buffer) error {

	var err error

	// Create a working temporary Excel "file"
	excel_file := excelize.NewFile()
	defer excel_file.Close()

	sheet_index, _ := excel_file.NewSheet("Sheet1")

	excel_file.SetActiveSheet(sheet_index)

	//Embolden the first row
	header_style, _ := excel_file.NewStyle(&excelize.Style{
		Font: &excelize.Font{
			Bold: true,
		},
	})
	header_row_opts := excelize.RowOpts{StyleID: header_style}

	stream_writer, _ := excel_file.NewStreamWriter("Sheet1")

	// Widen all used columns based on headers
	header_row := json_data[0]
	stream_writer.SetColWidth(1, len(header_row), 30)

	// Iterate through data and write to file
	for row := 0; row < len(json_data); row++ {

		active_row := json_data[row]
		//fmt.Printf("%s\n", active_row)

		first_cell := fmt.Sprintf("A%d", (row + 1))

		if row == 0 {
			stream_writer.SetRow(first_cell, active_row, header_row_opts)
		} else {
			stream_writer.SetRow(first_cell, active_row)
		}
	}

	stream_writer.Flush()

	_, err = excel_file.WriteTo(buffer_pointer)
	if err != nil {
		err = fmt.Errorf("write fail: %d", err)
		fmt.Println(err)
		return err
	}

	return nil
}
```

### What did you expect to see?

In use space for Linux 10 min after multiple requests processed
![image](https://github.com/golang/go/assets/144706161/d1eeb018-e2b2-4e60-ade4-2dacaf59ac5d)

### What did you see instead?

In use space for FreeBSD 10 min after multiple requests processed
![image](https://github.com/golang/go/assets/144706161/dcdec01e-22db-4b92-bba0-c82eb28b7cfe)

**Comment by erikdubbelboer** [comment]
I'm not sure how to help with this. There is no BSD specific code in fasthttp so I don't see how it could be causing this.

To me the FreeBSD memory profile looks more correct as it actually contains allocations you would expect. It seems like the Linux memory profile contains almost nothing which is unlikely. Try setting [`runtime.MemProfileRate = 1`](https://pkg.go.dev/runtime#MemProfileRate) at the top of your `main` func and re-run the memory profiles to get more accurate results.

Fasthttp will always keep some buffers allocated to re-use for next requests. You can see these in the FreeBSD profile but not in the Linux profile. Are you sure the Linux profile was made after it handled some requests?

Have you tried running the FreeBSD version for a while and see if the memory usage keeps increasing or if it stabilizes after a bit?

**Comment by johnpharmetika** [comment]
Thank you for your response,

Apologies for the previous Linux dump, this one with the MemProfileRate set is showing the Fasthttp buffers allocating as expected.

![image](https://github.com/valyala/fasthttp/assets/144706161/d8ee0483-68cc-4b0b-b384-c53b28594f22)

Versus FreeBSD, where the same test was done (same requests with the same body size amongst all of them)

![image](https://github.com/valyala/fasthttp/assets/144706161/d8f4a571-1376-49e4-9e36-9a92d1de4236)

![image](https://github.com/valyala/fasthttp/assets/144706161/ba4ec626-1e31-4ddf-abea-bc4b6a02a213)

It is also important to note that we use GoFiber (which uses fasthttp) for other endpoints, that do NOT have this issue when ran.

**Comment by erikdubbelboer** [comment]
It looks normal to me. I see buffers being allocated and kept. Why do you think there is a memory leak? What happens when you keep sending requests for a long time, does it run out of memory?

Your `top` screenshots show that Go has a lot of memory allocated. But that doesn't mean it's actually in use. If there is no memory pressure Go won't release memory to your system even if it isn't using any. How this behaves is differently between Linux and BSD I think.

**Comment by johnpharmetika** [comment]
Thank you for the response,

I believe you are correct with describing allocation being held on BSD vs Linux. Apologies for the non-issue.
