### ISSUE TITLE
How can I visit a website through http proxy?

### ISSUE THREAD

**Issue by AnotherGoogleFan** [valyala/fasthttp#168]
I need to visit a website by http proxy. But I just found socket proxy in fasthttp, and my proxy is a http proxy. Does fasthttp support http proxy? If it does, how can I do this?
Thank You.

**Comment by marcosrmendezthd** [comment]
Is there an example of how to use a proxy?

**Comment by mikelau864** [comment]
You can use HostClient to do it. But i found that it cant performs HTTPS request.

**Comment by erikdubbelboer** [comment]
Closed due to age.
