### ISSUE TITLE
Tests are not passing on mac with go1.7.

### ISSUE THREAD

**Issue by DocMerlin** [valyala/fasthttp#169]
--- FAIL: TestHostClientMaxConnsWithDeadline (0.06s)
    client_test.go:225: unexpected error: timeout

**Comment by erikdubbelboer** [comment]
All tests pass for me `go version go1.7.3 darwin/amd64`. I guess this issue can be closed.

**Comment by DocMerlin** [comment]
They are now passing with 1.8beta2 as well.  I'm going to close this.
