### ISSUE TITLE
Accessing some context in a `RoundTripper`

### ISSUE THREAD

**Issue by JonasDoe** [valyala/fasthttp#1696]
I'm trying to write some `RoundTrippers` which for example read correlation ids and some authorization infos from the context and write them into the outgoing `Request's` header. It seems like there nothing as a `context.Context` or a client-variant of `fasthttp.RequestCtx` get provided in the `RoundTripper's` signature `(hc *HostClient, req *Request, resp *Response) (retry bool, err error)` (or `fasthttp.Request`, respectively).

Is it possible to achieve something like that with fasthttp?

**Comment by erikdubbelboer** [comment]
I'm afraid that there is no such thing. But what you could try is keeping this information in a `map[*fasthttp.Request]Information`.

**Comment by JonasDoe** [comment]
I see. I imagine it's rather hard to set and delete/clean up these `Information` properly for `Request` use, though, esp. if I "just" want too provide some non-intrusive `RoundTrippers`. I think I'll refrain from creating those for now. Thank you for the clarification!
