### ISSUE TITLE
X-send-file

### ISSUE THREAD

**Issue by agborkowski** [valyala/fasthttp#17]
add support for x-send-file header ?

@ref http://stackoverflow.com/questions/3697748/fastest-way-to-serve-a-file-using-php/3731639#3731639

**Comment by valyala** [comment]
@agborkowski , fasthttp already provides the following approaches for sending local file contents in the response body:

* [RequestCtx.SendFile](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SendFile) for serving individual files.
* [FSHandler](https://godoc.org/github.com/valyala/fasthttp#FSHandler) and [FS](https://godoc.org/github.com/valyala/fasthttp#FS) for serving directory contents.

Could you provide more information on why these approaches don't fit your needs?

**Comment by valyala** [comment]
closing this issue, since it looks like fasthttp provides enough functionality for efficient files' sending. Feel free reopening the issue if fasthttp misses required functionality.
