### ISSUE TITLE
FastHTTP doesn't validate HTTP versions

### ISSUE THREAD

**Issue by kenballus** [valyala/fasthttp#1703]
RFC 2616 requires that HTTP versions match the following pattern:
```regex
HTTP/[0-9]+\.[0-9]+
```

RFCs 7230 and 9112 require that HTTP versions match the following pattern:
```regex
HTTP/[0-9]\.[0-9]
```

FastHTTP enforces neither of these rules. This feels a little risky because even control characters are permitted within HTTP versions. To see this for yourself, try sending the following request to a FastHTTP server, and observe that it is not rejected:
```
GET / HTTP/\r\r1.1\r\n\r\n
```

There is a small potential danger here, which is that if the HTTP version ends up being placed in a header value in the application logic, it is possible that this could be used for response splitting. This seems unlikely to me, so I'm reporting this publicly.

I recommend that FastHTTP begin enforcing the rule from the more modern RFCs. This is what the majority of other HTTP implementations do.

**Comment by erikdubbelboer** [comment]
I agree that potentially this could be an issue, what do you think of this fix? https://github.com/valyala/fasthttp/pull/1710

**Comment by kenballus** [comment]
If you want to continue to support HTTP/0.9, then you need to continue to support empty versions. Otherwise, the patch looks good.
