### ISSUE TITLE
application/octet-stream header gets added by default in case of a DELETE request without body

### ISSUE THREAD

**Issue by blaksucram** [valyala/fasthttp#1705]
Whenever I send a DELETE request without a `Content-Type` header and a body fasthttp adds the `application/octet-stream` `Content-Type` to the request which then confuses some of the back-ends which we call with that request.

As far as I read the several HTTP docs (mozilla and MSDN) a body should be ignored by the webservers which receive one in the DELETE request. This somehow does not fit the current logic which fasthttp implemented:

The `header.go` file contains logic which add a default `Content-Type` header in case of 

<img width="695" alt="image" src="https://github.com/valyala/fasthttp/assets/159246161/0d708e1e-669f-497b-8095-14668fa2c9f3">

Maybe we can either add the DELETE request to the `RequestHeader.ignoreBody` method or maybe remove the `ignoreBody` call from the `RequestHeader.AppendBytes` function.

<img width="695" alt="image" src="https://github.com/valyala/fasthttp/assets/159246161/c4e6e407-8ad6-44de-8d4c-2b452472ccd5">

What do you think?

Thanks in advance
Marcus

**Comment by erikdubbelboer** [comment]
I'm not sure where you got your information but according to [RFC9110 and the MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) a DELETE request **may** have a body. It doesn't say webservers should always ignore it. If you have a backend that gets confused by it I suggest you open an issue with them to fix this.

**Comment by blaksucram** [comment]
Hello @erikdubbelboer.

Got it thanks! 

But imho it does not make sense that the library "magically" makes up a `Content-Type` header of `application/octet-stream` in case a `DELETE` request with no body and no `Content-Type` header is executed.

**Comment by erikdubbelboer** [comment]
You need to call [ResponseHeader.SetNoDefaultContentType(true)](https://pkg.go.dev/github.com/valyala/fasthttp#ResponseHeader.SetNoDefaultContentType) to disable that behavior.

**Comment by blaksucram** [comment]
Thanks! That helped.
