### ISSUE TITLE
question regarding header parsing

### ISSUE THREAD

**Issue by prr123** [valyala/fasthttp#1706]
**Question:** Is there a code that parses the incoming heasder for shandard header fields? I looked through header.go and could only find methods for  selected header keys such as Content-length.  But there are 58 header keys according to Mozilla.

**Comment by erikdubbelboer** [comment]
Like you found specific headers that are actually used by fasthttp are parsed, other headers are just stored without parsing so they can be requested by the user. This is for example done here: https://github.com/valyala/fasthttp/blob/b430b88e7880ba596e093acf8e53186729e58882/header.go#L2989
