### ISSUE TITLE
Google App Engine Support 

### ISSUE THREAD

**Issue by amaendeepm** [valyala/fasthttp#172]
Does fasthttp support Google App Engine, and such over riding of http client needed therefore ?

https://medium.com/@amandeep.midha/case-for-kubernetes-go-google-appengine-gae-rabbitmq-and-hitting-the-glass-ceiling-51d6a60d307d#.uew0234dh

**Comment by erikdubbelboer** [comment]
I think App Engine should work. You just have to set [Client.Dial](https://godoc.org/github.com/valyala/fasthttp#Client.Dial) to use [google.golang.org/appengine/socket.Dial](https://godoc.org/google.golang.org/appengine/socket#Dial).
