### ISSUE TITLE
Expose `timeout` field in Request

### ISSUE THREAD

**Issue by TAYTS** [valyala/fasthttp#1745]
I want to retrieve the timeout with custom `RoundTripper` without creating another wrapper for the `Request` to tweak how the timeout is being handled or is it possible we could support user custom values similar to `RequestCtx.userValues` to allow the flexibility to inject value to the request?
The use case for this is that the current HostClient timeout is set for the whole request and for stream response I would like to fail the request if the response header is slow but wait for the response body for slightly longer time or a constant deadline extend if there are incoming data from stream

**Comment by erikdubbelboer** [comment]
I would be open to a pull request to add a method to expose this. But it needs some good documentation to make clear what it's for.

**Comment by gaby** [comment]
@erikdubbelboer @TAYTS this can be closed as fixed.
