### ISSUE TITLE
NewFastHTTPHandler does not set response status code.

### ISSUE THREAD

**Issue by luisgarciaalanis** [valyala/fasthttp#1753]
The NewFastHTTPHandler() handler does not set the Status code for the response:

https://github.com/valyala/fasthttp/blob/master/fasthttpadaptor/adaptor.go#L59

I have pointed the line of code that needs to be updated to set the status from the ctx response.

**Comment by erikdubbelboer** [comment]
It's a couple of lines below that? https://github.com/valyala/fasthttp/blob/d3a9c74c92588e83c465057c243e05b46d9118f7/fasthttpadaptor/adaptor.go#L65
