### ISSUE TITLE
error when serving connection ,body error

### ISSUE THREAD

**Issue by barnettZQG** [valyala/fasthttp#176]
code:
`handle = fasthttp.CompressHandler(handle)`
log:
`error when serving connection "127.0.0.1:8080"<->"127.0.0.1:60630": copied 1526 bytes from body stream instead of 1759 bytes`

If I do not use fasthttp.CompressHandler() ,there is no error.

**Comment by valyala** [comment]
@barnettZQG , could you verify that the issue is fixed now?
