### ISSUE TITLE
no free connections available to host

### ISSUE THREAD

**Issue by imtiazwazir** [valyala/fasthttp#1768]
I have following server setup and getting "no free connections available to host" any reason why? I did try many variations but none worked.

	server := &fasthttp.Server{
		Handler:            router.Handler,
		ReadBufferSize:     util.KBToBytes(16),
		WriteBufferSize:    util.KBToBytes(16),
		ReadTimeout:        time.Millisecond * 600,
		WriteTimeout:       time.Millisecond * 600,
		// IdleTimeout:        time.Second * 2,
		MaxRequestBodySize: util.MBToBytes(8),
		ReduceMemoryUsage:  false,
		MaxConnsPerIP:      10000,
		MaxRequestsPerConn: 10000,
		Concurrency:        1024 * 1024,
		LogAllErrors:       false,
		// TCPKeepalive:       true,
		// TCPKeepalivePeriod: time.Minute * 5,
	}

	config.Logger.Info("Server is starting on port 8080...")

	if err := server.ListenAndServe(":8080"); err != nil {
		config.Logger.Error("Error in ListenAndServe", "err", err)
	}

**Comment by erikdubbelboer** [comment]
What is generating the `no free connections available to host` message? Have you tried measuring how many concurrent requests you are receiving and if `10000` connections is enough for that?

I would not set `MaxRequestsPerConn` if not needed. This will force close connections after this many requests and is only needed for broken clients.

**Comment by imtiazwazir** [comment]
the thing is requests never reached to that value and still I am seeing that error `no free connections available to host` I am not sure if `.Server` also account `512` requests
