### ISSUE TITLE
when setting MaxConnsPerIP to  value greater than zero, the TLSConnectionState( ) is null on a TLS connection returned from the worker pool.

### ISSUE THREAD

**Issue by rabarar** [valyala/fasthttp#1770]
Using GoFiber (which uses fasthttp) if i attempt to set the server's `MaxConnsPerIP`, then the ` *fasthttp.RequestCtx.TLSConnectionState( )` returns nil. Without setting it to a value greater than zero, it works as expected and the `TLSConnectionState( )` returned is non-nil

**Comment by erikdubbelboer** [comment]
I have pushed a fix. I'll tag a release next week probably.

**Comment by rabarar** [comment]
how does one access the TLSConnectionState from a  *fasthttp.hijackConn - I attempted  type-casting it to *tls.Conn but it barfed on me saying it wasn’t a tls.Conn…

**Comment by erikdubbelboer** [comment]
I can't check right now but have you tried casting like this?
```
var conn *fasthttp.hijackConn
tlsConn, ok := conn.Conn.(*tls.Conn)
```

**Comment by rabarar** [comment]
indeed i have :-)

looking at your code, I want to get to the net.Conn - but  the issue is the type’s private 

kws.Conn.NetConn()  returns a *hijackConn - but I can’t call UnsafeConn to get the net.Conn to cast it...

type hijackConn struct {
	net.Conn
	r io.Reader
	s *Server
}

func (c *hijackConn) UnsafeConn() net.Conn {
	return c.Conn
}

**Comment by erikdubbelboer** [comment]
Maybe this?
```go
kws.Conn.NetConn().(interface{ UnsafeConn() net.Conn }).UnsafeConn()
```

**Comment by rabarar** [comment]
Actually - this likely should work - the PeerCertificate is empty because I put this in a test-strap that isn’t Requiring a Client Certificate….I’ll modify with a tls.Config requiring certificates and verify - in that case - no mods are needed.On May 3, 2024, at 11:58 AM, Robert Baruch ***@***.***> wrote:﻿nope - i tried this - (kws.Conn.NetConn().(interface{ UnsafeConn() net.Conn }).UnsafeConn()).(*tls.Conn)but it returns a ConnectionState that isn’t right - the PeerCertificates are empty …On May 3, 2024, at 11:43 AM, Erik Dubbelboer ***@***.***> wrote:Maybe this?
kws.Conn.NetConn().(interface{ UnsafeConn() net.Conn }).UnsafeConn()—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rabarar** [comment]
my goal is to replicate what i’m doing with a non-ws connection to access the PeerCerts:

peer := c.Context().TLSConnectionState().PeerCertificates[0]

...

**Comment by rabarar** [comment]
adding   tls.RequireAndVerifyClientCert to ClientAuth forced a client cert and all’s well - thanks again for taking a look!

**Comment by rabarar** [comment]
Any word on the tagged release with this update?On May 3, 2024, at 2:31 PM, Robert Baruch ***@***.***> wrote:﻿adding   tls.RequireAndVerifyClientCert to ClientAuth forced a client cert and all’s well - thanks again for taking a look!On May 3, 2024, at 11:43 AM, Erik Dubbelboer ***@***.***> wrote:Maybe this?
kws.Conn.NetConn().(interface{ UnsafeConn() net.Conn }).UnsafeConn()—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
