### ISSUE TITLE
peeking nested query args

### ISSUE THREAD

**Issue by turisap** [valyala/fasthttp#1777]
I have a request with nested query params which looks like this

```go
/ev?vendor_id=some_id&app_name=some_app_name&event={"cart":[{"some_idx":"484","vendor_id":"1065"}],"vendor_currency":"USD","vendor_id":"my_id"}&ip=123.123.123.123&some_source=
``` 

I can peek all top-level args with `ctx.QueryArgs().Peek()`. However, I cannot do that for nested query params like `vendor_id` in this case.

I will be happy to collaborate if this cannot be done and can be a new behaviour.

**Comment by erikdubbelboer** [comment]
This is not something that fasthttp will support. There is nothing HTTP about this. You happen to put JSON into a url param value, but there is no spec that defines any of this.
