### ISSUE TITLE
PFlag/Cobra compatibility in prefork

### ISSUE THREAD

**Issue by mhkarimi1383** [valyala/fasthttp#1782]
I'm using [Cobra](https://github.com/spf13/cobra) in my projects to manage my commands and Cobra is using [PFlag](https://github.com/spf13/pflag) to manage flags and since it's using `POSIX/GNU-style` (with `--` instead of `-`) I'm getting that error below

After adding snippet below to add compatibility I'm getting

```shell
      --prefork-child   Is a child process
unknown shorthand flag: 'p' in -prefork-child
unknown shorthand flag: 'p' in -prefork-child
```

```go
import (
	flag "github.com/spf13/pflag"
	goflag "flag"
)

func init() {
	flag.CommandLine.AddGoFlagSet(goflag.CommandLine)
	flag.Parse()
}
```

Also without

```go
flag.Parse()
```

I'm getting

```shell
Error: unknown shorthand flag: 'p' in -prefork-child
Error: unknown shorthand flag: 'p' in -prefork-child
```

**Comment by erikdubbelboer** [comment]
I agree, using a flag for this is not the best way to do it, see: https://github.com/valyala/fasthttp/pull/1783
