### ISSUE TITLE
fasthttp.FS won't return Content-Encoding when files are too small

### ISSUE THREAD

**Issue by gaby** [valyala/fasthttp#1795]
While writing unit-tests for Gofiber, we noticed that when using `fasthttp.FS` if the file is too small and we send a request with  `Accept-Encoding` to `gzip` the handler will *not* set the encoding header.

Request example:
```go
req := httptest.NewRequest(fiber.MethodGet, "/index.html", nil)
req.Header.Set("Accept-Encoding", "gzip")
```

Example file:
```css
h1 {
    color: red;
    text-align: center;
}
```

Returned headers:

```go
http.Header(
	http.Header{"Content-Length":[]string{"46"},
	"Content-Type":[]string{"text/css; charset=utf-8"},
	"Date":[]string{"Thu, 20 Jun 2024 12:11:58 GMT"},
	"Last-Modified":[]string{"Wed, 19 Jun 2024 20:44:53 GMT"}}
)
```

When using a bigger file like the index.html here https://github.com/gofiber/fiber/blob/main/.github/testdata/fs/index.html

The following headers are returned:

```go
http.Header(
	http.Header{"Content-Encoding":[]string{"gzip"},
	"Content-Length":[]string{"228"},
	"Content-Type":[]string{"text/html; charset=utf-8"},
	"Date":[]string{"Thu, 20 Jun 2024 12:13:47 GMT"},
	"Last-Modified":[]string{"Wed, 19 Jun 2024 20:44:53 GMT"}}
)
```

Is this intended, or should fasthttp always set the Content-Encoding header even if the file is now bigger ?

**Comment by ReneWerner87** [comment]
https://github.com/valyala/fasthttp/blob/497922a21ef4b314f393887e9c6147b8c3e3eda4/http.go#L1767-L1773

**Comment by gaby** [comment]
@erikdubbelboer Not sure if this should be better documented. Closing since it's not an issue.

**Comment by gaby** [comment]
@erikdubbelboer So fasthttp.FS only supports gzip/brotli, but it requires adding 2 params for it? Shouldn't it all just be "compress=True" and use the Accept-Encoding to decide which one to use?

**Comment by erikdubbelboer** [comment]
I'm not sure I understand. Yes it supports those if you enable them. You don't need a query param.
