### ISSUE TITLE
Fasthttp Client send multiple origin

### ISSUE THREAD

**Issue by ad3n** [valyala/fasthttp#1807]
![image](https://github.com/user-attachments/assets/d56a4152-d9b8-47e1-a949-7f0322d9d7cb)

Has prefix `,`

![image](https://github.com/user-attachments/assets/3d69682e-7ba5-489f-8ab0-18be78729236)

When using `net/http` client

How to send `origin` same as `net/http`?

**Comment by erikdubbelboer** [comment]
Can you please show the code to replicate this?

**Comment by ad3n** [comment]
Sorry my mistake, i'll close this issue
