### ISSUE TITLE
Cookie parse not working with upper case attributes

### ISSUE THREAD

**Issue by diegossilveira** [valyala/fasthttp#181]
Cookie's `Parse()` method only works with lower case attribute keys. If you try parsing this cookie string `Name=MyCookie; Path=/blog; Domain=site.net; Secure; Expires=Thu, 18 Dec 2013 12:00:00 UTC"` you will see the failure.

Accordingly to RFC-6265 (HTTP State Management Mechanism)[https://tools.ietf.org/html/rfc6265#section-4.1.1], these keys begins with a capital letter.

**Comment by diegossilveira** [comment]
Just created PR #183 to fix that!

**Comment by erikdubbelboer** [comment]
See: https://github.com/valyala/fasthttp/pull/384 should be merged soon.
