### ISSUE TITLE
Some questions about HTTP request headers?Welcome to join the discussion.

### ISSUE THREAD

**Issue by newacorn** [valyala/fasthttp#1838]
### Questiong1: Should values be formatted when setting HTTP headers under any circumstances?
Currently, values are only formatted in the `Set` method.
https://github.com/valyala/fasthttp/blob/0f84e656c2abc4f442fc3efb97aa79a252f4aba2/header.go#L1578-L1581
Other `Set`-like or `Add`-like methods do not format the values.
https://github.com/valyala/fasthttp/blob/0f84e656c2abc4f442fc3efb97aa79a252f4aba2/header.go#L1611-L1615

### Questiong2: Should the `disableNormalizing` configuration only control whether to ignore formatting of HTTP header keys?
Currently, it only applies to HTTP request header keys, and I think that's fine.
### Questiong3: Should the scope of the disableNormalizing configuration be more clearly defined?
From the current implementation, I observe that while parsing HTTP headers, the disableNormalizing setting is not respected, and formatting is always applied. This makes sense, as failing to do so could cause the HTTP header parsing process to hang in certain cases. If this behavior is confirmed, it could allow us to eliminate a lot of unnecessary repeated formatting, significantly improving performance in HTTP header operations.
### Questiong4: Aside from providing a `Canonical` interface for `Set`, should similar interfaces be provided for `Add`, `Peek`, and `Del` operations?
I think providing similar interfaces for Add, Peek, and Del operations could significantly improve performance. It also makes more sense from an API design perspective.
### Questiong5: Should further optimization be applied when validating keys based on the value of disableNormalizing?
If disableNormalizing is false, we still append the key.
https://github.com/valyala/fasthttp/blob/0f84e656c2abc4f442fc3efb97aa79a252f4aba2/header.go#L3432-L3436
If the value does not contain \r or \n, we still append the value.
https://github.com/valyala/fasthttp/blob/0f84e656c2abc4f442fc3efb97aa79a252f4aba2/header.go#L3427-L3429

**Comment by newacorn** [comment]
@erikdubbelboer  What do you think?
Disregarding optimization issues, whenever setting any HTTP header value, it should be formatted similarly to how it's done in the Set method. Should similar canonical interfaces be provided for the Peek, Del, and Add operations?

**Comment by erikdubbelboer** [comment]
I think for all questions backwards compatibility is the reason why things are what they are and why we aren't changing them. Adding similar functions for `Peek`, `Del` and `Add` would make sense.

**Comment by newacorn** [comment]
Makes sense.
