### ISSUE TITLE
Does the fasthttp can get the malformed HTTP response?

### ISSUE THREAD

**Issue by michaeldjonazh** [valyala/fasthttp#1853]
Hi I need to know does the fasthttp package can get the malformed HTTP response?
I using net/http but seems like this format:
`raw:b'GET /HTTP/1.0\r\nUser-Agent: Safari/1.0\r\nAuthorization: Basic MnZ0XcAxOjzyezVxd2By\r\n\r\n\r\n- I want to get this value over here -\r\n'
GET /HTTP/1.0
User-Agent: Safari/1.0
Authorization: Basic MnZ0XcAxOjzyezVxd2By

- I want to get this value over here -`

is possible to get value over there?

**Comment by erikdubbelboer** [comment]
I would just try it. I can't say from the top of my head but I'm guessing it will fail parsing. Just look at one of the tests that simple parse a request and modify that with your request.
