### ISSUE TITLE
RequestCtx forces the usage of a logger

### ISSUE THREAD

**Issue by gaby** [valyala/fasthttp#1867]
Looking at the `Init()` code from `RequestCtx` if `nil` is passes it defaults to using golangs native logger which adds latency.

Here https://github.com/valyala/fasthttp/blob/master/server.go#L2720
```go
func (ctx *RequestCtx) Init(req *Request, remoteAddr net.Addr, logger Logger) {
	if remoteAddr == nil {
		remoteAddr = zeroTCPAddr
	}
	c := &fakeAddrer{
		laddr: zeroTCPAddr,
		raddr: remoteAddr,
	}
	if logger == nil {
		logger = defaultLogger
	}
	ctx.Init2(c, logger, true)
	req.CopyTo(&ctx.Request)
}
```

Is this something that could be removed or avoided?

Related to https://github.com/gofiber/fiber/issues/3130

**Comment by gaby** [comment]
This can be avoided using:

```go
type NOOPLogger struct{}

func (NOOPLogger) Printf(ctx context.Context, format string, v ...interface{}) {
    // Do nothing here
}
```

But it adds overhead to the RequestCtx for no reason. Anything we can do about this ? @erikdubbelboer

**Comment by erikdubbelboer** [comment]
Changing this would in theory break backwards compatibility. It's such a minor thing and your `NOOPLogger` is a good solution that I think we should just leave it as is.
