### ISSUE TITLE
Support WebTransport

### ISSUE THREAD

**Issue by caevv** [valyala/fasthttp#1869]
WebTransport is an emerging protocol designed to address some limitations of WebSockets. Unlike WebSockets, which create a single stream per connection, WebTransport allows for multiple streams over a single connection, reducing delays and improving resource efficiency. It's built on top of HTTP/3 and QUIC, which enhances performance, particularly in environments with high latency or congestion.

**Comment by erikdubbelboer** [comment]
Since fasthttp only supports HTTP1/1.1 I'm afraid WebTransport will never be implemented in it.
