### ISSUE TITLE
Started receiving ErrConnectionClosed error on version 1.56.0

### ISSUE THREAD

**Issue by chlp** [valyala/fasthttp#1875]
After upgrading to version 1.56.0, started encountering error `ErrConnectionClosed`
```go
ErrConnectionClosed = errors.New("the server closed connection before returning the first response byte. " +
		"Make sure the server returns 'Connection: close' response header before closing the connection")
```

In my case, I was sending a POST request.
There is an inverse correlation between the error rate and RPS:
* At 500 RPS, there are almost no errors: 0% most of the time with consistently high RPS, with occasional periods where errors are less than 0.1%
* At around 10 RPS, the error rate significantly increases to 10-20%

Rolled back to version 1.55.0, and the errors disappeared completely.

**Comment by newacorn** [comment]
In version 1.56.0, for non-idempotent requests, the framework will no longer automatically make retry decisions for users regardless of the error encountered. When the newly added field `RetryIfErr` is not configured by the user, the default retry strategy is to never retry non-idempotent requests.

```go
	cli := HostClient{RetryIfErr: func(request *Request, attempts int, err error) (resetTimeout bool, retry bool) {
		isIdempotent := request.Header.IsGet() || request.Header.IsHead() || request.Header.IsPut()
		retry = true
		if !isIdempotent && err != io.EOF {
			retry = false
		}
		return
	}}
```
Defining `RetryIfErr` as shown below can replicate the behavior of version 1.55.0.

**Comment by chlp** [comment]
@newacorn wow, I see. I'll give it a try and come back to share results. Thank you so much!

**Comment by chlp** [comment]
yeah, it works, thanks again!

```go
	fasthttp.Client{
		RetryIfErr: func(req *fasthttp.Request, attempts int, err error) (resetTimeout bool, retry bool) {
			if err == io.EOF {
				return false, true
			}
			return false, false
		},
	}
```
