### ISSUE TITLE
Better error message on header without value

### ISSUE THREAD

**Issue by johanforssell** [valyala/fasthttp#188]
If you add a custom header with no value the connection will be dropped with an `error when reading request headers: need more data: cannot find trailing lf.`-message.

It's not that helpful when debugging - can it be changed?

**Comment by valyala** [comment]
@johanforssell , sure! Looking into this...

**Comment by valyala** [comment]
It looks like there is no bug here - see the added tests at 432960e4790434b344720ab55f8c5ef5e7822fe3 .

**Comment by johanforssell** [comment]
Those tests do look good! 

But I still ran into the issue and it went away when I removed the empty header.

I'll see if I can reproduce it outside of the environment of my client, so that I can show you directly what I ran into. Just need some free time :)

**Comment by valyala** [comment]
Waiting for additional info...

**Comment by johanforssell** [comment]
Unable to reproduce, please close.
