### ISSUE TITLE
HTTPS to HTTP proxying aka SSL termination.

### ISSUE THREAD

**Issue by figuerom16** [valyala/fasthttp#1903]
It looks like fasthttp can't proxy between HTTPS to HTTP or vice-versa with HostClient or Client.

HTTP to HTTP and HTTPS to HTTPS works fine of course.

HostClient result - **HostClient can't follow redirects to a different protocol fasthttp**
Client result - **tls: first record does not look like a TLS handshake**

My question is if it's possible to proxy between schemas?

It's not a big deal if it isn't since SSL can be terminated with NGINX or HAProxy.  Mostly would like to know if it's worth pursuing.

**Comment by erikdubbelboer** [comment]
With HostClient this is not possible, but with Client it should work. Can you post a minimal reproducible example?

**Comment by figuerom16** [comment]
I found the problem I was having.

For fasthttp.Client{}  I needed to set IncecureSkipVerify for upstream servers that use HTTPS selfsigned and wasn't correctly setting req.SetRequestURI().

Everything works perfectly now.
