### ISSUE TITLE
HostClient with SNI

### ISSUE THREAD

**Issue by diegossilveira** [valyala/fasthttp#191]
After the commit 4ca4d0ea09a64cfa8cce637383086ea2d6c20af1, TLS requests with SNI stopped working.

Please, take a look at this comment: https://github.com/valyala/fasthttp/commit/4ca4d0ea09a64cfa8cce637383086ea2d6c20af1#diff-d0b7f86cea13f90d3cc0cc2338da8d5fR1350

**Comment by valyala** [comment]
@diegossilveira , could you verify that the bug is fixed now?

**Comment by diegossilveira** [comment]
That's ok now. Thank you @valyala!
