### ISSUE TITLE
Feature Request: Do not override custom Host header with URI host part

### ISSUE THREAD

**Issue by missish** [valyala/fasthttp#1922]
Currently, when using the fasthttp client, the Host header is automatically set based on the URI in the request. However, when a custom Host header is set by the user, it should not be overridden by the host part of the URI.

Problem:
For example, when sending the following request:

```
curl -v -H "Host: abc.com" http://192.168.2.35/
```
The Host header should be abc.com. However, since fasthttp overrides the custom Host header with the host part of the URI (which is 192.168.2.35), the behavior does not match expectations.

Proposed Solution:
I would like to request an enhancement where if the Host header is explicitly set by the user, it should be used as-is and not be overridden by the host part of the URI.

Use Case:
Allow more precise control over the Host header in scenarios such as reverse proxies, domain-based routing, or when sending requests that require a specific Host header for virtual hosting.
Make the fasthttp client behave more like the standard library http.Client, which preserves the custom Host header without overriding it based on the URI.
Example Request Code:
```
package main

import (
	"fmt"
	"log"
	"github.com/valyala/fasthttp"
)

func main() {
	// Create fasthttp client and request
	client := &fasthttp.Client{}
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	// Set custom Host header
	req.SetRequestURI("http://192.168.2.35/")
	req.Header.Set("Host", "abc.com")

	// Send request
	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)

	err := client.Do(req, resp)
	if err != nil {
		log.Fatalf("Request failed: %v", err)
	}

	// Output response status and body
	fmt.Printf("Response status: %d\n", resp.StatusCode())
	fmt.Printf("Response body: %s\n", resp.Body())
}
```
Expected Behavior:
With the above code, the Host header should be abc.com, and it should not be overridden by the host part of the URI. The request should be sent with the Host: abc.com header, targeting http://192.168.2.35/.

**Comment by erikdubbelboer** [comment]
You can set [`req.UseHostHeader = true`](https://pkg.go.dev/github.com/valyala/fasthttp#Request.UseHostHeader) for this behavior. See this issue for why: https://github.com/valyala/fasthttp/pull/1169
