### ISSUE TITLE
DelClientCookie doesn't delete cookie with path

### ISSUE THREAD

**Issue by malstoun** [valyala/fasthttp#197]
Hi

If I create a new cookie with path I can't delete it with `DelClientCookie` method. It cleans the value and set the expdate, but browser also wants path.

Is it a bug or I should use SetExpire in this case?

**Comment by kataras** [comment]
Please post the solution if you 'fix' it or write down what you did wrong before and it didn't worked for you. This way you help newcomers, other people, if they meet an issue like yours. Thanks!!
