### ISSUE TITLE
Connection refused (echo/fasthttp)

### ISSUE THREAD

**Issue by Puffton** [valyala/fasthttp#198]
Some clients, seemingly at random, get "Connection refused" when trying to load any webpage, effectively shutting them out of the site. This has been a recurring issue for about a year now.

At first I found some bugs in my code and thought it might be the panic handler not working, causing panics to bring the server down. A reboot fixed the problem and in time I found the bugs and fixed them too.

After a while I realized that only some users get their connections refused. At that point the error log was blank. Curious to see if it could be some feature of Ubuntu I restarted just Go, not the entire machine, and it solved the issue (so it doesn't seem like an OS/firewall issue).

I'm puzzled to what this could be, do you guys have any suggestions? Currently running on Ubuntu 16.10, the latest versions of Go, fasthttp and the v2 branch of echo (but have had issues with Ubuntu 16.04, 15.10 and probably 15.04 too). I hear about these issues about once per week, so it's not occurring super frequently, making it hard to debug.

Also reported here: https://github.com/labstack/echo/issues/705

**Comment by valyala** [comment]
@Puffton , `connection refused` error may appear on a highly loaded `fasthttp` server when a lot of concurrent clients are trying to establish new connections to the server. This usually points to a low `backlog` value passed to [listen](http://man7.org/linux/man-pages/man2/listen.2.html).

By default `fasthttp` server uses system-wide `backlog` value read from `/proc/sys/net/core/somaxconn`. Increase this value and the error should disappear. Additionally, the value may be adjusted via a custom listener created from [tcplisten.Config](https://godoc.org/github.com/valyala/tcplisten#Config) and passed to [Server.Serve](https://godoc.org/github.com/valyala/fasthttp#Server.Serve).

Pay attention to the following lines from `listen(2)` manpage:
> If the backlog argument is greater than the value in /proc/sys/net/core/somaxconn, then it is silently truncated to that value; the default value in this file is 128

**Comment by Puffton** [comment]
I don't think it's because of the load. Once it stops responding, it never responds again for that specific user/client (but other users can use the site). If it gets stuck like that I can connect using my cellphone internet for example, but my other connection (from my regular IP at my computer at home) seems blocked somehow.

It's very weird, as if it were a firewall issue, but since restarting Go solves it, it should be related to Go. I was thinking if a certain connection hangs somehow and the server thinks it remains open on its end? I don't know.

**Comment by valyala** [comment]
@Puffton , try enabling `net.ipv4.tcp_tw_reuse` and on both the server and the client. Probably all the (client <-> server) address pairs are in `TIME_WAIT` state and this prevents from establishing new connections. See [this article](https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux.html) for details.
