### ISSUE TITLE
Is that possible to add support for net.ConnState?

### ISSUE THREAD

**Issue by velikaww** [valyala/fasthttp#205]
I hope there are callbacks for net.ConnState as net/http has, is that possible?
If fine, I'd to do that and raise a PR later.
Thx!

**Comment by lday0321** [comment]
We also need this feature

**Comment by Jamesxql** [comment]
Monitoring connection status changes is a very common requirement.

In `net/http` package, there are five states with client connection:
* StateNew
* StateActive
* StateIdle
* StateHijacked
* StateClosed

I want to be able to register a callback function that is called when a client connection changes state on the `fasthttp.Server` struct. 

Can you @velikaww  submit a PR to complete this function?

**Comment by tsingson** [comment]
https://github.com/valyala/fasthttp/blob/master/expvarhandler/expvar.go 

you want this ?

**Comment by erikdubbelboer** [comment]
A PR for this would be welcome! I'm not sure when I'll have time to implement this myself.
