### ISSUE TITLE
A new Middleware Web FrameWork based on fasthttp --- lu

### ISSUE THREAD

**Issue by vincentLiuxiang** [valyala/fasthttp#207]
hi @valyala, I am a loyal users of fasthttp, I just wrote a Light-weighted middleware web framework which is based on fasthttp, I quite hope you can recommend my project [lu a Light-weighted middleware webframework ](https://github.com/vincentLiuxiang/lu)

**Comment by zhuqiuyang** [comment]
@vincentLiuxiang @valyala i have a try of lu, it's quite lightweight ,fit my demand.
i can organize my middlewares in any route easily.
But can you add some performance compares with other web framework or router.

**Comment by thalesfsp** [comment]
Agreed

**Comment by vincentLiuxiang** [comment]
thx @thalesfsp, If you have used the frameworks like express/connect/koa in node.js, you will find that lu is very similar in usage.

**Comment by valyala** [comment]
@vincentLiuxiang , now `lu` is mentioned in [README.md](https://github.com/valyala/fasthttp/blob/master/README.md)
