### ISSUE TITLE
Best practices for a client application with large requests/responses?

### ISSUE THREAD

**Issue by keeyim** [valyala/fasthttp#211]
I'm using fasthttp to implement a Client interface, where I need to do 1MB+ GETs and 1-10MB PUTs. I'm finding that the performance is not as good as I expected, but I suspect that there are some best practices that I could be using to make things perform better in my application.

I've tried setting the HostClient.ReadBufferSize and WriteBufferSize, but it's not helping a lot and when I do memory profiling I see a lot of allocations and appends.

I've looked through the issues here and found a few hints, but in some cases it isn't enough information. For example, should I be using a StreamWriter? If so, do you have any examples of how to do this? What I've found in the tests and examples are a bit too simple and I'm having trouble applying these to a more complex case.

Thanks!

**Comment by joffreZju** [comment]
i met the same question, have you solving this problem? can you help me?

**Comment by themester** [comment]
@joffreZju we are solving huge requests and other issues in this fork github.com/erikdubbelboer/fasthttp

**Comment by erikdubbelboer** [comment]
Do you have a simple example of a program where the performance isn't as good as you expect?
