### ISSUE TITLE
Request cancellation

### ISSUE THREAD

**Issue by aaronshurley** [valyala/fasthttp#213]
Current implementation of fasthttp request does not seem to handle request cancellation/context. This functionality is provided by golang net/http's request context, is there a plan to include this in fasthttp? Or is there any alternative way of handling this right now? We would like to discuss with you about the addition of this functionality.

**Comment by erikdubbelboer** [comment]
The current way to handle this is using [`Client.DoTimeout`](https://godoc.org/github.com/valyala/fasthttp#Client.DoTimeout). There are no plans to support `context` at the moment.

**Comment by pjebs** [comment]
Cancel is not a timeout (specific time duration). It is when the client of the server cancels request.
