### ISSUE TITLE
DoTimeout alters multipart-form request

### ISSUE THREAD

**Issue by swetharepakula** [valyala/fasthttp#223]
When using HostClient.DoTimeout, our handler is unable to use the golang MultiPartReader to parse the request (which has a multipart form). We end up with an EOF error. However when using HostClient.Do, our handler has no issues parsing the request.

Thank You,
@swetharepakula && @aaronshurley
The CF Routing Team

**Comment by erikdubbelboer** [comment]
Can you please provide an example.

**Comment by aaronshurley** [comment]
@erikdubbelboer Thanks for following up. This issue is pretty old and we're no longer investigating this option. Feel free to close out the issue.

**Comment by lemonlinger** [comment]
We encounter this issue too. Any plans to solve it?

**Comment by erikdubbelboer** [comment]
@lemonlinger do you have some example code that causes this issue so I can have a look at it?
