### ISSUE TITLE
By default redirect http requests to https when using TLS

### ISSUE THREAD

**Issue by tytouf** [valyala/fasthttp#226]
Hi, when using ListenAndServeTLS, requests to http:// return error or garbage while I think it would be more appropriate to return a redirect to the same path, simply changing the scheme to https.

I would be happy to help implement that, but my first investigation got me stuck in the TLS layer. I'm not sure how TLS really works and where this kind of feature should be handled (ie. before the TLS net.conn or inside or after) so any pointer would definitely help :-)

Edit: or is it the work of a proxy and it should be kept out of fasthttp?

**Comment by erikdubbelboer** [comment]
I'm afraid it doesn't seem like this is possible. It seems like [reading from a tls.Conn](https://golang.org/pkg/crypto/tls/#Conn.Read) returns EOF as error no data when you don't send a TLS request. This means we won't be able to see if someone is sending a normal HTTP request or if something else is wrong with the connection.
