### ISSUE TITLE
Integrate pprof

### ISSUE THREAD

**Issue by nikunjy** [valyala/fasthttp#235]
Is there any easy way to integrate pprof with fasthttp ? Instead of using fasthttpadapter and pointing to handler functions provided by pprof

**Comment by codesenberg** [comment]
What about attaching `pprof` to a `net/http`-server binded to a different port?
```go
package main

import (
	"log"
	"net/http"
	_ "net/http/pprof"

	"github.com/valyala/fasthttp"
)

func main() {
	go func() {
		log.Println(http.ListenAndServe("localhost:6060", nil))
	}()
	fasthttp.ListenAndServe("localhost:8080", func(ctx *fasthttp.RequestCtx) {
		ctx.Success("text/plain; charset=utf-8", []byte("Hello, fasthttp and pprof"))
	})
}
```

**Comment by nikunjy** [comment]
That is not really a great solution, I have been doing that so far. 

@valyala

**Comment by codesenberg** [comment]
@nikunjy, what is exactly not so great about it?
Do you have in mind/want to propose anything specific?
Oh, and I have to warn you that @valyala rarely answered to issues in last few months.

**Comment by kataras** [comment]
@nikunjy Look how Iris did that months ago, copy the code and change it in order to work with raw fasthttp, it's quite easy:  https://github.com/iris-contrib/middleware/blob/5.0.0/pprof/pprof.go

**Comment by kataras** [comment]
@nikunjy Look how Iris did that months ago, copy the code and change it in order to work with raw fasthttp, it's quite easy:

-   https://github.com/iris-contrib/middleware/blob/5.0.0/pprof/pprof.go 
- https://github.com/kataras/iris/blob/5.0.0/http.go#L263


You're welcome,
kataras

**Comment by nikunjy** [comment]
Thank you @kataras I was hoping that it would be a first class citizen in this library. Maybe an opportunity for me to do a PR. 
@codesenberg the problem with that solution is that in prod environments I don't have to use another port to profile so it is not necessarily a  bad solution but would be even great if fasthttp supported it.

**Comment by codesenberg** [comment]
@nikunjy, oh, I see. Then it is indeed and an opportunity for a PR or, maybe, this doesn't have to live in `fasthttp` itself, since it doesn't use any internals, but in some other library.
I ask you to consider writing a separate library, because in last ~3 months @valyala accepted only [1 PR](https://github.com/valyala/fasthttp/pull/234).

**Comment by erikdubbelboer** [comment]
I just added a pull request for this.

I'm still hoping one day @valyala will add someone else to help maintain this repository (I don't mind doing it).

**Comment by nikunjy** [comment]
@valyala can you accept this PR ^

**Comment by DuckerMan** [comment]
Up!

**Comment by kirillDanshin** [comment]
ha-ha, I implemented this in https://github.com/gramework/gramework/blob/dev/pprof/pprof.go a long time ago but forgot that fasthttp doesn't support this out of the box. 

@DuckerMan just merged it :)
