### ISSUE TITLE
HostClient.Do seems to be using an absolute path instead of an absolute URI

### ISSUE THREAD

**Issue by jinpan** [valyala/fasthttp#239]
I'm seeing some unexpected behavior with the request line when issuing a HostClient.Do:  I have some code that looks like

```
c := &fasthttp.HostClient{
  Addr: "{some proxy ip}:{some proxy port}"
}

req = fasthttp.AcquireRequest()
resp = fasthttp.AcquireResponse()
defer fasthttp.ReleaseRequest(req)
defer fasthttp.ReleaseResponse(resp)

req.SetRequestURL("http://www.foo.com/bar")

c.Do(req, resp)
```

On the wire, this sends

```
GET /bar HTTP/1.1
User-Agent: fasthttp
Host: www.foo.com
```

RFC 2616 5.1.2 says 

> The absoluteURI form is REQUIRED when the request is being made to a
> proxy.
...
> To allow for transition to absoluteURIs in all requests in future
> versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI
> form in requests, even though HTTP/1.1 clients will only generate
> them in requests to proxies.

I'm running issues with fasthttp in its current from when I make a request to a proxy.  Can we make fasthttp compliant with the RFC and always send the full URI?

**Comment by erikdubbelboer** [comment]
See https://github.com/valyala/fasthttp/pull/240

**Comment by erikdubbelboer** [comment]
Closed in favor of https://github.com/valyala/fasthttp/pull/240.
