### ISSUE TITLE
Set TCP_NODELAY with fasthttp

### ISSUE THREAD

**Issue by dearcj** [valyala/fasthttp#241]
Hi

Is it possible to set SetNoDelay method with fasthttp.hijackConn?

I'm using gorilla websockets port for fasthttp but I don't understand how to get rid of Nigel algorithm
	c := conn.UnderlyingConn()
	conn2 := c.(*net.TCPConn)
	conn2.SetNoDelay(false)

this doesn't work because 
panic: interface conversion: net.Conn is *fasthttp.hijackConn, not *net.TCPConn

**Comment by codesenberg** [comment]
AFAIK, `fasthttp` doesn't provide such API, but you could workaround this by writing custom listener
```go
type CustomListener net.TCPListener

func NewCustomListener(raddr string) (*CustomListener, error) {
	addr, err := net.ResolveTCPAddr("tcp4", raddr)
	if err != nil {
		return nil, err
	}
	ln, err := net.ListenTCP("tcp4", addr)
	return (*CustomListener)(ln), err
}

func (cl *CustomListener) Accept() (net.Conn, error) {
	conn, err := (*net.TCPListener)(cl).AcceptTCP()
	if err != nil {
		return conn, err
	}
	conn.SetNoDelay(false)
	return conn, err
}

func (cl *CustomListener) Addr() net.Addr {
	return (*net.TCPListener)(cl).Addr()
}

func (cl *CustomListener) Close() error {
	return (*net.TCPListener)(cl).Close()
}

```
and then supplying it to `fasthttp.Serve`
```go
ln, err := NewCustomListener(addr)
if err != nil {
	log.Fatal(err)
}
err = fasthttp.Serve((net.Listener)(ln), handler)
```
Note, that this approach will set `NoDelay` to `false` as soon as connection is established.
Another thing you might do, if you really need to change `NoDelay`, is use reflection:
```go
var hijackHandler = func(c net.Conn) {
	p := reflect.ValueOf(c)
	v := reflect.Indirect(p)
	conn, ok := v.FieldByName("Conn").Interface().(*net.TCPConn)
	if ok {
		conn.SetNoDelay(false)
	}
	//... use c as you normally would ...
}
```
While it's probably safe thing to do, I wouldn't recommend doing it anyway.

**Comment by dearcj** [comment]
Thanks a lot! I recently learned that in go TCP_NODELAY  is set by default to false

**Comment by codesenberg** [comment]
@dearcj, so, the issue is resolved and can be closed or is there anything else that you want to resolve?

**Comment by dearcj** [comment]
oh yes, sure. thanks!
