### ISSUE TITLE
Why the data structure of query args is array instead of map? the official  net/http package is a map[string][]string

### ISSUE THREAD

**Issue by hanjm** [valyala/fasthttp#242]
it's seems that when i invoke  the `ctx.QueryArgs().Peek("key")` it will search in the []argsKV., if i want to parse all the query args, it is O(n*n).
but the official  net/http package is a map[string][]string,which is O(n).

https://github.com/valyala/fasthttp/blob/master/args.go#L395L403
```go
func peekArgBytes(h []argsKV, k []byte) []byte {
	for i, n := 0, len(h); i < n; i++ {
		kv := &h[i]
		if bytes.Equal(kv.key, k) {
			return kv.value
		}
	}
	return nil
}
```
``` go 
type Args struct {
	noCopy noCopy

	args []argsKV
	buf  []byte
}

type argsKV struct {
	key   []byte
	value []byte
}
```

**Comment by codesenberg** [comment]
@hanjm, if you want iterate over all query arguments in linear time use [fasthttp.(*Args).VisitAll](https://godoc.org/github.com/valyala/fasthttp#Args.VisitAll).
