### ISSUE TITLE
how to write a server to support chunked file uploading

### ISSUE THREAD

**Issue by newhow** [valyala/fasthttp#247]
It seems that I have to write my own code to parse each chunk and finally assemble all abstracted data into a file. Any package to ease this work?

**Comment by newhow** [comment]
Okay, it turns out that like native http package, fasthttp parses the chunked files automatically. 
`func upload(ctx *fasthttp.RequestCtx){
    f, _ := os.OpenFile("./uploaded/"+string(ctx.FormValue("name")), os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0666)
		fheader, _ := ctx.FormFile("file")
		file, _ := fheader.Open()
		io.Copy(f, file)
		defer file.Close()
		defer f.Close()
}`
The above code works right. But if I replaced io.copy with some other writing methods, for example `ctx.Request.BodyWriteTo(f) `
then I got the file f  wrong and a little larger than its original size. Anybody knows why?

**Comment by lusi1990** [comment]
@newhow file f contain some thing like this

------WebKitFormBoundaryZ50OiOiOilAD06v0
Content-Disposition: form-data; name="file"; filename="swagger.yaml"
Content-Type: application/octet-stream

**Comment by erikdubbelboer** [comment]
Writing the body using `ctx.Request.BodyWriteTo()` will write the form metadata submitted in the POST as well (like @lusi1990's example above). Using `ctx.FormFile("foo")` will parse this metadata and get you the file named `foo` only.
