### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by erikdubbelboer** [valyala/fasthttp#251]
There are lots of bugfixes and improvements that keep on piling up without any attention.

Is this project no longer maintained? Should the community fork this project and focus on the fork?

@valyala If you don't have the time to maintain this project can you at least answer this question?

**Comment by knadh** [comment]
@valyala? Wondering the same.

**Comment by kataras** [comment]
@erikdubbelboer and @knadh I think that is maintaned by @valyala , as always, I notified about some commits he made 17 days ago. I don't have any --inside information-- but I'm sure that he's working on something else so **at the moment** he is unable to find enough time to answer to all of your questions, but he will do, be pattient :) 

Kind regards,
Makis

**Comment by erikdubbelboer** [comment]
@kataras This is what I'm hoping for as well.

But there are simple pull requests that wouldn't take him longer than a couple of minutes to review and merge.

Like https://github.com/valyala/fasthttp/pull/248 which makes all fasthttp servers susceptible to a DOS attack and **prevents fasthttp from being used in any user facing programs**.

Or https://github.com/valyala/fasthttp/pull/231 for example to make tests not randomly fail anymore.

**Comment by oschwald** [comment]
I wonder if it would make sense for there to be a community-maintained fork that keeps pace with upstream but integrates fixes such at these as well as fixes to various HTTP edge cases that fasthttp mishandles. @valyala has done a wonderful job in creating fasthttp and continuing to develop it, but issues like these need to be addressed promptly for production use of it.

**Comment by erikdubbelboer** [comment]
@oschwald this is something I was thinking of doing here: https://github.com/erikdubbelboer/fasthttp
This is the fork we use for our projects.

**Comment by BorisKozo** [comment]
I am considering of using fasthttp for a new project which requires high performance. Was wondering the same thing when I saw no new release for about a year.

**Comment by erikdubbelboer** [comment]
@BorisKozo we are using fasthttp for projects which require high performance as well. We don't use it for any public facing infrastructure so I can't say how well it performs with the conditions on the open internet. But for predictable and stable conditions fasthttp is very reliable. I think the codebase is quite mature and doesn't require much maintaining as it is. It still would be nice if @valyala could maintain it a little bit for the small amount of bugs that people do find.

**Comment by BorisKozo** [comment]
@erikdubbelboer Thank you for the advice. Another option would be for @valyala to add collaborators such as yourself so that others can update the main repo and not create numerous forks.

**Comment by solarfly73** [comment]
https://github.com/valyala/fasthttp/commit/6ac0fd1a910c94aefb171ae56941833831e7c7fe

7 hours ago

**Comment by erikdubbelboer** [comment]
Yes he sometimes commits. But he completely ignores all issues and pull requests. Even when they are obvious bug fixes.

**Comment by solarfly73** [comment]
Yes, I researched this project yesterday and reviewed the issues, and I agree with several comments in the threads that it's not production ready.  I'm also worried with the intermittent attention to pull requests.  We're going to stick with HttpRouter and various middleware wrapping net/http for now, but I'm interested in this code so will be keeping an eye on it.

**Comment by kirillDanshin** [comment]
![image](https://user-images.githubusercontent.com/9026581/44006843-9be75c86-9e93-11e8-9d69-d02f59903036.png)

fasthttp is alive again 🙂

**Comment by knadh** [comment]
That's good news, @kirillDanshin.

Do you have any set plans for fasthttp that you'd be able to outline? @erikdubbelboer has put in a lot of effort into his fork (https://github.com/erikdubbelboer/fasthttp) which is now far ahead. Maybe that'd be a good place to start?

Thanks

**Comment by kirillDanshin** [comment]
@knadh please see https://github.com/erikdubbelboer/fasthttp/issues/51
