### ISSUE TITLE
Do not append default server name in HTTP Response when "Server" field not exists

### ISSUE THREAD

**Issue by zt2** [valyala/fasthttp#254]
Hi

When I using fasthttp as a http client, I found default server name "fasthttp" always appear in HTTP response header when response has no "Server" field.

For example:

```go
package main

import (
	"fmt"
	"github.com/valyala/fasthttp"
)

func main() {
	url := "http://x.x.x.x"

	client := &fasthttp.Client{}
	request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()

	defer fasthttp.ReleaseRequest(request)
	defer fasthttp.ReleaseResponse(response)

	request.SetConnectionClose()
	request.SetRequestURI(url)

	if err := client.Do(request, response); err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(string(response.Header.Header()))
	}
}
```

"x.x.x.x" is a http server where has no "Server" field in HTTP header, when `response.Header.Header()` called, fasthttp will append 'fasthttp' into server field like this:

```http
HTTP/1.1 200 OK
Server: fasthttp
Date: Tue, 25 Apr 2017 08:03:31 GMT
Content-Type: text/html
Content-Length: 6996
Expires: 0
Connection: close
```

code can be found in https://github.com/valyala/fasthttp/blob/3580c93d0226d5412e3e1531545405478d239c8e/header.go#L1429

```
// AppendBytes appends response header representation to dst and returns
// the extended dst.
func (h *ResponseHeader) AppendBytes(dst []byte) []byte {
	statusCode := h.StatusCode()
	if statusCode < 0 {
		statusCode = StatusOK
	}
	dst = append(dst, statusLine(statusCode)...)

	server := h.Server()
	if len(server) == 0 {
		server = defaultServerName // "fasthttp"
	}
```

**Comment by erikdubbelboer** [comment]
This was fixed in https://github.com/valyala/fasthttp/pull/232 but I think because this project seems to be unmaintained @Perelandric closed the pull request again.

**Comment by Perelandric** [comment]
@erikdubbelboer Yep, exactly. It became apparent to me that this isn't a dependable project that is taken seriously by its lead. I have other thoughts on the project pertaining to its codebase and API, but I'll refrain from posting them here.

**Comment by erikdubbelboer** [comment]
Should be fixed in https://github.com/valyala/fasthttp/commit/d84d8ea6048240b42f378176c6fb78efc59b6e06
