### ISSUE TITLE
appendQuotedPath breaks certain URLs

### ISSUE THREAD

**Issue by night** [valyala/fasthttp#256]
It seems that `appendQuotedPath` usage in uri.go causes certain URLs to break for services that do not expect URL-encoded entities in their paths.

An example case is Google drive URLs, which contain an asterisk. `https://doc-00-00-docs.googleusercontent.com/docs/securesc/redacted/redacted/redacted/redacted/*/redacted` resolves to `https://doc-00-00-docs.googleusercontent.com/docs/securesc/redacted/redacted/redacted/redacted/%2A/redacted`

This is one case, but another service we've seen has `@` in the path, which url encodes to `%40`.

**Comment by erikdubbelboer** [comment]
This seems to be almost the same issue as https://github.com/valyala/fasthttp/pull/250
