### ISSUE TITLE
HTTP Client Post with timeout/deadline

### ISSUE THREAD

**Issue by smthpickboy** [valyala/fasthttp#258]
I see there's a GetTimeout/GetDeadline for GET method. It would be really useful to add timeout/deadline for POST as well.

It's even better if fasthttp client could support context.

Thanks a lot!

**Comment by tmwalaszek** [comment]
I think the only way to do POST with timeout or deadline is to use DoTimeout/DoDeadline methods from Client and handle redirects on our own if necessary.
