### ISSUE TITLE
Bug in SaveMultipartFile

### ISSUE THREAD

**Issue by Saticmotion** [valyala/fasthttp#263]
There's a bug in `SaveMultipartFile()`. When it tries to rename the file, the file is not closed before renaming, and then fails with an error saying the file is in use by another process.

This bug only happens when a file is bigger than `defaultMaxInMemoryFileSize`, because only then a temp file is created on disk.

So I changed lines 758-760 from:

```go
if ff, ok := f.(*os.File); ok {
	return os.Rename(ff.Name(), path)
}
```

to:

```go
if ff, ok := f.(*os.File); ok {
	f.Close()
	return os.Rename(ff.Name(), path)
}
```

**Comment by erikdubbelboer** [comment]
@Saticmotion I'm guessing you're on Windows? On linux systems renaming a file that is open is perfectly fine.

I pushed a fix here: https://github.com/valyala/fasthttp/pull/403

**Comment by Saticmotion** [comment]
@erikdubbelboer  Yes indeed, thanks for the fix!
