### ISSUE TITLE
fasthttp does not respect Connection: close request header

### ISSUE THREAD

**Issue by brian-armstrong-discord** [valyala/fasthttp#264]
From a brief glance at the code, it seems fasthttp skips parsing this header in the name of speed. So it chooses to be incorrect, but does so very quickly. It should be correct instead.

**Comment by erikdubbelboer** [comment]
Should be fixed in https://github.com/valyala/fasthttp/commit/b3b6b8cb28ba2fb9783dd887031ecea0040280fd
