### ISSUE TITLE
How to reverse proxy websocket connection?

### ISSUE THREAD

**Issue by ysmood** [valyala/fasthttp#266]
I use `fasthttp.HostClient` to reverse proxy http requests, but it seems don't work when the http method is `CONNECTION`.

Is there any best practice to deal with it?

**Comment by erikdubbelboer** [comment]
Closed in favor of https://github.com/valyala/fasthttp/issues/363

**Comment by lightyen** [comment]
Is there an easy way to reverse proxy websocket like `NewSingleHostReverseProxy` in net/http/httputil?
I usually use other web framework base on net/http like this:
```go
func reverseProxy(target string) gin.HandlerFunc {
	url, _ := url.Parse(target)
	proxy := httputil.NewSingleHostReverseProxy(url)
	return func(c *gin.Context) {
		proxy.ServeHTTP(c.Writer, c.Request)
	}
}
```

**Comment by erikdubbelboer** [comment]
@lightyen https://godoc.org/github.com/valyala/fasthttp/fasthttpproxy#FasthttpHTTPDialer doesn't work for that?

**Comment by lightyen** [comment]
@erikdubbelboer I still didn't find out how to use it, I have created a small [demo](https://github.com/lightyen/proxy-demo) to show what I am thinking about.

**Comment by erikdubbelboer** [comment]
Ah you don't want to connect to a proxy, you're building a reverse proxy. Try looking at this: https://github.com/valyala/fasthttp/issues/64#issuecomment-194880575

**Comment by lightyen** [comment]
@erikdubbelboer Thank you.
