### ISSUE TITLE
Cann't get the value of hash

### ISSUE THREAD

**Issue by jincandev** [valyala/fasthttp#273]
This is my code:
```go
func HandleRouter(ctx *fasthttp.RequestCtx) {
	uri := ctx.URI()
	fmt.Println("Hash:", uri.Hash())
	ctx.Write([]byte("Hello"))
}
```
When I visit the address like this `http://localhost:8081/?id=123&name=456#frame`, but can not receive the  
value of hash. It's returned a blank array `Hash: []`

**Comment by erikdubbelboer** [comment]
This is because browsers don't send the hash to the server. The `Hash` function is only useful when you generate the URL on the server.

**Comment by jcindex** [comment]
Thanks, buddy
