### ISSUE TITLE
Enhancement: Custom Error Handler

### ISSUE THREAD

**Issue by imgurbot12** [valyala/fasthttp#275]
While using this library I noticed there is no way to manage or add a custom response to any errors within the server.

For Example
 Upon a bad request such as this:

> GET / HTTP/1.1\r\n

The returned response is:

> HTTP/1.1 400 Bad Request
> Server: fasthttp
> Date: Thu, 06 Jul 2017 03:38:32 GMT
> Content-Type: text/plain; charset=utf-8
> Content-Length: 26
> Connection: close
> 
> Error when parsing request

Is there any way to customize or modify the response to these errors?

**Comment by erikdubbelboer** [comment]
There is no such thing at the moment but there are thoughts about adding something like this, see https://github.com/valyala/fasthttp/issues/156#issuecomment-417872178.
