### ISSUE TITLE
Benchmarking of handlers.

### ISSUE THREAD

**Issue by PaulRaUnite** [valyala/fasthttp#276]
There is a way to benchmark handlers without running a server?

**Comment by kirillDanshin** [comment]
Please see [gramework](https://github.com/gramework/gramework) tests for example. There are tests for the routing which doesn't run servers.

**Comment by PaulRaUnite** [comment]
@kirillDanshin well, I get it, thank you.

**Comment by kirillDanshin** [comment]
Glad to help you :)
