### ISSUE TITLE
How do I disable sending a content-type header when there is no body?

### ISSUE THREAD

**Issue by Annonomus-Penguin** [valyala/fasthttp#28]
I run this code:

```go
package main

import (
	"github.com/valyala/fasthttp"
)

func main() {
	h := func(ctx *fasthttp.RequestCtx) {

	}
	s := fasthttp.Server{
		Handler: h,
	}
	s.ListenAndServe(":6060")
}
```

but inspect element on Chrome still says `Content-Type: text/plain`. Wouldn't it make sense to not send a `Content-Type` header when there is no content?

**Comment by valyala** [comment]
Currently there is no ability disabling content-type header for empty response. I'll add this functionality to fasthttp till the end of this week.

**Comment by valyala** [comment]
@Annonomus-Penguin , the issue has been fixed.

**Comment by Annonomus-Penguin** [comment]
Thanks!
