### ISSUE TITLE
Expose Conn in RequestCtx

### ISSUE THREAD

**Issue by illotum** [valyala/fasthttp#286]
Problem: Custom Conn implementations might want to expose data and methods to RequestHandlers. RequestCtx already contains the reference to underlying net.Conn, but it is kept private.

Example: Conn that exposes getsockopt() data.

Solution: rename `RequestCtx.c` to `RequestCtx.Conn`, update all affected call sites. This is a small and very contained change.

I will submit a PR if approved.

EDIT. On the second thought, just having an accessor method that yields the reference should be enough.

**Comment by erikdubbelboer** [comment]
@kirillDanshin weren't you going to add a `RequestCtx.UnsafeConn()`. I remember discussing something like this on Telegram I think.

**Comment by illotum** [comment]
This is the last item that block our migration off of the @erikdubbelboer's fork. Is there anything I can do to push it to being included in the next release?

We might start by developing a short doc, maybe part of a CONTRIBUTING.md, that delineates what features are considered "unsafe" and how they should be treated by contributors and consumers. 

Or I might outright submit a PR with the current design. Any preference @kirillDanshin?

**Comment by erikdubbelboer** [comment]
I have just added this method with a big warning. I think the method is so specialistic that people aren't just going to use it if they don't know what they are doing.
