### ISSUE TITLE
Is there any way to get all header key values into a map？

### ISSUE THREAD

**Issue by tianxiaoliang** [valyala/fasthttp#287]

**Comment by SilverRainZ** [comment]
`VisitAll`: https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.VisitAll

**Comment by tianxiaoliang** [comment]
I mean RequestHeader

**Comment by tianxiaoliang** [comment]
Oh I got,thanks

**Comment by gavinchou** [comment]
@tianxiaoliang 
How did you solve the problem? Would you please share the solution? 
Thank you!

**Comment by erikdubbelboer** [comment]
He probably used: https://godoc.org/github.com/valyala/fasthttp#RequestHeader.VisitAll
@tianxiaoliang I think you can close the issue right?

**Comment by gavinchou** [comment]
@erikdubbelboer 
Thank you, I'll try it.
