### ISSUE TITLE
fasthttp.Get() error: too many colons in address

### ISSUE THREAD

**Issue by monopolly** [valyala/fasthttp#290]
I have a valid adress 
**https://user:pass@sub.domain.com:9999/v1/api**

try to get
```fasthttp.Get(nil, "https://user:pass@sub.domain.com:9999/v1/api")```

but I got an error: **too many colons in address**

whats wrong here?
thank you

**Comment by erikdubbelboer** [comment]
I'm afraid `fasthttp` doesn't support `user:pass` in URLs.

**Comment by SaishNaik** [comment]
@erikdubbelboer , is this still not supported? I am getting the same error when using a proxy with 
```fasthttp.HostClient{Addr: proxyUrl}```

Is there any way I can send a parsed url or stop the validation?

**Comment by erikdubbelboer** [comment]
That's not how you use a proxy. I would suggest you look at https://godoc.org/github.com/valyala/fasthttp/fasthttpproxy
