### ISSUE TITLE
Client.go shared library version?

### ISSUE THREAD

**Issue by zfjoy520** [valyala/fasthttp#292]
Dear authors,

Is there a shared library, fasthttp.so for other language bind?

I'm very interested to try shared library bind in other language, such as: Ruby in our applications,
to improve the network cost for more concurrent backend delayed jobs.

I'd tried many ruby http clients, such as libcurl wrappers, pure ruby net/http，but those are not fast enough.

**Comment by illotum** [comment]
Why stop at Go, integrate with libcurl or like. Here's a library I googled up in 10 seconds https://github.com/taf2/curb

**Comment by zfjoy520** [comment]
@illotum 

In my service last version, I just used curb, but it throws Segmentation fault, and the issue I created is here: https://github.com/taf2/curb/issues/324

**Comment by erikdubbelboer** [comment]
It makes no sense to compile this as shared library. Go and Ruby both have their own garbage collectors which won't work together so all data would be copied all the time. This library really only makes sense for pure Go code as it's designed to optimize for this case (almost no allocations).

**Comment by zfjoy520** [comment]
@erikdubbelboer

Thanks. :)
