### ISSUE TITLE
when MaxKeepaliveDuration  is set , there are some worng with request 

### ISSUE THREAD

**Issue by lijinchao** [valyala/fasthttp#293]
Hi,   valyala: 
     i use curl access server , but there is wrong for "curl: (52) Empty reply from server" . And not set  MaxKeepaliveDuration , nothing is not right. I view the source , maybe there is  one bug in code:
func (s *Server) updateReadDeadline(c net.Conn, ctx *RequestCtx, lastDeadlineTime time.Time) time.Time {
	readTimeout := s.ReadTimeout
	currentTime := ctx.time
	if s.MaxKeepaliveDuration > 0 {
		connTimeout := s.MaxKeepaliveDuration - currentTime.Sub(ctx.connTime)
		if connTimeout <= 0 {
			return zeroTime
		}
		**_if connTimeout < readTimeout {
			readTimeout = connTimeout
		}_**
	}

	// Optimization: update read deadline only if more than 25%
	// of the last read deadline exceeded.
	// See https://github.com/golang/go/issues/15133 for details.
	if currentTime.Sub(lastDeadlineTime) > (readTimeout >> 2) {
		if err := c.SetReadDeadline(currentTime.Add(readTimeout)); err != nil {
			panic(fmt.Sprintf("BUG: error in SetReadDeadline(%s): %s", readTimeout, err))
		}
		lastDeadlineTime = currentTime
	}
	return lastDeadlineTime
}
 I think that  " connTimeout < readTimeout " is not right,  it should be that when connTimeout > readTimeout , we update readTimeout. Beacause  connTimeout means remaining time.

And funciton updateWriteDeadline also has this problem.

**Comment by erikdubbelboer** [comment]
The code is correct. `readTimeout` is what is used to set the deadline on the socket. If the amount of keep-alive time that is left, `connTimeout`, is less than `readTimeout` (set to `s.ReadTimeout`) we want to lower `readTimeout` so it doesn't wait until `s.ReadTimeout` but instead waits only the amount of keep-alive time left.

**Comment by erikdubbelboer** [comment]
Also a tip you can wrap a code block in \`\`\`go and \`\`\` to give it Go formatting.

So:
<pre>
```go
a := 1
```
</pre>

becomes:
```go
a := 1
```

**Comment by lijinchao** [comment]
Thanks @erikdubbelboer !!! I mean what you say , but when you only set MaxKeepaliveDuration,  and don't set readtimeout which is init by  zero.
```go
if currentTime.Sub(lastDeadlineTime) > (readTimeout >> 2) {
	if err := c.SetReadDeadline(currentTime.Add(readTimeout)); err != nil {
		panic(fmt.Sprintf("BUG: error in SetReadDeadline(%s): %s", readTimeout, err))
	}
	lastDeadlineTime = currentTime
}
```
lastDeadlineTime variable only define assigned by default at first, so these codes execute , but readTimeout is zero.  when readtimeout is set by user, I think we can consider it as what you say .

**Comment by erikdubbelboer** [comment]
But the function is only called when `ReadTimeout > 0`:
https://github.com/valyala/fasthttp/blob/30e92af08fad62919ff2eae84f530a2f52a547c3/server.go#L1476-L1477

**Comment by lijinchao** [comment]
But that the condition operation  is "||"  and not "&& " . when   MaxKeepaliveDuration > 0  , Even if ReadTimeout < = 0  ,that function is called .

**Comment by erikdubbelboer** [comment]
I see. I guess setting `MaxKeepaliveDuration` but not `ReadTimeout` results in all connections timing out immediately. This is indeed a bug as the documentation says `"By default request read timeout is unlimited."`. There should be an extra check to see if `ReadTimeout` is `0` which means unlimited instead of now.

**Comment by lijinchao** [comment]
Yes, you are right.
