### ISSUE TITLE
cannot get the customized status line

### ISSUE THREAD

**Issue by gpfei** [valyala/fasthttp#295]
Hi,
    It seems that fasthttp only parses the status code, and ignores the status reason.
    So is there any method to get the status reason?
    Thanks!

**Comment by erikdubbelboer** [comment]
No I'm afraid it completely ignores this: https://github.com/valyala/fasthttp/blob/master/header.go#L1639

**Comment by gpfei** [comment]
Yes, I had read the code. So will this feature be considered?

**Comment by erikdubbelboer** [comment]
Closing this issue because of age. If you still need the status line please reopen the issue.
