### ISSUE TITLE
Context support for fasthttp client

### ISSUE THREAD

**Issue by lukashes** [valyala/fasthttp#296]
Hello! I worked with fasthttp client and was surprised context does not supported (supported only timeouts).

Do you have reasons not append this feature? Or you do not have time for that? May be I can try to do this and send PR?

**Comment by erikdubbelboer** [comment]
I'm not sure if contexts are a good fit for fasthttp. They usually result in a lot of heap allocations, something fasthttp tries to prevent at all cost.
