### ISSUE TITLE
PipelineClient asynchronous response feature request

### ISSUE THREAD

**Issue by donovanhide** [valyala/fasthttp#297]
Hi,
I have an interesting problem where I need to make a rapid series of HTTP requests to the same host, each with a nonce which increments with each request and a signature of the request body including that nonce, but I don't want to wait for the response before sending the next request. The nonces must be received by the host in ascending order.

It would be great if PipelineClient had an asynchronous equivalent of the Do() function, where the response was returned over a channel at a later time, but the request gets enqueued immediately. It would allow me to guarantee that the nonces in requests get sent in sequential order and I don't need to block on a response being received. Not sure how the returned error could be handled, maybe bundled in a struct with the response?

Cheers,
Donovan.

**Comment by nahdukesaba** [comment]
Hi, currently I'm assign to do a research according to this issue. Is there any update according to this issue? or have it been answered?

thanks,
Ephraim

**Comment by erikdubbelboer** [comment]
Closing due to age.
