### ISSUE TITLE
Is there a way to define TCP dialing timeout?

### ISSUE THREAD

**Issue by maximus12793** [valyala/fasthttp#299]
`
2017/09/29 03:47:45 dialing to the given TCP address timed out
`

I am creating 500 requests and basically want to download various files at the same time. works fine with the regular net/http package but when call get w/ fasthttp I get the above error. Is there any way around this or configuration I can change to let it at least wait for the response? (or retry it)

**Comment by erikdubbelboer** [comment]
You can provide your own `Dial` func to do this: https://godoc.org/github.com/valyala/fasthttp#Client.Dial

**Comment by maximus12793** [comment]
@erikdubbelboer Do you have a quick toy example of how to do so? I have tried for quite a bit to define my own Dial with a timeout but w/o success. Very new to golang so imagine its simple

thanks!

**Comment by erikdubbelboer** [comment]
```go
c := fasthttp.Client{
  // Other options...
  Dial: func(addr string) (net.Conn, error) {
    return fasthttp.DialTimeout(addr, time.Second)
  },
}
```

**Comment by tsingson** [comment]
fasthttp request via timeout control ?  like this:

```
	client := &fasthttp.Client{
		MaxIdleConnDuration: timeOut,
	}
request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()

	//defer fasthttp.ReleaseRequest(request)
	//	defer fasthttp.ReleaseResponse(response)

	//	request.SetConnectionClose()
	request.SetRequestURI(url)
	request.Header.Add("Accept", "application/json")
	if len(sid) > 0 {
		request.Header.Add("Sid", sid)
	}

	err := client.DoTimeout(request, response, timeOut)

	if err != nil {
		return nil, err
	}
```

**Comment by maximus12793** [comment]
```
package main

import (
	"bufio"
	"fmt"
	"github.com/valyala/fasthttp"
	"log"
	"net"
	"os"
	"sync"
	"time"
)

func grabPage(fastClient *fasthttp.Client, i int, wg *sync.WaitGroup) {
	defer wg.Done()
	_, body, err := fastClient.GetTimeout(nil, "https://en.wikipedia.org/wiki/Immanuel_Kant", time.Duration(time.Second*20))
	if err != nil {
		log.Fatal(err)
	}
	f, err := os.Create(fmt.Sprintf("./data/%d.txt", i))
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	w.Write(body)
}

func main() {
	var wg sync.WaitGroup
	total := 500

	c := &fasthttp.Client{
		Dial: func(addr string) (net.Conn, error) {
			return fasthttp.DialTimeout(addr, time.Second*10)
		},
		MaxConnsPerHost: total,
	}

	wg.Add(total)
	for index := 0; index < total; index++ {
		go grabPage(c, index, &wg)
	}
	wg.Wait()
}

```

ok here is some example bs code. How come this times out 99% of the time w/ the custom Dialer AND is much much slower than just the basic net/http?

**Comment by frxncisjoseph** [comment]
Any update? @maximus12793

**Comment by maximus12793** [comment]
@frxncisjoseph I quit relying on this package since it was much less performant than the basic net/http package for my use case.

**Comment by T200proX7** [comment]
@maximus12793 

i see you define a fasthttp client one time in `main()` and pass it to the goroutine.. is it the correct way? i am new at go but i run this in a go routine function:

```
        req := fasthttp.AcquireRequest()
        defer fasthttp.ReleaseRequest(req)

        req.SetRequestURI(url)
        req.Header.SetMethod("GET")
        req.Header.Add("User-Agent", userAgent)

        //println(req.Header.String())

        resp := fasthttp.AcquireResponse()
        defer fasthttp.ReleaseResponse(resp)

        client := &fasthttp.Client{
                ReadTimeout:         time.Duration(60) * time.Second,
                MaxIdleConnDuration: time.Duration(600) * time.Second,
                Dial: func(addr string) (net.Conn, error) {
                        return fasthttp.DialTimeout(addr, time.Duration(60) * time.Second)
                },
                TLSConfig: &tls.Config{InsecureSkipVerify: true},
        }

        if err := client.DoTimeout(req, resp, time.Duration(60) * time.Second); err != nil {
                return "", err
        }

        bodyBytes := resp.Body()
        html := string(bodyBytes)
```

i guess i open for every go routine call a new client instance? am i doing wrong?

**Comment by erikdubbelboer** [comment]
@T200proX7 the benefit of only using one `fasthttp.Client` is that it can maintain state and can reuse keep-alive connections. If you keep remaking a `fasthttp.Client` it won't be able to use the keep-alive connections already established by another.

**Comment by erkexzcx** [comment]
> ```go
> c := fasthttp.Client{
>   // Other options...
>   Dial: func(addr string) (net.Conn, error) {
>     return fasthttp.DialTimeout(addr, time.Second)
>   },
> }
> ```

If you look at the [official client code example](https://github.com/valyala/fasthttp/blob/master/examples/client/client.go), you can find this code example:
```go
		Dial: (&fasthttp.TCPDialer{
			Concurrency:      4096,
			DNSCacheDuration: time.Hour,
		}).Dial,
```

I've tried using like this, because I wanted to set `Concurrency` and `DNSCacheDuration`:
```go
		Dial: func(addr string) (net.Conn, error) {
			return (&fasthttp.TCPDialer{
				Concurrency:      4096,
				DNSCacheDuration: 5 * time.Minute,
			}).DialTimeout(addr, *flagTimeout)
		},
```

and CPU was constantly increasing. In order to fix it, I had to do this instead:
```go
		Dial: (&fasthttp.TCPDialer{
			Concurrency:      4096,
			DNSCacheDuration: 5 * time.Minute,
		}).Dial,
```

and use like this:
```go
err := httpClient.DoTimeout(req, resp, timeout)
```

So TL;DR would be - it's possible to set tiimeout using `client.DoTimeout` function. :)
