### ISSUE TITLE
fasthttp suppresses TLS related errors

### ISSUE THREAD

**Issue by furiel** [valyala/fasthttp#300]
Commit 982edd5a7ff1b05be3a0e106825f1f92f32bd9dc introduced an exception in the error handling of connections: when fasthttp cannot read any bytes in the beginning of a request/response, fasthttp does not report the error, independently from the root cause. According to the commit message this was necessary to filter the overwhelming 'number of connection reset by peer' messages.

Now I try to implement a service with TLS client authentication. The problem is in case of TLS error, I ran into this behaviour: reader cannot read any bytes, so fasthttp hides the actual error with io.EOF. Though for debugging purposes, it would be important to see what kind of error caused the connection to drop, like invalid cert, signed by wrong authority, expired certs.

Later ed7ca4c631ff1c80a2c9bc34150ba97227ed13b2 introduced a filter mechanism for error logs: LogAllErrors: bool can be used to optionally suppress some connection related issues. But TLS errors are not propagated to this logic. Maybe the error should be propagated further in the reader, and this same variable could be used to filter the TLS related errors as well, if someone is not interested in those. Or alternatively a separate variable could be added.

For me partially reverting 982edd5a7ff1b05be3a0e106825f1f92f32bd9dc was enough for the TLS related error logs to appear: using the patch below. Though it is not PR-ready, as it only fixes the request version. Probably something similar should be done with the response version, but it breaks the TestClientNonIdempotentRetry logic. 

Could you check this issue, and fix that TLS errors could be logged?

```
diff --git a/header.go b/header.go
index fdc4851..0d2dfbe 100644
--- a/header.go
+++ b/header.go
@@ -1331,8 +1331,12 @@ func (h *RequestHeader) tryRead(r *bufio.Reader, n int) error {
 	b, err := r.Peek(n)
 	if len(b) == 0 {
 		// treat all errors on the first byte read as EOF
-		if n == 1 || err == io.EOF {
-			return io.EOF
+		if err == io.EOF {
+			return err
+		}
+
+		if err == nil {
+			panic("bufio.Reader.Peek() returned nil, nil")
 		}
 
 		// This is for go 1.6 bug. See https://github.com/golang/go/issues/14121 .
diff --git a/header_test.go b/header_test.go
index 112faa8..fd195b8 100644
--- a/header_test.go
+++ b/header_test.go
@@ -896,20 +896,6 @@ func TestResponseHeaderFirstByteReadEOF(t *testing.T) {
 	}
 }
 
-func TestRequestHeaderFirstByteReadEOF(t *testing.T) {
-	var h RequestHeader
-
-	r := &errorReader{fmt.Errorf("non-eof error")}
-	br := bufio.NewReader(r)
-	err := h.Read(br)
-	if err == nil {
-		t.Fatalf("expecting error")
-	}
-	if err != io.EOF {
-		t.Fatalf("unexpected error %s. Expecting %s", err, io.EOF)
-	}
-}
-
 type errorReader struct {
 	err error
 }
```

**Comment by erikdubbelboer** [comment]
I created a pull request for these changes: https://github.com/valyala/fasthttp/pull/400

**Comment by furiel** [comment]
@erikdubbelboer thank you!

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/c6fd90e432cc0afd32a031d778e86674af3f010b
