### ISSUE TITLE
[Question] Tips on better performance

### ISSUE THREAD

**Issue by imgurbot12** [valyala/fasthttp#304]
I appreciate your library, and it has helped me out a lot.
What are some tips that you have to improve the performance of my own golang library?

**Comment by kirillDanshin** [comment]
@imgurbot12 just avoid unnecessary memory copy and don't do anything that you can do later when it will be requested. basically, this rules works well with any software written in any language :)
also, see README.md for more tips and tricks

**Comment by erikdubbelboer** [comment]
@kirillDanshin Why answer only this old question and not one of the many new ones or many pull requests? I wish I was a collaborator so I could clean everything up :(

**Comment by erikdubbelboer** [comment]
@kirillDanshin since this repo is no longer maintained I have been maintaining a version with the help of everyone else here: https://github.com/erikdubbelboer/fasthttp. As you can see it's already 57 commits ahead with many important bug fixes and improvements.

**Comment by kirillDanshin** [comment]
@erikdubbelboer I know about your fork, but I can't use any of your and your fork contributors' commits without your written permission and/or PR, so I asking you to create such PR 🙂
