### ISSUE TITLE
Idle connections are kept alive longer than MaxIdleConnDuration

### ISSUE THREAD

**Issue by horgh** [valyala/fasthttp#308]
The `Client` (and other *`Client` types) has an option `MaxIdleConnDuration`. This says it is how long a keepalive connection is kept open after being idle before being closed. I noticed that due to how `connsCleaner()` works, the duration a connection can be idle before being closed is actually up to twice this value.

This happens because `connsCleaner()` checks for idle connections by checking if any have been idle for `MaxIdleConnDuration`, then sleeps for `MaxIdleConnDuration`. If a connection gets opened just after `connsCleaner()` goes to sleep, then afterwards is idle, it won't be closed the next time `connsCleaner()` wakes up. Instead, it will live idle through its next sleep, only being closed at that point.

Why does this matter? In my application I've had situations where I encounter the `ErrConnectionClosed` error. I believe this happens because the client tries to use a connection just as the server closed it (or after the server closed it). The workaround I want is to have the client's idle timeout just below the server's. I wanted to tweak `MaxIdleConnDuration` to something specific and be sure a connection wouldn't be used after it has been idle that duration. Due to the behaviour of this option, it was less obvious how to do so.

Simply documenting the behaviour would probably be okay. Alternatively, we could perhaps check a connection's idle time when we pull it from the pool, rather than in `connsCleaner()` (or perhaps in addition to).

**Comment by erikdubbelboer** [comment]
I agree this is broken and have fixed it in my maintained branch: https://github.com/erikdubbelboer/fasthttp/commit/19d7ccb88cf25bd0cf359175a7b7c56b2ff005e3

**Comment by horgh** [comment]
Thanks! You're awesome!
