### ISSUE TITLE
Open up fasthttp to community?

### ISSUE THREAD

**Issue by illotum** [valyala/fasthttp#309]
I would like to propose @erikdubbelboer, @valyala and all who are interested to create an org to maintain fasthttp under the common supervision.

This would let @valyala to offload some work to the community, while still retaining leadership position when it matters.

(As a side note, it is amusing how this library took off specifically in adtech.)

**Comment by erikdubbelboer** [comment]
I'm up for this. @valyala are you?

**Comment by andrewtw** [comment]
Will be glad to involve as sponsoring and maintaining our global infrastructures for test and production.

**Comment by illotum** [comment]
Unfortunately, I was not able to get response from Aliaksandr neither here nor over email. Should we reach out to VertaMedia the company (see LICENSE)?

**Comment by andrewtw** [comment]
Sure, worth a try.
Who should be the representative for contact?
@illotum @erikdubbelboer

**Comment by erikdubbelboer** [comment]
I have contacted them, I'll post here when I get a response.

**Comment by andrewtw** [comment]
any updates?

**Comment by erikdubbelboer** [comment]
They never responded to me :(

**Comment by kataras** [comment]
Sorry for telling you that but sometimes a single person can make the difference, without @valyala you can't do anything tremendus on any "fasthttp community", no offence really and excuse me for direct tone, he has experience that you can't learn just to mantain the library that's the truth, so be pattient. He has his own reasons for being "offline" and not answering back. If you want to really help try to add http/2 support and then I can say that if I wasn't using [iris](https://github.com/kataras/iris) I could use your fork :)

**Comment by illotum** [comment]
@kataras You're missing the point. No matter what you slap on top of the library in you mother of god huge framework, we're still unable to fix some pretty basic issues in what's already here.

**Comment by tsingson** [comment]
@illotum  and all , if there some basic issues in fasthttp,  please fix it in your fork,  if the 'basic issues' is  in my concern, i will use your fork and appreciate you.

**Comment by illotum** [comment]
This becomes unconstructive, so I'll try to curb it short.

We are doing exactly what @tsington suggested. Unfortunately, flagging every data type as `alias` in the fork is cumbersome and confusing, not to mention it was impossible until v1.9. 

So the community is left fractured into multiple forks, while the newcomers are still leaving in frustration. It's not a healthy open source project.

Most importantly, no one here wishes ill to fasthttp. I did not offer to depose valyala or migrate off to a fork. My offer was to let the community drive the library onwards, with the original author at the head. Please, don't turn this thread into an argument.

**Comment by Azareal** [comment]
I noticed a big surge of activity here, it looks like the baton has been passed or something?

**Comment by illotum** [comment]
Yes @Azareal, @kirillDanshin and @erikdubbelboer are merging the fork into mainline. Hopefully we'll be able to continue development in this repo after they're done. 

Considering it was my issue I'm closing it now.
