### ISSUE TITLE
ReadTimeout 1s results in Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by alxarch** [valyala/fasthttp#311]
When setting Server.ReadTimeout to 1s (presumably also less then 1s), the server will randomly drop incoming connections even on localhost requests. Since I presume that curl does not need a whole second to send a GET request to a local address, this has to do with using ctx.time wich is in turn uses CoarseTime on `Server.updateReadDeadline()` 

https://github.com/valyala/fasthttp/blob/70ceaddfae639b5f0eca290382de18f64d5aa62d/server.go#L1670

**Comment by erikdubbelboer** [comment]
You might want to try https://github.com/erikdubbelboer/fasthttp where I [removed coarsetime](https://github.com/erikdubbelboer/fasthttp/commit/033e10c58522144bd570ff3aa45fbd2f3df917db) because it's speedup is neglectable and apparently can cause issues.

**Comment by countingtoten** [comment]
I have the same issue. Set ReadTimeout or WriteTimeout to `1 * time.Second` and the server consistently kills the connections before they can complete. Setting the timeouts to `2 * time.Second` and this never occurs.

I see the following error messages from different services.

## Postman
```
Object
code
:
"ECONNRESET"
message
:
"socket hang up"
name
:
"Error"
stack
:
"Error: socket hang up↵    at createHangUpError (_http_client.js:253:15)↵    at Socket.socketOnEnd (_http_client.js:345:23)↵    at emitNone (events.js:91:20)↵    at Socket.emit (events.js:185:7)↵    at endReadableNT (_stream_readable.js:974:12)↵    at _combinedTickCallback (internal/process/next_tick.js:74:11)↵    at process._tickCallback (internal/process/next_tick.js:98:9)"
__proto__
:
Object
```

## Chrome
```
This site can’t be reached
The webpage at http://localhost:9000/health might be temporarily down or it may have moved permanently to a new web address.
ERR_SOCKET_NOT_CONNECTED
```

## Safari
```
Safari can’t open the page “‎localhost:9000/health” because the server unexpectedly dropped the connection. This sometimes occurs when the server is busy. Wait for a few minutes, and then try again.
```

**Comment by erikdubbelboer** [comment]
Issue should be fixed, please reopen the issue if it still occurs.
