### ISSUE TITLE
github.com/valyala/fasthttp.decodeArgAppend ：panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by goith** [valyala/fasthttp#312]
**panic: runtime error: invalid memory address or nil pointer dereference**
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45b241]

> goroutine 265214 [running]:
github.com/valyala/fasthttp.decodeArgAppend(0x0, 0x0, 0x8, 0xc4228fcce6, 0x1, 0x11a, 0x41219d, 0xc4211d8f98, 0xc421cdec00)
github.com/valyala/fasthttp/args.go:459 +0x49d
github.com/valyala/fasthttp.(*argsScanner).next(0xc42122da90, 0xc421cdf020, 0x939e01)
github.com/valyala/fasthttp/args.go:431 +0x25d
github.com/valyala/fasthttp.(*Args).ParseBytes(0xc4211d8f98, 0xc4228fcc00, 0x1e8, 0x200)

**Comment by erikdubbelboer** [comment]
Do you have a simple example where this happens?
