### ISSUE TITLE
setting host header does not take effect

### ISSUE THREAD

**Issue by tailnode** [valyala/fasthttp#318]
sorry for my poor  english : )

for example, i want to set request's Host header to "test.com" and send the request to 127.0.0.1:1111.
that is : the server receive request:
```
GET / HTTP/1.1
Host: test.com

```
in this comment(https://github.com/valyala/fasthttp/issues/114#issuecomment-226262070), 
> But the client sends the provided Host header to the server. This allows sending requests to distinct virtual hosts on a single physical host.

so i think fasthttp can do want i want, so i write this code:
```
	req := &fasthttp.Request{}
	resp := &fasthttp.Response{}
	req.SetRequestURI("http://127.0.0.1:1111")
	//req.Header.SetHost("test.com") // no effect too
	req.Header.Set("Host", "test.com")
	fmt.Println("fasthttp.Do result:", fasthttp.Do(req, resp))
```

but Host header is not set to "test.com":
```
GET / HTTP/1.1
Host: 127.0.0.1:1111

```

complete code can run:
```
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/http/httputil"
	"os"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		dumpReq, err := httputil.DumpRequest(r, true)
		checkErr(err)
		fmt.Println("server get request:------\n" + string(dumpReq) + "-------\n")
	}))
	defer testServer.Close()

	req := &fasthttp.Request{}
	resp := &fasthttp.Response{}
	req.SetRequestURI(testServer.URL)
	//req.Header.SetHost("test.com")
	req.Header.Set("Host", "test.com")
	fmt.Println("fasthttp request:--------")
	req.WriteTo(os.Stdout)
	fmt.Println("--------")
	fmt.Println("fasthttp.Do result:", fasthttp.Do(req, resp))
	time.Sleep(time.Second)
}
func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

output of code above:
```
fasthttp request:--------
GET http://127.0.0.1:55473 HTTP/1.1
User-Agent: fasthttp
Host: test.com

--------
server get request:------
GET / HTTP/1.1
Host: 127.0.0.1:55473
User-Agent: fasthttp

-------

fasthttp.Do result: <nil>

Process finished with exit code 0
```

**Comment by erikdubbelboer** [comment]
This is because `.Do()` ends up calling `req.URI()`:
https://github.com/valyala/fasthttp/blob/51bb00256c3cb0a130d470a087a98684ce003065/client.go#L356-L358
Which calls `.parse()`, which in turn resets the host to the one from the URI:
https://github.com/valyala/fasthttp/blob/51bb00256c3cb0a130d470a087a98684ce003065/uri.go#L232-L239
You can see this by doing `req.URI()` before your `req.WriteTo(os.Stdout)` to see how it changes the request.

The best way to avoid this for now is to use a [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient) directly.

**Comment by tailnode** [comment]
@erikdubbelboer thank you for your anwser, after i read the source code, i think there is a bug in https://github.com/valyala/fasthttp/blob/v20160617/http.go#L1025
```
func (req *Request) Write(w *bufio.Writer) error {
	if len(req.Header.Host()) == 0 || req.parsedURI {
		uri := req.URI()
		host := uri.Host()
		if len(host) == 0 {
			return errRequestHostRequired
		}
		req.Header.SetHostBytes(host) // Line 1025
		req.Header.SetRequestURIBytes(uri.RequestURI())
	}
```
in line 1025, host in the uri(`uri.Host()`) will overwrite Host header(`req.Header.SetHostBytes(host)`) even if we set Host header clearly before(`req.Header.SetHost()`)

i think line 2025 shoud change to :
```
		// set Host header to the host in uri only if we not set Host header earlier
		if len(req.Header.Host()) == 0 {
			req.Header.SetHostBytes(host)
		}
```

**Comment by erikdubbelboer** [comment]
I'm afraid doing that will break this test: https://github.com/valyala/fasthttp/blob/498431ce67adb2a2154fb1aad7a35736964c2878/http_test.go#L379
And as the test shows it's currently allowed to change on the return value of `Request.URI()` and expect those changes to be applied to the request. We can't change this behavior now as it might break things for other users.

**Comment by tailnode** [comment]
@erikdubbelboer thank you , i run `TestRequestUpdateURI` and it failed.
you mentioned [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient) in your first comment, i looked the code of HostClient, i don't think it can solve the host header problem because HostClient will call [req.Write()](https://github.com/valyala/fasthttp/blob/v20160617/client.go#L1020) and [set host header to the host in uri](https://github.com/valyala/fasthttp/blob/v20160617/http.go#L1025)
```
func (c *HostClient) doNonNilReqResp(req *Request, resp *Response) (bool, error) {
// ... ...
	err = req.Write(bw)
// ... ...
}
```
```
func (req *Request) Write(w *bufio.Writer) error {
	if len(req.Header.Host()) == 0 || req.parsedURI {
		uri := req.URI()
		host := uri.Host()
		if len(host) == 0 {
			return errRequestHostRequired
		}
		req.Header.SetHostBytes(host) // Line 1025
		req.Header.SetRequestURIBytes(uri.RequestURI())
	}
```

so could you please give me some more detailed explaintion about `HostClient` to set Host header.
thank you.

**Comment by erikdubbelboer** [comment]
This works fine:
```go
package main
  
import (
  "fmt"
  "net/http"
  "net/http/httptest"
  "net/http/httputil"
  "net/url"

  "github.com/valyala/fasthttp"
)

func main() {
  testServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    dumpReq, err := httputil.DumpRequest(r, true)
    checkErr(err)
    fmt.Println("server get request:------\n" + string(dumpReq) + "-------\n")
  }))
  defer testServer.Close()

  req := &fasthttp.Request{}
  resp := &fasthttp.Response{}
  u, _ := url.Parse(testServer.URL)
  client := fasthttp.HostClient{ // You will want to reuse this for other requests to the same host.
    Addr: u.Host,
  }
  req.SetRequestURI("/" + u.Path + "?" + u.RawQuery) // Don't include the host part!
  req.Header.SetHost("test.com")
  client.Do(req, resp)
}

func checkErr(err error) {
  if err != nil {
    panic(err)
  }
}
```
