### ISSUE TITLE
Request.Header.PeekBytes

### ISSUE THREAD

**Issue by goith** [valyala/fasthttp#319]
>  func
> 
>  (s *Controller) GetInfo(ctx *routing.Context) error {
>     var wg sync.WaitGroup
>     wg.Add(1)
>     go getH(ctx, &wg)
>     wg.Add(1)
>     go getH(ctx, &wg)
>     wg.Add(1)
>     go getH(ctx, &wg)
>     wg.Add(1)
>     go getH(ctx, &wg)
>     wg.Wait()
>     return nil
> }
> func getH(ctx *routing.Context, wg *sync.WaitGroup) {                                                                                                                                        
>     defer wg.Done()
>     println(string(ctx.Request.Header.PeekBytes([]byte("X-Real-IP"))))
> }

经测试这个写法有问题，这是不支持这样写吗？报错如下，
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4569ff]

goroutine 21572251 [running]:
vendor/github.com/valyala/fasthttp.(*RequestHeader).PeekBytes(0xc424ecb680, 0xc426093920, 0x9, 0x20, 0x9, 0x20, 0x0)
vendor/github.com/valyala/fasthttp/header.go:1170 +0x79

**Comment by erikdubbelboer** [comment]
Like many things in fasthttp `PeekBytes` is not thread safe, it re-uses a fixed temporary buffer:
https://github.com/valyala/fasthttp/blob/51bb00256c3cb0a130d470a087a98684ce003065/header.go#L1169-L1172
