### ISSUE TITLE
Keep-alive : error 400 when incoming request before connection timeout

### ISSUE THREAD

**Issue by nsagnett** [valyala/fasthttp#321]
After some tests with this server instance : 

```
server := &fasthttp.Server{
		Handler: func(ctx *fasthttp.RequestCtx) {
			ctx.Success("text/plain; charset=utf8", []byte("OK"))
		},
		ReadTimeout:          10 * time.Second,
		WriteTimeout:         10 * time.Second,
		MaxKeepaliveDuration: 10 * time.Second,
	}
```

When request enters just before connection timeout, I see logs like that each time : 

`error when serving connection "{ip}"<->"{ip}": write tcp {ip}->{ip}: i/o timeout`

Any solution for that ?

Thanks

**Comment by erikdubbelboer** [comment]
What exactly do you mean with `enters just before connection timeout`? Just before the Keep-Alive duration? Or just before the read or write finish?

**Comment by nsagnett** [comment]
Just before keep-alive ending.
For example, max keep-alive time is 10 second and send the last request with the same connection at 9.4 second

**Comment by erikdubbelboer** [comment]
Can you try your test on my fork of fasthttp: https://github.com/erikdubbelboer/fasthttp
My fork has a bunch of fixes, also to how keep-alive works.

**Comment by nsagnett** [comment]
I always tried it and it works ! But I don't understand why after switch from "CoarseTimeNow()" to "time.Now()" improves keep-alive management
