### ISSUE TITLE
Benchmark Handlers

### ISSUE THREAD

**Issue by hardcoar** [valyala/fasthttp#322]
is there any idiomatic way to benchmark my handlers?
im more on targeting allocations on often used handlers.

is there anyway i can use an inmemory listener for a server then bench my handlers?
i can't seem to get it right. got a working code using snippets from server_timing_test.go and client_timing_test.go but it seems it allocates too much.

anyone kind enough to provide an idiomatic way to bench mem allocs for handlers? 
THANKS A LOT!

**Comment by illotum** [comment]
You can construct RequestCtx out of public types.The rest should be straightforward:
```go
...
	b.ResetTimer()
	b.ReportAllocs()
	b.RunParallel(func(pb *testing.PB) {
		ctx := getContext()   // Some allocs 
		fillPath(ctx, fillKVs)   // will be difficult
		fillQuery(ctx, fillKVs) // to avoid.
		for pb.Next() {
			h(ctx)
		}
	})
...
```

**Comment by hardcoar** [comment]
@illotum thank you so much for responding!

anyway i was thinking something like a opening a listener and serving a request and closing it afterwards.
any idea how will this be implemented?

**Comment by illotum** [comment]
Have a look at https://godoc.org/github.com/valyala/fasthttp/fasthttputil#InmemoryListener

I still advise to use it only to evaluate fasthttp -- not bench your handlers -- although some benchmarks are available in this repo already.
