### ISSUE TITLE
Mocking and intercepting fasthttp client requests for tests

### ISSUE THREAD

**Issue by bernardolm** [valyala/fasthttp#323]
I seek by approach using **gock**, **httptest**, **fasthttputil**... but I can't find.

With [gock](https://github.com/h2non/gock) I can intercept a "built-in" `net/http` client and his `Transport` layer as you see here https://github.com/h2non/gock#mocking-a-custom-httpclient-and-httproundtripper.

I can't find a exposed `Transport` in fasthttp client to do my intercept.

Anybody knows any way to do this?
Or, @valyala or @h2non intends to implement this?

Thanks

**Comment by themester** [comment]
You can use DialFunc (https://godoc.org/github.com/erikdubbelboer/fasthttp#DialFunc).

**Comment by h2non** [comment]
While it should not be extremely hard supporting fasthttp in gock, I don't have plans to cover it within the package. Probably a new, forked package would be better.

**Comment by jakesyl** [comment]
For anyone coming across this from search, please see #36
