### ISSUE TITLE
How to read from a json request

### ISSUE THREAD

**Issue by inwady** [valyala/fasthttp#324]
You wrote in README:
> r.Body -> ctx.PostBody()

But  **io.ReadCloser** is not equal **[]byte** (those types).

How can I get stream of Body?

**Comment by themester** [comment]
Body of `net/http` package is io.ReaderCloser as you say. Fasthttp implementation returns an array of bytes. It's simply to use with json:
```
json.Unmarshal(ctx.PostBody(), &yourStructure)
```

**Comment by mochadwi** [comment]
If you prefer to use the routing framework instead, forked from fasthttp-routing with JSON support.

https://github.com/jackwhelpton/fasthttp-routing
