### ISSUE TITLE
InmemoryListener can be faster

### ISSUE THREAD

**Issue by bronze1man** [valyala/fasthttp#326]
InmemoryListener can be faster or it can be alloc less object.

The close method of pipeConn do not release the byteBuffer into the pool.So the byteBuffer pool is useless if I only send one message on that connection.

https://github.com/valyala/fasthttp/blob/e5f51c11919d4f66400334047b897ef0a94c6f3c/fasthttputil/pipeconns.go#L195
```
func (c *pipeConn) Close() error {
	return c.pc.Close()
}
```

should be if I do not consider data race between Read() and Close():
```
func (c *pipeConn) Close() error {
	c.pc.Close()
	if c.b!=nil{
		releaseByteBuffer(c.b)
		c.b = nil
	}
	return nil
}
```
I do not know how to recycle the byteBuffer without data race

**Comment by bronze1man** [comment]
I found the not data race and pipeConn.b not memory leak soluation:
https://github.com/valyala/fasthttp/blob/e5f51c11919d4f66400334047b897ef0a94c6f3c/fasthttputil/pipeconns.go#L139
```
func (c *pipeConn) read(p []byte, mayBlock bool) (int, error) {
	if len(c.bb) == 0 {
		if err := c.readNextByteBuffer(mayBlock); err != nil {
			return 0, err
		}
	}
	n := copy(p, c.bb)
	c.bb = c.bb[n:]

	return n, nil
}
```
to 
```
func (c *pipeConn) read(p []byte, mayBlock bool) (int, error) {
	if len(c.bb) == 0 {
		if err := c.readNextByteBuffer(mayBlock); err != nil {
			return 0, err
		}
	}
	n := copy(p, c.bb)
	c.bb = c.bb[n:]
	if len(c.bb) == 0{
		releaseByteBuffer(c.b)
		c.b = nil
		c.bb = nil
	}
	return n, nil
}
```

**Comment by erikdubbelboer** [comment]
I'm not sure if it's really useful to try and speedup `InmemoryListener`. It is only really used for tests which don't have to be super super fast. The change your suggesting doesn't seem clear and I'm afraid it might break something somehow somewhere.
