### ISSUE TITLE
Relative redirects work incorrect

### ISSUE THREAD

**Issue by lukashes** [valyala/fasthttp#328]
According to the doc of method [Redirect](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Redirect) URI may absolute or relative.

But implementation from relative URI does absolute. It may broke redirection if fasthttp under nginx or other reverse-proxy. HTTP standart [allows to use relative URIs ](https://tools.ietf.org/html/rfc7231#section-7.1.2)

Example:
nginx listen: project.com
fasthttp listen: localhost:8080
redirection `Redirect("/path")` may be `Location: http://project:8080/path`

**Comment by themester** [comment]
fasthttp gets the Host parameter of HTTP1.1 header to complete the request path. If you want to redirect to another domain you have to `Redirect("http://project.com/path")`. Am I wrong?

**Comment by lukashes** [comment]
Yes it is works if reverse-proxy correctly configured. But in several cases `Host` from nginx is not the same as domain name of host. What do you think: I should not trust the browser to resolve relative redirect?

**Comment by andrewcurioso** [comment]
The behavior of modifying the `Location` on me, while I can see why it would be helpful, was unexpected to me.

HTTP 1.1 allows relative redirects [1].

As a workaround I'm calling `ctx.SetStatusCode` and `ctx.Response.Header.Set` manually and that is working.

I think it would be nice if there was a way to modify the behavior to not edit the URL but the workaround is only one extra line of code.

[1] https://greenbytes.de/tech/webdav/draft-ietf-httpbis-p2-semantics-17.html#rfc.section.9.5

**Comment by erikdubbelboer** [comment]
I'm not sure I understand, can you show a simple example program to demonstrate the problem?

**Comment by lukashes** [comment]
Hello, sorry I'm too late. I had fasthttp app under nginx and nginx sent us another header `Host` (specific logic and I could not change it). And when I tried to use `Location("/my/path")` I got wrong redirect based on `Host` from nginx: `Location: wrong_host:8080/my/path`. I can't show original problem because I've changed project and do not have ability to check.

**Comment by erikdubbelboer** [comment]
I see. I think we have 2 options here:
1) We change the behavior of `Redirect()` to do a relative URL if the domain or scheme don't change. All browsers can handle relative `Location:` headers (it has been in the spec for 9 years) but it might break some other non browser implementations.
2) We add extra documentation to `Redirect()` to tell people that if they want to do relative redirects they can use the following code:
```go
strLocation = []byte("Location") // Put this with your top level var () declarations.
ctx.Response.Header.SetCanonical(strLocation, "/relative?uri")
ctx.Response.SetStatusCode(fasthttp.StatusMovedPermanently)
```

**Comment by lukashes** [comment]
Good explanation. I vote for the first option, because original behavior is not transparent enough.

**Comment by erikdubbelboer** [comment]
I opted to go for the second option as I think its very risk breaking current behavior and having the users write 3 lines instead of one is not such a big deal.
