### ISSUE TITLE
Cloning a RequestCtx

### ISSUE THREAD

**Issue by peterciccolosc** [valyala/fasthttp#330]
In my endpoint handler, I have a need to create a new RequestCtx object based on the incoming RequestCtx. I do not wish to return the response of this 2nd RequestCtx to the user. Here is my current approach:

```
func EndpointHandler(httpctx *fasthttp.RequestCtx) {
     otherCtx := &fasthttp.RequestCtx{}
     otherReq := fasthttp.AcquireRequest()
     httpctx.Request.CopyTo(otherReq)
     otherReq.ResetBody()
     // get body bytes for the other request here.
     otherReq.AppendBody(bytes)
     otherCtx.Init(otherReq)
     defer fasthttp.ReleaseRequest(&otherCtx.Request)
     
     // call my handleRequest() func in parallel on httpctx and otherCtx
     return  // I believe that the client should get the response from httpctx and the response for otherCtx is discarded.
}
```

Does this seem like a reasonable approach?

**Comment by illotum** [comment]
You should be able to straight away `newctx.Init(&oldctx.Request, ...)`. Init does  a `.CopyTo` under the hood, and that includes a body copy.

See https://github.com/valyala/fasthttp/blob/master/server.go#L1909

Keep in mind the copy will hold no references to the true server or conn.

**Comment by peterciccolosc** [comment]
Thanks.
