### ISSUE TITLE
Write gzipped byte array to response

### ISSUE THREAD

**Issue by lulusc** [valyala/fasthttp#331]
There is an existing function WriteGzipLevel but it takes a bufio.Write instead of a byte array. What's the recommended way to gzip a byte array and add it to the response?

**Comment by themester** [comment]
You can use this function: https://godoc.org/github.com/themester/fasthttp#AppendGzipBytes
```
ctx.Write(fasthttp.AppendGzipBytes(yourByteArray))
```
