### ISSUE TITLE
Server with closed listener still accepts new connections

### ISSUE THREAD

**Issue by veqryn** [valyala/fasthttp#336]
The below benchmark should not fail to run:
```go
package wtf

import (
	"fmt"
	"io/ioutil"
	"math/rand"
	"net"
	"net/http"
	"strconv"
	"testing"
	"time"

	"github.com/valyala/fasthttp"
)

func BenchmarkFastHttpHandler(b *testing.B) {
	fmt.Println("\n\nTest Iterations:", b.N)

	// Get a random number
	rand.Seed(time.Now().UTC().UnixNano())
	r := strconv.Itoa(rand.Intn(1000000))
	fmt.Println("Starting Server:", r)

	// Create listener
	ln, err := net.Listen("tcp", ":8080")
	Must(b, err)

	// Start server
	go func() {
		httpServer := &fasthttp.Server{Handler: func(ctx *fasthttp.RequestCtx) {
			fmt.Println("Hit:", r)
			ctx.SetBody([]byte(r))
		}}
		Must(b, httpServer.Serve(ln))
		fmt.Println("Closed Server:", r)
	}()

	time.Sleep(10 * time.Millisecond) // Let the server start

	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			req, err := http.NewRequest("GET", "http://127.0.0.1:8080", nil)
			Must(b, err)
			resp, err := (&http.Client{}).Do(req)
			Must(b, err)
			if err == nil {
				body, err := ioutil.ReadAll(resp.Body)
				Must(b, err)
				Must(b, resp.Body.Close())
				// Check that we are hitting the correct server
				if string(body) != r {
					b.Fatal("Expected:", r, "Got: ", string(body))
				}
			}
		}
	})
	Must(b, ln.Close())
}

func Must(tb testing.TB, err error) {
	if err != nil {
		tb.Fatal(err)
	}
}
```

Yet I get these results:
```
Test Iterations: 1
Starting Server: 586437
Hit: 586437
Closed Server: 586437

Test Iterations: 100
Starting Server: 608738
Hit: 586437
Hit: 608738
Hit: 586437
Hit: 608738
Hit: 608738
Hit: 608738
Hit: 608738
Hit: 608738
Hit: 608738
Hit: 586437
Hit: 608738
Closed Server: 608738
	pixel_server_benchmark_test.go:52: Expected: 608738 Got:  586437
	pixel_server_benchmark_test.go:52: Expected: 608738 Got:  586437
	pixel_server_benchmark_test.go:52: Expected: 608738 Got:  586437
	pixel_server_benchmark_test.go:52: Expected: 608738 Got:  586437
FAIL
```

The above was the simplest reproducer I could make.  My actual production server fails due to my handler trying to push values into a channel that is closed at the end of the test.

If this isn't an easy fix, is there a workaround to guarantee the server has stopped accepting new connections, that I can do at the end of the benchmark so that the thing can be run?
And/Or can a `Close()` method be created for fasthttp servers, that would solve this?

Golang 1.10.1

Here is a server using the stdlib, which succeeds in this benchmark:
```go
package ok

import (
	"fmt"
	"io/ioutil"
	"math/rand"
	"net"
	"net/http"
	"strconv"
	"testing"
	"time"
)

func Must(tb testing.TB, err error) {
	if err != nil {
		tb.Fatal(err)
	}
}

func BenchmarkHttpHandler(b *testing.B) {
	fmt.Println("\n\nTest Iterations:", b.N)

	// Get a random number
	rand.Seed(time.Now().UTC().UnixNano())
	r := strconv.Itoa(rand.Intn(1000000))
	fmt.Println("Starting Server:", r)

	// Setup server
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(writer http.ResponseWriter, request *http.Request) {
		fmt.Println("Hit:", r)
		_, err := writer.Write([]byte(r))
		Must(b, err)
	})
	srv := &http.Server{
		Addr:    ":8080",
		Handler: mux}

	// Create listener
	ln, err := net.Listen("tcp", ":8080")
	Must(b, err)

	// Start server
	go func() {
		fmt.Println(srv.Serve(ln))
		fmt.Println("Closed Server:", r)
	}()

	time.Sleep(10 * time.Millisecond) // Let the server start

	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			req, err := http.NewRequest("GET", "http://127.0.0.1:8080", nil)
			Must(b, err)
			resp, err := (&http.Client{}).Do(req)
			Must(b, err)
			if err == nil {
				body, err := ioutil.ReadAll(resp.Body)
				Must(b, err)
				Must(b, resp.Body.Close())
				// Check that we are hitting the correct server
				if string(body) != r {
					b.Fatal("Expected:", r, "Got: ", string(body))
				}
			}
		}
	})
	Must(b, srv.Close())
}
```

**Comment by forTWOS** [comment]
I find a situation:
`package wtf

import (
	"fmt"
	"io/ioutil"
	"math/rand"
	"net"
	"net/http"
	"strconv"
	"testing"
	"time"

	"github.com/valyala/fasthttp"
)

func BenchmarkFastHttpHandler(b *testing.B) {
	fmt.Println("\n\nTest Iterations:", b.N)

	// Get a random number
	rand.Seed(time.Now().UTC().UnixNano())
	r := strconv.Itoa(rand.Intn(1000000))
	fmt.Println("Starting Server:", r)

	// Create listener
	ln, err := net.Listen("tcp", ":8080")
	Must(b, err)

	// Start server
	go func() {
		httpServer := &fasthttp.Server{Handler: func(ctx *fasthttp.RequestCtx) {
			fmt.Println("Hit:", r)
			ctx.SetBody([]byte(r))
		}}
		Must(b, httpServer.Serve(ln))
		fmt.Println("Closed Server:", r)
	}()

	time.Sleep(10 * time.Millisecond) // Let the server start

	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			req, err := http.NewRequest("GET", "http://127.0.0.1:8080", nil)
			Must(b, err)
			req.Close = true // keep-alive disabled
			resp, err := (&http.Client{}).Do(req)
			Must(b, err)
			if err == nil {
				body, err := ioutil.ReadAll(resp.Body)
				Must(b, err)
				Must(b, resp.Body.Close())
				// Check that we are hitting the correct server
				if string(body) != r {
					b.Fatal("Expected:", r, "Got: ", string(body))
				}
			}
		}
	})
	Must(b, ln.Close())
}

func Must(tb testing.TB, err error) {
	if err != nil {
		tb.Fatal(err)
	}
}
`

This benchmark run successed.
Excepting that 44 line code, the Code is same to the first benchmark.
I guess there is something wrong with reusing the resource of server.
Until now, I don't find out it.

**Comment by erikdubbelboer** [comment]
This is not a bug in fasthttp.

The reason is that you use `http.Client{}` which will use the global `http.DefaultTransport` which will reuse existing connections. With your fasthttp benchmark you only wait until the listening socket is closed, not until all keep-alive connections are terminated. So your next `BenchmarkFastHttpHandler` call will reuse the exact same `http.DefaultTransport` again, which still has keep-alive connections to the same host from the previous call, which will be reused.

With your net/http benchmark you wait until the server and all its keep-alive connections are closed.

Waiting until all keep-alive connections are closed is something that is currently not possible with fasthttp. So to make the benchmark work you can either set [`Server.MaxRequestsPerConn`](https://godoc.org/github.com/valyala/fasthttp#Server.MaxRequestsPerConn) to `1`. Or you use `(&http.Client{Transport: &http.Transport{DisableKeepAlives: true}}).Do(req)`.

**Comment by illotum** [comment]
valyala/tcplisten Listener specifically enables TCP_REUSEPORT. It will not fail on any modern Linux, and actually all Listeners will be load-balanced by the kernel.

**Comment by erikdubbelboer** [comment]
You close the listener, it's not being listened on anymore? That doesn't mean that existing connections will stop to exist.

**Comment by veqryn** [comment]
So, even if you close a listener, you can still accept traffic on existing connections that were previously established.  And that traffic sent on those ports still reaches the server, despite the listener being closed.

How weird and surprising.

I guess I had thought that traffic was sent to a port, and if the port was being listened to it would be received by the server, and if it wasn't being listened to it would not be received.

If I understand correctly now, it seems listening on a port only has to do with accepting new connections, and has nothing to do with already existing connections or their traffic.

**Comment by erikdubbelboer** [comment]
Yes exactly.
