### ISSUE TITLE
Ignorance of certain redirect status code

### ISSUE THREAD

**Issue by raviqqe** [valyala/fasthttp#338]
[Some redirect status codes are ignored in `doRequestFollowRedirects`](https://github.com/valyala/fasthttp/blob/5116aa64e038d917b3916a74da456c00643ff1e6/client.go#L770). Others should also be followed like `307 Temporary Redirect`.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/erikdubbelboer/fasthttp/commit/de7bb6820e39066002bbc5fe90d09ff408901a89
