### ISSUE TITLE
server do not stop at the same time where fasthttp client request timeout

### ISSUE THREAD

**Issue by goith** [valyala/fasthttp#340]
i use GetTimeout, set 2s timeout in the request client, at the same time , in the sever , that is the respone peer , set sleep(10) (in the way of php+nginx), when to 2s timeout, the client stop,  but the server do not stop at the time.

**Comment by goith** [comment]
and tcp status  still is ESTABLISHED.

**Comment by erikdubbelboer** [comment]
Disabling idle connections is something which is not currently possible with fasthttp I'm afraid. Even when you set `MaxIdleConnDuration` to 0 [it will just use the default value of 10 seconds](https://github.com/valyala/fasthttp/blob/5116aa64e038d917b3916a74da456c00643ff1e6/client.go#L1944).

You could make a pull request to [my active fork of fasthttp](https://github.com/erikdubbelboer/fasthttp) to support this.

**Comment by goith** [comment]
so, current ly my problem is not be resolved.

**Comment by goith** [comment]
@valyala   i want to known  where client  encounter a  timeout err, how  to tell the server,  if not, the server will  be continue  exec.

**Comment by goith** [comment]
i find the reason in the code.

**Comment by xzw123** [comment]
@goith how you resolved your problem, i got the same problem

**Comment by goith** [comment]
do not use GetTimeout, just use Do, and set Client.ReadTimeout
