### ISSUE TITLE
func CopyTo(src *Cookie) act 'CopyFrom'

### ISSUE THREAD

**Issue by forTWOS** [valyala/fasthttp#343]
file cookie.go: CopyTo function name not exactly, and it is unused.
```
// CopyTo copies src cookie to c.
func (c *Cookie) CopyTo(src *Cookie) {
	c.Reset()
	c.key = append(c.key[:0], src.key...)
	c.value = append(c.value[:0], src.value...)
	c.expire = src.expire
	c.domain = append(c.domain[:0], src.domain...)
	c.path = append(c.path[:0], src.path...)
	c.httpOnly = src.httpOnly
	c.secure = src.secure
}
```

**Comment by erikdubbelboer** [comment]
What do you mean with `name not exactly`?

It might be unused in the fasthttp source itself but its an exported function for other people to use.

**Comment by forTWOS** [comment]
'copy to' often means copy self to destination.
The  actual function of the Cookie.CopyTo is copying information from src.
I mean it don't follow the name rules.

**Comment by themester** [comment]
Right... The name CopyTo is a little unexactly. Another datatypes that have CopyTo performs a copy from structure to parsed structure (this is because of (this)[https://github.com/valyala/fasthttp/blob/master/nocopy.go]).

**Comment by erikdubbelboer** [comment]
I agree `CopyTo` should be called `CopyFrom` in this case. But its too late to change now as people might already be using it.

**Comment by forTWOS** [comment]
:)
