### ISSUE TITLE
SetMethod question

### ISSUE THREAD

**Issue by Arnold1** [valyala/fasthttp#345]
Hi,

i have a question:
```
req := fasthttp.AcquireRequest()
fastheader.CopyTo(&req.Header)
req.Header.SetMethod("POST")
```

what happens fastheader already set the method to POST and i call req.Header.SetMethod("POST")?

currently i see the packet beeing sent with method  = "POSTPOST". is that expected?

**Comment by erikdubbelboer** [comment]
[`SetMethod` really overwrites the method](https://github.com/valyala/fasthttp/blob/e5f51c11919d4f66400334047b897ef0a94c6f3c/header.go#L474) and doesn't append like you suggest.

[It also only writes the method to the request just once](https://github.com/valyala/fasthttp/blob/e5f51c11919d4f66400334047b897ef0a94c6f3c/header.go#L1504) so I'm not sure why you are seeing `POSTPOST`.

Could you show me how I can reproduce this?

**Comment by Arnold1** [comment]
@erikdubbelboer i checked the fasthttp code:
```
type RequestHeader struct {
	noCopy noCopy

	disableNormalizing bool
	noHTTP11           bool
	connectionClose    bool
	isGet              bool

	// These two fields have been moved close to other bool fields
	// for reducing RequestHeader object size.
	cookiesCollected bool
	rawHeadersParsed bool

	contentLength      int
	contentLengthBytes []byte

	method      []byte
}

// SetMethod sets HTTP request method.
func (h *RequestHeader) SetMethod(method string) {
	h.method = append(h.method[:0], method...)
}
```

SetMethod takes a string and appends it to a byte, is that an issue?

**Comment by erikdubbelboer** [comment]
It appends it to `[:0]` which means it appends it to an empty slice. It’s done like this to reuse the backing array so there are no additional allocations.

**Comment by Arnold1** [comment]
@erikdubbelboer i try to reproduce the issue. i cloned the repo and set the gopath to root. how can i run the test called TestRequestHeaderSetGet  or testRequestHeaderMethod  inside header_test.go?

**Comment by Arnold1** [comment]
currently use that version of fasthttp, that seems to cause it:
https://github.com/valyala/fasthttp/blob/d42167fd04f636e20b005e9934159e95454233c7/header.go#L463-L466

the append fixed in master branch...

**Comment by themester** [comment]
@Arnold1 https://github.com/valyala/fasthttp/blob/master/header.go#L474

**Comment by Arnold1** [comment]
@themester thats the new tagged version right, which fixes it?

**Comment by themester** [comment]
@Arnold1 is the latest commit. Fixes your problem. Now the `append` appends since h.method[0] to length of method and not appends method to h.method.

**Comment by Arnold1** [comment]
cool
