### ISSUE TITLE
hi , ask questions about args.go

### ISSUE THREAD

**Issue by tbyes** [valyala/fasthttp#350]
func appendArgBytes(h []argsKV, key, value []byte) []argsKV {
	return appendArg(h, b2s(key), b2s(value))  <---- []bytes to string
}

func appendArg(args []argsKV, key, value string) []argsKV {
	var kv *argsKV
	args, kv = allocArg(args)
	kv.key = append(kv.key[:0], key...)               <----string to []byte....
	kv.value = append(kv.value[:0], value...)
	return args
}
step 1. key([]byte) ------> key(string)
step 2. key(string) ------> key([]byte)

I don't quite understand why here is need to convert []byte to string instead of using []byte directly

**Comment by kirillDanshin** [comment]
@tbyes @erikdubbelboer `b2s` is pretty much free and reuses memory. it's just a cheap and simple wrapper :)
