### ISSUE TITLE
how about a larger wokerChanCap?

### ISSUE THREAD

**Issue by listen-lavender** [valyala/fasthttp#351]
var workerChanCap = func() int {
	// Use blocking workerChan if GOMAXPROCS=1.
	// This immediately switches Serve to WorkerFunc, which results
	// in higher performance (under go1.5 at least).
	if runtime.GOMAXPROCS(0) == 1 {
		return 0
	}

	// Use non-blocking workerChan if GOMAXPROCS>1,
	// since otherwise the Serve caller (Acceptor) may lag accepting
	// new connections if WorkerFunc is CPU-bound.
	return 1
}()

Why is the variable  **workerChanCap**  should be 0  or  1?
I wonder whether I can improve performance by a larger wokerChanCap for each worker channel?

**Comment by erikdubbelboer** [comment]
`workerChanCap` is used as the cap for the channel used by 1 worker to accept work. It is not shared between all workers.

When assigning work to the worker the channel is taken out of the `ready` slice and the work is pushed into the channel. When the worker is done the channel is put back into `ready`. Setting the channel cap for something bigger than 1 won't do anything as nothing new will be pushed into the channel until the current work is done. So there can always be at most 1 item in the channel.

The optimization here makes sure that if you have only one processor that the channel is blocked when work is pushed into it so the worker is immediately woken up to start process this work.
