### ISSUE TITLE
Integrating hero template to fasthttp

### ISSUE THREAD

**Issue by otgoohsum** [valyala/fasthttp#353]
i am integrating hero template to fasthttp but localhost:8080 shows just like this

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body> 
<ul> <li> Alice</li></ul>
<ul><li>Bob</li></ul>
<ul><li>Tom</li></ul>
</body>
</html>

but i need localhost:8080 shows just like this

-Alice 
-Bob 
-Tom

problem is html code is shown. My app.go is

package main
import (
"bytes"
"log"
"github.com/shiyanhui/hero/examples/app/template"
"github.com/valyala/fasthttp"
)
func main() {
requestHandler := func(ctx *fasthttp.RequestCtx) {
var userList = []string{
"Alice",
"Bob",
"Tom",
}
buffer := new(bytes.Buffer)
template.UserList(userList, buffer)
if _, err := ctx.Write(buffer.Bytes()); err != nil {
log.Printf("ERR: %s\n", err)
}
}
log.Fatal(fasthttp.ListenAndServe(":8080", requestHandler))
}

**Comment by erikdubbelboer** [comment]
Looks like the HTML in your template is wrong then.

**Comment by kirillDanshin** [comment]
@otgoohsum don't forget to set proper content-type header for your html endpoints
