### ISSUE TITLE
How do I set header?

### ISSUE THREAD

**Issue by otgoohsum** [valyala/fasthttp#354]
How do I set this header code to fasthttp example code? where do i set this?

 w.Header().Set("Content-Type", "text/html")

**Comment by tsingson** [comment]
just return, then fasthttp auto send out header and body...

**Comment by di3663** [comment]
w.Header().Set() -> ctx.Response.Header.Set()

**Comment by frogstair** [comment]
ctx.Response.Header.Set(key, value)

**Comment by LintangWisesa** [comment]
```json
req := fasthttp.AcquireRequest()
req.Header.SetContentType("application/json")
req.Header.Set('key', 'value')
```
