### ISSUE TITLE
An issue with getting parsed path from RequestCtx using ctx.Path

### ISSUE THREAD

**Issue by GilbertGeliba** [valyala/fasthttp#358]
Go version: `go version go1.9.2 windows/amd64`, not really relevant to the issue but anyways.
Fasthttp verison: `v20180529`

See the following code:
```
func MyHandler(ctx *fasthttp.RequestCtx) {
          // Prints /path//info
          fmt.Println(string(ctx.Request.Header.RequestURI()))

          // Pprints /path/info
          fmt.Println(string(ctx.Path()))
}
```

Notice the first statement prints the actual URI which contains continuous double forward slashes , but the second statement omits one of the slashes.

This becomes an issue when I use [fasthttprouter](https://github.com/buaazp/fasthttprouter). I have a handler to handle request from path `/path/:inPathParam/info`, but fasthttprouter is using `ctx.Path()` to [get the current path](https://github.com/buaazp/fasthttprouter/blob/master/router.go#L296). As I know, `/path//info` is valid URL which contains an empty segment, and consequently,  requests to `/path//info` can not be handled by the intended handler and eventually leads to unexpected behaviour or bugs to my application.

**Comment by erikdubbelboer** [comment]
The documentation for `Path()` [says that it returns a normalized path](https://godoc.org/github.com/valyala/fasthttp#URI.Path). I'm guessing valyala did this so it can be used to serve static files as things like `..` get fixed.

I think this is an issue with fasthttprouter. It should use [`PathOriginal()`](https://godoc.org/github.com/valyala/fasthttp#URI.PathOriginal) to match the original unnormalized path. If I were you I would make a pull request there.

**Comment by GilbertGeliba** [comment]
@erikdubbelboer Thank you very much for the tip. I think I am going fix this on fasthttprouterside.

**Comment by savsgio** [comment]
After you create a pull request in fasthttprouter, I think you should try to create your own instance of fasthttprouter like this.
https://github.com/thehowl/fasthttprouter/blob/master/router.go#L145

Set to false RedirectFixedPath.

**Comment by savsgio** [comment]
@GilbertGeliba You're right, it is a bugfix in fasthttprouter.
Create a PR to fix it.

**Comment by savsgio** [comment]
I don't know, if thehowl continues to mantein this repo, I would want to fork buaazp's repo, update with original httprouter and include your bugfix.

I think in a few days, I will do it.

**Comment by savsgio** [comment]
@GilbertGeliba I checked httprouter and fasthttprouter and the two has the same code (regardless of the adaptation for fasthttp), so you can make PR directly to thehowl repo.

**Comment by GilbertGeliba** [comment]
@savsgio Sorry, the link that I used to show the buggy code should points to a different location. Actually, the original fasthttprouter repo is here https://github.com/buaazp/fasthttprouter.
