### ISSUE TITLE
Retrieve all user values

### ISSUE THREAD

**Issue by Raggaer** [valyala/fasthttp#360]
Hello. I want to retrieve all user values from the current `RequestCtx` however I noticed that the list of user values its not exported `userValues` so I can only call `GetUserValue`....

How can I retrieve all the user values without knowing the keys?

Thanks

**Comment by erikdubbelboer** [comment]
You cab use [`VisitUserValues`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.VisitUserValues).
