### ISSUE TITLE
Proxy Support over HTTPS requests

### ISSUE THREAD

**Issue by frxncisjoseph** [valyala/fasthttp#363]
Hello,

I'm currently a minor roadblock whilst using the fasthttp package.

I have done research into proxy support, however, I have only found one outstanding solution as of yet 
This would be using the HostClient and setting the address (as shown in the code example below):

`	
        client = &fasthttp.HostClient{
		Addr: "localhost:24000",
	}
`

However, when I attempt to make outgoing HTTPS requests, they do not work. Instead a non-HTTP request is sent/made. There appears to be no support for http.Transport either to set the proxy through this instance.

Is there any other way to set a proxy and make outgoing HTTPS (GET/POST/etc) requests using FastHTTP?

**Comment by kirillDanshin** [comment]
hi @frxncisjoseph, welcome to the family :)

We can prepare an example for full-featured reverse proxy. I did one a couple of months ago for myself but it may take a while 'cause I need to prepare the sources for example purposes :)

**Comment by frxncisjoseph** [comment]
Hi @kirillDanshin, thank you for the greetings! I would absolutely love that a lot as I'm in the need of guidance, haha. I'd love to be able to make outgoing HTTPs requests under a proxy through `.Get` or other means.

**Comment by erikdubbelboer** [comment]
@frxncisjoseph how would you implement this if you did have something like `net.Transport`? I see https://godoc.org/golang.org/x/net/proxy doesn't support HTTP proxies. For the `net/http` package it seems buildin.

I guess something like this might work? I don't have any HTTP proxy so I can't test it at the moment.
```go
func FasthttpHTTPDialer(proxyAddr string) fasthttp.DialFunc {
	return func(addr string) (net.Conn, error) {
		conn, err := fasthttp.Dial(proxyAddr)
		if err != nil {
			return nil, err
		}

		req := fasthttp.AcquireRequest()
		defer fasthttp.ReleaseRequest(req)

		req.Header.SetHost(addr)
		req.Header.SetMethod("CONNECT")
		// req.Header.Add("Proxy-Authorization", "...")

		if _, err := req.WriteTo(conn); err != nil {
			return nil, err
		}

		res := fasthttp.AcquireResponse()
		defer fasthttp.ReleaseResponse(res)

		// res.SkipBody = true // Maybe this is needed?

		if err := res.Read(bufio.NewReader(conn)); err != nil {
			conn.Close()
			return nil, err
		}
		if res.Header.StatusCode() != 200 {
			conn.Close()
			return nil, fmt.Errorf("could not connect to proxy")
		}
		return conn, nil
	}
}
```
Which you can then use with:
```go
	c := &fasthttp.Client{
		Dial: FasthttpHTTPDialer("localhost:9050"),
	}
```

**Comment by frxncisjoseph** [comment]
@erikdubbelboer That didn't work, sadly. :(

**Comment by erikdubbelboer** [comment]
@frxncisjoseph I have modified my comment to a version that does work for me with https://tinyproxy.github.io/.

**Comment by tsenart** [comment]
@erikdubbelboer: As part of my effort to integrate this library with Vegeta, I found that the Client is missing any built-in support for proxying HTTP(S) requests. For the time being, I'll make it so vegeta uses the standard library client if users specify proxy options, but it'd be great to have this natively supported in fasthttp.

**Comment by erikdubbelboer** [comment]
@tsenart the `FasthttpHTTPDialer` function I commented above doesn't work for you? If it does I guess we could add it to https://godoc.org/github.com/valyala/fasthttp/fasthttpproxy so everyone can use it more easy.

**Comment by tsenart** [comment]
@erikdubbelboer: I haven't tried it. I'm wondering if it's spec compliant? Does it support HTTPS proxying? Would like to see some tests in place for that code, rather than having it be somewhat fringe utility package.

**Comment by erikdubbelboer** [comment]
To be honest I have no idea if it's spec compliant. As I said above I tested the code with https://tinyproxy.github.io/ and it worked. That's all I did. I'm afraid I currently don't have time to test this more and read the spec. You have tried using the code for your use case?

**Comment by Fenny** [comment]
@erikdubbelboer, I tested your example with multiple http/https proxies from multiple providers. All worked fine without errors 👍 

It might be good to add an optional user:pass parser if exist in addr `user:pass@proxy:port`

```go
// ...
req := "CONNECT " + addr + " HTTP/1.1\r\n"
if strings.Contains(proxyAddr, "@") {
  s := strings.Split(proxyAddr, "@")
  c := base64.StdEncoding.EncodeToString([]byte(s[0]))
  req += "Proxy-Authorization: Basic " + c + "\r\n"
}
req += "\r\n"
// ...

**Comment by erikdubbelboer** [comment]
I have added the code to this repo. See: https://github.com/valyala/fasthttp/commit/54df169029f1c9f03afe9c830c9aa4ab0ad025d7 Thanks!

**Comment by SaishNaik** [comment]
@erikdubbelboer , https://github.com/valyala/fasthttp/issues/290#issuecomment-660237876 .
Following  your suggestion here,

I used this to connect to proxy URL

```
c := &fasthttp.Client{
		Dial: fasthttpproxy.FasthttpHTTPDialer(proxyUrl)
}
```

My proxy is of the following form :
`http://username-country-us:password@72.229.28.185:4055`

Now when I use `FasthttpHTTPDialer`, It tries to connect with `72.229.28.185:4055` as proxy , not the whole proxy url I mentioned above. 
If I edit `FasthttpHTTPDialer` to use the exact proxy, get this error again `"error: too many colons in address"`.

Note: this same proxy url works well with standard http client :
```
proxyUrl,_ := url.Parse(proxy)
myClient := &http.Client{
                     Transport: &http.Transport{
                             Proxy: http.ProxyURL(proxyUrl)
                     }
             }
```
any suggestions?

**Comment by erikdubbelboer** [comment]
That's not how authentication works for HTTP proxies. The username and password get turned into a `Proxy-Authorization` header that gets send with the `CONNECT` request. See: https://github.com/valyala/fasthttp/blob/34a61fe63f9b60826bcfb2ad62eafdefbc37ef35/fasthttpproxy/http.go#L34-L36
What you are trying to do doesn't make any sense.

**Comment by karthik-uj** [comment]
We can pass a CA certificate (if available for the proxy server) like so:

```golang
func FastHTTPDialerWithCert(proxy, caCertFile string) fasthttp.DialFunc {
	return func(addr string) (net.Conn, error) {
		var auth string

		// Load CA certificate
		caCert, err := os.ReadFile(caCertFile)
		if err != nil {
			return nil, fmt.Errorf("failed to read CA cert file: %v", err)
		}

		// Create a certificate pool from the CA
		caCertPool := x509.NewCertPool()
		if ok := caCertPool.AppendCertsFromPEM(caCert); !ok {
			return nil, fmt.Errorf("failed to append CA cert")
		}

		// Dial the proxy server
		conn, err := fasthttp.Dial(proxy)
		if err != nil {
			return nil, err
		}

		// Send CONNECT request to proxy
		req := "CONNECT " + addr + " HTTP/1.1\r\n"
		if auth != "" {
			req += "Proxy-Authorization: Basic " + auth + "\r\n"
		}
		req += "\r\n"

		if _, err := conn.Write([]byte(req)); err != nil {
			conn.Close()
			return nil, err
		}

		// Read response from the proxy
		res := fasthttp.AcquireResponse()
		defer fasthttp.ReleaseResponse(res)
		res.SkipBody = true

		if err := res.Read(bufio.NewReader(conn)); err != nil {
			conn.Close()
			return nil, err
		}

		if res.Header.StatusCode() != 200 {
			conn.Close()
			return nil, fmt.Errorf("could not connect to proxy: %s", res.String())
		}

		// Create a TLS connection with the CA cert pool
		tlsConn := tls.Client(conn, &tls.Config{
			RootCAs:            caCertPool,
			InsecureSkipVerify: false,
			ServerName:         strings.Split(addr, ":")[0],
			MinVersion:         tls.VersionTLS12, // Adjust based on the server
		})

		// Perform the TLS handshake
		if err := tlsConn.Handshake(); err != nil {
			tlsConn.Close()
			return nil, fmt.Errorf("TLS handshake failed: %v", err)
		}

		return tlsConn, nil
	}
}
```

You can also turn off SSL certificate verification using the `InsecureSkipVerify` option if a CA certificate is not available. Do not use that on production.
