### ISSUE TITLE
Should i deep copy  Response.Body() ?

### ISSUE THREAD

**Issue by shithappens2016** [valyala/fasthttp#390]
`func test() {
	req := fasthttp.AcquireRequest()
	res := fasthttp.AcquireResponse()

	Do(url, req, res)
      
        body := res.Body() 
       
	fasthttp.ReleaseRequest(req)
	fasthttp.ReleaseResponse(res)

       foo(body)
}`

In case response been reuse and modified

**Comment by kirillDanshin** [comment]
AFAICT no

**Comment by erikdubbelboer** [comment]
Yes the bytes returned by `Response.Body()` will be reused for the next response after you call `fasthttp.ReleaseResponse()`.

**Comment by shithappens2016** [comment]
thanks guys
i'm gonna deep copy it for safety

**Comment by kirillDanshin** [comment]
@erikdubbelboer ReleaseResponse() will free body bites and set body to nil before returning it into the pool

**Comment by erikdubbelboer** [comment]
@kirillDanshin but [it puts the buffer back in `responseBodyPool`](https://github.com/valyala/fasthttp/blob/a58298a3a8e13b8e065c8f2c0710eff2b425b0f4/http.go#L444) to be reused for future requests.
And on reuse it calls [`ByteBuffer.Reset()`](https://github.com/valyala/bytebufferpool/blob/e746df99fe4a3986f4d4f79e13c1e0117ce9c2f7/bytebuffer.go#L110) which as you can see reuses the bytes.

Fasthttp really tries to minimize allocations. Having to allocate a new body for each request would go against that philosophy.

**Comment by kirillDanshin** [comment]
ah, yeah, my fault, sorry, forgot it. thanks @erikdubbelboer
