### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by enderian** [valyala/fasthttp#399]
fasthttp will not compile after the following commit was merged to master:
https://github.com/valyala/fasthttp/commit/044d2a4b405b9a8f177f5a1877491eeaead54342

Compilation error:
`# github.com/valyala/fasthttp
/go/src/github.com/valyala/fasthttp/compress.go:223:8: undefined: acquireFlateWriter
/go/src/github.com/valyala/fasthttp/compress.go:225:2: undefined: releaseFlateWriter
/go/src/github.com/valyala/fasthttp/compress.go:274:60: AppendDeflateBytesLevel redeclared in this block
	previous declaration at /go/src/github.com/valyala/fasthttp/compress.go:207:60
/go/src/github.com/valyala/fasthttp/compress.go:290:64: WriteDeflateLevel redeclared in this block
	previous declaration at /go/src/github.com/valyala/fasthttp/compress.go:222:64
/go/src/github.com/valyala/fasthttp/compress.go:334:48: WriteDeflate redeclared in this block
	previous declaration at /go/src/github.com/valyala/fasthttp/compress.go:231:48
/go/src/github.com/valyala/fasthttp/compress.go:339:44: AppendDeflateBytes redeclared in this block
	previous declaration at /go/src/github.com/valyala/fasthttp/compress.go:236:44`

**Comment by erikdubbelboer** [comment]
Hi, sorry for the inconvenience, this has been fixed now.
