### ISSUE TITLE
Please provide real benchmark data and sever information.

### ISSUE THREAD

**Issue by abacaj** [valyala/fasthttp#4]
The claim for 1m concurrent connections is a pretty big one. Please provide the following:

- What machine was used to handle 1m connections? E.g. m3.2xLarge (8 cpus, 30gb memory)
 - To put it into perspective, node.js can handle 800k connections on a m3.2xLarge.

- Are these just ping/pong connections? If so then the actual throughput/rps is MUCH lower then 1million.
 - G-WAN + Go  can handle Average RPS:784,113 (at least according to their homepage)

- What was the average latency for handling 1m concurrent connections?

- Was there any bottlenecks? E.g. Is it just hardware that is holding this library back from achieving anymore throughput?

Thank you.

**Comment by abacaj** [comment]
My initial tests show there is alot of failures, with only 100 concurrents and 5 req per sec - throughput drops by 8% (unacceptable).

Any idea? Perhaps provide some sample code for me to test with.

<img width="554" alt="screen shot 2015-11-24 at 1 01 10 am" src="https://cloud.githubusercontent.com/assets/7272343/11359111/fc7d3b4e-9246-11e5-8278-65fc9b8f3d26.png">

**Comment by valyala** [comment]
> What machine was used to handle 1m connections?

1M concurrent connections with 100k rps were achieved in production, not in test environment. The server had the following configuration:

* 8xCPU Intel(R) Xeon(R) CPU E5-1630 v3
* 64GB RAM
* 1Gbit network

> Are these just ping/pong connections?

Long-living keep-alive connections are established by video clients all over the world. Clients periodically send event requests to the server over these connections. The server pushes event data to db and sends back just [transparent pixel](http://stackoverflow.com/questions/2570633/smallest-filesize-for-transparent-single-pixel-image). Every client sends an event every 10 seconds on average.

> What was the average latency for handling 1m concurrent connections?

Less than 100ms from the client side.

> Was there any bottlenecks? E.g. Is it just hardware that is holding this library back from achieving anymore throughput?

The main bottleneck was 1Gbit network, so we moved to 10Gbit :)
Also the db (postgres) could handle only 100K inserts per second over a single db connection. So now we push event data over multiple db connections.

We moved to 32-CPU, 128GB RAM, 10Gbit server now. Preliminary results show that the server could handle over 500K rps. Unfortunately we have no 5M concurrent clients yet for testing such a load :(

> Any idea? Perhaps provide some sample code for me to test with.

The rps seems too low for both net/http and fasthttp. Maybe your request handler is too heavy. See sample code [from the pull request to TechEmpower benchmarks](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1765/files).

**Comment by valyala** [comment]
FYI, server process ate 10Gb of RAM when serving 1M concurrent connections, i.e. ~10Kb per connection, including memory fragmentation and [GC overhead](https://blog.golang.org/go15gc).

**Comment by abacaj** [comment]
thanks for the example, it's useful :+1:

**Comment by rkravchik** [comment]
> My initial tests show there is alot of failures, with only 100 concurrents and 5 req per sec - throughput drops by 8% (unacceptable) and siege fails.
> <img alt="screen shot 2015-11-24 at 1 01 10 am" width="554" src="https://cloud.githubusercontent.com/assets/7272343/11359111/fc7d3b4e-9246-11e5-8278-65fc9b8f3d26.png">

@abacaj, perhaps, those errors are caused by small pool and unlimited dialing (see  https://github.com/golang/go/issues/6785)
@valyala, do you have plan to limit max in-flight dialing?

**Comment by erikdubbelboer** [comment]
@rkravchik judging from the first lines of your screenshot you aren't using keep-alive connections and your system/user ran our of available file descriptors or address:port combinations. If you're going to do a benchmark please do it properly.

**Comment by rkravchik** [comment]
@erikdubbelboer it was reply to the first post. Address your message to the proper reciepient.
Moreover, if you will read issue in golang repo you'll find why system may ran out of descriptors due to inproper behaviour.

**Comment by erikdubbelboer** [comment]
@rkravchik I'm so sorry, apparently I wasn't awake yet and didn't notice you were quoting a previous comment.

You can use [`Client.MaxConnsPerHost`](https://godoc.org/github.com/valyala/fasthttp#Client.MaxConnsPerHost) to limit the max in-flight dialing.

**Comment by rkravchik** [comment]
@erikdubbelboer net/http/Transport also have:
MaxIdleConns int
MaxIdleConnsPerHost int
knobs.
But under some circumstances (described in https://github.com/golang/go/issues/6785) there are many Dialing and that's why in go 1.11 have been added one more knob: [MaxConnsPerHost](https://golang.org/src/net/http/transport.go?#L210).

As I can see [in code](https://golang.org/src/net/http/transport.go?#L210) Client.MaxConnsPerHost is a hard limit that caused ErrNoFreeConns error. And there is no way to have such problem that exist in net/http/ below go 1.11. Am I right?

**Comment by erikdubbelboer** [comment]
Yes, [the `MaxConnsPerHost` limit is applied before the connection is being dialed](https://github.com/valyala/fasthttp/blob/e9eca1e4a09ebf127c88d38b371215196c7755b2/client.go#L1225-L1258).

**Comment by rkravchik** [comment]
@erikdubbelboer thank you for your patience.
