### ISSUE TITLE
InMemoryListener freezes on Write() method

### ISSUE THREAD

**Issue by Anon-Penguin** [valyala/fasthttp#41]
I've been trying to use InMemoryListener for a few hours now, and I've pinned the issue down to the fact that it freezes on the `Write()` method of the "server side" connection (the one returned from `Accept()`).

The write method freezes the goroutine and doesn't write anything to the connection.

Same result on both go version go1.5.3 windows/amd64 and go version go1.5.1 windows/amd64. A friend on an unknown version of Go on a Mac had a similar issue with the same exact code.

Thoughts on what's causing this issue?

```go
package main

import (
	"fmt"
	"net"

	"github.com/valyala/fasthttp/fasthttputil"
)

func main() {
	l := fasthttputil.NewInmemoryListener()
	go accept(l)

	c, err := l.Dial()
	if err != nil {
		panic(err)
	}
	defer c.Close()

	b := readOneByte(c)

	if string(b) == "A" {
		fmt.Println("Okay")
	} else {
		fmt.Println("Not Okay")
	}
}

func readOneByte(c net.Conn) byte {
	var b []byte

	n, err := c.Read(b)
	for n == 0 && err == nil {
		n, err = c.Read(b)
	}
	if err != nil {
		panic(err)
	}

	return b[0]
}

func accept(l *fasthttputil.InmemoryListener) {
	c, err := l.Accept() // Should be in a for loop, but doesn't matter here since there's only one connection.
	if err != nil {
		panic(err)
	}
	defer c.Close()

	_, err = c.Write([]byte("A")) // Freezes here.
	if err != nil {
		panic(err)
	}
}
```

**Comment by Anon-Penguin** [comment]
Fixed it myself, sorry. Didn't know the Read call needed the slice to be already created at a fixed size

**Comment by valyala** [comment]
FYI, now [InmemoryListener](https://godoc.org/github.com/valyala/fasthttp/fasthttputil#InmemoryListener) buffers up to 4 Write() calls, so there is no need to issue Read() for each Write() in a concurrently running goroutine - see [pipe.go](https://github.com/valyala/fasthttp/blob/master/fasthttputil/pipe.go) for details.
