### ISSUE TITLE
Fileserver example does not correctly set content-type

### ISSUE THREAD

**Issue by joker042** [valyala/fasthttp#417]
In the fileserver example file `/examples/fileserver/fileserver.go` (and any other code I've tried which uses `fasthttp.FS`), `fasthttp.FS` does not correctly set the content type for the file being served.

It looks like it tries to set the content type at `fs.go:827` after inferring it from the file extension at `fs.go:1154` and but all responses have the header `Content-Type: text/plain; charset=utf-8`

My request headers for `GET /static/1.html` in FireFox:

> Host: localhost:8080
> User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate
> Cookie: _ga=GA1.1.1154405670.1535787993; _gid=GA1.1.1062415716.1536816909
> Connection: keep-alive
> Upgrade-Insecure-Requests: 1
> Pragma: no-cache
> Cache-Control: no-cache

My response headers:
> HTTP/1.1 200 OK
> Server: fasthttp
> Date: Fri, 14 Sep 2018 04:25:33 GMT
> Content-Type: text/plain; charset=utf-8
> Content-Length: 72
> Last-Modified: Fri, 14 Sep 2018 04:15:10 GMT

The contents of 1.html

> `<html>`
> `<body>`
> `This is 1.html`
> `<img src = "mOxsUX.png" />`
> `</body>`
> `</html>`

The only modification I made to the example code was to point it at `./static` instead of the default `/usr/share/nginx/html` 

I also tested it with an absolute path instead of a relative one, same result.

Other Details:
> Kubuntu 18.04
> go version go1.10.1
> FireFox version 62.0 (64-bit)

(My first github issue, so please let me know if I've missed some info or etiquette)

Jeremy.

**Comment by erikdubbelboer** [comment]
You are right, this seems to have been broken in https://github.com/valyala/fasthttp/commit/6025a4a41c72c64db7d367b68dd2a8019bcddf97 because of the stupid behavior of `ResponseHeader.ContentType()` always returning a default content type if nothing is set.
I have a fix in the pipeline but it depends on https://github.com/valyala/fasthttp/pull/407 which needs to be merged first. This will probably happen any day now.

**Comment by joker042** [comment]
Cool, thanks for the update.
