### ISSUE TITLE
Fasthttp goroutine leak problem

### ISSUE THREAD

**Issue by wangtaoX** [valyala/fasthttp#419]
Hi, all:

We faced a goroutine leak problem in our production environment last day when QPS increased from 30K to 92K on single server，Is any reason that may cause such a  goroutine leak problem?

**Comment by erikdubbelboer** [comment]
No that I'm aware. Can you use [pprof](https://github.com/valyala/fasthttp/blob/master/pprofhandler/pprof.go) and get a dump of all the goroutines so we can see what they are doing?

**Comment by wangtaoX** [comment]
ok, thank you @erikdubbelboer , I will try my best to reproduce this problem and get the goroutine pprof.

**Comment by wangtaoX** [comment]
It is a cache service used internally by our service, the server has 64GB memory and Intel E5 cpu with 48 cores.

**Comment by wangtaoX** [comment]
Can not  reproduce this problem right now,  i will reopen this issue if we can reproduce it.
