### ISSUE TITLE
Document Corner cases of HTTP protocol

### ISSUE THREAD

**Issue by mdedetrich** [valyala/fasthttp#420]
I am currently evaluating whether to use fasthttp (starting a new project in Go), and I came across this section in the README.md

> net/http handles more HTTP corner cases.

Would it be possible to document what precisely these corner cases are and whether the result of the corner cases being there is due to completely optimizing for performance (i.e. a deliberate design decision) or whether its due to fasthttp not having as much usage as net/http and so not all of the corner cases have been discovered

**Comment by erikdubbelboer** [comment]
To be honest I'm not sure what the current corner cases are that `net/http` handles but `fasthttp` doesn't. Each time an issue is made about a corner case we fix it.

Of course `net/http` has many more users with many more use cases which means it's much more tested and robust.

**Comment by mdedetrich** [comment]
Okay thats cool, I just wanted to know whether these corner cases are deliberate (due to absolutely optimizing for performance), it seems like its not.

Thanks for letting me know!
