### ISSUE TITLE
Server Sent Events

### ISSUE THREAD

**Issue by ohenepee** [valyala/fasthttp#422]
Are Server Sent Events supported? If yes, is there an example I can follow?

**Comment by erikdubbelboer** [comment]
Sure, here is a simple self explanatory example:
```go
package main
  
import (
  "bufio"
  "bytes"
  "fmt"
  "time"

  "github.com/valyala/fasthttp"
)

func handler(ctx *fasthttp.RequestCtx) {
  if bytes.HasPrefix(ctx.Path(), []byte("/source")) {
    ctx.SetContentType("text/event-stream")
    ctx.SetBodyStreamWriter(func(w *bufio.Writer) {
      for {
        w.Write([]byte(fmt.Sprintf("data: %s\n\n", time.Now())))
        w.Flush()

        time.Sleep(time.Second)
      }
    })
  } else {
    ctx.SetContentType("text/html")
    ctx.SetBody([]byte(`
      <!doctype html>
      <body>
      <div id=d></div>
      <script>
        var source = new EventSource('http://localhost:8080/source');

        source.onmessage = function(e) {
          document.getElementById('d').innerHTML = e.data;
        };
      </script>
  `))
  }
}

func main() {
  if err := fasthttp.ListenAndServe(":8080", handler); err != nil {
    panic(err)
  }
}
```

**Comment by ohenepee** [comment]
Thanks a lot

**Comment by nikarh** [comment]
Hi, I am trying to use your example in my application, but it looks like in case a client closes connection, a go routine processing SSE still runs, causing a memory leak. Is there any way to handle that correctly? Thank you!

**Comment by erikdubbelboer** [comment]
That's because fasthttp uses a worker pool. So the next time a client connects it will reuse the goroutine. So this is not really a memory leak and the overhead of one goroutine is very small.

**Comment by frederikhors** [comment]
@erikdubbelboer how to detect if a client is disconnected?

**Comment by erikdubbelboer** [comment]
@frederikhors I have updated the example above to stop the loop when the client disconnects. You can detect this from `Flush` returning an error.

**Comment by frederikhors** [comment]
It is not immediate, why? Can I reduce the timeout time?

**Comment by erikdubbelboer** [comment]
Not that I'm aware. The server sends the next payload and then waits on the browser to confirm this (at the TCP layer). When the user has closed the page the browser might still keep listening on the connection for a while. Only when the browser closes the connection and the browser OS tells the server OS the connection is closed, and the server OS tells your server  the connection is closed is when fasthttp can know. This can all take some time.

**Comment by erikdubbelboer** [comment]
You can reduce that `time.Second` if you want to send data more often. It will detect a disconnect up to a second faster. If you remove the timeout completely you'll know the fastest. But it also means you'll use all your bandwidth to send updates as fast as possible.

**Comment by ablearthy** [comment]
@erikdubbelboer 
> Only when the browser closes the connection and the browser OS tells the server OS the connection is closed, and the server OS tells your server the connection is closed is **when fasthttp can know**.

It is possible to create the callback when the connection is closed?

**Comment by erikdubbelboer** [comment]
You can do this yourself, in the example above just replace `println("client disconnected")` with your callback.

**Comment by ablearthy** [comment]
> You can do this yourself, in the example above just replace `println("client disconnected")` with your callback.

Oh... I mean is it possible to know _immediately_ when the connection is closed? (the example above doesn't do it even if I run `curl -iv http://localhost:3000/sse`)
