### ISSUE TITLE
Content-Length: 0 in GET method

### ISSUE THREAD

**Issue by saniapro** [valyala/fasthttp#423]
I try to dump all request headers using VisitAll() and see that every header starts with 
Content-Length: 0
This request header is not sent by any known browser on GET request.

Maybe you should ignore this header for GET requests or then length is 0?

**Comment by erikdubbelboer** [comment]
I agree but I'm afraid we can't just change behavior like this. There might be people depending on it. When https://github.com/valyala/fasthttp/pull/378 gets merged you will be able to get the actual headers the client sent instead of what fasthttp makes out of it.
