### ISSUE TITLE
what do I need set if I want receive max response body 1MB

### ISSUE THREAD

**Issue by imfht** [valyala/fasthttp#429]
noticed there is a `MaxResponseBodySize` in [client.go](https://github.com/valyala/fasthttp/blob/d7688109a57b030752c3d45b1a95cb7d6b8eee96/client.go#L564) but no document talk about it.
Someone give me a help?

**Comment by erikdubbelboer** [comment]
You set it to the number of bytes. So in your case `1024*1024`.
