### ISSUE TITLE
Switching from Iris now to fasthttp directly but chatroom / doc materials much lesser. 

### ISSUE THREAD

**Issue by unisqu** [valyala/fasthttp#434]
Do we have a chatroom for fasthttp? the example docs are truly much lesser. I'm using  "github.com/buaazp/fasthttprouter"

and i cant seem to find how to read JSON post input and write JSON output "elegantly".

my problem is with JSON post input. can't seem to accept post data... i've tried

                qUD := &qdb.GD{}
                if err := json.Unmarshal(ctx.PostBody(), &qUD); err != nil {                        
                          JSONWrite(ctx,200,err)
                          fmt.Printf("%s\n",ctx.PostBody())

                }
Gotten

                  {"Offset":2}

copied this online for JSONWrite 
```
func JSONWrite(ctx *fasthttp.RequestCtx, code int, obj interface{}) {
        ctx.Response.Header.SetCanonical(strContentType, strApplicationJSON)
        ctx.Response.SetStatusCode(code)
        if err := json.NewEncoder(ctx).Encode(obj); err != nil {
                ctx.Error(err.Error(), fasthttp.StatusInternalServerError)
        }
}
```

I just switched from Iris. (everything did work in Iris though... just that too many people wrote bad things about it and the performance is 25% lesser than what fasthttp and fasthttprouter is offering.

**Comment by tsingson** [comment]
some code :
```
type (

	ReqEmsPayload struct {
		Mdc string `json:"mdc"`
		Apk string `json:"apk"`
		Tid string `json:"tid"`
	}
)


func postHandler( ctx *fasthttp.RequestCtx) {

     // handle POST json input 

	reqObj := new(ReqEmsPayload)
	body := ctx.PostBody()
	err1 := json.Unmarshal(body, &reqObj)
      if err1 != nil {
         ctx.Error(" json Post Payload is error", 500)
        return 

      }

    // handle OUTPUT
   
     jsonBody, err2 := json.Marshal(reqObj)

    if err2 != nil {
         ctx.Error(" json marshal fail", 500)
        return 

      }

	ctx.SetContentType("application/json; charset=utf-8")   //  *************
	ctx.SetStatusCode(200)
	ctx.Response.SetBody(   jsonBody)
	return

}

```

**Comment by tsingson** [comment]
BTW, suggest this  "github.com/json-iterator/go"  for json Unmarshal / Marshal , it's fast then std json lib.

**Comment by erikdubbelboer** [comment]
Maybe your body is gzipped in case you need something like:
```go
	var body []byte
	if bytes.Equal(ctx.Request.Header.Peek("Content-encoding"), strGzip) {
		var err error
		body, err = ctx.Request.BodyGunzip()
		if err != nil {
			panic(err)
		}
	} else {
		body = ctx.PostBody()
	}
```

To really find your problem we need to know a lot more, like what is `qdb.GD` and where is the `{"Offset":2}` from? I don't see any `Offset` in the code you shared.

**Comment by unisqu** [comment]
Thanks for the long awaited reply. I really wish there are more working examples for "useful" "real-life" scenario for API writing, afterall fasthttp is really very well suited for rest style api.

i'll research more into "github.com/json-iterator/go" etc first before i comment further. thanks.

**Comment by unisqu** [comment]
any real life working example of fasthttp for rest style api json?

thx in advance.

**Comment by unisqu** [comment]
also of course if there's like a chatroom on telegram etc to ask questions like these will be best...

**Comment by unisqu** [comment]
Can anyone try this?

https://pastebin.com/raw/wP5vztH1

use Postman

127.0.0.1:8080/1/u

whatever is posted, returned
{"Offset":2}

**Comment by kirillDanshin** [comment]
@unisqu currently we use gramework's telegram [chat](https://t.me/gramework) for internal communication, you can join there to get support :)
can you please provide a `fetch` request example, which breaks your handler? works for me well with `fetch('/1/u', { method: 'POST', body: '{"age": 1}' })`

P.S. I'd rewrite your example to this:
```go
package main

import (
	"github.com/gramework/gramework"
	"github.com/gramework/gramework/metrics"
)

type User struct {
	U string `json:"username"`
	F string `json:"firstname"`
	L string `json:"lastname"`
	C string `json:"city"`
	A int    `json:"age"`
}

func main() {
	app := gramework.New()

	metrics.Register(app, "example")

	app.POST("/1/u", func(ctx *gramework.Context) (interface{}, error) {
		var qUD User
		if err := ctx.UnJSON(&qUD); err != nil {
			ctx.Logger.WithError(err).Error("could not unmarshal request body")
			return nil, err
		}

		return qUD, nil
	})

	app.ListenAndServe()
}
```

it gives you additional preconfigured logging, fast server's health-check on startup, integrated prometheus metrics, heroku's `PORT` environment and `-bind` flag support and full fasthttp compatibility in still 13 lines shorter. basically, gramework is a bunch of optimized shortcuts and features based on a [legally embedded fasthttprouter](https://github.com/buaazp/fasthttprouter/issues/26) with some optimizations

**Comment by unisqu** [comment]
ok. i'm sold on gramework. hope u can keep it minimal / simple and focus on speed / memory as mentioned. seemed simpler (like iris). should be ok.

thx

**Comment by erikdubbelboer** [comment]
This works fine:
```sh
$ curl -H "Content-Type: application/json" -d '{"username":"foo","firstname":"bar","lastname":"baz","city":"Amsterdam","age":20}' localhost:8080/1/u
{"username":"foo","firstname":"bar","lastname":"baz","city":"Amsterdam","age":20}
```
But when I send invalid JSON I get the same error as you:
```sh
$ curl -H "Content-Type: application/json" -d 'x' localhost:8080/1/u
{"Offset":1}
```
This is because `json.Unmarshal` returns a [`json.SyntaxError`](https://golang.org/pkg/encoding/json/#SyntaxError) which has only one exported field named `Offset`.

**Comment by unisqu** [comment]
@erikdubbelboer Just realised I made a mistake with the Postman settings.
sticking to using fasthttprouter for now. need every extra speed for what I'm doing.
Thanks.

**Comment by erikdubbelboer** [comment]
Keep in mind that fasthttprouter does at least 1 allocation per request: https://github.com/buaazp/fasthttprouter/issues/33 So if you really want max performance and you don't really need a router the don't use one. For a simple router we just use:
```go
	path := ctx.Path()

	if bytes.Equal(path, slashBid) {
		bidHandler(ctx)
	} else if bytes.Equal(path, slashWin) {
		winHandler(ctx)
	} // etc...
```

**Comment by hiqbn** [comment]
given this code, slashBid := []byte("/")
or is slashBid something else?
?


path := ctx.Path()

	if bytes.Equal(path, slashBid) {
		bidHandler(ctx)
	} else if bytes.Equal(path, slashWin) {
		winHandler(ctx)
	} // etc...

**Comment by erikdubbelboer** [comment]
`slashBid := []byte("/")` yes, somewhere at the top scope of your file so it doesn't get reassigned every function call.
