### ISSUE TITLE
Is it support http2.0?

### ISSUE THREAD

**Issue by getkokomi** [valyala/fasthttp#435]

**Comment by kirillDanshin** [comment]
@dgrr working on https://github.com/fasthttp/http2

**Comment by getkokomi** [comment]
@kirillDanshin  How to use it?

**Comment by dgrr** [comment]
@getkokomi it is not ready yet.

**Comment by erikdubbelboer** [comment]
Closing this in favor of the older same issue: https://github.com/valyala/fasthttp/issues/144
