### ISSUE TITLE
how to reverse proxy dynamically?

### ISSUE THREAD

**Issue by unisqu** [valyala/fasthttp#436]
i saw this
https://github.com/valyala/fasthttp/issues/64

but i cant figure out how to dynamic matching reverse proxy

e.g. if domainName = "abc.com" {
proxy = "123.123.123.123"
}else{
proxy = "1.1.1.1"
}

can anyone help?

**Comment by erikdubbelboer** [comment]
Either you create a `fasthttp.HostClient` per domain or you change the `fasthttp.HostClient.Addr` depending on if you need to use the client concurrently or not.
