### ISSUE TITLE
ConnState hook for StateActive not working

### ISSUE THREAD

**Issue by alxarch** [valyala/fasthttp#441]
It seems that the ConnState hook is not called for a connection transitioning to StateActive. The hook call is inside an if that never evaluates to true since `RequestHeader.tryRead()` discards the header bytes before returning thus `if r.Buffered() > 0` is always `false` for requests with no body.

**Comment by alxarch** [comment]
Seems to be working OK with `if err == nil` [here](https://github.com/valyala/fasthttp/blob/afcef43292699fa1c35646db8e6423bc4417d4b3/server.go#L1813) but i don't know if there are corner cases where a non nil `err` results in an non active connection.

**Comment by erikdubbelboer** [comment]
I think only setting it `if err == nil` should work. [As you can see below](https://github.com/valyala/fasthttp/blob/afcef43292699fa1c35646db8e6423bc4417d4b3/server.go#L1826-L1833) it will always break out of the request loop if `err != nil` so it will never transition into an active connection state if `err != nil`.

**Comment by erikdubbelboer** [comment]
Should be fixed in https://github.com/valyala/fasthttp/commit/1b3ac0ccc9a9a57dd7dd0876a12a0d8e27b06582
