### ISSUE TITLE
Error: "too many open files" for 

### ISSUE THREAD

**Issue by sjke** [valyala/fasthttp#443]
I have one very unpleasant issue with the fasthttp :
There is a "highly loaded" server that stops processing requests after 5-10 minutes (about 5000 requests per minute) with error:
```Temporary error when accepting new connections: accept tcp4 IP:PORT: accept: too many open files```

Tried 2 ways to start the (with standard `ListenAndServe` and with custom Server options (disabled Keepalive, custom timeouts and closing connection on handers) but isn't works.

```golang
func HTTPServer() {
	listenAddress := strings.Join([]string{os.Getenv("SERVER_IP"), os.Getenv("SERVER_PORT")}, ":")
	log.Printf("Starting server on %q", listenAddress)
	go func() {
		if err := server.ListenAndServe(listenAddress, CustomModelHandler); err != nil {
			log.Fatalf("error in ListenAndServe: %s", err)
		}
	}()
}


func CustomModelHandler(ctx *server.RequestCtx) {
	var customModel models.CustomModel
	err := json.Unmarshal(ctx.PostBody(), &customModel)
	if err != nil {
		ctx.Error(err.Error(), server.StatusBadRequest)
		return
	}
        // ....
	// some actions with customModel
        // ....
	if updated {
		ctx.SetStatusCode(server.StatusOK)
	} else {
		ctx.SetStatusCode(server.StatusCreated)
	}

	defer ctx.Request.Reset()
	defer ctx.Request.SetConnectionClose()
}
`

Any ideas how to fix it?

**Comment by kirillDanshin** [comment]
`ulimit -Hn 1000000; ulimit -n 1000000` before starting the service. you can also find systemd service variables that will setup this for you

**Comment by sjke** [comment]
@kirillDanshin thx, but this isn't a fix for the issue (by increasing the limits, I'm just "delaying the inevitable"). I have to understand the reason: "Why it happens" and "How can I prevent it"

**Comment by sjke** [comment]
I figured out the problem in `TCPListener`.
Close!

**Comment by kirillDanshin** [comment]
@sjke to be precise, you should check that your listener is correctly closing connections (if you use custom listener), decrease TTL for your keep alive connections (or disable keep-alive) and set those limits to a max number of opened connections at once.

basically, you just found a common issue, when you got 4096 opened connections and tried to open 4097th, but it can't work due to ulimits. each socket (including client-server connections) in linux are files, so to serve more connections, you'll need higher limits and always correctly handle connection close.

**Comment by savsgio** [comment]
@sjke Could you explain the exactly error? please

**Comment by rof20004** [comment]
@savsgio Did you find a solution?

**Comment by savsgio** [comment]
Oh no, I would like to know more about this error, I meant

**Comment by savsgio** [comment]
No!, but @kirillDanshin has the reason, I think it's very probably the error is by the listener.

**Comment by rof20004** [comment]
@savsgio thanks for answer, but he not explained how did... sad!

**Comment by savsgio** [comment]
I think it too! :confused:

**Comment by erikdubbelboer** [comment]
@rof20004 are you having an issue with `too many open files` as well?

**Comment by rof20004** [comment]
@erikdubbelboer Sometimes yes, sometimes no.

My ulimit is 100000(one hundred thousand).

My test is with vegeta.

```
echo "GET http://localhost:8080" | vegeta attack -rate=20000 -duration=30s | vegeta report
```

My code is this:
```
package main

import (
	"fmt"
	"log"

	"github.com/buaazp/fasthttprouter"
	"github.com/valyala/fasthttp"
)

func Index(ctx *fasthttp.RequestCtx) {
	fmt.Fprint(ctx, "Welcome!\n")
}

func main() {
	router := fasthttprouter.New()
	router.GET("/", Index)
	log.Fatal(fasthttp.ListenAndServe(":8080", router.Handler))
}
```

**Comment by erikdubbelboer** [comment]
Running this as root on my macbook I only get:
```
$ echo "GET http://localhost:8080" | sudo vegeta attack -rate=20000 -duration=30s | vegeta report
Password:
	

Requests      [total, rate]            600000, 20000.55
Duration      [total, attack, wait]    29.999536238s, 29.999175s, 361.238µs
Latencies     [mean, 50, 95, 99, max]  256.769µs, 136.854µs, 378.63µs, 1.195158ms, 81.91395ms
Bytes In      [total, mean]            5396796, 8.99
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  99.94%
Status Codes  [code:count]             0:356  200:599644  
Error Set:
Get http://localhost:8080: dial tcp: lookup localhost: no such host
```

The only error there has nothing to do with fasthttp. Could it be that you're running your test as a user that runs out of file descriptors?

**Comment by rof20004** [comment]
@erikdubbelboer Thanks, maybe my user had a limit or I not setted ulimit correctly, I tested yesterday after set ulimit to one hundred again and no errors happens.

**Comment by savsgio** [comment]
@rof20004 I recomend you to use https://github.com/fasthttp/router also.

**Comment by rof20004** [comment]
@savsgio Thanks, I will use it.
