### ISSUE TITLE
Is it support http2.0?

### ISSUE THREAD

**Issue by Linvas** [valyala/fasthttp#45]
as title

**Comment by ernado** [comment]
> Are there known net/http advantages comparing to fasthttp?

> Yes:

> net/http supports HTTP/2.0 starting from go1.6.

No it does not.

**Comment by valyala** [comment]
Fasthttp doesn't support HTTP/2.0 at the moment, but it is in [TODO](https://github.com/valyala/fasthttp/blob/master/TODO).

**Comment by nkev** [comment]
Are there any plans to support HTTP2 soon? Go 1.8 will support HTTP2 push in Feb 2017. We would love to see this in fasthttp.

**Comment by dapchen** [comment]
Is there any plan to support HTTP2 soon?

**Comment by nkev** [comment]
It's been on the "todo" list for almost a year now, so we've moved on back to the standard library.

**Comment by dapchen** [comment]
Thanks @nkev for the information.  
We love the performance that fasthttp brings. However, the lack of HTTP2 support prevents us from adopting it.

**Comment by nkev** [comment]
Yes, same. It's still the best choice for APIs though, but I think the lack of HTTP2 is a deal breaker for serving web pages, despite the speed.

**Comment by goodwink** [comment]
HTTP/2 support is a blocker for adoption for me also since I need support for push.
