### ISSUE TITLE
Return headers even for too large body

### ISSUE THREAD

**Issue by digidis** [valyala/fasthttp#456]
Another issue related to ErrBodyTooLarge. It would be nice to still get the headers back even if the body is too large? Now they are cleared.

https://github.com/valyala/fasthttp/blob/8f4c5d5d1dbb772a29f059645f0f03a4556c1dad/http.go#L988-L992

**Comment by erikdubbelboer** [comment]
@kirillDanshin what do you think? Removing the `resp.Reset()` doesn't really break backwards compatibility as people shouldn't expect anything in case of an error. Removing it also doesn't break any tests.

I vote we remove this and document that in case of an error the response headers that could be parsed will be returned.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/65955d6208bfd6efe330d8c37b18d6402cb1c91b
