### ISSUE TITLE
Allow to return user-specific responses even on fasthttp errors

### ISSUE THREAD

**Issue by derElektrobesen** [valyala/fasthttp#457]
If we have a limit for the request body and this limit exceeded, fasthttp server returns default error:
```
$ curl -gvv 'http://127.0.0.1:9998/' -H 'Content-Length: 127890' -X POST
* About to connect() to 127.0.0.1 port 9998 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9998 (#0)
> POST /batch HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9998
> Accept: */*
> Content-Length: 127890
>
< HTTP/1.1 400 Bad Request
< Server: fasthttp
< Date: Fri, 09 Nov 2018 09:55:39 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 26
< Connection: close
<
* Closing connection 0
Error when parsing request
```

We need to redeclare this response: content type should be in JSON format: there are a lot of old mobile applications (for older platforms which are not supported but used by many users) which could crash when unexpected response comes.

**Comment by erikdubbelboer** [comment]
This is now be possible since https://github.com/valyala/fasthttp/commit/e771b6fe43f02a3abec94adf6100ea4243bd12d6

**Comment by derElektrobesen** [comment]
Thanks ^^
