### ISSUE TITLE
ParseUint of (1<<63) - 1 returns error

### ISSUE THREAD

**Issue by saniapro** [valyala/fasthttp#461]
Do you have plans to fix 18 chars for positive 63-bit uint?

const maxIntChars    = 18

I don't want to invent bike to parse number 9223372036854775807 or 7628839940808288973, for example, which is correct 63 bit number, but due to limitation in number of digits - func ParseUint([]byte("9223372036854775807")) returns -1, "unexpected trailing char found. Expecting 0-9"

**Comment by erikdubbelboer** [comment]
Thanks for reporting this, it has been fixed in https://github.com/valyala/fasthttp/commit/8a9bdc8177d5b4681dd09bb34e7b00170b05e342

**Comment by saniapro** [comment]
thanks! suprisingly fast reaction! Already use it in my project.
