### ISSUE TITLE
Determine client connection was closed

### ISSUE THREAD

**Issue by workanator** [valyala/fasthttp#468]
Hello,

is that possible to determine if client closed connection before request finished? I have a situation when client cannot wait to long so it closes connection on timeout and server should revert all changes it made in that case. That is possible with the standard `net/http` server but through [associated context](https://golang.org/pkg/net/http/#Request.Context). I reviewed docs and could not find anything what can help me.

Thanks.

**Comment by erikdubbelboer** [comment]
I'm afraid this is not possible and would be really hard to add. `net/http` serves the connection in a separate goroutine and is therefor able to detect when the connection closes. `fasthttp` serves the connection in the same goroutine that runs the handler so while your handler is processing the request we can't detect any changes to the connection.

The only way to do this at the moment is to [Hijack](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Hijack) the connection and add support for this yourself.

**Comment by workanator** [comment]
Thank you for your effort and time given to answering my question. Will review what can I do with hijacking.
