### ISSUE TITLE
Support huge read-only []byte response bodies

### ISSUE THREAD

**Issue by erikdubbelboer** [valyala/fasthttp#469]
From an email by Ciprian:

\=======
All the contents I serve is kept in memory in a large `[]byte`
slice (which might be memory-mapped).  Therefore I would be able to
just say:
```
response.SetBody(slice)
```

However this method tries to copy the slice, and if the buffer is to
small it leads to allocations.  I've solved this by calling:
```
response.SetBodyStream(bytes.NewReader(slice), len(slice))
```
Unfortunately this requires heap allocation and is sub-optimal (as
there is a lot of coping between the slice I provide and the internal
buffers `fasthttp` is using).  I've also seen the `SwapBody` method,
however the contract states that it will "take-over" the slice, which
is a problem if the slice is memory mapped.
\=======

I think we can implement this with an extra member of `Response` that stores the original slice of `Response.body.W` so we can restore it at `Response.ResetBody()`. There are some other places where `Response.body.W` is being manipulated so we'll need some proper tests to make sure we have everything.

**Comment by erikdubbelboer** [comment]
You need to fix all points that touch the body such as [`Response.CopyTo()`](https://github.com/cipriancraciun/go-fasthttp/blob/03ca6ec36bb5d32144d842f03ecc9b4f1b71cdf7/http.go#L629), [`swapResponseBody`](https://github.com/cipriancraciun/go-fasthttp/blob/03ca6ec36bb5d32144d842f03ecc9b4f1b71cdf7/http.go#L649), [`Response.gzipBody()`](https://github.com/cipriancraciun/go-fasthttp/blob/03ca6ec36bb5d32144d842f03ecc9b4f1b71cdf7/http.go#L1239) which now gzips the body but ignores the result, and the same for [`Response.deflateBody()`](https://github.com/cipriancraciun/go-fasthttp/blob/03ca6ec36bb5d32144d842f03ecc9b4f1b71cdf7/http.go#L1259).

**Comment by cipriancraciun** [comment]
Indeed `CopyTo` and `swapResponseBody` should be changed.

However at a first look the `gzipBody` and `deflateBody` already work (as I've already changed the `bodyBytes`), however they needlessly keep the buffer (which I'll change).

Perhaps another method `bodyBytesAndReset` which returns the current body and "resets" the buffer, might be used in those two use-cases (and future ones)?

---

I'll try to look in the `http.go` file for all places that touch both `body`, `bodyStream` and `w`.

Should this feature be added to `Request` also?

---

As a small side-note regarding the documentation:  today there are many methods that touch the body, however there is no "documentation" about what are the "does and dont's".  For example if one calls `SetBodyStream` and then calls `AppendBody` would the second one actually "append" (as one expects) or will it drop the previous stream (as the actual code does).

**Comment by erikdubbelboer** [comment]
The problem with `gzipBody` and `deflateBody` is that they set `resp.body` with the compressed body but `resp.body` is then ignored by `resp.bodyBytes()` because `resp.bodyRaw` is still set. So I guess it's best if these methods set `resp.bodyRaw` to `nil`.

I don't think these methods need to be added to `Request` for now. We can always do this in the future.

I agree that not everything is documented, but doing this for all cases would require a lot of extra documentation. I guess the issue is that `fasthttp` is designed for all kinds of optimizations and doesn't have a clear simple api like `net/http` has. People using `fasthttp` will always run into issues like this at some point and find out by themselves (either by changing their code or by reading the `fasthttp` code) how to do it correctly. If anyone wants to add more documentation pull requests are always appreciated of course.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/733a6505a93f9928bcbe5f6cdedd3f9a2645f02b
