### ISSUE TITLE
any idea quickly change fasthttp.Client request retry times?

### ISSUE THREAD

**Issue by chslink** [valyala/fasthttp#482]
fasthttp.HostClient has a MaxIdemponentCallAttempts option can do this，it's inconvenient use HostClient directly

**Comment by erikdubbelboer** [comment]
I'm afraid this is currently not possible. `Client` uses `HostClient` but doesn't allow you to change the `MaxIdemponentCallAttempts` option. This could easily be added to `Client` as well so pull requests are welcome!
