### ISSUE TITLE
Wrong http "Connection" header check, while websocket handshake

### ISSUE THREAD

**Issue by danekin** [valyala/fasthttp#483]
According to RFC 6455 (https://tools.ietf.org/html/rfc6455#section-4.2.1):

> 4.   A |Connection| header field that includes the token "Upgrade",
        treated as an ASCII case-insensitive value.

But in fasthttp library connection header comparing with string "Upgrade" in case-sensitive manner.

**Comment by erikdubbelboer** [comment]
You are right, I have fixed it.
