### ISSUE TITLE
Feature request: get request headers in the same order they arrived

### ISSUE THREAD

**Issue by dsenim** [valyala/fasthttp#486]
It would be great if RequestHeader.VisitAll method could pass request headers to 'f' in the same order they originally arrived.

**Comment by erikdubbelboer** [comment]
In theory you could use [`RequestHeader.RawHeaders`](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.RawHeaders) for this but that means you have to parse the raw bytes yourself.

I guess the only way we can have `RequestHeader.VisitAll` return the right order is to parse the raw bytes in there as well which would slow the function down by quite a bit. Maybe it's better to add this as a new function.

**Comment by dsenim** [comment]
Parsing RequestHeader.RawHeaders bytes seems like more or less duplicating parseHeaders function just outside the package. I could do that, no problem.

New function would also help.
