### ISSUE TITLE
Is TLS Mutual Authentication Supported?

### ISSUE THREAD

**Issue by rmerry** [valyala/fasthttp#487]
Presently with the native 'net/http' package I pass in a `tls.Config{}` object
to the server in order to set up TLS mutual authentication:

```
	tlsConf := tls.Config{
		ClientAuth:   tls.RequireAndVerifyClientCert,
		ClientCAs:    certPool,
		Certificates: []tls.Certificate{cert},
	}

	s := &http.Server{
		TLSConfig:    &tlsConf,
	}
```
The `tls.RequireAndVerifyClientCert` option is what ensures that a client
certificate is requested and validated.

With fasthttp I cannot see a way to achieve this as although the
`fasthttp.Server{}` object does contain a `tls.Config{}` reference, it is private so I
am therefore unable to set it.

I'm probably missing something; is there anyway to achieve this with fasthttp?

Thank you.

**Comment by erikdubbelboer** [comment]
You can use a custom `tls.Config` by building your own listener with it and passing that to fasthttp. See this example:
```go
	cfg := &tls.Config{
		MinVersion:               tls.VersionTLS12,
		CurvePreferences:         []tls.CurveID{tls.X25519, tls.CurveP256},
		PreferServerCipherSuites: true,
		CipherSuites: []uint16{
			tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
			tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
			tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
		},
		ClientAuth: tls.RequireAndVerifyClientCert,
			ClientCAs:    certPool,
			Certificates: []tls.Certificate{cert},
		},
	}

	cfg.Certificates = append(cfg.Certificates, cert)

	cfg.BuildNameToCertificate()
	
	ln, err := net.Listen("tcp4", "0.0.0.0:443")
	if err != nil {
		panic(err)
	}

	lnTls := tls.NewListener(ln, cfg)
	
	if err := fasthttp.Serve(lnTls, requestHandler); err != nil {
		panic(err)
	}
```

**Comment by rmerry** [comment]
Thank you @erikdubbelboer, I really appreciate your help.

**Comment by hsblhsn** [comment]
Why don't provide a method to set TLSConfig or make the tlsConfig an exported field?

**Comment by erikdubbelboer** [comment]
@hsblhsn I would be open to a pull request to add this.
