### ISSUE TITLE
the master branch's code is ok ?

### ISSUE THREAD

**Issue by goith** [valyala/fasthttp#491]
1、today  i  go get  new  fasthttp  code,  i found  when the browse  send a  request, somtimes it recevie a error message "Error when parsing request"

2、why use os.Command().Output() int my handler,  the bin will output "child exited" ?

**Comment by goith** [comment]
`} else if connRequestNum > 1 && err == errNothingRead { `

this line  ' connRequestNum > 1' ,  change to " connRequestNum >= 1" ？

**Comment by erikdubbelboer** [comment]
The code is ok. That line doesn't need any change, it handles the cases of an idle connection being closed from the client side.

1. We need more code and describe exactly what you are doing to diagnose this issue.
2. I don't understand. Can you show the code you are using?

**Comment by erikdubbelboer** [comment]
@goith without seeing the code it's really hard to tell what is going wrong. If you don't want other people to see the code you can also email it to erik@dubbelboer.com so only I can see.

**Comment by goith** [comment]
```
// Create custom server.
    s := &fasthttp.Server{
        Handler:     h,
        ReadTimeout: 5 * time.Second,
    }

    if err := s.ListenAndServe(*addr); err != nil {
        log.Fatalf("Error in ListenAndServe: %s", err)
    }
```

stderr:

> 2018/12/25 18:52:03 error when serving connection "10.135.54.224:9080"<->"10.129.157.9:58242": read timeout with nothing read

above is example,  i  found it's  the ReadTimeout' setting.

**Comment by erikdubbelboer** [comment]
Can you show the code of your `h` function? What browser are you using?

**Comment by goith** [comment]
@erikdubbelboer  just using "examples/helloworldserver/helloworldserver.go"

**Comment by erikdubbelboer** [comment]
When running the following code I don't see any problems with the latest versions of Firefox or Chrome. What browser are you using and can you maybe share your whole code? You're being to vague about everything to be able to find the issue.

```go
package main
  
import (
  "fmt"
  "time"

  "github.com/valyala/fasthttp"
)

func h(ctx *fasthttp.RequestCtx) {
  fmt.Fprintf(ctx, "Hello, world!")
}

func main() {
  s := &fasthttp.Server{
    Handler:     h,
    ReadTimeout: 5 * time.Second,
  }

  if err := s.ListenAndServe(":8080"); err != nil {
    panic(err)
  }
}
```

**Comment by ErgoZUpdates** [comment]
> @erikdubbelboer
> for a new start service, send a request in the browser, and wait until the service stdout: "read timeout with nothing read" to refresh the request that have requested， the browser will show 'Error when parsing request', and status code is 400.
> 
> thanks for your reply.

same problem and only on first request from browser. On second or third i dont get error. (Chrome 72.0.3626.121)

```go
app.FHServer = &fasthttp.Server{
		Name:                 serverVersion,
		Handler:              serviceRouter.Handler,
		ReadTimeout:          5 * time.Second,
		WriteTimeout:         30 * time.Second,
		MaxConnsPerIP:        500,
		MaxRequestsPerConn:   500,
		MaxKeepaliveDuration: 30 * time.Second,
	}
```

**Comment by ErgoZUpdates** [comment]
> When running the following code I don't see any problems with the latest versions of Firefox or Chrome. What browser are you using and can you maybe share your whole code? You're being to vague about everything to be able to find the issue.
> 
> ```go
> package main
>   
> import (
>   "fmt"
>   "time"
> 
>   "github.com/valyala/fasthttp"
> )
> 
> func h(ctx *fasthttp.RequestCtx) {
>   fmt.Fprintf(ctx, "Hello, world!")
> }
> 
> func main() {
>   s := &fasthttp.Server{
>     Handler:     h,
>     ReadTimeout: 5 * time.Second,
>   }
> 
>   if err := s.ListenAndServe(":8080"); err != nil {
>     panic(err)
>   }
> }
> ```

Just tried your example with small modification (added logger)

```go

package main

import (
	"fmt"
	"os"
	"time"

	"github.com/sirupsen/logrus"
	"github.com/valyala/fasthttp"
)

func h(ctx *fasthttp.RequestCtx) {
	fmt.Fprintf(ctx, "Hello, world!")
}

func main() {

	Logger := logrus.New()
	Logger.Out = os.Stdout
	Logger.SetReportCaller(true)

		Logger.Formatter = &logrus.TextFormatter{FullTimestamp: true, DisableColors: true, TimestampFormat: "2006-01-02T15:04:05.999999999Z07:00"}

	Logger.Level, _ = logrus.ParseLevel("debug")


	s := &fasthttp.Server{
		Handler:     h,
		Logger:Logger,
		ReadTimeout: 5 * time.Second,
	}

	if err := s.ListenAndServe(":8123"); err != nil {
		panic(err)
	}
}
```

and i got error.
my go mod file:

```
module github.com/ErgoZUpdates/test

go 1.12

require (
	github.com/sirupsen/logrus v1.4.0
	github.com/valyala/fasthttp v1.2.0
)

```

go.sum file:

```go
github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/klauspost/compress v1.4.0 h1:8nsMz3tWa9SWWPL60G1V6CUsf4lLjWLTNEtibhe8gh8=
github.com/klauspost/compress v1.4.0/go.mod h1:RyIbtBH6LamlWaDj8nUwkbUhJ87Yi3uG0guNDohfE1A=
github.com/klauspost/cpuid v0.0.0-20180405133222-e7e905edc00e h1:+lIPJOWl+jSiJOc70QXJ07+2eg2Jy2EC7Mi11BWujeM=
github.com/klauspost/cpuid v0.0.0-20180405133222-e7e905edc00e/go.mod h1:Pj4uuM528wm8OyEC2QMXAi2YiTZ96dNQPGgoMS4s3ek=
github.com/konsorten/go-windows-terminal-sequences v1.0.1/go.mod h1:T0+1ngSBFLxvqU3pZ+m/2kptfBszLMUkC4ZK/EgS/cQ=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/sirupsen/logrus v1.4.0 h1:yKenngtzGh+cUSSh6GWbxW2abRqhYUSR/t/6+2QqNvE=
github.com/sirupsen/logrus v1.4.0/go.mod h1:LxeOpSwHxABJmUn/MG1IvRgCAasNZTLOkJPxbbu5VWo=
github.com/stretchr/objx v0.1.1/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/testify v1.2.2/go.mod h1:a8OnRcib4nhh0OaRAV+Yts87kKdq0PP7pXfy6kDkUVs=
github.com/valyala/bytebufferpool v1.0.0 h1:GqA5TC/0021Y/b9FG4Oi9Mr3q7XYx6KllzawFIhcdPw=
github.com/valyala/bytebufferpool v1.0.0/go.mod h1:6bBcMArwyJ5K/AmCkWv1jt77kVWyCJ6HpOuEn7z0Csc=
github.com/valyala/fasthttp v1.2.0 h1:dzZJf2IuMiclVjdw0kkT+f9u4YdrapbNyGAN47E/qnk=
github.com/valyala/fasthttp v1.2.0/go.mod h1:4vX61m6KN+xDduDNwXrhIAVZaZaZiQ1luJk8LWSxF3s=
github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a/go.mod h1:v3UYOV9WzVtRmSR+PDvWpU/qWl4Wa5LApYYX4ZtKbio=
golang.org/x/crypto v0.0.0-20180904163835-0709b304e793 h1:u+LnwYTOOW7Ukr/fppxEb1Nwz0AtPflrblfvUudpo+I=
golang.org/x/crypto v0.0.0-20180904163835-0709b304e793/go.mod h1:6SG95UA2DQfeDnfUPMdvaQW0Q7yPrPDi9nlGo2tz2b4=
golang.org/x/net v0.0.0-20180911220305-26e67e76b6c3/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33 h1:I6FyU15t786LL7oL/hn43zqTuEGr4PN7F4XJ1p4E3Y8=
golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
```

Console output:

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/ergoz/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/zd/603y5jfn0md6jwkz6hgprjpw0000gn/T/___go_build_test_ . #gosetup
/private/var/folders/zd/603y5jfn0md6jwkz6hgprjpw0000gn/T/___go_build_test_ #gosetup
time="2019-03-18T22:02:05.919939+03:00" level=info msg="error when serving connection \"127.0.0.1:8123\"<->\"127.0.0.1:60946\": read timeout with nothing read" func="github.com/valyala/fasthttp.(*workerPool).workerFunc" file="/Users/ergoz/go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/workerpool.go:218"
```

**Comment by erikdubbelboer** [comment]
Works perfectly for me. What platform are you on? Is there maybe some proxy or Docker or anything else between the request and the server? How do you run the server? How do you send the request?

**Comment by goith** [comment]
this issue  will occur when accessing in the browser. And I don't know why there are two tcp connections.

In addition, when 400 appeared, I found that the 400 response was actually earlier than the request.

![](https://github.com/goith/go-learn/raw/master/QQ%E6%88%AA%E5%9B%BE20190325153030.jpg)

**Comment by erikdubbelboer** [comment]
@goith What platform are you on? Is there maybe some proxy or Docker or anything else between the request and the server? How do you run the server?

**Comment by goith** [comment]
no proxy, no Docker.   just a vm (centos7.4). 
```golang
if err != nil {
            if err == io.EOF {
                err = nil
            } else if connRequestNum > 1 && err == errNothingRead {
                //} else if err == errNothingRead {
                // This is not the first request and we haven't read a single byte
                // of a new request yet. This means it's just a keep-alive connection
                // closing down either because the remote closed it or because
                // or a read timeout on our side. Either way just close the connection
                // and don't return any error response.
                err = nil
            } else {
          //print  log,  after accessed using a chrome browser,  and  unitl the log output  refresh the browser, 
                fmt.Println("goith:", "writeErrorResponse", err, ctx.Conn().RemoteAddr(), time.Now())                                                        
                bw = s.writeErrorResponse(bw, ctx, serverName, err)
            }
            break
        }
```

**Comment by erikdubbelboer** [comment]
Where and how is the VM running?

I don't understand the code there?

**Comment by caibirdme** [comment]
Meet with the same problem, and can reproduce
Here is my dir structure:
```
fun
├── main.go
└── static
    ├── index.html
    └── some.json
```
1 directory, 3 files

and main.go

```
package main

import (
	"github.com/valyala/fasthttp"
	"log"
	"time"
)

func main() {
	path := "./static"
	fs := fasthttp.FS{
		Root: path,
		Compress: true,
	}
	srv := fasthttp.Server{
		ReadTimeout: time.Second,
		Handler: fs.NewRequestHandler(),
	}
	log.Fatal(srv.ListenAndServe(":9001"))
}
```

every time when I access `localhost:9001/index.html` from browser, it outputs `2019/04/13 10:32:59 error when serving connection "127.0.0.1:9001"<->"127.0.0.1:51482": read timeout with nothing read`
But it's ok to curl from the terminal

**Comment by caibirdme** [comment]
I found this problem just occurs with chrome browser, Firefox and Safari are both Okay.
The only difference behavior among these browsers is that Chrome will send an extra GET request /favicon.ico

**Comment by erikdubbelboer** [comment]
@caibirdme I have just pushed a branch that should fix this issue (https://github.com/valyala/fasthttp/pull/564). Can you maybe try using this branch before I merged it into master?: https://github.com/valyala/fasthttp/tree/timing-fixes

**Comment by caibirdme** [comment]
@erikdubbelboer I'd love to but the project I'm working on is still developing and I can't test it in production. I'll try it in test environment, and if there's any problem, I'll give you a feedback

**Comment by scarbo87** [comment]
@erikdubbelboer 
If I use fasthttp ver 1.2.0 and I use Safary (ver 12.1), then I get no errors.
If I use fasthttp ver 1.2.0 and I use Chrome (ver 73.0.3683.103), then I get error "error when serving connection \"172.20.0.7:8080\"<->\"172.20.0.1:57354\": read timeout with nothing read"
But, If I use fasthttp branch `timing-fixes` and any browser I get a new error "read tcp 172.20.0.7:8080->172.20.0.1:56794: i/o timeout"

My config:
```
	server := &fasthttp.Server{
		Logger:  newServerLoggerAdapter(logger),
		Handler: ps.handler,
		ErrorHandler: func(ctx *fasthttp.RequestCtx, err error) {
			errorResponse(ctx, err)
		},
		Concurrency:          256*1024,
		DisableKeepalive:     false,
		ReadTimeout:          10*time.Second,
		WriteTimeout:         10*time.Second,
		ReadBufferSize:       4096,
		WriteBufferSize:      4096,
		MaxConnsPerIP:        256,
		MaxRequestsPerConn:   0,
		MaxKeepaliveDuration: 30*time.Second,
		MaxRequestBodySize:   4*1024*1024,
		//
		LogAllErrors:                  false,
		DisableHeaderNamesNormalizing: false,
	}
```

**Comment by erikdubbelboer** [comment]
@scarbo87 I'm still not seeing those errors. Can you try the following code with the `timing-fixes` branch?

```go
package main
  
import (
  "log"
  "time"

  "github.com/valyala/fasthttp"
)

func handler(ctx *fasthttp.RequestCtx) {
}

type fasthttpLogger struct {
  fasthttp.Logger
}

func (f fasthttpLogger) Printf(format string, args ...interface{}) {
  log.Printf(format, args...)
}

func main() {
  server := &fasthttp.Server{
    Logger:  fasthttpLogger{},
    Handler: handler,
    ErrorHandler: func(ctx *fasthttp.RequestCtx, err error) {
      log.Printf("%v", err)
    },
    Concurrency:          256 * 1024,
    DisableKeepalive:     false,
    ReadTimeout:          10 * time.Second,
    WriteTimeout:         10 * time.Second,
    ReadBufferSize:       4096,
    WriteBufferSize:      4096,
    MaxConnsPerIP:        256,
    MaxRequestsPerConn:   0,
    MaxKeepaliveDuration: 30 * time.Second,
    MaxRequestBodySize:   4 * 1024 * 1024,
    //
    LogAllErrors:                  false,
    DisableHeaderNamesNormalizing: false,
  }

  panic(server.ListenAndServe(":8080"))
}
```

**Comment by erikdubbelboer** [comment]
@scarbo87 are you maybe sending a really big request? Like big headers or big cookies? This could maybe cause an issue if the request is bigger than the ReadBufferSize.

**Comment by scarbo87** [comment]
@erikdubbelboer 
I recorded a video from the screen where you can see this error: https://take.ms/sqVQa
Source code: https://github.com/scarbo87/fasthttp_test
My golang version: `go version go1.12.1 darwin/amd64`

**Comment by erikdubbelboer** [comment]
Ah I see now, that's the idle connection hitting its timeout. It indeed shouldn't print that as it's not really an error. I have force pushed a new version to the `timing-fixes` that fixes this.

**Comment by scarbo87** [comment]
@erikdubbelboer, I still have this problem now. I use d3715c3 commit

**Comment by erikdubbelboer** [comment]
Yes please create a new issue and describe again exactly what you are seeing. Is it still the same as your video and code you posted above?
