### ISSUE TITLE
Multiple files in upload form values?

### ISSUE THREAD

**Issue by unisqu** [valyala/fasthttp#494]
Everything's good. My last part with fasthttp is multiple files in upload form.

Does anyone have a working example i can find online? How do i get multiple files from a html form with multiple file?

Also, how do i do a send by client for the multiple files?

**Comment by erikdubbelboer** [comment]
I don't understand. You want your server to accept uploads of multiple files or you want to use fasthttp to upload multiple files to another server? So is fasthttp the client or the server?

**Comment by unisqu** [comment]
I would like fasthttp to accept uploads of multiple files. how can i do that?

**Comment by tsingson** [comment]
@dgrr 

cool.

**Comment by unisqu** [comment]
Thx
