### ISSUE TITLE
Connection state active is not triggerred

### ISSUE THREAD

**Issue by vijayviji** [valyala/fasthttp#498]
In servConn fn (in server.go), we do ctx.Request.readLimitBody() and using the return err, we set the state to active.

However, if the fn ctx.Request.readLimitBody() returns EOF, then we won't enter into active state at all.

Active State and Idle state differ in that, Idle state is called after Handler() and Active state should be set before that.

**Comment by erikdubbelboer** [comment]
But if `err == io.EOF` then Handler isn't even called and the state will go to Closed.

**Comment by erikdubbelboer** [comment]
@vijayviji are you seeing this issue with real traffic?

**Comment by vijayviji** [comment]
Yes. My client is sending around 1 Million requests per minute, everything with a new connection (no keep-alive). However I'm not getting any call backs for state active. I've measured state changes and this is what I get.

cumConnNewToIdleCount 	649516
cumConnEndToEndCount 	649513
cumConnIdleToClosedCount  649513
cumConnNewToActiveCount  0
cumConnIdleToActiveCount 	 0
cumConnActiveToIdleCount 	 0
cumConnNewToClosedCount  0
cumConnActiveToClosedCount 0 

The description I've mentioned is a conjecture, not a proper root-cause.

**Comment by erikdubbelboer** [comment]
Can you share the code you use to generate this?
I just pushed a commit with a test case for `ConnState` and it seems to work fine. See: https://github.com/valyala/fasthttp/commit/4333427994dcc107f38f556dd7bfdc33bc485c94

**Comment by erikdubbelboer** [comment]
When I try the following program loosely based on your code everything seems to work fine:
```go
package main
  
import (
  "log"
  "net"
  "sync"

  "github.com/valyala/fasthttp"
)

func main() {
  // Using a net.Conn as map key seems to be safe in this case.
  // See: https://forum.golangbridge.org/t/using-interface-types-as-map-keys/706/5
  states := make(map[net.Conn]fasthttp.ConnState)
  var statesMu sync.Mutex

  s := fasthttp.Server{
    Handler: func(ctx *fasthttp.RequestCtx) {
    },
    ConnState: func(conn net.Conn, state fasthttp.ConnState) {
      statesMu.Lock()
      defer statesMu.Unlock()

      old, exists := states[conn]
      states[conn] = state

      if exists {
        log.Printf("%#v from %s to %s\n", conn, old, state)

        if state == fasthttp.StateClosed {
          delete(states, conn)
        }
      }
    },
  }

  if err := s.ListenAndServe(":8080"); err != nil {
    panic(err)
  }
}
```

What are you using to make the requests? I'm 99% sure the issue isn't with fasthttp so if you want me to find it I'm afraid you're going to have to share all your code as a lot is missing now.
