### ISSUE TITLE
How do I get various response times for the site?

### ISSUE THREAD

**Issue by KeenCN** [valyala/fasthttp#501]
How do I get various response times for the site? 

curl  http://www.google.com   -v  -w %{time_namelookup}::%{time_connect}::%{time_starttransfer}::%{time_total}::%{speed_download}

**Comment by erikdubbelboer** [comment]
I'm afraid these are things that are impossible to get from fasthttp. We don't have anything like [httptrace](https://golang.org/pkg/net/http/httptrace/) yet. Pull requests are always welcome!
