### ISSUE TITLE
client forward request to back-end,  url truncated

### ISSUE THREAD

**Issue by miniframework** [valyala/fasthttp#503]
i found lb client forward request to back-end， back-end request [error req.ParseForm error: invalid URL escape "%9" ] 

lb client log *********&title=%E6%83%B3%E5%8A%A0%E7%9B%9F%E5%88%9B%E4%B8%9A%E5%93%81%E7%89%8C%E5%8D%83%E4%B8%87%E5%88%AB%E9%80%89%E9%94%99%EF%BC%81%E8%BF%99%E4%B8%AA%E9%9B%B6%E9%A3%9F%E5%BA%97%E5%8A%A0%E7%9B%9F%E9%A1%B9%E7%9B%AE%E5%88%A9%E6%B6%A6%E6%98%AF%E5%90%8C%E8%A1%8C3%E5%80%8D%EF%BC%81&tu=5867985

url truncate 

back-end log 
*********&title=%E6%83%B3%E5%8A%A0%E7%9B%9F%E5%88%9B%E4%B8%9A%E5%93%81%E7%89%8C%E5%8D%83%E4%B8%87%E5%88%AB%E9%80%89%E9%94%99%EF%BC%81%E8%BF%99%E4%B8%AA%E9%9B%B6%E9%A3%9F%E5%BA%97%E5%8A%A0%E7%9B%9F%E9%A1%B9%E7%9B%AE%E5%88%A9%E6%B6%A6%E6%98%AF%E5%9

**Comment by erikdubbelboer** [comment]
Can you explain more and show your code? Where is fasthttp being used?

**Comment by miniframework** [comment]
i know why。

because i before used this code :
req.Header = ctx.Request.Header
client.Do(req)

modify i used this code:
ctx.Request.Header.CopyTo(&req.Header)

i found  Requestheader comments 
It is forbidden copying Args instances. Create new instances instead and use CopyTo().

**Comment by miniframework** [comment]
why ? forbidden copying RequestHeader instances

**Comment by erikdubbelboer** [comment]
Because of internal pointers that won't be copied correctly and will result in race conditions or memory issues.
