### ISSUE TITLE
hao  to dynamic add client 

### ISSUE THREAD

**Issue by miniframework** [valyala/fasthttp#504]
code example:
```go
c := &fasthttp.HostClient{Addr: addr}
lbc.Clients = append(lbc.Clients, c)
lbc.Do()  
c1 := &fasthttp.HostClient{Addr: addr}
lbc.Clients = append(lbc.Clients, c1)
lbc.Do()  
```
i see code ：
cc.once.Do(cc.init)      run once init
so c1 not add in cc.cs

hao to dynamic add client  to lbClient 
service discovery need

**Comment by erikdubbelboer** [comment]
I'm afraid this is not possible at the moment. It is fairly easy to add a `Add` method to `LBClient` to add new clients after first use. I don't have time to write the code at the moment. Pull requests are always welcome!

**Comment by miniframework** [comment]
easy add a client to LBClient.

func (cc *LBClient) AddClient(client BalancingClient) {
	cc.cs = append(cc.cs, &lbClient{
		c:           client,
		healthCheck: cc.HealthCheck,
	})
}

Hao to del client by client.Addr      
question,  if i implement other client interface , I have to change this function， 
I don't want to do that. hao?

func (cc *LBClient) DelClientByAddr(string addr) {
   k,c := range cc.cs {
       switch  c.(type) {
        case HostClient:
                  if c.(HostClient).Addr == addr {
                      cc.cs = append(cc.cs[:k], cc.cs[k+1:]...)   
                   }
        case PipelineClient:
                .....
      }
  }
}
@erikdubbelboer

**Comment by erikdubbelboer** [comment]
Is deleting by address really useful? I would think passing a `BalancingClient` and removing that from the list makes more sense? If someone then wants to delete by address they can just loop though the `Clients` and find the one with the address that they want to have removed.

Also right now you have a race condition if you do this from multiple goroutines. You will need to add a `sync.Mutex` to `LBClient` to protect against this. And since `Clients` is public I guess this mutex should also be public even though that's kinda ugly.

**Comment by miniframework** [comment]
type BalancingClient interface {
	DoDeadline(req *Request, resp *Response, deadline time.Time) error
	PendingRequests() int
       Addr() string     ? 
}
HostClient add Addr()
PipelineClient add Addr()

**Comment by miniframework** [comment]
@erikdubbelboer  
i used  service discovery.   after-end register addr to etcd， proxy add addr to lbClient ,  after-end hung, proxy del addr eq client from lbClient.

type BalancingClient interface {
	DoDeadline(req *Request, resp *Response, deadline time.Time) error
	PendingRequests() int
        Addr()  string ? 
}

**Comment by erikdubbelboer** [comment]
The problem with adding `Addr()` to `BalancingClient` is that it breaks the code of all users who current implement their own `BalancingClient`. I guess this is the reason why we should do proper versioning and release new versions more often.

For now I'm ok with adding `Addr()` as I don't think anyone will really be affected. So go ahead and make a pull request for this.
