### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by densmnko** [valyala/fasthttp#506]
Dear @valyala, thanks a lot for you awesome fasthttp. 

I`m new to golang and may be its my fault, but got twice (on a dozen runs) a "fatal error: concurrent map read and map write". 
--------------------------- first stack ----------------------------------------
fatal error: concurrent map read and map write

goroutine 992 [running]:
runtime.throw(0x71ab07, 0x21)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0000ab9f8 sp=0xc0000ab9c8 pc=0x42c372
runtime.mapaccess2_faststr(0x6b4a00, 0xc000077110, 0xc026352f60, 0x13, 0x0, 0x0)
/usr/local/go/src/runtime/map_faststr.go:110 +0x458 fp=0xc0000aba68 sp=0xc0000ab9f8 pc=0x413598
main.UpdateHandler(0xc0321a5200, 0x32135)
/root/go/src/dumb/main.go:373 +0x61a fp=0xc0000abbc0 sp=0xc0000aba68 pc=0x66deea
main.Router(0xc0321a5200)
/root/go/src/dumb/main.go:675 +0x874 fp=0xc0000abd20 sp=0xc0000abbc0 pc=0x6708a4
github.com/valyala/fasthttp.(*Server).serveConn(0xc0000921a0, 0x765020, 0xc0269260f0, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1926 +0x77a fp=0xc0000abea0 sp=0xc0000abd20 pc=0x657dca
github.com/valyala/fasthttp.(*Server).serveConn-fm(0x765020, 0xc0269260f0, 0x1, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1531 +0x3e fp=0xc0000abed8 sp=0xc0000abea0 pc=0x66144e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000e0090, 0xc00f64c6c0)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:212 +0xc3 fp=0xc0000abf98 sp=0xc0000abed8 pc=0x65ec83
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0000e0090, 0xc00f64c6c0, 0x6975e0, 0xc00f64c6c0)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x35 fp=0xc0000abfc0 sp=0xc0000abf98 pc=0x65f635
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000abfc8 sp=0xc0000abfc0 pc=0x458621
created by github.com/valyala/fasthttp.(*workerPool).getCh
/root/go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x119

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f178c7390f0, 0x72, 0x0)
/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000012318, 0x72, 0xc00b0dcf00, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000012318, 0xffffffffffffff00, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc000012300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc000012300, 0x4, 0xc0000adc58, 0x406d5c)
/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc009056020, 0xc021d60780, 0xc0000adcd8, 0x406bcf)
/usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc009056020, 0x0, 0xc0269260f0, 0x0, 0xc0000add10)
/usr/local/go/src/net/tcpsock.go:260 +0x47
github.com/valyala/fasthttp.acceptConn(0xc0000921a0, 0x763ca0, 0xc009056020, 0xc0000ade20, 0x765020, 0xc0269260f0, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1625 +0x49
github.com/valyala/fasthttp.(*Server).Serve(0xc0000921a0, 0x763ca0, 0xc009056020, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1547 +0x2bd
github.com/valyala/fasthttp.(*Server).ListenAndServe(0xc0000921a0, 0x71155f, 0x3, 0x6a4440, 0xc063248040)
/root/go/src/github.com/valyala/fasthttp/server.go:1340 +0xa7
github.com/valyala/fasthttp.ListenAndServe(0x71155f, 0x3, 0x726930, 0x2, 0x2)
/root/go/src/github.com/valyala/fasthttp/server.go:91 +0x60
main.main()
/root/go/src/dumb/main.go:528 +0x246

goroutine 5 [sleep]:
time.Sleep(0x3b9aca00)
/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/valyala/fasthttp.init.0.func1()
/root/go/src/github.com/valyala/fasthttp/header.go:1441 +0x2a
created by github.com/valyala/fasthttp.init.0
/root/go/src/github.com/valyala/fasthttp/header.go:1439 +0x3a

goroutine 7 [sleep]:
time.Sleep(0x2540be400)
/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/valyala/fasthttp.(*workerPool).Start.func1(0xc0000e0090, 0xc0000162a0)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:61 +0x57
created by github.com/valyala/fasthttp.(*workerPool).Start
/root/go/src/github.com/valyala/fasthttp/workerpool.go:53 +0x7f

goroutine 2034 [runnable]:
syscall.Syscall(0x3, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x5, 0x7f1781a5ecb8, 0x77)
/usr/local/go/src/syscall/zsyscall_linux_amd64.go:310 +0x40
internal/poll.(*FD).destroy(0xc027d15f80, 0x485b01, 0x7f1781a5ecb0)
/usr/local/go/src/internal/poll/fd_unix.go:78 +0x4e
internal/poll.(*FD).decref(0xc027d15f80, 0x1, 0xc028e7f1a0)
/usr/local/go/src/internal/poll/fd_mutex.go:213 +0x45
internal/poll.(*FD).Close(0xc027d15f80, 0xc027d15f80, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:100 +0x9b
net.(*netFD).Close(0xc027d15f80, 0x765020, 0xc0269260e8)
/usr/local/go/src/net/fd_unix.go:184 +0x4f
net.(*conn).Close(0xc0269260e8, 0x0, 0x0)
/usr/local/go/src/net/net.go:201 +0x4a
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000e0090, 0xc00e013540)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:224 +0x292
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0000e0090, 0xc00e013540, 0x6975e0, 0xc00e013540)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
/root/go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x119

--------------------------- second stack ----------------------------------------
fatal error: concurrent map read and map write

goroutine 2007 [running]:
runtime.throw(0x7198b8, 0x21)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00fa7daa0 sp=0xc00fa7da70 pc=0x42c372
runtime.mapaccess2_faststr(0x6b3980, 0xc00007d110, 0xc04fede540, 0x1b, 0x0, 0x0)
/usr/local/go/src/runtime/map_faststr.go:110 +0x458 fp=0xc00fa7db10 sp=0xc00fa7daa0 pc=0x413598
main.NewHandler(0xc00d262900)
/root/go/src/dumb/main.go:236 +0x10f fp=0xc00fa7dc68 sp=0xc00fa7db10 pc=0x66d04f
main.Router(0xc00d262900)
/root/go/src/dumb/main.go:675 +0x580 fp=0xc00fa7dd20 sp=0xc00fa7dc68 pc=0x6703c0
github.com/valyala/fasthttp.(*Server).serveConn(0xc0000a41a0, 0x763bc0, 0xc01834e650, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1926 +0x77a fp=0xc00fa7dea0 sp=0xc00fa7dd20 pc=0x657eba
github.com/valyala/fasthttp.(*Server).serveConn-fm(0x763bc0, 0xc01834e650, 0x1, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1531 +0x3e fp=0xc00fa7ded8 sp=0xc00fa7dea0 pc=0x66153e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000f2090, 0xc015504200)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:212 +0xc3 fp=0xc00fa7df98 sp=0xc00fa7ded8 pc=0x65ed73
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0000f2090, 0xc015504200, 0x696520, 0xc015504200)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x35 fp=0xc00fa7dfc0 sp=0xc00fa7df98 pc=0x65f725
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00fa7dfc8 sp=0xc00fa7dfc0 pc=0x458621
created by github.com/valyala/fasthttp.(*workerPool).getCh
/root/go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x119

goroutine 1 [runnable]:
syscall.Syscall6(0x36, 0x7, 0x6, 0x1, 0xc00fa7bb5c, 0x4, 0x0, 0x0, 0x1, 0x0)
/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.setsockopt(0x7, 0x6, 0x1, 0xc00fa7bb5c, 0x4, 0xc00fa7bb80, 0x18)
/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1591 +0x79
syscall.SetsockoptInt(0x7, 0x6, 0x1, 0x1, 0x7f145babdd80, 0x0)
/usr/local/go/src/syscall/syscall_unix.go:285 +0x5b
internal/poll.(*FD).SetsockoptInt(0xc017a61f80, 0x6, 0x1, 0x1, 0x0, 0x0)
/usr/local/go/src/internal/poll/sockopt.go:17 +0xa0
net.setNoDelay(0xc017a61f80, 0xc01766c501, 0xc0500fb980, 0x406e75)
/usr/local/go/src/net/tcpsockopt_posix.go:15 +0x50
net.newTCPConn(0xc017a61f80, 0xc017a61f80)
/usr/local/go/src/net/tcpsock.go:195 +0x56
net.(*TCPListener).accept(0xc00000e028, 0xc01483c300, 0xc00fa7bcf8, 0x406bcf)
/usr/local/go/src/net/tcpsock_posix.go:143 +0x68
net.(*TCPListener).Accept(0xc00000e028, 0x0, 0xc01834e650, 0x0, 0xc00fa7bd30)
/usr/local/go/src/net/tcpsock.go:260 +0x47
github.com/valyala/fasthttp.acceptConn(0xc0000a41a0, 0x762840, 0xc00000e028, 0xc00fa7be40, 0x763bc0, 0xc01834e650, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1625 +0x49
github.com/valyala/fasthttp.(*Server).Serve(0xc0000a41a0, 0x762840, 0xc00000e028, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1547 +0x2bd
github.com/valyala/fasthttp.(*Server).ListenAndServe(0xc0000a41a0, 0x710402, 0x3, 0x6a33c0, 0xc054e3e040)
/root/go/src/github.com/valyala/fasthttp/server.go:1340 +0xa7
github.com/valyala/fasthttp.ListenAndServe(0x710402, 0x3, 0x725680, 0x13d620, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:91 +0x60
main.main()
/root/go/src/dumb/main.go:537 +0x174

goroutine 19 [sleep]:
time.Sleep(0x3b9aca00)
/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/valyala/fasthttp.init.0.func1()
/root/go/src/github.com/valyala/fasthttp/header.go:1441 +0x2a
created by github.com/valyala/fasthttp.init.0
/root/go/src/github.com/valyala/fasthttp/header.go:1439 +0x3a

goroutine 22 [sleep]:
time.Sleep(0x2540be400)
/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/valyala/fasthttp.(*workerPool).Start.func1(0xc0000f2090, 0xc00006e240)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:61 +0x57
created by github.com/valyala/fasthttp.(*workerPool).Start
/root/go/src/github.com/valyala/fasthttp/workerpool.go:53 +0x7f

goroutine 2009 [chan receive]:
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000f2090, 0xc00df3b500)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:207 +0x6e
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0000f2090, 0xc00df3b500, 0x696520, 0xc00df3b500)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
/root/go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x119

goroutine 1695 [runnable]:
github.com/valyala/fasthttp.(*Request).ResetBody(0xc00d262000)
/root/go/src/github.com/valyala/fasthttp/http.go:578 +0xb6
github.com/valyala/fasthttp.(*Request).resetSkipHeader(0xc00d262000)
/root/go/src/github.com/valyala/fasthttp/http.go:798 +0x2f
github.com/valyala/fasthttp.(*Request).Reset(0xc00d262000)
/root/go/src/github.com/valyala/fasthttp/http.go:794 +0x3b
github.com/valyala/fasthttp.(*Server).serveConn(0xc0000a41a0, 0x763bc0, 0xc01834e648, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1941 +0x7c4
github.com/valyala/fasthttp.(*Server).serveConn-fm(0x763bc0, 0xc01834e648, 0x1, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:1531 +0x3e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000f2090, 0xc00deba440)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:212 +0xc3
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0000f2090, 0xc00deba440, 0x696520, 0xc00deba440)
/root/go/src/github.com/valyala/fasthttp/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
/root/go/src/github.com/valyala/fasthttp/workerpool.go:183 +0x119

**Comment by erikdubbelboer** [comment]
I don't think this has anything to do with fasthttp. It's hard to see from just these stack traces but it looks like maybe your `UpdateHandler` and `NewHandler` are trying to read from and write to the same map without a mutex?

**Comment by densmnko** [comment]
Dear @erikdubbelboer thanks a lot, shame on me :(  
How can i delete or remove this issue?

**Comment by densmnko** [comment]
thanks dear, and a happy new year :)
