### ISSUE TITLE
More examples for posting multiple values with POST

### ISSUE THREAD

**Issue by unisqu** [valyala/fasthttp#510]
I have seen only things like here
https://github.com/kataras/iris/blob/c598e7bee38a260b7173418a33281bf1a9f91aab/context.go#L282

here
https://zhuanlan.zhihu.com/p/52644362

and here
https://godoc.org/github.com/valyala/fasthttp#Args

and also vaguely somewhere but seems like only 1 post value.

how can i post k=key, v=value, i=item multiple values with fasthttp as a client? (not server receiving end but sending POST request to another service/service)

can anyone give an example? thx

**Comment by dgrr** [comment]
```go
package main
  
import (
  "fmt"

  "github.com/valyala/fasthttp"
)

func main() {
  c := fasthttp.Client{
    Name: "POST example",
  }
  args := fasthttp.AcquireArgs()
  defer fasthttp.ReleaseArgs(args)

  args.Add("k", "key")
  args.Add("v", "value")
  args.Add("i", "item")

  statusCode, body, err := c.Post(nil, "http://localhost:8080", args)
  if err != nil {
    panic(err)
  }
  fmt.Printf("Status: %d\n", statusCode)
  fmt.Printf("Body:\n%s\n", body)
}
```

**Comment by unisqu** [comment]
You are the best! Thx!
