### ISSUE TITLE
About the usage of stackless package?

### ISSUE THREAD

**Issue by JasonYuan** [valyala/fasthttp#511]
As per comments in the NewFunc, stackless can save a lot of stack space when the function f cost a lot of stack space.
But the usage in fasthttp seems not in such case. stackless is used in writer where data being passed by slice. Since slice is passed by reference, it will not cost much stack space at all. I also wrote some test case to validate this. 
[func_test.txt](https://github.com/valyala/fasthttp/files/2744704/func_test.txt)
Are there any other reason to use stackless?

**Comment by erikdubbelboer** [comment]
I have to be honest that I haven't looked into the stackless package before. From what I can see is that it tries to reduce stack usage by running the stack heavy work on only `GOMAXPROC` goroutines. This way only those goroutines will get a big stack and the others stay small.

Within fasthttp stackless is only used for compressing data. From my test it seems like gzip requires about 1MB of stack. I have [written a small benchmark](https://gist.github.com/erikdubbelboer/deee1f15804c6eaab0721e0f002c634a) as well which shows that if you start compressing from multiple goroutines they will all grow their stack and it takes a while for the garbage collector to shrink the stacks again:
```
BenchmarkWithoutStackless-8   	400785408 bytes
902070272 bytes
1398112256 bytes
1845002240 bytes
2097905664 bytes
2097905664 bytes
    3000	   1073229 ns/op	    2676 B/op	       0 allocs/op
BenchmarkWithStackless-8      	25526272 bytes
25526272 bytes
25526272 bytes
25526272 bytes
25526272 bytes
25526272 bytes
    3000	    996146 ns/op	    3682 B/op	       0 allocs/op
```
As you can see with 2000 workers it takes up around 2GB of stack space without stackless.

Fasthttp has a default concurrency (number of goroutines) of `256 * 1024` which means if you are serving a lot of compressed responses it could use up to `256` GB of stack space. Gzip is CPU intensive so having only `GOMAXPROCS` goroutines doing the gzipping has the same speed as having more goroutines do it. So using the stackless package is a big advantage here.

When I run your test I can definitely also see that `TestPureFunc` uses a lot more stack space:
```
=== RUN   TestNewFunc
inuse: 140345344 sys: 140345344

=== RUN   TestPureFunc
inuse: 326565888 sys: 326565888
```
