### ISSUE TITLE
Unwanted header: Accept-Ranges: bytes

### ISSUE THREAD

**Issue by flddr** [valyala/fasthttp#515]
Hello, thank you for your amazing work 🥇 

I am relatively new to _Go_ and **fasthttp** and testing writing my first backend - maybe, i need more time to find everything in the docs.

I am wondering, why `net/http` does not, but **fasthttp|tls** adds an `Accept-Ranges: bytes` _header_ - but i did not found anything about in your source code or docs or issues.

![image](https://user-images.githubusercontent.com/42785945/51308669-ee519b00-1a42-11e9-9247-9f9e2dd704f1.png)

Have you an idea? If, can you point me to your docs or source code for that?

Actually, i am only using **fasthttp** for network.

Thank you for your great explanations in your issues.

**Comment by flddr** [comment]
I have another question about automatically handled headers.

If i set

```go
ctx.SetStatusCode(status)
```

this becomes overwritten to `200` using some functions, without documentation about it.

Generally, headers are a wide topic and sometimes it is very comfortable to have functions, which handle that.

Even if its often usefull to handle that automatically i would like to have options to handle that myself, otherwise a am never in a guarantied state about it.

Besides headers like `Date`, `Content-Length` in many cases, and `Server` to your honor, all headers should be kept if i already set them myself. The case of errors is up to me then.

**Comment by flddr** [comment]
Thanks,

it's a little bit hard to find everything, maybe i will reopen sometime 👍

**Comment by erikdubbelboer** [comment]
If you didn't find it yet, `Accept-Ranges: bytes` is added when serving files. This tells the browser/client that you can also request parts of the content using the `Range` header.

**Comment by flddr** [comment]
@erikdubbelboer thank you,

but i am not asking about the RFC, i am asking about _automatically_ adding 😉 

It would be nice to have an _overall overview_ which function will add which headers automatically or it should be explicitely documented (best option)

**Comment by flddr** [comment]
@erikdubbelboer 

As my first steps in _Go_ i just understand now how to use `ctx.Write()`, like `io.Copy()`. That's awesome!

But about `Accept-Ranges: bytes`: is `fasthttp.ServeFileUncompressed()` doing some _black magic_? :wink: As i had **not implemented anything** about serving those _ranges_, my backend cannot handle this header!? Or is `fasthttp.ServeFile...()`holding the connection and handling those ranges _itself_?

That's why i am wondering about automatically adding an header, which isn't handled myself :relaxed:

**Comment by erikdubbelboer** [comment]
Yes fasthttp will handle `Range` requests automatically if you use `fasthttp.ServeFile...()`.

**Comment by flddr** [comment]
@erikdubbelboer oh, that's interesting.

Crazy game, saw already a lot of sensational stuff in **fasthttp** and _Go_

Which details would help to select the use of `ctx.Write()` or `fasthttp.ServeFile...()` as best effort? Already for a 1MB file or better the really big ones? As **fasthttp** is heavily optimized in it's ways, when will this already makes sense?

Thanks again :+1:

**Comment by flddr** [comment]
Oh, and what's about _parallel_ downloads via _range_? This isn't handled i guess?

**Comment by erikdubbelboer** [comment]
`fasthttp.ServeFile...()` serves a file from the filesystem while `ctx.Write()` returns a response you build yourself. They have very different use cases.

Parallel downloads via `Range` requests is of course supported if you use `fasthttp.ServeFile...()`.

**Comment by flddr** [comment]
Oh, ok, thanks :blush:
