### ISSUE TITLE
I have encountered a goroutine leak

### ISSUE THREAD

**Issue by liuxingbaoyu** [valyala/fasthttp#518]
After my program runs for about 6 hours, the goroutine will become very large and the system will be unable to access the network, such as using chrome to access google. I used pprof analysis and found some exception information about fasthttp.
I am sorry for my bad English, thank you for your help.

```
28576 @ 0x43572b 0x42ebe0 0x42e1d5 0x5217ad 0x523001 0x525790 0x55db4f 0x57a207 0x515ee9 0x5162c4 0x82ae05 0x82ac9f 0x83d5a2 0x801515 0x800b19 0x800806 0x7fd7d5 0x85c482 0x463531
#	0x42e1d4	internal/poll.runtime_pollWait+0x64				C:/Go/src/runtime/netpoll.go:173
#	0x5217ac	internal/poll.(*pollDesc).wait+0x9c				C:/Go/src/internal/poll/fd_poll_runtime.go:85
#	0x523000	internal/poll.(*ioSrv).ExecIO+0x2b0				C:/Go/src/internal/poll/fd_windows.go:222
#	0x52578f	internal/poll.(*FD).Read+0x41f					C:/Go/src/internal/poll/fd_windows.go:487
#	0x55db4e	net.(*netFD).Read+0x8e						C:/Go/src/net/fd_windows.go:152
#	0x57a206	net.(*conn).Read+0xb6						C:/Go/src/net/net.go:177
#	0x515ee8	bufio.(*Reader).fill+0x2d8					C:/Go/src/bufio/bufio.go:100
#	0x5162c3	bufio.(*Reader).Peek+0x133					C:/Go/src/bufio/bufio.go:132
#	0x82ae04	github.com/valyala/fasthttp.(*ResponseHeader).tryRead+0x94	E:/Eternal/go/src/github.com/valyala/fasthttp/header.go:1309
#	0x82ac9e	github.com/valyala/fasthttp.(*ResponseHeader).Read+0x5e		E:/Eternal/go/src/github.com/valyala/fasthttp/header.go:1295
#	0x83d5a1	github.com/valyala/fasthttp.(*Response).ReadLimitBody+0x71	E:/Eternal/go/src/github.com/valyala/fasthttp/http.go:976
#	0x801514	github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp+0x944	E:/Eternal/go/src/github.com/valyala/fasthttp/client.go:1183
#	0x800b18	github.com/valyala/fasthttp.(*HostClient).do+0x78		E:/Eternal/go/src/github.com/valyala/fasthttp/client.go:1089
#	0x800805	github.com/valyala/fasthttp.(*HostClient).Do+0xb5		E:/Eternal/go/src/github.com/valyala/fasthttp/client.go:1039
#	0x7fd7d4	github.com/valyala/fasthttp.(*Client).Do+0x254			E:/Eternal/go/src/github.com/valyala/fasthttp/client.go:427
#	0x85c481	github.com/valyala/fasthttp.clientDoDeadline.func1+0x51		E:/Eternal/go/src/github.com/valyala/fasthttp/client.go:981
```

**Comment by erikdubbelboer** [comment]
The stacktrace shows that you have about 28576 outgoing requests that never send any response. This is not an issue with fasthttp. I suggest you either fix the server to properly send a response. Or if you have no control over the server [set a read timeout](https://godoc.org/github.com/valyala/fasthttp#Client.ReadTimeout) to terminate broken connections like this after a while.

**Comment by liuxingbaoyu** [comment]
> 堆栈跟踪显示您有大约28576个从不发送任何响应的传出请求。这不是fasthttp的问题。我建议您修复服务器以正确发送响应。或者，如果您无法控制服务器，请[在一段时间后设置读取超时](https://godoc.org/github.com/valyala/fasthttp#Client.ReadTimeout)以终止此类断开的连接。

It’s incredible. He has been bothering me for many days. It’s been solved like this. Thank you so much.
But I am still confused, why after using `req.SetConnectionClose()` and `client.DoTimeout`, and the `DoTimeout` function has returned, the connection will never be closed.

**Comment by erikdubbelboer** [comment]
That's a good point. `DoTimeout` just makes the function return within the timeout. The actual request will keep on going in the background. The only way to make the actual request stop is using `ReadTimeout`. I guess this should be documented better.
