### ISSUE TITLE
Reduce memory allocations for io.Copy(*net.TCPConn, *fasthttp.hijackConn)

### ISSUE THREAD

**Issue by dchusovitin** [valyala/fasthttp#519]
I'm doing reverse proxy and faced with a large amount of allocated memory inside io.Copy method call.
Because fasthttp.hijackConn doesn't expose raw *net.TCPConn (via GetConn() method for example), copying between two structs (*net.TCPConn and *fasthttp.hijackConn) cannot use splice.

Golang has some memory optimizations on UNIX systems for *net.TCPConn (https://github.com/golang/go/blob/master/src/net/splice_linux.go#L17)
```
// splice transfers data from r to c using the splice system call to minimize
// copies from and to userspace. c must be a TCP connection. Currently, splice
// is only enabled if r is a TCP or a stream-oriented Unix connection.
```

Of course, I can get *net.TCPConn from *fasthttp.hijackConn through reflection (which I did).
Maybe *net.TCPConn should have public access?

Memory allocations (alloc_space):
```
// Before: go tool pprof -alloc_space
// io.Copy(*net.TCPConn, *fasthttp.hijackConn)
flat  flat%   sum%        cum   cum%
76.81GB 77.19% 77.19%    76.81GB 77.19%  io.copyBuffer

// After optimization: go tool pprof -alloc_space
// io.Copy(*net.TCPConn, *net.TCPConn)
near zero =)
```

Example server:
```go
// server.go
package main

import (
	"io"
	"log"
	"net"

	"github.com/valyala/fasthttp"
)

var (
	remote = "127.0.0.1:9090"
)

func pipe(errc chan<- error, dst, src net.Conn) {
	_, err := io.Copy(dst, src)
	errc <- err
}

func requestHandler(ctx *fasthttp.RequestCtx) {
	proxyConn, err := net.Dial("tcp4", remote)
	if err != nil {
		return
	}

	ctx.Hijack(func(localConn net.Conn) {
		errc := make(chan error, 1)
		go pipe(errc, proxyConn, localConn)
		go pipe(errc, localConn, proxyConn)
		<-errc

		return
	})
}

func main() {
	if err := fasthttp.ListenAndServe(":8080", requestHandler); err != nil {
		log.Fatalf("Error in ListenAndServe: %s", err)
	}
}
```

**Comment by erikdubbelboer** [comment]
If we would expose the `net.Conn` inside `hijackConn` so people could type cast it to a `net.TCPConn` we would have to explain really well that it can only be used for writing. If you read from the connection directly you will probably miss some data. This is because fasthttp uses a `bufio.Reader` internally which might already have some of the data you want to read buffered. This is why `hijackConn` has it's own reader and `Read` method.

**Comment by Arnold1** [comment]
hi, is it possible that func requestHandler(ctx *fasthttp.RequestCtx) can be called by multiple requests at the same time?

**Comment by Quons** [comment]
When hijackConn.Close() is called, hijackConn.Conn is set to nil, and calling io.Copy(dst, src) may result in a nil pointer exception.
Is there any solution?
