### ISSUE TITLE
maybe acquireTimer and releaseTimer be public api

### ISSUE THREAD

**Issue by xuecai** [valyala/fasthttp#525]
when write post timeout func . i need write timer myself.
 acquireTimer and releaseTimer maybe public api as tools

**Comment by erikdubbelboer** [comment]
@kirillDanshin what do you think? I think it's a good idea.

**Comment by kirillDanshin** [comment]
🤔 yes, I think that's good

**Comment by damoxinjiang** [comment]
Very nice idea! May fasthttp better and better.!

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http%3A%2F%2Fmail-online.nosdn.127.net%2F0da6f66747dad956125bb83d5d937238.jpg&name=damoxinjiang&uid=damoxinjiang%40hotmail.com&ftlId=1&items=%5B%22Email%3Adamoxinjiang%40hotmail.com%22%5D>
[http://mail-online.nosdn.127.net/0da6f66747dad956125bb83d5d937238.jpg]
damoxinjiang

Email:damoxinjiang@hotmail.com


Signature is customized by Netease Mail Master<https://mail.163.com/dashi/dlpro.html?from=mail88>

On 02/02/2019 11:16, Kirill Danshin<mailto:notifications@github.com> wrote:

🤔 yes, I think that's good

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/627d63dd25bce25772a610342afd632238463c33
