### ISSUE TITLE
SkipBody = true ignored in response if client.DoTimeout is used

### ISSUE THREAD

**Issue by enchantner** [valyala/fasthttp#529]
I have a little bit unusual case, but I need to perform GET requests ignoring the body of the response, like with HEAD requests. Fasthttp provides this by exposing SkipBody parameter (https://github.com/valyala/fasthttp/blob/master/http.go#L75), which I set manually after doing `resp := fasthttp.AcquireResponse()`.

The problem is, when using `client.DoTimeout(req, resp, timeout)`, this approach doesn't work and body is still read, because fasthttp makes an empty copy of `Response` object totally ignoring the original one: https://github.com/valyala/fasthttp/blob/master/client.go#L984 . It calls `copyToSkipBody` only for `Request`, but not for `Response` (https://github.com/valyala/fasthttp/blob/65955d6208bfd6efe330d8c37b18d6402cb1c91b/http.go#L626), and there is no easy workaround for this.

**Comment by kirillDanshin** [comment]
closed by #532
