### ISSUE TITLE
Is it OK to reuse Request?

### ISSUE THREAD

**Issue by sschepens** [valyala/fasthttp#53]
Assuming I'm going to concurrently execute the exact same request multiple times, is it OK to reuse the same Request instance or should I copy it?

**Comment by valyala** [comment]
It is unsafe using [Request](https://godoc.org/github.com/valyala/fasthttp#Request) object from concurrently running goroutines, even for marshaling the request. Make a distinct copy for each concurrent goroutine with [Request.CopyTo](https://godoc.org/github.com/valyala/fasthttp#Request.CopyTo).

Currently fasthttp provides only the following goroutine-safe instances:
* [Client](https://godoc.org/github.com/valyala/fasthttp#Client)
* [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient)

All other instances must not be used from concurrently running goroutines.

**Comment by sschepens** [comment]
Thought so, thanks!
