### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by kirillDanshin** [valyala/fasthttp#533]
We somehow managed to go from 7mln rps to 4mln rps.
That must have an urgent fix.

For some more details, see https://github.com/TechEmpower/FrameworkBenchmarks/issues/4410

**Comment by erikdubbelboer** [comment]
The last commit before 2018-10-30 was https://github.com/valyala/fasthttp/commit/afcef43292699fa1c35646db8e6423bc4417d4b3. I have been running benchmarks for the last couple of hours now comparing the performance of this commit against the performance of master and I can't see any difference so far. I'm thinking something went wrong when they ran their benchmark.

**Comment by philcaetano** [comment]
Looking at their history, https://tfb-status.techempower.com/  It looks like the drop in performance happened between Dec 3 and Dec 14.  On Dec 3 the performance was 6.6 mil after it was dropped to 4.5.  There are two commits during that time.  Can any of those be related?

**Comment by erikdubbelboer** [comment]
@philcaetano 
```
Can any of those be related?
```
No those commits have nothing to do with performance. Neither do any of the commits before or after that.

**Comment by erikdubbelboer** [comment]
I finally found the issue and fixed it in https://github.com/valyala/fasthttp/commit/02b7301203131adee3b9a91249db9c24da669f6d 🍾

**Comment by ww9** [comment]
That was fast!

Hope to see Go at the top 3 again, thanks to fasthttp contributors! 🚀
