### ISSUE TITLE
Error 7 at 1-3 Open Connections

### ISSUE THREAD

**Issue by Slind14** [valyala/fasthttp#534]
Hi there,

I'm currently at a loss as to what is bottle necking. As soon as I hit fasthttp with +1000 reqs/s (same origin), it starts to fail. Curl is throwing: `curl: (7) Couldn't connect to server`.

I'm using fasthttp with fasthttp-router and their default configurations. Seeing that `Open Connections` is always below `5` from `262144` I don't see what could be causing this and have my doubts of it being caused by the app. 

Could this be a limit from the OS it self, are there any unix settings we need to change? In terms of connections we are using `net.core.somaxconn = 16384`

Thanks for you help

**Comment by erikdubbelboer** [comment]
How are you generating the +1000 req/s?

**Comment by Slind14** [comment]
In production it is nginx -> php -> golang app. => issue appears
For testing I just sent a bunch of curl requests with a bash for loop. => issue appears

When I launch multiple instances of the go app (different ports) and load balance +1000 requests/s between them it works fine. => doesn't seem to be the available connections on the system unless there is some option tied to ports/processes

**Comment by erikdubbelboer** [comment]
The issue with bash in a for loop is probably your system running out of file descriptors sockets because they are all in TIME_WAIT state.

Do the connections from PHP to Go use keep-alive? If not that might also be the issue there. Maybe try increasing your ulimit?

**Comment by Slind14** [comment]
> Do the connections from PHP to Go use keep-alive?
I had to check the library, it looks like it disables the default keep-alive and sets custom headers for it:

```php
        $this->options[CURLOPT_FORBID_REUSE] = TRUE;
        $this->headers['Connection'] = 'Keep-Alive';
        $this->headers['Keep-Alive'] = $sec;
```
The issue is the same no matter how I configure it (default curl settings, custom headers, no keep-alive at all...) I guess this means that the keep-alive only works across the same php script execution. 

I'm gonna try increasing ulimit.

**Comment by Slind14** [comment]
Unfortunately increasing ulimit didn't change anything.

Do you have some more ideas?

**Comment by erikdubbelboer** [comment]
Have you tried using [wrk](https://github.com/wg/wrk) to see how many req/s you can get there? That should be using keep-alive out of the box.

**Comment by Slind14** [comment]
```
Running 30s test @ http://127.0.0.1:8139/
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.29ms    1.61ms  73.38ms   92.99%
    Req/Sec    27.02k     3.11k   43.36k    67.04%
  9699570 requests in 30.10s, 1.73GB read
  Non-2xx or 3xx responses: 9699570
Requests/sec: 322247.67
Transfer/sec:     58.70MB
```

**Comment by erikdubbelboer** [comment]
What status is your endpoint returning during these tests? They are all non 200.

**Comment by Slind14** [comment]
```
HTTP/1.1 405 Method Not Allowed
Server: fasthttp
Date: Sat, 09 Feb 2019 18:30:49 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 18
Allow: GET, OPTIONS
```

```
Running 30s test @ http://127.0.0.1:8139/status
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.31ms    1.37ms  42.48ms   91.42%
    Req/Sec    26.27k     3.20k   43.04k    67.13%
  9429769 requests in 30.10s, 1.20GB read
Requests/sec: 313280.40
Transfer/sec:     40.93MB
```

**Comment by erikdubbelboer** [comment]
Ok so 313280.40 req/s is a lot more than the 1000 you seem to be having issues with. So I'm afraid it has nothing to do with the Go side of things. I'm thinking maybe PHP runs out of file descriptors?

Can you run this command when you are seeing the issue: `netstat -tan | awk '$4 ~ /:80/ {print $6}' | sort | uniq -c | sort -n`

`net.core.somaxconn` has nothing to do with file descriptors and is something that doesn't really need any tuning.

**Comment by Slind14** [comment]
Current production setup with multiple golang workers and PHP picking a random one (workaround for this issue):
```
GolangAppNode #15 8139
      1 LISTEN
Nginx & PHP 443
      2 LISTEN
     25 CLOSING
    125 SYN_RECV
    286 FIN_WAIT1
    450 LAST_ACK
   2810 FIN_WAIT2
   5542 TIME_WAIT
   5687 ESTABLISHED
```

Single golang worker, PHP sends all requests to this one (connections get refused):

```
GolangAppNode #15 8139
      1 LISTEN
Nginx & PHP 443
      1 CLOSE_WAIT
      2 LISTEN
     35 CLOSING
    271 FIN_WAIT1
    281 SYN_RECV
    506 LAST_ACK
   2418 FIN_WAIT2
   4806 ESTABLISHED
   7071 TIME_WAIT
```

**Comment by erikdubbelboer** [comment]
I think the issue is PHP not using a keep-alive connection so it keeps on creating new connections and the old connections that are closing are put into TIME_WAIT state first before they can be reused. You either need to find a way for PHP to use keep-alive connections or you need to tune your `sysctl` with something like:
```
# reuse TIME_WAIT sockets
net.ipv4.tcp_tw_reuse = 1

# shorten the time we wait for the ack on our first syn
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2

# Decrease the time default value for tcp_fin_timeout connection
net.ipv4.tcp_fin_timeout = 10

net.ipv4.tcp_max_tw_buckets=6000000

# Don't reset the congestion window on keep alive connections.
net.ipv4.tcp_slow_start_after_idle = 0

# Increase the number of ports we can use (also increasing the number of connections that can be open or in time_wait).
# Default is 32768 61000
net.ipv4.ip_local_port_range = 10000 61000
```

**Comment by Slind14** [comment]
hmm, aren't those settings global? (not limit to process and or port)

**Comment by Slind14** [comment]
@erikdubbelboer I believe we looked at the wrong data. We need to filter netstat based on the receiving port:

Load balanced (<200 req/s):
```
netstat -tan | awk '$5 ~ /:8139/ {print $6}' | sort | uniq -c | sort -n
  19137 TIME_WAIT
```
Single Node (~1000 req/s): 
```
netstat -tan | awk '$5 ~ /:8139/ {print $6}' | sort | uniq -c | sort -n
      1 ESTABLISHED
  28230 TIME_WAIT
```

**Comment by erikdubbelboer** [comment]
The amount of `TIME_WAIT` is still very high and indicates no keep-alive usage.

Those settings are global yes.

**Comment by erikdubbelboer** [comment]
Seems like you need `pecl_http` for persistent connections between PHP requests: https://stackoverflow.com/a/41643667/6907368

**Comment by Slind14** [comment]
Yeah, looks like it. https://bugs.php.net/bug.php?id=71832

**Comment by Slind14** [comment]
Thank you for your help :)

**Comment by Slind14** [comment]
FYI and everyone coming along, the pecl_http package is working great:

```
      8 TIME_WAIT
     14 ESTABLISHED
```

**Comment by erikdubbelboer** [comment]
That is great to hear!

**Comment by Arnold1** [comment]
@erikdubbelboer I have a docker container with a fasthttp server running on linux. how can I check how many http connections the fasthttp server handles on that box? im looking for the linux command to check...

what happens if the fasthttp client has 10 connections and 2 threads per connection...
each worker will send with 10 qps.
what will GetOpenConnectionsCount  and GetCurrentConcurrency return in the case?
-> https://godoc.org/github.com/valyala/fasthttp#Server.GetOpenConnectionsCount and
-> https://godoc.org/github.com/valyala/fasthttp#Server.GetCurrentConcurrency

**Comment by erikdubbelboer** [comment]
`ESTABLISHED` are open connections. `FIN_WAIT2` are connections that have been closed that the kernel should cleanup after `/proc/sys/net/ipv4/tcp_fin_timeout` seconds.

If there's 10 connections then `GetOpenConnectionsCount` will return 10. `GetCurrentConcurrency` will return the number of requests being handled at that moment, so it could be less in case a connection is idle, but never more than 10.

**Comment by Arnold1** [comment]
@erikdubbelboer what I wonder is why so many connections are FIN_WAIT2 if I use keep alive? something seems wrong?

**Comment by erikdubbelboer** [comment]
If `GetOpenConnectionsCount` shows 20 then there are 20 active TCP connections to the server.

If you have connections in `FIN_WAIT2` that definitely means no all connections use keep-alive or they are getting closed. Could it for example be that you have a health check for your docker container that connects to the server and then disconnects again?
