### ISSUE TITLE
debug/perf/err log for monitor needs raddr info

### ISSUE THREAD

**Issue by xuecai** [valyala/fasthttp#535]
when i use fasthttp in production environment, i want's write some errer logs or performance logs which contans request uri and the current response server's ip address for check problem quickly。
the HostClient use conn from a pool and back when use end or close when err immediately, and there is no public api for get current request's ip address, like conn.RemoteAddr().
@erikdubbelboer  is any good idea for me to solve this question? tks.

**Comment by xuecai** [comment]
canResponse struct add  Network、Local、Remoteto for store conn.LocalAddr().Network()、conn.LocalAddr().String()、conn.RemoteAddr().String() ?

**Comment by erikdubbelboer** [comment]
I would be open to adding something like `RemoteAddr` to `Response` yes. Maybe a `net.IP`? Could you write a pull request?

**Comment by xuecai** [comment]
i think net.IP is not enouth, five info is useful.  network, localip, local port, remoteip, remoteport
network like tcp,udp , in fasthttp this maybe ignore, only tcp. 
i will try a pr . please review for it, thanks.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/10b98c2cdf73b9741b9d8eb62dda81fe315ffb8f
