### ISSUE TITLE
Response.Reset question

### ISSUE THREAD

**Issue by xuecai** [valyala/fasthttp#536]
Response.Reset not reset keepBodyBuffer, maybe this is a bug?
Response.Reset() used in func doNonNilReqResp in client.go, it will reset SkipBody which seted by Custom. maybe this is a bug? response is no need to reset in doNonNilReqResp ?

**Comment by erikdubbelboer** [comment]
I'm not sure I understand? `keepBodyBuffer` is only used internally and doesn't really need to be reset in `Response.Reset`. I'm also confused what this has to do with `doNonNilReqResp`?

**Comment by xuecai** [comment]
frist question about keepBodyBuffer, maybe this is not safe enough for it? It depends on people or test cases to make sure it's init before use.
second question about reset in doNonNilReqResp , resp is function parameter from Do , and it reset in doNonNilReqResp, it will reset public member resp.SkipBody.

**Comment by erikdubbelboer** [comment]
There's lots of behavior like that with fasthttp I'm afraid.

Setting `Response.SkipBody` for `Client` isn't supported. I'm not sure why exactly `SkipBody` is exported, it's more for internal use. But I guess we can't change this anymore now.

**Comment by xuecai** [comment]
tks, i got it

**Comment by xuecai** [comment]
[respCopy.SkipBody](https://github.com/valyala/fasthttp/blob/master/client.go#L990)   set it by self
and respCopy be reset in [resp.Reset()](https://github.com/valyala/fasthttp/blob/master/client.go#L1131) .

**Comment by erikdubbelboer** [comment]
I guess setting `SkipBody` on a request is not supported. Like I said it's more something for internal use, I have no idea why it was ever exposed 😞
