### ISSUE TITLE
example make fail !

### ISSUE THREAD

**Issue by YG-FLUSH** [valyala/fasthttp#54]
![image](https://cloud.githubusercontent.com/assets/8018232/13132764/be8185f6-d630-11e5-93c8-d115b40a5801.png)
What the hell?  I just do it  following README.md .

**Comment by YG-FLUSH** [comment]
It was blamed to the version of Go while I make it with the 1.2 version of Go, and the probem fixed by updating to 1.6

**Comment by valyala** [comment]
It looks like something is wrong with compression package used by fasthttp. @klauspost, could you look into this?

**Comment by klauspost** [comment]
Will do.

**Comment by valyala** [comment]
OK. By the way, fasthttp works only with go 1.5+

**Comment by klauspost** [comment]
NaCL (amd64p32) was added in Go 1.3, so the build doesn't exclude the platform on earlier versions.

The compress package requires/is only tested with Go 1.3+
