### ISSUE TITLE
can swapRequestBody and swapResponseBody be public api?

### ISSUE THREAD

**Issue by xuecai** [valyala/fasthttp#540]
when write post timeout func for support redirect follow . 
i write code like clientDoDeadline , but the swapRequestBody and swapResponseBody not a public api, i can't set exactly deadline time. 
i only can use DoDeadline for each redirect request.
i think request.CopyTo  is diffrent of copyToSkipBody + swapRequestBody ?

or write a support redirect follow func posttimeout pr?

**Comment by erikdubbelboer** [comment]
@kirillDanshin what do you think? Should we expand our API?
