### ISSUE TITLE
if using fasthttp.RequestCtx as context.Context, it will panic during server shutdown

### ISSUE THREAD

**Issue by peczenyj** [valyala/fasthttp#541]
If I use `*fasthttp.RequestCtx` as `context.Context`

during a `server.Shutdown()`

It will panic because we expect the context.Err() will be different than nil when the context id Done.

More information:
https://github.com/valyala/fasthttp/commit/51532b9517b3a01b442e0d58bcfd7fffbf183c68#commitcomment-32317617

related to issue #459

**Comment by peczenyj** [comment]
example of panic by composing the context with another context.
I trap signal 15 to perform a `server.Shutdown()` so to emulate this we must start an http request ( via curl )

```go
func handler(ctx *fasthttp.RequestCtx) {
  		logrus.Infof("start timeout countdown")
		c, cancel := context.WithTimeout(ctx, 5*time.Second)
		defer cancel()
		<-c.Done()
		logrus.Infof("start timeout done: %v", c.Err())
}
```

**Comment by peczenyj** [comment]
Of course, I forget update `TestShutdownDone` to check if ctx.Err() is not nil...

**Comment by Arnold1** [comment]
hi is it allowed to use ctx in context.WithTimeout and can i write to ctx after c.Done?
```
c, cancel := context.WithTimeout(ctx, 5*time.Second)
defer cancel()
<-c.Done()
ctx.Write("test")
```

**Comment by erikdubbelboer** [comment]
1) You can write to `ctx` as long as the handler that the `ctx` came from hasn't returned yet.
1) Your code looks fine yes.
1) There is always a slight overhead yes. Contexts tend to generate garbage which is also means longer garbage collection pauses.
1) You don't need to use any mutex in the example you gave.

**Comment by Arnold1** [comment]
how to avoid using context.WithTimeout to get less gc?

**Comment by erikdubbelboer** [comment]
You can't avoid garbage when you use context. Then you need to build your own timeout mechanism.

**Comment by Arnold1** [comment]
my process actually talks to another server and waits for response.... and when the outside does an timeout i want the sending to be stopped... how to achieve that?
```
func process(respChan chan<- ResultData) {
    httpReq := fasthttp.AcquireRequest()
    fhttpReq.Header.Add("Content-Type", "application/json")
    fhttpReq.Header.SetMethod("POST")
    fhttpReq.SetRequestURI(url + "/test")
    fhttpReq.SetBody(marshalledReq)
    fresp := fasthttp.AcquireResponse()
    err = fclient.DoTimeout(fhttpReq, fresp, 20*time.Second)
   
    // return fresp.Body() to the respChan
}
```

**Comment by erikdubbelboer** [comment]
I would do the same as your code but instead of using `context.WithTimeout` I would use [`fasthttp.AcquireTimer`](https://godoc.org/github.com/valyala/fasthttp#AcquireTimer).

`client.DoTimeout` is the best option then yes.

**Comment by ygqwan** [comment]
哈局21啊1啊1啊咯 1就 1`他啊11111272121@#511`![]()凡事就这么远呢？我等下就是没有来到他妈真正的脂肪。

**Comment by Arnold1** [comment]
ok, try to use fasthttp.AcquireTimer.

lets say there is a timeout how can i stop the go routine and the sending/receiving in ```func process(respChan chan<- ResultData) {```?

what does the ```20*time.Second``` in fclient.DoTimeout?

**Comment by erikdubbelboer** [comment]
```go
func process(stop *int64, resp chan<- ResultData) {
	// process...
	// You can check if you should stop using
	if atomic.LoadInt64(&stop) == 1 {
		return
	}

	resp <- ResultData{}
}

func fastHTTPHandler(ctx *fasthttp.RequestCtx) {
	stop := int64(0)
	resp := make(chan ResultData, 2)

	go process(&stop, resp)
	go process(&stop, resp)

	responses := make([]ResultData, 0, 2)

	t := fasthttp.AcquireTimer()
	defer fasthttp.ReleaseTimer()

readLoop:
	for {
		select {
		case <-t.C:
			atomic.StoreInt64(&stop, 1)
			break readLoop
		case r <- resp:
			responses = append(responses, r)

			if len(responses) == 2 {
				break readLoop
			}
		}
	}

	// ctx.Write etc...
}
```
Now to get `stop` and `resp` into pools that's quite a bit harder. You'll need to make sure all `process` functions are done before you can put it in the pool. There are ways, but it's best if you try to find out yourself first.

**Comment by Arnold1** [comment]
@erikdubbelboer 
- ```go process(&stop, resp)``` is twice, copy past error?

- right now i create a new go-routine every time fastHTTPHandler is called. is there anything i can optimize to avoid creating a single go-routine every time? creating a go-routine is also costly i guess?

**Comment by erikdubbelboer** [comment]
No, I thought you maybe wanted to do some parallel processing in multiple goroutines. Creating a goroutine is very cheap these days. But if it’s a bottleneck you could always use a goroutine pool.

**Comment by Arnold1** [comment]
i see that between 100- 1200 go routines run at the same time

**Comment by erikdubbelboer** [comment]
In the past I would have said yes. But with the recent improvements I wouldn't do this. Starting a new goroutine is really cheap in the latest Go. The overhead you're seeing is probably only a couple of microseconds (not milli, micro).
