### ISSUE TITLE
`server.Shutdown undefined` from test

### ISSUE THREAD

**Issue by shlomi-nx** [valyala/fasthttp#547]
Hi,
New go user here. I am trying this out and keeps failing. What am I doing wrong? 

```golang
package tests

import (
	"github.com/qiangxue/fasthttp-routing"
	"github.com/valyala/fasthttp"
	"testing"
)

func TestUpdateClusterStatusHandler(t *testing.T) {
	router := routing.New()

	server := fasthttp.Server{
		Handler: router.HandleRequest,
	}

	defer server.Shutdown()
}
```

```
> go test project/tests
# project/tests [project/tests.test]
project/tests/test.go:16:14: server.Shutdown undefined (type fasthttp.Server has no field or method Shutdown)
FAIL    project/tests [build failed]
```

Looking deeper, I see that `dep ensure` puts version "v20180529" in the `Gopkg.lock` and that what I get in the `/vendor` path as well. How do I get the latest version?

**Comment by savsgio** [comment]
You could modify version in Gopkg.toml setting to v1.2.0 and running again `dep ensure`

**Comment by erikdubbelboer** [comment]
I have no idea why `dep` would take such an old version. I would suggest using `go mod` instead as this is now the standard way of handling modules. `go mod` will do the right thing.
