### ISSUE TITLE
Wrong path on valid requests when error handler exists

### ISSUE THREAD

**Issue by avivpxi** [valyala/fasthttp#548]
When i register an error handler to a server instance, whenever i peeks into `ctx.Path()` method, it seem to corrupt the value of **another** request which gets handled later on.
I'm building my server with `github.com/valyala/fasthttp v1.2.0`,
and able to reproduce the issue using this hello world example:
```go
package main

import (
	"fmt"
	"github.com/valyala/fasthttp"
)

func main() {
	server := &fasthttp.Server{
		Handler: requestHandler,
		ErrorHandler: errorHandler,
		MaxRequestBodySize: 10,
		Concurrency: 1,
	}
	if err := server.ListenAndServe(":8080"); err != nil {
		fmt.Println(err)
	}
}

func requestHandler(ctx *fasthttp.RequestCtx) {
	fmt.Printf("handler requested resource: %v %v\n", string(ctx.Method()), string(ctx.Path()))
	fmt.Fprintf(ctx, "Hello, world\n")
}

func errorHandler(ctx *fasthttp.RequestCtx, err error) {
	fmt.Printf("error requested resource: %v %v\n", string(ctx.Method()), string(ctx.Path()))
	fmt.Println("error handler", err)
}

```

Note that i use `MaxRequestBodySize` to be able to trigger the error handler using the sent body size, and also note the concurrency parameter (which causes the issue to appear faster).

Now these are the steps to reproduce the issue:

`curl -XPOST http://localhost:8080/a -d 'valid body'` -> `handler requested resource: POST /a`
`curl -XPOST http://localhost:8080/b -d 'invalid body'` -> `error requested resource: POST /b`
`curl -XPOST http://localhost:8080/c -d 'invalid body'` -> `error requested resource: POST /c`
`curl -XPOST http://localhost:8080/d -d 'valid body'` -> `handler requested resource: POST /c`

Note that this result is non-deterministic, the last request can also result in `handler requested resource: POST /b`, but the value was inaccurate every time i tried these steps.

**Comment by kirillDanshin** [comment]
@avivpxi thanks for pointing out. #551 fixes this issue

**Comment by lxj15398019970** [comment]
i think this bug is still exist in v 1.50
