### ISSUE TITLE
The server use more cpu after I switch from golang 1.11 net.http to fasthttp

### ISSUE THREAD

**Issue by bronze1man** [valyala/fasthttp#549]
The server use more cpu after I switch from golang 1.11 net.http to fasthttp.

I have a process the act as reverseProxy, it is behind cloudflare cdn.
I want to use fasthttp to reduce cpu usage on my server.
The golang 1.11 net.http use 70% cpu, more then 1GB memory.
The fasthttp use 379% cpu, 401.13MB memory.
It looks like fasthttp use less memory, and use more cpu.

As the fasthttp do not support http/2. And cloudflare support it.
I doubt the http/2 and golang 1.11 net.http use less cpu than fasthttp with http/1.1 under the same load.

May relative to https://github.com/valyala/fasthttp/issues/144

Cpu usage Profile:
* With fasthttp the first cpu usage come from tls stuff.
* With golang 1.11 net.http the first cpu usage come from alloc stuff.

Alloc profile (I use debug.allocfreetrace to profile the alloc):
* With fasthttp first alloc usage come from net.conn and tls stuff.
* With golang 1.11 net.http first alloc usage come from the header map of http.Request

I use default fasthttp.Server{} setting. I only set handler to it. So the http/1.1 keep alive is enabled.

**Comment by kirillDanshin** [comment]
hi @bronze1man,
First of all, what do you use for TLS: RSA or ECDSA? RSA is pretty slow and ineffective, so I suggest checking this first.
Also, usually fasthttp trying to get things done as soon as possible, so it seemed like higher CPU usage when it is basically doing the same but made without waiting for next memory allocation.

net/http usually allocates more and spends more time waiting for allocation, so it spreads the load over time. fasthttp skips that wait time because it tries to reuse as much memory as possible.

**Comment by erikdubbelboer** [comment]
How many requests per second? Are you using keep-alive connections?

**Comment by bronze1man** [comment]
> How many requests per second?
I do not measure that. 

> Are you using keep-alive connections?
Yes, in both cases(fasthttp and net/http).

> Also, usually fasthttp trying to get things done as soon as possible, so it seemed like higher CPU usage when it is basically doing the same but made without waiting for next memory allocation.

I do not measure the requests per second when I measure the cpu usage. Maybe fasthttp process more requests than net/http. Thanks, that is a good idea to try.

**Comment by erikdubbelboer** [comment]
If with fasthttp most CPU usage goes into TLS I'm suspecting that keep-alive connections aren't being used. Setting up a TLS connections uses a lot of CPU, but once it's setup it's very fast. Can you somehow verify that it's really using keep-alive?
