### ISSUE TITLE
Question: net/http.Request.Form equivalent?

### ISSUE THREAD

**Issue by mxmCherry** [valyala/fasthttp#55]
Hi,

I have a question, if there's any analog to `http.Request.Form` container planned?
[http.Request doc](https://golang.org/pkg/net/http/#Request)

Or any convenience methods like `PeekMulti(name)` (for `fasthttp.RequestCtx` and/or `fasthttp.Request`), that peek multi params both from query and body?

I guess, this may lead to increased memory usage (for `http.Request.Form` analog) or memory allocations (for `PeekMulti(name)` methods) or be tricky to implement (pooling, if possible).

Or some kind of walker method like `.Visit(name, callback(value))` (also for `fasthttp.RequestCtx` and/or `fasthttp.Request`) would be also nice (and shouldn't result in memory allocs). Btw, I've read code for [peekArgStr](https://github.com/valyala/fasthttp/blob/master/args.go#L366) and it seems, that such `.Visit` method (that focuses on specific param name) would not provide any performance gain, as `peekArgStr` already loops through key-value pair list (and I don't think, that this should/can be optimized).

Anyway, that's just a question/suggestion; that's, obviously, not hard to work around.

**Comment by valyala** [comment]
Fasthttp already provides such methods:
- [RequestCtx.FormValue](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.FormValue) - for obtaining query value from both GET and POST requests.
- [RequestCtx.QueryArgs](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.QueryArgs) - for obtaining query value from GET request.
- [RequestCtx.PostArgs](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.PostArgs) - for obtaining query value from POST request.

Both `QueryArgs` and `PostArgs` return [Args](https://godoc.org/github.com/valyala/fasthttp#Args), which has [PeekMulti](https://godoc.org/github.com/valyala/fasthttp#Args.PeekMulti) convenience method for obtaining multiple values for the same key. `Args` also has [VisitAll](https://godoc.org/github.com/valyala/fasthttp#Args.VisitAll) method for visiting all the `(key, value)` pairs from `Args`.

**Comment by valyala** [comment]
Closing the question. @mxmCherry , feel free re-opening it if there are unanswered questions here I didn't notice.

**Comment by mxmCherry** [comment]
Not what I wanted, but thanks for replying.
