### ISSUE TITLE
Customer handler that wraps fasthttp.TimeoutHandler doesn't get 408 from ctx.Response.StatusCode()

### ISSUE THREAD

**Issue by jinfengnarvar** [valyala/fasthttp#552]
HI, currently my code has a number of request handlers chaining together for a desired server side behavior, on a high level this is what it looks like:

```
router.GET("/myendpoint",
        MyErrorLoggingHttpHandler(                      // we want to log all errors, so it's at outermost layer.
            MyContextSettingHttpHandler(                // setting the http context (including stat, timeout, cache)
                MyStatWrappingHttpHandler(              // success rate and latency stats.
                    fasthttp.TimeoutHandler(            // server side timeout.
                        MyActualHandler,                // that does the work.
                        100 * time.Milliseconds,
                        "server timeout")))))
```

The problem is when MyActualHandler times out, and fasthttp.TimeoutHandler sets the 408 into timeoutResponse, not the regular response. In my wrapper handler such as MyStatWrappingHttpHandler and MyErrorLoggingHttpHandler, they currently only call ```ctx.Response.StatusCode() == http.StatusOK``` to check errors or not to do stats or logging.

Obviously it doesn't work. Of course I can additionally call ```ctx.LastTimeoutErrorResponse``` to figure out. But it's a bit inconvenient. Just wondering what the design rationale behind this separate of response is?

**Comment by jinfengnarvar** [comment]
I suspect that maybe one of the reasons is that you want to separate the response body and status code so the timeout status code/body msg are not "contaminated" by the still outstanding inner handler, so the server can always reliably and cleanly return 408 + the timeout msg?

**Comment by erikdubbelboer** [comment]
Exactly. While the timeout response is being returned `MyActualHandler` is still running and can still make modifications to the original response. If we would allow this we will have a race condition and very undefined behavior.
I'm afraid using `ctx.LastTimeoutErrorResponse()` is really the only way.
