### ISSUE TITLE
It's better to use static objects pool rather than sync.Pool

### ISSUE THREAD

**Issue by caibirdme** [valyala/fasthttp#553]
I'm developing a proxy server based on fasthttp, but found some performance bottleneck within the fasthttp itself. Below is my pprof flame graph for heap:
<img width="1097" alt="flamegraph-1" src="https://user-images.githubusercontent.com/8054803/53774599-1e3cfb00-3f2a-11e9-95b8-da78a8585f2c.png">
From the graph, fasthttp allocate almost all objects and most of those objects are created from here:
<img width="896" alt="sourcecode" src="https://user-images.githubusercontent.com/8054803/53774987-aa9bed80-3f2b-11e9-998b-6f55c3f71caf.png">
Because I use short connection---"Connection: Close", which results in serveConn break from the loop, and every time acquire a new bufio.Reader. Though fasthttp use sync.Pool to store these buffer, it will be all cleared once GC occur and fasthttp have to create more new bufio.Readers.
Under high pressure, say 15K QPS, gc dominates the process:
<img width="533" alt="gc" src="https://user-images.githubusercontent.com/8054803/53775592-24cd7180-3f2e-11e9-8e0b-e69ad575379c.png">
I suggest that fasthttp could maintain a length-fixed(an option for user) buffer pool through out the lifetime of the process and reuse buffer from that pool rather than from sync.Pool. Use sync.Pool only when there's no available buffer in buffer pool.

**Comment by erikdubbelboer** [comment]
I'm wondering if its better to create our own pool that doesn't get cleared or wait for this to be merged: https://go-review.googlesource.com/c/go/+/162919

You could benchmark changing `acquireReader` and `releaseReader` to:
```go
var readerPool = make(chan *bufio.Reader, 10240)

func acquireReader(ctx *RequestCtx) *bufio.Reader {
	var r *bufio.Reader
	select {
	case r = <- readerPool:
	default:
	}

	if r == nil {
		n := ctx.s.ReadBufferSize
		if n <= 0 {
			n = defaultReadBufferSize
		}
		return bufio.NewReaderSize(ctx.c, n)
	}
	r.Reset(ctx.c)
	return r
}

func releaseReader(s *Server, r *bufio.Reader) {
	select {
	case readerPool <- r:
	default:
	}
}
```

**Comment by caibirdme** [comment]
We need two pools, one for reader and one for writer. And I think it's better to implement a concurrent buffer pool rather than channel, cause it would affect the schedule. I will test it as soon as possible

**Comment by caibirdme** [comment]
@erikdubbelboer I don't have access to test this change in our production, just do it on my own PC. Using channel is just no more than 10% faster compared to sync.Pool. But this is obviously based on how I test it, and channel also brings new overhead here(lock, scheduler, etc...). I know this conclusion isn't convincing, but is it better to give users a chance to implement their own `acquireWriter/Reader`, which means making acquireWriter and acquireReader as interface and configurable in Server struct. So that User could pre-allocate an array(depends on their use case) to store the buffer, which would significantly reduce  the burden of garbage collector

**Comment by erikdubbelboer** [comment]
But those aren't the only pools. If we do that we would have to expose all these pools:
https://github.com/valyala/fasthttp/blob/517df8833274a3bf8c1377ceec64a8f131876cb7/server.go#L352-L356
I'll do some benchmarks this weekend and see how much things improve using other pool implementations. But I still maintain that I'd rather wait until `sync.Pool` gets improved as that can do optimizations that are unable for us to do that could always make it faster.

**Comment by erikdubbelboer** [comment]
I wrote a benchmark and tried `sync.Pool`, `chan interface{}` and `[]interface{}` against each other.

See: https://gist.github.com/erikdubbelboer/c956534efd311d069e0dd14c628936ac

Only with really big request and response bodies and GC running unrealistically often it makes a difference to not use `sync.Pool`. I think in almost all common cases the difference in neglectable.
For this reason I prefer to wait until `sync.Pool` gets improved instead of adding new functionality and exposing new public methods/fields that we would have to maintain in the future as well. Once `sync.Pool` doesn't empty on GC anymore it will be impossible to beat with your own code as it can do per core optimizations that are impossible in user land.

**Comment by erikdubbelboer** [comment]
In your original post you wrote `Under high pressure, say 15K QPS, gc dominates the process`. Have you used `pprof` to determine which objects get allocated and collected a lot?

**Comment by erikdubbelboer** [comment]
A fix has just been merged into Go: https://github.com/golang/go/commit/2dcbf8b3691e72d1b04e9376488cef3b6f93b286
