### ISSUE TITLE
What's the behavior during HTTP pipeline

### ISSUE THREAD

**Issue by 1a1a11a** [valyala/fasthttp#555]
Hi there, 
     I would like to know if I have a client keeps sending HTTP requests (using persistent connection, in other words same TCP connection), while some requests takes longer than other, will this cause head of line blocking? In other words, for requests coming from same TCP connection be handled concurrently or sequentially?

**Comment by erikdubbelboer** [comment]
Yes this will cause head of line blocking because http 1 requires to send the responses in the same order. Fasthttp will process the requests one by one, not in parallel.

**Comment by 1a1a11a** [comment]
Thank you for confirming this!
