### ISSUE TITLE
what is server specification of VertaMedia

### ISSUE THREAD

**Issue by sajadabasi** [valyala/fasthttp#557]
Hi,
In description you have said:
> Currently fasthttp is successfully used by VertaMedia in a production serving up to 200K rps from more than 1.5M concurrent keep-alive connections per physical server.

what is the server specification of VertaMedia that handle these much of requests?

**Comment by dgrr** [comment]
I think VertaMedia (Adtelligent currently) is an SSP (Supply Side Platform) that serves ad contents to their clients. This is why they handle that number of request.

**Comment by erikdubbelboer** [comment]
They are probably doing bidding using OpenRTB. So it will be lots of requests from a couple of servers (not directly from browsers) which send small JSON payloads which they have to respond with small JSON payloads as well.

What kind of server you need for 200k RPS completely depends on how much processing you're going to do per request.

Keep in mind that handling 200k keep-alive connections will also requite some kernel tuning.
