### ISSUE TITLE
Why the request time goes longer after serval hours loop running?

### ISSUE THREAD

**Issue by Jolly23** [valyala/fasthttp#559]
```golang
func getBalance(retCh chan *AsyncBalResult) (error, []byte)  {
        req, resp := fasthttp.AcquireRequest(), fasthttp.AcquireResponse()
	req.SetRequestURI(c.BaseURL + endPoint)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept-Encoding", "gzip")
	req.Header.SetMethod(string(method))
	req.SetBodyString(getSignParam(params))

	err := fasthttp.DoTimeout(req, resp, time.Duration(3)*time.Second)
        retCh <- &AsyncBalResult{
                ......
        }
	return err, resp.Body()
}
```

```golang
for {
        resCh := make(chan * AsyncBalResult, 16)

        go getBalance(resCh)
        go getBalance(resCh)

        for i := 0; i < 2; i++ {
                ......
                <No problem here>
                res := <-resCh
                ......
        }
        time.Sleep(10*time.Second)
}
```

I have codes above. 
I run 2 getBalance requests at the same time in a nonstop loop:

At the beginning of running, it works well, the requests could finish in 0.03s

However, after a half hours or more, its finish time will increase to 0.5s
That's a big problem for me.

Could someone tell me why?

Should I close req or resp after I use them?

Or is there any memory leakage?
Or something stuck?

**Comment by kirillDanshin** [comment]
@Jolly23 try to release Request and Response. You acquired it, but you didn't release it back.
also by the Go conventions, the error goes last in return parameters, not like in JS callback conventions, where it go first; but that's a minor notice.

**Comment by Jolly23** [comment]
@kirillDanshin thanks for your reply.

But I don’t know how can I release them. 
Could you please make it more clear?

I tried but they don’t have like req.Close() function.

**Comment by erikdubbelboer** [comment]
Can you please post the whole function. You're returning `respBytes` but that isn't defined. It's really hard to tell what's happening without the whole picture.

**Comment by Jolly23** [comment]
@erikdubbelboer 
No problem, I edited the issue and pasted almost raw codes.
I was supposed to that I just need a simple code to show my problem.

**Comment by erikdubbelboer** [comment]
What is happening here?
```go
        retCh <- &AsyncBalResult{
                ......
        }
```

And why are you returning `resp.Body`? That doesn't make sense and isn't even valid code.

**Comment by Jolly23** [comment]
@erikdubbelboer 
Thanks for your reply.
I swear that there is no problem, it just creates a variable and passes it to the channel, no stuck.
resp.Body is a mistake I paste codes here. It is resp.Body(). 
Thanks.

**Comment by Jolly23** [comment]
This made me lose 1k USD in tonight's BTC pump trade.

**Comment by erikdubbelboer** [comment]
It doesn't make sense to return anything if you run the function in a goroutine and ignore the return value. But that's not the issue.

Its really hard to help you if you're not showing me all the code! Like, what is happening in that `AsyncBalResult` block? Do you do anything with `resp` there?

Are you sure that your program is the issue and it's not just the endpoint really getting slower and slower instead?

How often are you doing this? Are we talking about lots of requests per second or is it really only 2 requests every 10 seconds? In other words, could your code be generating so much garbage that the garbage collector is slowing it down?

How are you measuring these 0.03s and 0.5s? Can I see that code?

**Comment by Jolly23** [comment]
@erikdubbelboer 
I am pretty sure that My code works well
The only part that I don't know is about fasthttp.

I don't use resp and req in that block.

When transactions are frequent, it sends 5 requests per second. 
When there is no transaction, it works 2 times pre 10s.

I have time.Duration() to measuring time.

**Comment by erikdubbelboer** [comment]
Since the request is always fast, can you try this:
```go
func getBalance(retCh chan *AsyncBalResult) {
        req, resp := fasthttp.AcquireRequest(), fasthttp.AcquireResponse()
        defer fasthttp.ReleaseRequest(req)
        defer fasthttp.ReleaseResponse(resp)

	req.SetRequestURI(c.BaseURL + endPoint)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept-Encoding", "gzip")
	req.Header.SetMethod(string(method))
	req.SetBodyString(getSignParam(params))

	fasthttp.Do(req, resp)

        retCh <- &AsyncBalResult{}
}
```

Can I see the timing code?

**Comment by Jolly23** [comment]
@erikdubbelboer 
Wow, Thanks!
I am looking for how to release req and resp codes. You did it!

The timing code:
```golang
	st := time.Now().UnixNano()
        ......
        time.Duration(time.Now().UnixNano() - st).Seconds()
```

**Comment by erikdubbelboer** [comment]
It doesn't get slower anymore?

**Comment by Jolly23** [comment]
@erikdubbelboer 
It needs time to finish the real trading test.
Because what happened in the bitcoin market yesterday is not always happens.
That is very high-frequency trading on that day which has never been seen in this year.

**Comment by Jolly23** [comment]
@erikdubbelboer 
Thank you!

**Comment by erikdubbelboer** [comment]
@Jolly23 are you still seeing this issue using `.Do`?
