### ISSUE TITLE
sub runtime in handler

### ISSUE THREAD

**Issue by Mjiulee** [valyala/fasthttp#562]
i want to do some time consume job in my website

step:
1、client post request to start a job , serve will return a job id immediately
2、server process the job and notify client with websocket msg 

here is my code 
`
func jobRegistHandler(ctx *fasthttp.RequestCtx) {
    // come code for prepare
   ......
    // start runtime to process job 
    go doProcess()
    
  // return to client immediately
   ctxExt.JSON(200, response)
}
`

but , with this code , http do not return immediately
it return after untill the doProcess() finished 
 
any idea for this problem?  thanks

**Comment by erikdubbelboer** [comment]
The request should always return when your handler returns. Can you post your whole function so we can see what is happening there?

**Comment by Mjiulee** [comment]
sorry for this , finally it was my redis timeout cause this problem
