### ISSUE TITLE
What's the difference among many timeouts

### ISSUE THREAD

**Issue by caibirdme** [valyala/fasthttp#563]
There're many timeout related configurations, but some of those comments are a little bit vague.

```
	// Maximum duration for reading the full request (including body).
	//
	// This also limits the maximum duration for idle keep-alive
	// connections.
	//
	// By default request read timeout is unlimited.
	ReadTimeout time.Duration

	// Maximum duration for writing the full response (including body).
	//
	// By default response write timeout is unlimited.
	WriteTimeout time.Duration
```

* For ReadTimeout, when it starts timing? Does it mean that a keep-alive connection can be used no more than ReadTimeout, no matter how many times it has been used? What's the difference between ReadTimeout and MaxKeepaliveDuration?
* WriteTimeout, when it starts timing?
* What should I set if I expect an incoming request is processed no more than X seconds,  and will get a error if timeout?

**Comment by erikdubbelboer** [comment]
I'm looking into possible causes for https://github.com/valyala/fasthttp/issues/491#issuecomment-482769451 and I think I'll rewrite part of the timing code as its very unclear now and has the potential for some race conditions. I'll document these variables more properly with this as well.

**Comment by caibirdme** [comment]
@erikdubbelboer Do you have any plan about rewriting those timing codes, I think it would be better if fasthttp's timeout can be the same as net/http. And I'm willing to provide help if you need

**Comment by erikdubbelboer** [comment]
`ReadTimeout` and `WriteTimeout` are already the same. 

`MaxKeepaliveDuration` doesn't make any sense. It counts from the start of the connection and kills the connection after the duration no matter if it's still serving requests or not. I want to get rid of this as the whole concept doens't make sense and confuses people.

Instead we should probably introduce an `IdleTimeout` like `net/http.Server` has. Seems like many people think this is what `MaxKeepaliveDuration` is.

**Comment by erikdubbelboer** [comment]
@caibirdme see the new documentation changes in: https://github.com/valyala/fasthttp/pull/564

**Comment by Arnold1** [comment]
im using fasthttp v1.1.0 whats the right way to set MaxKeepaliveDuration, ReadTimeout and WriteTimeout?

**Comment by erikdubbelboer** [comment]
I suggest upgrading to v1.3.0 for bugfixes and other improvements.

In 1.3.0 `MaxKeepaliveDuration` is deprecated, don't use it. `IdleTimeout` is what you want instead. All the timings depend on your use case and who is on the other side of the connection.
