### ISSUE TITLE
How to support auth while there is no auth API

### ISSUE THREAD

**Issue by supercz** [valyala/fasthttp#566]
Issue #79 mentioned there is a way to manually set and parse request headers, but how?

**Comment by erikdubbelboer** [comment]
You can just use `ctx.Request.Header.Peek("Some-Auth-Header")` to get the value of your header and parse the value in your code. And `ctx.Response.Header.Set("Some-Auth-Header", "some-value")` to set the value in your response. Assuming you are talking about the server side of things.

**Comment by supercz** [comment]
Well, mine is client side, I put Auth information in URI，and the problem solved. Thanks anyway!
