### ISSUE TITLE
fastthtp not starting (at times)

### ISSUE THREAD

**Issue by em9999** [valyala/fasthttp#568]
Hello,

We have an application using fasthttp in production, which after an app restart, it *sometimes* won't start listening on its designated port. Unfortunately, it won't give us any kind of error, everything seems to be executing as it should. We are currently calling this function through a coroutine, and we try to start listening on 2 different ports.

-- We are not using reuse port.

```go
func start_http_server(config *FastHTTPConfigType){
	var ln net.Listener
	var err error

	for _, port := range config.ListenOnPorts{
		go func(config *FastHTTPConfigType, port string){
			port=":"+port
			fmt.Printf("Starting HTTP Server (fasthttp) on port %v \n", port)

			if(config.ReusePort==true){
				ln, err = reuseport.Listen("tcp4", port)
				if err != nil { 
					fmt.Printf("error in reuseport listener: %s %s\n" , err.Error(), port)
				}
			}else{
				ln, err = net.Listen("tcp4", "0.0.0.0" + port)
				if err != nil {
					fmt.Printf("error in ListenAndServe: %s\n", err)
				}
			}
			fmt.Printf("Listener created on port %v \n", port)

			h:=RouteIt
			if(config.UseGzipCompression==true){
				h = fasthttp.CompressHandlerLevel(h, fasthttp.CompressBestSpeed)
			}
			
			s := &fasthttp.Server{
				Handler: h,
				Name				:config.Name,
				ReadBufferSize		:config.ReadBufferSize,
				WriteBufferSize		:config.WriteBufferSize,
				MaxKeepaliveDuration:config.MaxKeepaliveDuration*time.Second,
				ReadTimeout			:config.ReadTimeout*time.Second,
				WriteTimeout		:config.WriteTimeout*time.Second,
				MaxConnsPerIP		:config.MaxConnsPerIP,
				MaxRequestsPerConn	:config.MaxRequestsPerConn,
			}

			if err := s.Serve(ln); err != nil {
				fmt.Printf("error in ListenAndServe: %s", err)
				log.Fatalf("error in ListenAndServe: %s", err)
			}
		}(config, port)
	}
}
```
Is there anything we are doing that could be producing this behaviour?

Thanks!

**Comment by erikdubbelboer** [comment]
Your code looks normal to me. Does it print `Listener created on port` when this happens?

**Comment by em9999** [comment]
Yes, it prints it.

When debugging I've also added a few more println points to ensure it reached to s.Serve and it did without problem.

I did observe that a few times a println after s.Serve() will print out, without any error, nor any port being listened to:

if err := s.Serve(ln); err != nil {
	fmt.Printf("error in ListenAndServe: %s", err)
	log.Fatalf("error in ListenAndServe: %s", err)
}
println("We are here").

With err being nil.

**Comment by erikdubbelboer** [comment]
`s.Serve` will return nil if calling accept on the listener returns `io.EOF`, meaning it is closed. I don't think your issue is with fasthttp but with your listener. Which OS are you on?

Can you change this:
```go
	ln, err = net.Listen("tcp4", "0.0.0.0" + port)
	if err != nil {
		fmt.Printf("error in ListenAndServe: %s\n", err)
	}
```
to:
```go
	ln, err = net.Listen("tcp4", "0.0.0.0" + port)
	if err != nil {
		panic(err)
	}
```
and try again? You're only printing and error but not stopping there right now.

**Comment by em9999** [comment]
Unfortunately that panic (from your example), never happens. I've been testing this a lot, and the only times this seems to fail is when the code is within a goroutine:

for _, port := range config.ListenOnPorts{
		go func(config *FastHTTPConfigType, port string){

However, if we remove that:
     for _, port := range config.ListenOnPorts{
		func(config *FastHTTPConfigType, port string){

We don't see it failing (at least till now.)

Is there any logic behind that?

We are using: go version go1.12.4 linux/amd64 to compile. This behaviour seems to be both working at Ubuntu x64 server and Centos x64.

**Comment by erikdubbelboer** [comment]
What happens in your code after `start_http_server` is done?

**Comment by em9999** [comment]
start_http_server is the last step in our app.

func main(){
......
go start_http_server(&config.Object.FastHTTPConfig)
if(config.DebugConfig.EnableProfiling==true){
	log.Println(http.ListenAndServe("0.0.0.0:1111", nil))
}

select{}
}

config.DebugConfig is set to false on this scenario.

**Comment by erikdubbelboer** [comment]
Does it always print the `fmt.Printf("Listener created on port %v \n", port)` line, even when it isn't working?

**Comment by em9999** [comment]
yes it prints it.

**Comment by erikdubbelboer** [comment]
Can you add another print statement after
```go
if err := s.Serve(ln); err != nil {
	fmt.Printf("error in ListenAndServe: %s", err)
	log.Fatalf("error in ListenAndServe: %s", err)
}
```
And see if it reaches that?

How are you testing if it is working or not?

**Comment by erikdubbelboer** [comment]
I don't mean inside the if, I mean:
```go
if err := s.Serve(ln); err != nil {
	fmt.Printf("error in ListenAndServe: %s", err)
	log.Fatalf("error in ListenAndServe: %s", err)
}
log.Fatalf("This should never be reached")
```

How do you manually test it? Can you check on the server if the process has a listening socket on the port? Otherwise can you use `curl -v http://...` and paste the response here?

**Comment by em9999** [comment]
ok just tried with that fatalf (and using the original code with the goroutine). I restarted the service a few times until I could reproduce the problem. Had to do it about 4 times, at the next one, we got that error.

Right now the app is set to listen on 2 different ports (hence the reason you see a for and a go func(...):

output of curl -v:  (i've replaced the IP due to security concerns)

*   Trying 1.1.1.1...
* connect to 1.1.1.1 port 80 failed: Connection refused
* Failed to connect to 1.1.1.1 port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 1.1.1.1 port 80: Connection refused

On netstat, I don't see port 80 being listened, however, the second port we set it is being listened and we can access it.

**Comment by erikdubbelboer** [comment]
If you're getting `connect to 1.1.1.1 port 80 failed: Connection refused` it means the process isn't even listening. Which means it has nothing to do with fasthttp. Either the `ln, err = net.Listen("tcp4", "0.0.0.0" + port)` is not working, but you already change the print after that to a panic and that didn't crash anything. Or there is something wrong with your `config.ListenOnPorts` and the code to start a listener is never started. Or your program isn't started at all.
