### ISSUE TITLE
Is there any way to integrate autocert?

### ISSUE THREAD

**Issue by twharmon** [valyala/fasthttp#569]
`http.Server` has a public field `TLSConfig` which takes`&autocert.Manager.TLSConfig()`. This is convenient for custom `HostPolicy`s. Is there a way to do the same thing in a `fasthttp.Server`?

See https://godoc.org/golang.org/x/crypto/acme/autocert for more info.

**Comment by erikdubbelboer** [comment]
You could for example use https://godoc.org/golang.org/x/crypto/acme/autocert#NewListener and pass the listener to https://godoc.org/github.com/valyala/fasthttp#Serve
