### ISSUE TITLE
How can fasthttp support swagger?

### ISSUE THREAD

**Issue by golangfxi** [valyala/fasthttp#570]
I didn't find any related items on the search engine.
How can I achieve this function?
Because swagger is not currently supported. So I need to write additional documents for clients to use. 
I need help  ~ ~

**Comment by erikdubbelboer** [comment]
Looks like swagger only generates a `net/http` framework. But I have never worked with it before so I have no idea.

**Comment by savsgio** [comment]
I think so you could use [fasthttpadapter](https://github.com/valyala/fasthttp/blob/master/fasthttpadaptor/adaptor.go#L13) to wrap swagger handler.
