### ISSUE TITLE
why use panic?

### ISSUE THREAD

**Issue by goith** [valyala/fasthttp#574]
https://github.com/valyala/fasthttp/blob/3bfa86f572c7e7f31c9d8d694b30599bab813751/http.go#L828

**Comment by erikdubbelboer** [comment]
Do you have a case where this panic is tiggered? It should never happen which is something `panic` was designed for.

**Comment by toby3d** [comment]
@erikdubbelboer Try get MultipartForm from RequestCtx with nil body and without multipart header.

**Comment by erikdubbelboer** [comment]
Ok lets change it into a normal error. Do you want to make a pull request or should I fix it?

**Comment by toby3d** [comment]
@erikdubbelboer I can try replace that panic on error return. Whats message can explain clearly this bug? :thinking:

**Comment by erikdubbelboer** [comment]
After this
https://github.com/valyala/fasthttp/blob/3bfa86f572c7e7f31c9d8d694b30599bab813751/http.go#L725
I would add:
```go
var ErrNoMultipartFormBody = errors.New("can not read multipart/form-data from an empty body")
```

And then instead of the panic:
```go
return nil, ErrNoMultipartFormBody
```

**Comment by erikdubbelboer** [comment]
Test it with your own code first to see if this helps you fix your issue.
