### ISSUE TITLE
ctx.Error() clears headers, even though "Fasthttp allows setting response headers and writing response body in an arbitrary order."

### ISSUE THREAD

**Issue by iivvoo** [valyala/fasthttp#578]
I have the following piece of middleware, which is, in a way, just a fasthttp RequestHandler:

```
func BasicAuthMiddleware(options *Options, h RouteHandler) RouteHandler {
	return func(ctx *fasthttp.RequestCtx, vars RouterVars) {

		ctx.Response.Header.Set("WWW-Authenticate", `Basic realm="Restricted"`)
		_, password, ok := basicAuth(ctx)

		if !ok {
			ctx.Error("Not authorized", fasthttp.StatusUnauthorized)
			return
		}

		if password != options.AdminPassword {
			ctx.Error("Not authorized", fasthttp.StatusUnauthorized)
			return
		}

		h(ctx, vars)
	}
}
```

Even though the WWW-Authenticate header is always set, it is removed when ctx.Error() is invoked. Setting the header after ctx.Error() does work.

This contradicts with the net/http Error() function which preservers headers and with the statement that 

> Fasthttp allows setting response headers and writing response body in an arbitrary order.

I can think of workarounds (setting the header afterwards, not using ctx.Error()) but the current behaviour is inconsistent/confusing and should at least be documented.

**Comment by erikdubbelboer** [comment]
I agree this should be documented. I'm afraid we can't change the behavior of `RequestCtx.Error` as that would potentially break all current users of this function.
