### ISSUE TITLE
What is the best way to read headers ?

### ISSUE THREAD

**Issue by djannot** [valyala/fasthttp#58]
The only way I found is to get use RequestCtx.Header.String() and to parse them, but I think it would be easier to provide a function for this, no ? Or perhaps, I missed it.

**Comment by valyala** [comment]
See the following [RequestHeader](https://godoc.org/github.com/valyala/fasthttp#RequestHeader) methods:
- [RequestCtx.Header.Peek](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Peek) - for obtaining a single request header value by name.
- [RequestCtx.Header.VisitAll](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.VisitAll) - for iterating all the headers in the request.

There are a lot of other useful [RequestHeader](https://godoc.org/github.com/valyala/fasthttp#RequestHeader) methods too.

**Comment by valyala** [comment]
Closing the issue. Feel free re-opening it if you have related questions

**Comment by djannot** [comment]
Thanks !
