### ISSUE TITLE
Context not use scheme from X-Forwarded-Proto header

### ISSUE THREAD

**Issue by toby3d** [valyala/fasthttp#580]

**Comment by kirillDanshin** [comment]
Can we have some details on your case?

**Comment by erikdubbelboer** [comment]
We don't use `X-Forwarded-Proto` or `X-Forwarded-IP` because those are not from the real request that you are receiving. If you're interested in these headers you can easily parse them yourself.

**Comment by kirillDanshin** [comment]
basically, we even have an example of using such headers in gramework's `Behind` feature. note: you should remember to check if you get X-Forwarded-{Proto,IP} from a trusted source
