### ISSUE TITLE
cookie should support cookie option SameSite=None

### ISSUE THREAD

**Issue by peczenyj** [valyala/fasthttp#582]
Reason

> Chrome 76 introduces a new `same-site-by-default-cookies` flag. Setting this flag will shift the default behaviour of `Set-Cookie` to apply `SameSite=Lax` if no other `SameSite` value is provided.

https://web.dev/samesite-cookies-explained/
https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html

I'd like to set `SameSite=None` and ignore chrome's default behaviour

**Comment by erikdubbelboer** [comment]
See: https://github.com/valyala/fasthttp/pull/581
