### ISSUE TITLE
Example for fasthttp, fasthttprouter and quicktemplate combining

### ISSUE THREAD

**Issue by AndriiHanenko** [valyala/fasthttp#584]
Can`t figure out how to combine those three packages to make it work. Could somebody show me like thread that flushes throught? Or give some example, cause its blow my mind)

**Comment by kirillDanshin** [comment]
fasthttprouter provides handler separation by URLs. It still gives you RequestCtx, as you usually get with raw fasthttp. Quicktemplate templates accepts Writer as it's first argument. RequestCtx implements Writer, so it should just work.
