### ISSUE TITLE
why I cannot listen 80 and 443 both?

### ISSUE THREAD

**Issue by 59duncom** [valyala/fasthttp#585]
code that:

package main

import (
    "fmt"
    "github.com/valyala/fasthttp"
)
func Index( ctx *fasthttp.RequestCtx){
    ctx.WriteString("index")
}
func main() {

    https:=&fasthttp.Server{ Handler:Index }
    web:=&fasthttp.Server{ Handler:Index }
    https.AppendCert("./ssl/shangpu6666.com.pem" ,"./ssl/shangpu6666.com.key" )
    https.AppendCert("./ssl/xtx0523.com.pem" ,"./ssl/xtx0523.com.key" )
    fmt.Println(https.ListenAndServeTLS(":443","",""))
    fmt.Println( web.ListenAndServe(":80"))
    
}

When I put https.ListenAndServeTLS(":443","","")first ,then 443 listened,80 failed.
When I put web.ListenAndServe(":80") first,80 listen,443 failed

**Comment by AndriiHanenko** [comment]
![Знімок екрана  о 14 34 08](https://user-images.githubusercontent.com/50235170/58703412-4618ef00-83b1-11e9-93b0-684ba2ffec5e.png)

**Comment by dgrr** [comment]
Listen calls are blocking.

```go
go fmt.Println(https.ListenAndServeTLS(":443", "", ""))
fmt.Println( web.ListenAndServe(":80"))
```

**Comment by 59duncom** [comment]
thanks

**Comment by kirillDanshin** [comment]
I think this issue is solved. If you have additional questions, feel free to ask in a new issue.
