### ISSUE TITLE
Any tarpit / purposefully dropping connection for malicious attacks?

### ISSUE THREAD

**Issue by hiqbn** [valyala/fasthttp#586]
Any tarpit / purposefully dropping connection for malicious attacks?
I'm looking for fasthttp equivalent of tarpitting / dropping slowloris kind of attacks.

**Comment by kirillDanshin** [comment]
I've tested slowloris kind of attacks for fasthttp couple of weeks ago and I wasn't able to make any damage or DDoS. If you were able, please see [SECURITY.md](https://github.com/valyala/fasthttp/blob/master/SECURITY.md) for instructions, we'll be glad to receive such report.

If we look into another level of attacks, such as application-level vectors, you can see [Gramework](github.com/gramework/gramework)'s Protection as an example implementation of Whitelists, Blacklists and more.

Injection attacks tho, kinda difficult to detect and filter while maintaining low false-positives and high correct detection rate. E.g, mod_security can be bypassed and also easy to misconfigure, which bumps false-positives, etc. This kind of attacks can be detected and dropped using third-party WAF provider, but it depends of your project.

**Comment by hiqbn** [comment]
if u are referring to this
https://github.com/gramework/gramework/blob/dev/app_protection.go

i gave a quick glance and saw you didnt have an option to unban or untime the ban...
it's ok. it's well written anyhow.

back to my question
Any tarpit / purposefully dropping connection for malicious attacks? (how do i achieve this) what do we do after we blacklist the remote ip?

how to "drop" connection for the purpose of hiding the fact that we "dropped" the connection silently from the malicious attacker's point of view.

would like a suggestion on how to do tarpit too, with fasthttp

**Comment by erikdubbelboer** [comment]
This is more in scope for a separate library or a framework. Fasthttp is really meant as a low level library for http, nothing more.
