### ISSUE TITLE
I had write a simply httpproxy by fasthttp,but I had test the speed find the qps is so bad

### ISSUE THREAD

**Issue by 59duncom** [valyala/fasthttp#587]
fasthttp proxy  wrk report that:

```
  ./wrk -c 1000 -t 1000 -d 30s http://127.0.0.1:8080/
Running 30s test @ http://127.0.0.1:8080/
  1000 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   123.28ms  283.75ms   1.99s    88.85%
    Req/Sec    49.95     49.44   653.00     68.67%
  103307 requests in 30.12s, 12.31MB read
  Socket errors: connect 0, read 0, write 0, timeout 2795
  Non-2xx or 3xx responses: 2136
Requests/sec:   3429.97
Transfer/sec:    418.45KB
```

I use nginx proxy reports this:
```
 ./wrk -c 1000 -t 1000 -d 30s http://127.0.0.1:5555/
Running 30s test @ http://127.0.0.1:5555/
  1000 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   245.24ms  329.09ms   1.25s    79.48%
    Req/Sec    42.25     35.39     1.97k    60.26%
  434163 requests in 30.11s, 100.60MB read
  Socket errors: connect 0, read 0, write 0, timeout 604
Requests/sec:  14421.42
Transfer/sec:      3.34MB
```

the fasthttp proxy code is that:
```
package main
import (
    "github.com/valyala/fasthttp"
    "time"
)
func test(ctx *fasthttp.RequestCtx){
  time.Sleep(100)
  ctx.WriteString("ok ")
}
func proxytest( ctx *fasthttp.RequestCtx){

    s:= &fasthttp.HostClient{Addr:"127.0.0.1:666"}
    req:=fasthttp.AcquireRequest()
    resp:=fasthttp.AcquireResponse()
    defer fasthttp.ReleaseRequest(req)
    defer fasthttp.ReleaseResponse(resp)
    ctx.Request.CopyTo(req)
    err:=s.Do(req,resp )
    if err!=nil{
        ctx.Error(err.Error(),504  )
    }
    resp.Header.Add("Server","waf")
    resp.WriteTo( ctx.Conn())
}
func main() {

    web:=&fasthttp.Server{Handler:proxytest }
    test:=&fasthttp.Server{ TCPKeepalive:true,TCPKeepalivePeriod:30*time.Second  ,  Handler:test }
    go test.ListenAndServe(":666")
    web.ListenAndServe(":8080")
    
}
```

the nginx conf is that:
```
location /
{
    proxy_pass http://127.0.0.1:666;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    

    add_header X-Cache $upstream_cache_status;
    
    
}
```

why nginx is Requests/sec:  14421.42 ,but the fasthttp proxy is Requests/sec:   3429.97.
how to improve my code

**Comment by erikdubbelboer** [comment]
Try putting the `fasthttp.HostClient` outside if the function. Right now you are creating a new `fasthttp.HostClient` and setting up a new connection for each request instead of reusing keep-alive connections like nginx does.

But even with that fixed fasthttp is always going to be slower than nginx seeing as nginx is written in C which allows for many more optimizations for something like this.

**Comment by 59duncom** [comment]
do you mean this：
var s= &fasthttp.HostClient{Addr:"127.0.0.1:666"}
func proxytest( ctx *fasthttp.RequestCtx){
...
}?
put the fasthttp.HostClient out of function can do like the http.transport?

**Comment by erikdubbelboer** [comment]
Exactly.

**Comment by erikdubbelboer** [comment]
Does that improve the Requests/sec?

**Comment by 59duncom** [comment]
but now is error that :no free connections available to host

**Comment by 59duncom** [comment]
I had set var s= &fasthttp.HostClient{Addr:"127.0.0.1:666",MaxConns:10000},and try this

**Comment by erikdubbelboer** [comment]
Are you running this as root? Or did you give the process enough file descriptors?

**Comment by 59duncom** [comment]
yes is root,now I set MaxConns:10000.
I cannot believe that fasthttp is fast a lot than nginx.
fasthttp-proxy:Requests/sec:  57417.13
nginx:Requests/sec:  14421.42

**Comment by 59duncom** [comment]
my ulimit -n is  65535

**Comment by 59duncom** [comment]
@erikdubbelboer  I suggest add a blocking (like sync.WaitGroup )here ,if the connections  is not free

**Comment by 59duncom** [comment]
the default DefaultMaxConnsPerHost =512 ,I keep 1000 threads，then the HostClient  always error "no free connections available to host",until the wrk test is done.

**Comment by erikdubbelboer** [comment]
No free connections available is an error that needs to be fixed. It's something that shouldn't happen when things are configured properly. So blocking instead would just hide this issue.

**Comment by erikdubbelboer** [comment]
Yes if you try to make 1000 connections and only 512 are allowed you will get that error.

**Comment by 59duncom** [comment]
it seems that blocking and waiting is  no useful~

**Comment by kirillDanshin** [comment]
@59duncom I've got a simple proxy example for you https://github.com/highloadltd/connmgr/blob/master/connmgrd/main.go#L15

I've got 25474 rps without any additional configurations on my MBP 2014 (Core I7-4770hq / 16GB RAM), that's better, but then I've got "no free connections available to host" error

**Comment by 59duncom** [comment]
thanks

**Comment by kirillDanshin** [comment]
@59duncom using [this two options](https://github.com/highloadltd/connmgr/blob/master/connmgrd/main.go#L35-L36) for client got me an easy 40krps:
```
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.59ms    7.20ms 172.80ms   96.76%
    Req/Sec     5.08k   675.02     8.52k    77.23%
  204119 requests in 5.10s, 18.10MB read
Requests/sec:  40023.34
```

**Comment by 59duncom** [comment]
I see your code thanks a lot .I had test my code in a 2 cores and 2G RAM vps,so is not very good.
but I think your code that:
1.do not use sync.pool which is use many in fasthttp to reduce memory
2.you do not limit your clients conns,wich can limit in fasthttp.HostClient,I only need that if the maxconns reach,blocking and wait for new free conns in  fasthttp.HostClient.
I just now write a proxy ,thanks for you codes
