### ISSUE TITLE
fasthttp client many timeout with highly concurrent 

### ISSUE THREAD

**Issue by helperShang** [valyala/fasthttp#591]
dialing to the given TCP address timed out
dialing to the given TCP address timed out
dialing to the given TCP address timed out
dialing to the given TCP address timed out
dialing to the given TCP address timed out

**Comment by erikdubbelboer** [comment]
That just means that the server you are trying to connect to can't handle the load and isn't able to accept new connections quickly enough. Nothing we can do about that in fasthttp.
