### ISSUE TITLE
big mistake in fasthttp.cleint

### ISSUE THREAD

**Issue by 59duncom** [valyala/fasthttp#593]
when the body is big  for example  5Gb, you fasthttp.appendBodyFixedSize and directly try to use malloc ,but the os had no 5GB memory free.

error codes that:
github.com/valyala/fasthttp.appendBodyFixedSize(0xc000036060, 0xc000274000, 0x0, 0x100, 0x172e5fc24, 0x7ca340, 0xc000232100, 0x0, 0x0, 0x0)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/http.go:1684 +0x232 fp=0xc000263d48 sp=0xc000263cc0 pc=0x6b16e2
github.com/valyala/fasthttp.readBody(0xc000036060, 0x172e5fc24, 0x0, 0xc000274000, 0x0, 0x100, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/http.go:1635 +0x78 fp=0xc000263da8 sp=0xc000263d48 pc=0x6b0f18
github.com/valyala/fasthttp.(*Response).ReadLimitBody(0xc000056640, 0xc000036060, 0x0, 0xc000036060, 0x3)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/http.go:1040 +0x135 fp=0xc000263e18 sp=0xc000263da8 pc=0x6aecf5
github.com/valyala/fasthttp.(*HostClient).doNonNilReqResp(0xc0001c6500, 0xc0000f7080, 0xc000056640, 0xbf6f00, 0x3ba6d8600, 0x0)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/client.go:1208 +0x316 fp=0xc000263ea0 sp=0xc000263e18 pc=0x699006
github.com/valyala/fasthttp.(*HostClient).do(0xc0001c6500, 0xc0000f7080, 0xc000056640, 0xed49555b7, 0x16b552a0e60, 0x4)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/client.go:1112 +0x5e fp=0xc000263ef8 sp=0xc000263ea0 pc=0x698c0e
github.com/valyala/fasthttp.(*HostClient).Do(0xc0001c6500, 0xc0000f7080, 0xc000056640, 0xc000263fb0, 0x42d3b6)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/client.go:1062 +0x7d fp=0xc000263f58 sp=0xc000263ef8 pc=0x6988ad
github.com/valyala/fasthttp.clientDoDeadline.func1(0x887fa0, 0xc0001c6500, 0xc0000f7080, 0xc000056640, 0xc000054710, 0x76b6a0, 0xc0000b0660, 0xc0000b0660)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/client.go:1004 +0x50 fp=0xc000263fa0 sp=0xc000263f58 pc=0x6be830

**Comment by 59duncom** [comment]
so the error occur

**Comment by erikdubbelboer** [comment]
That is correct, fasthttp will always read the whole body into memory. The way fasthttp as designed from the start makes it really hard to change this so I don't think it ever will. If you need to support huge bodies I'm afraid you'll have to use `net/http`.
