### ISSUE TITLE
reverse HTTP proxy with fasthttp

### ISSUE THREAD

**Issue by Arnold1** [valyala/fasthttp#594]
Hi,

i wonder how good fasthttp would be for the following usecase. how much qps could it handle with fasthttp and how much is the additonal latency?
```
teeproxy is a reverse HTTP proxy. For each incoming request, it clones 
the request into 2 requests, forwards them to 2 servers. 
The results from server A are returned as usual, but the results from 
server B are ignored.

teeproxy handles GET, POST, and all other http methods.
```

cc:
https://github.com/chrislusf/teeproxy

**Comment by erikdubbelboer** [comment]
If it's going to be a very high number of requests fasthttp would definitely help. But I would first test it and see if the CPU is really your bottleneck.
