### ISSUE TITLE
in line 1074,  why not retry  in some case?

### ISSUE THREAD

**Issue by goith** [valyala/fasthttp#595]
https://github.com/valyala/fasthttp/blob/9ba4cef1bac8ebc8fe71123bd20cfc681fdb78a8/client.go#L1063-L1078

in line 1074,  not retry  in some case.  

The following example，return false when acquireConn returnting err.  just is not retry,    how to solve in  this case ?

https://github.com/valyala/fasthttp/blob/9ba4cef1bac8ebc8fe71123bd20cfc681fdb78a8/client.go#L1157-L1160
thanks.

**Comment by erikdubbelboer** [comment]
Because retrying here would just immediately fail again. The chances that a connection became free without waiting any time are super low. If we would retry here we would have to implement some kind of delay which could complicate things by a lot.
