### ISSUE TITLE
why ctx.Request.URI().RequestURI() is missing?

### ISSUE THREAD

**Issue by 59duncom** [valyala/fasthttp#597]
I had write a websocket proxy,but ctx.requesturi is miss  and fmt.Println( ctx.Request.String()) is ok:

func Proxyhttp(ctx *fasthttp.RequestCtx){

fmt.Println( string(ctx.RequestURI())) //here is ok
if websocket.FastHTTPIsWebSocketUpgrade(ctx){
   	    Dowebsocket(ctx,   clientproxy.source)

   }
}
func Dowebsocket( ctx *fasthttp.RequestCtx,sourcestr string){
	upgrader :=  websocket.FastHTTPUpgrader{HandshakeTimeout: 15 * time.Second, CheckOrigin:func(ctx *fasthttp.RequestCtx) bool { return true },    }
	upgrader.Upgrade(ctx,func(ws *websocket.Conn) {
			   wsURL := url.URL{Scheme: "ws", Host: sourcestr, Path:string(ctx.RequestURI())) }//here is miss
			   fmt.Println(string(ctx.URI().RequestURI())) //here is miss
			   dialer := websocket.Dialer{
				   Proxy:            http.ProxyFromEnvironment,
				   HandshakeTimeout: 15 * time.Second,
			   }
			   server, _, err := dialer.Dial(wsURL.String(), nil)
...................
}

**Comment by 59duncom** [comment]
first ctx.RequestURI() is "/echo" ,missing is print "/"

**Comment by dgrr** [comment]
Maybe there is any problem before you print the request URI.
As I checked by making a simple program which prints the ctx.URI().RequestURI() it should work. So I think maybe the websocket library is modifying the request uri or something else. Not a fasthttp issue

![image](https://user-images.githubusercontent.com/10146748/60507012-7660ef80-9cc7-11e9-96bd-db8c33d0d80f.png)

**Comment by 59duncom** [comment]
I had use "github.com/fasthttp/websocket"for websocket
I will write a demo and test

**Comment by dgrr** [comment]
Ah, yep, I know where the error is. https://github.com/valyala/fasthttp/blob/master/server.go#L2063
The RequestCtx is reset when a connection is Hijacked.

**Comment by 59duncom** [comment]
ok thanks
