### ISSUE TITLE
Can't set Content-Type on GET requests

### ISSUE THREAD

**Issue by wendigo** [valyala/fasthttp#6]
~~~
package main
import "github.com/valyala/fasthttp"
import "fmt"

func main() {
	header := fasthttp.RequestHeader{}

	header.SetRequestURI("http://localhost/test")
	header.Set("Accept", "application/json")
	header.Set("Arbitrary", "should-be-present")
	header.SetContentType("application/json")
	header.Set("Content-Type", "application/json")
	fmt.Printf("Header is: %s\n", string(header.String()))
}
~~~

Actual result:

~~~
Header is: GET http://localhost/test HTTP/1.1
User-Agent: fasthttp client
Accept: application/json
Arbitrary: should-be-present
~~~

According to the RFC2616 section 7.2.1 Content-Type should be set on methods containing entity but RFC does not prohibit to set it on other methods. Some APIs are using content-type to select API version on GET requests.

**Comment by abacaj** [comment]
Looks to me like it does set the content-type, but it does not print it with the `.String()` method.

**Comment by wendigo** [comment]
It's not sent over the wire. Double checked it.

**Comment by wendigo** [comment]
https://github.com/valyala/fasthttp/blob/master/header.go#L996 :)

**Comment by AlekSi** [comment]
So there is no way to set for PUT too?

**Comment by valyala** [comment]
Fixed

Thanks for the bug report :)

**Comment by valyala** [comment]
> So there is no way to set for PUT too?

@AlekSi, PUT requests are now supported - see the commit 6a340b733407c966d87521e188e08492ad27305d .

**Comment by wendigo** [comment]
:+1:

**Comment by AlekSi** [comment]
What about PATCH?

**Comment by valyala** [comment]
@AlekSi , done
