### ISSUE TITLE
after using williamyeh/wrk there left some ESTABLISHED ports on server

### ISSUE THREAD

**Issue by northfun** [valyala/fasthttp#600]
Server(ubuntu 16.04) is listening on port "ABC" and `net.ipv4.tcp_keepalive_time = 30` is set.
After using williamyeh/wrk(`docker run --rm`) to do benchmark, test is over and the container is already removed, then
on server,even 1h later:
```
root@ydhl-go-02:~/adx# netstat -ant | grep ABC                                
tcp        0      0 192.168.0.52:ABC      192.168.0.53:40077      ESTABLISHED 
tcp        0      0 192.168.0.52:ABC      192.168.0.53:44651      ESTABLISHED 
```
but on client, the progress is stoped and can't find the established ports:
```
go-01:~$ netstat -ant | grep 40077
go-01:~$ 
```
I use fasthttp.Shupdown() to close the server, but it is waiting the last connections,the stack is here:
```
 /usr/local/go/src/runtime/netpoll.go:182
 /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
 /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
 /usr/local/go/src/internal/poll/fd_unix.go:169
 /usr/local/go/src/net/fd_unix.go:202
 /usr/local/go/src/net/net.go:177
 /usr/local/go/src/bufio/bufio.go:100
 /usr/local/go/src/bufio/bufio.go:138
 /home/workspace/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/header.go:1382
 /home/workspace/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/header.go:1368
 /home/workspace/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/http.go:931
 /home/workspace/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/server.go:1890
 /home/workspace/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/workerpool.go:212
 /home/workspace/go/pkg/mod/github.com/valyala/fasthttp@v1.3.0/workerpool.go:184
```
I wonder why, and how to avoid it, thanks~~

**Comment by erikdubbelboer** [comment]
These are TCP connections that are still open according to the OS.

Is the docker container that was running wrk completely shut down?

I can imagine the docker container not always shutting down properly thereby not sending close packets for each TCP connection.

You could try setting [`Server.TCPKeepalive`](https://godoc.org/github.com/valyala/fasthttp#Server.TCPKeepalive) to `true`. This will make the OS send TCP keep alive packets to see if the connection is really still alive.

**Comment by northfun** [comment]
> These are TCP connections that are still open according to the OS.
> 
> Is the docker container that was running wrk completely shut down?
> 
> I can imagine the docker container not always shutting down properly thereby not sending close packets for each TCP connection.
> 
> You could try setting [`Server.TCPKeepalive`](https://godoc.org/github.com/valyala/fasthttp#Server.TCPKeepalive) to `true`. This will make the OS send TCP keep alive packets to see if the connection is really still alive.

I'm sure the container was shut down,not only I run it using `docker run --rm`,but also checked by `docker ps -a`.

Which confused me so much was that I coundn't find any port established to the server port ABC on the client server(the server runs wrk container),but on the server side,there still showed some ESTABLISHED connections to the port.Even few days later,the state is still.

Thanks for your advise,I'm going to have a try.

**Comment by erikdubbelboer** [comment]
Can you share the code and commands you are running?
