### ISSUE TITLE
equivalent of https://golang.org/pkg/net/http/httptest/#Server

### ISSUE THREAD

**Issue by Milerius** [valyala/fasthttp#603]
Hello,

There is an equivalent to: https://golang.org/pkg/net/http/httptest/#Server

with fasthttp ?

Best Regards,

**Comment by erikdubbelboer** [comment]
There isn't an exact equivalent as far as a I know. What we use for testing with fasthttp is [`InmemoryListener`](https://godoc.org/github.com/valyala/fasthttp/fasthttputil#InmemoryListener).

You can see an example of how to use this with a client and server here:
https://github.com/valyala/fasthttp/blob/1bd0404cedf0148dca83663870e12cf8b156c7f7/client_test.go#L23-L39
