### ISSUE TITLE
How to set value to a context?

### ISSUE THREAD

**Issue by AnikHasibul** [valyala/fasthttp#604]
I want to use a value in all the functions my `RequestCtx` goes, how to do that? In `context.Context` I could do it with `context.WithValue()`.

**Comment by erikdubbelboer** [comment]
I'm not sure I understand, can you explain with some sample code?

**Comment by dgrr** [comment]
Hello @AnikHasibul 

Do you mean something like this? https://godoc.org/github.com/valyala/fasthttp#RequestCtx.UserValue

**Comment by AnikHasibul** [comment]
> Do you mean something like this? https://godoc.org/github.com/valyala/fasthttp#RequestCtx.UserValue

Exactly this one! 
Thank you @dgrr and @erikdubbelboer 
Closing...
