### ISSUE TITLE
Logging verbosity

### ISSUE THREAD

**Issue by horgh** [valyala/fasthttp#605]
Hi!

I've found a log message that is more verbose than I need. Would hiding it in some way be an option?

```
server: [snip]github.com/valyala/fasthttp/workerpool.go:218: error when serving connection
"[snip]:13010"<->"[snip]:35338": read timeout with nothing read
```

It looks like adding it as a condition here would be ok: https://github.com/valyala/fasthttp/blob/master/workerpool.go#L214-L218

**Comment by erikdubbelboer** [comment]
No, this is a special case which shouldn't happen normally. This means the server wasn't able to read any bytes from the connection but there wasn't an `io.EOF` error either.
I'm thinking https://github.com/valyala/fasthttp/blob/1bd0404cedf0148dca83663870e12cf8b156c7f7/header.go#L1400 should probably wrap `err` so at https://github.com/valyala/fasthttp/blob/9494955f8e5a64a6abd126049e11f916d3121ac9/server.go#L1924 we can unwrap it and return a proper error. I'll try to do this tomorrow.

**Comment by horgh** [comment]
Wow, I had no idea! Thank you for looking at it.

**Comment by erikdubbelboer** [comment]
I have just published a fix, can you please test `master` and see if this still happens.

**Comment by horgh** [comment]
Thank you! I'll update and let you know. I'm not sure how to cause it so I'll watch logs for a while.

**Comment by horgh** [comment]
Since updating almost 2 days ago, I've seen no more errors like this. Previously I'd have expected several. So it looks great!

Thanks again for figuring it out and fixing it so quickly!
