### ISSUE TITLE
get "invalid memory address or nil pointer dereference" under heavy request load

### ISSUE THREAD

**Issue by blankroom** [valyala/fasthttp#606]
The goroutine traceback is:
```
github.com/valyala/fasthttp.(*Response).copyToSkipBody(0x0, 0xc001f21cc0)
        /home/blankroom/go/src/github.com/valyala/fasthttp/http.go:673 +0x34
github.com/valyala/fasthttp.(*Response).CopyTo(0x0, 0xc001f21cc0)
        /home/blankroom/go/src/github.com/valyala/fasthttp/http.go:658 +0x3c
...(my own code)
```

I use wrk to test performance of my program which is deployed on a Kubernetes cluster  and it works fine under 400 connections but throws panic rapidly under 600 connections. The panic even leads to container restart. So I wonder what happened to the Response.copyToSkipBody and any suggestion for me to avoid this?

**Comment by erikdubbelboer** [comment]
Can you share some of your code? Are you using `fasthttp.Server` or `fasthttp.Client`?

**Comment by blankroom** [comment]
I'm using both fasthttp.Server and fasthttp.Client, but the part related to the panic is only about fasthttp.client. Here is the snippet around:
```
       for i, b := range bs {
		wg.Add(1)
		go func(arr []*WriteResponse, index int, b BackendAPI) {
			defer wg.Done()
			resp, err := b.Write(line)
			arr[index] = NewWriteResponse(resp, err)
		}(wrs, i, b)
	}
	wg.Wait()
	err := HttpResult(ctx, bs, wrs, line)
```
In b.Write() func, I use fasthttp.client to constuct a request by the input and send it to a backend.
And in HttpResult func I analyse the response from two backends.
NewWriteResponse func where the panic actually occurs simply copy the response to a new instance:
```
func NewWriteResponse(resp *fasthttp.Response, err error) (wr *WriteResponse) {
	copyResp := fasthttp.AcquireResponse()
	resp.CopyTo(copyResp)
	wr = &WriteResponse{
		resp: copyResp,
		err:  err,
	}
	return
}
```

**Comment by dgrr** [comment]
If there is an error calling `b.Write` it returns the the resp or nil? Maybe you are copying a nil resp.

**Comment by erikdubbelboer** [comment]
Do you have a longen stack trace for us?

And maybe some more code. I can’t see much with only this. For example what does `BackendAPI` do?

**Comment by blankroom** [comment]
> If there is an error calling `b.Write` it returns the the resp or nil? Maybe you are copying a nil resp.

@dgrr Thanks for reminding me of checking the code inside and you are right. The returned response from b.write is nil. After I fixed the code, the error is gone. However, it seems that I come into another problem. I will keep testing my code and if there is any problem related to  fasthttp, I may open another issue.
@erikdubbelboer Thanks for your reply, I really appreciate it. That’s all about my own bug and please close this issue.
