### ISSUE TITLE
when set content-lenght smaller than reallenght

### ISSUE THREAD

**Issue by jamsonzan** [valyala/fasthttp#607]
we expect a "400 bad request" respones, but fasthttp would not return a respones but read next request.  source code in server.go:
```go
if br == nil || br.Buffered() == 0 || connectionClose {
			err = bw.Flush()
			if err != nil {
				break
			}
		}
``````
when set content-lenght smaller than reallenght, br.Buffered() > 0.  so bw would not Flush and fasthttp read next request. Becuase of br.Buffered>0, the next request always a bad request too. Then, fasthttp would return a respone like this:
```
HTTP/1.1 200 OK
Server: ...
Date: ...

HTTP /1.1 400 Badrequest
...
...
Error when parsing request
```

it seem that two respones mix. fasthttp think this is a pipeline, but it is a bad request actually.

is fasthttp necessary to check the content lenght (to peek extra 1 byte) and if hasbyte return "400 bad request" respones with connection close?

**Comment by erikdubbelboer** [comment]
This is how HTTP works. The Content-Length header tells fasthttp how long the body is. Anything after it is officially the next request on that connection. This is called HTTP pipelining. It is impossible for fasthttp to know that the body is actually longer than the length from Content-Length.

**Comment by jamsonzan** [comment]
i know. thanks for your answer.
