### ISSUE TITLE
Can we support user:pass in RequestURIs?

### ISSUE THREAD

**Issue by durango** [valyala/fasthttp#609]
Passing a URL struct would be nice... should not be getting this error:

`(*net.AddrError)(0xc0001ea000)(address user:pass@host:1234: too many colons in address)`

**Comment by erikdubbelboer** [comment]
I guess this means you'll also want this to be turned into a `Authorization: Basic ...` header when a request to this URL is send?

**Comment by durango** [comment]
Yeah, that was definitely the workaround but it just seemed "not the go way" when I was implementing it. Thank you for labeling the issue 👍

**Comment by dgrr** [comment]
@durango https://gist.github.com/dgrr/0a10fded51d4c02a0190f51366bb051b

**Comment by erikdubbelboer** [comment]
@dgrr that's the server side, this is about the client side of it.

**Comment by dgrr** [comment]
https://gist.github.com/dgrr/2e41b058db3ead93c161feb9472254a7

**Comment by durango** [comment]
Yes, I know how to do it. That's not the issue ;) Thank you though!

**Comment by dgrr** [comment]
Ok. @durango I understand the issue but I think it requires to change the internal API a lot just to make something which is not a widely extended case. I think in this library we should tend to implement only some general purpose cases. An HTTP authentication process in the URL is so specific to make the package process all the cases in which an URL could contain credentials or not making then the URL interpreter slower. And the performance, in that case, is not only the point I want to make you be aware of. If the client has to support credentials in the URL the path to follow will be to do something like checking the URL first and if it requires authentication then perform that action. This could be done in a function or two, but again will make the developers add more code to the client making it heavier.
To conclude this comment I think it's a matter of a framework or some other package that can make that easy for the ones who want to implement that.

**Comment by erikdubbelboer** [comment]
https://github.com/valyala/fasthttp/pull/614 is going to fix this.
