### ISSUE TITLE
it takes a long time on function readMultipartForm

### ISSUE THREAD

**Issue by iampoty** [valyala/fasthttp#61]
When i’m upload a file with “multipart/form-data” from Web Browser or Post-man for Google Chome
,it takes a long time on function readMultipartForm and not return error "cannot read multipart/form-data body"

**Comment by valyala** [comment]
@iampoty , the issue should be fixed now. Feel free re-opening it if related issues appear.

**Comment by iampoty** [comment]
Thanks you.
