### ISSUE TITLE
why don't you make a pull request to Golang ?

### ISSUE THREAD

**Issue by catastrop** [valyala/fasthttp#611]

**Comment by erikdubbelboer** [comment]
A pull request with what exactly? The `fasthttp` API is not compatible with the `net/http` API at all because the `net/http` API doesn’t allow for reusing of objects.

**Comment by AnikHasibul** [comment]
What about proposing a separate package? Like `net/fasthttp` or anything else?

I know, it would be hard to convince them, but if we show support, then it can be helpful. After all it's all about a huge performance improvement.

**Comment by erikdubbelboer** [comment]
I'm 100% sure this will never happen. Go is all about simplicity and having only 1 way to do things. Having 2 competing http libraries in the standard library would never be allowed.

There was already some work on redesigning the http library for go2. I can't find it now so I'm not sure where that was going.
