### ISSUE TITLE
Question: How to dump a http request for debugging or logging purpose?

### ISSUE THREAD

**Issue by AnikHasibul** [valyala/fasthttp#615]
I want to dump one of my request that caused an error. I mean is there any function to all the value from a `*fasthttp.RequestCtx`. 
https://golang.org/pkg/net/http/httputil/#DumpRequest is an example.

**Comment by erikdubbelboer** [comment]
You can do [`ctx.Request.String()`](https://godoc.org/github.com/valyala/fasthttp#Request.String). Keep in mind that this is not the best for high performance. So if you're going to log this for each request you might want to use [`ctx.Request.Write()`](https://godoc.org/github.com/valyala/fasthttp#Request.Write) to write to a reusable buffer for example.
