### ISSUE TITLE
Can't set value to context

### ISSUE THREAD

**Issue by AnikHasibul** [valyala/fasthttp#616]
Is #604 I knew about `RequestCtx.SetValue()`.

But another problem raised.

A function uses `context.Context`  as parameter. I passed `*fasthttp.RequestCtx` there, because it also implements `context.Context` interface.

That function will call `context.WithValue(context.Background(), "foo", "bar")`

Then if I check `fasthttp.RequestCtx.Value("foo")` I will get `nil`, but I expected `bar`

**Comment by erikdubbelboer** [comment]
I'm confused, how are you getting a `fasthttp.RequestCtx` based on a `context.Context`? Can you show your code?

If you pass a `fasthttp.RequestCtx` to the function and the function does `context.WithValue(context.Background(), "foo", "bar")` then that doesn't update the value in the `fasthttp.RequestCtx`. Contexts never work that way. `context.WithValue(context.Background(), "foo", "bar")` will return a new context with the value added, contexts are somewhat immutable so they previous one doesn't change. [`WithValue`](https://golang.org/pkg/context/#WithValue) even says this in the documentation: `WithValue returns a copy of parent in which the value associated with key is val.`.

**Comment by AnikHasibul** [comment]
Few minutes ago, I got it. And changed my code to use the copied context. However, thanks @erikdubbelboer .

**Comment by RobertoOrtis** [comment]
> Few minutes ago, I got it. And changed my code to use the copied context. However, thanks @erikdubbelboer .

Could you please share your solution. Thank you.
