### ISSUE TITLE
setPath in ResponseHeader.DelClientCookie()

### ISSUE THREAD

**Issue by iapyeh** [valyala/fasthttp#619]
When removing a cookie , its "path" has to be specified. Otherwise it would be ignored by browser. (at least by Chrome)

```
func (h *ResponseHeader) DelClientCookie(key string) {
	h.DelCookie(key)
	c := AcquireCookie()
	c.SetKey(key)
	c.SetPath("/") //<------- the missing line
	c.SetExpire(CookieExpireDelete)
	h.SetCookie(c)
	ReleaseCookie(c)
}
```

**Comment by erikdubbelboer** [comment]
Not setting the path means the current path of URL is used. Deleting a cookie just by key doesn't make too much sense, you will always want to set a path as well. But adding a path argument would break the API which we can't do so I'm afraid we're stuck with this. What we could do is document this better.
