### ISSUE TITLE
Streaming request body

### ISSUE THREAD

**Issue by vincent-163** [valyala/fasthttp#622]
Hello! First of all, thanks for the awesome work.

I'm building a simple file server that receives files from clients. The files are presented in the raw request body (i.e. no multipart/form-data), and file sizes can be several hundred megabytes large. fasthttp seems to have a small default request body limit (4MB), and when I try to increase that limit via MaxRequestBodySize I get out of memory error when uploading large files. Is there a way to stream request body directly so it uses only constant memory?

**Comment by kirillDanshin** [comment]
Currently working on/testing this feature

**Comment by erikdubbelboer** [comment]
At the moment not. By design fasthttp waits until the whole request is in memory before it calls the handler. @kirillDanshin is working on changing this so keep an eye on this repo.

**Comment by tsingson** [comment]
> Currently working on/testing this feature

cool..........

**Comment by ochanism** [comment]
@kirillDanshin Could you update your progress?

**Comment by Fenny** [comment]
Any updates? Seems like a big thing

**Comment by kirillDanshin** [comment]
sorry for delay.

this feature is currently in production testing. had to reimplement it again due to insufficient performance.

**Comment by erikdubbelboer** [comment]
@kirillDanshin can you maybe make a pull request already (maybe in Draft mode?) so people can look at the code?

**Comment by dfirsht** [comment]
@kirillDanshin any updates on this?

**Comment by johnlanni** [comment]
@kirillDanshin Could you update your progress?

**Comment by dgrr** [comment]
Isn't [implemented](https://github.com/valyala/fasthttp/blob/master/http.go#L1419)?
Or do you mean reading from a reader?

**Comment by Fenny** [comment]
@kirillDanshin could you share what you got so far, maybe we could help?

**Comment by taoyuanyuan** [comment]
@kirillDanshin could you share your code ？

**Comment by refine36** [comment]
@kirillDanshin any updates on this?

**Comment by iarkaroy** [comment]
@kirillDanshin any update on this?

**Comment by jan4984** [comment]
any update? i use the issue-622 branch and it totally not work.  the handler blocking at 'appendBodyFixedSize'.

**Comment by dengqian** [comment]
@kirillDanshin Can you maybe make a pull request already?

**Comment by kirillDanshin** [comment]
@jan4984 please provide an example of this issue

**Comment by frankdvd** [comment]
@kirillDanshin  Thank you so much for your work, this is a really helpful feature, any idea on when the PR will be merged?
