### ISSUE TITLE
Is there any way to specify laddr for fasthttp.Dial/DialTimeout?

### ISSUE THREAD

**Issue by mikefaraponov** [valyala/fasthttp#625]

**Comment by erikdubbelboer** [comment]
There currently isn't. Would it work if this became an option in [`fasthttp.TCPDialer`](https://github.com/valyala/fasthttp/blob/b97bc32543cbd94e41a3c58a035bb8b2dea60a2f/tcpdialer.go#L123) or do you need to change it Dial call? Adding it as argument to the `fasthttp.Dial` functions would mean introducing 4 new functions.

**Comment by mikefaraponov** [comment]
I think it's not a problem to pass this option to TCPDialer

**Comment by erikdubbelboer** [comment]
Could you make a pull request or should I do it?

**Comment by mikefaraponov** [comment]
I will do it after one related to tls handshake timeout.
