### ISSUE TITLE
Does fasthttp.Client take care of half-open/half-closed connections?

### ISSUE THREAD

**Issue by mikefaraponov** [valyala/fasthttp#627]

**Comment by erikdubbelboer** [comment]
What do you mean with a `half-closed` connection?

**Comment by mikefaraponov** [comment]
My fault - half-opened connections. lsof show me many sock files with can't identify protocol status sometimes near 200k with requests per seconds rate near 4k to many different hosts

**Comment by mikefaraponov** [comment]
Probably relates with https://github.com/valyala/fasthttp/issues/630

**Comment by erikdubbelboer** [comment]
Sounds like something in the TCP layer unrelated to fasthttp. Could it be that these are sockets in the `TIME_WAIT` state?

**Comment by mikefaraponov** [comment]
I am using SO_REUSEPORT

**Comment by mikefaraponov** [comment]
Probably I am trapped into https://github.com/golang/go/issues/18588

**Comment by mikefaraponov** [comment]
I found the root cause. Fasthttp is nice lib. My fault.

**Comment by erikdubbelboer** [comment]
@mikefaraponov would you mind sharing what the cause was?

**Comment by mikefaraponov** [comment]
The reason in spawning unknown ```can't identify protocol``` messages in lsof -n was SO_REUSEPORT behavior for client side connections, it's absolutely normal. The root cause of degraded performance was another dnscache library, even not a library itself but my missing of knowledge how it works internally
