### ISSUE TITLE
Embedding certFile and keyFile into exe

### ISSUE THREAD

**Issue by kashcode** [valyala/fasthttp#63]
Is there any option embedding cert file and key file?

**Comment by valyala** [comment]
Just added the corresponding helper functions - see https://github.com/valyala/fasthttp/commit/15ffe2f795058a281d94f8d7464875bea05e7822 for details.

**Comment by valyala** [comment]
FYI, cert and key files may be embedded without the added helper functions - just implement custom [tls listener](https://golang.org/pkg/crypto/tls/#NewListener) and pass it to [Serve](https://godoc.org/github.com/valyala/fasthttp#Serve).
