### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [valyala/fasthttp#632]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

might be related to this https://github.com/valyala/fasthttp/issues/33

Cheers,
Yevgeny

**Comment by kirillDanshin** [comment]
@yevgenypats thanks, I think it would be useful 🙂

**Comment by yevgenypats** [comment]
@kirillDanshin sounds good. 

Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by kirillDanshin** [comment]
@yevgenypats actually, I gonna need fuzzing for [another my OSS project](https://github.com/audioid/audioid) later, where I currently can't publish testdata for; but speaking of fasthttp, I'm currently working on a huge update (#622), and I would appreciate any help with testing fasthttp.


Although, I should say that integrating fuzzing seems to be tricky from a security point. We have many users and if during fuzzing we'll find a bug, it should be considered as a subject of our [security rules](https://github.com/valyala/fasthttp/blob/master/SECURITY.md), to allow some time to update before the disclosure

**Comment by yevgenypats** [comment]
@kirillDanshin, good question regarding the security policy. so I can create an organisation for fasthttp on fuzzit and the bugs and testdata are private by default there so only the relevant people that have access to fuzzit will be alerted of any crashes.

**Comment by kirillDanshin** [comment]
@yevgenypats I would definitely appreciate that, thank you

**Comment by yevgenypats** [comment]
@kirillDanshin  can you sign up at https://app.fuzzit.dev so I can add you to fasthttp organisation.

**Comment by kirillDanshin** [comment]
@yevgenypats done

**Comment by yevgenypats** [comment]
@kirillDanshin done. https://app.fuzzit.dev/orgs/fasthttp/dashboard
you can join our [slack](https://slack.fuzzit.dev) we can discuss there what would be the best way to write the fuzzers for your change

**Comment by erikdubbelboer** [comment]
@yevgenypats I have signed up with my github as well.

I already wrote simple fuzzers a while back: https://github.com/erikdubbelboer/fasthttp-gofuzz
Do we just need `_fuzz.go` files with `// +build gofuzz` in it for this to work?

**Comment by kirillDanshin** [comment]
@erikdubbelboer I've added you in the organization

**Comment by erikdubbelboer** [comment]
I have made a test branch that is now building: https://travis-ci.org/valyala/fasthttp/builds/573069279

@yevgenypats seeing as you can only have one `Fuzz()` function, how would you recommend fuzzing multiple things?

**Comment by yevgenypats** [comment]
@erikdubbelboer you should compile multiple fuzzers and upload them to Fuzzit (you should create target for each fuzzer). you can also join our [slack](https://slack.fuzzit.dev) and we can open fasthttp channel there

**Comment by erikdubbelboer** [comment]
I have just made a pull request the way I think we should do this: https://github.com/valyala/fasthttp/pull/634
@yevgenypats how long does it fuzz for? My previous job was running for almost a day before I cancelled it.

**Comment by yevgenypats** [comment]
@erikdubbelboer the PR looks good though I would add also a regression job that runs on PRs - as this runs quickly and prevent from old/new bugs crippling into master.

The fuzzing runs infinitely - no need to stop it. It stops automatically once you upload a new fuzzer with new version which continuous from the same place (using the same corpus). I hope it wasn't too confusing.

**Comment by erikdubbelboer** [comment]
What does `local-regression` do exactly? Does it just run the existing corpus locally or does it do more? I can't find any documentation for this.

**Comment by yevgenypats** [comment]
Yes, I'll add more documentation. This runs locally (it spawns a docker) with the existing corpus. You should mark the corpus public in the target settings (If this is ok by you - it shares only the corpus and the fixed crashes - This is due to the fact that forked PR don't have access to secrets which makes sense). You can see a simple example [here](https://github.com/fuzzitdev/example-go) and an in the wild example [google/syzkaller](https://github.com/google/syzkaller) and [coredns/coredns](https://github.com/coredns/coredns)

**Comment by erikdubbelboer** [comment]
@yevgenypats do you have any idea what to do about this?
```
$ clang -fsanitize=fuzzer fasthttp_request.a -o fasthttp_request
/usr/bin/ld: cannot find /usr/local/clang-5.0.0/lib/libLLVMFuzzer.a: No such file or directory
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by yevgenypats** [comment]
@erikdubbelboer Yes you need clang > 6.0 (clang 5.0 is really old). I think this is easy to solve if you  will add `dist: bionic` in the fuzzit stages. let me know if that worked.

**Comment by yevgenypats** [comment]
@erikdubbelboer cool! ping me at yp [at] fuzzit.dev if you are interested in our reward:)
