### ISSUE TITLE
Support multiple listeners per single `fasthttp.Server` instance

### ISSUE THREAD

**Issue by cipriancraciun** [valyala/fasthttp#633]
At the moment a single `fasthttp.Server` instance can listen on a single `net.Listener` due to the following internal check:
https://github.com/valyala/fasthttp/blob/85217e0d5e01adcd51e6fe5142fa1bda07eaf50b/server.go#L1563-L1573

However nothing in the underlying implementation of `acceptConn` depends on this assumption, nor does the rest of `Serve`:
https://github.com/valyala/fasthttp/blob/85217e0d5e01adcd51e6fe5142fa1bda07eaf50b/server.go#L1674-L1709
https://github.com/valyala/fasthttp/blob/85217e0d5e01adcd51e6fe5142fa1bda07eaf50b/server.go#L1593-L1629

In fact the `ln` attribute is only used in `Shutdown` to close the listener.

Therefore I would say it would be quite trivial to support out-of-the-box multiple listeners.

---

Granted one could mock a `net.Listener` and use goroutines and channels to simulate this, but it is "sub-optimal".

If this feature is thought to be useful I could provide the initial implementation.

---

On the question of "why" would one to use multiple listeners with the same server?

Because `fashttp` mentains per server a concurrency counter and other rate-limiting features;  therefore by using the same server one can handle both HTTP and HTTPS while maintaining a single server context.  (Or perhaps multiple HTTP listeners on selected network interfaces, etc.)

**Comment by erikdubbelboer** [comment]
Yes it shouldn't be too hard to do this. If you could make a pull request that would be great.

**Comment by eloff** [comment]
I came here to ask this very question, I want to have one reuseport listener per core, pinned to a HW thread and that thread pinned to a core using taskset.

But I want it in the same process so threads can share in-memory caches.

**Comment by cipriancraciun** [comment]
@eloff  Although I understand the reason of tying one listener (and handler) per physical core, I think you won't achieve what you are searching for given Go's concurrency approach of using, basically, green-threads (i.e. goroutines)...  (I am also skeptical that you can actually pin the Go listener to an actual thread, without "fighting" with the Go runtime...)

Could you perhaps describe what are you exactly trying to achieve?

**Comment by AlbinoGeek** [comment]
Half a year later, need this feature, my use-case was already listed too:

Hosting the HTTP and HTTPS server in the same context is essential for any application you can login to, jut saying. Currently, you are forcing me to either shove the entire application (including the index and other public pages) under a TLS-terminated Load Balancer, which unfortunately adds the overhead of encryption to every page, nearly defeating the performance gain of using fasthttp in the first place.

Or, to handle TLS within the application, and again add the overhead of encryption to every request...

When given #730 , one could easily write both SSL and non-SSL pages in the same context, using their own middleware (such as that shown in the Auth example), while simply having multiple listeners as above:

```go
go handleErr(server.ListenAdnServe(":80"))

// currently fails with ErrAlreadyServing
go handleErr(server.ListenAndServeTLS(":443"))
```

---

Hell, I would argue the multi-host example is worthless without multiple listeners, or the ability to check he incoming protocol, as that would mean you are making a "Virtual Host" (like) server that either handles ONLY plaintext or ONLY TLS... as it were... as things are ow.

**Comment by cipriancraciun** [comment]
@AlbinoGeek

> Hell, I would argue the multi-host example is worthless without multiple listeners, or the ability to check he incoming protocol, as that would mean you are making a "Virtual Host" (like) server that either handles ONLY plaintext or ONLY TLS... as it were... as things are now.

This is a valid point I've not thought about in my initial request, namely:  how to tell from within the request through which listener the request came in.  (I.e. was it HTTP, or HTTPS, was it this network card or the other.)

----

> Hell, showing me the port number in `ctx.Request.Host()` is also a gigantic moot point, if there is only one listener, and therefore only ever one port, why even bother to tell me about it, so I have to strip it to match --just-- a hostname?

This is an unrelated issue.  The `.Host()` method -- I'm guessing without checking, but I am highly confident this is how things are -- returns the actual value of the `Host` header, which in turn is set by your browser, based on what the user has entered in the URL bar.  (I.e. it is not set by `fasthttp` by concatenating "something" with the listener's port.)

----

[This is off-topic to this feature request, but I think it's an important remark on the poster's text.]

> Currently, you are forcing me to either shove the entire application (including the index and other public pages) under a TLS-terminated Load Balancer, which unfortunately adds the overhead of encryption to every page, nearly defeating the performance gain of using fasthttp in the first place.

In that statement there are two "sub-problems".  First of all, if you deploy your application into production, regardless if it's exposed to the internet or not, and regardless if it hosts public accessible pages, **I would strongly suggest enabling TLS**.  (For one, Google "prefers" HTTPS pages, and secondly, even if one accesses public information over HTTP, it opens the opportunity for "bad guys" to inject unwanted adware (in the best case scenario) or even malware (worst case scenario).)

Then secondly, depending on your actual deployment performance requirements, I would still strongly suggest terminating TLS through a "dedicated" component, as I don't think Go's TLS stack is on par with that.  (I could strongly suggest taking a look at HAProxy, which BTW, can also solve the multiple listener issue.)

**Comment by erikdubbelboer** [comment]
I'm working on a change that allows calling `.Serve()` multiple times on a `Server`. I'll push it this weekend.

**Comment by cipriancraciun** [comment]
> I'm working on a change that allows calling `.Serve()` multiple times on a `Server`. I'll push it this weekend.

@erikdubbelboer  Perfect!  Thanks!

However, in the light of the previous comment, please take into account a way to detect from within a request handler (most likely through the request's context) from which `.Serve()` call the request was made.

(I now understand that for applications wanting to implement HTTP/HTTPS, this is essential, as perhaps to redirect protected pages through HTTPS;  another important use-case is "split-horizon-like" deployments, where the application behaves differently if the request came through the "intranet" network interface or the "internet" one.)

**Comment by erikdubbelboer** [comment]
@AlbinoGeek @cipriancraciun would this work for you: https://github.com/valyala/fasthttp/pull/731

**Comment by AlbinoGeek** [comment]
@cipriancraciun --

This was exactly the use-case, where the application displays different information based on whether you have come in through the public internet or private internet, requiring an idea of the receiving network card's identity (by IP range is good enough for this, which at least required multiple serving.) You have interesting points about TLS; however, ...

While somewhat off-topic " if this were the case, why aren't things simply "TLS by default" now to prevent this from even being a question?" Giving plaintext HTTP examples will have new developers making non-TLS webservers, as it's simply what the example they started from gave them. (Think: Boilerplates.)

@erikdubbelboer --

Success, sort of. This is 90% the way there.

Now we've run into a funny case, where a listener with the syntax `:80` shows up as `an-actual-ip:80` such as `127.0.0.1:80` in the request, when using `ctx.LocalAddr()` -- so it's not a great way to tell which listener got the request, if some of my listeners use wildcard IP addresses.

---

**Comment by erikdubbelboer** [comment]
@AlbinoGeek the problem with fixing this is that our worker pool is in the way. The handler has no idea which listener the connection was accepted on. Since this is also easily fixable by the user (if you listen on `:80` you can just do a suffix check on `ctx.LocalAddr()`) I don't think we want to make this easier for now.
