### ISSUE TITLE
Reverse Proxy?

### ISSUE THREAD

**Issue by caleblloyd** [valyala/fasthttp#64]
The golang httputil package has a ReverseProxy that will serve from an http.Request.

Is there any comporable revrese proxy for fasthttp that will serve from a fasthttp.Request?

**Comment by valyala** [comment]
Currently there is no reverse proxy, but it is [on the radar](https://github.com/valyala/fasthttp/blob/master/TODO) - see 'proxy handler' line there.

Currently reverse proxy may be implemented quite easily using [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient):
```go
import (
    "github.com/valyala/fasthttp"
)

var proxyClient = &fasthttp.HostClient{
    Addr: "upstream.host:port",
    // set other options here if required - most notably timeouts.
}

func ReverseProxyHandler(ctx *fasthttp.RequestCtx) {
    req := &ctx.Request
    resp := &ctx.Response
    prepareRequest(req)
    if err := proxyClient.Do(req, resp); err != nil {
        ctx.Logger().Printf("error when proxying the request: %s", err)
    }
    postprocessResponse(resp)
}

func prepareRequest(req *fasthttp.Request) {
    // do not proxy "Connection" header.
    req.Header.Del("Connection")
    // strip other unneeded headers.

    // alter other request params before sending them to upstream host
}

func postprocessResponse(resp *fasthttp.Response) {
    // do not proxy "Connection" header
    resp.Header.Del("Connection")

    // strip other unneeded headers

    // alter other response data if needed
}

func main() {
    if err := fasthttp.ListenAndServe(":8080", reverseProxyHandler); err != nil {
        log.Fatalf("error in fasthttp server: %s", err)
    }
}
```

**Comment by caleblloyd** [comment]
Thanks for the example.  To reverse proxy to a Unix Domain Socket, could I simply pass HostClient a Dialer function that makes use of [net.DialUnix](https://golang.org/pkg/net/#DialUnix)?

**Comment by valyala** [comment]
> To reverse proxy to a Unix Domain Socket, could I simply pass HostClient a Dialer function that makes use of net.DialUnix?

Yes

**Comment by pdcawley** [comment]
There's a problem, I'm afraid, `HostClient.Do` follows redirects, and there's no way to turn that off.

**Comment by valyala** [comment]
@pdcawley , `Do*` methods in any client type (`Client`, `HostClient` and `PipelineClient` currently) shouldn't follow redirects. Only `Get*` and `Post` methods follow redirects. Could you provide a short code snippet demonstrating that `HostClient.Do` follows redirects?

**Comment by pdcawley** [comment]
Nope. I misread the code.

**Comment by hnakamur** [comment]
@valyala First of all, thanks for sharing a great software!
I would like to implement a cache server using fasthttp, so I need a reverse proxy support.
I would like a hook point when all response headers from the upstream (origin) server are read so that I can determine the content should or should not be cached.

When I cache a content, I would like to write a response chunk to the client as well as the write the chunk to a buffer on the server at the same time. And once when I find the content is too large to be cached, I would like to switch to the pass though mode and just write a response chunk to the client without writing the chunk to a buffer on the server.

What structure is the best for such a need? A hook when a HostClient read all response headers, or splitting HostClient.Do into sending a request, reading response headers and reading the response body?

**Comment by valyala** [comment]
@hnakamur , your requirements for reverse proxy sound good - they may be used as a basis for reverse proxy implementation in `fasthttp`.

> I would like a hook point when all response headers from the upstream (origin) server are read so that I can determine the content should or should not be cached

Currently there `fasthttp` doesn't support response headers' inspection before reading response body. But this may be implemented by reading response headers with [ResponseHeader.Read](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.Read) and inspecting their contents before reading or discarding response body.

> I would like to write a response chunk to the client as well as the write the chunk to a buffer on the server at the same time

This sounds good in theory, but the caching in such a system may be abused by slow clients consuming big response bodies at 1kbps speed. It would be better just reading upstream response chunk up to the given size limit as fast as possible, caching it and then feeding slow clients.

> What structure is the best for such a need? A hook when a HostClient read all response headers, or splitting HostClient.Do into sending a request, reading response headers and reading the response body?

I don't know :( Probably it would be better to start with new client type (`ProxyClient`) and then integrating changes into `HostClient` if possible.

**Comment by zhuqiuyang** [comment]
ask a question, i copy your code above.
```
import (
    "github.com/valyala/fasthttp"
)

var proxyClient = &fasthttp.HostClient{
    Addr: "upstream.host:port",
    // set other options here if required - most notably timeouts.
}

func ReverseProxyHandler(ctx *fasthttp.RequestCtx) {
    req := &ctx.Request
    resp := &ctx.Response
    prepareRequest(req)
    if err := proxyClient.Do(req, resp); err != nil {
        ctx.Logger().Printf("error when proxying the request: %s", err)
    }
    postprocessResponse(resp)
}

func prepareRequest(req *fasthttp.Request) {
    // do not proxy "Connection" header.
    req.Header.Del("Connection")
    // strip other unneeded headers.

    // alter other request params before sending them to upstream host
}

func postprocessResponse(resp *fasthttp.Response) {
    // do not proxy "Connection" header
    resp.Header.Del("Connection")

    // strip other unneeded headers

    // alter other response data if needed
}

func main() {
    if err := fasthttp.ListenAndServe(":8080", reverseProxyHandler); err != nil {
        log.Fatalf("error in fasthttp server: %s", err)
    }
}
```

but i throw an error, maybe i'm unfamiliar with fasthttp.

> error when proxying the request: the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection

i'm a newbie to golang and fasthttp ,another question , how to change the http from proxy server?

**Comment by zhuqiuyang** [comment]
i know why . 
i add 
```go
req.SetHost(upstream.host)
```
in prepareRequest function,
 then it's ok.

**Comment by zhuqiuyang** [comment]
another question , why delete connection header in postprocessResponse function. @valyala

**Comment by katzien** [comment]
@zhuqiuyang Connection, Authenticate and Authorization are "single hop" headers - see http://www.w3.org/Protocols/rfc2616/rfc2616.txt:

```
14.10 Connection
    The Connection general-header field allows the sender to specify
    options that are desired for that particular connection and MUST NOT
    be communicated by proxies over further connections.
```

**Comment by zhuqiuyang** [comment]
@katzien thx for your answer. i have to read it carefully.

**Comment by bronze1man** [comment]
@valyala thx for your answer. I think it may be better to add an example of Reverse Proxy in the source code.

**Comment by hiqsociety** [comment]
how do i stop sending to client if i detected some status response from the backend? e.g. dropping the client connection or not sending to client.

> Currently there is no reverse proxy, but it is [on the radar](https://github.com/valyala/fasthttp/blob/master/TODO) - see 'proxy handler' line there.
> 
> Currently reverse proxy may be implemented quite easily using [HostClient](https://godoc.org/github.com/valyala/fasthttp#HostClient):
> 
> ```go
> import (
>     "github.com/valyala/fasthttp"
> )
> 
> var proxyClient = &fasthttp.HostClient{
>     Addr: "upstream.host:port",
>     // set other options here if required - most notably timeouts.
> }
> 
> func ReverseProxyHandler(ctx *fasthttp.RequestCtx) {
>     req := &ctx.Request
>     resp := &ctx.Response
>     prepareRequest(req)
>     if err := proxyClient.Do(req, resp); err != nil {
>         ctx.Logger().Printf("error when proxying the request: %s", err)
>     }
>     postprocessResponse(resp)
> }
> 
> func prepareRequest(req *fasthttp.Request) {
>     // do not proxy "Connection" header.
>     req.Header.Del("Connection")
>     // strip other unneeded headers.
> 
>     // alter other request params before sending them to upstream host
> }
> 
> func postprocessResponse(resp *fasthttp.Response) {
>     // do not proxy "Connection" header
>     resp.Header.Del("Connection")
> 
>     // strip other unneeded headers
> 
>     // alter other response data if needed
> }
> 
> func main() {
>     if err := fasthttp.ListenAndServe(":8080", reverseProxyHandler); err != nil {
>         log.Fatalf("error in fasthttp server: %s", err)
>     }
> }
> ```

**Comment by hiqsociety** [comment]
how can i control when to send the request to client? e.g. i would like to send the status and header and body information based through cache and not proxy backend.

**Comment by erikdubbelboer** [comment]
If you want to respond based on the response of the backend you can read the response from `resp` and decide based on that. You can for example [reset the response](https://godoc.org/github.com/valyala/fasthttp#Response.Reset) if you don't want to send back what the backend responded with.

In your example this line sends the request
```go
if err := proxyClient.Do(req, resp); err != nil {
```
So you control when to send it by calling or not calling this line I guess.

**Comment by hiqsociety** [comment]
ok thx.

**Comment by baurine** [comment]
> i know why .
> i add
> 
> ```go
> req.SetHost(upstream.host)
> ```
> 
> in prepareRequest function,
> then it's ok.

You saved me! thanks a lot!
