### ISSUE TITLE
Can you pls put the optimum maximum capacity for reverse proxy?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#641]
With reference to this:
https://github.com/valyala/fasthttp/issues/64

Would like to have the optimum max for open files, incoming connections, max clients etc etc for both incoming and outgoing connections.

pls provide the maximum setting. I'm seeing a lot of dropped connections. i would like to have time to first byte as 10s, wait for 30 seconds for response and close the connection in 1800 seconds and transfer of up to 100mb file. Currently I have this. the doc does not have any optimum / recommended setting. will be best if can have some configuration suggestion for different scenario. Thanks in advance.

        proxyClient := &fasthttp.HostClient{
                Addr: "127.0.0.1:80",
                MaxConns: 65535,
                MaxIdleConnDuration: 30 * time.Second,
                ReadTimeout: 30 * time.Second,
                WriteTimeout: 30 * time.Second,
}

**Comment by erikdubbelboer** [comment]
There is no specific optimum. It all depends on what kind of requests you are handling, what kind of hardware you are running on, network latency, other things running on the same machine, ...

What is the reason the connections are being dropped? Are they timing out? How many requests are you handling per second? Are you using keep-alive connections or does your backend not like this (if you are I would increase `MaxIdleConnDuration` by a lot)?

**Comment by hiqsociety** [comment]
i'm running reverse proxies using fasthttp
Is it advisable to have keep-alive for both reverse proxies (RP)
Haproxy <-> RP <-> RP <-> Backend? 

if so, how do i do the keep-alive setting?

**Comment by erikdubbelboer** [comment]
Yes having keep-alive connections is always good. Unless you only have 1 request per hour or so. How many requests are we talking about?

You said `I'm seeing a lot of dropped connections.`. How are you seeing this?
