### ISSUE TITLE
ShutDown Server in GoRoutine from Main

### ISSUE THREAD

**Issue by Eskies** [valyala/fasthttp#642]
Hello, I tried to shut down the server that running in goroutine from main, but I never get a return from the server. It always hangs and server won't stop. Is there any example to do this? Btw, this is what I'm done.
```go
signalExit := false
var wg sync.WaitGroup
r := router.New()
r.GET("/", Index)
s := &fasthttp.Server{
	Handler:           r.Handler,
	Name:              "Microservice",
	ReduceMemoryUsage: true,
	ReadTimeout:       time.Duration(30 * time.Second),
}

wg.Add(1)
go func() {
	defer func() {
		fmt.Printf("|%s| Closing Server/Rountine\n", time.Now().Format("02-01-2006 15:04:05"))
		fmt.Println("Goodbye!....")
		wg.Done()
	}()

	fmt.Println("============================================")
	fmt.Printf("|%s| Microservice - Starting\n", time.Now().Format("02-01-2006 15:04:05"))

	for signalExit == false {
		fmt.Printf("|%s| Listening on: %s\n", time.Now().Format("02-01-2006 15:04:05"), localtools.ListenAdr)
		err := s.ListenAndServe(localtools.ListenAdr)
		if err != nil {
			fmt.Sprintf("error in ListenAndServe: %s", err)
			fmt.Printf("\n|%s| Recovery From Error\n", time.Now().Format("02-01-2006 15:04:05"))
		}
		fmt.Printf("|%s| Stop Listen on: 127.0.0.1:6669\n", time.Now().Format("02-01-2006 15:04:05"))
	}

}()

c := make(chan os.Signal, 1)
signal.Notify(c, os.Interrupt, os.Kill)
<-c
fmt.Printf("|%s| Got Signal from OS - Telling Server/Rountine to Stop\n", time.Now().Format("02-01-2006 15:04:05"))
signalExit = true
_ = s.Shutdown
wg.Wait()

os.Exit(0)
```

I'm adding control to re-run server if crashed with `signalExit` variable, I think it could help me to keep the server running.

**Comment by kirillDanshin** [comment]
```
_ = s.Shutdown
```

you forgot to actually call s.Shutdown()

**Comment by Eskies** [comment]
oh really, it just missing 2 chars...
It took 2 days to look at it.
Thanks 👍

**Comment by erikdubbelboer** [comment]
Also you really don't want to do `for signalExit == false {`. This will consume 1 full CPU core for 100%!

**Comment by Eskies** [comment]
> Also you really don't want to do `for signalExit == false {`. This will consume 1 full CPU core for 100%!

Is there any good way to keep my server up/restart if an error happened?

**Comment by erikdubbelboer** [comment]
I didn't see the `ListenAndServe` in that for loop. It won't use any CPU. But you can just remove the for loop and `signalExit` and it will still work fine and exit the goroutine once `ListenAndServe` returns from `Shutdown`.
