### ISSUE TITLE
FasthttpSocksDialer makes new proxy connection for each request

### ISSUE THREAD

**Issue by ubombi** [valyala/fasthttp#644]
SOCKS5 is capable of proxying multiple connections. I think there is no need to make a separate proxy connection for each HTTP(S) request.

https://github.com/valyala/fasthttp/blob/8ce231e840720d91e22f855ddba797b3b916fc75/fasthttpproxy/socks5.go#L17-L25

Should be replaced with code like:
```go
func FasthttpSocksDialer(proxyAddr string) (fasthttp.DialFunc, error) {
	dialer, err := proxy.SOCKS5("tcp", proxyAddr, nil, proxy.Direct)
	if err != nil {
		return nil, err
	}
        return func(addr string) (net.Conn, error) {
		return dialer.Dial("tcp", addr)
	}, nil
}
```

Or replace it with Docs, like 
```
// Example usage:
// Make a proxy dialer
//   dialer, err := proxy.SOCKS5("tcp", "localhost:9050", nil, proxy.Direct)
// And use it in Client
//   c := &fasthttp.Client{
//       Dial: func(addr string) (net.Conn, error) {
//           return dialer.Dial("tcp", addr)
//       },
//   }
```

**Comment by erikdubbelboer** [comment]
Thanks, it's fixed in https://github.com/valyala/fasthttp/commit/e5e21db0c30040eede8af4d11abc91be6f996063
