### ISSUE TITLE
Support Close connection by user, not automately

### ISSUE THREAD

**Issue by hoojos** [valyala/fasthttp#648]
Hello:
     I am writing a http load test tool, and choose **fasthttp** as my http client library. This load test tool is a long time running process, I find client will not close connection if i never use the same client. could you please expose Close function api to users?

**Comment by erikdubbelboer** [comment]
That's exactly what [`Request.SetConnectionClose()`](https://godoc.org/github.com/valyala/fasthttp#Request.SetConnectionClose) is for. It will make sure the connection gets closed after the request is done. Another way it to set [`Client.MaxIdleConnDuration`](https://godoc.org/github.com/valyala/fasthttp#Client.MaxIdleConnDuration) too a low but not `0` value.
