### ISSUE TITLE
error: non-zero body for non-POST request

### ISSUE THREAD

**Issue by medcampus** [valyala/fasthttp#651]

**Comment by erikdubbelboer** [comment]
What is the question exactly?

**Comment by kirillDanshin** [comment]
@medcampus if I understand you correctly, you tried to send a body within GET or HEAD request. it's not supported.

Feel free to reopen this issue if you have further questions on this topic.

**Comment by jordantaylor2** [comment]
In our use of fasthttp, we've also encountered this issue as one of our downstream services supports gets with a body. I've been doing some reading and it seems that the spirit of the HTTP spec is that non-posts have no restrictions on having a body, but no logic should be done on the body of a non-POST request so checking its size to produce an error shouldn't be how its done. Rather, the body should just be passed along and not checked by the HTTP implementation.

As seen in [the HTTP spec for POST requests](https://tools.ietf.org/html/rfc2616#section-9.3), there is no restriction on e.g. a GET request having a body.

On other projects on GitHub, I've seen similar issues come up and I feel this comment states it well: https://github.com/postmanlabs/postman-app-support/issues/131#issuecomment-109812798

I think that it makes sense to avoid throwing an error on non-POST requests with a body based on the aforementioned. Would it be possible to change this behavior? It seems to be from [here](https://github.com/valyala/fasthttp/blob/master/http.go#L1200)
