### ISSUE TITLE
How can I set proxy for fasthttp client ?

### ISSUE THREAD

**Issue by PePoDev** [valyala/fasthttp#652]
I see this [repo](https://github.com/imroc/req)
And they can set http proxy.
I want to do that for fasthttp too.

Like this

```go
 req.SetProxy(func(r *http.Request) (*url.URL, error) {
 	if strings.Contains(r.URL.Hostname(), "google") {
 		return url.Parse("http://my.vpn.com:23456")
 	}
 	return nil, nil
})
```
or
```go
req.SetProxyUrl("http://my.proxy.com:23456")
```

**Comment by erikdubbelboer** [comment]
You can use [`Client.Dial`](https://godoc.org/github.com/valyala/fasthttp#Client.Dial) and [`fasthttpproxy.FasthttpSocksDialer`](https://godoc.org/github.com/valyala/fasthttp/fasthttpproxy#FasthttpSocksDialer) for this.

So it would be like:
```go
client := fasthttp.Client{
 	Dial: func(addr string) (net.Conn, error) {
 	 	if strings.Contains(addr, "google") {
 	 	 	return fasthttpproxy.FasthttpSocksDialer("my.vpn.com:23456")
 	 	} else {
 	 	 	return fasthttp.Dial(addr)
 	 	}
 	},
}
```
