### ISSUE TITLE
Need a way to write unit test

### ISSUE THREAD

**Issue by caibirdme** [valyala/fasthttp#661]
cuz fasthttp's function signature is `func(ctx *fasthttp.RequestCtx)`, so we need a convenient way to create the fasthttp.RequestCtx object. For now, I didn't find any way to do it. I think a function like `InitRequestCtx(req *http.Request) *fasthttp.RequestCtx` that can convert a standard http.Request to fasthttp.RequestCtx is very helpful.
How do u think about that? I'm willing to add it in fasthttputil if it's feasible

**Comment by dgrr** [comment]
https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Init
