### ISSUE TITLE
may be data race in pipeConn.readNextByteBuffer

### ISSUE THREAD

**Issue by rogercarter1** [valyala/fasthttp#664]
https://github.com/valyala/fasthttp/blob/b1ca43febc44fadacbe003d3760dfa3e8395bf7c/fasthttputil/pipeconns.go#L169

There is three references of c.readDeadlineCh , but only two of them are protected by the locker.
At least this will make the code reader ask whether there is a data race question.
So fix it or a comment why not fix it should be added.

**Comment by erikdubbelboer** [comment]
Good point, I'll commit a fix tomorrow.
