### ISSUE TITLE
appendBodyFixedSize memory gradually rising

### ISSUE THREAD

**Issue by zplzpl** [valyala/fasthttp#667]
- I use fasthttp client as the crawler's httpclient.
- goroutine concurrency is 200.
- The number of URLs crawled is 300,000.
- Memory keeps rising over time.

**go version go1.12.9 windows/amd64**

**fasthttp version 1.5.0**

**Can you provide some help? I hope that the memory should be in a stable state because my concurrency is fixed.**

# More detailed information

about pprof and pseudo code

## go tool pprof -inuse_space heap

```
(pprof) top 1
Showing nodes accounting for 23.46MB, 92.14% of 25.46MB total
Showing top 1 nodes out of 23
      flat  flat%   sum%        cum   cum%
   23.46MB 92.14% 92.14%    23.46MB 92.14%  github.com/valyala/fasthttp.appendBodyFixedSize

(pprof) list appendBodyFixedSize
Total: 25.46MB
ROUTINE ======================== github.com/valyala/fasthttp.appendBodyFixedSize in \d\goproject\pkg\mod\github.com\valyala\fasthttp@v1.5.0\http.go
   23.46MB    23.46MB (flat, cum) 92.14% of Total
         .          .   1713:   }
         .          .   1714:
         .          .   1715:   offset := len(dst)
         .          .   1716:   dstLen := offset + n
         .          .   1717:   if cap(dst) < dstLen {
   23.46MB    23.46MB   1718:           b := make([]byte, round2(dstLen))
         .          .   1719:           copy(b, dst)
         .          .   1720:           dst = b
         .          .   1721:   }
         .          .   1722:   dst = dst[:dstLen]
         .          .   1723:
```

## fetch Pseudo code

```
// concurrent quantity control 
......

// fasthttp client
req,res := fasthttp.AcquireRequest(),fasthttp.AcquireResponse()
	defer func() {
		fasthttp.ReleaseRequest(req)
		fasthttp.ReleaseResponse(res)
	}()

// request params set
req.SetRequestURI(u)
	req.Header.SetMethod(method)
	for k,vs := range hdr {
		for _,v := range vs {
			req.Header.Add(k,v)
		}
	}
	req.SetBody(requestBody)
	req.SetHost(host)

// client.Do
fasthttp.Client.Do(req,res)

// handle Response
handleOnResponse(res)

return
```

**Comment by zplzpl** [comment]
I found the reason.

**The cause is caused by the design of the bytebuffer pool.**

I would like to make two suggestions:

* fasthttp open bytebuff pool capabilities. (use interface to define)
* bytebufferpool provides more setup configuration functions to intervene in some important configurations. For example:

```
const (
	minBitSize = 6 // 2**6=64 is a CPU cache line size
	steps      = 20

	minSize = 1 << minBitSize
	maxSize = 1 << (minBitSize + steps - 1)

	calibrateCallsThreshold = 42000
	maxPercentile           = 0.95
)
```

@valyala

**Comment by erikdubbelboer** [comment]
Yes fasthttp will keep memory in buffers to be able to reuse this memory instead of the garbage collector spending time cleaning it up. This means that in the start memory will grow but at some point it will stabilize.

This approach works best if all your bodies are around the same size. If you have small bodies most of the time but once in a while a big body it will keep those big buffers around and your average memory usage will be higher than it in theory should be. Exposing more control over the bytebuffer pool would be one way to fix this. Pull requests are always welcome!
