### ISSUE TITLE
Errors thrown on GET requests with bodies, despite them being allowed in the HTTP spec

### ISSUE THREAD

**Issue by jordantaylor2** [valyala/fasthttp#670]
In our use of fasthttp, we've encountered this issue as one of our downstream services supports gets with a body. I've been doing some reading and it seems that the spirit of the HTTP spec is that non-posts have no restrictions on having a body, but no logic should be done on the body of a non-POST request so checking its size to produce an error shouldn't be how its done. Rather, the body should just be passed along and not checked by the HTTP implementation.

As seen in [the HTTP spec for GET requests](https://tools.ietf.org/html/rfc2616#section-9.3), there is no restriction on e.g. a GET request having a body.

On other projects on GitHub, I've seen similar issues come up and I feel this comment states it well: https://github.com/postmanlabs/postman-app-support/issues/131#issuecomment-109812798

I think that it makes sense to avoid throwing an error on non-POST requests with a body based on the aforementioned. Would it be possible to change this behavior? It seems to be from [here](https://github.com/valyala/fasthttp/blob/master/http.go#L1200)

**Comment by erikdubbelboer** [comment]
After thinking about it I'm in favor of changing this behavior and just always allowing a body.

@kirillDanshin @dgrr what do you guys think?

**Comment by tsingson** [comment]
5 years ago,  my project in java that support GET with payload. sometime it's very useful.

**Comment by micross** [comment]
upset that fasthttp reject the message body from the GET request

**Comment by erikdubbelboer** [comment]
This should be fixed now in master.
