### ISSUE TITLE
go mod install error

### ISSUE THREAD

**Issue by cyanBone** [valyala/fasthttp#681]
fasttools ➤ go get github.com/valyala/fasthttp                                                                                                                                  
go: downloading github.com/valyala/fasthttp v1.5.0
verifying github.com/valyala/fasthttp@v1.5.0: github.com/valyala/fasthttp@v1.5.0: Get https://sum.golang.org/lookup/github.com/valyala/fasthttp@v1.5.0: dial tcp 172.217.27.145:443: i/o timeout

**Comment by erikdubbelboer** [comment]
Looks like you have problems connecting to sum.golang.org. Are you behind a firewall or VPN that might be blocking access to this domain?

**Comment by cyanBone** [comment]
thanks ,Just add proxy
