### ISSUE TITLE
fasthttp client limit body read and also handle connection reuse

### ISSUE THREAD

**Issue by Ice3man543** [valyala/fasthttp#686]
Hi, kudos for the really nice library.

I'm doing a lot of http requests to different sites and came across fasthttp which seems a better solution for my needs. My question is that net/http provides a simple io.Reader which can be chained with io.LimitReader to limit the number of bytes we read from the http response preventing DOS attacks, but fasthttp doesn't seems to provide any such functionality. There does seem to be a MaxResponseSize but i'm not sure if that's what i need?

Next question is whether connection reuse happens by default even if i do not read the response. Because in stdlib, if you don't read the full response body, it doesn't do connection reuse.

Thanks!

**Comment by erikdubbelboer** [comment]
[`Client.MaxResponseBodySize`](https://godoc.org/github.com/valyala/fasthttp#Client.MaxResponseBodySize) is indeed what you need.

Yes, connection reuse happens by default. Unless you call [`Request.SetConnectionClose()`](https://godoc.org/github.com/valyala/fasthttp#Request.SetConnectionClose). fasthttp will always read the entire response, so you don't need to do this like you have to with stdlib.
