### ISSUE TITLE
Do we have equivalent to http.Header.Add?

### ISSUE THREAD

**Issue by vishr** [valyala/fasthttp#69]
I am not able to find a function equivalent to `http.Header#Add(key, val string)`, do we have one?

**Comment by valyala** [comment]
There is [ResponseHeader.Set](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.Set). But it cannot add multiple headers with the same name.
There are plans for adding `http.Header#Add()` equivalent to fasthttp later.

**Comment by valyala** [comment]
Added [ResponseHeader.Add](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.Add) and [RequestHeader.Add](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Add) for setting multiple headers under the same key.
