### ISSUE TITLE
Data corruption for header values

### ISSUE THREAD

**Issue by vladc** [valyala/fasthttp#690]
We've been running a server based on fasthttp and we've encountered a strange bug.
After a random amount of requests (many millions) the value of a header field is corrupted, for no obvious reason. I've managed to capture such a request with tcpdump and the value being received by fasthttp is correct.

This is the code that we use:
```
func main() {
	var TCPcfg = &tcplisten.Config{
		ReusePort:   false,
		DeferAccept: true,
		FastOpen:    true,
	}
	go func() {
		ln, err := TCPcfg.NewListener("tcp4", "0.0.0.0:80")
		if err != nil {
			log.Fatalf("error in listener: %s", err)
		}
		s := &fasthttp.Server{
			Handler:               requestHandler,
			ReadTimeout:           6 * time.Second,
			WriteTimeout:          6 * time.Second,
			IdleTimeout:           10 * time.Second,
			NoDefaultServerHeader: true,
			Logger:                log.New(ioutil.Discard, "", 0),
		}
		if err = s.Serve(ln); err != nil {
			log.Fatalf("error: %s", err)
		}
	}()
}

func requestHandler(c *fasthttp.RequestCtx) {
	var ip net.IP
	proxyHeader := string(c.Request.Header.Peek("OriginalIP"))
	if len(proxyHeader) > 0 {
		ip = net.ParseIP(proxyHeader).To4()
		if ip == nil {
			log.Printf("error, %s sent bad proxy header: %q %q", c.RemoteIP(), c.Request.Header.RawHeaders(), proxyHeader)
			c.SetStatusCode(422)
			return
		}
	}
	[...]
}
```

Here's an example of the above error, including the headers received:

> error, -snipped- sent bad proxy header: "http.keepAlive: false\r\nUser-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.2; SM-G355H Build/KOT49H)\r\nHost: -snipped-\r\nConnection: Keep-Alive\r\nAccept-Encoding: gzip\r\nOriginalIP: 31.184.182205 \r\n\r\n" "31.184.182205"

Some more values that were corrupted:
> .39.227.236
> 4730.146.220
> 87142.45.34

I've been trying to replicate this issue locally, but after many billions of requests I haven't been able to see the bug. Annoyingly, it only happens in production. We've seen the bug on more than one server.

Do you have any suggestions on how I could debug this further or any idea how this can happen?

**Comment by erikdubbelboer** [comment]
Are you doing anything else with headers in other parts of your code?

This example program https://gist.github.com/erikdubbelboer/81a1f23be935e5b764506f728f021423 shows how changing old header values can corrupt the headers of incoming requests. I'm guessing this is happening somewhere in your `[...]` code block.

If you check the fasthttp source you can see that [`RawHeaders()` just returns `rawHeadersCopy`](https://github.com/valyala/fasthttp/blob/70223a183c44d77b3362f263cef6cfa45650c5a5/header.go#L1566-L1567). And [`rawHeadersCopy` is just a copy of the headers](https://github.com/valyala/fasthttp/blob/70223a183c44d77b3362f263cef6cfa45650c5a5/header.go#L1671) that is made before any processing is done on them.

So I'm thinking the headers are already corrupted before they reach this code.

**Comment by vladc** [comment]
Thank you for the gist and the explanation.

The code doesn't do anything by reference to the request headers, the only other related calls are:
```
strings.TrimSuffix(string(c.Request.Header.Peek("Origin")), "/")
c.Response.Header.Set() 
c.Request.SetRequestURI()
```
Converting from byte to string should create a copy, correct? 
Additionally, everything happens inside requestHandler() function, there are no other calls to the ctx after it returns.

**Comment by erikdubbelboer** [comment]
Would you mind sharing the code so I can have a look? If you don't want to share it publicly you can also email it to erik@dubbelboer.com if that's ok.

I have never seen this issue myself. Even after millions and millions of requests. So I want to make 100% sure first that it's not something in your code.

When you were looking at these requests in TCP dump, what was the actual IP and what was the corresponding return value from `.Peek("OriginalIP")`? Maybe the way the header is malformed will help finding the issue.
