### ISSUE TITLE
about parameter MaxConnDuration 

### ISSUE THREAD

**Issue by ndsun** [valyala/fasthttp#692]
when I user fasthttp.Client,why I can not set the MaxConnDuration  value.I check the source code, fasthttpClient also user HostClient to send http request, but why HostClient can set MaxConnDuration , Client can't do this?

**Comment by erikdubbelboer** [comment]
Do you really want `MaxConnDuration` or do you want [`Client.MaxIdleConnDuration`](https://godoc.org/github.com/valyala/fasthttp#Client.MaxIdleConnDuration)?

`MaxConnDuration` will kill the connection even if it just had a request. So it kills connections even if it isstill being used (not during a request). `MaxIdleConnDuration` will kill the connection only when it hasn't been used for `MaxIdleConnDuration`. This normally makes much more sense as there is no need to kill connections that are still being used.

If you really need `MaxConnDuration` in `Client` we can easily add it.

**Comment by ndsun** [comment]
Thanks for your reply. I know the differences between MaxConnDuration and MaxIdleConnDuration. And I really need MaxConnDuration.I want't to use it because I don't want a connection always being used, If you can add it, that's very good!

**Comment by erikdubbelboer** [comment]
This is fixed in: https://github.com/valyala/fasthttp/commit/5f666588000bc4a0e0852494958417036ccbb3b7

**Comment by ndsun** [comment]
Thank you very much!

**Comment by transfercai** [comment]
I wonder How MaxConnDuration work as? does it kill connection where the request is being used, etc. I created a connection which timeout is 10 sec, and MaxConnDuration is 12 sec, when the down service response and used 9sec, an other request income reused this connection which timeout is also 10 sec, but connection will be killed in (12-9)=3sec, then I got timeout error.
