### ISSUE TITLE
Unnecessary allocations on init

### ISSUE THREAD

**Issue by zilman** [valyala/fasthttp#693]
Just by importing fasthttp it kicks off a refreshServerDate goroutine - [header.go#L1439](https://github.com/valyala/fasthttp/blob/master/header.go#L1439).

Keeping the time up to date in response headers is obviously useful but for users who only use fasthttp as a client this appears to be completely unnecessary. 

I admit that one timer causes a _tiny_ amount of allocations but this goroutine is entirely the difference between a zeroallocations fasthttp client, so I think it is worth making it configurable somehow.

**Comment by erikdubbelboer** [comment]
I guess we could start it in a [`once.Do`](https://golang.org/pkg/sync/#Once.Do) at every place we need it. That would only add a single `atomic.LoadUint32` as overhead in these places which I guess is acceptable.

I'll fix when I have some time tomorrow.
