### ISSUE TITLE
How do I override response write method to be able to fit in adaptor writer?

### ISSUE THREAD

**Issue by vishr** [valyala/fasthttp#70]
Hello,

I have a need to put `gzip` adapter  writer on `*fasthttp.RequestCtx` to be able use it with gzip middleware in Echo. With `http.ResponseWriter` I can override `Write ` method. How can I do it with `fasthttp`?

I tried the following code but need help to make it work.

```go

func handler(ctx *fasthttp.RequestCtx) {
	w := gzip.NewWriter(ctx)
	ctx.Response.WriteTo(w)
	ctx.Response.BodyWriteTo(w)
	// ctx.Response.Header.Set("Content-Encoding", "gzip")
	ctx.Write([]byte("Hello world"))
}

func main() {
	fasthttp.ListenAndServe(":1323", handler)
}
```

Any help appreciated!

**Comment by valyala** [comment]
Hi Vishal,

Just compress response body after the wrapped request handler returns. See
how CompressHandlerLevel
<https://github.com/valyala/fasthttp/blob/master/server.go#L322> is
implemented.

On Wed, Mar 16, 2016 at 6:56 AM, Vishal Rana <notifications@github.com>
wrote:

> Hello,
>
> I have a need to put gzip adapter writer on *fasthttp.RequestCtx to be
> able use it with gzip middleware in Echo. With http.ResponseWriter I can
> override Write method. How can I do it with fasthttp?
>
> I tried the following code but need help to make it work.
>
> func handler(ctx *fasthttp.RequestCtx) {
>     w := gzip.NewWriter(ctx)
>     ctx.Response.WriteTo(w)
>     ctx.Response.BodyWriteTo(w)
>     // ctx.Response.Header.Set("Content-Encoding", "gzip")
>     ctx.Write([]byte("Hello world"))
> }
> func main() {
>     fasthttp.ListenAndServe(":1323", handler)
> }
>
> Any help appreciated!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/valyala/fasthttp/issues/70>
>



-- 
Best Regards,

Aliaksandr

**Comment by vishr** [comment]
Thanks @valyala. I will re-open if required.
