### ISSUE TITLE
[Documentation] Upload a file with greater dimension than DefaultMaxRequestBodySize

### ISSUE THREAD

**Issue by alessiosavi** [valyala/fasthttp#700]
Hi Team,

I can not find an example for upload a file with greater dimension than the `DefaultMaxRequestBodySize`. Could you please share how to upload a big file using `fasthttp`?

Unfortunately, I receive the error `body size exceeds the given limit`.

**Comment by erikdubbelboer** [comment]
The documentation for `DefaultMaxRequestBodySize` says:
```
See Server.MaxRequestBodySize for details. 
```
You need to set [`Server.MaxRequestBodySize`](https://godoc.org/github.com/valyala/fasthttp#Server.MaxRequestBodySize) to a higher value than your file size.

**Comment by alessiosavi** [comment]
Hi @erikdubbelboer , thank you for the response.

I've changed the `Server.MaxRequestBodySize` as following:

```go

// The gzipHandler will serve a compress request only if the client request it with headers (Content-Type: gzip, deflate)
gzipHandler := fasthttp.CompressHandlerLevel(m, fasthttp.CompressBestCompression) // Compress data before sending (if requested by the client)

s := &fasthttp.Server{
	Handler: gzipHandler,
	// Every response will contain 'Server: Check diff binary server' header.
	Name: "Check diff binary server",
	// Other Server settings may be set here.
	MaxRequestBodySize: 100 * 1024 * 1024,
}
```

It's possibile to accept a file with arbitrary dimension instead of using the limit of `MaxRequestBodySize`?

**Comment by erikdubbelboer** [comment]
If you want to allow any size upload you could just set `MaxRequestBodySize: math.MaxInt32,` or some other really high number. Or is that not what you mean?

**Comment by alessiosavi** [comment]
Hi @erikdubbelboer,

Yes, it the solution that i've found. I was trying to find a method for avoid to set an high number for limit the `MaxRequestBodySize` and, instead, read everything.

I accept the solution of set an high number, cause from the architectural POV is the method for limit the dimension of the file.

Thank you for the time (:
