### ISSUE TITLE
Stopping the request on demand without killing program

### ISSUE THREAD

**Issue by kashkashio** [valyala/fasthttp#704]
Hi Guys,
First i want to say thank you for the amazing work and the brilliant library which delivers what its suppose to !

So i'm developing http server and i came into an issue which i can't overcome..
I'm pretty sure that there is a way to achieve what i'm looking for but i searched all issues and code to try and figure how but without any luck :\

I Will explain:
http request incoming to the handler, and i want a way to call something anywhere in the code that will stop the current running flow and return response to the user.

os.exit for example isn't good because it will terminate the server.

As far as i understand every request is a new goroutine in the system right?
There must be a way to call a function on the context that will kill the current running code in the handler and "return" is not good enough because it will require me to do checks after every function and wont allow me to cut in 2nd or 3rd level functions, every parent function will have to check the children function with if return statement which i'm trying to avoid.

Is there any already implemented way to do so?
Think of it as a "Global Return" for the handler

e.g:
```go
func LoadData() {
    data := Sql.query("blahblahblah")
    if data == nil {
        {{ this is the point i want to break the flow }}
    }
}

func requestHandler(ctx *fasthttp.RequestCtx){
    LoadData()
    // This is where i dont want the code to reach after calling the break on LoadData
    DoSomething()
}
```
Any help will be appreciated, thanks a lot !

**Comment by kashkashio** [comment]
any help ?

**Comment by erikdubbelboer** [comment]
I'm afraid that there is no very easy way to do this in Go. If you don't want to do this using an error that gets propagated all the way down you could try using a `panic` and `defer` `recover` from that error at the top of your handler.

Another method could be `runtime.Goexit()`](https://golang.org/pkg/runtime/#Goexit) but this is not advised as this method is really only for testing and debugging.

**Comment by kashkashio** [comment]
Thanks a lot !
