### ISSUE TITLE
How to http.Transport.Dial adapter for HTTPproxy support ?

### ISSUE THREAD

**Issue by LeMoussel** [valyala/fasthttp#706]
HI,

I need to visit a website by http proxy. I just found [socket proxy](https://github.com/valyala/fasthttp/blob/master/fasthttpproxy/socks5.go#L17) in fasthttp.

In another project, I overrides the previously used `http.Transport` like this :
```
proxyUrl, err := url.Parse("http://proxyIp:proxyPort")
http.DefaultTransport = &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
```
but it doesn't work with fasthttp. How can I use http proxy with fasthttp?

**Comment by erikdubbelboer** [comment]
The example is right there in the comment:
https://github.com/valyala/fasthttp/blob/a266a926ae7cf645c53b201a499d8a69e4566aaf/fasthttpproxy/socks5.go#L13-L17

You then use that [Client](https://godoc.org/github.com/valyala/fasthttp#Client) to make requests.

There is no such thing as `DefaultTransport` to overwrite it globally.

**Comment by LeMoussel** [comment]
OK. But How can I overwrite it locally?
The example is right for SOCKS Proxy but for HTTP Proxy how do we do it? `FasthttpHttpDialer(....)`?

**Comment by erikdubbelboer** [comment]
An example of how to use a HTTP proxy can be found here: https://github.com/valyala/fasthttp/blob/a266a926ae7cf645c53b201a499d8a69e4566aaf/client_example_test.go#L10-L17

**Comment by LeMoussel** [comment]
Thank you for your help.

**Comment by 1602** [comment]
What if proxy requires auth?

**Comment by erikdubbelboer** [comment]
@1602 then you just have to add a `Proxy-Authorization` header to the request as far as I know.
