### ISSUE TITLE
skip verify tls error

### ISSUE THREAD

**Issue by kingangelAOA** [valyala/fasthttp#709]
hc := fasthttp.Client{
		MaxConnsPerHost: 60000,
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
	}
	req := fasthttp.AcquireRequest()
	req.SetBody([]byte(`{"username":"xxxxxx", "password":"xxxxxx"}`))
	req.Header.SetContentType("application/x-www-form-urlencoded")
	req.Header.SetMethod("POST")
	resp := fasthttp.AcquireResponse()
	req.SetRequestURI("https://127.0.0.1:8060/fip/v1/auth/login")
	defer fasthttp.ReleaseRequest(req)
	defer fasthttp.ReleaseResponse(resp)
	if err := hc.DoTimeout(req, resp, 20*time.Second); err != nil {
	}

fmt.Println(string(resp.Body()))
   result: Bad credentials

tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: tr}
	data := url.Values{"username":{"xxxxxxx"}, "password":{"xxxxxxx"}}
	body := strings.NewReader(data.Encode())
	r, err := client.Post("https://127.0.0.1:8060/fip/v1/auth/login",  "application/x-www-form-urlencoded", body)
	if err != nil {
		fmt.Println(err)
	}
	bodyBytes, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Fatal(err)
	}
	bodyString := string(bodyBytes)
	fmt.Println(bodyString)
result: is ok

**Comment by erikdubbelboer** [comment]
Did you find the issue?
