### ISSUE TITLE
Is this the fastest http server for go 2020?

### ISSUE THREAD

**Issue by Fenny** [valyala/fasthttp#710]
Hello,

I started go one month after nodejs could not bring the performance to the table that I needed.
When searching for fast http frameworks, fasthttp was in the top 20.

But the top 5 (according to benchmarks) are dominated by rust.

- What is the reason rust beats almost every language out there in http performance?
- Is fasthttp currently the fastest http framework in go?

PS: Coming from nodejs, I ( and probably many others ) are used to the [expressjs](https://expressjs.com/) framework.
Since all routers that are made for fasthttp are either non-maintained or outdated, can we expect a build-in router into fasthttp?

Something like rust did with [nickel.rs](https://github.com/nickel-org/nickel.rs)

Thank you!

**Comment by proyb6** [comment]
Why is the reason rust beats almost every language out there in http performance?
Rust is known for not having garbage collection.

Is fasthttp currently the fastest http framework in go?
According to these simple routers benchmark, yes,
https://github.com/the-benchmarker/web-frameworks/blob/master/README.md

But you still need to specify your requirements for using Go, and recommend profiling with `pprof` to find other bottleneck in the Go application.

**Comment by LeMoussel** [comment]
There is also fork [valyala/fasthttprouter](https://github.com/valyala/fasthttprouter) forked from [buaazp/fasthttprouter](https://github.com/buaazp/fasthttprouter) forked from [julienschmidt/httprouter](https://github.com/julienschmidt/httprouter)

**Comment by kirillDanshin** [comment]
@LeMoussel actually, we maintain github.com/fasthttp/router

**Comment by pellea** [comment]
I'm calling an external API to make a GET request using either fasthttp or net/http and net/http is by far quicker ...
Regarding the benchmarks on the front page; are they still accurate for the latest release?

Top is net/http and bottom is fasthttp:
![image](https://user-images.githubusercontent.com/395982/71622539-a76aa000-2bd6-11ea-9d3e-6f9a1d74911a.png)

Is the difference somehow related to caching?
