### ISSUE TITLE
Вопрос про отдачу файлов

### ISSUE THREAD

**Issue by hardd2007** [valyala/fasthttp#711]
Можно ли ограничивать скорость отдачи файлов через ServeFileUncompressed?
В документации не нашёл. Или писать на стороне клиента?

**Comment by erikdubbelboer** [comment]
I'm afraid there is nothing in fasthttp to limit the speed (bytes per second) of an upload or download.

**Comment by hardd2007** [comment]
Thanks. I'll  do it by client side.
