### ISSUE TITLE
Authorization header helper function

### ISSUE THREAD

**Issue by Dot-H** [valyala/fasthttp#714]
Hi, the net/http package exposes two handy method which are:
* [SetBasicAuth](https://github.com/golang/go/blob/100bf440b9a69c6dce8daeebed038d607c963b8f/src/net/http/request.go#L962)
* [BasicAuth](https://github.com/golang/go/blob/100bf440b9a69c6dce8daeebed038d607c963b8f/src/net/http/request.go#L925)

I could not find those helpers for the Header in the project.

Am I missing something?
If not, what do you think about implementing them as it is related to #609? I would not mind doing it.

**Comment by erikdubbelboer** [comment]
A pull request is always welcome!

**Comment by kirillDanshin** [comment]
You can also take a look into this: https://github.com/gramework/gramework/blob/dev/context_Auth.go

**Comment by Fenny** [comment]
I think this should not belong in an HTTP framework, but as a helper tool/middleware. It should be easy to copy from the link provided above. Can you close this @erikdubbelboer?
