### ISSUE TITLE
Question: HeadersSent logic?

### ISSUE THREAD

**Issue by Fenny** [valyala/fasthttp#719]
Hello,

I'm wondering if fasthttp supports some logic to check if headers are sent.

[nodejs: response.headersSent](https://nodejs.org/api/http.html#http_response_headerssent)
*Boolean (read-only). True if headers were sent, false otherwise.*

// ctx.HeadersSent => false
ctx.Response.SetBodyString("Thank you!")
// ctx.HeadersSent => true
// Continue to finish some database queries that are not important for the user

Is there a better way to send a response to the client and continue execute code after?

Is there a performance drawback using the following method to be able to continue within the function and the client doesn't have to wait?
```go
// Return to client asap.
ctx.SetBodyStreamWriter(func(w *bufio.Writer) {
  w.Write([]byte("Hello, World!"))
  w.Flush()
})
// Finish up some database queries
```
Versus
```go
// Return to client asap.
ctx.SetBody([]byte("Hello, World!"))
// Finish up some database queries
// But wait... client is still waiting for us :<
```

**Comment by erikdubbelboer** [comment]
Fasthttp doesn't support flushing the response before the handler function has ended. Anything like cleanups that the response doesn't have to wait on should be done in another goroutine.

So even if you use `SetBodyStreamWriter`, the function you provided will only be called once the handler function has returned.
