### ISSUE TITLE
ConnectionUpgrade and firefox.

### ISSUE THREAD

**Issue by Eepee1** [valyala/fasthttp#72]
Hey,

Fasthttp's ConnectionUpgrade wont detect if http-request from firefox wants to upgrade, because firefox adds "keep-alive" to the Connection header. So firefox's Connection header looks like "keep-alive, Upgrade", while for others its just "Upgrade".

**Comment by valyala** [comment]
@Eepee1 , thanks for the bug report. It should be fixed now.
