### ISSUE TITLE
TCPDialer is not setting ZoneID.

### ISSUE THREAD

**Issue by anshul-jain881** [valyala/fasthttp#724]
An IPv6 address can have a [ZoneID](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses) followed by a ```%``` sign for example ```http://[fe80::1ff:fe23:4567:890a%tun5]:80/hello/index.html```

Even though the [LookupIPAddr](https://github.com/valyala/fasthttp/blob/master/tcpdialer.go#L448) is returning the ZoneID, [resolveTCPAddrs](https://github.com/valyala/fasthttp/blob/master/tcpdialer.go#L460-L463) is not setting it, causing TCP calls to n/w interface with IPv6 link-local addresses to fail.

Changing the code to set ZoneID line should fix the problem.
```go
addrs = append(addrs, net.TCPAddr{
			IP:   ip.IP,
			Port: port,
                        Zone: ip.Zone,
		})

```

**Comment by erikdubbelboer** [comment]
Thanks, it's been fixed now.
