### ISSUE TITLE
Cookies HttpOnly

### ISSUE THREAD

**Issue by hanscem** [valyala/fasthttp#73]
Is there anyway to include HttpOnly flag to cookies? (sorry im new to web dev)
thank you in advance

**Comment by valyala** [comment]
I just added `HttpOnly` and `secure` flags support to fasthttp Cookie - see [Cookie.HTTPOnly](https://godoc.org/github.com/valyala/fasthttp#Cookie.HTTPOnly), [Cookie.SetHTTPOnly](https://godoc.org/github.com/valyala/fasthttp#Cookie.SetHTTPOnly), [Cookie.Secure](https://godoc.org/github.com/valyala/fasthttp#Cookie.Secure) and [Cookie.SetSecure](https://godoc.org/github.com/valyala/fasthttp#Cookie.SetSecure) for details.

**Comment by hanscem** [comment]
awesome. thanks!
