### ISSUE TITLE
How to check for HTTP(S)? [help wanted] [question]

### ISSUE THREAD

**Issue by AlbinoGeek** [valyala/fasthttp#730]
Hey there,

I couldn't help but notice there's no obvious way to check for HTTP(S) on the connection context, e.g: to selectively redirect to HTTPS when required for certain routes (such as login pages, etc.)

**Comment by erikdubbelboer** [comment]
You can use [`RequestCtx.IsTLS()`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.IsTLS) for this.
