### ISSUE TITLE
possible cause for 502 error in long running request

### ISSUE THREAD

**Issue by harsh-mittal** [valyala/fasthttp#739]
I have long running http request that is database intensive and takes more than 2 minutes to complete. Handler code runs to completion without any errors.

Server is behind a Nginx proxy with timeouts set to 300s (proxy_read_timeout, proxy_send_timeout and proxy_connect_timeout)

![transmission_intercept](https://user-images.githubusercontent.com/1447123/74023749-56bb4380-49db-11ea-95a9-5b82e6909960.png)

<img width="867" alt="502_error" src="https://user-images.githubusercontent.com/1447123/74024827-9551fd80-49dd-11ea-924e-f9dc6442b793.png">

<img width="1674" alt="502_error_body" src="https://user-images.githubusercontent.com/1447123/74024854-a1d65600-49dd-11ea-8969-97795498c869.png">

As can be seen in the screenshots, client receives a 502 at time 120s.

Nginx log contains:
`2020/02/05 17:42:38 [error] 344728#344728: *4968424505 upstream prematurely closed connection at processing header while reading response header from upstream`

I have not been able to figure out what's causing this behaviour in fasthttp. Any suggestions what may be causing this issue?

**Comment by erikdubbelboer** [comment]
What fasthttp config are you using?

**Comment by harsh-mittal** [comment]
```
	httpServer := &fasthttp.Server{
		Concurrency:  config.Concurrency,
		Handler:      fastHandler,
		ReadTimeout:  config.ReadTimeout,
		WriteTimeout: config.WriteTimeout,
	}
```

```
compress = false
concurrency = 10240
read-timeout = 500000000
write-timeout = 500000000
```

**Comment by erikdubbelboer** [comment]
And what are those values in? In Go durations are expressed in nanoseconds which would mean [500000000 is only 0.5 seconds](https://play.golang.org/p/lnL9BQ3F_DD) which would be way to low. But fasthttp also doesn't impose any timeout on the handler itself so that's not the issue.

What could be the issue is that your TCP connection just times out. Try setting [`Server.TCPKeepalive = true`](https://godoc.org/github.com/valyala/fasthttp#Server.TCPKeepalive) and [`Server.TCPKeepalivePeriod = time.Second`](https://godoc.org/github.com/valyala/fasthttp#Server.TCPKeepalivePeriod) for example.

**Comment by harsh-mittal** [comment]
still got 502 after setting `Server.TCPKeepalive = true` and `Server.TCPKeepalivePeriod = time.Second`. And yes read write timeouts are in nanoseconds when passed to fasthttp.

**Comment by erikdubbelboer** [comment]
Would you be willing to share your nginx config and Go code so I can reproduce this locally? Maybe you could replace your database code with a `time.Sleep(time.Minute*2)` so simplify the code that can reproduce this.

**Comment by harsh-mittal** [comment]
I have uploaded a stripped down version of the codebase with which I'm trying to reproduce the bug, https://github.com/harsh-mittal/offline, trying to reproduce the bug

**Comment by harsh-mittal** [comment]
Hi, I have uploaded nginx config [here](https://drive.google.com/file/d/1P12vQje-nyT_bu8xkEydlsStMaaUZZPq/view?usp=sharing) and [sample code](https://github.com/harsh-mittal/offline). Please take a look.
I have not been able to reproduce the bug, maybe you can help.

**Comment by harsh-mittal** [comment]
what could be the possible causes for this? 502 is received exactly at 120s (packet 11 in Wireshark capture).
I have experimented with various possible timeout settings but couldn't find a solution.

**Comment by erikdubbelboer** [comment]
@harsh-mittal without all the lua scripts loaded from your nginx file I obviously can't do anything. The nginx config file itself says nothing.

Maybe you can try building a Dockerfile using https://hub.docker.com/r/openresty/openresty that runs your specific nginx setup so I can try it?

**Comment by harsh-mittal** [comment]
I'll give it a try and get back.

**Comment by Fenny** [comment]
We didn't hear back from you @harsh-mittal, did you managed to make it work. If so, please let us know so we can close this issue.

**Comment by harsh-mittal** [comment]
It's no longer an issue. I'm closing the ticket now, thanks for helping out.
