### ISSUE TITLE
Multipart reader function

### ISSUE THREAD

**Issue by vishr** [valyala/fasthttp#74]
I have a need to read multipart stream, do we have a function equivalent to https://golang.org/pkg/net/http/#Request.MultipartReader?

**Comment by valyala** [comment]
@vishr , you can use the following functions:
- [RequestCtx.FormFile](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.FormFile) for accessing uploaded files.
- [RequestCtx.FormValue](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.FormValue) for accessing form values, which were posted with uploaded file.
- [RequestCtx.MultipartForm](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.MultipartForm) for accessing parsed multipart form data.

**Comment by valyala** [comment]
Closing the issue. Feel free re-opening it if the provided answer is unsatisfactory.

**Comment by vishr** [comment]
Correct me if I am wrong, this won't give me control until the file is fully uploaded I actually wanted to accomplish streaming file upload with simultaneous processing it specially for large files in gbs.

**Comment by valyala** [comment]
Yes, you are correct. Re-opening the issue. Need to think about proper API for file upload progress notifications...

**Comment by vishr** [comment]
Not sure, but if we can match https://golang.org/pkg/net/http/#Request.MultipartReader, it would be great.

**Comment by valyala** [comment]
@vishr, I cannot figure out how [multipart.Reader](https://golang.org/pkg/mime/multipart/#Reader) returned from [Request.MultipartReader](https://golang.org/pkg/net/http/#Request.MultipartReader) could be used for simultaneous processing of multi-GB uploaded file. The [Reader.NextPart](https://golang.org/pkg/mime/multipart/#Reader.NextPart) returns only after multi-GB file is uploaded to the server. So the file can be processed only after the upload is comple.

**Comment by vishr** [comment]
For reference your can see this example https://github.com/vishr/echo-recipes/blob/master/v1/streaming-file-upload, it does a streaming file upload byte by byte (I can double check).

**Comment by valyala** [comment]
Yeah, I see - `Reader.NextPart` reads only multipart header and then returns, so the multipart body could be read with [Part.Read](https://golang.org/pkg/mime/multipart/#Part.Read).

**Comment by vishr** [comment]
Cool.

**Comment by bermanf** [comment]
Hi! Is there currently a way to stream files from the request body in fasthttp, similar to how MultipartReader from the standard net/http package works?

I need to upload large files and save them to S3 in a streaming manner, using io.Pipe and MultipartReader. As far as I understand, fasthttp still doesn't support this functionality.

The default MultipartForm() writes large files to disk, which is problematic for me. Is there a way to avoid this?

**Comment by bermanf** [comment]
Hi! Is there currently a way to stream files from the request body in fasthttp, similar to how MultipartReader from the standard net/http package works?

I need to upload large files and save them to S3 in a streaming manner, using io.Pipe and MultipartReader. As far as I understand, fasthttp still doesn't support this functionality.

The default MultipartForm() writes large files to disk, which is problematic for me. Is there a way to avoid this?
