### ISSUE TITLE
Cookie support for multiple requests?

### ISSUE THREAD

**Issue by authrequest** [valyala/fasthttp#740]
I am looking for a way to save cookies after a POST request then when I need to make more requests for the same site those cookies follow. New to go so I did a lot of research and tired various methods and have not found anything yet.

**Comment by alessiosavi** [comment]
Probably the authors can have an efficient way:

You can retrieve the cookie with the following method, then you can reassign it to another request.

```go
func ParseTokenFromRequest(ctx *fasthttp.RequestCtx) string {
    token := string(ctx.Request.Header.Cookie("GoLog-Token")) // GoLog-Token is the hardcoded name of the cookie
    return token
}
```

Then you can create the cookie with the value already retrieved:

```go
//CreateCookie Method that return a cookie valorized as input (GoLog-Token as key)
func CreateCookie(key string, value string, expire int) *fasthttp.Cookie {
	if strings.Compare(key, "") == 0 {
		key = "GoLog-Token"
	}
	log.Debug("CreateCookie | Creating Cookie | Key: ", key, " | Val: ", value)
	authCookie := fasthttp.Cookie{}
	authCookie.SetKey(key)
	authCookie.SetValue(value)
	authCookie.SetMaxAge(expire)
	authCookie.SetHTTPOnly(true)
	authCookie.SetSameSite(fasthttp.CookieSameSiteLaxMode)
	return &authCookie
}
```

And then you can forward the cookie or save it into a (maybe in-memory)  db:

```go
authcookie := CreateCookie("GoLog-Token", token, cfg.Redis.Token.Expire)
ctx.Response.Header.SetCookie(authcookie)
// store cookie here
```

**Comment by erikdubbelboer** [comment]
Maybe this will help. This is an implementation of a sort of cookie jar for fasthttp: https://github.com/valyala/fasthttp/issues/446#issuecomment-433688795
If that doesn't help please let me know.

**Comment by authrequest** [comment]
> Maybe this will help. This is an implementation of a sort of cookie jar for fasthttp: [#446 (comment)](https://github.com/valyala/fasthttp/issues/446#issuecomment-433688795)
> If that doesn't help please let me know.

I tried this method but it doesn't seem to work for me or I am doing something wrong. How would I be able to send more requests with the same cookies from the first POST request?

**Comment by erikdubbelboer** [comment]
Do you want to send the same cookie with each request, or do you want follow up requests to have the same cookie set as the POST request responded with?

Can you maybe share your code?

**Comment by authrequest** [comment]
> Do you want to send the same cookie with each request, or do you want follow up requests to have the same cookie set as the POST request responded with?
> 
> Can you maybe share your code?

I would like to have the same cookies set in the POST request.

link to code: https://paste.ofcode.org/CrMvyNgM4drxCxXs4Jpysc

**Comment by erikdubbelboer** [comment]
I can't run your code, but try something like this: https://play.golang.org/p/sefn1EkwzLF
At like 68 it takes all the cookies returned by the response and stores them in the `cookies` slice. Then at like 25 `CookieClient` always adds all stored cookies to each request.

**Comment by authrequest** [comment]
> I can't run your code, but try something like this: https://play.golang.org/p/sefn1EkwzLF
> At like 68 it takes all the cookies returned by the response and stores them in the `cookies` slice. Then at like 25 `CookieClient` always adds all stored cookies to each request.

It works! :D finally!! Thank you so much! glad I chose to use fasthttp over net/http
