### ISSUE TITLE
ctx.QueryArgs().GetUfloat("ltd") returns -1

### ISSUE THREAD

**Issue by snmad** [valyala/fasthttp#743]
When sending negative float values to query args, fasthttp GetUfloat returns -1
http://localhost:8080/geocode?ltd=-26.7058442,&lng=26.707516

func (h *handler) Geocode(ctx *fasthttp.RequestCtx) {
ltd, err := ctx.QueryArgs().GetUfloat("ltd")
}

ctx.QueryArgs().GetUfloat("ltd") always returns -1 instead of -26.7058442

am I missing anything ?

**Comment by erikdubbelboer** [comment]
The `U` in `Ufloat` stands for unsigned (not negative). It returns `-1` on error, you might want to check `if err != nil` and then print the error.

As to why it only supports unsigned floats, I don't know either. It was commit in the `initial commit` by @valyala more than 4 years go, without any documentation as to why.

**Comment by erikdubbelboer** [comment]
To get a proper float value you could do:
```go
ltd, err := strconv.ParseFloat(string(ctx.QueryArgs().Peek("ltd")), 64)
```

**Comment by snmad** [comment]
thanks erikdubbelboer, I did the same thing. I just wanted to know if I was missing anything. Thanks for confirming.
