### ISSUE TITLE
catch error:  empty hex number

### ISSUE THREAD

**Issue by kingangelAOA** [valyala/fasthttp#746]
if err := HttpClient.DoTimeout(req, resp, 20*time.Second); err != nil {
		end = time.Since(start)
		result.ResponseTime = time.Now()
		result.err = err
		result.Elapsed = end.Seconds() * 1000
		result.status = false
		return result
	}

err: empty hex number

**Comment by erikdubbelboer** [comment]
Sounds like an invalid HTTP response (more specifically a broken chunked response header). Do you have the HTTP response or the URL you requested?

**Comment by kingangelAOA** [comment]
this is error: 
 HTTP/1.1 200 OK
Date: Tue, 25 Feb 2020 08:55:54 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 0
X-Oneapi-Cursor: 4e6dad2e-2592-483b-9920-f3f00e974a72
Connection: close

this is ok:  
HTTP/1.1 200 OK
Date: Tue, 25 Feb 2020 08:55:56 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 3108
X-Oneapi-Cursor: 925e671b-8c80-452a-bc06-2027f59b27ea

{"results": .................................}

**Comment by kingangelAOA** [comment]
I may know what the problem is, tcp connection was closed in advance
suggestion: Can the error message be detailed?
