### ISSUE TITLE
fasthttp is not handling URL hash correctly

### ISSUE THREAD

**Issue by chizhg** [valyala/fasthttp#748]
If a URL contains `#`, the HTTP GET request using `fasthttp` will return `404`, while `net/http` will return `200`.

Example:
```Go
package main

import (
	"fmt"
	"github.com/valyala/fasthttp"
	"net/http"
)

func main() {
	u := "https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#events"
	sc, _, _ := fasthttp.Get(nil, u)
	fmt.Println(sc)                     // prints 404

	resp, _ := http.Get(u)
	fmt.Println(resp.Status)       // prints 200
}
```

**Comment by erikdubbelboer** [comment]
Thanks for reporting this. I have just pushed a fix to master (https://github.com/valyala/fasthttp/commit/76b74e34c20dfaf25e491571044655e3fdf39c19).
