### ISSUE TITLE
CLOSE_WAIT tcp state

### ISSUE THREAD

**Issue by hardd2007** [valyala/fasthttp#757]
Good day. 
I use ServeFileUncompressed for transfer files to client side.
When the connection losts by client side, I see 
"error when serving connection "Z.251.X.Y:8038"<->"31.173.81.20:41624": write tcp4 Z.251.X.Y:8038->31.173.81.20:41624: write: connection timed out"
in stdout. After that I see CLOSE_WAIT tcp state on this port.
What can I do to resolve this?

**Comment by erikdubbelboer** [comment]
If you don't want the log entry you can either set [`Server.LogAllErrors`](https://godoc.org/github.com/valyala/fasthttp#Server.LogAllErrors) to `false` or implement your own [`Server.Logger`](https://godoc.org/github.com/valyala/fasthttp#Server.Logger).

`CLOSE_WAIT` is something in your OS TCP stack so if you want to change that you'll have to tune your OS parameters. For example reducing `net.ipv4.tcp_fin_timeout` in Linux.

**Comment by Fenny** [comment]
The author of this issue didn't respond for 5 months, I think we can close this. @erikdubbelboer
