### ISSUE TITLE
Specify Network Interface

### ISSUE THREAD

**Issue by tech-a-go-go** [valyala/fasthttp#759]
Hi there,

How can I specify the network interface (e.g. eth0, eth1) when sending a http request.

I couldn't find any clues in document.

Cheers

**Comment by erikdubbelboer** [comment]
I have just added [`LocalAddr`](https://godoc.org/github.com/valyala/fasthttp#TCPDialer.LocalAddr) to TCPDialer so you should be able to use this. You just have to overwrite [`Client.Dial`](https://godoc.org/github.com/valyala/fasthttp#Client.Dial) with a custom TCPDialer.Dial function.

**Comment by tech-a-go-go** [comment]
@erikdubbelboer 

Thank you !! 😃
