### ISSUE TITLE
Passing raw-header bytes to fasthttp.Request

### ISSUE THREAD

**Issue by harikb** [valyala/fasthttp#761]
I have the need to pass in header bytes (already formatted correctly) to a  `*fasthttp.Request` obtained from `fasthttp.AcquireRequest()`

I think it can be done if this particular internal method is exposed
`func (h *RequestHeader) parseHeaders(buf []byte) (int, error) {`

Otherwise I would be parsing the raw headers first, and then add each one via `req.Header.Add()`. 

I can work on this change (as a PR) if you think it is a good approach & ok to expose such a method.

**Comment by erikdubbelboer** [comment]
Is it not possible to use [`RequestHeader.Read`](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.Read)?

**Comment by harikb** [comment]
@erikdubbelboer , there is a such an option, but it seems to have the following problems
Note this is `client`, not incoming-http-server side. The `request` is the client-request to elsewhere I am about to make.

1. `req.Header.Read` get a header content like this (only these three lines)
```
Host: 127.0.0.1
Content-Type: application/txt
Content-Length: 2048
```
However, it does not read `Host` to be the target host. Instead it expects it to be explicitly set via `SetRequestURI()`. This is fine, although I do need to make the RequestUI to be complete URL `http://www.foo.bar/path/to/file.html` not just the request-uri (what goes in GET line) as one would expect. Anyways, this is a minor issue. May be I am reading the docs wrong.

2. `req.Header.Read` seems to "reset" a bunch of useful defaults in the outgoing request (critical/important things like connectionClose=false was set to connectionClose=true). I can sort of understand why this might be the case since the code is thinking it is parsing an incoming request from browser/outside and browser didn't indicate all those fancy options.
May be the trick is to add an explicit `GET <uri> HTTP/1.1` first-line that some of the code seems to expect?


I have a sample code like this

```
		req := fasthttp.AcquireRequest()
		defer fasthttp.ReleaseRequest(req)

		log.Printf("Headers\n>%s<\n", reqEnvelope.Headers()) 
                //  reqEnvelope.Headers() is a flatbuffers entity returning []byte
                //  exactly as shown above in previous quote
		req.Header.Read(bufio.NewReader(bytes.NewReader(reqEnvelope.Headers())))
		req.SetRequestURI(uriStr)

		req.SetBody(reqEnvelope.BodyBytes())
		resp := fasthttp.AcquireResponse()
		defer fasthttp.ReleaseResponse(resp)

		err = fasthttp.Do(req, resp)
		if err != nil {
			return errors.Wrap(err, "outgoing request failed")
		}
```

I would also like to know if there is a way to enable logging (similar to using `httputil.DumpRequest`) where I can see exactly what is sent to the connection. Of course my program itself is a http-recorder, so I could point to it and see. However it is would be something nice to have if possible with flatbuffers.

**Comment by harikb** [comment]
![Screen Shot 2020-03-18 at 2 14 42 PM](https://user-images.githubusercontent.com/952886/77009376-095cbb00-6925-11ea-8ce3-a308ebb3c6e4.png)

The above screenshot is from Goland after stepping through `req.Header.Read` line. Afaik, all blue items indicate a change

I should also mention that the code "works" in that it is able to make an outgoing http request, but resetting those connectionClose etc results in heavy performance degradation and other socket reuse/timeout issues.

**Comment by harikb** [comment]
My bad. that call does work correctly with the following sequence

I need to have the `first-line`. It makes sense otherwise I did not even specify what `method` to use for the request. The data was originally captured from an incoming fasthttp request's `ctx.Request.Header.RawHeaders()` (elsewhere in the system) . I assumed, incorrectly, that the same content is what header parser expects. But I can see it is missing the first line with Method, URI, HTTP/1.1 markers. 

Apparently `Host` header is ignored, but still works. Again, I should fix it since target host could barf on it. 

```
SetRequestURI with http://localhost:80/index.html

Headers.Read() with
==
POST /index.html HTTP/1.1
Host: bogus.com
Content-Type: application/txt
Content-Length: 2048
==
```

`SetRequestURI` is called after the `Header.Read()`, I wonder if the order matters.
