### ISSUE TITLE
fasthttp request nginx lose body

### ISSUE THREAD

**Issue by saltbo** [valyala/fasthttp#766]
Hello,

I found a scenes lose the request body that is fasthttp request the nginx based  on keepalive.

fasthttp keepalive time is 12 sec, nginx keepalive is 120 sec.

There is a test code, exec the cmd `nginx -s reload` when it run, you can find `{"message": "no body"}`.
```
// client test code
func TestFasthttpPost(t *testing.T) {
	for i := 0; i < 2; i++ {
		req := fasthttp.AcquireRequest()
		resp := fasthttp.AcquireResponse()
		defer fasthttp.ReleaseRequest(req)
		defer fasthttp.ReleaseResponse(resp)

		req.SetRequestURI("http://fe.test.svc.dc/api/activity/update")
		req.Header.SetMethod("POST")
		req.Header.Set("Accept", "application/json, text/plain, */*")
		req.Header.Set("Accept-Language", "zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7,zh-TW;q=0.6")
		req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36")
		req.Header.Set("Content-Type", "application/json; charset=UTF-8")

		body := bytes.NewBufferString(`{"address":"Beijing","city":"Beijing","end_time":"2021-03-12 00:00:00"}`)
		req.SetBodyStream(body, body.Len())
		err := fasthttp.DoTimeout(req, resp, time.Second*10)
		fmt.Println(err, string(resp.Body()))
		assert.Equal(t, http.StatusOK, resp.StatusCode())
		assert.Contains(t, string(resp.Body()), "ok")
		time.Sleep(time.Millisecond * 3000)
		fmt.Println("12333start next")
	}
}

// server code
r.POST("/api/activity/update", func(c *gin.Context) {
	fmt.Println(c.Request.ContentLength)
	time.Sleep(time.Second * 5)
	if c.GetHeader("Content-Length") == "0" {
		c.JSON(200, gin.H{
			"message": "no body",
		})
		return
	}
	c.JSON(200, gin.H{
		"message": "ok",
	})
})
```

After reading the source code of fasthttp, I found the body was lose because of a retry. The retry was triggered when the response of the first request was not received, then the bodyStream was already empty when the second attempt was made, so the request sent lost the body.

## Question 1
> fasthttp cannot sense the close of the long connection, is this issue known from issue #189 ?

Will this issue improve?

## Question 2
> `req.bodyStream` cannot be retried because it has become empty after the first time.

Don't use bodyStream or set MaxIdemponentCallAttempts to 1?  Is there any  better solution?

**Comment by erikdubbelboer** [comment]
1. I'm not sure I understand. You're saying the fastthttp client doesn't notice the connection closing? Even when setting [`Client.ReadTimeout`](https://godoc.org/github.com/valyala/fasthttp#Client.ReadTimeout) ?

2. You are right, fasthttp doesn't look at where the body came from before retrying the request. This means it doesn't see that bodyStream was already read.
One option would be to use [`SetBodyStreamWriter`](https://godoc.org/github.com/valyala/fasthttp#Request.SetBodyStreamWriter) and in that function pipe your reader to the write. But it all depends on where your body comes from. Is it even possible to restart your reader for example?

**Comment by saltbo** [comment]
Calling relationship：
> fasthttpClient -> nginx -> anyHttpServer.

Event sequence:
1. fasthttp send the request A to nginx.
2. nginx reload during the request A sending.
3. request A completed normally (because the nginx reload is gracefully).
4. fasthttp send the request B1 to nginx (nginx connection has closed, but fasthttp client doesn't notice).
5. error EOF happend when fasthttp read the response header.
6. enter the retry logic for the request B1.
7. fasthttp send the request B2 to nginx (no body be sent because the reader has be readed).


Now, let ’s discuss question 1: 
fastthttp client doesn't notice the connection closing before the request be sent?  
It doesn't seem to know that the connection was closed until reading the response header.

**Comment by saltbo** [comment]
The question 2 happend if the question1 can't be resolve.

I try to use the `SetBodyStreamWriter` and read the source code. But i can't understand your means.
```
func TestFasthttp(t *testing.T) {
	req := fasthttp.AcquireRequest()
	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseRequest(req)
	defer fasthttp.ReleaseResponse(resp)

	for i := 0; i < 2; i++ {
		req.SetRequestURI("http://mogao-fe.test.svc.dc/api/activity/update")
		req.Header.SetMethod("POST")
		body := bytes.NewBufferString(`{"type":"log","@timestamp":"2020-03-25T09:11:55Z","tags":["info","plugins","metrics"],"pid":7,"message":"Stopping plugin"}`)
		//req.SetBodyStream(body, body.Len())
		req.SetBodyStreamWriter(func(w *bufio.Writer) {
			//n, err := w.ReadFrom(body)
			n, err := w.Write(body.Bytes())
			fmt.Println(n, err)
		})
		err := fasthttp.Do(req, resp)
		fmt.Println(err, resp.String())
		time.Sleep(time.Second)
	}
}
```
It will still lose the body.

**Comment by erikdubbelboer** [comment]
I have just pushed a commit that should fix this issue: https://github.com/valyala/fasthttp/commit/0ba26f7b423406d937507f2fe9e23ea0de80d5d2

In theory we could implement logic that checks if the read is also a [`io.Seeker`](https://golang.org/pkg/io/#Seeker) so we can instead seek to 0 to retry the request. But that could get complicated so for now we'll just throw and error instead of retrying a request without a body.
