### ISSUE TITLE
Klauspost gzip vs pgzip

### ISSUE THREAD

**Issue by Fenny** [valyala/fasthttp#767]
I came across https://github.com/klauspost/pgzip and I'm wondering if this could speed up the compression in fasthttp compared to https://github.com/klauspost/gzip ?

**Comment by erikdubbelboer** [comment]
For big responses maybe. But for normal and small ones doing parallel compression will just hurt performance.
From the pgzip page:
```
To get any performance gains, you should at least be compressing more than 1 megabyte
of data at the time.
```
So it's only worth it if a response is multiple megabytes, and if your cores aren't busy with other things of course. Anyone who has this workload can probably implement a handler using pgzip themselves.
