### ISSUE TITLE
select proxy runtime for each request 

### ISSUE THREAD

**Issue by Hedgehogues** [valyala/fasthttp#768]
I want to use different proxies for each request to any host. But, I see [here](https://github.com/valyala/fasthttp/blob/master/client_example_test.go) that proxy set up the only time. There fore I cannot do next thing:

    	c := &fasthttp.HostClient{}
        c.Get(host: "localhost:8081", proxy: "localhost:8080")

This is a big problem for me. Can I solve this problem wit h fasthttp? May be I can do next thing:

	c := &fasthttp.HostClient{
		Addr: "localhost:8080",
	}
	statusCode, body, err := c.Get(nil, "http://google.com/foo/bar")
        c.Addr = "localhost:8085"

Is it correct to change proxy after initialization of Client?

**Comment by erikdubbelboer** [comment]
No, I'm afraid changing the Addr of HostClient won't work after it has been used already.

What you should do is create a different HostClient for each proxy you want to send a request to. Then based on the host in the url you can decide which HostClient to re-use.

**Comment by Hedgehogues** [comment]
Could you say how slowlier can work fasthttp, if I create new client for each request, than I have the only client?

**Comment by erikdubbelboer** [comment]
What do you mea with slowlier?

I'm thinking of something like this:
```go
// Somewhere globally:
var hostClients map[string]*fasthttp.HostClient



// Where you want to do the request:
req := fasthttp.AcquireRequest()
req.URI().Parse(nil, []byte("http://google.com/foo/bar"))

host := string(req.URI().Host())
hc := hostClients[host]
if hc == nil {
	hc = &fasthttp.HostClient{
		Addr: host,
	}
	hostClients[host] = hc
}

res := fasthttp.AcquireResponse()
err := hc.Do(req, res)

// ...
```
