### ISSUE TITLE
About multiple flushes

### ISSUE THREAD

**Issue by bhtbed** [valyala/fasthttp#78]
Is there a way to do progressive rendering via multiple flushes?

**Comment by bhtbed** [comment]
Or can *fasthttp.Response implement http.Flusher interface?

**Comment by kataras** [comment]
@bhtbed I don't think so, but if you want the Writer then check ```ctx.Response.BodyWriter()```

**Comment by bhtbed** [comment]
@kataras  So this feature will not be added to fasthttp?

**Comment by kataras** [comment]
fasthttp has it's own methodology to handle these things, it doesn't need manual flush, but I really can't answer you extracly, just wait for a better answer from @valyala  who mantains this package. Or just think how you could do that you want to do without Flush, take a closer look at the code I'm sure you will find the solution

**Comment by valyala** [comment]
> Is there a way to do progressive rendering via multiple flushes?

Yes - see [RequestCtx.SetBodyStreamWriter](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SetBodyStreamWriter). See [this example](https://godoc.org/github.com/valyala/fasthttp#ex-RequestCtx-SetBodyStreamWriter) for details.

**Comment by kataras** [comment]
Very good valyala, can you add [Iris](https://github.com/kataras/iris) to the readme.md and faq.md, we have only support for fasthttp :rose:

**Comment by valyala** [comment]
@kataras , done.

**Comment by kataras** [comment]
@valyala Thanks you, I appreciate this!, again nice job with fasthttp all things you doing are excelent :)
