### ISSUE TITLE
Memory consumption with gzip

### ISSUE THREAD

**Issue by ollevche** [valyala/fasthttp#782]
Hi!

I've added gzip compression to the project i'm working on and memory consumption increased a lot. Moreover, the server crashed. After some tests, i made a conclusion the thing is in gzip compression.

So i prepared some code to illustrate the problem:

```
package main

import (
	"fmt"
	"github.com/valyala/fasthttp"
	"sync"
	"time"
)

func doMulti(times int) {
	var wg = &sync.WaitGroup{}

	wg.Add(times)

	for i := 0; i < times; i++ {
		// hacky thing to avoid high load error
		// only for the test, there's no something like this in production code
		time.Sleep(time.Microsecond)

		go func(wg *sync.WaitGroup) {
			defer wg.Done()

			do()
		}(wg)
	}

	wg.Wait()
}

func doSingle(times int) {
	for i := 0; i < times; i++ {
		do()
	}
}

func do() {
	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	_, err := fasthttp.WriteGzipLevel(req.BodyWriter(), genArr(65536), fasthttp.CompressBestSpeed)
	if err != nil {
		panic(err)
	}
}

func main() {
	var times = 100_000

	doMulti(times)
	// doSingle(times)

	fmt.Print("Finished")

	// do not terminate
	for {
	}
}

func genArr(size int) (b []byte) {
	b = make([]byte, size)
	for i := range b {
		b[i] = 'a'
	}
	return
}
```

After printing 'Finished' the program still occupies up to 3 GB of RAM and it doesn't decrease at all. With `doSingle` test memory consumption much lower, but it still doesn't decrease. It's OK to reuse this memory, but is it expected behaviour in the first test?

Am i doing something wrong? How can i reduce memory usage in multithreading case? Or is it a bug?

**Comment by erikdubbelboer** [comment]
This probably has nothing to do with fastthttp. Go likes to keep allocated unused memory around in case it is needed again. So even if your OS tells you 3 GB has been allocated much less will probably actually be in use. You can partially see this by calling [`runtime/debug.FreeOSMemory()`](https://golang.org/pkg/runtime/debug/#FreeOSMemory) after `fmt.Print("Finished")`. You will see that the allocated memory your OS reports will be a lot lower. If you leave the process open for a long time you'll also see the allocated memory drop as Go gradually releases memory over time. On Linux it is even more nuanced as Go uses `MADV_FREE` to tell the OS the memory isn't needed anymore. The OS can then decide when to reclaim the memory. But it will only do this under pressure.

**Comment by ollevche** [comment]
I'm running Ubuntu 19.10 and test's memory consumption dropped heavily under pressure, but the main app with consumption ~18GB dropped to ~8GB and then got killed. Usually (without gzip) the app uses ~500MB and never ever raises higher than 1GB. The app's gzip code is exactly the same as in the test and the result of gzip isn't stored anywhere, except request body. So i'm wondering how to make the app more stable in terms of memory consumption? Do you have any advice?

**Comment by erikdubbelboer** [comment]
Are you able to profile your app to see where most memory is allocated? You need to get a heap profile, see https://golang.org/doc/diagnostics.html for example.

**Comment by ollevche** [comment]
As you said, heap profile shows lower memory usage (~3GB) than OS tells (~7GB). The most `inuse_space` is from compression code:

![image](https://user-images.githubusercontent.com/35274215/79637008-6944bc80-8184-11ea-87a7-f07230450c4b.png)

This profile got captured with `GODEBUG=madvdontneed=1` and RSS doesn't get higher than ~7GB. It decreases without load to ~300MB. With the default `MADV_FREE`, the app takes all of the memory available and eventually gets killed. The thing is RSS can shrink to ~300MB (as with `MADV_DONTNEED`), because there's no load at the time. RSS on kill is ~8GB, top ~18GB.

I think there's something wrong with runtime. Should i report it to Go repository or am i missing something?

**Comment by erikdubbelboer** [comment]
I'm assuming you're on linux? If so, what does the OOM killer say when it kills your process? (in `/var/log/kern.log` probably).

Also which version of Go are you using?

**Comment by ollevche** [comment]
I'm on Ubuntu 19.10 with Go 1.14. In `/var/log/kern.log` i found:
```
Out of memory: Killed process <app_pid> (<app_name>) total-vm:19902940kB, anon-rss:12777444kB, file-rss:0kB, shmem-rss:0kB
oom_reaper: reaped process <app_pid> (<app_name>), now anon-rss:76kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by erikdubbelboer** [comment]
How many concurrent requests are you responding to? And how big is your response? The gzip writer is re-used using sync.Pool so it shouldn't be allocating that much under normal use.

Can you try upgrading to the latest version of fasthttp (`v1.12.0`). I updated the compression library which performs slightly better for me now.

**Comment by ollevche** [comment]
Test load (as for heap profile, OOM test) is around 40k rps with json bodies under 1K chars (500-700 usually).

I'll try `v1.12.0` and write you back, thanks!

**Comment by ollevche** [comment]
So here are heap profiles for `v1.12.0`.

RSS raised to ~14GB and gets higher:

![image](https://user-images.githubusercontent.com/35274215/79843030-5b7c7a80-83c2-11ea-8ee1-3b4a38a02064.png)

With `GODEBUG=madvdontneed=1`, RSS behavior and heap profile are almost the same:

![image](https://user-images.githubusercontent.com/35274215/79843602-2290d580-83c3-11ea-9e6c-13249da53399.png)

On `v1.8.0` with `GODEBUG=madvdontneed=1` i'm getting stable 7GB RSS:

![image](https://user-images.githubusercontent.com/35274215/79844713-b1522200-83c4-11ea-99ba-ef9270d73a78.png)

**Comment by erikdubbelboer** [comment]
I'm not sure how to continue with this. Maybe you could try doing your own gzip compression instead of using fasthttp for that. Fasthttp use stackless which I'm not sure if it works properly here.

In your example that would be:
```go
import (
  "github.com/klauspost/compress/gzip"
)

var gzipReaderPool sync.Pool

func do() {
  req := fasthttp.AcquireRequest()
  defer fasthttp.ReleaseRequest(req)

  a := genArr(65536)

  // get a write from the pool, or create a new one.
  var zw *gzip.Writer
  v := gzipReaderPool.Get()
  if v == nil {
    zw, _ = gzip.NewWriterLevel(req.BodyWriter(), gzip.BestCompression)
  } else {
    zw = v.(*gzip.Writer)
    zw.Reset(req.BodyWriter())
  }

  // use the writer.
  zw.Write(a)

  // release the writer to the pool
  zw.Close()
  gzipReaderPool.Put(zw)
}
```

**Comment by ollevche** [comment]
Seems like `stackless` should save us some space, so why it has the reverse effect at all? Is it uncommon usage of compression? Or maybe we should consider an architecture review (for our app) based on the problem? I mean, 40K rps doesn't sound like a super huge load?

**Comment by erikdubbelboer** [comment]
stackless is useful if you only have to compress a body once in a while. It saves memory by having a small pool of goroutines that are being used to do the stack heavy processing. But when almost all of your request need to compress then it just becomes an overhead. You'll end up with as many big stack goroutines as normal worker goroutines. So in this case your normal worker gorountines might as well be the ones with the big stack space. That way you don't have any of the overhead of stackless (extra goroutines, extra pools, goroutine synchronization).

40k rps can be quite a lot depending on how much processing you do for each request.

**Comment by ollevche** [comment]
Okay, got you. Thanks a lot, i have learned something new.

Here is final compression code, which has lower memory consumption (maybe, someone finds it useful):

```
func WriteGzipLevel(w io.Writer, b []byte, lvl int) (err error) {
  zw, err := acquireGzipWriter(w, lvl)
  if err != nil {
    return
  }
  defer releaseGzipWriter(zw)

  if _, err = zw.Write(b); err != nil {
    return
  }

  return
}

var gzipWriterPool sync.Pool

func acquireGzipWriter(w io.Writer, lvl int) (zw *gzip.Writer, err error) {
  v := gzipWriterPool.Get()
  if v == nil {
    return gzip.NewWriterLevel(w, lvl)
  }

  zw = v.(*gzip.Writer)
  zw.Reset(w)
  return
}

func releaseGzipWriter(zw *gzip.Writer) {
  zw.Close()
  gzipWriterPool.Put(zw)
}
```

**Comment by erikdubbelboer** [comment]
@ollevche the custom compression code fixed your issue? It brought back memory usage far enough to not be an issue anymore?

**Comment by ollevche** [comment]
@erikdubbelboer yes, RSS is under 1GB now with the same load. 

I'm wondering, why OS kills runtime, even if its heap profile is really low, but at the same time RSS is super high (actually all the available memory). Why can't runtime just free its unused memory? Or does it take too long?

I don't have enough low-level knowledge about Go runtime, but i found [this article](https://blog.detectify.com/2019/09/05/how-we-tracked-down-a-memory-leak-in-one-of-our-go-microservices/) and these issues ([32124](https://github.com/golang/go/issues/32124), [29844](https://github.com/golang/go/issues/29844)), which are very similar to our problem. Surely it's not because of fasthttp, just an interesting question i have no answer to.

**Comment by erikdubbelboer** [comment]
Great. I'm afraid I don't have enough knowledge about OOM conditions either.
