### ISSUE TITLE
Expect 100 Continue example/support?

### ISSUE THREAD

**Issue by mmacdermaid** [valyala/fasthttp#783]
Does fasthttp actually support expect 100 continue workflow, or does it just automatically return the continue response and read the incoming body?

Not sure if this is the right section.
https://github.com/valyala/fasthttp/blob/master/server.go#L2036-L2067

There's a chance to further optimize my use case by reading the headers inside of my handler, and it would be nice to not process the bodies coming my direction.

If it does support the handling of the 100 continues, it would be great to see an example.

**Comment by erikdubbelboer** [comment]
fasthttp automatically handles Expect 100-continue and reads the incoming body. It currently doesn't have a callback or something that you could use to reject the body. This shouldn't be too hard to implement in the lines you linked. A pull request is always welcome 😄

**Comment by mmacdermaid** [comment]
@erikdubbelboer :+1: I will see if I can come up with something if I get a second.  I appreciate the response.
