### ISSUE TITLE
Questions about the SipBody's judgment.

### ISSUE THREAD

**Issue by wangfakang** [valyala/fasthttp#785]
The following [code](https://github.com/valyala/fasthttp/blob/master/client.go#L1353) snippet is used by fasthttp to check whether `skipBody` is required for the  request. 

```
func (c *HostClient) doNonNilReqResp(req *Request, resp *Response) (bool, error) {
……
	if customSkipBody || !req.Header.IsGet() && req.Header.IsHead() {
		resp.SkipBody = true
	}
……
}
```

My question is why not use the following methods ? thx.

```
func (c *HostClient) doNonNilReqResp(req *Request, resp *Response) (bool, error) {
……
	if customSkipBody || req.Header.IsHead() {
		resp.SkipBody = true
	}
……
}
```

**Comment by erikdubbelboer** [comment]
You're correct. The header can't be both a HEAD and GET so checking both doesn't make any sense. This code was introduced [more than 4 years ago](https://github.com/valyala/fasthttp/commit/c5d9023043414b9b900436801bf5f14537f2248b#diff-d0b7f86cea13f90d3cc0cc2338da8d5fR850) and it seems nobody noticed it until now. I'll fix it in a commit. Thanks for reporting this!
