### ISSUE TITLE
Support for setting and reading basic auth headers

### ISSUE THREAD

**Issue by mark-rushakoff** [valyala/fasthttp#79]
I'm already using fasthttp, and I have an upcoming requirement to support basic auth. The implementation is fairly simple, so I can manually set and parse request headers if I have to, but it would be more convenient if basic auth was part of the RequestHeader API.

**Comment by kataras** [comment]
I have a different opinion, if that's ok, I think it's better to keep libraries like fasthttp as simple as possible, just do their job as best as they can, each lib has its own job...
