### ISSUE TITLE
fasthttp client not closing the connection on reception of FIN from server

### ISSUE THREAD

**Issue by subhashmohan88** [valyala/fasthttp#791]
I've been using fasthttp client for load-balancing the messages to different servers. 
I'm using client DoTimeout for sending the request and the maximum MaxIdleConnDuration is set to 60 seconds. 
The idle timeout on server is 10 seconds. 
Even though server closes the connection after 10 seconds, fasthttp still uses the same connection to send any new request destined to that server, due to this server sends RST. 

Ideally fasthttp client must close the connection when the server closes it and not use the connection ?

**Comment by erikdubbelboer** [comment]
I'm afraid the only way the client can find out that the connection is closed is by trying to send something on it. The is no function to check if a connection is closed.

It is always advised to set the client max idle time lower than the server max idle time. It's always better if the client closes the connection (exactly why servers send back `Connection: close` headers to tell the client to close the connection).
