### ISSUE TITLE
FS: redirect directories to have a trailing slash

### ISSUE THREAD

**Issue by moqmar** [valyala/fasthttp#792]
Currently, I can access a file `/test/index.html` either through `/test/` or through `/test`. In the latter case, relative paths in the document will refer to completely different files, which makes this unappropriate in my opinion - `/test` should yield a 301 redirect to `/test/`. This will be a breaking change if someone uses something like `ctx.Request.SetRequestURI(path.Clean(p))` before calling the FSHandler though, so I guess making it an option would make sense?.

**Comment by erikdubbelboer** [comment]
I agree it should redirect like other web servers do. Can you make a pull request to add this 301 redirect. Just do it without the option. I plan on releasing another [breaking change](https://github.com/valyala/fasthttp/pull/800) soon as well. So we might as well release these changes together as fasthttp 2.0.0 (semver breaking change major version increment).

**Comment by moqmar** [comment]
Sure. Another thing I'd really find useful together with this would be automatically cleaning up the path - this would force a redirect from e.g. http://localhost:8080/hello/../world//aha/./blubb to http://localhost:8080/world/aha/blubb. This would fix a similar problem: different paths can refer to the same file.

Would that be something you'd like to see in the FS code as well? Or should this be an option for the server itself? Or do you think that this should be done manually by the developer?

**Comment by erikdubbelboer** [comment]
Yes that would be a nice option to have as well to enable redirects to cleaner paths.

**Comment by moqmar** [comment]
Alright, seems like the second part is obsolete, as https://tools.ietf.org/html/rfc3986#section-6 specifies that browsers may clean up paths themselves, and it seems like Firefox, curl, wget, httpie and Insomnia already do that. As servers shouldn't use PathOriginal anyways when serving files, it's also not possible to run a `GET /../../../../etc/passwd HTTP/1.1` with Telnet, at least with the FS module.

So, I'll just fix the trailing directory slash.
