### ISSUE TITLE
fasthttp as client sometimes [write: broken pipe] while other clients not

### ISSUE THREAD

**Issue by yijia2413** [valyala/fasthttp#794]
## background
server:  Django 3, receive json data from fasthttp, sometime it reports [write broken pipe]
the post body size is about `254457` bytes each time. (the body is too big ?)

Django server do not report any problems, as sometimes it might be `broken pipe the server connection closed unexpectedly`, but it's not

I tried with `python requests`, `http curl`, `golang net/http`,  and they all return success

## fasthttp code

```golang
func Send1(url string, body *[]byte) ([]byte, error) {

	req := fasthttp.AcquireRequest()
	rsp := fasthttp.AcquireResponse()

	defer func() {
		fasthttp.ReleaseResponse(rsp)
		fasthttp.ReleaseRequest(req)
	}()

	req.Header.SetContentType("application/json")
	req.Header.SetMethod("POST")

	req.SetRequestURI(url)
	// testBody := []byte(`{"request":"test"}`)
	req.SetBody(*body)

	if err := fasthttp.Do(req, rsp); err != nil {
		log.Error("push data remote failed, ", err, ", bytes:", len(*body))
		return []byte{}, err
	}

	return rsp.Body(), nil
}

```

## net/http code
```golang
func Send(url string, body *[]byte) error {
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(*body))
	if err != nil {
		log.Error("NewRequest Error, ", err)
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Error(err)
		return err
	}
	defer resp.Body.Close()

	// if body, err := ioutil.ReadAll(resp.Body); err == nil {
	// 	log.Info(string(body))
	// }
	return nil
}
```

**Comment by erikdubbelboer** [comment]
How often is "sometimes"? And how many requests are you sending?

Is this a public URL I could test myself? Just this code tells me nothing.

If you call `fasthttp.ReleaseResponse(rsp)` everything in `rsp` becomes invalid as it can be reused for other requests. So returning `rsp.Body()` will return a byte slice that might be modified by another request at any moment. If you want to return the body like that you will have to copy it into another byte slice first.

**Comment by Fenny** [comment]
We didn't hear from you @yijia2413, did you managed to solve the issue?

**Comment by yijia2413** [comment]
to finish the project as soon as possible, I use `net/http` instead.

I'm not very familiar with `fasthttp`,  I need more time to read the [doc](https://godoc.org/github.com/valyala/fasthttp), it might be a usage error..

If I meet some problems in the future, I will file a new issue, thanks.

**Comment by liufeihe** [comment]
> 



> to finish the project as soon as possible, I use `net/http` instead.
> 
> I'm not very familiar with `fasthttp`, I need more time to read the [doc](https://godoc.org/github.com/valyala/fasthttp), it might be a usage error..
> 
> If I meet some problems in the future, I will file a new issue, thanks.

My version is 1.39.0，I have met the same error, like below:
"write tcp 10.11.137.96:58540-\u003e43.156.86.47:443: write: broken pipe"

My code is like below:

var (
	HttpClientLock sync.Mutex
	MyHttpClient   *fasthttp.Client
)

func SendPost(v map[string]interface{}, txConfig SDKConfig) ([]byte, error) {
	HttpClientLock.Lock()
	if MyHttpClient == nil {
		MyHttpClient = &fasthttp.Client{
			MaxIdleConnDuration:       300 * time.Second,
			MaxConnsPerHost:           2000,
			MaxIdemponentCallAttempts: 5,
			ReadTimeout:               300 * time.Millisecond,
			DialDualStack:             true,
		}
	}
	HttpClientLock.Unlock()
	request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()
	defer func() {
		fasthttp.ReleaseRequest(request)
		fasthttp.ReleaseResponse(response)
	}()

	myData := MakeQueryString(v, true)
	logx.Infow("request info", logx.Field("url", txConfig.URL), logx.Field("myData", myData))

	request.Header.SetMethod(txConfig.HttpMethod)
	request.SetRequestURI(fmt.Sprintf("https://%v", txConfig.URL))
	request.SetBody([]byte(myData))
	request.Header.SetContentType("application/x-www-form-urlencoded")
	request.Header.SetUserAgent("Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;SV1)")
	if err := MyHttpClient.DoTimeout(request, response, 3000*time.Millisecond); err != nil {
		logx.Errorw("SendPost failed", logx.Field("error", err.Error()))
		return nil, err
	}
	respondBody := make([]byte, len(response.Body()))
	copy(respondBody, response.Body())
	logx.Infow("res info", logx.Field("statusCode", response.StatusCode()), logx.Field("resData", string(respondBody)))
	return respondBody, nil
}

**Comment by liufeihe** [comment]
> How often is "sometimes"? And how many requests are you sending?
> 
> Is this a public URL I could test myself? Just this code tells me nothing.
> 
> If you call `fasthttp.ReleaseResponse(rsp)` everything in `rsp` becomes invalid as it can be reused for other requests. So returning `rsp.Body()` will return a byte slice that might be modified by another request at any moment. If you want to return the body like that you will have to copy it into another byte slice first.

My version is 1.39.0，I have met the same error, like these:
"write tcp 10.11.137.96:58540-\u003e43.156.86.47:443: write: broken pipe"

My code is :

var (
	HttpClientLock sync.Mutex
	MyHttpClient   *fasthttp.Client
)

func SendPost(v map[string]interface{}, txConfig SDKConfig) ([]byte, error) {
	HttpClientLock.Lock()
	if MyHttpClient == nil {
		MyHttpClient = &fasthttp.Client{
			MaxIdleConnDuration:       300 * time.Second,
			MaxConnsPerHost:           2000,
			MaxIdemponentCallAttempts: 5,
			ReadTimeout:               300 * time.Millisecond,
			DialDualStack:             true,
		}
	}
	HttpClientLock.Unlock()
	request := fasthttp.AcquireRequest()
	response := fasthttp.AcquireResponse()
	defer func() {
		fasthttp.ReleaseRequest(request)
		fasthttp.ReleaseResponse(response)
	}()

	myData := MakeQueryString(v, true)
	logx.Infow("request info", logx.Field("url", txConfig.URL), logx.Field("myData", myData))

	request.Header.SetMethod(txConfig.HttpMethod)
	request.SetRequestURI(fmt.Sprintf("https://%v", txConfig.URL))
	request.SetBody([]byte(myData))
	request.Header.SetContentType("application/x-www-form-urlencoded")
	request.Header.SetUserAgent("Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;SV1)")
	if err := MyHttpClient.DoTimeout(request, response, 3000*time.Millisecond); err != nil {
		logx.Errorw("SendPost failed", logx.Field("error", err.Error()))
		return nil, err
	}
	respondBody := make([]byte, len(response.Body()))
	copy(respondBody, response.Body())
	logx.Infow("res info", logx.Field("statusCode", response.StatusCode()), logx.Field("resData", string(respondBody)))
	return respondBody, nil
}

**Comment by liufeihe** [comment]
> 

I just copy the error here, not the whole log

**Comment by liufeihe** [comment]
> ```go
> SendPost failed
> ```

{"C":"logic/describe_risk_assessment.go:137","L":"error","M":"SendPost failed","T":"2022-10-11T05:22:31.469Z","ext":{"error":"write tcp 10.11.238.79:34834-\u003e43.156.222.139:443: write: broken pipe"}}

**Comment by erikdubbelboer** [comment]
It probably means the server closed the connection. Or you're having some other socket problems on your machine. Maybe look at the syslog.

**Comment by liufeihe** [comment]
> My client ReadTimeout is 300Millisecond, but my DoTimeout is 3seconds, shall i set these two timeout the same ?

My client ReadTimeout is 300Millisecond, but my DoTimeout is 3seconds, shall i set these two timeout the same ?

**Comment by erikdubbelboer** [comment]
You shouldn't use DoTimeout at all. Just use Do. And set a WriteTimeout as well. And set both timeouts to 3 seconds if that is what you want to allow.
