### ISSUE TITLE
Is there a conversion of Request.ParseMultipartForm?

### ISSUE THREAD

**Issue by kataras** [valyala/fasthttp#80]
net/http Request has this to limit the upload bytes, does the fasthttp has something like that and if yes can you tell me which one is? I am searching and I can't find it :/
```go
// net/http
Request.ParseMultipartForm(32 << 20) //32MB
// fasthttp ?
```

**Comment by valyala** [comment]
> net/http Request has this to limit the upload bytes, does the fasthttp has something like that and if yes can you tell me which one is?

See [Server.MaxRequestBodySize](https://godoc.org/github.com/valyala/fasthttp#Server).

**Comment by kataras** [comment]
That's it, thanks you!
