### ISSUE TITLE
Accessing ctx.Request.PostBody() hangs the server on chunked POST

### ISSUE THREAD

**Issue by mvanderkroon** [valyala/fasthttp#801]
I am trying to push (potentially) very large files to a `fasthttp` backend. For this purpose I am relying on [chunked transfers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) which is being sent by the Python `requests` library.

The server handler code works fine for non-chunked transfers (as well as MultiPartForm). But when I try and upload data using the chunked transfer method, the code simply 'hangs' - for lack of a better understanding of what is going on. Curiously, when calling `ctx := PostBody()` and not assigning the result to a variable, the code continues fine (obviously without me being able to access said data). Even more curiously, if I call `ctx.Request.String()` and print the result of this to sdtout, it neatly prints all my data!

Between my limitations with the Go language, as well as being a bit numb from looking at this issue I'm not sure there is a _bug_ per se, but a little help would be greatly appreciated!

For reference, this is my (Python) client code:
```
resp = requests.post(
    URL,
    headers={
        "Transfer-encoding": "chunked",
        "Cache-Control": "no-cache",
        "Connection": "Keep-Alive",
    },
    data=yield_data("myfile.dat"),
)
```

The server handler code is very minimal and looks as follows:
```
func (s *HTTPTransport) Post(ctx *fasthttp.RequestCtx) {
	buf := ctx.PostBody()
        fmt.Println(buf)
        // this call hangs the server

        ctx.PostBody()
        // this allows the server to continue running, but I can't access my data

       fmt.Println(ctx.Request.String())
       // this call neatly prints the contents of my (JSON) data to console
}
```

UPDATE: it's becoming more clear to me I must be making a mistake somewhere in my reasoning. I have now managed to access the data in the Body by casting the byte buffer to a string:

```
func (s *HTTPTransport) Post(ctx *fasthttp.RequestCtx) {
	d := ctx.Request.Body()
	fmt.Println(string(d)) // data can be accessed just fine
}
```

Perhaps what remains is the demystification of why I can't seem to display the byte buf directly to my console, but I can once I have converted it to a string...?

**Comment by erikdubbelboer** [comment]
My initial guess is that this has nothing to do with fasthttp. I guess trying to print really large byte buffers with `fmt.Println` is just really slow. How big is your file?

Try this code:
```go
package main

import (
  "fmt"
  "math/rand"
)

func main() {
  b := make([]byte, 1024*1024*10) // 10MB, set this to the size of your file.
  rand.Read(b)
  fmt.Println(b)
}
```

**Comment by mvanderkroon** [comment]
That seems very plausible, I tried your snippet set to 10MB which worked fine. I then used my filesize (147KB) and that worked fine too, so it doesn't seem to be the issue here - but I agree this is something probably unrelated to `fasthttp`.

Further prodding also shows that I am able to index and traverse (albeit extremely slowly) the returned buffer array:
```golang
buf := ctx.PostBody()
fmt.Println(buf[0]) // this is fine
fmt.Println(len(buf)) // this is fine
fmt.Println(buf[len(buf) - 1]) // this is also fine

for int i := 0; i < len(buf); i++ {
   fmt.Println(buf[i]) // prints fine, but it takes ages (for a 147KB file); on the order of minutes
}
```

**Comment by erikdubbelboer** [comment]
My guess now is that you terminal is somehow rate limiting its output.

At the point the fasthttp handler is executed the whole body is already in memory. `ctx.PostBody()` just returns a pointer to this memory. So all you are doing in all those examples is just reading memory without anything else.
Once you start printing a certain amount of data to your terminal it seems to slow down for you.

I'm going to close this as it seems unrelated to fasthttp.
