### ISSUE TITLE
Question: Do we need to decode query string explicitly with ctx.QueryArgs().QueryString()

### ISSUE THREAD

**Issue by subbu05** [valyala/fasthttp#803]
`ctx.QueryArgs().QueryString()` return encoded byte array of the query string.

`curl "http://127.0.0.1/?a%3Da1%26b%3Db2"`
 a%3Da1%26b%3Db2

**Comment by erikdubbelboer** [comment]
You can use `v := ctx.QueryArgs().Peek("name")` to get the value of a specific arg. `ctx.QueryArgs().QueryString()` just returns the encoded version of the arguments.

I'm not sure why your URL is so weird. If you would use `http://127.0.0.1/?a=a1&b=b2` then `ctx.QueryArgs().QueryString()` would return `a=a1&b=b2` and `ctx.QueryArgs().Peek("a")` would return `a1`.
