### ISSUE TITLE
SSL Pinning/Fingerprinting?

### ISSUE THREAD

**Issue by adeptedcase** [valyala/fasthttp#806]
Is it possible to do SSL pinning with the fasthttp client?

If so, how?

**Comment by erikdubbelboer** [comment]
It should be east to change this code to use fasthttp: https://medium.com/@zmanian/server-public-key-pinning-in-go-7a57bbe39438
See: https://godoc.org/github.com/valyala/fasthttp#Client.Dial
Would that work for you?

**Comment by adeptedcase** [comment]
Hi, I tried this and it gives me this tls error

```
Do err tls: first record does not look like a TLS handshake
```

Here's the code i'm running

```golang
package main

import (
	"crypto/tls"
	"fmt"
	"net"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	dialer := func(addr string) (net.Conn, error) {
		c, err := tls.Dial("tcp", addr, &tls.Config{InsecureSkipVerify: false})
		if err != nil {
			fmt.Println("dialer err", err)
			return c, err
		}
		return c, nil
	}

	c := &fasthttp.Client{
		Dial:           dialer,
	}

	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	req.SetRequestURI("https://google.com")
	req.Header.SetMethod("GET")

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)
	err := c.DoTimeout(req, resp, 15*time.Second)

	fmt.Println("Do err", err)
}
```

**Comment by erikdubbelboer** [comment]
I just pushed a fix for this to master: https://github.com/valyala/fasthttp/commit/9507d7c7d70d8da6c3559bd31360f491bf0c254b

The problem was that fasthttp assumed Dial to always return a plain Conn and would try to wrap it with TLS itself as well. Which obviously doesn't work with double TLS.

**Comment by adeptedcase** [comment]
Awesome, this works great. Thank you for resolving it so fast

**Comment by adeptedcase** [comment]
@erikdubbelboer one more question on this if you don't mind.

Can I use this when going through a HTTP proxy?
https://github.com/valyala/fasthttp/blob/master/fasthttpproxy/http.go

**Comment by erikdubbelboer** [comment]
Yes, but you'll have to copy the code and change this line to use your new dialer:
https://github.com/valyala/fasthttp/blob/9507d7c7d70d8da6c3559bd31360f491bf0c254b/fasthttpproxy/http.go#L29

**Comment by adeptedcase** [comment]
It looks like that would verify the connection to the proxy server and not the server that I'm trying to connect to through the proxy?

**Comment by erikdubbelboer** [comment]
But the connection to the server that you're trying to connect to through the proxy is being made by the proxy if you're using a HTTP proxy. You'll need a SOCKS5 proxy and then modify https://github.com/valyala/fasthttp/blob/master/fasthttpproxy/socks5.go. You'll need to use [`tls.Client`](https://golang.org/pkg/crypto/tls/#Client) (intead of `tls.Dial`) to convert the returned `net.Conn` into a TLS conn.

**Comment by adeptedcase** [comment]
Hmm with net/http I'm able to do it with HTTP proxies.

```go
		transport := http.Transport{
			Proxy:              http.ProxyURL(proxyURL),
			ProxyConnectHeader: hdr,
			TLSClientConfig: &tls.Config{
				VerifyPeerCertificate: func(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error {
					var fingerprints [][32]byte
					for _, rawCert := range rawCerts {
						cert, _ := x509.ParseCertificate(rawCert)
						fmt.Println(cert.Subject)
						fingerprints = append(fingerprints, sha256.Sum256(rawCert))
					}
					for _, fingerprint1 := range fingerprints {
						fmt.Println(fingerprint1)

						if bytes.Compare(fingerprint, fingerprint1[0:]) == 0 {
							return nil
						}
					}
					return errors.New("certificate signature does not match")
				},
			},
		}
		client = http.Client{
			Transport: &transport,
		}
```

https://golang.org/pkg/crypto/tls/#example_Config_verifyPeerCertificate

Is VerifyPeerCertificate something that could be made to work with fasthttp?

**Comment by erikdubbelboer** [comment]
I think you're right, this should work (I don't have a proxy to test it):
```go
package fasthttpproxy

import (
	"crypto/tls"
	"fmt"
	"net"
	"time"

	"github.com/valyala/fasthttp"
	"github.com/valyala/fasthttp/fasthttpproxy"
)

func main() {
	proxy := fasthttpproxy.FasthttpHTTPDialer("https://yourproxyhere.com")

	dialer := func(addr string) (net.Conn, error) {
		c, err := proxy(addr)
		if err != nil {
			return nil, err
		}
		return tls.Client(c, &tls.Config{InsecureSkipVerify: false}), nil
	}

	c := &fasthttp.Client{
		Dial: dialer,
	}

	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	req.SetRequestURI("https://google.com")
	req.Header.SetMethod("GET")

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)
	err := c.DoTimeout(req, resp, 15*time.Second)

	fmt.Println("Do err", err)
}
```
If it does you can change the `VerifyPeerCertificate` method in the `tls.Config` as well like your example above.

**Comment by adeptedcase** [comment]
this gives me 
```
Do err tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

If theres a way to private message you i can give a proxy?

**Comment by erikdubbelboer** [comment]
You can email me on erik@dubbelboer.com

**Comment by adeptedcase** [comment]
Emailed. Thank you

**Comment by erikdubbelboer** [comment]
The following code works. Like the error said, you have to set `ServerName` like `tls.Dial` does as well: https://github.com/golang/go/blob/2b70ffe9307c0992e28513ba25081d767b5937b2/src/crypto/tls/tls.go#L148-L164

```go
package main

import (
	"crypto/tls"
	"fmt"
	"net"
	"strings"
	"time"

	"github.com/valyala/fasthttp"
	"github.com/valyala/fasthttp/fasthttpproxy"
)

func main() {
	proxy := fasthttpproxy.FasthttpHTTPDialer("username:password@proxy:port")

	dialer := func(addr string) (net.Conn, error) {
		c, err := proxy(addr)
		if err != nil {
			return nil, err
		}

		config := &tls.Config{
			InsecureSkipVerify: false,
		}

		colonPos := strings.LastIndex(addr, ":")
		if colonPos == -1 {
			colonPos = len(addr)
		}

		config.ServerName = addr[:colonPos]

		return tls.Client(c, config), nil
	}

	c := &fasthttp.Client{
		Dial: dialer,
	}

	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)

	req.SetRequestURI("https://google.com")
	req.Header.SetMethod("GET")

	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)
	err := c.DoTimeout(req, resp, 15*time.Second)

	fmt.Println("Do err", err)
	fmt.Println(string(resp.Body()))
}
```

**Comment by adeptedcase** [comment]
Perfect, that's got it. Thanks

**Comment by adeptedcase** [comment]
One thing I've found, the following part of code causes retries when VerifyPeerCertificate fails.
https://github.com/valyala/fasthttp/blob/master/client.go#L1204

Also it appears to hold the `CONNECT` open with the proxy server which I'm trying to figure out

**Comment by erikdubbelboer** [comment]
As long as requests are non-idempotent it should retry them on failure, that's normal. You can disable that by setting [`MaxIdemponentCallAttempts`](https://godoc.org/github.com/valyala/fasthttp#Client.MaxIdemponentCallAttempts) to `1`.

It will keep connections alive by default. You can disable this by setting a really low [`Client.MaxIdleConnDuration`](https://godoc.org/github.com/valyala/fasthttp#Client.MaxIdleConnDuration) or sending a `Connection: Close` header.

**Comment by adeptedcase** [comment]
Thanks
