### ISSUE TITLE
Is it possible to forward the client's response body to ctx response body?

### ISSUE THREAD

**Issue by dyrkin** [valyala/fasthttp#807]
Good day, guys,

Is it possible to forward the client's response body to ctx response body without reading it into memory?

I do HTTP requests from my go code when receiving external requests in RequestHandler.
```golang
var client *fasthttp.Client

func Handle(ctx *fasthttp.RequestCtx) {
	req := fasthttp.AcquireRequest()
	rsp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseRequest(req)
	defer fasthttp.ReleaseResponse(rsp)
	if err := client.Do(req, rsp); err !=nil {
		ctx.Response.SetStatusCode(fasthttp.StatusNotFound)
	}
	var body []byte
	body = append(body, rsp.Body()...) //need to copy it into a memory before exit the Handle function
	ctx.SetBody(body)
}
```

I would like to pass somehow `rsp.Body()` directly `ctx.Response`.
Thanks.

**Comment by erikdubbelboer** [comment]
I'm afraid not at the moment. fasthttp.Client will always read the whole body into memory. @kirillDanshin is working on changing this at https://github.com/valyala/fasthttp/issues/622
