### ISSUE TITLE
Is there a dependency free, trimmed version just for http client?

### ISSUE THREAD

**Issue by gonyyi** [valyala/fasthttp#808]
This is not an issue, but question..

I work on a project where pulling outside dependencies aren't that easy due to all security measures.... Just wondering

**Comment by kirillDanshin** [comment]
nope

**Comment by erikdubbelboer** [comment]
I'm afraid not. If pulling outside dependencies isn't easy I would recommend just using net/http first.

The dependencies of fasthttp are very little and very stable: https://github.com/valyala/fasthttp/blob/master/go.mod

**Comment by phuslu** [comment]
two thoughts here,

for github.com/valyala/bytebufferpool, we could bundle it.
for github.com/valyala/tcplisten, we could rewrite it by go 1.12 net.ListenConfig (i think it's time to upgrade fasthttp to go 1.12)

Hi @erikdubbelboer and @kirillDanshin, If one of above if acceptable, I am happy submit PRs to start review.

**Comment by erikdubbelboer** [comment]
To be honest, I don't think its worth it. Bundling dependencies is never a good idea (unless you want to modify them for some reason). And I'd rather keep Go 1.11 support for now.

If a company can't clear these simple dependencies then that's a problem for that company. We shouldn't bend to such weird rules.

**Comment by Fenny** [comment]
I think this issue can be closed since there will not be a separate trimmer version due to reasons explained by @erikdubbelboer.
