### ISSUE TITLE
About the behavior of PipelineClient

### ISSUE THREAD

**Issue by marlonfan** [valyala/fasthttp#809]
Hi, Thank you very much for your work.

I am confused by the PipelineClient behavior.

> PipelineClient pipelines requests over a limited set of concurrent connections to the given Addr.
> This client may be used in highly loaded HTTP-based RPC systems for reducing context switches and network level overhead. See https://en.wikipedia.org/wiki/HTTP_pipelining for details.
> It is forbidden copying PipelineClient instances. Create new instances instead.
> It is safe calling PipelineClient methods from concurrently running goroutines.

Will the pipeline connection be retried? I'm not sure idempotent is guaranteed.

**Comment by marlonfan** [comment]
If it's idempotent, I'll use it for HTTP-Based RPC

**Comment by erikdubbelboer** [comment]
PipelineClient doesn't follow redirects and doesn't retry requests on error so it's idempotent.

Depending on if your server can handle pipelining (not nearly all can) and the volume of requests you want to make just using a HostClient or Client is better. PipelineClient is only for super high volume requests (hundreds per second) to servers that support it.

**Comment by marlonfan** [comment]
Got it,  Thanks so mush :)
