### ISSUE TITLE
SetTimeout and Follow Redirect at same time.

### ISSUE THREAD

**Issue by proabiral** [valyala/fasthttp#811]
Hello,

Is it possible to timeout request when server does not responds after certain interval and follow redirect as well ?

`GetTimeout` seems to solve the problem but it does not return Response Headers.

**Comment by erikdubbelboer** [comment]
What do you mean `not return Response Headers`? When there is a timeout you still want the response headers if the server send any? If there is a timeout the server might not have send any headers at all yet?

Have you tried using [`Client.ReadTimeout`](https://godoc.org/github.com/valyala/fasthttp#Client.ReadTimeout) to limit the amount of time the Client waits for the server to respond?

**Comment by proabiral** [comment]
Hi @erikdubbelboer ,
Thank you so much for your response. 

`When there is a timeout you still want the response headers if the server send any?` 
  No, I want to read the response header when there is no timeout.

```
var URL="http://rpstg.caltex.com.au"
var Timeout=time.Duration(10)*time.Second

func doRedirect(){
	req := fasthttp.AcquireRequest()
	req.SetRequestURI(URL)
	resp := fasthttp.AcquireResponse()

	client := &fasthttp.Client{
		TLSConfig: &tls.Config{InsecureSkipVerify: true},
		ReadTimeout: Timeout,
	}

	client.DoRedirects(req, resp, 2)

	fmt.Println(string(resp.Header.Header()))

}

func main() {
	doRedirect()
	}

```

The above code follows redirect and I can read response header when there is no timeout. But for the server that does not responds, the scripts waits for around 50 seconds even though read timeout is set to 10 seconds.


```
var URL="http://rpstg.caltex.com.au"
var Timeout=time.Duration(10)*time.Second


func getTimeoutTest(){
	var dest []byte
	statusCode,body,err:=fasthttp.GetTimeout(dest,URL,time.Duration(Timeout))
	fmt.Println(statusCode,string(body),err,dest)
}


func main() {
	getTimeoutTest()
}
```

 `fasthttp.GetTimeout` follows redirects and timeouts pretty accurately at given 10 seconds but does not seem to return response Headers.

Is there any function that allows to follow redirect, timeout properly and read response headers ?

Regards,

**Comment by erikdubbelboer** [comment]
There is currently no method for this I'm afraid. It has been tried before but it's not that easy: https://github.com/valyala/fasthttp/pull/166

But it's easy to implement yourself:
```go
package main

import (
	"fmt"
	"time"

	"github.com/valyala/fasthttp"
)

var (
	strLocation = []byte("Location")
)

type FollowRedirectClient struct {
	fasthttp.Client
}

func (c *FollowRedirectClient) DoTimeout(req *fasthttp.Request, resp *fasthttp.Response, timeout time.Duration) error {
	for {
		if err := c.Client.DoTimeout(req, resp, timeout); err != nil {
			return err
		}

		statusCode := resp.Header.StatusCode()
		if statusCode != fasthttp.StatusMovedPermanently &&
			statusCode != fasthttp.StatusFound &&
			statusCode != fasthttp.StatusSeeOther &&
			statusCode != fasthttp.StatusTemporaryRedirect &&
			statusCode != fasthttp.StatusPermanentRedirect {
			break
		}

		location := resp.Header.PeekBytes(strLocation)
		if len(location) == 0 {
			return fmt.Errorf("Redirect with missing Location header")
		}

		u := req.URI()
		u.UpdateBytes(location)
	}

	return nil
}

func main() {
	c := FollowRedirectClient{}

	req := fasthttp.AcquireRequest()
	defer fasthttp.ReleaseRequest(req)
	resp := fasthttp.AcquireResponse()
	defer fasthttp.ReleaseResponse(resp)

	req.SetRequestURI("http://google.com")

	if err := c.DoTimeout(req, resp, time.Second); err != nil {
		panic(err)
	}

	println(string(resp.Body()))
}
```

**Comment by proabiral** [comment]
Thanks a lot :)
