### ISSUE TITLE
Response.ContentLength Not correct

### ISSUE THREAD

**Issue by ruslanBik4** [valyala/fasthttp#812]
Code:
```			
if len(string(resp.Body())) > 0 {
	logs.DebugLog( "i got %d %s", resp.Header.ContentLength(), resp.String() )
}
```
#read log:
[[DEBUG]]11:18:38 task.go:105: i got **90** HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 08:18:38 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: **89**

What??? resp.Header.ContentLength()=90, resp.String() thinks different 

(I found this paradox out when wrote code:
```
If resp.Header.ContentLength() > 0 {
logs.StatusLog(resp.Body() )
}
```
and got many empty row on log !
 Reading body is not match performance on empty response :-)
)

*Go 1.14
*github.com/valyala/fasthttp v1.9.0

**Comment by erikdubbelboer** [comment]
Do you have the raw HTTP response? `resp.String()` rebuilds the response from the parsed state. If you have the real HTTP response I could see what goes wrong. So far I have not been able to reproduce it by trying different things here: https://play.golang.org/p/sNcqHFMAktA

**Comment by ruslanBik4** [comment]
``` 	var resp fasthttp.Response
	c := fasthttp.Client{
		MaxIdleConnDuration: time.Minute * 10,
		MaxConnDuration :	time.Minute * 10,
	}
	
	//some code

		err := c.Do(req, &resp)
```
(Got  HTTP response)

**Comment by erikdubbelboer** [comment]
? I mean do you have the HTTP text from before fasthttp parses it? Is it a public endpoint you are requesting? Can I make the same request and see the response?

**Comment by ruslanBik4** [comment]
No. I did’t parsing after client.Do. I check ContentLength immediately. 
 This are my own service (client &server), ContentLength, connection must to be open for repetition requests. 
 Request made on the code:
```

func DoRequestAndKeep(url string, params map[string]string )
	req := &fasthttp.Request{}
        if params != nil {
		var b bytes.Buffer
		w := multipart.NewWriter(&b)
		for name, val := range params {
			err := w.WriteField(name, val)
			if err != nil {
				return err
			}
		}

		if err := w.Close(); err != nil {
			return errors.Wrap(err, "w.Close")
		}
		req.Header.Set("Content-Type", w.FormDataContentType())
		req.SetBody(b.Bytes())
	} else {
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	}

	req.Header.SetMethod(fasthttp.MethodPost)
	req.SetRequestURI(url)
```

**Comment by ruslanBik4** [comment]
Log of responses:

[[DEBUG]]13:19:58 task.go:106: i got 19 HTTP/1.1 200 OK
Server: propReport manager (dev)
Date: Mon, 25 May 2020 10:19:58 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 19
fill download start
[[DEBUG]]13:20:04 task.go:106: i got 89 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:04 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 89
CommGetAndWriteFills is running ‘ insert 0 fills #456’
[[DEBUG]]13:20:04 task.go:106: i got 89 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:04 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 89
CommGetAndWriteFills is running ‘ insert 0 fill #987’
[[DEBUG]]13:20:13 task.go:106: i got 90 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:13 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 90
CommGetAndWriteFills is running ‘ insert 0 fills by #1157 '
[[DEBUG]]13:20:19 task.go:106: i got **89** HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:18 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: **90**
CommGetAndWriteFills is running ‘ insert 0 fills by #1865 '
[[DEBUG]]13:20:19 task.go:106: i got 90 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:18 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 90
CommGetAndWriteFills is running ‘ insert 0 fills by #1865 '
[[DEBUG]]13:20:19 task.go:106: i got 88 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:19 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 90
CommGetAndWriteFills is running ‘ insert 0 fills by #1060 '7060123' 2020-05-20 (104/321)
[[DEBUG]]13:20:19 task.go:106: i got 90 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:19 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 90
CommGetAndWriteFills is running ‘ insert 0 fills by #1060 '7060123' 2020-05-20 (104/321)
[[DEBUG]]13:20:19 task.go:106: i got 88 HTTP/1.1 206 Partial Content
Date: Mon, 25 May 2020 10:20:19 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 88
CommGetAndWriteFills is running ‘ insert 0 fills by #563 '7060222' 2020-05-20 (93/321)
[[DEBUG]]13:20:42 task.go:106: i got 32 HTTP/1.1 200 OK
Server: propReport manager (dev)
Date: Mon, 25 May 2020 10:20:42 GMT
Content-Type: text/plain; charset=utf-8

(I shrink real body text)

**Comment by erikdubbelboer** [comment]
What URL are you requesting? Is it something I can request as well?

**Comment by ruslanBik4** [comment]
It is local service. 
I’m sorry, I wrote for this question above. 
It is my own server:
https://github.com/ruslanBik4/httpgo
(Is based on fasthhtp )

**Comment by ruslanBik4** [comment]
I can’t give you URL (it is private system) for checking but it is very simple code on server side:
https://github.com/ruslanBik4/httpgo/blob/b9b850418ae59d5860ab1d1ca6634c4725ba4f40/apis/apis.go#L147

**Comment by erikdubbelboer** [comment]
That's not possible, fasthttp never returns `206 Partial Content` when using `ctx.Response.SetBodyString` on the server. Is there maybe some proxy in between?

**Comment by ruslanBik4** [comment]
I’m so sorry! It is custom handler with 	ctx.Hijack(hijackHandler).
Only first response making with httpgo.Apis(see above). 
Other response make the code:
```
Func handler(ctx) {
hijackHandler := func(c net.Conn) {

	const header = `HTTP/1.1 206 Success 
Content-Type: text/plain; charset=utf-8
Content-Length: `

For {
...
   w := bufio.NewWriter(c)	
  msg = header + addStr(cmd + " is running ‘" + msg)
  _, err = w.WriteString( msg )
...
}
}
...
ctx.Hijack(hijackHandler)
} //end handler 
// add content length 
func addStr(str string) string {
	return fmt.Sprintf(`%d

`, len(str)) + str
}

**Comment by erikdubbelboer** [comment]
The wrong `ContentLength()` happens when the body is shorter than the `Content-Length` header: https://play.golang.org/p/L685jv2vjyf not sure where this goes wrong in your handler, the code you posted seems ok.

```go
err := c.Do(req, &resp)
```
should return an `unexpected EOF` error as you can see from my example as well. Are you sure you are checking this error?

**Comment by ruslanBik4** [comment]
Yes, of course. 
```
		err := c.Do(req, &resp)
		switch err {
		case fasthttp.ErrTimeout, fasthttp.ErrDialTimeout:
			logs.DebugLog("timeout %+v", resp)
			<-time.After(time.Minute * 2)
			continue
		case fasthttp.ErrNoFreeConns:
			logs.DebugLog("timeout %v", resp)
			<-time.After(time.Minute * 2)
			continue
		case nil:
			if resp.Header.ContentLength() > 0 {
```
 I understood well  that  resp.Header.ContentLength() return value according to header of request but resp.String() get real length of requests body?

**Comment by erikdubbelboer** [comment]
I don't see you handling `io.ErrUnexpectedEOF` or `io.EOF` or any other possible error?

What you have here is bad response. Your `Content-Length` header says the response is going to be 90 characters long. But after reading 89 characters the connection is closed. If you don't look at the error returned by `c.Do` and just print the response it will only print those 89 characters it read.

**Comment by ruslanBik4** [comment]
Any other errors break conversation among services. 
I will add handling for io.ErrUnexpectedEOF or io.EOF today. 
May be. Connection close during sending response

**Comment by ruslanBik4** [comment]
<img width="1218" alt="PNG image" src="https://user-images.githubusercontent.com/13148162/82816844-8caa0800-9ea4-11ea-9e2c-80adcc631316.png">

I got it now. Same response, different Content Lenght

**Comment by erikdubbelboer** [comment]
Are you really sure `err == nil`. When I do something very similar to your code `err = io.ErrUnexpectedEOF`: https://play.golang.org/p/mEKbOk6NFSI

Would you be able/willing to run a modified version of fasthttp so I can add more logging to try and find out what is happening?

`w := bufio.NewWriter(c)` do you `w.Flush()` this in your `hijackHandler`?

**Comment by ruslanBik4** [comment]
All answer -yes

**Comment by erikdubbelboer** [comment]
I'll need to think of how to approach this best and write a branch, I'll try to get to that this week.

**Comment by erikdubbelboer** [comment]
Can you try this branch: https://github.com/valyala/fasthttp/tree/response-raw-headers
It adds `ResponseHeader.RawHeaders`. Can you then `fmt.Printf("%q", resp.Header.RawHeaders)` when it goes wrong.

**Comment by Fenny** [comment]
@ruslanBik4, did you tried the above solution?
