### ISSUE TITLE
How does TCP []byte convert to fasthttp?

### ISSUE THREAD

**Issue by sanxun0325** [valyala/fasthttp#816]
I got TCP []byte through net.conn, and I want to convert it to fasthttp req.Any good ideas or Suggestions?

**Comment by erikdubbelboer** [comment]
If you have `[]byte` and you want to convert it to a `fasthttp.Request` for example you can use [`fasthttp.Request.Read`](https://godoc.org/github.com/valyala/fasthttp#Request.Read):

```go
var b []byte

// ... b is ready from net.Conn

var req fasthttp.Request
err := req.Read(bufio.NewReader(bytes.NewReader(b)))
```

You can do exactly the same for `fasthttp.Response`.
