### ISSUE TITLE
Client sometimes returned ErrConnectionClosed

### ISSUE THREAD

**Issue by silence44** [valyala/fasthttp#818]
I'm using fasthttp.Client to make requests to my other services that have basic http.Server (with keepAlives enabled by default).

Sometimes I have this error returned by the client.

"the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection"

I read all the documentation and code connected with ErrConnectionClosed but can't understand how can I fix my issue. If connection was closed by the server, then why does the client not reopening it?

In logs of the other service I see that everything is fine and it returned the response correctly to the client. But on the client side I have ErrConnectionClosed.

Please help me to resolve this. What kind of information is needed to identify my problem?

**Comment by erikdubbelboer** [comment]
`ErrConnectionClosed` happens when the server closes the connection before or during a request. What are your client and server timeouts set to? The timeouts on the server should always be longer than the timeouts on the client.

**Comment by Fenny** [comment]
@silence44 we didn't hear back from you, did you managed to solve the issue? If so, please let us know so we can close this issue 👍
