### ISSUE TITLE
🐞 Wrong Content-Type FileServer

### ISSUE THREAD

**Issue by Fenny** [valyala/fasthttp#819]
Hello, when I'm playing with multiple directories using the `FS` request handler it will return the default content-type `text/plain` using the second file handler.

Maybe I'm not doing it the right way, so please correct me if I'm wrong.

![](https://i.imgur.com/dnodwvm.png)
```go
package main

import (
	"log"

	"github.com/valyala/fasthttp"
)

func main() {
	path1 := &fasthttp.FS{Root: "./path1", IndexNames: []string{"index.html"}}
	fs1 := path1.NewRequestHandler()

	path2 := &fasthttp.FS{Root: "./path2"}
	fs2 := path2.NewRequestHandler()

	log.Fatal(fasthttp.ListenAndServe(":3000", func(ctx *fasthttp.RequestCtx) {
		fs1(ctx)
		if ctx.Response.StatusCode() != 200 {
			fs2(ctx)
		}
	}))

	// http://localhost:3000/index.html   // text/html
	// http://localhost:3000/demo.html    // text/plain
}

```

**Comment by erikdubbelboer** [comment]
It's not really normal to chain FS handlers like. The first one will return a 404 not found (which gets a `text/plain` Content-Type. Then the next FS handler [won't overwrite](https://github.com/valyala/fasthttp/blob/24410e58c0f42eeff818f08c50acac9895454816/fs.go#L837-L839) the Content-Type if it's already set.

This should work:
```go
if ctx.Response.StatusCode() != 200 {
	ctx.SetContentType("")
	fs2(ctx)
}
```

**Comment by Fenny** [comment]
Solved it, thanks for pointing me in the right [direction](https://github.com/valyala/fasthttp/blob/24410e58c0f42eeff818f08c50acac9895454816/fs.go#L837-L839)
