### ISSUE TITLE
 r.ParseForm() in fasthttp?

### ISSUE THREAD

**Issue by xpbliss** [valyala/fasthttp#82]
Http.Request.ParseForm
What is the  r.ParseForm() in fasthttp?

**Comment by absourdnoise** [comment]
@xpbliss 
https://godoc.org/github.com/valyala/fasthttp#RequestCtx.PostArgs
https://godoc.org/github.com/valyala/fasthttp#RequestCtx.QueryArgs

**Comment by valyala** [comment]
See also [RequestCtx.FormValue](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.FormValue).

**Comment by kataras** [comment]
@xpbliss  you already know the answer, you are an iris fan go to it's source and look how [Context:ReadForm](https://github.com/kataras/iris/blob/development/context_binder.go#L78) works :)
