### ISSUE TITLE
🐞 panic in fs.go

### ISSUE THREAD

**Issue by Fenny** [valyala/fasthttp#824]
<https://github.com/valyala/fasthttp/blob/master/fs.go#L85>

```go
	if len(path) == 0 || path[0] != '/' {
		// extend relative path to absolute path
		hasTrailingSlash := path[len(path) - 1] == '/'
```

We match `len(path) == 0` and within the statement we call `path[len(path) - 1]` and causes a panic when the path length is `0`. This is possible using specific `NewPathSlashesStripper` or `NewPathPrefixStripper` conditions, please correct me if I'm wrong.

**Comment by ReneWerner87** [comment]
https://github.com/valyala/fasthttp/blob/master/fs.go#L691
`func (h *fsHandler) handleRequest(ctx *RequestCtx) {
	var path []byte
	if h.pathRewrite != nil {
		path = h.pathRewrite(ctx)
	} else {
		path = ctx.Path()
	}
	hasTrailingSlash := path[len(path) - 1] == '/'
	path = stripTrailingSlashes(path)
`
please add a check of the length here as well, I would recommend to put this check on trailing slash into a function and check the length before

**Comment by ReneWerner87** [comment]
PR for that
https://github.com/valyala/fasthttp/pull/825
