### ISSUE TITLE
Support fileserving precompressed files

### ISSUE THREAD

**Issue by Vorror** [valyala/fasthttp#829]
Background: We compress our assets files during the build phase of webpack(gz, br) and don't need the server to compress our assets.

Currently, Fileserve doesn't check if the requested exists in compressed form. Fileserve should check for alternate file extensions before serving the request(assuming the request header allows for compression)

Alternatively, I could just be doing something wrong or read the fs.go code incorrectly and there's some option not being set.

[prior art(js/koa-js)](https://github.com/koajs/send/blob/master/index.js#L75)

Example directory structure of the assets folder:
```
├── css
│   ├── app.acc3a0be.css
│   ├── app.acc3a0be.css.br
│   ├── app.acc3a0be.css.gz
│   ├── chunk-vendors.152e64c3.css
│   ├── chunk-vendors.152e64c3.css.br
│   └── chunk-vendors.152e64c3.css.gz
├── favicon.ico
├── favicon.ico.br
├── favicon.ico.gz
├── img
│   ├── icons.7ff3503a.svg
│   ├── icons.7ff3503a.svg.br
│   ├── icons.7ff3503a.svg.gz
│   └── logo.png
├── index.html
├── index.html.br
├── index.html.gz
├── js
│   ├── app.f1ae8fdd.js
│   ├── app.f1ae8fdd.js.br
│   ├── app.f1ae8fdd.js.gz
│   ├── app.f1ae8fdd.js.map
│   ├── chunk-vendors.34c45940.js
│   ├── chunk-vendors.34c45940.js.br
│   ├── chunk-vendors.34c45940.js.gz
│   └── chunk-vendors.34c45940.js.map
└── robots.txt
```

**Comment by erikdubbelboer** [comment]
This is already supported by setting `CompressedFileSuffix: ".gz"`

But keep in mind that fasthttp will recompress the file if the source file has a newer modification time than the compressed file.

I just pushed a fix for a bug regarding this on MacOS: https://github.com/valyala/fasthttp/commit/2f28edba01f05c1e065739deb7bd3dabade7d2a6

**Comment by Vorror** [comment]
@erikdubbelboer Thanks for the quick reply. Does that setting support both gzip _and_ brotli/br?

Also, it sounds like I have to turn on server-based compression for this feature to work. Preferably, I _only_ want compression if the files already exist in a compressed state.

**Comment by erikdubbelboer** [comment]
I'm afraid it only supports gzip. Brotli hasn't been build into the FS handler at all yet.

Yes you have to enable compression for all files.

I'm afraid I currently don't have time to build these features. But pull requests are always welcome!

**Comment by Fenny** [comment]
@erikdubbelboer, I have some time to help, should we add `CompressBrotli bool` and `CompressedBrotliFileSuffix string` to the `FS` settings? If Brotli is enabled it will fallback to gzip/deflate if `br` is not present in the `Accept-Encoding` header? Or do you want to prioritize brotli compression by default?

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/pull/880
