### ISSUE TITLE
Removing Cookies

### ISSUE THREAD

**Issue by hardcoar** [valyala/fasthttp#83]
Sorry, this might be a dumb question, but what's the most convenient way of complete removing cookies? i don't have any problems setting up cookies, but i don't know how to completely remove them.

my temporary solution in getting rid of the cookie for now is like this:
```
cookie := fasthttp.AcquireCookie()
	cookie.SetKey("mykey")
	cookie.SetValue("") // removes existing values
	cookie.SetHTTPOnly(true)
	ctx.Response.Header.SetCookie(cookie)
	fasthttp.ReleaseCookie(cookie)
```

is there anyway i can completely remove or clear the cookie?

the way i can acquire cookie (as far as i know im new to this lol) is through ```fasthttp.AcquireCookie()``` but it returns an empty cookie.

also ```func (h *RequestHeader) Cookie(key string) []byte``` and ```ctx.Request.Header.Cookie("mykey")``` both returns []byte.

is there anyway i can just remove the Cookie Header?
again im sorry if this is a stupid question and thanks a lot in advance! (:

**Comment by valyala** [comment]
@hardcoar , I just added the following methods to fasthttp:
- [ResponseHeader.DelCookie](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.DelCookie), [ResponseHeader.DelCookieBytes](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.DelCookieBytes) for removing cookies by name from response header.
- [ResponseHeader.DelAllCookies](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.DelAllCookies) for removing all the cookies from response header.

Note that these functions should remove `Set-Cookie` response headers, but they don't remove the corresponding cookies from the client. Send expired cookies for removing cookies from the client. See [Cookie.SetExpire docs](https://godoc.org/github.com/valyala/fasthttp#Cookie.SetExpire) for details.

**Comment by kataras** [comment]
@valyala  I think you should explain it better, because I made my own sessions package and I will searching about an hour + why DelCookie wasn't work and finally I made a cookie, set expire to -1 second and send to the response header...

**Comment by valyala** [comment]
@kataras , I just added [ResponseHeader.DelClientCookie](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.DelClientCookie) method and clarified the meaning of [ResponseHeader.DelCookie](https://godoc.org/github.com/valyala/fasthttp#ResponseHeader.DelCookie) method.

**Comment by kataras** [comment]
Excellent! Thanks you
