### ISSUE TITLE
Docs: Fuzzit badge isn't loading

### ISSUE THREAD

**Issue by nyaascii** [valyala/fasthttp#838]
Hi!

I've noticed the Fuzzit badge isn't loading anymore, and also read that [Fuzzit got acquired by GitLab](https://fuzzit.dev/2020/06/11/news-fuzzit-is-acquired-by-gitlab/). They also wrote about deleting all the data in 6 months, so I assume they are going to shut down Fuzzit.

Sorry for this unconventional issue, I thought it would be good to let you know about this 😊 

Thank you very much for your time and fasthttp 🙇‍♀️

**Comment by nyaascii** [comment]
![404](https://user-images.githubusercontent.com/17256443/85160948-64bd8280-b25f-11ea-8cd6-2c2727c96bae.png)

https://app.fuzzit.dev/badge?org_id=fasthttp&branch=master returns `Error 404`

**Comment by erikdubbelboer** [comment]
Too bad for them deleting all current users. I have removed fuzzit from the repo here https://github.com/valyala/fasthttp/commit/ac4cc171a5cbab437b7618772166a0b85f7d2649

**Comment by erikdubbelboer** [comment]
fasthttp is still being fuzz tested by https://github.com/google/oss-fuzz/tree/master/projects/fasthttp
