### ISSUE TITLE
Setting host header not working with HTTPS

### ISSUE THREAD

**Issue by moredure** [valyala/fasthttp#841]
https://github.com/valyala/fasthttp/issues/318

Same example as in the issue above with HTTPS, result in
HostClient can't follow redirects to a different protocol, please use Client instead
error

**Comment by moredure** [comment]
In case of schema SetSchema("https") 
result in 
"missing required Host header in request"

**Comment by moredure** [comment]
Looks like the problem is here
if c.IsTLS != bytes.Equal(req.uri.Scheme(), strHTTPS) {
		return false, ErrHostClientRedirectToDifferentScheme
	}

isTLS not working with SetHost because expects Schema to be https, but it comes as nil, because URI is not parsed in order to replace uri host with host header
in case of schema specified host header grabbed from uri

**Comment by erikdubbelboer** [comment]
Can you show a full example of what you mean? I'm confused at what you are trying to do. It sounds like a bug but I need some code to verify.

**Comment by moredure** [comment]
Smth like that
github.com -> 140.82.118.3
I just want to access website by IP using custom Host Header via HTTPS
```
func main() {
	req := &fasthttp.Request{}
	resp := &fasthttp.Response{}
	client := fasthttp.HostClient{
		IsTLS: true,
		Addr: "140.82.118.3:443",
	}
	req.SetRequestURI("/")
	req.Header.SetHost("github.com")
	fmt.Println(client.Do(req, resp))
}
```
Result in HostClient can't follow redirects to a different protocol, please use Client instead

**Comment by moredure** [comment]
Slightly different code results in TLS error
```
func main() {
	req := &fasthttp.Request{}
	resp := &fasthttp.Response{}
	client := fasthttp.HostClient{
		IsTLS: true,
		Addr: "140.82.118.3:443",
	}
	req.SetRequestURI("/")
	req.Header.SetHost("github.com")
	req.URI().SetScheme("https")
	fmt.Println(client.Do(req, resp))
}
```
x509: cannot validate certificate for 140.82.118.3 because it doesn't contain any IP SANs

**Comment by anshul-jain881** [comment]
A workaround is to use ```tlsConfig``` and set``` ServerName``` for now. But yeah seems that code commit you mentioned needs some modifications for it to work.

```go

func main() {
	req := &fasthttp.Request{}
	resp := &fasthttp.Response{}
	tlsConfig := &tls.Config{
		ServerName: "httpbin.org",
	}
	client := fasthttp.HostClient{
		IsTLS: true,
		Addr: "3.220.112.94:443",
		TLSConfig: tlsConfig,
	}
	req.URI().SetScheme("https")
	req.SetRequestURI("/get")
	req.Header.SetHost("httpbin.org")
	err := client.Do(req, resp)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(resp.Body()))
}


```

**Comment by moredure** [comment]
Yes, one more workaround is to specify IP address in Dial option

**Comment by moredure** [comment]
The most wanted feature is been able to do it with fasthttp.Client instead of HostClient

**Comment by erikdubbelboer** [comment]
The recommended way to do this with both `fasthttp.Client` is to implement your own Dial function that dials the IP you want instead of the IP the domain resolves to.

This is fairly easy and will also follow any redirects (even cross protocol):
```go
func main() {
	req := &fasthttp.Request{}
	resp := &fasthttp.Response{}
	client := fasthttp.Client{
		Dial: func(addr string) (net.Conn, error) {
			if addr == "github.com" {
				addr = "140.82.118.3"
			}
			return fasthttp.Dial(addr)
		},
	}
	req.SetRequestURI("https://github.com")
	fmt.Println(client.Do(req, resp))
}
```

Would this work for you?

**Comment by moredure** [comment]
I've done a little bit another way using cache in dial wich is filled from main goroutine to not create fasthttp each time I need dial another domain.

**Comment by erikdubbelboer** [comment]
Sounds like you have it working. Can this issue be closed?
