### ISSUE TITLE
some confusions when reading workerpool code 

### ISSUE THREAD

**Issue by microyahoo** [valyala/fasthttp#844]
Currently, I'm learning the code of `fasthttp`, the code is very elaborate and benefit me a lot. I have some confusion of `workerpool` implementation. https://github.com/valyala/fasthttp/blob/master/workerpool.go
1. The `Serve()` can continue to serve the incoming connection even if user have invoked the `Stop()`, because `getCh()` will create a new workerChan and provide service. Does we need to add some logic to prevent this situation?
2. Is there such a situation that the obsolete worker will continue to provide a service even if it has been added to scratch slice in `clean`, because seems to exist a time window.
3. For `type ServeHandler func(c net.Conn) error`, whether necessary to add a `context.Context` parameter or not?

Thanks advance.

**Comment by erikdubbelboer** [comment]
1. `workerPool.Serve()` is called from the loop in `Server.Serve()`. But this loop is terminated when you call `Server.Stop()`. Keep in mind that the `workerPool` implementation is very specific to fasthttp and its use of it. I wouldn't recommend this as a general worker pool (why the package isn't exported).
2. `clean` does its operations while holding a lock on the mutex. `ready` is also only modified when this lock is hold. This should prevent this from happening.
3. I'm not sure what you mean? Adding a `context.Context` would break how it's being used in fasthttp?
