### ISSUE TITLE
get cookie object by name

### ISSUE THREAD

**Issue by jney** [valyala/fasthttp#845]
Hi, I can see I can get cookie value using `fasthttp.Request.Header.Cookie("key")`, but I was wondering how to get all cookie attributes, I mean a `fasthttp.Cookie` object instead of the value. The equivalent function of `cookie, err := http.Request.Cookie("key")`  in the standard library.
Thanks

**Comment by jney** [comment]
I really don't understand how I should deal with cookies, as the paradigm differ from std lib

```go
	req.Header.VisitAllCookie(func(k, v []byte) {
		if c.Cookie != nil {
			return
		}
		if bytes.Equal(bName, k) {
			ck := fasthttp.AcquireCookie()
			ck.ParseBytes(v)
			c.Cookie = ck
			logrus.
				WithField("v", string(v)).
				WithField("ck.Value", string(ck.Value())).
				Info("cookie value")
		}
	})
```

and I get

```
time="2020-07-02T16:28:03Z" level=info msg="cookie value" ck.Value="=" v="MTU5MzcwNzI4M3xZcm5yRWkxeVdoMlJ5a1hRakhaX0d6NjZYX1otOVZmdlZhU0JSZ1JkbG9CUGl6YXptRmxiYTZrVERuY3o4MEdvWmUwVWtXbk5hdGt6OVN0aWhpT2JFQ1V1TnA0VmtyUWtlZk5iVHBYQk5KMVh4YmJncGlrPXySvW0_rdKEQEpVlSQelhzpaG0cmTcnb-F5kVnJd-ayjQ=="
```

aren't `v` and `ck.Value()` supposed to be equals?

**Comment by jney** [comment]
In the same thematic, I don't get how to set a cookie (I mean a cookie object with some meta, not only key/value) using the `fasthttp.Client`

**Comment by erikdubbelboer** [comment]
Are we talking about a server or client here?

A server will send a [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header with all the attributes. But a Client will only send a [`Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) header with `key=value` pairs. A [`Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) header doesn't include the attributes. A client never sends the attributes to the server.

**Comment by Fenny** [comment]
@jney I think you are confused with the [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) ( server ) and [Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) ( server ) headers. Did you managed to solve your issue, if so please let us know so we can close this issue.

**Comment by jney** [comment]
hello guys. my bad, it is indeed a confusion. 
anyway, does it looks regular to you in my second message to have not the same content in `v` and `ck.Value`

**Comment by erikdubbelboer** [comment]
@jney the Request header cookie you are trying to parse is just a value (as you can see from the `v=...`). There is nothing to parse.

`Cookie.ParseBytes` is for cookies from Response headers that contain key value pairs such as `name=value; path=/; domain=...` etc.

**Comment by Fenny** [comment]
@erikdubbelboer could you close this issue?
