### ISSUE TITLE
TestServeFileDirectoryRedirect failure

### ISSUE THREAD

**Issue by tranja-aws** [valyala/fasthttp#850]
I keep getting this error when trying to build fasthttp v1.14.0:

`TestServeFileDirectoryRedirect: fs_test.go:754: Unexpected status code 404 for directory '/.git' without trailing slash. Expecting 302.`

This seems to be the error:
`GET http:///path/to/directory/build/gopath/src/github.com/valyala/fasthttp/.git - cannot open file "/path/to/directory/build/BackplaneFastHttp/BackplaneFastHttp-1.x.59.0/AL2012/DEV.STD.PTHREAD/build/gopath/src/github.com/valyala/fasthttp/.git": open /path/to/directory/build/gopath/src/github.com/valyala/fasthttp/.git: no such file or directory`

I've tried debugging this issue by printing out ctx.Request.URI().fullURI within fs.go in the ServeFile() method, right before passing the ctx to rootFSHandler the URI is blank...

```
	ctx.Request.SetRequestURI(path)
	ctx.Logger().Printf("uri123: " + string(Request.URI().fullURI))
	rootFSHandler(ctx)
```

Result:
`GET http:///path/to/directory/build/gopath/src/github.com/valyala/fasthttp/fs.go - uri123:`

Any ideas what's going on here?

**Comment by erikdubbelboer** [comment]
I have just released [v1.15.0](https://github.com/valyala/fasthttp/releases/tag/v1.15.0), can you check if this is still happening with this version? It contained some fixes for the FS code so it should be fixed.

**Comment by tranja-aws** [comment]
Same issue after updating to v1.15.0:

```
2020/07/14 21:59:19 0.000 #0000012700000000 - 0.0.0.0:0<->0.0.0.0:0 - GET http:///path/to/directory/build/gopath/src/github.com/valyala/fasthttp/.git - cannot open file "path/to/directory/build/gopath/src/github.com/valyala/fasthttp/.git": open /path/to/directory/build/gopath/src/github.com/valyala/fasthttp/.git: no such file or directory
    TestServeFileDirectoryRedirect: fs_test.go:759: Unexpected status code 404 for directory '/.git' without trailing slash. Expecting 302.
--- FAIL: TestServeFileDirectoryRedirect (0.00s) 
```

**Comment by erikdubbelboer** [comment]
I just tagged v1.15.1 which should fix your issue. Just curious, why are you running the tests of your dependencies? Never seen that done before.

**Comment by Fenny** [comment]
I can confirm that `v1.15.1` solves this issue, I think we can close this @erikdubbelboer.
