### ISSUE TITLE
[Feature Request] Convenience method for RequestHeader 

### ISSUE THREAD

**Issue by bogdanciuca** [valyala/fasthttp#853]
> net/http headers are stored in a `map[string][]string`. So the server must parse all the headers, convert them from `[]byte` to `string` and put them into the `map` before calling user-provided request handler. This all requires unnecessary memory allocations avoided by `fasthttp`.

This is great, but there are some scenarios (e.g. proxies) where the list of expected headers is unknown and the request needs to be transformed in a consistent and safe manner. 

Another use case would be converting and outputting the request headers as a `JSON` response (e.g. http://httpbin.org/headers). We've actually started implementing a slightly more advanced `httpbin` service in `Go` based on `Fiber`, to be used in various testing scenarios.

I believe having a commodity method like `func (h *RequestHeader) HeadersMap() map[string]string` would be really useful, so you can easily iterate on the headers, without adding performance costs to the framework, since it's on demand. 

The `return type` could also be the one used by `net/http` (e.g. `map[string][]string`), for better interoperability / consistency, however I'm ok with either approach.

What do you guys think? Looking forward to contribute!

**Comment by erikdubbelboer** [comment]
We have a method for this already: [`RequestHeader.VisitAll`](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.VisitAll). By using a callback instead of returning a map we can still guarantee zero allocations. Would this method not work for you?

**Comment by bogdanciuca** [comment]
That should work, don't know how I missed it. Thanks @erikdubbelboer !
