### ISSUE TITLE
[Feature Request] Client convenience method for retrieving response headers 

### ISSUE THREAD

**Issue by bogdanciuca** [valyala/fasthttp#854]
Since `Client` already has some commodity methods, e.g. `Get()` & `Post()`, another useful case would be a method (or pair) that also retrieves the response headers.

I know this can be achieved with `Do()`, but that requires a lot more boilerplate, so it isn't really a commodity method.

What do you think?

**Comment by bogdanciuca** [comment]
@valyala @erikdubbelboer any thoughts?

**Comment by erikdubbelboer** [comment]
What format/type would it return the response headers in? I think when you design this to support zero allocations you'll end up with `Do()`.

**Comment by bogdanciuca** [comment]
I'll see what I can come up with, thanks for the feedback @erikdubbelboer .
