### ISSUE TITLE
Is HTTP/2.0 support finished?

### ISSUE THREAD

**Issue by leo2n** [valyala/fasthttp#856]
Hello, I want to know Is http/2.0 finished? :smiley:

**Comment by erikdubbelboer** [comment]
I'm afraid nobody is working on http2 at the moment. See https://github.com/valyala/fasthttp/issues/144

**Comment by Fenny** [comment]
@kirillDanshin is working on http2 <https://github.com/valyala/fasthttp/issues/786#issuecomment-617979014>
