### ISSUE TITLE
Pre handler function

### ISSUE THREAD

**Issue by dyrkin** [valyala/fasthttp#857]
Hi guys,

Is it possible to specify a kind of pre handler function which receives just a response as a parameter and based on a boolean result tells fasthttp to read a request into memory and call to the handler or do not read the request and do not call the handler?

In my application, I receive many requests with large bodies. Sometimes based on some conditions I do want not to allow `fasthttp` to read the request body into memory rather set the response status.

```golang
server := &fasthttp.Server{
	PreHandler: func (rsp *fasthttp.Response) bool {
		if isEnoughRam() && isEnoughDiskSpace() && isNotQueueLimitReached() {
			return true
		}
		rsp.SetStatusCode(fasthttp.StatusInternalServerError)
		return false
	},
}
```

**Comment by erikdubbelboer** [comment]
You could use [`Server.HeaderReceived`](https://godoc.org/github.com/valyala/fasthttp#Server.HeaderReceived) and return a really small [`https://godoc.org/github.com/valyala/fasthttp#RequestConfig.MaxRequestBodySize`](RequestConfig.MaxRequestBodySize) if you don't want to read a big request body.

Or if your clients are browsers or other clients that send an Expect 100 Continue header before sending a large body you could use [`Server.ContinueHandler`](https://godoc.org/github.com/valyala/fasthttp#Server.ContinueHandler).
