### ISSUE TITLE
ServeFile prepends / on windows

### ISSUE THREAD

**Issue by henkman** [valyala/fasthttp#86]
I get following error when trying to serve a file using ServeFile:
`2016/04/27 11:05:40 0.001 #0000000100000001 - [::1]:8080<->[::1]:50575 - GET http://localhost:8080/C:%5CProjects%5Cgo%5Csrc%5Ctest%5Cindex.html - cannot open file "/C:\\Projects\\go\\src\\test\\index.html": open /C:\Projects\go\src\test\index.html.fasthttp.gz: The filename, directory name, or volume label syntax is incorrect.`
Looks like it always prepends a slash which on windows does not make a lot of sense.
I use ServeFile like this:
`fasthttp.ServeFile(ctx, "index.html")`

**Comment by valyala** [comment]
I have no access to Windows, so cannot fix the issue at the moment.
Will happily merge a pull request for the issue provided it contains the corresponding tests and it doesn't break `fasthttp` on linux.

**Comment by kataras** [comment]
@henkman You maybe want to check [Iris:ServeFile](https://github.com/kataras/iris/blob/development/context_renderer.go#L227) implementation for ServeFile, which is working both linux & windows. Note that iris is build on top of the fasthttp so it's code can help you with this!

**Comment by ernado** [comment]
I have access to windows machine and will try to debug this issue today.

**Comment by valyala** [comment]
Closing the issue, since it should be fixed now
