### ISSUE TITLE
Cookie always comes back as secure

### ISSUE THREAD

**Issue by saul-gush** [valyala/fasthttp#861]
We are trying to work with a cookie on localhost and we cannot remove "secure". I think it is a bug in setting cookies with fasthttp. 

```
	authCookie := fasthttp.Cookie{}
	authCookie.SetKey("jwt")
	authCookie.SetValue("xyz")
	authCookie.SetPath("/")
	authCookie.SetExpire(timein)
	authCookie.SetSecure(false)
	authCookie.SetHTTPOnly(true)
	authCookie.SetSameSite(fasthttp.CookieSameSiteNoneMode)
	c.Fasthttp.Response.Header.SetCookie(&authCookie)
```
Response:
```
set-cookie: jwt=xyz; expires=Thu, 10 Sep 2020 23:39:37 GMT; path=/; secure; SameSite=None
```
Expected response without "secure;"

**Comment by erikdubbelboer** [comment]
As the documentation of [`Cookie.SetSameSite`](https://godoc.org/github.com/valyala/fasthttp#Cookie.SetSameSite) says:
```
// SetSameSite sets the cookie's SameSite flag to the given value.
// set value CookieSameSiteNoneMode will set Secure to true also to avoid browser rejection
```
This is a requirement from the spec as you can read here as well for example: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```
... any cookie that requests SameSite=None but is not marked Secure will be rejected.
```
