### ISSUE TITLE
Ability to customize the bytes of the request

### ISSUE THREAD

**Issue by melardev** [valyala/fasthttp#862]
Hi, I was looking to customize the HTTP request bytes before the request is sent, with the standard package I learned it was not possible without writing a custom http.RoundTripper which is overkill for such a basic task, because the bytes to send are built on the write() method from the Request struct object and it turns out the http.HttpClient.Do() takes a Request struct object so there is no way to customize it, if http.Request was an interface then we could just pass our own interface to Do() but since it is a struct we can not pass our own implementation because even if we extend *http.Request there is no polymorphism in function arguments in Golang so the compiler will refuse to pass our Request struct to Do().

I am wondering if we can do what I am looking for in fasthttp, I am new to it, I looked a little bit and it seems to have the same limitation, am I wrong?

**Comment by erikdubbelboer** [comment]
What changes do you want to make to the request? Changes to the body or headers? Why can't you make these changes before you send the request?

**Comment by melardev** [comment]
@erikdubbelboer Hi, don't think about average use, the reason why I need this is because I want to issue not so well-formed HTTP requests, this is very useful when writing security scanners, we need the ability to customize things that the frameworks won't do such as writing the following header:
`Header:Value` Or `Header:    Value`
Notice there lack or excessive spaces, this is on purpose, or we sometimes want to remove a piece of the request, for example, the Host header (which by the way it is a valid HTTP 0.9 request), or we may want to set a custom path that should not be normalized for example:
`/path/../another`
For this last example I figured out how to do it in standard HTTP package, but the others we just can not, except If we implement a Roundtripper from scratch which is asking a lot for such a basic task.

**Comment by erikdubbelboer** [comment]
I'm afraid that with fasthttp this isn't easy either.

What I would do is open a plain `net.Conn` to the host. Build a `fasthttp.Request` and use [`Request.WriteTo`](https://godoc.org/github.com/valyala/fasthttp#Request.WriteTo) to write the request to a `bytes.Buffer` modify that buffer and send it over the `net.Conn`. Then use [`Response.Read`](https://godoc.org/github.com/valyala/fasthttp#Response.Read) to read the response from the `net.Conn`. But you could do exactly the same with `net/http`.
