### ISSUE TITLE
Toggle header normalization for custom headers

### ISSUE THREAD

**Issue by mbdeveci** [valyala/fasthttp#863]
I am using fasthttp to make requests and I realized fasthttp normalizes headers, what would you suggest to be able to 
add header without normalizing, then keep working with normalizing.

Can i achieve a code like 
```
request.Header.DisableNormalizing()
request.Header.Set("x-very-custom-header", "value")
request.Header.EnableNormalizing()
```
or
```
request.Header.SetWithoutNormalizing("x-very-custom-header", "value")
```

**Comment by erikdubbelboer** [comment]
The first option would be the only way as `SetWithoutNormalizing` doesn't exist. Keep in mind that `EnableNormalizing()` didn't exist either, I just added it and pushed it to master. No idea why that method was never added while `DisableNormalizing()` was. I'll tag a release with it tomorrow.
