### ISSUE TITLE
[Question] fasthttp DefaultDialTimeout vs net/Dialer timeout

### ISSUE THREAD

**Issue by theblackturtle** [valyala/fasthttp#869]
Hi!
I see the net/Dialer timeout is around 3 minutes (https://golang.org/pkg/net/#Dialer) but `fasthttp.DefaultDialTimeout` is only 3 seconds. Is there anything different between these? 
Thanks.

**Comment by erikdubbelboer** [comment]
The default timeout for net/Dialer is 0 which means unlimited, so it's limited by what your OS will do. Apparently its around 3 minutes usually.

`fasthttp.DefaultDialTimeout` is a hard 3 seconds. But if you set your timeout to 0 in fasthttp to make it unlimited as well, the same OS limits apply.
