### ISSUE TITLE
socket.io support???

### ISSUE THREAD

**Issue by bbs3723216** [valyala/fasthttp#87]
socket.io support???

**Comment by valyala** [comment]
I think it would be better if socket.io support is provided via third-party packages like [go-socket.io](https://github.com/googollee/go-socket.io).

**Comment by valyala** [comment]
Created the corresponding feature request for `go-socket.io` - see https://github.com/googollee/go-socket.io/issues/127 .

**Comment by kataras** [comment]
@bbs3723216 do you want to port together the go-socket.io into a fasthttp compatible package?

**Comment by kataras** [comment]
@bbs3723216  if you still care about 'socket.io - LIKE'  for fasthttp, but only for websocket, you should look at kataras/iris/websocket I implemented a new library for that reason, just copy the code and use to your project :)

**Comment by kataras** [comment]
@bbs3723216  if you still care about 'socket.io - LIKE'  for fasthttp, but only for websocket, you should look at [kataras/iris/websocket](https://github.com/kataras/iris/tree/master/websocket) I implemented a new library for that reason, just copy the code and use to your project :)

**Comment by kirillDanshin** [comment]
@odiferousmint this is outside the scope of fasthttp. You can use any websocket library you like, for example, https://github.com/fasthttp/websocket, but for now we have no plans for embedding such protocols in the core project.

Cheers.
