### ISSUE TITLE
Custom metrics using expvar

### ISSUE THREAD

**Issue by alessiosavi** [valyala/fasthttp#870]
Hi Team,

Is possible to add some custom metrics to the one provided from `"github.com/valyala/fasthttp/expvarhandler"`?

The method is very simple to use, just declare an endpoint and pass the context as following:

```go

import "github.com/valyala/fasthttp/expvarhandler"
...
...
case "/stats":
    expvarhandler.ExpvarHandler(ctx)
```

Is there an example related to add some new custom metrics?

**Comment by erikdubbelboer** [comment]
This just uses the normal `expvar` golang package: https://golang.org/pkg/expvar/ You can use the functions in this package (`NewInt`, `NewString`, etc) to define new variables.
