### ISSUE TITLE
[client] Read only part of response

### ISSUE THREAD

**Issue by AntonKuzminRussia** [valyala/fasthttp#876]
Hello. How can i read only X bytes of server response body if i use fasthttp client? 
I found only ReadLimitBody() method of *Response, but it's wrong, as i understood. 
My problem is read responses of thousands servers. I do not known what they return to me in responses. It is may be a big responses in GBytes, and i do not want download them all. I want read some start bytes and analyse it.

**Comment by erikdubbelboer** [comment]
I'm afraid that this is currently not possible. There has been [some work](https://github.com/valyala/fasthttp/issues/622) on this, but it's not finished yet.
