### ISSUE TITLE
[help]close all net.Conn of fasthttp.Client before shut down the main program

### ISSUE THREAD

**Issue by amell93** [valyala/fasthttp#877]
hi :
    I want to close all net.Conn before my main program shut down to avoid send the RST flag to the server. now I find all net.Conn be store in the HostClient.conns, but it's not export. so how can I get all net.Conn to close it?

here is my program

```go
package main

import (
	"github.com/valyala/fasthttp"
)

func main() {
    client := fasthttp.Client{}
    for i := 0; i < 5; i++ {
        func() {
            req := fasthttp.AcquireRequest()
            defer fasthttp.ReleaseRequest(req)
            resp := fasthttp.AcquireResponse()
            defer fasthttp.ReleaseResponse(resp)
            req.SetRequestURI("http://www.baidu.com")
            _ = client.Do(req, resp)
        }()
    }
}
```
when this program exit, it send [RST,ACK] flag to she server.

**Comment by erikdubbelboer** [comment]
I'm afraid that this is currently not possible. I would be open to add a `CloseIdleConnections` method just like [`net/http.Client.CloseIdleConnections`](https://golang.org/pkg/net/http/#Client.CloseIdleConnections). A pull request would be welcome, otherwise I can probably add this soon.

**Comment by amell93** [comment]
hi:
    Thank you for your suggestion. I try to add a method to close all net.Conn. like this:
```go
package fasthttp


// CloseAllIdleConnections close all idle net.Conn and idle TLS net.Conn of the Client
func (c *Client) CloseAllIdleConnections()  {
	c.CloseIdleNonTLSConnections()
	c.CloseIdleTLSConnections()
}

// CloseIdleNonTLSConnections close all non-TLS net.Conn of the Client
func (c *Client) CloseIdleNonTLSConnections()  {
	c.mLock.Lock()
	defer c.mLock.Unlock()

	for _,hc := range c.m {
		for _,cc := range hc.conns {
			cc.c.Close()
		}
	}
}

// CloseIdleTLSConnections close all TLS net.Conn of the Client
func (c *Client) CloseIdleTLSConnections()  {
	c.mLock.Lock()
	defer c.mLock.Unlock()

	for _,hc := range c.ms {
		for _,cc := range hc.conns {
			cc.c.Close()
		}
	}
}
```
but, when I call CloseAllIdleConnections() method before my main program exit. it send RST to the server occasionally and I found there may be some problem in the method: func (c *Client) mCleaner(m map[string]*HostClient).
I think that when the code"if shouldRemove { delete(m, k) }" be called, it may be discard some *HostClient  instance so that some net.Conn be discarded.  but I'm the beginner of Go, so I 'm not sure this suspect. Can you analyze it for me?  
thank you very much !!!

**Comment by amell93** [comment]
@erikdubbelboer 
I add some debug information after the line:1447 in the client.go.
```go
			fmt.Println("line 1448: counts:", c.connsCount)
			fmt.Printf("c pointer: %p\n", c)
```

and there is my test code:
```go
package fasthttp

import (
	"sync"
	"testing"
	"time"
)

func TestClient_CloseIdleNonTLSConnections(t *testing.T) {
	client := Client{}

	var wg sync.WaitGroup
	for i := 0; i < 5; i++ {
		wg.Add(1)
		go func(wg *sync.WaitGroup) {
			defer wg.Done()
			req := AcquireRequest()
			defer ReleaseRequest(req)
			resp := AcquireResponse()
			defer ReleaseResponse(resp)

			req.SetRequestURI("http://www.baidu.com")
			_ = client.Do(req, resp)
		}(&wg)
		time.Sleep(100 * time.Microsecond)
	}

	wg.Wait()
	client.CloseAllIdleConnections()
	time.Sleep(1*time.Second)

}

```

there is output message :

line 1448: counts: 1
**c pointer: 0xc00038e000**
line 1448: counts: 1
**c pointer: 0xc000284300**
line 1448: counts: 2
c pointer: 0xc000284300
line 1448: counts: 3
c pointer: 0xc000284300
line 1448: counts: 4
c pointer: 0xc000284300

and sometimes, the output message is:

line 1448: counts: 1
c point: 0xc000041680
line 1448: counts: 2
c point: 0xc000041680
line 1448: counts: 3
c point: 0xc000041680
line 1448: counts: 4
c point: 0xc000041680
line 1448: counts: 5
c point: 0xc000041680

as you can see, the pointer of HostClient be changed.

**Comment by erikdubbelboer** [comment]
I have just pushed [a commit](https://github.com/valyala/fasthttp/commit/ae8b65fa6279eb1c654d837612f06894384935b1) that adds a `Client.CloseIdleConnections()` method.

**Comment by farss** [comment]
@erikdubbelboer why missing CloseIdleTLSConnections

**Comment by erikdubbelboer** [comment]
@farss `CloseIdleConnections` also closes TLS connections.

**Comment by farss** [comment]
```
func (c *Client) CloseIdleConnections() {
	c.mLock.Lock()
	for _, v := range c.ms {
		v.CloseIdleConnections()
	}
	c.mLock.Unlock()
}
```

**Comment by erikdubbelboer** [comment]
@farss oh wow you're completely right. I have fixed it in https://github.com/valyala/fasthttp/commit/245e7ecded9ac895b28f683596da823160216d4d. I will tag a new release next week.
