### ISSUE TITLE
why does http.go#writeBodyFixedSize unwrap the limited reader for sendfile??

### ISSUE THREAD

**Issue by KingDomPan** [valyala/fasthttp#878]
i get an error, when i use `ctx.SetBodyStream(file, size)` to send the size of file using zero copy ( size != file.length) 
but `writeBodyFixedSize` has discard the size param by no warp a limitreader for sendfile func ??

why ??? 

![image](https://user-images.githubusercontent.com/7733300/93492392-543fa580-f93d-11ea-8d3a-6128d356fb18.png)

**Comment by erikdubbelboer** [comment]
I have been trying to figure this out but I'm not sure. The code seems to be from an old commit that got modified later:
```go
	// Unwrap a single limited reader for triggering sendfile path
	// in net.TCPConn.ReadFrom.
```
I'm wondering if this is still relevant, but I'm guessing it still does as FS still uses it:
https://github.com/valyala/fasthttp/blob/380f00bfdba28d882bc5a01967cc3db12dfad0c2/fs.go#L499-L505

But I agree that it's bad that it just unwraps the `io.LimitedReader` without that being documented anywhere. I guess we should either fix it or document it.

**Comment by KingDomPan** [comment]
yes, FS uses it, but it always send a file (all file size) by a file path.

but, if i ues ctx.SetBodyStream(FD, size), it has no warp a LimitedReader

**Comment by KingDomPan** [comment]
if i warp a LimitedReader by, ctx.SetBodyStream( LimitedReader(FD, size), size). the LimitedReader has no close method to be invoked by framework to close my FD

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/b8b065b0d71acaa5c77f06e88db3fa4c3e86feb5
