### ISSUE TITLE
tryDial func doesn't handle timeout right

### ISSUE THREAD

**Issue by vpikulik** [valyala/fasthttp#879]
I'm making http Client that uses proxy to make some amount of http requests.
I use proxy as in example fasthttpproxy/http.go with one change: [fasthttp.Dial](https://github.com/valyala/fasthttp/blob/ae8b65fa6279eb1c654d837612f06894384935b1/fasthttpproxy/http.go#L29) is replaced by [DialTimeout](https://github.com/valyala/fasthttp/blob/ae8b65fa6279eb1c654d837612f06894384935b1/tcpdialer.go#L61), that uses [tryDial](https://github.com/valyala/fasthttp/blob/ae8b65fa6279eb1c654d837612f06894384935b1/tcpdialer.go#L305).

The problem that I have now: too many open files
`tryDial` finish correctly by timeout with correct error, but [this gorutine](https://github.com/valyala/fasthttp/blob/ae8b65fa6279eb1c654d837612f06894384935b1/tcpdialer.go#L334) works until `net.DialTCP` is not finished. And socket is opened.

As a solution I would suggest to use [Dialer.DialContext](https://godoc.org/net#Dialer.DialContext).
If it makes sense, I can create a pool request.

**Comment by erikdubbelboer** [comment]
Yes please make a pull request.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/56775f4d9fa114edf7f860abfe95294b58e61020
