### ISSUE TITLE
fasthttp request error EOF

### ISSUE THREAD

**Issue by hunght3101** [valyala/fasthttp#882]
Dear all,
I am a new in fasthttp in golang.
Now i am working in fasthttp with golang.
My problem when i try to use fasthttp client request.
My request :
```
req := fasthttp.AcquireRequest()
resp := fasthttp.AcquireResponse()
defer fasthttp.ReleaseRequest(req)
defer fasthttp.ReleaseResponse(resp)
req.SetMethod(method)
req.SetRequestURI(url)
fasthttp.Do(req, resp)
```

My config :
```
MaxConnsPerHost : 512
MaxIdleConnDuration : time.Duration(10) * time.Second,

```
I set this request in some function and use those function some time for call to other server(python SimpleHTTPServer)
My problem are when use this request for call server in the first time request success but from second time it issue error
`the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection`

I found issue below and try to fix follow suggest but my project still issue that error
https://github.com/valyala/fasthttp/issues/189

So i set timeout server python greater timeout of client fasthttp but still issue that error
```
def setup(self):
self.request.settimeout(self.timeout)
SimpleHTTPServer.SimpleHTTPRequestHandler.setup(self)
```
 
Please suggest for me to fix this error.
Thanks all!

**Comment by erikdubbelboer** [comment]
What happens when you use [Request.SetConnectionClose](https://godoc.org/github.com/valyala/fasthttp#Request.SetConnectionClose) to prevent a keep-alive connection from being used?

**Comment by hunght3101** [comment]
> What happens when you use [Request.SetConnectionClose](https://godoc.org/github.com/valyala/fasthttp#Request.SetConnectionClose) to prevent a keep-alive connection from being used?

I did this but still issue the same above error.
I set max duration in second is -1, is it that right ?
`MaxConnDuration : -1`

**Comment by hunght3101** [comment]
Sorry, i edited some where on my original post.

**Comment by hunght3101** [comment]
I fixed EOF error by response header `'Connection', 'close'` from server python.
Thanks all!
https://github.com/valyala/fasthttp/commit/a2e6d65e9dfc894bb8f2448def91f36f68564567

**Comment by Fenny** [comment]
@erikdubbelboer could you close this issue? Thanks
