### ISSUE TITLE
How do I get the number of request cookies?

### ISSUE THREAD

**Issue by kaibox-git** [valyala/fasthttp#883]
In my task I need to know the number of cookies in request. Unfortunally, I did not find any method for it. I only found existing unexported property:
https://github.com/valyala/fasthttp/blob/a995d43d9c0fbd726d0dcbaf2f104ff70ad794d8/header.go#L746
Is there a possibility to add a method like ctx.Request.Header.CookieCount on its base?

**Comment by erikdubbelboer** [comment]
You can use [`RequestHeader.VisitAllCookie`](https://godoc.org/github.com/valyala/fasthttp#RequestHeader.VisitAllCookie) to count the cookies like this:
```go
cookiesCount := 0
resp.Header.VisitAllCookie(func(_, _ []byte) {
    cookiesCount++
})
```

**Comment by kaibox-git** [comment]
Thank you!
