### ISSUE TITLE
ctx.Request.Header.Cookie('foo') is incorrect when the header `cookie: ` is lowercase and `DisableHeaderNamesNormalizing` is true

### ISSUE THREAD

**Issue by golopot** [valyala/fasthttp#884]
#### Description:
With `DisableHeaderNamesNormalizing: true`, fasthttp `ctx.Request.Header.Cookie("foo")` fails to read cookies when the header `Cookie: ` is written as `cookie: ` (lowercase). Since http header keys are case insensitive by spec, fasthttp should be able to read both `Cookie: ` and `cookie: ` correctly.

#### Code:
```go
package main

import (
	"fmt"
	"net"
	"time"

	"github.com/valyala/fasthttp"
)

func request(addr string, payload string) {
	conn, err := net.Dial("tcp", ":1234")
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(conn, payload)
}

func main() {
	server := fasthttp.Server{
		DisableHeaderNamesNormalizing: true,
		Handler: func(ctx *fasthttp.RequestCtx) {
			fmt.Println("cookie foo value:", string(ctx.Request.Header.Cookie("foo")))
			fmt.Println("cookie foo length:", len(ctx.Request.Header.Cookie("foo")))
			ctx.Success("text/plain", []byte("ok"))
		},
	}

	go server.ListenAndServe(":1234")
	time.Sleep(100 * time.Millisecond)
	request(":1234", "GET / HTTP/1.0\r\nCookie:foo=bar\r\n\r\n")
	request(":1234", "GET / HTTP/1.0\r\ncookie:foo=bar\r\n\r\n") // note the lowercase `cookie`
	time.Sleep(100 * time.Millisecond)
}
```
#### Expected:

```
$ go run app.go 
cookie foo value: bar
cookie foo length: 3
cookie foo value: bar
cookie foo length: 3
```
#### Actual:
```
$ go run app.go 
cookie foo value: bar
cookie foo length: 3
cookie foo value: 
cookie foo length: 0

**Comment by erikdubbelboer** [comment]
This is what `DisableHeaderNamesNormalizing` does. It makes sure all headers are normalized so they are always the same case. If you want this you shouldn't disable it.

**Comment by golopot** [comment]
Do you mean when I have this option set, I should be expecting that a call to the cookie API will be buggy?

**Comment by erikdubbelboer** [comment]
No not buggy, when you set `DisableHeaderNamesNormalizing = true` you are asking fasthttp to use the exact case of the headers, so that's what you get. If you don't know what case the headers are in, then I suggest keeping `DisableHeaderNamesNormalizing = false`.
