### ISSUE TITLE
what's the proper way to drop a connection?

### ISSUE THREAD

**Issue by gitmko0** [valyala/fasthttp#886]
there is a pesky hacker / spammer and i would like to drop his ip. DROP not return etc.

what's the proper way to drop a connection based?

**Comment by erikdubbelboer** [comment]
I would block his IP in your firewall and not in your application. That's what firewalls are made for.

If you want to drop the connection you can call [`ctx.SetConnectionClose()`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SetConnectionClose) and immediately return from your handler. That will send an empty response and drop the connection.

**Comment by gitmko0** [comment]
possible to drop the connection without sending any sort of response?

**Comment by gitmko0** [comment]
the reason i'm saying so is because my ip is fronted by cloudflare and i cant block cloudflare ip with iptables.

**Comment by kirillDanshin** [comment]
You can Hijack() the conn, and immediately return, as long as you don't have KeepHijackedConns enabled. If you do, you can Close() the conn in hijack handler manually. You can see a similar implementation in Gramework. Hope this helps

**Comment by gitmko0** [comment]
i did do a Hijack() 
```

var 


        hijackHandler = func(c net.Conn) {
                        return
                }


then...


                if BANN == 1 {
                ctx.Hijack(hijackHandler)
                 return
                }


```


didn't work as it returns 0 bytes instead of hanging the connection.
mind to share the code where gramework does it better?

**Comment by erikdubbelboer** [comment]
```go
if BANN == 1 {
	ctx.HijackSetNoResponse(true)
	ctx.Hijack(func(c net.Conn) {
		c.Close()
	})
	return
}
```

**Comment by gitmko0** [comment]
ok thx. that works.
