### ISSUE TITLE
Using RequestCtx with API.

### ISSUE THREAD

**Issue by Mikkkch** [valyala/fasthttp#887]
Hello, I am writing my own library for working with API and I need all requests to be made in some context. I know that net/http has a NewRequestWithContext, or WithContext(ctx context.Context) method that can be applied to an existing request, but compared to your framework, net/http is slow.  Is it possible to do the same thing using fasthttp? Perhaps you have already been asked this question, but I did not find anything similar on the Internet, and, reading the documentation, I also did not really understand using RequestCtx. If so far my question has remained incomprehensible to you, then here is an example of my code:
```golang
func (c *client) makeAndUnmarshalRequest(ctx context.Context, region, URL string, object interface{}) error {
	// checking
        // ...

	req, err := http.NewRequestWithContext(ctx, "GET",
		"https://" + region + ".api.riotgames.com" + URL, nil)

	if err != nil {
		return err
	}

	req.Header.Add("X-Riot-Token", c.APIKey)

	// limiting
        // ...

	resp, err := c.HTTPClient.Do(req)

	if err != nil {
		return err
	}

	// checking
        // ...

	body, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		return err
	}

	if err := resp.Body.Close(); err != nil {
		return err
	}

	return json.Unmarshal(body, object)
}
```

**Comment by erikdubbelboer** [comment]
I'm afraid fasthttp doesn't support context.

To be honest using context and fasthttp together feels weird to me. People should only really use fasthttp if they need their code to be so fast that they have to avoid any memory allocations to prevent GC spikes. But using context for anything will always cause allocations: https://play.golang.org/p/iO9nFxGcpJ- So I always feel that if you can afford to use context you probably don't need fasthttp.
