### ISSUE TITLE
could provid an API like  `(req *Request) SetBodyRaw(body []byte) `?

### ISSUE THREAD

**Issue by wangfakang** [valyala/fasthttp#891]
could provid an API `(req *Request) SetBodyRaw(body []byte)` ,  such as `(resp *Response) SetBodyRaw(body []byte) `  for seting  body and avoid copying it. In some scenarios, we need to set the request body directly, but using `request.SetBody(data.Bytes())` will additional data copies and memory allocation.

**Comment by erikdubbelboer** [comment]
A pull request would be welcome. Otherwise I'll try to add it this weekend.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/ce7b94fee9a8fd0fbb7996a63367b8237e9863c7
