### ISSUE TITLE
How to get duration between request arrived and response sent?

### ISSUE THREAD

**Issue by Thor-x86** [valyala/fasthttp#896]
Gin framework already implement this. However, when I'm using fasthttp I have no idea how to get the time when response just sent. Currently I'm heavily rely on `fasthttp.ServeFile(ctx, path)` function. Maybe there is any method for the duration? Thanks!

**Comment by erikdubbelboer** [comment]
You can use the [`Server.ConnState`](https://godoc.org/github.com/valyala/fasthttp#Server.ConnState) hook to track this. See for example: https://github.com/valyala/fasthttp/pull/793#issuecomment-622947064
