### ISSUE TITLE
error when serving connection "127.0.0.1:6607"<->"127.0.0.1:62252": read timeout with nothing read

### ISSUE THREAD

**Issue by Devying** [valyala/fasthttp#898]
```
2020/10/30 16:41:49 error when serving connection "127.0.0.1:6607"<->"127.0.0.1:62252": read timeout with nothing read
```

**Comment by gitmko0** [comment]
check your proxy server with telnet connection. most probably because backend server cannot be read

**Comment by erikdubbelboer** [comment]
@Devying we need a lot more information. What kind of server are you connection to, what config are you using, how often do you see this, what kind of traffic are you sending/receiving, which version of fasthttp are you using?

**Comment by Devying** [comment]
@gitmko0 thank you
