### ISSUE TITLE
Is there a way to limit transfer rate per host?

### ISSUE THREAD

**Issue by gitmko0** [valyala/fasthttp#899]
Trying to run a hosting platform here and wanting to limit each host domain name to certain transfer rate of e.g. 300kbps.

How can I do this with fasthttp? Sorry for asking. Hope it help others with same concern to limit attacks etc on fasthttp

**Comment by hiqsociety** [comment]
DefaultMaxConnsPerHost 512

per Host = per domain name or...? per server?

**Comment by gitmko0** [comment]
https://github.com/efarrer/iothrottler/blob/master/example_test.go
How to plug iothrottler into fasthttp with Dial? as in net/http

**Comment by erikdubbelboer** [comment]
The default example should work just fine, `fasthttp.RequestCtx` implements `io.Writer` so it should work fine with `pool.AddWriter`.
