### ISSUE TITLE
Why HostClient can't follow redirects to a different protocol?

### ISSUE THREAD

**Issue by nilbyli2020** [valyala/fasthttp#900]
RT: Why HostClient can't follow redirects to a different protocol?

```go
//        if c.IsTLS != bytes.Equal(req.uri.Scheme(), strHTTPS) {
//		return false, ErrHostClientRedirectToDifferentScheme
//	}
```

i comment this code, http and https both can work, so there is something error if the protocol different?

thank you.

**Comment by erikdubbelboer** [comment]
Because a HostClient has a pool of connections to a server:port combination. So when switching to a different scheme it will try to send https traffic to http port or the other way around. For more see: https://github.com/valyala/fasthttp/pull/800
