### ISSUE TITLE
Unexpected EOF client error

### ISSUE THREAD

**Issue by kasha13** [valyala/fasthttp#913]
```
func doRequest(url string) {
    req := fasthttp.AcquireRequest()
    resp := fasthttp.AcquireResponse()
    defer fasthttp.ReleaseRequest(req)
    defer fasthttp.ReleaseResponse(resp)

    req.SetRequestURI(url)

    err := fasthttp.Do(req, resp)
    if  err != nil { fmt.Print(err) }
}

func main() {
    doRequest("https://www.nbcnews.com/id/39870275/ns/technology_and_science-science/t/biodegradable-styrofoam-made-milk-clay\
/")
    return
}

```
unexpected EOF error is returned: _unexpected EOF_
fasthttp version - 1.17.0
OS - Ubuntu 18.04.2 LTS

wget console utility downloads this url successfully.
curl console utility provides following output _curl: (18) transfer closed with 78663 bytes remaining to read_
my C++ client based on libcurl successfully downloads this url.
is it possible to download this url using fasthttp?

**Comment by erikdubbelboer** [comment]
I'm afraid fasthttp only returns something with a correct http response. This website is returning a `Content-Length: 78655` header even though there isn't any body. This is an error.

If you really want to request this url you could do `req.Header.SetMethod(fasthttp.MethodHead)` to turn it into a HEAD request that doesn't have a body.
