### ISSUE TITLE
fasthttp request flask error

### ISSUE THREAD

**Issue by Huangsh17** [valyala/fasthttp#916]
fasthttp request flask error: tcp4 10.244.21.176:33706->10.12.30.1:3000: write: broken pipe

**Comment by erikdubbelboer** [comment]
We need a lot more information than that to see what is happening.

**Comment by Huangsh17** [comment]
fasthttp upload file times this error, the following is the sample code:
![image](https://user-images.githubusercontent.com/27496367/99928214-1e76cd00-2d83-11eb-94a3-8a62aa30c34f.png)

**Comment by Huangsh17** [comment]
> 我们需要比这更多的信息来了解正在发生的事情。
fasthttp upload file times this error, the following is the sample code:
![image](https://user-images.githubusercontent.com/27496367/99928233-33ebf700-2d83-11eb-98cb-0b80f2f387e6.png)

**Comment by erikdubbelboer** [comment]
What host are you connecting to? Looks like it doesn't like the formdata body and closes the transfer before it finishes.

**Comment by Huangsh17** [comment]
I connect to the intranet host, is interoperable, my program is mainly to upload files to the flask server

**Comment by Huangsh17** [comment]
> 您要连接到什么主机？看起来好像不喜欢formdata主体，并在完成传输之前将其关闭。

I connect to the intranet host, is interoperable, my program is mainly to upload files to the flask server

**Comment by erikdubbelboer** [comment]
Have you checked in the logs of the server you connect to? Maybe it's saying why it is closing the connection too early.
