### ISSUE TITLE
[Question/Bug] Can't make my handler time out

### ISSUE THREAD

**Issue by thomas-goncalves** [valyala/fasthttp#917]
Hello,

I've been using **fasthttp** for a few months to handle the API of my project and I've come to the point where I need to setup timeouts in my API to prevent abuses.

I thought I should do it using the *Timeout attributes of the fasthttp.Server class but it doesn't work and I don't know why.
Here is an example of what I'm trying to do:

`main.go`
```go
package main

import (
	"log"
	"time"

        "github.com/valyala/fasthttp"
)

// This handler just sleeps for a few seconds (which is more than the timeout I set)
func dummy(ctx *fasthttp.RequestCtx) {
	log.Printf("Hit dummy")
	time.Sleep(5 * time.Second)
	panic("should have timed out")
}

func main() {
	httpServer := fasthttp.Server{
                ReadTimeout:       1 * time.Millisecond,
                WriteTimeout:      1 * time.Millisecond,
                IdleTimeout:       1 * time.Millisecond,
		Handler:           dummy,
	}
        log.Printf("Starting listening on port 8080")
	log.Fatal(httpServer.ListenAndServe(":8080"))
}
```
`Output`
```
2020/11/20 11:47:34 Starting listening on port 8080
2020/11/20 11:47:43 Hit dummy
panic: should have timed out
```

To be clear, I would like to know if there is a way to make the request timeout when the handler takes too long directly from the fasthttp library or if I should handle it manually.

**Comment by erikdubbelboer** [comment]
Try using https://godoc.org/github.com/valyala/fasthttp#TimeoutHandler

But keep in mind that your handler won't be aborted as this is ([almost](https://golang.org/pkg/runtime/#Goexit)) not possible in Go. So your `panic` will still execute!

`Server.ReadTimeout` specifies how long the server waits to read data from the client. This timer is not active during your handler.

`Server.WriteTimeout` specifies how long the server waits between writes to the client. This timer is also not active during your handler and only starts after your handler is done.

`Server.IdleTimeout` specifies how long the server keeps idle connections open. Idle connections are connections that aren't sending or receiving and aren't in the middle of their handler running. So this also doesn't apply to what you want.

**Comment by ericreis** [comment]
@erikdubbelboer I'm sorry to reopen a discussion about this, but I think it is possible to stop the execution of the handler if done properly. I've managed to create this example that allows this but requires a workaround.

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/valyala/fasthttp"
)

func Handler(ctx context.Context, reqCtx *fasthttp.RequestCtx) {
	select {
	case <-time.After(2 * time.Second):
		log.Println("Finished")
		reqCtx.WriteString("Welcome!")
	case <-ctx.Done():
		log.Println("Timeout")
		reqCtx.TimeoutError("Timeout")
	}
}

type CustomHandler func(ctx context.Context, reqCtx *fasthttp.RequestCtx)

func timeout(h CustomHandler, timeout time.Duration, msg string, statusCode int) fasthttp.RequestHandler {
	return func(reqCtx *fasthttp.RequestCtx) {
		ctx, cancel := context.WithTimeout(reqCtx, timeout)
		defer cancel()

		ch := make(chan struct{}, 1)
		go func() {
			h(ctx, reqCtx)
			ch <- struct{}{}
		}()

		select {
		case <-ch:
		case <-ctx.Done():
			reqCtx.TimeoutErrorWithCode(msg, statusCode)
		}
	}
}

func main() {
	exec := func(h CustomHandler, reqCtx *fasthttp.RequestCtx) {
		timeout(h, 1*time.Second, "Request timed out", fasthttp.StatusRequestTimeout)(reqCtx)
	}
	requestHandler := func(ctx *fasthttp.RequestCtx) {
		switch string(ctx.Path()) {
		case "/":
			exec(Handler, ctx)
		default:
			ctx.Error("Unsupported path", fasthttp.StatusNotFound)
		}
	}

	srv := &fasthttp.Server{
		Handler: requestHandler,
	}

	log.Fatal(srv.ListenAndServe(":8080"))
}
```

I could not identify any major performance impact with this approach. However, it would be much more simple if the `TimeoutHandler` provided by `fasthttp` package worked with `ContextWithTimeout` instead of its timers. I've tried a similar approach without needing to create this `CustomHandler`, but I've hit a wall.

```go
package main

import (
	"log"
	"time"

	"github.com/valyala/fasthttp"
)

func Handler(ctx *fasthttp.RequestCtx) {
	select {
	case <-time.After(2 * time.Second):
		log.Println("Finished")
		ctx.WriteString("Welcome!")
	case <-ctx.Done():
		log.Println("Timeout")
		ctx.TimeoutError("Timeout")
	}
}

func main() {
	requestHandler := func(ctx *fasthttp.RequestCtx) {
		switch string(ctx.Path()) {
		case "/":
			Handler(ctx)
		default:
			ctx.Error("Unsupported path", fasthttp.StatusNotFound)
		}
	}

	srv := &fasthttp.Server{
		Handler: fasthttp.TimeoutHandler(requestHandler, 1*time.Second, "Request timed out"),
	}

	log.Fatal(srv.ListenAndServe(":8080"))
}
```

The `fasthttp.RequestCtx` is never canceled when it times out and, therefore, the `ctx.Done()` is never triggered. What are your thoughts on this?

**Comment by erikdubbelboer** [comment]
The problem with `TimeoutHandler` making the `RequestCtx.Done()` channel close on timeout is that it would require allocating a new channel for every request. To be honest `context` and `fasthttp` don't really match because `context` is bad for performance. I'm curious what your use case is and if you really need fasthttp for that?
