### ISSUE TITLE
Auto closing userdata values is not a good idea

### ISSUE THREAD

**Issue by derkan** [valyala/fasthttp#920]
Hi, as coded [here](https://github.com/valyala/fasthttp/blob/master/userdata.go#L66), userdata value is closed automatically if it supports `io.Closer`. 

I'm using [fiber](https://github.com/gofiber/fiber) with [godb](https://github.com/samonzeweb/godb). For godb I set `db` instance in userdata context and call `db.Clear()` for just clearing after response(in a middleware). But as `fasthttp` is magically calling `db.Close()` which drops db connection(which cost me an hour to detect why). To overcome this issue I have to reconnect to db for every request which is a big resource eater.

Also, it is hard to detect why connection is closed(as fasthttp does this magically). Magical things are not suitable for golang programming. We should make calling `Close()` optional.

**Comment by kirillDanshin** [comment]
@derkan hey

I wouldn't suggest keeping persistent connections inside UserValues. See [this example](https://play.golang.org/p/XNPoUzCCejZ), if you need persistent dependencies, I'd suggest providing them this way.
UserValues were created for request-wide values in the first place, not for service-wide dependencies

**Comment by derkan** [comment]
@kirillDanshin thanks for response. 

Actually db session is valid for that single request. It gets a clone of db interface object and and frees resources clone in a middleware. But, when fasthttp auto-calls `Close()`, it drops db connection from db server. 

To solve problem, I wrapped DB clone with a custom struct like ` type DBWrapper{db *godb.DB}` and used this object's instance in `UserValues`. Now, `fasthttp` cannot drop connection. Sample:

```go
// DBWrap wraps DB  because of https://github.com/valyala/fasthttp/issues/920
type DBWrap struct {
	DB *godb.DB
}
func New(config ...Config) fiber.Handler {
	// Set default config
	cfg := ConfigDefault

	// Override config if provided
	if len(config) > 0 {
		cfg = config[0]
		if cfg.ContextKey == "" {
			cfg.ContextKey = ConfigDefault.ContextKey
		}
	}

	if cfg.DB == nil {
		log.Fatal().Msgf("no db connection is defined")
		return nil
	}

	return func(c *fiber.Ctx) (err error) {
		// Don't execute the middleware if Next returns true
		if cfg.Next != nil && cfg.Next(c) {
			return c.Next()
		}

		db := cfg.DB.Clone()

		c.Locals(cfg.ContextKey, &DBWrap{DB: db})

		if err = c.Next(); err != nil {
			if db.CurrentTx() != nil {
				if err2 := db.Rollback(); err2 != nil {
					log.Error().Err(err2).Msgf("transaction rollback failed for %v ", err)
				}
			}
			return err
		}
		if db.CurrentTx() != nil {
			if err = db.Commit(); err != nil {
				log.Error().Err(err).Msg("transaction commit failed")
			}
		}
		if err = db.Clear(); err != nil {
			log.Error().Err(err).Msg("clearing db session failed")
		}
		return err
	}
}
```

You may close this issue.

**Comment by erikdubbelboer** [comment]
I'm afraid it's also something we can't change anymore as that would break backwards compatibility. Wrapping it in a struct like that is a good way to work around it.
