### ISSUE TITLE
my fasthttp client can only do 5000/s qps?

### ISSUE THREAD

**Issue by ohmygd** [valyala/fasthttp#921]
hi guys:
     
![image](https://user-images.githubusercontent.com/19659483/100321529-c8618e00-2ffd-11eb-9e21-922b520b4764.png)

![image](https://user-images.githubusercontent.com/19659483/100321563-d7e0d700-2ffd-11eb-92ff-ccd3ccfd4c61.png)
this is my client demo
my fasthttp version : v1.12.0
my machine : 16C 64G 
can anyone give me a favour?

**Comment by erikdubbelboer** [comment]
Try using `client.Do` instead of `client.DoTimeout` and see what effect it has. Besides that we would have to see a lot more of your code to determine what can be improved.
