### ISSUE TITLE
optimizing fasthttp

### ISSUE THREAD

**Issue by Arnold1** [valyala/fasthttp#923]
Hi,

I currently see about 500 open connections and between 500 and 1400 go routines. go_gc_duration_seconds (quaintly 1) = 12ms

will it have a new go routine per request or per connection in fasthttp?

what happens if too many requests are received by the server? I know it also depends on the number of concurrent requests vs. number of connections?
how to deal with that? should you limit the number of go routines in that case, any other ideas?

Thanks,
Arnold

**Comment by erikdubbelboer** [comment]
Normally you will have one goroutine per connection.

You could use [`Server.Concurrency`](https://godoc.org/github.com/valyala/fasthttp#Server.Concurrency) to limit the number of concurrent connections. Once the max number of connections is reached new connections will be closed without reading the request or writing a response.

**Comment by Arnold1** [comment]
ok, what will the client see if the server reaches max number of connections?

**Comment by erikdubbelboer** [comment]
The client will see the connection being terminated before it reads anything.
