### ISSUE TITLE
NotModified resets whole response

### ISSUE THREAD

**Issue by kiyonlin** [valyala/fasthttp#929]
This issue is related with gofiber/fiber#920 . 

Seems that fasthttp [invokes NotModified](https://github.com/valyala/fasthttp/blob/master/fs.go#L823) to reset response and send 304.

As the [rfc](https://tools.ietf.org/html/rfc7232#section-4.1) mentions
> A 304 response cannot contain a message-body; it is always terminated  by the first empty line after the header fields.

So my question is, should we reset the whole response when using [NotModified](https://github.com/valyala/fasthttp/blob/master/server.go#L1274)?

**Comment by erikdubbelboer** [comment]
It says in the function documentation `NotModified resets response and sets '304 Not Modified' response status code.`. I think that's pretty clear. We also can't just change the behavior as it would break things for people currently using it.
