### ISSUE TITLE
Apply reuseport on the static file server example?

### ISSUE THREAD

**Issue by ingolfured** [valyala/fasthttp#93]
I'm having a hard time using the `reuseport` to allow multiple processes to use port 80. I'm trying to finda an example where it's being used. Since my server is pretty much based on the file server example in this repo, I was hoping someone could assist me and show me how to add the `reuseport` part to that example. Thanks!

**Comment by valyala** [comment]
Just use [fasthttp.Serve](https://godoc.org/github.com/valyala/fasthttp#Serve) instead of [fasthttp.ListenAndServe](https://godoc.org/github.com/valyala/fasthttp#ListenAndServe). See [this example](https://godoc.org/github.com/valyala/fasthttp/reuseport#example-Listen) for details.
