### ISSUE TITLE
[Help Request] How to get client tcp conn after parsed response header in http 1.1 without tls

### ISSUE THREAD

**Issue by jim3ma** [valyala/fasthttp#930]
We need read http response body data to local file, for performance, we  use splice syscall to offload data copy to kernel.
So we need get client tcp conn after parsed response header.
Is there some available functions to do this ?

**Comment by erikdubbelboer** [comment]
I'm afraid this isn't possible. At the moment fasthttp will always read the full request before your handler is called so there is nothing to read from the TCP conn at that point.
