### ISSUE TITLE
Disable TCP keep-alive on fasthttp with go 1.12+

### ISSUE THREAD

**Issue by ajithcnambiar** [valyala/fasthttp#933]
(1) fasthttp server has TCP keep-alive disabled by [default](https://github.com/valyala/fasthttp/pull/427/files). And can be configured to enable it.

(2) Go lang 1.12+ [enabled](https://github.com/golang/go/commit/1abf3aa55bb8b346bb1575ac8db5022f215df65a#diff-78ad41a3943105ab2ef3bb7e1aa2bf14192d63840164736e12b665cf9252c088) TCP keep-alive by default. 

I understand that (1) happened before (2). But the issue is, when fasthttp is used on go 1.12+, TCP keep-alive is enabled and don't respect [Server.TCPKeepalive](https://github.com/valyala/fasthttp/blob/master/server.go#L264). A custom listener will solve the issue but it would be good if disabling keep-alive is supported. This is especially helpful in the scenario where port reuse is done, where TCP keep-alive is [not configurable](https://github.com/valyala/fasthttp/blob/d0dfbd4494632e4bf398d1c0098e4c389a1c4356/reuseport/reuseport.go#L34)  when the listener is created.

Please let me know thoughts.

**Comment by erikdubbelboer** [comment]
Fixed in https://github.com/valyala/fasthttp/commit/bd3513389dacf39e53f27acd64d48ca4dff05f6a
