### ISSUE TITLE
Does fasthttp support reverse proxy?

### ISSUE THREAD

**Issue by vkuznet** [valyala/fasthttp#934]
I'm interested to know if fasthttp can be used for reverse proxy, and if it does not, will fasthttp be a good choice for that with combination of `httputil.ReverseProxy` from net/http? If so, can someone provide a very basic example.

**Comment by erikdubbelboer** [comment]
See for example: https://github.com/valyala/fasthttp/issues/64#issuecomment-194880575
or https://github.com/valyala/fasthttp/search?q=reverse+proxy&type=issues
