### ISSUE TITLE
Error when serving connection: copied <x> bytes instead of <y> bytes

### ISSUE THREAD

**Issue by karlmcguire** [valyala/fasthttp#936]
I'm using `github.com/fasthttp/router` and my main code looks like this:

```go
r := router.New()

// registering handlers with r.GET(...)

L.Fatalln(http.ListenAndServe(":"+C.PORT, r.Handler))
```

Occasionally (it seems like once every 20-50 requests) I get error messages like this and the server responds with messed up HTML/CSS:

```
2021/01/01 17:45:14 error when serving connection "192.168.1.230:8080"<->"192.168.1.230:34034": copied 16246 bytes from body stream instead of 16234 bytes

2021/01/01 17:45:35 error when serving connection "192.168.1.230:8080"<->"192.168.1.230:34170": copied 16169 bytes from body stream instead of 16257 bytes
```

I've tried this on multiple machines and it happens on all of them.

**Comment by erikdubbelboer** [comment]
Can you share the code of your handler which has this issue? Without it, it will be impossible to find the bug.

**Comment by karlmcguire** [comment]
Here's a request handler I've been seeing the error pop up with:

```go
func GetHome(v *View, c *http.RequestCtx) {
	last := string(c.QueryArgs().Peek("last"))
	lastNum := &big.Int{}
	lastNum.SetString(last, 16)
	lastFloat := math.Float64frombits(lastNum.Uint64())
	a := &action.GET_POSTS{
		Ip:   realip.FromRequest(c),
		Last: lastFloat,
		Back: c.QueryArgs().GetBool("back"),
	}
	e := types.NewEvent(types.GET_POSTS, v.Token.Username, "ip="+a.Ip)
	s, err := M.GET_POSTS(e, a)
	if err != nil {
		panic(err)
	}
	if s.Err != "" {
		flash.Set(c, C.DOMAIN, C.FLASH_NAME, !C.DEV, []string{s.Err})
		c.Redirect("/", 302)
		return
	}
	c.WriteString(views.Template(v.Token, &views.Home{
		Posts: s.Posts,
		Err:   flash.Get(c, C.FLASH_NAME),
	}))
}
```

And here's the logs where I noticed the error:

![2021-01-01-192712_1920x1080_scrot](https://user-images.githubusercontent.com/4767637/103448456-0dfe2000-4c68-11eb-8392-e59764f389c7.png)

The error has been popping up from multiple request handlers and I'm not sure if that's the cause. I'd love to hear any input on what could be causing it.

**Comment by karlmcguire** [comment]
Yea, just got the error with another handler as well. It's happened on three separate machines so far.

**Comment by erikdubbelboer** [comment]
What is `http` in your code there? If it's `fasthttp` then I don't see how this handler could cause this error. The hander uses [`RequestCtx.WriteString`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx.WriteString) which just writes the bytes and doesn't do anything special. The error you are getting only happens when you use [`RequestCtx.SetBodyStream`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx.SetBodyStream) to set a body stream and the stream returns a different amount of bytes than specified in the `bodySize` argument. Are you using body streams anywhere in your handlers?

**Comment by karlmcguire** [comment]
Yes, I forgot to mention I usually alias `fasthttp` as `http`. I agree I don't see how any of my handlers could cause this error, that's why I posted here. 

Here's a recursive search within my project for `SetBodyStream`:

```
$ grep -r "SetBodyStream" .
Binary file ./main matches
$ rm ./main
$ grep -r "SetBodyStream"
$ 
```

So it's not any of my code calling `SetBodyStream` but it still appears in the binary... I think that's what that means. I'll check out `fasthttp/router` and see what they're doing.

**Comment by erikdubbelboer** [comment]
I see this can happen when the file changes. `FSHandler` caches file metadata. For files smaller than 8kb it also caches the contents in memory so they don't have any issues. But for files bigger than 8kb it might re-open the file handle. So if the file has changed the cached content-length and actual file size don't match anymore.

To be honest I'm not sure if we should fix this or not. Fixing it would probably mean doing a Stat call to see if the file has changed which hurts performance for the main use case, serving static files.

**Comment by karlmcguire** [comment]
That makes sense because I've been updating my CSS as the server is running. I'm just glad to know what is causing it, I wouldn't change anything. Thanks so much for your help!
