### ISSUE TITLE
If transfer-encoding header is present and empty, it's set to chunked

### ISSUE THREAD

**Issue by un000** [valyala/fasthttp#938]
Response example from the internet. I don't know why they do this, but they do.
```
< HTTP/1.1 200 OK
< access-control-allow-origin: *
< content-length: 975
< transfer-encoding:
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-headers: content-type, accept
< access-control-max-age: 10
< Content-Type: application/json
< Date: Tue, 05 Jan 2021 00:42:42 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
```

So this code thinks that body is chunked:
https://github.com/valyala/fasthttp/blob/master/header.go#L1842-L1845

And
https://github.com/valyala/fasthttp/blob/master/http.go#L1888
Fails with empty hex number.

I propose to skip this header if it's empty.

**Comment by erikdubbelboer** [comment]
Thanks for reporting this. Fixed in https://github.com/valyala/fasthttp/commit/70e00dc4f3b8c1ac01a2e82410c9f4d59248c099
