### ISSUE TITLE
fasthttp.FS seems to have no way to exit from a goroutine it starts

### ISSUE THREAD

**Issue by denisvmedia** [valyala/fasthttp#941]
I think I faced an issue that might be a bug here: https://github.com/valyala/fasthttp/blob/70e00dc4f3b8c1ac01a2e82410c9f4d59248c099/fs.go#L400-L406

The thing is that if I need to dynamically serve static files in multiple independent contexts (have multiple dynamic FS instances) I can only start a new instance, but never stop it.

Do you think we could have a way to tear down this routine? It can be context, stop or clean function. If you want I can also provide a PR, but I need to understand what's the solution you would prefer (if any).

**Comment by erikdubbelboer** [comment]
How about this way https://github.com/valyala/fasthttp/pull/942 ?

**Comment by sergerdn** [comment]
Hi all. Thank you for talking about this cool feature. I have one question. Why we started goroutine in any case and do not checks fs.CacheDuration?
```golang

	if fs.CacheDuration != 0 {
		go func() {
			// some code
		}()
	}
```

**Comment by denisvmedia** [comment]
CacheDuration is not expected to be 0:
https://github.com/valyala/fasthttp/blob/70e00dc4f3b8c1ac01a2e82410c9f4d59248c099/fs.go#L369

**Comment by sergerdn** [comment]
So, is there any other way to skip create goroutine?

**Comment by denisvmedia** [comment]
@erikdubbelboer thanks for you efforts!

I think here, a better naming for the Stop channel could be used. Maybe something like `CleanStop`.
https://github.com/valyala/fasthttp/pull/942/files#diff-743cdebe46d24f3bde38fa09b9f7aea780e43853a3bac3d85df9eec304a76dd8R287

Also, I think, the code could be slightly reduced if we could just create a dummy channel if it's empty (so, it will be never closed, which will fallback to the original behavior). In this case it will be possible to call clean in one place only.

**Comment by erikdubbelboer** [comment]
I have renamed it to `CleanStop`.

I rather have a little bit extra code if it means we don't have to allocate a dummy channel.

It's merged now, I'll tag a release on Monday.
