### ISSUE TITLE
Why my fasthttp client can only support 3000 concurrent

### ISSUE THREAD

**Issue by folivoramao** [valyala/fasthttp#947]
hi guys:

i set MaxConnsPerHost is equal to 10000 and use Do method to send POST request.
when concurrent is more than 3000, the tp95 is grew faster.
client demo(concurrentNum=3000, sndNum=10000):

```
wg := sync.WaitGroup{}
wg.Add(concurrentNum)
for i := 0; i < concurrentNum; i++ {
    go func(i int, wg *sync.WaitGroup) {
        for j := 0; j < sndNum; j++ {
            httpCall(ctx, j)
        }
        wg.Done()
    }(i, &wg)
}
wg.Wait()
```

```
//httpCall
c := &fasthttp.Client {
    MaxConnsPerHost: 10000,
    ReadTimeout: 15 * time.Second,
    WriteTimeout: 15 * time.Second,
}
c.Do(fasthttp.AcquireRequest(), fasthttp.AcquireResponse()).
```

my fasthttp version : v1.18.0
my machine : 4C 2.3GHz 16G 
can anyone give me a favour?

**Comment by moredure** [comment]
move your fasthttp.Client initialization block out of httpCall

**Comment by erikdubbelboer** [comment]
As @moredure says, it seems like you are creating a new `fasthttp.Client` for every call so you aren't reusing existing connections. Only create one `fasthttp.Client` and reuse that for each `c.Do` call to use keep-alive connections.

**Comment by folivoramao** [comment]
```
c := &fasthttp.Client {
    MaxConnsPerHost: 10000,
    ReadTimeout: 15 * time.Second,
    WriteTimeout: 15 * time.Second,
}
wg := sync.WaitGroup{}
wg.Add(concurrentNum)
for i := 0; i < concurrentNum; i++ {
    go func(i int, wg *sync.WaitGroup) {
        for j := 0; j < sndNum; j++ {
            httpCall(c, ctx, j)
        }
        wg.Done()
    }(i, &wg)
}
wg.Wait()
```


```
//httpCall
c.Do(fasthttp.AcquireRequest(), fasthttp.AcquireResponse()).
```

I use this method to send http requests, but it cannot have good concurrent performance.

**Comment by erikdubbelboer** [comment]
Your `httpCall` should at least reuse the request and response. So:
```go
req := fasthttp.AcquireRequest()
res := fasthttp.AcquireResponse()
c.Do(req, res)
fasthttp.ReleaseRequest(req)
fasthttp.ReleaseResponse(res)
```

What is `ctx`?
