### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by kataras** [valyala/fasthttp#95]
Hello, **First** I think it will be a good idea to create a repository like fasthttp-contrib or something like that, I already have ready my own sessions implementation (unique) for fasthttp, a (html/template,json,xml,...) renderer also for fasthttp and much more which are being used inside the iris. I want everyone to be able to use them with fasthttp even if they don't use iris web framework :)

**Secondly**, in the README.md add a section for Install with `go get -u github.com/valyala/fasthttp
` for new comers :) ( I don't want to a pr this small thing) 

Thanks you @valyala !

**Comment by valyala** [comment]
> I think it will be a good idea to create a repository like fasthttp-contrib or something like that.

This sounds great!

Let's just start with a `Third-party packages that use and/or enhance fasthttp` section in README. The section may be transformed into a `fasthttp-contrib` repository later.

BTW, did you consider using [quicktemplate](https://github.com/valyala/quicktemplate) in [iris](https://github.com/kataras/iris) additionally to `html/template`?

**Comment by kataras** [comment]
Yes at the iris-v3 users will be able to choose between html/template, yours quicktemplate and pongo2 template engine :) I'm looking your code the last 2 days in order to understand better how this is working. Ok then where do I post my packages for fasthttp ?

**Comment by kataras** [comment]
Done **Websocket**, **Sessions**, easy **Render** on the [fasthttp-contrib](https://github.com/fasthttp-contrib) organisation you are invited too, accept in order to make you admin also!! 

You can post them inside readme, they're ready :)

**Comment by valyala** [comment]
Cool!

Added [Related projects](https://github.com/valyala/fasthttp#related-projects) section to README

**Comment by kataras** [comment]
Good!

**Comment by valyala** [comment]
Closing the issue, since it looks like it has been addressed.

**Comment by kataras** [comment]
Ofcourse, Sorry for letting this open I though it was a good idea to be shown on the front for newcomers
