### ISSUE TITLE
potential memory leak in ResponseHeader.Reset()? maybe more

### ISSUE THREAD

**Issue by dunjut** [valyala/fasthttp#952]
`h.cookies` aren't zeroed before they are reset to 0 length, it seems these cookies are leaked until other cookies take their places or the whole header is dropped?
https://github.com/valyala/fasthttp/blob/master/header.go#L666

**Comment by erikdubbelboer** [comment]
That's on purpose. We keep the memory allocated so it can be reused for the next response. It will also reuse the slices inside the cookie when parsing. This way the garbage collector only has to do minimal work.
