### ISSUE TITLE
fasthttp.Client's response body is invalid in status ok

### ISSUE THREAD

**Issue by zacscoding** [valyala/fasthttp#955]
Hello :) 
I use fasthttp client `v1.19.0` and
code is:
```go
var (
    statusCode    int
    respBodyBytes []byte
)
err := retry.Do(ctx, c.backoff(), func(ctx context.Context) error {
    var (
        req          = fasthttp.AcquireRequest()
        resp         = fasthttp.AcquireResponse()
        deadline, ok = ctx.Deadline()
    )
    defer fasthttp.ReleaseRequest(req)
    defer fasthttp.ReleaseResponse(resp)
    buildRequest(req, method, uri, body, header)
    var err error
    if ok {
        err = c.cli.DoDeadline(req, resp, deadline)
    } else {
        err = c.cli.Do(req, resp)
    }
    if err != nil {
        return retry.RetryableError(err) // mark as a retryable
    }
    switch resp.StatusCode() / 100 {
    case 2, 4:
        // We receive 200 Status OK, But invalid response body bytes
        statusCode = resp.StatusCode()
        respBodyBytes = resp.Body()
        return nil
    default: // retry 300~399, 500~
        return retry.RetryableError(err)
    }
})
...
return StatusCode(statusCode), respBodyBytes, nil
```

We received `200 Status OK` but invalid response body bytes like below. 

```
e.g1) // missing "}"
{ "id": "UserID"

e.g2) // mixed another connection's body
{ "id": "UserID", "name": "User" }, "id":"UserID2"
```

When i checked our gateway's `byteSent` log, 142 bytes was sent from server,

but my fasthttp client's response body was 152 bytes :(

Is there any misuse in my code?

If u need more information, I will add some comments. Thx :)

**Comment by erikdubbelboer** [comment]
The return value of `resp.Body()` is invalid after you call `fasthttp.ReleaseResponse(resp)`. If you want to return the bytes you're going to have to make a copy first. When you release a response all bytes associated with it will be request for other requests. So the slice your function returns can already contain a partial read of the response body of the next request being handled in parallel.

**Comment by zacscoding** [comment]
@erikdubbelboer thx for reply 👍
