### ISSUE TITLE
gracefully shuts down bug.

### ISSUE THREAD

**Issue by alpha-baby** [valyala/fasthttp#958]
when invocate `func (s *Server) Shutdown() error`, should return header: `Connection: close`

if you sure it's a bug, i will commit a PR to fix it.

**Comment by erikdubbelboer** [comment]
Good idea. I think here:
https://github.com/valyala/fasthttp/blob/5661df8bbd4235f7bb537199be48884c866948d1/server.go#L2199
It should include `|| atomic.LoadInt32(&s.stop) == 1`

Can you test this and make a pull request? Thanks.

**Comment by kirillDanshin** [comment]
hey @alpha-baby, thanks for your report.

I'm concerned this one could introduce bugs in case of fasthttp service being behind ALB, 'cause the client would close the connection to ALB, then open it again unnecessarily, which will cause a spike in load during rollouts. I'd prefer having this under an option

**Comment by erikdubbelboer** [comment]
@kirillDanshin good point I didn't think of that. @alpha-baby can you add an option to the `Server` struct for this. Something like `CloseOnShutdown` so the default is `false` which doesn't break anything for current users.

**Comment by alpha-baby** [comment]
> @kirillDanshin good point I didn't think of that. @alpha-baby can you add an option to the `Server` struct for this. Something like `CloseOnShutdown` so the default is `false` which doesn't break anything for current users.

Ok,tomorrow i will commit new code.

**Comment by alpha-baby** [comment]
> hey @alpha-baby, thanks for your report.
> 
> I'm concerned this one could introduce bugs in case of fasthttp service being behind ALB, 'cause the client would close the connection to ALB, then open it again unnecessarily, which will cause a spike in load during rollouts. I'd prefer having this under an option

before i commit this [PR](https://github.com/valyala/fasthttp/issues/958), tcp connection also will be close when you call `func (s *Server) Shutdown() error`.

Closing connection source code in here: https://github.com/valyala/fasthttp/blob/master/server.go#L2303

**Comment by erikdubbelboer** [comment]
The connections being closed is what is supposed to happen. What people might not want is the connection from the client to the loadbalancer being terminated as well if there is a loadbalancer.
