### ISSUE TITLE
Handler error

### ISSUE THREAD

**Issue by gangstaJS** [valyala/fasthttp#96]
In main.go

```go

httpServer := fasthttp.Server{
				Name:            "sgo",
				Handler:         serv.HandleFastHTTP,
				ReadTimeout:     60 * time.Second,
				WriteTimeout:    60 * time.Second,
				WriteBufferSize: 32 * 1024,
				ReadBufferSize:  32 * 1024,
				Concurrency:     32000,
			}
```

Discrabe serv.HandleFastHTTP

```go

func HandleFastHTTP(ctx *fasthttp.RequestCtx) {

	defer utils.WTimeStart().Stop(string(ctx.Path()))

	path := bytes.TrimSuffix(ctx.Path(), textSlash)

	switch {
	case bytes.HasPrefix(path, urlApi):
		ApiHandle(bytes.TrimPrefix(path, urlApi), ctx)

	default:
		StaticHandle(ctx)
	}
}

```

Error:
`./main.go:68: cannot use serv.HandleFastHTTP (type func(*"sgo/vendor/github.com/valyala/fasthttp".RequestCtx)) as type "sgo-ui/server/vendor/github.com/valyala/fasthttp".RequestHandler in field value`

**Comment by valyala** [comment]
It looks like your code contains at least two `fasthttp` source code copies - one in `sgo/vendor` folder and another one in `sgo-ui/server/vendor` folder. Go treats them as unrelated packages, so the error appears.
Move `fasthttp` into a global `vendor` directory and delete other `fasthttp` copies across the code. This should fix the problem.

**Comment by kataras** [comment]
This was the issue I had too and I removed entirely vendors support for my package... it is dissapointment that the go authors don't design the package manager  to work better..

**Comment by gangstaJS** [comment]
@valyala  
`sgo` it is simlink to `sgo-ui`

**Comment by valyala** [comment]
@gangstaJS , see also [this topic in golang-dev](https://groups.google.com/d/topic/golang-dev/4FfTBfN2YaI/discussion) .
