### ISSUE TITLE
Incorrect timeout handling in tryDial in case of package drop

### ISSUE THREAD

**Issue by leonidboykov** [valyala/fasthttp#961]
## My use case

I've tried to access multiple hosts in the loop with goroutines (see sample code below). One of the servers dropped all requests with a simple iptables rule

    iptables -A INPUT -p tcp --dport 80 -j DROP

I've expected to receive timeout errors only from that server, however, the test code also failed to connect to a good URL. I've tried to replace the bad URL with http://httpbin.org/delay/8 (to test if this is a dialing issue), and I've got timeout errors only for that host.

<details>
<summary>Example code</summary>

```go
// testURLGood - test http server
// testURLBad - drops requests with iptable
// testCount = 3000
for i := 0; i < testCount; i++ {
	go func(i int) {
		testURL := testURLGood
		if rand.Intn(2) == 0 {
			testURL = testURLBad
		}

		c := fasthttp.Client{
			Dial: func(addr string) (net.Conn, error) {
				u, _ := url.Parse(testURL)
				return fasthttp.DialTimeout(u.Host, 5*time.Second)
			},
		}

		req := fasthttp.AcquireRequest()
		defer fasthttp.ReleaseRequest(req)

		req.SetRequestURI(testURL)

		resp := fasthttp.AcquireResponse()
		defer fasthttp.ReleaseResponse(resp)
		if err := c.DoTimeout(req, resp, 5*time.Second); err != nil && testURL == testURLGood {
			log.Println(testURL, resp.StatusCode(), err, i+i)
		}
	}(i)
}
```
</details>

## Fix I've tried

If I replace (in sample code above)

```go
return fasthttp.DialTimeout(u.Host, 5*time.Second)
```

with

```go
return net.DialTimeout("tcp", u.Host, 5*time.Second)
```

everything works as expected.

I'm not sure but perhaps `cancel_ctx` [in tryDialer](https://github.com/valyala/fasthttp/blob/c2542e5acf973cb1a2ab82d74dcb66f7afcb968b/tcpdialer.go#L305-L342) has to be called in case of timeout, caused by a timer.

**Comment by erikdubbelboer** [comment]
I think I found the race condition causing this and fixed it here: https://github.com/valyala/fasthttp/commit/ed1cedd51e07e6ddedfe18d860bb9e837f133c26
I will tag a new release on Monday. Can you check if this solves your issue?

**Comment by leonidboykov** [comment]
@erikdubbelboer thanks for the fast reply! I've tried this fix on my sample test and looks like it solves my issue. I will try it again in a real project on Monday and let you know if my issue is really fixed.
