### ISSUE TITLE
I'm using net/https for the ssl termination and fasthttp as a reverse proxy http for other purposes. How to map them without using tcp or UDS?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#963]
1. how do i combine net/http and pass to fasthttp directly?

2. also how do i pass fasthttp to another fasthttp directly? i've written two fasthttp programs and connect them with UDS mostly. would like to be able to transfer req and resp without much code rewriting, maintaining them "separately". I tried the memconn but it was using too much ram so i dropped it.

```go
func main() {

                ln, err := net.Listen("tcp4", ":87")
                if err != nil {
                        log.Fatalf("error in net.Listen: %s", err)
                }


                go func() {
                        if err := fasthttp.ListenAndServeUNIX("/tmp/httpserver.socket", os.FileMode(int(0777)),ReverseProxyHandler); err != nil {
                                //memconn.Listen("memb", "localhost")
                                //lis, _ := memconn.Listen("memb", "localhost")
                                //if err := fasthttp.Serve(lis,ReverseProxyHandler); err != nil {
                                log.Fatalf("error in fasthttp server: %s", err)
                        }
                }()

}
```

in net/http program
```go
func main() {
// ...

        //fmt.Printf("hello")
        server.ListenAndServeTLS("", "")
}


// Serve a reverse proxy for a given url
func serveReverseProxy(res http.ResponseWriter, req *http.Request) {
        url, _ := url.Parse("unix:///tmp/fasthttp.socket")



        dialer := (&net.Dialer{
                KeepAlive: 10 * time.Second,
                Timeout:   10 * time.Second,
        }).Dial

        socketPath := "/tmp/fasthttp.socket"
        dialer = func(network, address string) (net.Conn, error) {
                return net.Dial("unix", socketPath)
        }
        url.Path = ""
        url.Host = "domain-sock"
        url.Scheme = "http"
        //      }
        // step: create the reverse proxy
        proxy := httputil.NewSingleHostReverseProxy(url)

//...
        proxy.Transport = &http.Transport{
                Dial: dialer,
                //              TLSClientConfig: &tls.Config{
                //                      InsecureSkipVerify: r.config.SkipUpstreamTLSVerify,
                //              },
                //              DisableKeepAlives: !r.config.UpstreamKeepalives,
        }



}
```

**Comment by erikdubbelboer** [comment]
Is this running in the same process or separate processes? Maybe you can use https://pkg.go.dev/github.com/valyala/fasthttp/fasthttpadaptor ?

**Comment by hiqsociety** [comment]
Same process, how do I pass w and r to fasthttp?


        mux := http.NewServeMux()
        mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                   proxy.ServeHTTP(w, r)
                   //want to use fasthttp to handle the requests.

        })




        server := &http.Server{
                Addr:    ":80",
                Handler:  mux,
        }
        server.ListenAndServe("", "")

**Comment by erikdubbelboer** [comment]
I'm afraid that that is very difficult. fasthttp handlers want a `fasthttp.RequestCtx` which you can't just easily build from a `http.Request`. They also write a full response which is not compatible with `http.ResponseWriter`.

Why would you ever want to do this? This will make things so slow that I don't see any reason why to use fasthttp?

**Comment by hiqsociety** [comment]
net/http is for the ssl terminator / https. the example i've shown is only a section.

for fasthttp is used in other processing services. instead of using UDS socket (which I'm using now), would like to convert the above to switch to fasthttp. Other than changing w, r or "transferring" w,r. how can i get the ctx to fasthttp then? Can you provide an example to modify the code? I've seen other examples of wrapping the handlefunc or handler BUT i dunno how to pass the ctx over to fasthttp and pass it back to net/http.

**Comment by erikdubbelboer** [comment]
Why use `net/http` for SSL termination, why not use fasthttp for that as well?

`fasthttpadaptor` is to call `net/http` handlers from fasthttp, not the other way around as you seem to want. Is it not just possible for you to rewrite those `fasthttp` handlers to normal `net/http` handlers and not use `fasthttp` at all? Seems like `fasthttp` is really not suited for you use case.

Calling a fasthttp hander from a net/http server is something that is almost impossible to do. The only way I can think of is using [`net/http/httputil.DumpRequest`](https://golang.org/pkg/net/http/httputil/#DumpRequest) to get the whole HTTP request. Then using [`fasthttp.Request.Read`](https://pkg.go.dev/github.com/valyala/fasthttp#Request.Read) to read it into a `fasthttp.Request`. And then using that request to call [`fasthttp.RequestCtx.Init`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx.Init) to get a `fasthttp.RequestCtx` that you can pass to the handler. But this is really slow.

**Comment by hiqsociety** [comment]
because fasthttp is only 1.1 there's a http2 now, will wait for it. thx!
