### ISSUE TITLE
Resolver usage

### ISSUE THREAD

**Issue by melardev** [valyala/fasthttp#964]
Hi, I was reading a little bit fasthttp source code to know how to use a custom resolver, I found there was a resolver field in TCPDialer, which was introduced in: https://github.com/valyala/fasthttp/pull/689

However, my example does not work, any hint why?

```go

	req := fasthttp.AcquireRequest()
	req.SetRequestURI("https://google.com")
	req.Header.Add("User-Agent", "Test-Agent")
	resp := fasthttp.AcquireResponse()
	client := &fasthttp.Client{}
	defaultDialer := &fasthttp.TCPDialer{
		Concurrency: 1000,

		Resolver: &net.Resolver{
			PreferGo:     false,
			StrictErrors: false,
			Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
				fmt.Println("Inside TcpDialer")
				d := net.Dialer{}
				return d.DialContext(ctx, "udp", "127.0.0.1:53")
			},
		},
	}

	client.Dial = func(addr string) (net.Conn, error) {
		fmt.Println("Inside Dial")
		return defaultDialer.Dial(addr)
	}

	err := client.Do(req, resp)
	if err != nil {
		panic(err)
	}

	bodyBytes := resp.Body()
	fmt.Println(string(bodyBytes))

```

Inside TcpDialer is never executed, I debugged the code on Windows, and it seems the Dial is never taken into account, the resolution happens lookup_windows.go::Resolver::lookupIP, which we can not override and the result is retrieved in lookup_windows.go::Resolver::lookupIP::syscall.GetAddrInfoW.
A raw syscall without taking into account my Dial implementation.

**Comment by melardev** [comment]
Ok, I compiled the snippet for Linux and it works, I have not debugged the Linux snippet so I don't know what makes it work, but I guess this can be considered a bug on Windows.

**Comment by erikdubbelboer** [comment]
Sounds like this is not a fasthttp issue, but an issue in Go itself in `net.Resolver` on Windows. https://golang.org/pkg/net/ mentions `On Windows, the resolver always uses C library functions, such as GetAddrInfo and DnsQuery.` so what you are trying doesn't seem supported.
