### ISSUE TITLE
Permission denied on cert keys when setting up TLS 

### ISSUE THREAD

**Issue by l1ving** [valyala/fasthttp#966]
I'm entirely new to Go so apologies if I'm missing something here. You can find my programs code at https://github.com/l1ving/heartbeat/blob/cbb56d65f766892c6be85af95bb598da5be8a5f4/main.go#L39

I get this error here when trying to run fasthttp with tls
```
liv@living-heartbeat:~/heartbeat$ ./heartbeat -addr=135.181.98.249:80 -tls -key=/etc/letsencrypt/live/hb.l1v.in/privkey.pem -cert=/etc/letsencrypt/live/hb.l1v.in/fullchain.pem
2021/02/10 09:50:31 - Error in ListenAndServe: cannot load TLS key pair from certFile="/etc/letsencrypt/live/hb.l1v.in/privkey.pem" and keyFile="/etc/letsencrypt/live/hb.l1v.in/fullchain.pem": open /etc/letsencrypt/live/hb.l1v.in/privkey.pem: permission denied
```

My `privkey.pem` / `fullchain.pem` permissions:

```
liv@living-heartbeat:~/heartbeat$ sudo ls -la /etc/letsencrypt/live/hb.l1v.in
total 12
drwxr-xr-x 2 root root 4096 Feb  9 22:23 .
drwx------ 3 root root 4096 Feb  9 22:23 ..
lrwxrwxrwx 1 root root   33 Feb  9 22:23 cert.pem -> ../../archive/hb.l1v.in/cert1.pem
lrwxrwxrwx 1 root root   34 Feb  9 22:23 chain.pem -> ../../archive/hb.l1v.in/chain1.pem
lrwxrwxrwx 1 liv  liv    38 Feb  9 22:23 fullchain.pem -> ../../archive/hb.l1v.in/fullchain1.pem
lrwxrwxrwx 1 liv  liv    36 Feb  9 22:23 privkey.pem -> ../../archive/hb.l1v.in/privkey1.pem
-rw-r--r-- 1 root root  692 Feb  9 22:23 README
```

The permissions of the files they're linked to:

```
liv@living-heartbeat:~/heartbeat$ sudo ls -la /etc/letsencrypt/archive/hb.l1v.in
total 24
drwxr-xr-x 2 root root 4096 Feb  9 22:23 .
drwx------ 3 root root 4096 Feb  9 22:23 ..
-rw-r--r-- 1 root root 1826 Feb  9 22:23 cert1.pem
-rw-r--r-- 1 root root 1586 Feb  9 22:23 chain1.pem
-rwxr--r-- 1 liv  liv  3412 Feb  9 22:23 fullchain1.pem
-rwx------ 1 liv  liv  1708 Feb  9 22:23 privkey1.pem
```

`liv` is the user that I am running Heartbeat's daemon under with fasthttp.

I'm not quite sure what went wrong here. My user owns and has read permissions to both the original file and symlinks.

**Comment by erikdubbelboer** [comment]
Sorry but this has nothing to do with fasthttp. The `permission denied` error clearly shows that something is wrong with your permissions. What happens when you run `cat /etc/letsencrypt/live/hb.l1v.in/privkey.pem`?

**Comment by l1ving** [comment]
I'm now using a file with the default permissions, which is 777 and owned by root for the privkey.pemm, and 600 owned by root for privkey1.pem

```
liv@living-heartbeat:~/heartbeat$ cat /etc/letsencrypt/live/hb.l1v.in/privkey.pem
cat: /etc/letsencrypt/live/hb.l1v.in/privkey.pem: Permission denied
```


I did post the previous permissions above in the `ls` outputs

**Comment by l1ving** [comment]
I fixed the permissions and now I have what I think is *actually* a fasthttp issue (error on my end, probably)

```
liv@living-heartbeat:~/heartbeat$ ./heartbeat -addr=135.181.98.249:80 -tls -key=/home/liv/certs/privkey.pem -cert=/home/liv/certs/fullchain.pem
2021/02/10 20:00:26 - Error in ListenAndServe: cannot load TLS key pair from certFile="/home/liv/certs/privkey.pem" and keyFile="/home/liv/certs/fullchain.pem": tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched
```

After switching said inputs, it launches but I get

```
liv@living-heartbeat:~/heartbeat$ ./heartbeat -addr=135.181.98.249:80 -tls -cert=/home/liv/certs/privkey.pem -key=/home/liv/certs/fullchain.pem    
2021/02/10 20:01:40 error when serving connection "135.181.98.249:80"<->"My IP Address:43908": tls: first record does not look like a TLS handshake
```

I'm just opening `http://hb.l1v.in` in a browser, same thing happens with `https://hb.l1v.in`

**Comment by erikdubbelboer** [comment]
```
tls: first record does not look like a TLS handshake
```
This is what you usually get when you send a `http` request to a `https` endpoint.

From your code it seems like your server is listening on port 6060? So I would expect you to use `https://hb.l1v.in:6060/`. Do you maybe have a loadbalancer in front that is already terminating the tls connection so your fasthttp server doesn't even need tls?

**Comment by l1ving** [comment]
No, I'm passing port 80 in my program args as you can see. I just have 6060 as the default if it isn't set. 

I don't believe I'm using any sort of load balancing, I don't know how to do that.

**Comment by l1ving** [comment]
Turns out I'm really stupid. It works when running on port 443

**Comment by l1ving** [comment]
Thanks for your patience
