### ISSUE TITLE
is it possible implement http.ResponseWriter interface on RequestCtx ?

### ISSUE THREAD

**Issue by fxding** [valyala/fasthttp#97]
Hi
Is it possible to implement http.ResponseWriter interface on RequestCtx ? or is there a method to get a ResponseWriter instance.

I want to use RequestCtx on some libs wrote for http.ResponseWriter.
like [render](https://github.com/unrolled/render)

Thank you

**Comment by kataras** [comment]
@fxding  There is already a render package for fasthttp which is supporting gzip compression also :) take a look [here](https://github.com/fasthttp-contrib/render), you can take a look also inside [iris framework's source code](https://github.com/kataras/iris) to see how things works with fasthttp :)

**Comment by fxding** [comment]
Thank you @kataras , that is what I'm looking for, I will take a look it :)

but if I want to use fasthttp with other libs created for http.ResponseWriter, I need to create a fasthttp version :(

**Comment by kataras** [comment]
Or write an issue here and I will respond again :)

**Comment by fxding** [comment]
ok, thanks for you help @kataras  :)

**Comment by kataras** [comment]
@fxding  you're welcome!

**Comment by valyala** [comment]
> Is it possible to implement http.ResponseWriter interface on RequestCtx ?

@fxding , there is also [fasthttpadaptor](https://godoc.org/github.com/valyala/fasthttp/fasthttpadaptor) for converting `net/http` request handlers to `fasthttp` request handlers.

**Comment by fxding** [comment]
that's great, thanks @valyala, I will  check it
