### ISSUE TITLE
How do I do net/http equivalent Transport: in Client{} ?

### ISSUE THREAD

**Issue by hiqsociety** [valyala/fasthttp#971]
Trying to use this :
github.com/akutz/memconn

Backend: // working fine
https://pastebin.com/uteGXWYy

Server: // Transport doesnt work obviously. How do I work around?
https://pastebin.com/e2fbP82s

**Comment by erikdubbelboer** [comment]
Not sure why you have it commented out, but this should probably work:
```go
fasthttp.Client{
                Dial: func(addr string) (net.Conn, error) {
                        return memconn.Dial("memb", "AAA")
                },
}
```
You can ignore `Client.Addr` as you aren't using in in the `Dial` anyways.
