### ISSUE TITLE
Ability to serve embed.FS files

### ISSUE THREAD

**Issue by night-codes** [valyala/fasthttp#974]
Will there be a native fasthttp way (like .ServeFile) to share filesystems of embedded files, support for which came in go 1.16?

https://golang.org/doc/go1.16#library-embed

**Comment by erikdubbelboer** [comment]
A pull request for that would be very welcome. Maybe add a `FS fs.FS` member to `fasthttp.FS` and if it's not nil use `FS.open` instead of `os.Open`.

**Comment by lukekim** [comment]
@erikdubbelboer with that solution, how might it handle `mustCompress`? Or just not support it for embedded content?

**Comment by erikdubbelboer** [comment]
Yeah I guess that's not supported then.

**Comment by leonklingele** [comment]
Anyone working on this atm? Else I'll give it a try on the weekend.
