### ISSUE TITLE
Export info about HostClient.connsCount

### ISSUE THREAD

**Issue by kiyonlin** [valyala/fasthttp#976]
I'm [implementing Fiber http client](https://github.com/gofiber/fiber/pull/1177) on top of fasthttp HostClient, and I want to reuse HostClient too. But I can't clean them because I have no access to [connsCount](https://github.com/valyala/fasthttp/blob/master/client.go#L740). So can we export this information?

PS I can make the PR.

**Comment by kiyonlin** [comment]
@erikdubbelboer Could you please take a look 😃 ?

**Comment by erikdubbelboer** [comment]
Can you please make a pull request to add a function that returns this number? Thanks.

**Comment by kirillDanshin** [comment]
maybe it's better to provide a Reset() method to allow reusing HostClient? 🤔

**Comment by kiyonlin** [comment]
> maybe it's better to provide a Reset() method to allow reusing HostClient? 🤔 

But when to call Reset() if there are current connections?
