### ISSUE TITLE
Mocking response body for unit tests

### ISSUE THREAD

**Issue by saartamir** [valyala/fasthttp#982]
Hi All,
I'm pretty much beginner in Go and I'm trying to build a test for function that uses fasthttp to send API request to Slack and check the response. The problem is that I can't find how to mock/stub response body. I mocked Response.Body() but because I need to use AcquireResponse, it overrides my mocked response object and I get nil body.
Someone maybe can help/navigate me to the problem?
Appreciate your help!

**Comment by erikdubbelboer** [comment]
You could either read a response from a HTTP request string: https://github.com/valyala/fasthttp/blob/c3cd5e15545a0ba0f4cd4eb692a73274a099ea3c/http_test.go#L22-L26

Or use an in-memory server that you can connect to and get the response form: https://github.com/valyala/fasthttp/blob/c3cd5e15545a0ba0f4cd4eb692a73274a099ea3c/client_test.go#L160-L181

**Comment by saartamir** [comment]
@erikdubbelboer thanks for the help! but I'm not sure we quite understood each other.
I have a function called "SendSlackNotification(webhookUrl string, msg string) error" which use fasthttp to send POST request to given url with given msg, checks that response.body gives me "ok" and return error if not.
In the example you gave me the in memory listener, I need to create my own Client and use it, but then function uses different client (I'm not sending the client in the function). How can I solve this?

**Comment by erikdubbelboer** [comment]
Then how do you configure the URL the function send this to? You could also build a real listener instead of an in-memory one and send it that URL.
