### ISSUE TITLE
TCP question i got while learning Go fasthttp framework

### ISSUE THREAD

**Issue by extems** [valyala/fasthttp#983]
I am a new developer who's learning about this framework, i want to play a little with an example given by the developer of that framework and see how to use this tool but when I start the application it says that I have to write on the cmd:

    -addr=tcp.addr.to.listen:to

I wrote on the console:

    "-addr=0.0.0.0:80" 

And an error displays on the console:

    2021/02/25 21:29:54 Error in ListenAndServe: listen tcp4: address default: missing port in address

I understand that the error says that I am not inserting any port, but I'm inserting one, the port 80.

I know that i am inserting an existing port because i follow the next commands:

    1.    Find a listening TCP port on my windows system
    2.    Copy and paste it on the "tcp.addr.to.listen:to"

I write "netstat -a" on the console, copy the "0.0.0.0:80" TCP port that is on listening mode and paste it on "tcp.addr.to.listen:to" but that error comes out. What did I have misunderstood?

**Comment by erikdubbelboer** [comment]
Which of the example are you trying? I don't have a windows machine but maybe you aren't allowed to listen on port 80, can you try 8080? Can you try removing the `""` around your argument? Can you try `-addr 0.0.0.0:8080` without the `=` (I'm not sure what windows supports these days).

**Comment by extems** [comment]
I managed to make things work.

    1. I created a mod file inside the helloworldserver.go directory writing  "go mod init helloworldserver"
    2. I initiated port 140 writing -addr 0.0.0.0:140 on cmd as you said
    3. I opened google, write http://localhost:140 and it worked. 
 
Thanks for the help!
