### ISSUE TITLE
Respose 403

### ISSUE THREAD

**Issue by po4atok** [valyala/fasthttp#984]
Hello,
why does this code print 403 status code:

```
url := "https://mobile.market.yandex.net/market/blue/v2.1.5/redirect?contents=REDIRECT_CATALOG%2CREDIRECT_MODEL%2CREDIRECT_SEARCH%2CREDIRECT_SKU&fields=MODEL_DEFAULT_OFFER%2CSTANDARD&redirect_types=CATALOG%2CMODEL%2CSEARCH%2CSKU%2CVENDOR&text=twix&geo_id=10851&uuid=26141853636f44838654ac3bfd642543"
req := fasthttp.AcquireRequest()
res := fasthttp.AcquireResponse()
req.SetRequestURI(url)
req.Header.SetMethod("GET")
defer fasthttp.ReleaseRequest(req)
defer fasthttp.ReleaseResponse(res)
client := fasthttp.Client{}
err := client.Do(req, res)
if err == nil {
	fmt.Println(res.StatusCode)
}
```
python code print status 200:
```
url = "https://mobile.market.yandex.net/market/blue/v2.1.5/redirect?contents=REDIRECT_CATALOG%2CREDIRECT_MODEL%2CREDIRECT_SEARCH%2CREDIRECT_SKU&fields=MODEL_DEFAULT_OFFER%2CSTANDARD&redirect_types=CATALOG%2CMODEL%2CSEARCH%2CSKU%2CVENDOR&text=twix&geo_id=10851&uuid=26141853636f44838654ac3bfd642543"
resp = requests.get(url)
print(resp.status_code)
```

Thanks

**Comment by dgrr** [comment]
Hello.

I checked and you are right... But I am neither able to access it from my web browser. So, I don't think is fasthttp's problem. It's weird to see that python is able to access it. Maybe Yandex checks the integrity of the client. No idea so far.

**Comment by erikdubbelboer** [comment]
I'm getting `403 Forbidden` with curl. This is definitely the website doing some checks (maybe on User-Agent) and has nothing to do with fasthttp. You could try using [`req.Header.SetUserAgent("...")`](https://pkg.go.dev/github.com/valyala/fasthttp#RequestHeader.SetUserAgent) to set a different user agent.
