### ISSUE TITLE
How do i refactor "ioutil.ReadAll(r.Body)" from nethttp?

### ISSUE THREAD

**Issue by extems** [valyala/fasthttp#986]
i know that i can refactor r.Body to:

        ctx.PostBody()

But when I try to refactor ioutil.ReadAll nothing seems to work. I tought writing:

         "Reponse.Body(ctx.PostBody())" 

Will do the refactor but an error displays above "RESPONSE" saying "undeclared name: Reponsecompiler(UndeclaredName)". What am I doing wrong?

**Comment by dgrr** [comment]
Are you looking for [this](https://pkg.go.dev/github.com/valyala/fasthttp#Response.SetBody)?

**Comment by erikdubbelboer** [comment]
You don't have to `ioutil.ReadAll`. With `net/http` you have to do this because `r.Body` is an `io.Reader`. But with `fasthttp` `ctx.PostBody()` is already a `[]byte` just like `ioutil.ReadAll` would return.

So `body, err := ioutil.ReadAll(r.Body)` would become `body := ctx.PostBody()`

**Comment by extems** [comment]
Thank you so much for supporting this framework!! This worked for me
