### ISSUE TITLE
Fragment trapped into Host() of URI

### ISSUE THREAD

**Issue by moredure** [valyala/fasthttp#987]
In case of links such as http://example.com#fragment

**Comment by moredure** [comment]
http://sbnonline.com%E2%80%8B/shaping-my-entrepreneurial-destiny-a-ceo-x2019-s-view-from-the-2010-ernst-amp-young-strategic-growth-forum/

such links as %E2%80%8B trapping into host

**Comment by erikdubbelboer** [comment]
Can you post a code example of what you mean?

**Comment by moredure** [comment]
@erikdubbelboer , sure!
```go
u := AcquireURI()
u.Update("https://github.com%E2%80%8B")

u1, err := url.Parse("https://github.com%E2%80%8B")
if err != nil {
    panic(err)
}
if u1.Host != string(u.Host()) {
   t.Fail()
}
```
Test fails

**Comment by erikdubbelboer** [comment]
I don't think this is a bug. It's just a different way to parse a bad hostname which isn't allowed according to the spec.

`net/url` parses it into `"github.com\u200b"` which is also wrong and unusable.

fasthttp uses the same behavior as `curl`:
```
curl -v 'https://github.com%E2%80%8B'
* Could not resolve host: github.com%E2%80%8B
```

**Comment by moredure** [comment]
Indeed, my fault.
