### ISSUE TITLE
Add function to allow or disallow redirects (fasthttp.Client) and fail with passed error in case of disallow

### ISSUE THREAD

**Issue by moredure** [valyala/fasthttp#988]
smth like
```go
func Allow(req *fashtttp.Request, location []byte) error {
  if bytes.Contains(location, "example.com") {
     return ErrNotAllowed
  }
  return nil
}
```
with ability to access at least `from` and `to` of redirect.

**Comment by erikdubbelboer** [comment]
When you use `Client.Do` it doesn't automatically follow redirects and you can implement this logic yourself.

**Comment by moredure** [comment]
It's more about DoRedirects

**Comment by moredure** [comment]
DRAFT https://github.com/valyala/fasthttp/pull/1000/files
